### ISSUE TITLE
Numpy dependency detection for OpenCV not working

### ISSUE THREAD

**Issue by malcolmreynolds** [Homebrew/homebrew-science#1071]
I just upgraded my numpy installation as I need a feature introduced in 1.9.x. My code using the python OpenCV bindings started failing assertions - reasonable enough as I guess it was compiled against a Numpy in the 1.7.x range.

Anyway when I tried to recompiled opencv via brew I get the problem that it doesn't detect Numpy being installed - it gives me a message saying "this dependency can be installed via pip install numpy" or something. I have numpy installed (from my own git repository) and it's definitely working, I can do import numpy with no problems.

I hacked around this by commenting out the numpy requirement in opencv.rb, but obviously this is an imperfect solution and could really trip someone up. I don't know how the Numpy detection code works (I'm not a ruby guy unfortunately) but it would seem it needs to be made more general, so that it detects Numpy installed from methods other than pip.

**Comment by iml** [comment]
Feel free to reopen if there are any developments.
