### ISSUE TITLE
Tag formula with their academic field

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#1132]
I'd like to be able to tag software with their academic field using a free-form "tag" field added to the formula (see below for an example). I'll open a feature request at Homebrew/homebrew. In the mean time, I'll do as I've been doing with the doi field by adding a comment in the same form (second line below). Thoughts?

``` ruby
tag "bioinformatics"
#tag "bioinformatics"
```

@dpo @iml @samueljohn

**Comment by tseemann** [comment]
The DOI tag doesn't suffer from the ontology problems that the category tag will have.

I am envisaging a "brew cite xxxx" command which uses xxxx.doi to fetch the reference information and print out the paper details and possibly PubMed ID.  This may help software to be cited more!

**Comment by sjackman** [comment]
Yes, absolutely. That's been my plan all along. It simply hasn't come to an implementation. See #781 "Associate DOI with published science software"
