### ISSUE TITLE
Supporting Enhanced Reproducibility for Platforms like Galaxy

### ISSUE THREAD

**Issue by jmchilton** [Homebrew/homebrew-science#1191]
I was told this was the right forum for this conversation - but it is not a bug or feature request per se. The [Galaxy project] (http://galaxyproject.org/) develops an analysis platform focused on reproducibility and to help with that a product called the Tool Shed which includes its own custom package manager. Many people on the Galaxy core development team feel that the package management piece should be augmented to allow Homebrew/linuxbrew based specification and installation of dependencies.

Unfortunately Galaxy has a lot of specific requirements both because it is a platform and because its main focus is reproducibility - and I am pretty sure Homebrew/linuxbrew do not do exactly what is needed. The three biggest potential hurdles or questions that initially rose up when investigating this were:

1) Supporting installing multiple versions of applications at any time - not just the newest. For instance should we salvage and improve the deprecated versions command (seems @chapmanb has had problems with it in CloudBioLinux) or should there exist versioned taps for scientific software?

2) Creating isolated environments - is there a way to grab just what Galaxy needs from the Cellar at runtime for a particular job and not link stuff in globally at install time for instance? Galaxy knows what dependencies it needs for a particular job in the abstract - it would be nice to have a way to just set those up for a particular job - like [Modules](http://modules.sourceforge.net/).

I have jotted some Galaxy-specific thoughts on this issue in our issue tracker [here](https://trello.com/c/YmIBHyxm) and [here](https://trello.com/c/oycD78Cq).

3) How to best handle scripting languages. The current tool shed implementation has nice support for isolated Python, R, Perl, and Ruby environments and it would be great to replicate this in the brew ecosystem - I am not sure whether to rebuild something on top of brew or try to improve brew’s support for these.

If a path like this seems tenable to the Galaxy core development team - the team will happily devote developer resources to achieve these goals - be that maintaining forks of projects like `linuxbrew` and `homebrew-science` or working with the community to push changes we need upstream or help out with new community maintained projects in this ecosystem.

Any advice on these ideas/issues would be most appreciated and if other people have these same concerns we would be eager to talk things out and try to develop a unified approach.

**Comment by jmchilton** [comment]
The response on #1215 makes it clear the maintainers are not interested in supporting older versions of recipes. This is of course reasonable and entirely fair, but nonetheless disappointing - if we wish to do this we will have to create a competing tap.

Thanks for the input all.

**Comment by sjackman** [comment]
I do want to support older versions, but I agree with @tdsmith that the git history is not the best way to accomplish that. I'm afraid that I don't have a better solution to suggest at the moment. If you need this feature immediately, a personal tap is probably the way to go.

**Comment by sjackman** [comment]
Now that we have binary bottles for about 200 Homebrew-Science formula in Linuxbrew, you can install older versions of software from the bottles: http://linuxbrew.bintray.com/bottles-science/ Not a complete solution, but definitely an improvement.

**Comment by brucellino** [comment]
Hi all.

Coming late to the party. In the project I'm working on, we maintain the older versions of the code, but since there is transparent continuous integration, we also maintain the tests (positive and false results). Very similar to what https://github.com/Homebrew/homebrew-science/issues/1231 was talking about I think - we are using Jenkins to do this. 

Applications which pass tests are put into a CVMFS  repository, which is version controlled, similar to, but not the same as git versioning. Future work will have us publish the recipes (which are in git repos) and artifacts (which are in the  CVMFS repo) with persistent identifiers so that we can track usage and citation of the application as well.

**Comment by bgruening** [comment]
@sjackman we were fixing the problem with building Docker images automatically out of brew recipes with this project: https://github.com/mulled/mulled
Unfortunately we all moved on to conda packages and this features is not maintained, it should work through.
If anyone cares to maintain the brew part I would be happy to give a introduction.

**Comment by sjackman** [comment]
Mulled is a great idea. I'm not sure that I can volunteer to maintain the Linuxbrew port myself, but if there's any work I can do in Linuxbrew to better support mulled, I'd be happy to.
