### ISSUE TITLE
OpenCV build errors with gcc-4.9; Compile errors

### ISSUE THREAD

**Issue by Asix3** [Homebrew/homebrew-science#1307]
If I build OpenCV without specifying gcc-4.9, it builds without error. However, when I attempt to compile a simple program, I get the following error:
```
Undefined symbols for architecture x86_64:
  "cv::VideoCapture::open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      initialize_opencv()     in cc85wWaN.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

If I attempt to build OpenCV with gcc-4.9, I get undefined symbol errors for _main.

This program compiles fine on a different machine that has opencv installed via brew.

Gist w/o gcc-4.9:  https://gist.github.com/e54c52bc6ea8697b976f

Gist with gcc-4.9: https://gist.github.com/23f71b101e56e14e37ef

**Comment by iml** [comment]
We don't support building with GCC, sorry. Please ask questions related to programming with OpenCV here: http://answers.opencv.org/questions/
