### ISSUE TITLE
Allpaths-lg fails on OSX 10.10

### ISSUE THREAD

**Issue by kastman** [Homebrew/homebrew-science#1329]
@iml @sjackman Great to see a recipe for ALLPATHS-LG, but I can't get it to compile using homebrew-installed gcc 4.8 or 4.9.

``` bash
 brew install allpaths-lg
 ==> Installing allpaths-lg from homebrew/homebrew-science
 ==> Downloading ftp://ftp.broadinstitute.org/pub/crd/ALLPATHS/Release-LG/latest_
 Already downloaded: /Library/Caches/Homebrew/allpaths-lg-50378.tar.gz
 ==> ./configure --prefix=/usr/local/Cellar/allpaths-lg/50378
 ==> make install
 ./kmers/KmerRecord.h:297:1: note: in expansion of macro 'DEFINE_BYTE_PAC_LESS'
  DEFINE_BYTE_PAC_LESS(10000)
  ^
 make[1]: *** [SupportedHyperBasevector4.o] Error 1
 make: *** [install-recursive] Error 1
```

Build logs are here:  https://gist.github.com/anonymous/6aa276fb7d54724c578d

These logs are from using HOMEBREW_CC=gcc-4.8 but I got the same error with gcc-4.9. I glanced at them and didn't see anything obvious.

Any thoughts on things I could do to further troubleshoot this?

I also tried doing a normal ./configure from within a release directory, but can't seem to figure out an easy way to switch to homebrew's installed gcc instead of the standard OSX Command Line tools. 

Thanks in advance,
Erik

**Comment by iml** [comment]
`gcc47` is available via bottle now but it doesn't build with that either. I don't think this has ever build successfully on Mac. Has anyone reported this upstream?

See also #1975, #1889

**Comment by sjackman** [comment]
Yes, I believe I reported it upstream, but that was some time ago. I don't believe Mac OS is a priority for the upstream authors.

**Comment by tdsmith** [comment]
Should we just slap a LinuxRequirement on this?

**Comment by sjackman** [comment]
Yeah, that's fine by me.

**Comment by tdsmith** [comment]
I'm closing this ticket since we do not believe this package supports building on OS X. Sorry!
