### ISSUE TITLE
 vigra failed to build on 10.10.1

### ISSUE THREAD

**Issue by loranger** [Homebrew/homebrew-science#1406]
It seems I have awaken an [old build error](/Homebrew/homebrew-science/issues/348) using Yosemite
https://gist.github.com/283d4a931cd9242ad146

**Comment by dulaccc** [comment]
I can confirm that it's working for me too with the `gcc-4.9` compiler !

**Comment by dpo** [comment]
Closing this. Please feel free to reopen if you're still experiencing problems.

**Comment by shrx** [comment]
Builds with `brew install vigra --cc=gcc-5` but issues a warning:
```
Warning: homebrew/science/vigra dependency libtiff was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
```
