### ISSUE TITLE
opencv doesn't include any python bindings

### ISSUE THREAD

**Issue by peterbe** [Homebrew/homebrew-science#1418]
When I do `brew install opencv` (on OSX 10.10.1, brew version 0.9.5) it installs fine but no Python bindings are installed anywhere. 

I was expecting a cv2.py and a cv.so file being created somewhere but it's not. Not anywhere.

**Comment by iml** [comment]
The new version in 317ca9f565dad46af7faf2f41b8574c1c2de168d now builds against Homebrew's NumPy.
