### ISSUE TITLE
latest blastdbcmd -help segfaults

### ISSUE THREAD

**Issue by yeban** [Homebrew/homebrew-science#1438]
This is on OSX Yosemite 10.10.1. Installed BLAST 2.2.30 by: `brew upgrade blast`.

**Comment by iml** [comment]
Looks like this was fixed by https://github.com/Homebrew/homebrew-science/commit/f03bf54deb73c135e1458fce896f9bdc9ee49fd7.

**Comment by yeban** [comment]
Working for me now. Thanks.

**Comment by sjackman** [comment]
Thanks @dunn and @iml.
