### ISSUE TITLE
Removing old hdf5 

### ISSUE THREAD

**Issue by ChrisBail** [Homebrew/homebrew-science#1443]
Hi,

I just had some issues installing hdf5. 
When doing "brew install hdf5" the url was not uptodate, I had to to "brew install homebrew/science/hdf5"
How can I upgrade the standard formulas so I don't need to specify the "homebrew/science" path?

Thanks,

Christian

**Comment by dpo** [comment]
@ChrisBail Any news?

**Comment by ChrisBail** [comment]
Yes it worked at the end, thanks dpo!
