### ISSUE TITLE
octave: Building with an alternative Fortran compiler

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#1476]
Installing Octave results its some noisy and contradictory messages. It says `Using Homebrew-provided fortran compiler.` and then after `Building with an alternative Fortran compiler`, which it warns three times (see below). The `FC` environment variable is not set.

**Comment by iml** [comment]
This is a dupe of https://github.com/Homebrew/homebrew/issues/31156, which should be fixed eventually by the dependency rewrite @jacknagel. We could break out early if `FC` is set to Homebrew gfortran, which would be less confusing to users. But that's more of an ugly hack than a proper fix. e.g.
```diff
diff --git a/Library/Homebrew/extend/ENV/shared.rb b/Library/Homebrew/extend/ENV/shared.rb
--- a/Library/Homebrew/extend/ENV/shared.rb
+++ b/Library/Homebrew/extend/ENV/shared.rb
@@ -157,6 +157,7 @@ module SharedEnvExtension
     flags = []
 
     if fc
+      return if fc = which("gfortran", (HOMEBREW_PREFIX/"bin").to_s)
       ohai "Building with an alternative Fortran compiler"
       puts "This is unsupported."
       self['F77'] ||= fc
```

**Comment by dpo** [comment]
I suggest we close this as it's a core issue.

**Comment by sjackman** [comment]
Dupe of https://github.com/Homebrew/homebrew/issues/31156
