### ISSUE TITLE
Opencv cuda broken with CUDA 6.5

### ISSUE THREAD

**Issue by bafonso** [Homebrew/homebrew-science#1500]
I am unable to compile it with cuda support. It does compile, but not with cuda support. If you look at the log, it appears it cannot find the cuda required libs and then keeps on compiling with support.

I'm on mavericks.

**Comment by bafonso** [comment]
No, looks like I may have interrupted it half way through? My bad. 

I just updated and tried to compile again. Only option is --with-cuda

https://gist.github.com/99e0b33b494913ba4dbb

As you can see, the cmake switches to NO with the CUDA option but I don't even see it trying to find the nvidia cuda libraries.

**Comment by iml** [comment]
Assuming this was resolved by https://github.com/Homebrew/homebrew-science/commit/98e9515758bb86416476604d43e3d286a07f37f9?
