### ISSUE TITLE
Problem installing LAMMPS with homebrew [Need Help Urgently] 

### ISSUE THREAD

**Issue by sahar2011** [Homebrew/homebrew-science#1517]
I am trying to install LAMMPS with the instructions written here: 
http://lammps.sandia.gov/download.html#homebrew
for MAC OS and I keep getting a fail message. I have already tried the serial then uninstall then the parallel version but when I test I keep getting the following message:  
Help me please ... *_* ...  
Regards, 
Sahar 
% ===========

```
brew test lammps -v
Testing lammps
==> lammps -in /usr/local/share/lammps/bench/in.lj
LAMMPS (12 Feb 2014)
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (33.5919 33.5919 33.5919)
  1 by 1 by 1 MPI processor grid
Created 32000 atoms
Setting up run ...
Memory usage per processor = 13.2266 Mbytes
Step Temp E_pair E_mol TotEng Press 
       0         1.44   -6.7733681            0   -4.6134356   -5.0197073 
     100    0.7574531   -5.7585055            0   -4.6223613   0.20726105 
Loop time of 1.93075 on 1 procs for 100 steps with 32000 atoms

Pair  time (%) = 1.65166 (85.5449)
Neigh time (%) = 0.220561 (11.4236)
Comm  time (%) = 0.0193527 (1.00234)
Outpt time (%) = 0.000102997 (0.00533456)
Other time (%) = 0.0390749 (2.02382)

Nlocal:    32000 ave 32000 max 32000 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Nghost:    19657 ave 19657 max 19657 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Neighs:    1.20283e+06 ave 1.20283e+06 max 1.20283e+06 min
Histogram: 1 0 0 0 0 0 0 0 0 0

Total # of neighbors = 1202833
Ave neighs/atom = 37.5885
Neighbor list builds = 5
Dangerous builds = 0
==> python -c from lammps import lammps ; lammps().file('/usr/local/share/lammps/bench/in.lj')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lammps
Error: lammps: failed
Failed executing: python -c from\ lammps\ import\ lammps\ ;\ lammps().file('/usr/local/share/lammps/bench/in.lj')
/usr/local/Library/Homebrew/formula.rb:644:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb:210:in `block (2 levels) in <class:Lammps>'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb:208:in `block in <class:Lammps>'
/usr/local/Library/Homebrew/formula.rb:562:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:560:in `run_test'
/usr/local/Library/Homebrew/cmd/test.rb:59:in `block (2 levels) in test'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/cmd/test.rb:58:in `block in test'
/usr/local/Library/Homebrew/cmd/test.rb:37:in `each'
/usr/local/Library/Homebrew/cmd/test.rb:37:in `test'
/usr/local/Library/brew.rb:136:in `<main>'
kl-14050:~ amirsz$ 
 ```

**Comment by dpo** [comment]
@sahar2011 Has this been resolved?

**Comment by sahar2011** [comment]
No ... 
I tried everything you said until now and also some other solutions I found online but nothing worked ??

**Comment by dpo** [comment]
Please post the output of the following commands
````
which python
echo $PYTHONPATH
pyver=$(python -c 'import sys; print sys.version[:3]'); echo $pyver
ls -l /usr/local/lib/python$pyver/site-packages
````

**Comment by sahar2011** [comment]
It gives the following: 
kl-14050:~ pc$ which python
/usr/bin/python
kl-14050:~ pc$ echo $PYTHONPATH

kl-14050:~ pc$ pyver=$(python -c 'import sys; print sys.version[:3]'); echo $pyver
2.7
kl-14050:~ pc$ ls -l /usr/local/lib/python$pyver/site-packages
ls: /usr/local/lib/python2.7/site-packages: No such file or directory
kl-14050:~ pc$

**Comment by dpo** [comment]
Did you add `/usr/local/bin` to your `PATH`? You need to add `export PATH=/usr/local/bin:$PATH` to your `~/.bashrc` and open a new terminal. Then try `brew test lammps`. If it still doesn't work, you might have to reinstall `lammps`.

**Comment by dpo** [comment]
@sahar2011 I'm going to close this as it seems to be a path issue. If the above doesn't do it for you, please reopen.

**Comment by jdv25** [comment]
Hi, I have recently tried installing lammps on my Mac running OS 10.12.3 using home-brew. It seems that I am dealing with the same issue as above. I originally tried a normal installation using "`brew install lammps --without-mpi`". That did not work. I recently tried doing "`brew uninstall $(brew deps lammps); brew install lammps --without-mpi`". This gave the same error mentioned above. `16 errors generated.
make[1]: *** [dump_atom_mpiio.o] Error 1
make: *** [mac] Error 2
`
When trying to do brew test lammps, I got the following output to the terminal:
Last 15 lines from /Users/apple/Library/Logs/Homebrew/lammps/test.01.lammps:
2017-02-09 13:10:41 -0500

/usr/local/Cellar/lammps/2016.11.17/bin/lammps
-in
/usr/local/share/lammps/bench/in.lj

dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib
  Referenced from: /usr/local/Cellar/lammps/2016.11.17/bin/lammps
  Reason: image not found

I attached the link the the output of brew gist-logs lammps here:
https://gist.github.com/bb6cefb0b68147a4ab48d35fd2d4dd5f

Any help with this would be greatly appreciated.
