### ISSUE TITLE
Formula that fails_with :clang and depends on C++ library built with clang fail

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#1593]
# Affected formula

Formula | Dependency | Issue
---|---|---
abyss | google-sparsehash | #2332
amos | boost | #485
augustus | boost | #1373
blasr | hdf5 | #2415
bless | google-sparsehash | #1839
diamond | boost | #1909
garli | ncl | #1538
htqc | boost | #1595
meraculous | boost | #1695
mira | boost | #1148
quorum | jellyfish | #1661
sailfish | boost | #1555

**Comment by sjackman** [comment]
@Homebrew/owners These formula fail to build with clang, and so are built with GCC by default, but they have C++ dependencies (libraries) that are built with clang by default. These formula then get link errors and fail to build. Is there a solution to this issue?

**Comment by mikemcquaid** [comment]
Given what you've said: I don't think so, no.

**Comment by sjackman** [comment]
Has this issue not come up in Homebrew/homebrew?

**Comment by mistydemeo** [comment]
We have a policy of no longer accepting software that doesn't build with clang.

**Comment by mikemcquaid** [comment]
At this point software that doesn't build with `clang` can't really be considered to be ported to OSX.

**Comment by sjackman** [comment]
Hmm. There's too much important scientific software that doesn't build with `clang` out of the box to adopt that same policy in Homebrew/science, I don't have the time to port it myself. How would you feel about Homebrew/science packaging a `keg_only` version of boost `boost-gcc` that is built with GCC? I don't think it's a great solution, but it's an option.

**Comment by mikemcquaid** [comment]
@sjackman If you do that for one package you're going to end up doing it for a bunch. I think it's a bad call, personally. As I said previously: if stuff doesn't work with `clang` (let alone `libc++`) it can't really be considered to be working on OS X. If you can workaround that within a formula or it can build with `gcc` and still link OK that makes sense otherwise I'd just leave it (or put it in a `homebrew-science-gcc` tap)

**Comment by sjackman** [comment]
This issue is resolved now that `/usr/bin/clang` and `gcc-5` are ABI compatible on recent versions of Mac OS.

**Comment by mikemcquaid** [comment]
> This issue is resolved now that /usr/bin/clang and gcc-5 are ABI compatible on recent versions of Mac OS.

@sjackman Does that mean the standard library checks are no longer needed as-of GCC-5 and recent Clangs? Thanks!

**Comment by sjackman** [comment]
I don't know the answer to that question off the top of my head. Do you know which C++ library is used by default by `clang` and `gcc-5`, and do you know whether the two C++ libraries are ABI compatible?

**Comment by mikemcquaid** [comment]
> Do you know which C++ library is used by default by clang and gcc-5

`libstdc++` and `libc++`



> do you know whether the two C++ libraries are ABI compatible?

No idea 😥

**Comment by sjackman** [comment]
http://libcxx.llvm.org

> ABI compatibility with gcc's libstdc++ for some low-level features such as exception objects, rtti and memory allocation.

So looks like it's best-effort ABI compatibility. I think that this compatibility is due to the `libc++abi` library http://libcxxabi.llvm.org although that page doesn't mention `libstdc++` at all, but does mention `On Mac OS X, be ABI compatible with the existing low-level support.`, which may be a reference to `libstdc++` compatibility. There are a few StackOverflow questions and answers stating `Although they are API compatible, they are not ABI compatible.`, and that was my understanding, but perhaps this situation has changed recently.
