### ISSUE TITLE
Use BrewTestBot CI with Linuxbrew

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#1605]
Using either Jenkins, Travis or Circle CI.

**Comment by sjackman** [comment]
I meant to open this issue at Homebrew/linuxbrew. Woops.

**Comment by saketkc** [comment]
On that note, how about a similar `.travis.yml` for `homebrew-science` too?

**Comment by sjackman** [comment]
Yes, absolutely. I'd like to use Standalone Linuxbrew to build bottles ideally, but just checking that the formula builds on Linux is worthwhile.

**Comment by sjackman** [comment]
Done! Travis CI is now enabled for Homebrew/science! It seems to have disabled Jenkins though.

**Comment by saketkc** [comment]
Awesome! But I can see it waiting for the build bot results: https://github.com/Homebrew/homebrew-science/pull/1610
![bwa 0 7 11 remove require formula by sjackman pull request 1610 homebrew homebrew science](https://cloud.githubusercontent.com/assets/682153/5593813/d0150dee-91dd-11e4-9155-6a646c6dcc81.png)

**Comment by sjackman** [comment]
Woot!

**Comment by sjackman** [comment]
We'll have to apt-get install the dependencies for Linuxbrew. It's going to slow down the builds if we have to reinstall everything every time, so I'd like to use the Travis [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/). See [Caching Dependencies and Directories](http://docs.travis-ci.com/user/caching/). Unfortunately…
> The features described here are currently only available for private repositories on travis-ci.com and our new container-based infrastructure.

**Comment by dpo** [comment]
That's fantastic @sjackman! Many thanks for setting this up!

**Comment by dpo** [comment]
Travis is currently showing a failure related to Java not being installed. Here are the affected formulae:
- [ ] `abyss-explorer`: should have a `:java` dependency but doesn't
- [ ] `nextflow`
- [ ] `octave`: Java recommended
- [ ] `opencv`: Java optional
- [ ] `openni2`: Java optional to build the docs
- [ ] `picard-tools`: needs Java for the test, but no `:java` dependency
- [ ] `rampart`
- [ ] `simpleitk`: Java optional
- [ ] `trinity`.

In some of those, `:java` could simply be made `:optional` in the same way `:tex` was recently made `:optional` in `octave`. Those that have a hard Java dependency could be excluded from the build.

**Comment by saketkc** [comment]
Or we could do a system install of `java` on `travis`?

**Comment by sjackman** [comment]
Yes, switched on Java in 91353aa53e9c8663c7051387f166d651beccae0f.

**Comment by sjackman** [comment]
Note that `depends_on :java` is broken in Linuxbrew. Pull requests welcome.

```
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
$ brew install nextflow
==> Installing nextflow from homebrew/homebrew-science
nextflow: Java 1.7 is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/java

You can download from:
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
```

**Comment by dpo** [comment]
Any chance we could convince the Travis guys to install LinuxBrew on their Linux machines in the same way they install Homebrew on OSX machines?

**Comment by saketkc** [comment]
As for the Linuxbrew thing it is indeed going to be very sloow, but there are other bottlenecks as well: Keeping the verbose output from exceeding 4MB limit  and preventing the from build timing out if there is no output for some 10 minutes or so. Verbose mode for `brew` would exceed the 4MB limit of logs and hence this particular bash file handles that: https://github.com/saketkc/linuxbrew/commit/0aa886cdd20659ac185c5855fd0c990b5ecbeafd

**Comment by sjackman** [comment]
@dpo Wouldn't that be something! Their [new stack uses Docker](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), so it's not that crazy, really.

**Comment by dpo** [comment]
@saketkc The bash script you recommend is crucial, especially for anything that will want to build `gcc`!

**Comment by sjackman** [comment]
I'd rather incorporate the functionality of that shell script (outputting a periodic status update to prevent time out) into `brew test-bot` [in `run` around line 124](https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/cmd/test-bot.rb#L124).
