### ISSUE TITLE
Re-enable BrewTestBot for Homebrew/science

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#1611]
Hi, Mike. I've set up Travis CI for building Homebrew/science formula on Linuxbrew. I'm pretty excited about this. The BrewTestBot service seems to have been lost though. I didn't remove it manually, so I guess that Travis removed it for me, which seems rather unfriendly. Could you please re-enable it? Sorry for the hassle, and I appreciate your help. I'm super happy to have BrewTestBot building Homebrew/science bottles for us. I went on a sprint the last couple days and bottled over fifty bioinformatics formula.

**Comment by sjackman** [comment]
#1610 is an example of a PR that built on Travis, but wasn't tested on BrewTestBot.

**Comment by sjackman** [comment]
False alarm! There was just a delay after Travis had finished and before BrewTestBot kicked in. Yeah!

**Comment by mikemcquaid** [comment]
> I went on a sprint the last couple days and bottled over fifty bioinformatics formula.

Yeh, I noticed this a bit. Please keep an eye on the queue just to make sure the bot doesn't get too overloaded. Glad it's proving useful for you, though.

**Comment by dpo** [comment]
@sjackman We might be able to send every pull request (as opposed to the entire repo) to Travis on OSX, and only forward the job to the brew bot once it compiles correctly. That might lighten the load.
