### ISSUE TITLE
garli installation error

### ISSUE THREAD

**Issue by jrherr** [Homebrew/homebrew-science#1620]
the garli installation breaks for me:
```
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [Garli] Error 1
make: *** [install-recursive] Error 1
```

It installs from source -- I'm looking into it, but don't have much time today...

**Comment by iml** [comment]
We'll need the full logs but this is probably related to #1593, which requires `ncl` to be built with `--cc=gcc-4.9`.

**Comment by sjackman** [comment]
```sh
brew remove ncl garli
brew install ncl garli --cc=gcc-4.9
```
