### ISSUE TITLE
fgsl for intel compiler

### ISSUE THREAD

**Issue by hyuna917** [Homebrew/homebrew-science#1623]
First of all, I’m really appreciated for making this formula, to @tschoonj, @BrewTestBot. 
I use it when I compile something by gfortran. 
And, I try to use it by intel compiler. But, I can’t find intel compiled mod file. 
How to use it by intel compiler?

**Comment by dpo** [comment]
I've never tried but you might be able to do it with `FC=ifort brew install fgsl`.

**Comment by hyuna917** [comment]
thanks for reply :) 
I’ve tried it, now. But it doesn’t work for me. ;(

**Comment by dpo** [comment]
What isn't working exactly? Could you gist the output of `FC=ifort brew install fgsl`?

**Comment by hyuna917** [comment]
Remove fgsl: 
$ brew remove fgsl
Uninstalling /usr/local/Cellar/fgsl/1.0.0⋯

Reinstall fgsl with FC=ifort option: 
$ FC=ifort brew install fgsl
==> Installing fgsl from homebrew/homebrew-science
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/science/fgs
Already downloaded: /Library/Caches/Homebrew/fgsl-1.0.0.yosemite.bottle.tar.gz
==> Pouring fgsl-1.0.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/fgsl/1.0.0: 935 files, 18M

For test, compile example file with ifort: (sum.f90 is example file)
$ ifort -I/usr/local/include/fgsl sum.f90 -lfgsl
sum.f90(2): error #7013: This module file was not generated by any release of this compiler.   [FGSL]
  use fgsl

try to do the same thing with gfortran: (It succeed to compile) 
$ gfortran -I/usr/local/include/fgsl sum.f90 -lfgsl

**Comment by dpo** [comment]
That's because if you want to use an alternative compiler, you have to build from source. The bottle was compiled with gfortran. Try: `FC=ifort brew install fgsl --build-from-source`.

**Comment by hyuna917** [comment]
It works! thanks, @dpo! 
Is there another way to use both of them? 
I use ifort mainly, but sometimes use gfortran either.

**Comment by dpo** [comment]
I'm not sure what you mean by "use both of them". Every time you want to compile something with `ifort`, you can use `FC=ifort brew install --build-from-source <formula>`. If you don't specify `FC`, then gfortran is used by default. If you always want to compile from source, you can set `export HOMEBREW_BUILD_FROM_SOURCE=1` in your `~/.bashrc`.

**Comment by hyuna917** [comment]
I mean, everytime I want to use fgsl with ifort, I should reinstall fgsl. 
So, if I could have both of version, one is installed with gfortran, another is installed with ifort, I don't have to reinstall fgsl, like lapack that can use with gfortran and ifort. 

I'm afraid about my english. ;( 
Sorry about that.

**Comment by dpo** [comment]
Yes, unfortunately, there currently isn't a way to keep different versions of the same package built with different compilers.

**Comment by hyuna917** [comment]
Oh, I see. 
Thanks for replying. :) 
It was really useful.
