### ISSUE TITLE
OpenCV installation fails to compile

### ISSUE THREAD

**Issue by rupulsafaya** [Homebrew/homebrew-science#1638]
Hi all, 

When trying to install OpenCV, I am coming across the following compile errors. My brew --config is below.

brew install opencv 
==> Installing opencv from homebrew/homebrew-science
==> Downloading https://github.com/Itseez/opencv/archive/2.4.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv-2.4.9.tar.gz
==> Patching
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv/2.4.9 -DCMAKE_BUILD_TYPE=None -DCM
==> make
/tmp/opencv-WdmC0S/opencv-2.4.9/modules/python/src2/cv2.cpp:389: error: expected initializer before ‘*’ token
/tmp/opencv-WdmC0S/opencv-2.4.9/modules/python/src2/cv2.cpp:1125: error: expected declaration before end of line
make[2]: *** [modules/python/CMakeFiles/opencv_python.dir/src2/cv2.cpp.o] Error 1
make[1]: *** [modules/python/CMakeFiles/opencv_python.dir/all] Error 2
make: *** [all] Error 2
----------------------------------------------
 brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.6.8-i386
Xcode: 3.2.6
CLT: N/A
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2335
Clang: 1.7 build 77
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby

**Comment by dpo** [comment]
Please post the output of `brew gist-logs opencv`.

**Comment by rupulsafaya** [comment]
Here is the gist-log: https://gist.github.com/anonymous/90c97c59e0470348f993

**Comment by rupulsafaya** [comment]
Right. 

I had installed Python from their website, via an installer. I installed it via Homebrew and then installed OpenCV and it worked.

Thanks for your help.

**Comment by Whinza** [comment]
No rule to make target `/usr/lib/libpython2.7.a', needed by `lib/cv2.so'.  Stop.

This is what I get after 3 hours
