### ISSUE TITLE
Problem with maxima 5.34.1 and wxMaxima 13.04 - gnuplot not executed

### ISSUE THREAD

**Issue by github4uw** [Homebrew/homebrew-science#1647]
I installed maxima, gnuplot and wxmaxima. (actually my first install using homebrew)
First time with brew install <package>
Second time I build everything from source with brew install --build-from-source <package> which did not help. Before I also installed aquaterm-1.1.1.

When using wxMaxima I expect that the following test plots the graphics right into wxMaxima. But I get the following error:
(%i1) plot2d(sin(x),[x,0,5]);
"Maxima encountered a Lisp error:
 Couldn't execute "gnuplot": No such file or directory
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil."

I tried the same with maxima in a terminal which gives: 
(%i1) plot2d(sin(x),[x,0,5]);
(%o1)               [/Users/biophoton/maxout.gnuplot_pipes]
But again gnuplot is not invoked only the data is written to home dir.
However, gnuplot is installed and the path is known in the terminal. So I think the error message above does not address the problem. I suppose there is a bug in the code for maxima (and rmaxima) and plot2d (and may be other functions) do not search for gnuplot at all. Maybe due to a lisp error.
(Doing the same on a ubuntu system shows the expected result. gnuplot is called and shows the graphic in a separate window.) 

I tried the same with Xmaxima in a terminal:
Wish opens and in the Xmaxima: console I entered 
(%i1) plot2d(sin(x),[x,0,5]);
Surprisingly here the graphics is plotted into the terminal or in a separate window (dep. on settings).
This shows the gnuplot is working and can be called. 

Please let me know of you need further information or how I could help. 
I really want to use wxMaxima and Maxima from the homebrew project.

Best regards

**Comment by github4uw** [comment]
Edit: I also tried: 
(%i1) wxplot2d([sin(x)], [x,-5,5],
 [gnuplot_preamble, "set zeroaxis;"])$
"/bin/sh: gnuplot: command not found" 

(%i1) wxplot2d([sin(x)], [x,-5,5]);Maxima encountered a Lisp error:
"Couldn't execute "gnuplot": No such file or directory
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil."

**Comment by iml** [comment]
Might need to set the variable. See https://www.ma.utexas.edu/pipermail/maxima/2006/000413.html
```
gnuplot_command : sconcat("/usr/local/bin/gnuplot")$
wxplot2d(sin(x),[x,0,5]);

**Comment by github4uw** [comment]
This partly solves the problem.
I found a similar solution here http://pangea.stanford.edu/~schmitt/maxima.html (see step 15).
But when I create the maxima-init.mac file putting in gnuplot_command : sconcat("/usr/local/bin/gnuplot")$ then wxMaxima cannot connect to maxima at startup anymore.
What can I do the wxMaxima first connects and then executes the gnuplot_command?
A working init-script would make things much easier ;-)

**Comment by iml** [comment]
I added some caveats to the formula based on that page. It doesn't seem to be necessary to set the gnuplot terminal, at least with wxplot, but the `draw_command` may not be needed either.
