### ISSUE TITLE
SHA1 mismatch while building Hypre as a dependency of PETSc

### ISSUE THREAD

**Issue by mw8** [Homebrew/homebrew-science#1652]
==> Downloading http://computation.llnl.gov/casc/hypre/download/hypre-2.9.0b.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: aaf8354437be38aa2fbcc944ab64d464a5b39207
Actual: bd7ca57e45badf322b9c9cb970403c191287da72
Archive: /Library/Caches/Homebrew/hypre-2.9.0b.tar.gz

**Comment by saketkc** [comment]
[It no longer is available for download without registration](https://computation.llnl.gov/project/linear_solvers/download/hypre-2.9.0b_reg.php). The tarball is not even a valid tarball.
```
$:~/.cache/Homebrew$ tar -zxvf hypre-2.9.0b.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by iml** [comment]
That's a bit silly for GPL software, from a government lab.
