### ISSUE TITLE
qgis error refers to nonexistent information

### ISSUE THREAD

**Issue by poggs** [Homebrew/homebrew-science#1682]
When installing qgis, the following message appears:

==> Installing qgis from homebrew/homebrew-science
qgis: Python could not import the PyQt4 module. This will cause the QGIS build to fail.
The most common reason for this failure is that the PYTHONPATH needs to be adjusted.
The pyqt caveats explain this adjustment and may be reviewed using:

```
brew info pyqt
```

However, 'brew info pyqt' does not explain this adjustment:

piccadilly:~ pwh$ brew info pyqt
pyqt: stable 4.11.1 (bottled)
http://www.riverbankcomputing.co.uk/software/pyqt
/usr/local/Cellar/pyqt/4.11.1 (560 files, 19M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pyqt.rb
==> Dependencies
Required: qt ✔, sip ✔
==> Options
--with-python3
    Build with python3 support
--without-python
    Build without python 2 support
==> Caveats
Phonon support is broken.
piccadilly:~ pwh$

**Comment by pensato** [comment]
I had that problem. Adding 
`export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"`
to my ~/.bash_profile fixed it. Hope that helps!

**Comment by iMichka** [comment]
`qgis` was removed from `homebrew-science` with #4688. Closing.
