### ISSUE TITLE
brew install opencv error

### ISSUE THREAD

**Issue by yogaliew** [Homebrew/homebrew-science#1698]
Error: /usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:135: syntax error, unexpected end-of-input, expecting keyword_end
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:127:in `gist_logs'
/usr/local/Library/brew.rb:135:in `<main>'

I used $ brew tap homebrew/science but the error is still there.
Help me!
Thanks in advance

**Comment by dpo** [comment]
There is no line 135 in `opencv.rb`. Perhaps you have an old version lying around that you modified at some point? Try `brew untap homebrew/science; brew update; brew tap homebrew/science`.

**Comment by yogaliew** [comment]
Oh Thanks! It works. But unfortunately, there is another error coming up:
opencv: Unsatisfied dependency: numpy
Homebrew does not provide Python dependencies; install with:
  pip install numpy
Error: An unsatisfied requirement failed this build.

**Comment by dpo** [comment]
You can either install Python dependencies with `pip install numpy` (`pip` was installed when you installed `python`), or you can `brew tap homebrew/python; brew install numpy`.
