### ISSUE TITLE
Can't install octave as qhull.org appears to be down.

### ISSUE THREAD

**Issue by juancarlosfarah** [Homebrew/homebrew-science#1705]
$ brew install octave
    ==> Installing octave from homebrew/homebrew-science
    ==> Installing dependencies for octave: qhull, qrupdate, epstool, jbig2de
    ==> Installing octave dependency: qhull
    ==> Downloading http://www.qhull.org/download/qhull-2012.1-src.tgz

    curl: (6) Could not resolve host: www.qhull.org
    Error: Failed to download resource "qhull"
    Download failed: http://www.qhull.org/download/qhull-2012.1-src.tgz

**Comment by iml** [comment]
Seems to work now but I added a mirror in bab4f4527d4ee714f8ac5479096b6c0d2a2031ef.

**Comment by juancarlosfarah** [comment]
Thanks @iml !
