### ISSUE TITLE
Cannot install McSpatial R package due to error in _libintl_dgettext

### ISSUE THREAD

**Issue by EconGeo** [Homebrew/homebrew-science#1711]
I have tried everything I can think of and am at a loss figuring out this error when attempting to install McSpatial in R

```
 * installing *source* package ‘McSpatial’ ...
** package ‘McSpatial’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/bluebird/Library/R/3.1/library/foreign/libs/foreign.so':
  dlopen(/Users/bluebird/Library/R/3.1/library/foreign/libs/foreign.so, 6): Symbol not found: _libintl_dgettext
  Referenced from: /Users/bluebird/Library/R/3.1/library/foreign/libs/foreign.so
  Expected in: /usr/local/Cellar/r/3.1.2_1/R.framework/Versions/3.1/Resources/lib/libR.dylib
 in /Users/bluebird/Library/R/3.1/library/foreign/libs/foreign.so
Error : package ‘maptools’ could not be loaded
ERROR: lazy loading failed for package ‘McSpatial’
* removing ‘/Users/bluebird/Library/R/3.1/library/McSpatial’
* restoring previous ‘/Users/bluebird/Library/R/3.1/library/McSpatial’ 
```

The package ```foreign``` is installed with the initial R build in homebrew and is part of the base R installation, so I'm wondering if this is an R installation issue.  Reinstallation of ```gccc``` and ```r``` with homebrew execute without issue.  Does anyone have any guidance on where I might look to get this working?  I know there have been issues with ```gettext``` in homebrew in the past.  I'm wondering if the r formula does not point to the homebrew installed ```gettext``` when installing?

**Comment by EconGeo** [comment]
apparently an un-installation of all my local packages and reinstall solved the issue

**Comment by dpo** [comment]
Are you using Homebrew R? I don't have a `~/Library/R` folder. In another post, you were using a different precompiled version of R. Is that still lying around?

**Comment by EconGeo** [comment]
I'm using Homebrew R.  I uninstalled the pre compiled version using command line and am attempting to get the hombrew R to work.  The default setting for installing packages in R is ```User/<user>/Library/R/<version>/library/``` which is the "user" directory, unless you tell your gui you want it stored in the system directory, in which case it would be stored in the ```Cellar``` address.  Any ideas?

**Comment by dpo** [comment]
I'm not a user of R, so I'm really not sure. You added a comment saying that reinstalling resolved the issue and you later removed that comment. Could you perhaps elaborate on what made you reconsider?

**Comment by EconGeo** [comment]
I just did ``` brew rm gcc && brew install gcc --with-all-languages && brew reinstall r ```
i still get the same error when attempting to update ```foreign``` from version 0.8-61 to 0.8-62 but the one installed by the build seems to not throw errors for installing other packages anymore.

**Comment by dpo** [comment]
I recall in a previous conversation you said `r` had to be installed with `gcc` in order to build other packages. So you would need to do `brew install r --cc=gcc-4.9`.

**Comment by EconGeo** [comment]
That is true.  I checked and ```brew install r``` is pointing to homebrew ```gcc``` .   Thanks for your help
