### ISSUE TITLE
gfortran dylib not found when trying to run octave

### ISSUE THREAD

**Issue by ma2rten** [Homebrew/homebrew-science#1727]
When I try to run octave I get this error message:

    $ octave
    dyld: Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
      Referenced from: /usr/local/Cellar/octave/3.8.1_1/bin/octave-cli-3.8.1
      Reason: image not found
    Trace/BPT trap: 5

As suggested in a previous issue, I tried ```brew reinstall qrupdate``` and I even tried ```brew reinstall $(brew deps octave)```, but without avail.

**Comment by ma2rten** [comment]
I was able to fix the problem myself. In case other people run into the same problem:

    $ brew doctor
    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:

    gcc

so I did

    $ brew unlink gfortran
    $ brew link gcc

And it worked.

**Comment by suczako** [comment]
I had similar issue on OS X after upgrade to => Yosemite and then => El Capitan and then => Sierra---always the same ;)---but non of solutions above worked. Each time I solved it with command: 

$ brew reinstall octave --with-java
