### ISSUE TITLE
R bottle doesn't install libRlapack.dylib

### ISSUE THREAD

**Issue by EconGeo** [Homebrew/homebrew-science#1733]
Bottled version of R does not install 
```/Library/Frameworks/R.framework/Versions/3.1/Resources/lib/libRlapack.dylib ```
which causes problems when trying to install packages in R, since so many packages depend on lapack.  Messing around with this for some time, trying to build with ```cc=gcc-4.9``` fails, etc. I also discovered that ``/Library/Frameworks/R.framework``` is empty instead of being symlinked to the homebrew folder.  Is this by design, I thought it would be symlinked?  Any idea how we can get R to build like the binary from CRAN that has ```libRlapack``` installed?

**Comment by dpo** [comment]
`libR.dylib` is linked against the Accelerate framework, which is what the bottle provides. If you want `libRlapack`, I believe you must build from source `--without-accelerate`. Homebrew doesn't link anything to `/Library/Frameworks`. Instead, the frameworks are in `/usr/local/Frameworks`.

**Comment by EconGeo** [comment]
hmmm, insteresting.  I searched for libRlapack on my machine and i get a hit as the makefile for R which says that libRlapack is the defualt.  lapack is a subroutine of accelerate without a doubt.  This was installed last time I had the CRAN version installed (yesterday) on my mac.  Hence why I think it is not building correctly with the bottle.

**Comment by EconGeo** [comment]
I'm not familiar with Ruby.  How do I pass extra options to the configure script?  According to this
http://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#Which-BLAS-is-used-and-how-can-it-be-changed_003f
I want to pass the option ```--enable-BLAS-shlib ``` to the configure script and link it to R BLAS which I think is what is causing the problems building packages that require lapack.

**Comment by dpo** [comment]
`brew install r --without-accelerate` builds Rblas.

**Comment by EconGeo** [comment]
OK, great.  Thanks!

**Comment by iml** [comment]
You probably have to add C99 or C11 switch to the GCC invocation in `~/.R/Makevars`. This isn't an issue with the default, supported build with clang.

**Comment by EconGeo** [comment]
would that be with ```CC=gcc-49 -std=g99``` ?

**Comment by EconGeo** [comment]
That did it!  Thank you so much!!!

**Comment by dpo** [comment]
For the record, did you install with `brew install r --without-accelerate --cc=gcc-4.9`?

**Comment by EconGeo** [comment]
no, I tried that and it failed to build.  i installed with ```brew install r --with-openblas```.  All of my package problems were taken care of changing the ```~/.R/Makevars``` file.

**Comment by dpo** [comment]
Ok thanks.

**Comment by zmjones** [comment]
do you still get this message when running `brew install r with-openblas`?

```
==> Installing r from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.
```

**Comment by dpo** [comment]
See Homebrew/homebrew#31156

**Comment by EconGeo** [comment]
Yes I do.

**Comment by zmjones** [comment]
`RCurl` fails to install for me with the openblas build but works fine with the CRAN binary

**Comment by EconGeo** [comment]
Did you change the ```~/.R/Makevars``` file?  I was able to build packages I was having trouble with using both ```CC=gcc -std=gnu99``` and ```CC=clang```.  I guess since R is built with clang with the ```brew install r --with-openblas``` installed it makes sense to build the other packages using the same C compiler

**Comment by EconGeo** [comment]
I just tried ```RCurl```, it built with a few errors using ```clang``` but was still loadable,  and built with no errors using the ```gcc``` option.

**Comment by zmjones** [comment]
I just tried again with `brew install r --with-openblas` and `~/.R/Makevars`: `CC=gcc -std=gnu99` and doesn't look like anything changed

**Comment by EconGeo** [comment]
nope, see above.  It's ```CC=gcc-4.9 -std=gnu99```   gcc points to clang.  gcc-49 points to GNU

**Comment by zmjones** [comment]
had used that before, same error. just did it again to verify. now that i look at it it may be due to a conflict with anaconda.

**Comment by EconGeo** [comment]
I don't know.  What does anaconda do in relation to R?  Are you on 10.10 or 10.9?

**Comment by zmjones** [comment]
10.10. I thought it just lived nicely on its own in my home folder but apparently not. I've killed the buffer now but I saw gcc doing some stuff in there whilst installing `RCurl` which was strange, and the error was some sort of library linking problem.

**Comment by zmjones** [comment]
recovered the buffer. seems that `curl.h` is included in anaconda too, and was before the `curl.h` in `/usr/bin`.

**Comment by EconGeo** [comment]
I'm on 10.9 but I had all sorts of library linking problems until I made the edit to the Makevar file.  gcc should be doing a good amount of work when installing R packages.  A lot of authors write routines in C if they are computationally intensive, so that's why it matters which C compiler R is using.  I think since most authors seem to do some sort of Linux build on their packages the gcc-4.9 is probably the best one to use.

**Comment by zmjones** [comment]
makes sense. i used the homebrew compiled R for a long time. didn't seem to break until recently (3-4 months ago). have had to use the binary since then.
