### ISSUE TITLE
brew install octave on Mac OS X seems to need docs enabled

### ISSUE THREAD

**Issue by josmithiii** [Homebrew/homebrew-science#1742]
After `brew install octave`, octave mostly works ok, except that some commands fail, such as `pkg install -forge control`:

    copyfile /var/tmp/oct-QK6fTX/control/src/__control_slicot_functions__.oct /var/tmp/oct-QK6fTX/control/src/is_matrix.oct /var/tmp/oct-QK6fTX/control/src/is_real_matrix.oct /var/tmp/oct-QK6fTX/control/src/is_real_scalar.oct /var/tmp/oct-QK6fTX/control/src/is_real_square_matrix.oct /var/tmp/oct-QK6fTX/control/src/is_real_vector.oct /var/tmp/oct-QK6fTX/control/inst/x86_64-apple-darwin14.1.0-api-v49+
    unable to open /usr/local/Cellar/octave/3.8.1_1/share/octave/3.8.1/etc/macros.texi for reading
    error: called from '__makeinfo__' in file /usr/local/Cellar/octave/3.8.1_1/share/octave/3.8.1/m/help/__makeinfo__.m near line 103, column 5
    error: called from:
    error:   /usr/local/Cellar/octave/3.8.1_1/share/octave/3.8.1/m/pkg/private/install.m at line 242, column 5
    error:   /usr/local/Cellar/octave/3.8.1_1/share/octave/3.8.1/m/pkg/pkg.m at line 394, column 9

Perhaps the missing macros.texi is related to the following configure in /usr/local/Cellar/octave/3.8.1_1/share/octave/3.8.1/etc/config.log

  $ ./configure --prefix=/usr/local/Cellar/octave/3.8.1_1 --disable-docs --without-opengl --with-x=no

Specifcially, maybe `--disable-docs` is causing this failure?

**Comment by iml** [comment]
This is an unfortunate limitation of Homebrew's bottling infrastructure. The bots don't have TeX, so the docs are disabled by default in order that Octave may be tested and bottled. For the time being you have to `brew reinstall octave --with-docs` to enable docs.

**Comment by dpo** [comment]
See #1592 and the reference in that PR.

**Comment by josmithiii** [comment]
I checked the MacPorts case, and octave apparently only requires texinfo, not TeX:

>port deps octave
Full Name: octave @3.8.2_3+atlas+gcc49
Build Dependencies:   bison, flex, gperf, perl5, pkgconfig, gcc49, clang-3.4
Library Dependencies: arpack, curl, fftw-3, fftw-3-single, gawk, glpk, gnuplot,
                      GraphicsMagick, grep, gsed, hdf5, less, ncurses, pcre,
                      qhull, qrupdate, readline, SuiteSparse, zlib, texinfo,
                      atlas, libgcc
Runtime Dependencies: epstool, ghostscript, transfig, pstoedit
>port deps texinfo
Full Name: texinfo @5.2_2
Extract Dependencies: xz
Build Dependencies:   help2man
Library Dependencies: gettext, libiconv, ncurses, perl5.16
>octave
octave:1> pkg install -forge control
For information about changes from previous versions of the control package, run 'news control'.
octave:2> which tf
'tf' is a function from the file /Users/me/octave/control-2.6.6/@tf/tf.m
octave:3> exit
libc++abi.dylib: terminating with uncaught exception of type octave_interrupt_exception
panic: Abort trap: 6 -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
Abort
> (the reason I tried switching to Homebrew after months of this kind of crashing of the MacPorts version)

**Comment by dpo** [comment]
`texinfo` ships with OSX. But perhaps it's not sufficient?
