### ISSUE TITLE
octave not working

### ISSUE THREAD

**Issue by tjwudi** [Homebrew/homebrew-science#1761]
After installing **octave**, found that octave complains

```
dyld: Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/octave/3.8.1_1/bin/octave-cli-3.8.1
  Reason: image not found
[1]    2066 trace trap  octave
```

Reinstalling `qrupdate` does not work (suggested in other issues).

**Comment by dpo** [comment]
You seem to have an outdated `gcc`. Try `brew reinstall gcc`.

**Comment by tjwudi** [comment]
@dpo I just got the latest gcc installed, but it still can't work. 

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

Any thoughts? Thank you for your time.

**Comment by tjwudi** [comment]
Solved by adding symlink for gcc.

```
$ cd /usr/local/lib/gcc/
$ ln -s x86_64-apple-darwin14.0.0/4.9.2 4.9
```

**Comment by dpo** [comment]
I think there must have been an update of `gcc` and the `octave` bottles (binaries) were built against the previous one. I'll have them rebuilt. Thanks for mentioning this.

**Comment by iml** [comment]
There hasn't been an update of the `gcc` bottles. If your gcc is in /usr/local/lib/gcc/x86_64-apple-darwin14.0.0/4.9.2 than means you are using an older build before 1ef4c2d310c42193a525935404dac053d0218319.

**Comment by ssim12** [comment]
tjwudi commented on Jan 25
Solved by adding symlink for gcc.
$ cd /usr/local/lib/gcc/
$ ln -s x86_64-apple-darwin14.0.0/4.9.2 4.9

The above did not work for me. 
Solved by adding symlink
$ cd /usr/local/lib/gcc/
$ ln -s ../../Cellar/gcc/4.9.2/lib/gcc/x86_64-apple-darwin14.0.0 .
