### ISSUE TITLE
Maxima error: fatal error encountered in SBCL

### ISSUE THREAD

**Issue by hyuna917** [Homebrew/homebrew-science#1791]
I have the same problem(Maxima 5.34.1. #1405). How can I fix it? I try to reinstall sbcl, and reinstall maxima with with-sbcl option.

**Comment by dpo** [comment]
Are you building from source or using bottles?

**Comment by hyuna917** [comment]
I use homebrew and I think it is installed from bottles.

**Comment by dpo** [comment]
#1405 reports that building from source resolves the issue (I'm not sure where the actual problem comes from).

**Comment by hyuna917** [comment]
How can I install from source? Could I use homebrew?

**Comment by hyuna917** [comment]
I have found the way to install from source! thanks dpo!

**Comment by dpo** [comment]
Does it work now?

**Comment by hyuna917** [comment]
yes! It works! 
and, can I ask another question about maxima? 

I want to use wxmaxima. and I found that I should compile maxima with cmucl to use wxmaxima. 
how can I compile with cmucl?

**Comment by iml** [comment]
It should work fine with SBCL. The `maxima` formula doesn't support CMUCL right now, but you're free to patch that and submit a PR if you wish.

**Comment by andrejv** [comment]
The error implies that you compile maxima with one sbcl binary and run in it with a different binary. 

To compile trully portable bottle you should probably compile maxima with `--enable-sbcl-exec`. This compiles maxima to an executable image which does not require sbcl to be installed on the system.

**Comment by hyuna917** [comment]
`brew install maxima −enable-sbcl-exec` doesn’t work for me ;( but, brew install `−build-from-source brew` works! so, thanks everyone! 

and, @iml. 
did you mean I don’t have to compile with cmucl to use wxmaxima?

**Comment by dpo** [comment]
`brew options maxima` tells you what build options are available, and there currently aren't any :).

@andrejv The `maxima` bottle is built against Homebrew's `sbcl`, which is also bottled. When a user installs bottles, both the `sbcl` and `maxima` bottles are installed on their machine. So it doesn't seem that it's a different binary. What am I missing?

**Comment by iml** [comment]
@hyuna917 I've tested it with Homebrew maxima. I don't think the lisp compiler would impact wxMaxima, in any case. Just follow the directions in `brew info wxmaxima` to point it to the correct binary.

**Comment by andrejv** [comment]
@iml The runtime is the sbcl part which loads the core which is the maxima part. The runtime is very picky about which cores it can load. Every time you recompile sbcl you will also need to recompile maxima (even if you use exactly the same source and options for sbcl).

**Comment by andrejv** [comment]
The post is a reply to @dpo of course. Sorry;)

**Comment by dpo** [comment]
@andrejv Thanks for clarifying. In that case, I don't see much point in bottling `maxima` unless we use `--enable-sbcl-exec`.

**Comment by hyuna917** [comment]
@iml I’m already to try to follow the directions in `brew info`. 
I give up to use wxmaxima, but imaxima. ;(

**Comment by iml** [comment]
@hyuna917 wxMaxima works for me, please start a new thread to tackle that if you're still having issues.
