### ISSUE TITLE
Sundials fails to build

### ISSUE THREAD

**Issue by kwkelly** [Homebrew/homebrew-science#1799]
Not entirely sure why. I see no obvious build errors in the verbose output.

Verbose output in the link: http://pastebin.com/EZgHfGbE

brew doctor shows nothing. 

    $ brew config
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew
    HEAD: 66b1bb0445b66a07e0e5d7a07fd6cfcb930379b0
    Last commit: 2 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    CPU: quad-core 64-bit haswell
    OS X: 10.10.2-x86_64
    Xcode: 6.1.1
    CLT: 6.1.1.0.1.1416017670
    Clang: 6.0 build 600
    X11: 2.7.7 => /opt/X11 
    System Ruby: 2.0.0-p481
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby
    Java: 1.6.0_65

**Comment by dpo** [comment]
It seems some tests are failing, indicated by lines of the form
````
Number of error test failures            =    5
````
You should be able to build `--without-check` but I can't say if the errors are significant.

**Comment by kwkelly** [comment]
I can do that just fine.

    $ brew install sundials --without-check --enable-shared --disable-fcmix --enable-mpi --with-mpi-root=/usr/local

succeeds, but then when I do `brew install petsc` it installs it again (strange), but then succeeds.

**Comment by iml** [comment]
`--enable-shared --disable-fcmix --enable-mpi --with-mpi-root=/usr/local` aren't formula options so they are ignored. Petsc requires the `with-mpi` option for `sundials` so it rebuilds it with that (plus the `without-check`).

**Comment by dpo** [comment]
See `brew options sundials`.

**Comment by kwkelly** [comment]
I just copied the options for the configure script. That was a mistake.

In any event, it seems to have reinstalled (maybe saving the --without-check option because it doesn't seem to have run them) and then installs fine. 

Still not sure why it was failing those tests.

**Comment by dpo** [comment]
Several tests fail for me too.
