### ISSUE TITLE
samtools: Illegal instruction: 4

### ISSUE THREAD

**Issue by bede** [Homebrew/homebrew-science#1801]
Brewed samtools is very broken for me on OS 10.9.5. File IO doesn't seem to work at all.

```
$ brew update && brew upgrade && brew install samtools
==> Installing samtools from homebrew/homebrew-science
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/science/samtools-1.1.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/samtools-1.1.mavericks.bottle.tar.gz
==> Pouring samtools-1.1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/samtools/1.1: 45 files, 1.2M
$ which samtools
/usr/local/bin/samtools
$ samtools view -bS file.sam
Illegal instruction: 4
```

This post points to it being an OS X issue:
http://redmine.soe.ucsc.edu/forum/index.php?t=msg&th=5913&start=0&S=e78469aa350424e1fc888171baf23986

**Comment by bede** [comment]
Any ideas @sjackman?

**Comment by sjackman** [comment]
My best guess is that the GCC target CPU includes an instruction that your CPU doesn't support. Can you report the output of `sysctl -n machdep.cpu.brand_string`. The work around is easy: `brew install samtools --build-from-source`.

**Comment by sjackman** [comment]
Also which version of Mac OS are you on? `sw_vers -productVersion`

**Comment by bede** [comment]
I didn't know we could still `--build-from-source`, thanks! I'm running 10.9.5 with two 12 core Xeon Westmere X5670s.

**Comment by sjackman** [comment]
It is pretty strange though. The default optimization level is supposed to be valid for any Mac that is capable of running 10.9. Is it a Hackintosh?

**Comment by bede** [comment]
It's a 2010 Mac Pro. Interesting.
