### ISSUE TITLE
Support for sim-x

### ISSUE THREAD

**Issue by webdrone** [Homebrew/homebrew-science#1805]
Any chance of supporting this?
http://simx.lanl.gov

If there is a better alternative someone is aware of, I'd appreciate the head's up.

**Comment by dpo** [comment]
The best and fastest way to add a new formula is to submit a pull request. See the [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook).

**Comment by saketkc** [comment]
It is on `pypi`, right?
https://pypi.python.org/pypi/simx/0.3

**Comment by webdrone** [comment]
It is, but it has dependencies on non-python software, that’s why I thought it would be useful to have support through brew.
