### ISSUE TITLE
Installing Lammps with Homebrew, please help..

### ISSUE THREAD

**Issue by ccccdong** [Homebrew/homebrew-science#1810]
I tried to install lammps on my Mac with 10.10.2 iOS , using Home brew, when I try "brew install lammps", the error pops up as following:

==> Installing lammps from homebrew/homebrew-science
==> Installing dependencies for lammps: openssl, libevent, open-mpi, fftw, jpeg, voro++
==> Installing lammps dependency: openssl
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/openssl-1.0.2.yosemite.bottle

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "openssl"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/openssl-1.0.2.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: /usr/local/opt/makedepend not present or broken
Please reinstall makedepend. Sorry :(

Anyone know how to solve this?

**Comment by dpo** [comment]
Same issue as https://github.com/Homebrew/homebrew/issues/36703 ?

**Comment by dpo** [comment]
SourceForge appears to be back up. Are you able to install bottles now?

**Comment by iml** [comment]
Yea it looks like things have returned to normal. You can always `--build-from-source` if the bottles are unavailable.
