### ISSUE TITLE
Invalid Bottle for formula slepc : compiles/links with petsc 3.5.2 instead of 3.5.3

### ISSUE THREAD

**Issue by prudhomm** [Homebrew/homebrew-science#1812]
@dpo @BrewTestBot the bottle for slepc 3.5.3 was generated against petsc 3.5.2 instead of 3.5.3
hence it is usable if one has only petsc 3.5.3
Recompiling slepc from source is necessary and works nicely

**Comment by dpo** [comment]
@prudhomm Thanks for the report. How did that manifest itself? It's odd because the `slepc` formula refers to `petsc`'s `opt_` folders, and so bottles should remain valid across updates.

**Comment by dpo** [comment]
#1820 should fix it anyways.

**Comment by prudhomm** [comment]
Installation of the bottle was fine but at.runtime slepc was looking for the 3.5.2 lib and they were not there of course. That's how I detected the problem 
thanks for the fix
