### ISSUE TITLE
Sundials: segmentation fault

### ISSUE THREAD

**Issue by aancel** [Homebrew/homebrew-science#1814]
While trying to install petsc on Yosemite 10.10.2, brew installs sundials as a dependency and adds the `--with-mpi` flag. If my understanding is correct, when we add a flag, brew automatically recompiles the dependency with the correct flags and do not use bottles. The compilation of sundials ends up with an error.

Using the `--debug` flag for `install`, I noticed that the sundial installation ends up with a segfault when executing `./cvodes/serial/cvsHessian_ASA_FSA`.

This can be worked around by adding the `without-check` flag to the dependency in petsc, but does not solves this segmentation fault issue.
According to their [website](https://computation.llnl.gov/casc/sundials/download/download.php), the version of sundial provided in homebrew is the latest (the release date of 2.5.0 is March 2012).

What could be the solution to this problem ?
- removing the dependency on sundials from petsc ?
- adding the `without-check` flag (might not be safe as the segfault could come from the library itself)

**Comment by dpo** [comment]
Could you `brew gist-logs sundials` so we can have a look at the full output? In the mean time, you should be able to `brew install petsc --without-sundials` but it's not ideal.

**Comment by aancel** [comment]
Here is the gist you asked for: https://gist.github.com/anonymous/f027832082b68afb393f

Just a note, we are working on our own fork of homebrew-science (https://github.com/feelpp/homebrew-science) and the sundials.rb file is the same as the one published in hombrew-science.

**Comment by dpo** [comment]
Sorry I can't see a segmentation fault. Does it not appear in the logs? Does it occur during the execution of `cvsHessian_ASA_FSA`? I have many more log files (there at 74 in total!)

**Comment by aancel** [comment]
I have redone an installation starting from scratch (removed all the brew installed software).
I used the following command to install petsc:
```
brew -v install petsc
```

When it reaches the installation of sundials, the installation fails and I get:
```
Error: sundials 2.5.0 did not build
```
Then I launch brew in debug mode to check what failed:
```
brew -v install --debug petsc
```
When the installation of sundials fails at `./cvodes/serial/cvsHessian_ASA_FSA` and brew ask me what to do, I choose the drop down to shell option, and tries to execute the application manually, then I end up with:
```
$/private/tmp/sundials-DBRwBC/sundials-2.5.0/examples: ./cvodes/serial/cvsHessian_ASA_FSA
-------------------
Forward integration
-------------------

ncheck = 1

     y:      2.2732e-01   1.3534e-01   3.1472e-02     G:      5.3088e-01

     yS1:   -1.6714e-01   0.0000e+00   0.0000e+00
     yS2:    2.1339e-01   0.0000e+00  -1.0885e-01

   dG/dp:   -1.2838e-01   1.8037e-02

Final Statistics for forward pb.
--------------------------------
 Number steps:   142

 Function evaluations:
  f:          165
  fQ:         147
  fS:         165
  fQS:        147
 Error test failures:
  netf:         1
  netfQ:        0
  netfS:        0
  netfQS:       1
 Linear solver setups:
  nsetups:     27
  nsetupsS:     0
 Nonlinear iterations:
  nni:        161
  nniS:         0
 Convergence failures:
  ncfn:         0
  ncfnS:        0

---------------------------------------------
Backward integration ... (2 adjoint problems)
---------------------------------------------

zsh: segmentation fault  ./cvodes/serial/cvsHessian_ASA_FSA
```

Do you think it might come from other softwares that I might have installed locally ? or my configuration ?

**Comment by dpo** [comment]
On OSX 10.10 I also get a segmentation fault, but in a different test. It's interesting that the brew bot didn't suffer from it. The first thing to try would be to build Sundials outside of Homebrew to determine whether the problem is due to Homebrew or not. The same configure and make commands should be used.

**Comment by aancel** [comment]
I downloaded the last release of sundials and built it on my computer. I tested the example that fails during the brew build and it worked (I also tested several other examples and they seem to be working).

I made some additional tests with homebrew and noticed a peculiar behaviour.
To start, I used the following brew command (that will install sundials as a dependency):
```
brew -v install --debug petsc
```
Then sundials fails to execute the exemple `cvsHessian_ASA_FSA` and I drop down to a shell in the build directory. Let's says that I am in the `/private/tmp/sundials-PR5YkZ/sundials-2.5.0/examples` directory.
When I launch:
```
./cvodes/serial/cvsHessian_ASA_FSA
```
The application segfaults.

But when I open an other terminal to the same directory and launch the same command, the application seems to be working fine.
Could there be something in the environment that brew defines that would make the application execution fail ?

**Comment by dpo** [comment]
Actually I was on a similar lead. On Yosemite, `brew install sundials` without any options builds fine for me, and all tests pass. But `petsc` needs to build `sundials --with-mpi`. As I mentioned above, `brew install sundials --with-mpi` segfaults for me, but `brew install sundials --with-mpi --env=std` builds fine. So you're right, it has to do with the environment. Could you confirm that the same works for you?

That's happened to me in the past and I've not been able to tell why building with `--env=std` is sometimes necessary on a machine, but not on others.

**Comment by aancel** [comment]
Indeed, your solution with `--env=std` seems to be working on my side.
Do you think it should be added by default to the package ?

**Comment by dpo** [comment]
Yes it probably should be added if the user builds `--with-mpi` on Yosemite. Do you want to submit a PR?

**Comment by aancel** [comment]
I can take care of the modification with a PR indeed.
But before doing so, I guess it would be worth checking the other options, i.e. openblas and fortran, in case they produce the same error, don't you think ?

**Comment by dpo** [comment]
Yes I agree.

**Comment by aancel** [comment]
On my side, compiling with:
- `--with-fortran` doesn't fail,
- `--with-openblas` does fail, but it works with `--env=std`.

I'll issue a PR with the fix for `--with-openblas` and `--with-mpi`.

**Comment by dpo** [comment]
Ok thanks for testing. For reference, insiste a brew command, you can use the statement `ENV.std` to deactivate `superenv`.

**Comment by aancel** [comment]
I didn"t find any existing reference to the `ENV.std`statement in existing formulae and it doens't seem to work for me.
I managed to make the formula work by adding an if-conditionned `ARGV << "--std=env"`. 
Is it OK like this ?

**Comment by dpo** [comment]
Sorry, the correct directive is `env :std`. See, e.g., the formula for Vim.

**Comment by davydden** [comment]
i have sundials installed (Homebrew from mid January) and did not have any issue:
```
$ brew info sundials
sundials: stable 2.5.0 (bottled)
https://computation.llnl.gov/casc/sundials/main.html
/usr/local/Cellar/sundials/2.5.0 (248 files, 4.8M) *
  Built from source with: --with-mpi
```
I can't explain why you guys experienced this issue and i didn't...

**Comment by dpo** [comment]
Try to build from source on 10.10.

**Comment by davydden** [comment]
it was build from source

**Comment by dpo** [comment]
It wasn't. It says "bottled".

**Comment by dpo** [comment]
Well hang on. That message's a bit confusing...

**Comment by davydden** [comment]
i believe you are wrong. It says it is bottled in general, but it was build from source, as I have it `--with-mpi` for petsc.

**Comment by davydden** [comment]
I also have `export HOMEBREW_BUILD_FROM_SOURCE=true`, so everything on my system shall be built from source

**Comment by davydden** [comment]
Well, as I said, it was built from source in January, perhaps now it would fail. But currently my homebrew is up-to-date.

**Comment by dpo** [comment]
You would have to rebuild to see the error. It would be good to know if it's also a problem for you. I think that would indicate a larger issue with superenv.

**Comment by davydden** [comment]
what is the safest way to try it without loosing what i have? I can't break my tool-chain now. Perhpas if I first do `brew unlink sundials`, then make a hard-copy of installed folder (version) into a new one (say, `2.5.0.tmp`) and then try to build `--with-mpi`? I that sounds reasonably safe, i will give a go tomorrow...

**Comment by dpo** [comment]
I imagine that should work fine, but better give it a go with a formula you don't care about first.

**Comment by dpo** [comment]
@aancel Somehow `brew install sundials --with-mpi` is now working correctly for me on Yosemite and all tests pass. I do have a problem with certain MPI tests when using MPICH2. They are ok with OpenMPI. The error always has the form `npes is not equal to NPEX*NPEY`. So it seems the issue is with MPI's `MPI_comm_size` somehow.

**Comment by aancel** [comment]
@dpo Indeed it also seems to work on my side with openmpi
Do you have an idea about what could have been the problem ?
I guess you can cancel the pull request.

**Comment by dpo** [comment]
@aancel Thanks for confirming. I'm not sure what the problem is exactly, but [another issue](https://github.com/Homebrew/homebrew-science/pull/1299#issuecomment-96457366) with MPICH tipped me off.

It would still be worth adding caveats to this formula to warn users about possible problems if they're using MPICH.
