### ISSUE TITLE
Warning: opencv dependency gcc was built with a different C++ standard

### ISSUE THREAD

**Issue by xmen4u** [Homebrew/homebrew-science#1859]
Hi!,

in reference to https://github.com/Homebrew/homebrew-science/issues/844

I'm also experiencing the same warning: 
Warning: opencv dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.

gist of the output(s): https://gist.github.com/xmen4u/2cec8b8f1c22c60a69a1

any ideas on resolving this? thank you..

**Comment by iml** [comment]
You can safely ignore this error, which is expected (though confusing) when brew checks Fortran-using dependencies. It's different than #844 in that most things are expected to be built with libc++ from clang, but GCC/GFortran is a big exception.

Also you might want to `brew update` as your repository is relatively old.

**Comment by xmen4u** [comment]
@iml thank you very much for the quick update! appreciate it. So now i can start working on it. Very uninformative message then... to most users who'll think it's broken.

**Comment by ahundt** [comment]
If it is this specific fortran case, could it be sensible to correctly detect and prevent he warning to occur when it is not applicable?

**Comment by tdsmith** [comment]
Yes, that would be a welcome improvement.
