### ISSUE TITLE
new octave version

### ISSUE THREAD

**Issue by boborbt** [Homebrew/homebrew-science#1860]
The currently supported octave version 3.8.1 seems to have problems with printing graphs (the `plot` command works just fine, the `print` command instead would produce legible axes but empty black contents). Is there any news about supporting for the already released 3.8.2 version? This version includes the new experimental GUI and may fix printing problems (this is a wild guess on my part). 

Unfortunately, AFAICT support for the new version may require some effort. I've tried to edit the formula just to point to the new version, but this does not work due to compilation errors.

**Comment by dpo** [comment]
Porting the formula to the new version is probably a major effort, which is why it hasn't happened yet.

**Comment by iml** [comment]
Have you tried with `octave --force-gui`? I believe that uses the experimental Qt-based GUI.

**Comment by mcg1969** [comment]
I see no reason to even bother trying to get the formula working for later versions of Octave 3.8.x. The future is Octave 4.0, and that's where any effort should go. Unfortunately I've had quite a bit of difficulty getting Octave 4.0 to compile, though I periodically re-attempt it.

**Comment by dpo** [comment]
See #1989.
