### ISSUE TITLE
Shogun brew not active under Python

### ISSUE THREAD

**Issue by nirbenz** [Homebrew/homebrew-science#1868]
It seems like the current version of the shogun installer doesn't add the required links to python.

Wondering if this is a local issue I'm facing (been thinking my entire homebrew/python install is messed up) or a wider issue.

Running Python 2.7.6.

**Comment by saketkc** [comment]
#1818 is pending. It should hopefully fix that too

**Comment by dpo** [comment]
Please test and comment on #1818.
