### ISSUE TITLE
allpaths-lg fails to build

### ISSUE THREAD

**Issue by lizzhao** [Homebrew/homebrew-science#1889]
Dear colleagues, 

I have a problem in building allopaths-lg using brew and would appreciate any of your helpful suggestions.  The errors came with gcc 4.9, however error remains if I use gcc4.7 or gcc4.8.

Thanks,

 Li

localhost:bin MacPro$ brew install allpaths-lg -v
==> Installing allpaths-lg from homebrew/homebrew-science
==> Downloading ftp://ftp.broadinstitute.org/pub/crd/ALLPATHS/Release-LG/latest_source_code/allpathslg-50378.tar.gz
Already downloaded: /Library/Caches/Homebrew/allpaths-lg-50378.tar.gz
==> Verifying allpaths-lg-50378.tar.gz checksum
tar xf /Library/Caches/Homebrew/allpaths-lg-50378.tar.gz
==> ./configure --disable-dependency-tracking --prefix=/usr/local/Cellar/allpaths-lg/50378
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-apple-darwin12.5.0
checking host system type... x86_64-apple-darwin12.5.0
checking for style of include used by make... GNU
checking for gcc... gcc-4.9
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-4.9 accepts -g... yes
checking for gcc-4.9 option to accept ISO C89... none needed
checking dependency style of gcc-4.9... none
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc-4.9... /usr/local/Library/ENV/4.3/ld
checking if the linker (/usr/local/Library/ENV/4.3/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/local/Library/ENV/4.3/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc-4.9 object... ok
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking how to run the C preprocessor... gcc-4.9 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc-4.9 supports -fno-rtti -fno-exceptions... no
checking for gcc-4.9 option to produce PIC... -fno-common -DPIC
checking if gcc-4.9 PIC flag -fno-common -DPIC works... yes
checking if gcc-4.9 static flag -static works... no
checking if gcc-4.9 supports -c -o file.o... yes
checking if gcc-4.9 supports -c -o file.o... (cached) yes
checking whether the gcc-4.9 linker (/usr/local/Library/ENV/4.3/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin12.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether we are using the GNU C++ compiler... no
checking whether g++-4.9 accepts -g... no
checking dependency style of g++-4.9... none
checking whether we are using the GNU C++ compiler... (cached) no
checking whether g++-4.9 accepts -g... (cached) no
checking dependency style of g++-4.9... (cached) none
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/private/tmp/allpaths-lg-hsdZkA/allpathslg-50378':
checking whether byte ordering is bigendian... no

Failed to execute g++-4.9 -pipe -Os -dumpversion -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names

Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
  xcodebuild -license
  sudo xcode-select -switch /path/to/Xcode.app

Failed...
configure: Configure failed with the error message: You must compile this with g++ 4.7 or higher.
configure: 
configure: Common error conditions in the build process are documented
configure: on our wiki page:
configure: http://www.broadinstitute.org/crd/wiki/index.php/Build_FAQ
configure: We also offer email support at crdhelp@broadinstitute.org
configure: error: in `/private/tmp/allpaths-lg-hsdZkA/allpathslg-50378':
configure: error: Configure failed.
See `config.log' for more details.
==> Formula
Tap: homebrew/homebrew-science
Path: /usr/local/Library/Taps/homebrew/homebrew-science/allpaths-lg.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: aa5f792a46f5a79c6db52cdac9965090e19cc0e2
Last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 12-core 64-bit sandybridge
OS X: 10.8.5-x86_64
Xcode: 5.1.1
CLT: 5.0.1.0.1.1377666378
GCC-4.2: build 5666
Clang: 5.0 build 500
X11: 2.7.5 => /opt/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.0/bin/ruby
Java: 1.7.0_75
==> ENV
HOMEBREW_CC: gcc-4.9
HOMEBREW_CXX: g++-4.9
MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.8
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin

Error: allpaths-lg 50378 did not build
Logs:
     /Users/MacPro/Library/Logs/Homebrew/allpaths-lg/01.configure
     /Users/MacPro/Library/Logs/Homebrew/allpaths-lg/01.configure.cc
     /Users/MacPro/Library/Logs/Homebrew/allpaths-lg/config.log

**Comment by tdsmith** [comment]
I'm closing this ticket since we do not believe this package supports building on OS X. Sorry!
