### ISSUE TITLE
R installation does not include the cairo graphics devices

### ISSUE THREAD

**Issue by gwerbin** [Homebrew/homebrew-science#1890]
After installing R ([r.rb](https://github.com/Homebrew/homebrew-science/blob/master/r.rb)), I found that I was missing files necessary for the cairo-based graphics (like the `svg` function).

It seems that they need to be installed separately with `make cairodevices` as described [here](http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Building-the-cairo-devices-files). Currently there is no option to do this with the Homebrew formula. I don't know any Ruby or how to use make, but I feel like this should be possible; I'm sure it was just overlooked.

**Comment by gwerbin** [comment]
I just realized those instructions are Windows-only; that step shouldn't be necessary on a Mac.

Nevertheless, this is my `capabilities()` output:

    capabilities()
    # jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets   libxml     fifo   cledit 
    # TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
    # iconv      NLS  profmem    cairo      ICU 
    # TRUE     TRUE    FALSE    FALSE     TRUE 

and clearly neither cairo or memory profiling are enabled. I would like to build R with these enabled but it's not clear to me what needs to be added to the formula.

**Comment by dpo** [comment]
That's odd. I get
````
> capabilities()
    jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets
    TRUE     TRUE     TRUE    FALSE    FALSE     TRUE     TRUE     TRUE
  libxml     fifo   cledit    iconv      NLS  profmem    cairo      ICU
    TRUE     TRUE     TRUE     TRUE     TRUE    FALSE     TRUE     TRUE
````

**Comment by gwerbin** [comment]
What else can I do to help diagnose what went wrong during installation?

**Comment by dpo** [comment]
We're waiting to see if #1906 builds correctly, but the build bot appears to be down at the moment. If it builds, it should resolve your issue.

**Comment by dpo** [comment]
@gwerbin Please `brew update` and try to reinstall `r`. It should have both Cairo and memory profiling enabled.

**Comment by pooranis** [comment]
I had the same problem and reinstalled R.  profmem is enabled, but cairo still is not.  Is there something else I should do?  I noticed in the formula there's no flag for `--with-cairo`.  In the past, when I've built R from source without homebrew, I've had to include that flag.  Should that be included here?

**Comment by dpo** [comment]
Does `brew reinstall cairo` help?

**Comment by pooranis** [comment]
I just reinstalled cairo and R (in that order), and cairo is still disabled:
```
> capabilities()
    jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets 
   FALSE    FALSE    FALSE     TRUE    FALSE     TRUE     TRUE     TRUE 
  libxml     fifo   cledit    iconv      NLS  profmem    cairo      ICU 
    TRUE     TRUE     TRUE     TRUE     TRUE     TRUE    FALSE     TRUE 
```

**Comment by dpo** [comment]
Are you using bottles? Could you try building from source (`--build-from-source`)?

**Comment by iml** [comment]
I don't see cairo enabled with bottled R, so `--with-cairo=yes` is probably called for.

**Comment by dpo** [comment]
This is odd because `--with-cairo=yes` is the default, and `cairo` is a dependency.

**Comment by iml** [comment]
There may be something peculiar with the bottling environment, I'll check when they're built. 

The other possibility is that pango is also required, and configure turns off cairo if pango is missing. This would result in `with-cairo` being disabled on the bot or a clean machine but not when built from source with an existing pango.

**Comment by iml** [comment]
Nevermind, tried removing pango and cairo capability is still enabled with building from source (on master).

**Comment by dpo** [comment]
It's still worth committing your change with the accelerate flag.

**Comment by iml** [comment]
Same `FALSE` result from the above bottle. I'll test out pango before revisiting this later.

**Comment by pooranis** [comment]
Sorry, I didn't reply sooner, but building from source `--build-from-source` fixed the problem for me yesterday (now if I could just figure out how to enable x11!):
```
 jpeg      png     tiff    tcltk      X11     aqua http/ftp 
    TRUE     TRUE     TRUE     TRUE    FALSE     TRUE     TRUE 
 sockets   libxml     fifo   cledit    iconv      NLS  profmem 
    TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
   cairo      ICU 
    TRUE     TRUE 
```

**Comment by dpo** [comment]
It should be enabled. If you quit R, launch your X server, and then restart R, is it enabled?

**Comment by pooranis** [comment]
Yes, restarting XQuartz fixed it!  Thanks.

**Comment by dpo** [comment]
@gwerbin Any news on this?

**Comment by gwerbin** [comment]
capabilities()
    #     jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets   libxml 
    #     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
    #     fifo   cledit    iconv      NLS  profmem    cairo      ICU 
    #     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE

Thank you guys!

**Comment by gwerbin** [comment]
Is there any hope of this working without having to `--build-from-source` every time? I carelessly used `brew upgrade` yesterday to get the latest version of R and ended up having to reinstall.

**Comment by iml** [comment]
This should be resolved now, `brew update` and retry the bottle.
```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double 
       TRUE        TRUE        TRUE        TRUE        TRUE
