### ISSUE TITLE
Warnings on tap stage

### ISSUE THREAD

**Issue by rdo777** [Homebrew/homebrew-science#1898]
>brew tap Homebrew/science
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 9109, done.
remote: Total 9109 (delta 0), reused 0 (delta 0), pack-reused 9109
Receiving objects: 100% (9109/9109), 2.37 MiB | 713.00 KiB/s, done.
Resolving deltas: 100% (5083/5083), done.
Checking connectivity... done.
Warning: Could not create link for homebrew/science/cantera, as it
conflicts with Homebrew/homebrew/cantera. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/cantera
Warning: Could not create link for homebrew/science/gromacs, as it
conflicts with Homebrew/homebrew/gromacs. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/gromacs
Warning: Could not create link for homebrew/science/openfst, as it
conflicts with Homebrew/homebrew/openfst. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/openfst
Warning: Could not create link for homebrew/science/opengrm-ngram, as it
conflicts with Homebrew/homebrew/opengrm-ngram. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/opengrm-ngram
Warning: Could not create link for homebrew/science/sundials, as it
conflicts with Homebrew/homebrew/sundials. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/sundials
Tapped 438 formulae

are they important? or I can continue work regardless these warnings

**Comment by saketkc** [comment]
You can ignore them. They could have been avoided by running `brew update` before tapping.

**Comment by rdo777** [comment]
I did `brew update` before `brew tap`. And it reduces an amount of warnings, but some of them still exist.

**Comment by dpo** [comment]
Try
````
brew untap homebrew/science
brew update
brew tap homebrew/science
````

**Comment by rdo777** [comment]
That is exactly what I did.
`workmachine:~ rdo$ brew untap homebrew/science && brew update && brew tap homebrew/science
Error: No such tap!
workmachine:~ rdo$ brew update && brew tap homebrew/science
Updated Homebrew from 0d725936 to 7656218a.
==> Updated Formulae
asciinema	  chcase	    deis	      frei0r		libpst		  ruby		    term	      xctool
autoconf-archive  chinadns-c	    denominator	      juju-quickstart	lightning	  sysdig	    tutum
==> Deleted Formulae
git-flow-clone
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 9121, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 9121 (delta 5), reused 0 (delta 0), pack-reused 9109
Receiving objects: 100% (9121/9121), 2.39 MiB | 442.00 KiB/s, done.
Resolving deltas: 100% (5088/5088), done.
Checking connectivity... done.
Warning: Could not create link for homebrew/science/cantera, as it
conflicts with Homebrew/homebrew/cantera. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/cantera
Warning: Could not create link for homebrew/science/gromacs, as it
conflicts with Homebrew/homebrew/gromacs. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/gromacs
Warning: Could not create link for homebrew/science/openfst, as it
conflicts with Homebrew/homebrew/openfst. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/openfst
Warning: Could not create link for homebrew/science/opengrm-ngram, as it
conflicts with Homebrew/homebrew/opengrm-ngram. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/opengrm-ngram
Warning: Could not create link for homebrew/science/sundials, as it
conflicts with Homebrew/homebrew/sundials. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/science/sundials
Tapped 439 formulae
`

**Comment by saketkc** [comment]
That looks strange:
```
workmachine:~ rdo$ brew untap homebrew/science && brew update && brew tap homebrew/science
Error: No such tap!
```

**Comment by rdo777** [comment]
That is because I untapped it before. I tried several options but all end with these warnings.

**Comment by saketkc** [comment]
Can you post the output of `$ brew config | grep Last`?

**Comment by rdo777** [comment]
`$ brew config | grep -i last`
`Last commit: 2 hours ago`
`$`

**Comment by dpo** [comment]
Does `brew untap homebrew/science && brew update && brew prune && brew tap homebrew/science` help?

**Comment by rdo777** [comment]
`workmachine:~ rdo$ brew tap`
`homebrew/dupes`
`workmachine:~ rdo$ mv /usr/local/Library/Formula/cantera.rb /usr/local/Library/Formula/.mv.cantera.rb `
`workmachine:~ rdo$ mv /usr/local/Library/Formula/gromacs.rb /usr/local/Library/Formula/.mv.gromacs.rb`
`workmachine:~ rdo$ mv /usr/local/Library/Formula/openfst.rb /usr/local/Library/Formula/.mv.openfst.rb`
`workmachine:~ rdo$ mv /usr/local/Library/Formula/opengrm-ngram.rb /usr/local/Library/Formula/.mv.opengrm-ngram.rb`
`workmachine:~ rdo$ mv /usr/local/Library/Formula/sundials.rb /usr/local/Library/Formula/.mv.sundials.rb`
`workmachine:~ rdo$ brew prune`
Pruned 0 dead formulae
Tapped 37 formulae
workmachine:~ rdo$ brew tap homebrew/science
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 9121, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 9121 (delta 5), reused 0 (delta 0), pack-reused 9109
Receiving objects: 100% (9121/9121), 2.39 MiB | 902.00 KiB/s, done.
Resolving deltas: 100% (5088/5088), done.
Checking connectivity... done.
Tapped 439 formulae
`workmachine:~ rdo$`

Somehow these files were in Formula's folder but without homebrew/science repository.

Thanks a lot for the help!
