### ISSUE TITLE
ucsc: kent-tools only option

### ISSUE THREAD

**Issue by idot** [Homebrew/homebrew-science#1904]
There was a discussion on ucsc <-> kent-tools and the idea to have a kent-tools-only option.
It would be really nice to have this.
https://github.com/Homebrew/homebrew-science/pull/37#issuecomment-18679881

**Comment by iml** [comment]
If it's the standalone tools are available from the src archives at http://hgdownload.cse.ucsc.edu/admin/exe/, we could still package as a separate formula, since `ucsc-genome-browser` is keg-only.

**Comment by iml** [comment]
Fullfilled by 868fd82. Thanks @jonchang
