### ISSUE TITLE
change root6 file to add option

### ISSUE THREAD

**Issue by leoredi** [Homebrew/homebrew-science#1915]
Hi guys we should change the root6 file like this

"cmake-build" do system "cmake", "..", "-Dgnuinstall=ON", "-Dbuiltin_freetype=ON", "-Dall=ON", cmake_opt("python"), cmake_opt("ssl", "openssl"), cmake_opt("xrootd"), *std_cmake_args system "make", "install" end 

this will allow us to install root6 with all the possible dependences.

**Comment by lgeiger** [comment]
> install root6 with all the possible dependencies.

this would be great.

**Comment by dpo** [comment]
I'm not convinced that will lead to a clean install because some optional components are already available as separate Homebrew formulae. But if you feel strongly, please feel free to submit a pull request that we'll evaluate. Thanks.
