### ISSUE TITLE
openblas bottles for sandybridge, segfaults on penryn

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-science#1930]
Sorry if I missed an earlier discussion about this. When I `brew install openblas` I get a bottle containing /usr/local/Cellar/openblas/0.2.13/lib/libopenblas_sandybridgep-r0.2.13.dylib.

Unfortunately, on my vintage laptop, this means `brew install numpy --with-openblas` gives me a numpy that segfaults on its tests.

My config:
```
darkside:homebrew-pypi-poet tim$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: git@github.com:homebrew/homebrew.git
HEAD: 14fc4411c8ebea423c5cbc999af967e8e6f4d2fe
Last commit: 43 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/tim/.rvm/rubies/ruby-2.1.2/bin/ruby
Java: 1.8.0_20
```

Should openblas have bottles? Can Homebrew be more aggressive about telling openblas to bottle for the core2 arch? Alternatively but probably less favorably, a `pour_bottle?` method could decide whether or not to pour the bottle depending on the user's arch.

**Comment by iml** [comment]
> Should openblas have bottles?

I think the answer is no. Even if we could better enforce the preferred bottle arch there's no guarantee that would be more forward-compatible.

**Comment by tdsmith** [comment]
Penryn is older than Sandy Bridge, so I think the problem is that the bottles are being built for the build bot's native arch and aren't backwards-compatible; they should be perfectly forwards-compatible, though they won't perform optimally.

If openblas users will be disappointed by bottles that aren't optimized for their microarchitecture, it probably shouldn't be bottled, or else the formula could print a caveat warning users that source builds are better optimized.

I opened a pull request to bottle against the older arch and print a caveat.

**Comment by iml** [comment]
OK, sounds like a good compromise.
