### ISSUE TITLE
Question: using homebrew for data sets?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#1951]
There are many data scientific data sets, particularly in genomics, which be very useful to be able to install via brew in a systematic manner. 

This would allow for default settings for the corresponding software tools to be pointing at the right databases and so on. There are many examples:

* Rfam database, Infernal tool
* Pfam database, HMMER tool
* CDD database, RPS-BLAST tool

Does this fit into the Hombrew model?  Is it already being done for other data sets? Should I just start a ```homebrew-omicsdata``` or somesuch?

**Comment by saketkc** [comment]
@arq5x started working on something similar: https://github.com/arq5x/ggd

**Comment by tseemann** [comment]
Thanks for the pointer!
