### ISSUE TITLE
igraph failed to build on OS X 10.10.2

### ISSUE THREAD

**Issue by pmoriano** [Homebrew/homebrew-science#1969]
I am trying to install igraph for Python by using the following command 

brew install homebrew/science/igraph

I am using a macbook pro with OS X 10.10.2.I already update to the last version of Xcode. However, I am getting the following errors. Does anyone know how to deal a with them? Thank you.

==> Installing igraph from homebrew/homebrew-science
==> Downloading http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/igraph-0.7.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/igraph/0.7.1
==> make install
ld: illegal text-relocation to '___gmp_binvert_limb_table' in /usr/local/lib/libgmp.a(mp_minv_tab.o) from '___gmpn_divexact_1' in /usr/local/lib/libgmp.a(dive_1.o) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libigraph.la] Error 1

make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

**Comment by dpo** [comment]
Are you trying to build `igraph` without `gmp` support? I just submitted an update that should ensure `igraph` disables `gmp` support altogether.

**Comment by dpo** [comment]
Please check #2078.
