### ISSUE TITLE
Question: can I have depends_on from other external taps?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#1972]
I need the freebayes and vcflib tools as dependencies.
@chapmanb has them in his repository: https://github.com/chapmanb/homebrew-cbl
Brad regularly promotes formulae to homebrew-science.
Can i depends_on them where they are?

**Comment by dpo** [comment]
We don't support depending on external taps. If it makes sense, you could submit PRs for those formulas here, or else the best might be to have your own tap.

**Comment by tseemann** [comment]
Ok, thanks @dpo . I'll work with @chapmanb to migrate the key ones where suitable.
