### ISSUE TITLE
allpaths-lg on OS X 10.10.2 (installation error)

### ISSUE THREAD

**Issue by kim612** [Homebrew/homebrew-science#1975]
Thank you.

computer:~ kim$ brew install allpaths-lg
==> Installing allpaths-lg from homebrew/homebrew-science
couldn't understand kern.osversion `14.1.0'
==> Downloading ftp://ftp.broadinstitute.org/pub/crd/ALLPATHS/Release-LG/latest_source_code/allpathslg-50378.tar.gz
Already downloaded: /Library/Caches/Homebrew/allpaths-lg-50378.tar.gz
==> ./configure --prefix=/usr/local/Cellar/allpaths-lg/50378
==> make install
./kmers/KmerRecord.h:297:1: note: in expansion of macro 'DEFINE_BYTE_PAC_LESS'
 DEFINE_BYTE_PAC_LESS(10000)
 ^
make[1]: *** [SupportedHyperBasevector4.o] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

computer:~ kim$

And, please check this link too. It was made by "brew gist-logs allpaths-lg".
https://gist.github.com/e3e60c17582024294459

**Comment by tseemann** [comment]
Mine builds on Linux, but fails on OSX (I have 14.1.10 too). However, it is not the macro error, I get errors with ```cstring```.

@kim612 as an aside - are you sure you can use allpath-lg? it requires (1) _overlapping_ paired end reads **and** (2) a large mate-pair library. This combination is rare unless you speficially sequenced for it. Try using ```spades``` instead.

**Comment by tdsmith** [comment]
I'm closing this ticket since we do not believe this package supports building on OS X. Sorry!
