### ISSUE TITLE
opencv: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sleekweasel** [Homebrew/homebrew-science#1979]
Hi folks.

On my shiny new Yosemite mac, I just installed with brew reinstall opencv --with-java (I installed without java first time round).

Attempting the trivial suggested test on the OpenCV website...

        System.loadLibrary("opencv_java2410");
        Mat m  = Mat.eye(3, 3, CvType.CV_8UC1);
        System.out.println("m = " + m.dump());

resulted in this exception:

    Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_eye(III)J
	at org.opencv.core.Mat.n_eye(Native Method)
	at org.opencv.core.Mat.eye(Mat.java:1467)
	at org.opencv.core.Mat$eye.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:138)
	at com.gat.opencvhack.Hack.main(Hack.groovy:12)

Running the library whose directory I've specified with -Djava.library.path through nm and c++filt shows the JNI entries for that call and some corresponding C++ ones:

    nm /usr/local/Cellar/opencv/2.4.10.1/share/OpenCV/java/libopencv_java2410.dylib |c++filt |grep eye
    0000000000013344 T _Java_org_opencv_core_Mat_n_1eye__DDI
    00000000000130ea T Java_org_opencv_core_Mat_n_1eye(int0_t)
                 U cv::Mat::eye(cv::Size_<int>, int)
                 U cv::Mat::eye(int, int, int)

Now I did see the 

    Warning: opencv dependency gcc was built with a different C++ standard
    library (libstdc++ from clang). This may cause problems at runtime.

error, but I understand that to relate to the Fortran compiler. I also found http://answers.opencv.org/question/16689/jni-error-on-playframework-v211-unsatisfiedlinkerror-orgopencvcorematn_matiiiddddj/ but that is (a) an older version of OSX, and (b) my library loads without being called .jnilib (copying it to which name does nothing anynow).

Have I done something stupid? Should I be using a different Java? I have this:

    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

I presume my use of IntelliJ has no effect. Failing to specify -Djava.library.path at all causes the expected 'no such library' exception, so I'm fairly sure it's trying to run the expected library.

There's a gist here - https://gist.github.com/anonymous/f31c4b41a65b73e3781c

Also:

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 35e22f0add1da811e7531779c867e64579044fb1
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.2-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_31

Thanks.

**Comment by sleekweasel** [comment]
Oh, failing to specify -Djava.library.path at all causes the expected 'no such library' exception, so I'm fairly sure it's trying to run the expected library.

**Comment by AUGxhub** [comment]
e have you solved this problem .i meet a similarly  problem.

**Comment by dpo** [comment]
Please update and open a new issue if problems persist. Thanks.
