### ISSUE TITLE
Error building opencv with cuda support

### ISSUE THREAD

**Issue by mons91** [Homebrew/homebrew-science#1987]
Hi all!
I'm having trouble building opencv with cuda 7 giving the --with-cuda flag during the installation.
In particular I get:

make[2]: *** [modules/core/CMakeFiles/cuda_compile.dir/__/dynamicuda/src/cuda/cuda_compile_generated_matrix_operations.cu.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

How can i fix this? Thx!

**Comment by mons91** [comment]
For now i solving building from scratch the opencv sources downloaded from their repository adding the flag: -DCUDA_ARCH_BIN="3.0" among the cmake arguments, that is:

cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=ON -DCUDA_ARCH_BIN="3.0" ..

**Comment by iml** [comment]
Fair warning, I don't think any of the maintainers have the necessary hardware to troubleshoot this so it's up to you or any fellow CUDA compatriots to submit a fix.

**Comment by CyberCastle** [comment]
Hi!
OpenCV 2.4.11 solves this trouble. I'm using the mentioned version CUDA 7, in Yosemite 10.10.2 with Xcode 6.2.

Greetings

**Comment by iml** [comment]
Should be fixed with https://github.com/Homebrew/homebrew-science/commit/98e9515758bb86416476604d43e3d286a07f37f9.
