### ISSUE TITLE
brew build pcl fail

### ISSUE THREAD

**Issue by liujiboy** [Homebrew/homebrew-science#1992]
I use `brew install -vd pcl --with-example` to  build pcl 1.72 with vtk6.2 and yosemite.
I got the following errors:
Linking CXX shared library ../lib/libpcl_filters.dylib
cd /tmp/pcl20150321-71920-918bjs/pcl-pcl-1.7.2/macbuild/filters && /usr/local/Cellar/cmake/3.2.1/bin/cmake -E cmake_link_script CMakeFiles/pcl_filters.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++  -ftemplate-depth=1024 -Qunused-arguments -Wno-invalid-offsetof   -dynamiclib -Wl,-headerpad_max_install_names   -compatibility_version 1.7.0 -current_version 1.7.2 -o ../lib/libpcl_filters.1.7.2.dylib -install_name /tmp/pcl20150321-71920-918bjs/pcl-pcl-1.7.2/macbuild/lib/libpcl_filters.1.7.dylib CMakeFiles/pcl_filters.dir/src/conditional_removal.cpp.o CMakeFiles/pcl_filters.dir/src/crop_box.cpp.o CMakeFiles/pcl_filters.dir/src/extract_indices.cpp.o CMakeFiles/pcl_filters.dir/src/filter.cpp.o CMakeFiles/pcl_filters.dir/src/filter_indices.cpp.o CMakeFiles/pcl_filters.dir/src/passthrough.cpp.o CMakeFiles/pcl_filters.dir/src/shadowpoints.cpp.o CMakeFiles/pcl_filters.dir/src/project_inliers.cpp.o CMakeFiles/pcl_filters.dir/src/radius_outlier_removal.cpp.o CMakeFiles/pcl_filters.dir/src/random_sample.cpp.o CMakeFiles/pcl_filters.dir/src/normal_space.cpp.o CMakeFiles/pcl_filters.dir/src/sampling_surface_normal.cpp.o CMakeFiles/pcl_filters.dir/src/statistical_outlier_removal.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid.cpp.o CMakeFiles/pcl_filters.dir/src/approximate_voxel_grid.cpp.o CMakeFiles/pcl_filters.dir/src/bilateral.cpp.o CMakeFiles/pcl_filters.dir/src/fast_bilateral.cpp.o CMakeFiles/pcl_filters.dir/src/fast_bilateral_omp.cpp.o CMakeFiles/pcl_filters.dir/src/crop_hull.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid_covariance.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid_label.cpp.o CMakeFiles/pcl_filters.dir/src/frustum_culling.cpp.o CMakeFiles/pcl_filters.dir/src/covariance_sampling.cpp.o CMakeFiles/pcl_filters.dir/src/median_filter.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid_occlusion_estimation.cpp.o CMakeFiles/pcl_filters.dir/src/normal_refinement.cpp.o CMakeFiles/pcl_filters.dir/src/grid_minimum.cpp.o CMakeFiles/pcl_filters.dir/src/morphological_filter.cpp.o CMakeFiles/pcl_filters.dir/src/local_maximum.cpp.o CMakeFiles/pcl_filters.dir/src/model_outlier_removal.cpp.o /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib -lm ../lib/libpcl_sample_consensus.1.7.2.dylib ../lib/libpcl_search.1.7.2.dylib ../lib/libpcl_kdtree.1.7.2.dylib ../lib/libpcl_octree.1.7.2.dylib ../lib/libpcl_common.1.7.2.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib -lm /usr/local/lib/libflann_cpp.dylib 
cd /tmp/pcl20150321-71920-918bjs/pcl-pcl-1.7.2/macbuild/filters && /usr/local/Cellar/cmake/3.2.1/bin/cmake -E cmake_symlink_library ../lib/libpcl_filters.1.7.2.dylib ../lib/libpcl_filters.1.7.dylib ../lib/libpcl_filters.dylib
/usr/local/Cellar/cmake/3.2.1/bin/cmake -E cmake_progress_report /tmp/pcl20150321-71920-918bjs/pcl-pcl-1.7.2/macbuild/CMakeFiles  33 34 35 36 37
`[ 30%] Built target pcl_filters`
`make: *** [all] Error 2`
How can I sovle this problem？

**Comment by fran6co** [comment]
This is a duplicated issue of https://github.com/Homebrew/homebrew-science/issues/2016
