### ISSUE TITLE
Question: what is the expected time to accept a successful pull request?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#1993]
I am just wondering what is the expected time for a build-passing pull request to be accepted?

I understand we are all busy, but I'm just trying to decide whether I should use my own repository instead, like Brad Chapman does, and just push things to homebrew-science every now and then, so my collaborators can use my formulae immediately.

Thanks for any advice, 

Torst

**Comment by tdsmith** [comment]
There's no SLA. :) Homebrew is a volunteer-maintained best-effort project. If you need your collaborators to use your formulae immediately, a tap is a great solution.

**Comment by tseemann** [comment]
@tdsmith I am well aware of that. I have contributed many formulae. I get quick responses to Issues (eg. from @lml, @saketc, @sjackman and others) but it seems working pull requests languish (looking back historically), which seems backward. Homebrew-science team members have the advantage of directly pushing their new formulae without having others review them. From an outsider's point of view, this pattern is not a good strategy to encourage further contributions from outside?

**Comment by saketkc** [comment]
I am not an official team member, just another big fan ;-)

**Comment by tdsmith** [comment]
I appreciate the frustration you're feeling. As a Homebrew maintainer I think we are a little bit in danger of being victims of our own success. Something on my own to-do list is to write more useful documentation about setting up and maintaining taps, because I think they really are a useful alternative to landing formulas in the Homebrew organization's taps, especially for rapidly-evolving projects.

Do you have any suggestions for ways we can turn PRs around more quickly? I've noticed at Homebrew/homebrew that sorting oldest-first isn't very productive because a pile of difficult and non-urgent PRs tend to get stuck at the bottom. :) Still, resisting the urge to pick the newest PR off the stack might be helpful.

**Comment by sjackman** [comment]
@tseemann Feel free to tag me and @iml for bioinformatic formula. You'll get a quicker response than waiting for me to scan the pull requests. I'm also open to adding more people to the Homebrew/science team that have a history of contributions.

@tdsmith I'm less keen on encouraging personal taps. I would like Homebrew/science to be the definitive source of bioinformatics software. That being said, I'll hold no grudge if someone would prefer to maintain a personal tap.

**Comment by tseemann** [comment]
Thank you @tdsmith and @sjackman for responding kindly to my (mildly grumpy) response. I too am guilty on my own projects of picking the recent issues, and ignoring pull requests (too hard basket). I feel one day I could be a homebrew-science team member, but I need to go through the training hoops still first. I've installed 1000s of softwares over the last 20 years, and have always wanted to package things properly. I had done some RPM packaging but never mastered Debian. Homebrew is simpler and amenable to multiple version installation. You have all been generous in helping me through my issues and I hope to repay it with more, good formulae.

The documentation is ok, but not great. I mostly learn by looking at existing formulae, but it seems I often choose "old" ones which aren't following the current best practices?  I guess this is always true in fast moving open source projects like this.

I'd prefer to keep everything under the -science tap if possible, as dependencies can't span taps (that's what I asked and was told on the Homebrew issue list).  FOr example, my software depends on freebayes, and Brad Chapman has a formula in his cbl-homebrew tap by I can't depend on it?

**Comment by sjackman** [comment]
> The documentation is ok, but not great. I mostly learn by looking at existing formulae, but it seems I often choose "old" ones which aren't following the current best practices? 

Yes, that's true. I know it should be, but I'm afraid improving documentation isn't on the top of my priority list. Check the commit history and find a formula that was updated recently to see an example of the current best practices.

> I'd prefer to keep everything under the -science tap if possible, as dependencies can't span taps (that's what I asked and was told on the Homebrew issue list). FOr example, my software depends on freebayes, and Brad Chapman has a formula in his cbl-homebrew tap by I can't depend on it?

I'd prefer to add freebayes to homebrew-science, unless there's a good reason not to.

**Comment by saketkc** [comment]
> I'm also open to adding more people to the Homebrew/science team that have a history of contributions.

@sjackman Are you still looking for?
cc @tdsmith @iml @dpo
