### ISSUE TITLE
VIGRA fails to build on 10.9.5

### ISSUE THREAD

**Issue by OliverJennrich** [Homebrew/homebrew-science#1994]
Trying to install VIGRA via
brew install vigra --cc=gcc-4.9

I get a failure in make check
./run_test_math.sh: line 1: 87318 Trace/BPT trap: 5       /tmp/vigra20150321-86030-1jthdj0/vigra-1.10.0/build/test/math/test_math
make[3]: *** [test/math/test_math] Error 1
make[2]: *** [test/math/CMakeFiles/test_math.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2

**Comment by dpo** [comment]
Please paste the output of `brew gist-logs vigra`.

**Comment by iml** [comment]
Feel free to reopen with further diagnostic info (I suggest using clang, though).
