### ISSUE TITLE
readseq - curl: (22) 401 Unauthorized Error: Failed to download resource "readseq"

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2002]
This does not occur for other bottles eg. "gingr"

```
==> Downloading https://homebrew.bintray.com/bottles-science/readseq-2.1.19.yosemite.bottle.tar.gz
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "readseq"
Download failed: https://homebrew.bintray.com/bottles-science/readseq-2.1.19.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by iml** [comment]
Also trimmomatic. Should work now, fixed from the web interface: https://bintray.com/homebrew/bottles-science/readseq/view

**Comment by shail-mmt** [comment]
Hi ,

I am getting below issue, any guess ?

``
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "openssl"
Download failed: https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: /usr/local/opt/makedepend not present or broken
``

**Comment by tseemann** [comment]
Can you report what ```brew install opensll --build-from-source``` says?

**Comment by tdsmith** [comment]
That issue is unrelated; if you continue to experience it after running `brew update`, please open a ticket against Homebrew/homebrew.
