### ISSUE TITLE
pcl: Error: invalid attribute: version (nil)

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-science#2006]
_From @jasonw580 on March 20, 2015 13:58_

When I run "brew info pcl",I get the informations below:
pcl: stable 1.7.2 (bottled), HEAD
http://www.pointclouds.org/
Not installed
From: https://github.com/homebrew/homebrew-science/blob/master/pcl.rb
==> Dependencies
Build: cmake ✘, pkg-config ✔
Error: invalid attribute: version (nil)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:129:in `validate_attributes!'
/usr/local/Library/Homebrew/formula.rb:96:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:38:in `installed?'
/usr/local/Library/Homebrew/cmd/info.rb:146:in `block in decorate_dependencies'
/usr/local/Library/Homebrew/cmd/info.rb:145:in `collect'
/usr/local/Library/Homebrew/cmd/info.rb:145:in `decorate_dependencies'
/usr/local/Library/Homebrew/cmd/info.rb:127:in `block in info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:125:in `map'
/usr/local/Library/Homebrew/cmd/info.rb:125:in `info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:31:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:135:in `<main>'

Is there someone can tell me what happened ?

_Copied from original issue: Homebrew/homebrew#37912_

**Comment by mikemcquaid** [comment]
_From @DomT4 on March 20, 2015 15:6_

Should really be reported to [Homebrew/science](https://github.com/homebrew/homebrew-science) as it's their formula. That said, ` brew readall ` should help work out what is broken.

**Comment by mikemcquaid** [comment]
_From @jacknagel on March 24, 2015 0:36_

Can't reproduce, but yes, this report belongs on homebrew-science.

**Comment by mikemcquaid** [comment]
@DomT4 @jacknagel Let's use this to move issues now: https://github-issue-mover.appspot.com

**Comment by iml** [comment]
@jasonw580. I can't reproduce this either. Please follow the troubleshooting steps and let us know if you're still having problems: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by dpo** [comment]
Can't reproduce either. @jasonw580 please `brew update`.
