### ISSUE TITLE
Octave Docstring Installation Error

### ISSUE THREAD

**Issue by jamestaylr** [Homebrew/homebrew-science#2008]
I've been trying to setup Octave (a package in the homebrew/science tap). I ran:

    brew install octave

and it works fine, but running:

    octave --silent

produces the error:

    warning: docstring file '/usr/local/Cellar/octave/3.8.1_1/share/octave/3.8.1/etc/built-in-docstrings' not found

I looked online it appears some people have fixed this by installing Octave with the `--without-docs` argument, so I uninstalled and reinstalled Octave with this argument:

    brew uninstall --force octave
    brew install octave --without-docs

Still, Octave complains about not having docstrings and I'm not sure how to fix this. I've also reported it [here](http://stackoverflow.com/q/29238053/1944335) and was instructed to create an issue in the repository so people could look into it.

Any help you could provide would be greatly appreciated! Thanks!

**Comment by iml** [comment]
Octave needs to be built `--with-docs` in order to suppress that warning. See https://github.com/Homebrew/homebrew-science/issues/1742#issuecomment-70965865

**Comment by jamestaylr** [comment]
I think that's a sizable dependency just so I can silence a warning when Octave starts. I also assumed `--without-docs` was suggested because maybe the parsers conflict. I just want to use a command-line argument and I don't need full doc functionality.

Anyways, thanks for taking a look into the problem.

**Comment by iml** [comment]
If you don't need built-in docs, it's not really worth installing MacTeX and building from source. However, I'll look into whether we can get by with just `texinfo` per the later comment on that thread.
