### ISSUE TITLE
Empty archive: does it handle top level ".dir" in a tar.gz ?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2023]
I get this error on a new formula I am writing. 
I have a feeling it is because the tar is a hidden "dot" directory?

```
==> Downloading https://github.com/pcingola/BigDataScript/releases/download/v0.999h/bds_Darwin.tgz
######################################################################## 100.0%
Error: Empty archive
```

```
% tar ztf bds_Darwin.tgz
.bds/
.bds/bds
.bds/bds.config
.bds/bigDataScript.config
.bds/clusterGeneric/
.bds/clusterGeneric_localhost/
.bds/fakeClusterTasks/
```

**Comment by iml** [comment]
Correct, `Dir[]` doesn't match hidden files and that's the method used to check if an archive is empty.

**Comment by iml** [comment]
Here's the relevant bit if you're interested: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/download_strategy.rb#L209-L211

It could be changed to match hidden files, but there might be a reason to keep the current behavior. This seems like an unusual situation to have only hidden files in the top dir. cc @jacknagel

**Comment by tseemann** [comment]
I think they expect people will be installing in their personal $HOME. 
Very odd!
I don't need this package, I was doing it for someone else, so I'm prepared to abandon it!
