### ISSUE TITLE
brew install graph-tool ERROR

### ISSUE THREAD

**Issue by mohancodehub** [Homebrew/homebrew-science#2030]
2 errors generated.
make[3]: *** [graph_blockmodel.lo] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**Comment by saketkc** [comment]
Can you `brew gist-logs graph-tools`?

**Comment by dpo** [comment]
I can't reproduce this on Mavericks or Yosemite. I'm going to close the issue for lack of activity, but please feel free to reopen if you're still experiencing difficulties.

**Comment by CindiThompsonUSF** [comment]
I have the same error. Not on Mavericks but OS X 10.8.5
I did brew gist-logs graph-tools and got: https://gist.github.com/anonymous/bdfb3769b74e0a224686

**Comment by dpo** [comment]
For reference, here's the error message:
````
/usr/bin/../lib/c++/v1/unordered_map:1224:25: error: call to member function '__construct_node' is ambiguous
    __node_holder __h = __construct_node(_VSTD::move(__k));
                        ^~~~~~~~~~~~~~~~
````
See also: http://stackoverflow.com/questions/20797326/why-would-indexing-a-map-by-tuple-cause-the-ambiguous-error-in-c-in-xcode
Your version of `clang` might not have the bug fix. Could you try installing with `--cc=gcc-4.9`?

**Comment by CindiThompsonUSF** [comment]
Do you mean use this flag for brewing graph-tool or do I need to upgrade clang itself? And if the latter, how? I tried "brew graph-tool -cc=gcc-4.9" and that did not work. (As you must guess, I'm relatively new with homebrew).

**Comment by dpo** [comment]
To upgrade clang you would have to install one of the `llvm` formulas. Let's first determine that clang is indeed the problem. The command I was recommending is `brew install graph-tool --cc=gcc-4.9` (note the two dashes in front of `cc`).

**Comment by CindiThompsonUSF** [comment]
thanks for your help! I did use two dashes, sorry for the typo. No joy, same problem.
Second, I earlier did "brew install llvm --with-clang"

**Comment by dpo** [comment]
Does gcc fail with the same error message? Could you `brew gist-logs graph-tool` once again?

**Comment by CindiThompsonUSF** [comment]
Yes, that's what I meant by same problem. See:
https://gist.github.com/openp2pdesign/8864593

Could it be my old OSX, or other issues in my brew doctor output?
