### ISSUE TITLE
HDF5 and netCDF4 fail to install 

### ISSUE THREAD

**Issue by wxcoder** [Homebrew/homebrew-science#2033]
I've been trying to several hours to get HDF5 and netCDF4 running to use in python, but I run into an issue when trying to install them. The first error is from doing "brew install hdf5":

Error: /usr/local/Library/Formula/hdf5.rb:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/usr/local/Library/Formula/hdf5.rb:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/usr/local/Library/Formula/hdf5.rb:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">

Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by iml** [comment]
> /usr/local/Library/Formula/hdf5.rb

This file shouldn't be there, or contain HTML. Delete it and `brew tap --repair`

**Comment by wxcoder** [comment]
Thank you, that worked for HDF5. I went to do "sudo pip install netCDF4" and got the following:

NETCDF4_DIR environment variable not set, checking standard locations..
    
    checking /Users/(myname) ...
    
    checking /usr/local ...
    
    checking /sw ...
    
    checking /opt ...
    
    checking /opt/local ...
    
    checking /usr ...
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/tmp/pip-build-gQtGO2/netCDF4/setup.py", line 259, in <module>
    
        raise ValueError('did not find netCDF version 4 headers')
    
    ValueError: did not find netCDF version 4 headers


How and where should I set the NETCDF4_DIR environment variable?

**Comment by wxcoder** [comment]
I solved that problem with brew install netcdf, then pip install netcdf4.
