### ISSUE TITLE
Update Gmsh formula to 2.9.1

### ISSUE THREAD

**Issue by prudhomm** [Homebrew/homebrew-science#2036]
Gmsh 2.9.1 has been released. Could you update the formula ?

thank you very much in advance. 

I have a basic change here to support that, I haven't yet looked into the features of this release
https://github.com/feelpp/homebrew-science/commit/60e9d74f7c536486186558437eb1615a5f3447e2

**Comment by dpo** [comment]
It's typically more efficient to submit a pull request. Thanks.
