### ISSUE TITLE
lammps-12Feb14.tar.gz doesn't exist

### ISSUE THREAD

**Issue by dezyx** [Homebrew/homebrew-science#2039]
I am having trouble building lammps with $ brew install lammps	
	GitHub webpage (https://github.com/homebrew/homebrew-science/blob/master/lammps.rb) line 5
	The file lammps-12Feb14.tar.gz doesn't exist at http://lammps.sandia.gov/tars/

**Comment by tdsmith** [comment]
This should work after `brew update`.
