### ISSUE TITLE
Can't update Octave to 3.8.2 because of missing arpack

### ISSUE THREAD

**Issue by lmontrieux** [Homebrew/homebrew-science#2049]
Hi there,

It seems that I can't update Octave to 3.8.2, as there are no available formula for arpack:

`Error: No available formula for arpack (dependency of octave)`

I am currently running Octave 3.8.1. A search for `arpack` doesn't return any formula, which is rather strange since I can see it in `/usr/local/Library/Taps/homebrew/homebrew-science/arpack.rb`

**Comment by dpo** [comment]
Try `brew untap homebrew/science; brew tap homebrew/science`.

**Comment by lmontrieux** [comment]
It worked. Thanks a lot!
