### ISSUE TITLE
Brew install Lammps user package does not work!!! (MacOsx)

### ISSUE THREAD

**Issue by yang15** [Homebrew/homebrew-science#2072]
I am trying to install the lammps with
brew install lammps --enable-user-colvars
it gives me the error showing below
==> Installing lammps from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://lammps.sandia.gov/tars/lammps-12Feb14.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "lammps"
Download failed: http://lammps.sandia.gov/tars/lammps-12Feb14.tar.gz

I tried the user package of USER-OMP, this works fine. With this installation, I went to directory /usr/local/Cellar/lammps/2014.02.12/share/lammps/tools/
I can see a folder named "colvars". Does that mean lammps default installation will automatically install the user option package? However, I still could not get the simulation running properly. My suspect is the installation with the user package still doesn't work. 

My major question is how should I install lammps with colvars and misc package enabled? What can I do to check whether these packages are installed properly?

Thanks,
Jing

**Comment by dpo** [comment]
See #2039 and #2065.

**Comment by yang15** [comment]
I checked this to requests. Unfortunately, they do not help really much...

**Comment by tdsmith** [comment]
This should work after `brew update`.

**Comment by yang15** [comment]
Hi, tdsmith
     Thank you very much. I can install lammps perfectly fine after brew update. You have been very helpful on my issue.
