### ISSUE TITLE
Unable to install open cv 3 in mac os 10.9 using brew

### ISSUE THREAD

**Issue by deepsamal** [Homebrew/homebrew-science#2099]
I am trying to install open cv 3.0. anaconda 2.2.0, python 2.7.9
 brew install --HEAD homebrew/science/opencv
(same error with --devel instead of --HEAD.)

Output-
==> Installing opencv from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/Itseez/opencv.git
Updating /Library/Caches/Homebrew/opencv--git
==> Checking out branch master
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL
DPYTHON_INCLUDE_DIR=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
-DWITH_CUDA=ON

CMake Error: The source directory "/tmp/opencv20150414-45329-1eu278k/macbuild/DPYTHON_INCLUDE_DIR=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7" does not exist.

I am not able to change any options in opencv, as when I run - $brew edit /homebrew/science/opencv
I get this error-
Error: No available formula for opencv 

Any help appreciated.

**Comment by tdsmith** [comment]
Can you share the results of `brew gist-logs opencv` after a failure?

**Comment by deepsamal** [comment]
I am sorry , I reverted back to opencv 2.4.11. BTW I also tried  brew install --HEAD opencv, the same issue persisted. Also used cmake to install. Even though cmake installation was successful, I wasn't able to open cv in python. So I reverted back.

**Comment by tdsmith** [comment]
I can't reproduce this failure and we can't diagnose without failure logs. Thanks for filing, though; sorry it didn't work out.
