### ISSUE TITLE
`veclibfort` formula is missing

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew-science#2112]
_From @amirmasoudabdol on April 16, 2015 8:18_

Upgrading `armadillo` produces this error:

```
❯ brew upgrade armadillo 
==> Upgrading 1 outdated package, with result:
armadillo 4.650.4
Error: No available formula for veclibfort (dependency of armadillo)
```

_Copied from original issue: Homebrew/homebrew#38705_

**Comment by mikemcquaid** [comment]
_From @xu-cheng on April 16, 2015 14:56_

Please run `brew update`. If not work, follow the [troubleshooting](https://git.io/brew-troubleshooting) and provide the necessary diagnostic information. Thanks.

**Comment by mikemcquaid** [comment]
_From @DomT4 on April 16, 2015 14:58_

Wrong repo. You want [Homebrew/science](https://github.com/Homebrew/homebrew-science).

**Comment by iml** [comment]
@amirmasoudabdol Please `brew update; brew tap --repair` If it still fails we will need more info from `brew gist-logs armadillo`

**Comment by dpo** [comment]
@amirmasoudabdol
