### ISSUE TITLE
issue installing openCV

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-science#2115]
_From @mohithingorani on April 17, 2015 1:47_

I was trying to install openCV today but it seems like GCC is unable to compile it:

Mohit:~ mohithingorani$ brew install opencv
==> Installing opencv from homebrew/homebrew-science
==> Installing dependencies for opencv: gcc, eigen, libpng, ilmbase, openexr, homebrew/python/numpy
==> Installing opencv dependency: gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.1.0 --prefix=/usr/local/Cellar/gcc/4.9.2_1 --libdir=/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9 --enable-languages=c,c++,objc,obj-c++,fortr
==> make bootstrap
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [configure-stage1-target-libgcc] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
GCC fails to build with Xcode 6.3 (https://github.com/Homebrew/homebrew/issues/38501)
Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
--cc=gcc-4.9 gets me in an infinite loop (https://github.com/Homebrew/homebrew/issues/33731)
gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)
Mohit:~ mohithingorani$ 

any work arounds/suggestions?

_Copied from original issue: Homebrew/homebrew#38731_

**Comment by tdsmith** [comment]
_From @DomT4 on April 17, 2015 2:5_

> READ THIS: https://git.io/brew-troubleshooting

:wink:

**Comment by tdsmith** [comment]
Nevermind; this is a GCC build issue, not an opencv build issue.

**Comment by sirarut** [comment]
@tdsmith i have the same problem with you, so is there any solution to this??. If yes, i would be so happy to hear it.
