### ISSUE TITLE
Mummer test will always pass even when failing

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2119]
https://github.com/Homebrew/homebrew-science/blob/master/mummer.rb

This is the test:

```
TOOLS.each do |tool|
      system "#{bin}/#{tool} -h 2>&1 |grep #{tool}"
    end
```

If the tool is installed and working, it will print the tool name as part of the help.

If the tools is NOT installed, then the SHELL will print "toolname not installed" and return 127, but the test will still pass!

Bit tricky to solve because the compiled code return 0 on --help while the scripts return things like 2.

Sorry to discover this while @sjackman is on holiday/vacation....

**Comment by iml** [comment]
Checking `File.exist?` or `File.executable?` may be another possibility, if it's fundamentally just the presence of the tool that needs to be confirmed.

**Comment by tseemann** [comment]
I think the formula is broken because mummerplot doesn't seem to get installed, and it is missing optional dependencies like gnuplot.  I am working on a new version of the formula.

**Comment by sjackman** [comment]
Nice catch, Torsten. I fixed it by replacing the test with

```diff
--- a/mummer.rb
+++ b/mummer.rb
@@ -31,7 +31,7 @@ class Mummer < Formula
 
   test do
     TOOLS.each do |tool|
-      system "#{bin}/#{tool} -h 2>&1 |grep #{tool}"
+      system "#{bin}/#{tool} -h 2>&1 |grep -i Usage"
     end
   end
 end
```
