### ISSUE TITLE
LAMMPS head build is broken

### ISSUE THREAD

**Issue by jblood14** [Homebrew/homebrew-science#2130]
Trying to install LAMMPS on my mac. Followed the instructions here: http://lammps.sandia.gov/download.html#homebrew

I get this:

$ brew install lammps --HEAD
==> Installing lammps from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning http://git.icms.temple.edu/lammps-ro.git
Updating /Library/Caches/Homebrew/lammps--git
==> Checking out branch master
==> Patching
patching file python/lammps.py
==> make -f Makefile.gfortran
==> make -f Makefile.gfortran
==> make -f Makefile.g++
Error: No such file or directory - MAKE/Makefile.mac

Any suggestions? Thanks

**Comment by dpo** [comment]
Is your Homebrew up to date?

**Comment by jblood14** [comment]
I'm on version 0.9.5

**Comment by dpo** [comment]
I meant to ask if you ran `brew update` recently. Please post the output of `brew gist-logs lammps`.

**Comment by jblood14** [comment]
I ran brew update, and it got further along, but still failed

here's the output you asked for: https://gist.github.com/0b7d0c3c737f8da92337

Here's what happened when I tried to install after the update

$ brew install lammps --HEAD
==> Installing lammps from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning http://git.icms.temple.edu/lammps-ro.git
Updating /Library/Caches/Homebrew/lammps--git
==> Checking out branch master
==> Patching
patching file python/lammps.py
==> make -f Makefile.gfortran
==> make -f Makefile.gfortran
==> make -f Makefile.g++
==> make yes-standard
==> make no-gpu
==> make no-kim
==> make no-user-omp
==> make no-kokkos
==> make mac
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [python.o] Error 1
make: *** [mac] Error 2

**Comment by tdsmith** [comment]
Does a stable build (i.e. without --HEAD) work? lammps has an eclectic and unstable build system.

Is there any reason the Python headers in /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 would be missing or incomplete?

**Comment by tdsmith** [comment]
Closing for lack of response; let us know if we can help.

**Comment by taohonker** [comment]
I came across the same issue. Seems that "Python.h" is not included properly:
```
/usr/local/bin/mpicxx -O  -DLAMMPS_GZIP -I../../lib/voronoi/includelink -I../../lib/reax -DLMP_PYTHON -I../../lib/poems -DLMP_MPIIO -I../../lib/meam  -DOMPI_SKIP_MPICXX -DFFT_FFTW3 -I/usr/local/opt/fftw/include -DLAMMPS_JPEG -I/usr/local/opt/jpeg/include -I/usr/local/opt/voro++/include/voro++  -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7   -c ../python.cpp
../python.cpp: In destructor 'virtual LAMMPS_NS::Python::~Python()':
../python.cpp:51:5: error: 'PyObject' was not declared in this scope
     PyObject *pFunc = (PyObject *) pfuncs[i].pFunc;
     ^
../python.cpp:51:15: error: 'pFunc' was not declared in this scope
     PyObject *pFunc = (PyObject *) pfuncs[i].pFunc
```
PS: I use python from homebrew instead of the one coming with osx.

**Comment by tdsmith** [comment]
Can you share the output of `brew gist-logs lammps` please?

**Comment by taohonker** [comment]
Sorry for replying late.
First I complied lammps with this command:
```
$brew install --build-from-source lammps
```
and lammps was compiled correctly.
Logs: https://gist.github.com/anonymous/8be3306053e9348942bf

Then I uninstalled lammps and compiled its git version:
```
$brew install --build-from-source lammps --HEAD
```
it failed when compiling python.cpp.
Logs: https://gist.github.com/anonymous/38ac95b1f04a1ad19ca8

**Comment by tdsmith** [comment]
We can't provide very much support for HEAD builds since they're moving targets but if someone can figure out how to change the formula to build lammps correctly, I'll be happy to accept the change. It might be worth asking the LAMMPS developers what they know.

**Comment by tdsmith** [comment]
Let us know if we can help.
