### ISSUE TITLE
shogun: 'jni.h' file not found

### ISSUE THREAD

**Issue by andyli** [Homebrew/homebrew-science#217]
`brew install shogun -v` failed with `modshogun_wrap.cxx:159:10: fatal error: 'jni.h' file not found`.

Full log can be found at https://gist.github.com/andyli/16b65db64942806636cf

`brew doctor`:
```
Warning: /Library/Frameworks/Mono.framework detected
This can be picked up by CMake's build system and likely cause the build to
fail. You may need to move this file out of the way to compile CMake.
```

`brew --config`:
```
HOMEBREW_VERSION: 0.9.4
ORIGIN: https://github.com/mxcl/homebrew
HEAD: 1ede32b48196ab0eb076a591b31bc84456e29a7d
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit sandybridge
OS X: 10.7.5-x86_64
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.6.5 => /usr/X11
System Ruby: 1.8.7-358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
```

**Comment by MartinHjelm** [comment]
I get it to compile(with colpack) if I remove all modular interfaces, however test 228 fails(unit-SerializationJSON).

Removing colpack and compiling with python interface I get the same errors as in https://gist.github.com/Ialong/159ee33c6c3717d75c6d

**Comment by MartinHjelm** [comment]
In Shogun 4 the error still persists 

 error: expected member name or ';' after declaration specifiers
    static bool check(PyObject *obj) {

without Python test 230 

Start 230: unit-SerializationJSON 230/232 Test #230: unit-SerializationJSON

**Comment by dpo** [comment]
Closing in favor of #1818.
