### ISSUE TITLE
brew install opencv --devel failed

### ISSUE THREAD

**Issue by andyli** [Homebrew/homebrew-science#2196]
The full log of `brew install opencv --devel -v` is at https://gist.githubusercontent.com/andyli/b0f371f3133a3b8fb4c3/raw/terminal
Related logs are at https://gist.github.com/andyli/b0f371f3133a3b8fb4c3

**Comment by tdsmith** [comment]
Failure is:

```
make[2]: *** No rule to make target `/usr/local/Cellar/qt/HEAD/lib/QtGui.framework', needed by `lib/libopencv_viz.3.0.0.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by tdsmith** [comment]
Does this work if you don't use the HEAD version of Qt?

**Comment by tdsmith** [comment]
Closing for no response; let us know if we can still help.
