### ISSUE TITLE
blat formula fails (Linuxbrew, Ubuntu 14.04)

### ISSUE THREAD

**Issue by mscook** [Homebrew/homebrew-science#2197]
Installation of boat formula fails on 'blank' Ubuntu 14.04 (with exception of linuxbrew dependencies installed via apt-get).

It's a libpng issue.

Please see: https://gist.github.com/anonymous/3fe0c4283a54d89bb728

I resolved it with:
```
sudo apt-get install libpng-dev
```

**Comment by tseemann** [comment]
The dependency is in the formula ```  depends_on "libpng" => :build``` but the Makefile isn't directed to use it. Needs to be a patch for ```-I#{include} -L#{lib}``` or similar?

**Comment by iml** [comment]
`png.h` is not provided by OS X. The easy fix is to append the header location to CFLAGS explicitly. Not sure why Linuxbrew would have difficulty finding headers and not the Mac compiler in this instance, but it is a common problem. Installing system packages with APT is a fine workaround, however.
