### ISSUE TITLE
Protocol for building GO language software?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2199]
Is there a standard protocol for building GO apps?

eg.  https://github.com/brentp/vcfanno

**Comment by iml** [comment]
Dependencies need to be vendored, and there's a helper function `Language::Go.stage_deps` to stage them into a gopath. `docker-machine`, `hugo`, and `hub` are some examples.

**Comment by iml** [comment]
Testing #2202.

**Comment by iml** [comment]
`brew install vcfanno` should be available. Nice to see some Go bio projects. The approach is similar to other language module dependencies, except that everything seems to come straight off github. We need to pin revisions for brew packaging.
