### ISSUE TITLE
lmod formula has broken dependency on luarocks

### ISSUE THREAD

**Issue by npch** [Homebrew/homebrew-science#2212]
The lmod formula (v5.9) has a dependency on luarocks, however luarocks is now installed as part of lua. As a result, it's not possible to install lmod using the formula. 

See: 
https://github.com/Homebrew/homebrew/commit/06e2a38236544d74eb672d6dd7ba40a03da72ef3
https://github.com/keplerproject/luarocks/issues/363

**Comment by dpo** [comment]
Thanks for reporting this!

**Comment by npch** [comment]
Thanks for providing a fix so quickly.
