### ISSUE TITLE
Octave installed with brew complains, upon launch, "No Java runtime present, requesting install" (JR ver 1.8.0_45, OSX 10.10 Yosemite)

### ISSUE THREAD

**Issue by JavierMares** [Homebrew/homebrew-science#2245]
Upon running, it says: "No Java runtime present, requesting install". A pop up to install Java SE 6 runtime appears.
I was advised to tag @xu-cheng 

Thank you in advance,
Javier

**Comment by xu-cheng** [comment]
This is a know bug. See #1899. I have tried to solve it in #2051. But it fails. I would suggest you to report it to Octave as it should be an upstream issue.

**Comment by JavierMares** [comment]
Thank you. I have reported it to Octave.

**Comment by tdsmith** [comment]
Closing as a duplicate; thanks, xu-cheng!

**Comment by vadimrostok** [comment]
[This update](https://support.apple.com/kb/DL1572?locale=en_US) of java for osx solved the problem for me.
