### ISSUE TITLE
idba installs but doesn't run

### ISSUE THREAD

**Issue by lmrodriguezr** [Homebrew/homebrew-science#2252]
The defined test is `idba_ud 2>&1 |grep IDBA`, which works well, but the binary is unable to read actual data (regardless of size):
```
$> idba_ud -r test.fa -o test
Bus error: 10
````
I'm testing it in OS 10.10.3 (Yosemite) and the same error occurs with the bottled package (`brew install idba`) and recompiling with `brew install --build-from-source --cc=gcc-4.9 idba`. Note that simply using `brew install --build-from-source idba` fails with a compilation error:
````
==> Downloading https://hku-idba.googlecode.com/files/idba-1.1.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/idba-1.1.1.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/idba/1.1.1
==> make
make[2]: *** [assembly_utility.o] Error 1
20 errors generated.
make[2]: *** [local_assembler.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
couldn't understand kern.osversion `14.3.0'

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
````

**Comment by tseemann** [comment]
Is your Brew installation up to date?  ie. ```brew update -v```

**Comment by lmrodriguezr** [comment]
Yes, it is. I also tried with a fresh installation of brew and the bottle seems to be missing C++ libraries, but I'll open a new bug for that. After solving the missing requirements and successfully installing it, I get the same "bus error: 10" message when passing files.

**Comment by dpo** [comment]
Sorry for the long wait. I just pushed an update that successfully reads in data in the test. Please open a new issue if problems persist.
