### ISSUE TITLE
KmerStream.cpp:13:10: fatal error: 'omp.h' file not found

### ISSUE THREAD

**Issue by gawbul** [Homebrew/homebrew-science#2266]
Was trying to install `kmerstream` and hit this issue with `clang`. Failed with `clang-omp` too. See here regarding `OpenMP` support in `clang` https://github.com/Homebrew/homebrew/issues/23849.

Got it to install by reverting to `gcc49` with `CPPFLAGS="-I/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin14.3.0/4.9.2/include/" brew install kmerstream --cc=gcc-4.9 -vvv`.

**Comment by iml** [comment]
The build is out-of-date but it should use `needs :openmp` in any case.
