### ISSUE TITLE
maker: missing module dependencies

### ISSUE THREAD

**Issue by gawbul** [Homebrew/homebrew-science#2267]
Hit this issue trying to install `maker`. Got the following log https://gist.github.com/gawbul/b3111aaafd5142f850ba.

However, all these prerequisites are installed in my local `perlbrew` installation:

```
cpan -i forks Perl::Unsafe::Signals Bio::Root::Version IO::All forks::shared Want
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.49_01)
Reading '/Users/sm1818/.cpan/Metadata'
  Database was generated on Fri, 15 May 2015 10:29:02 GMT
CPAN: Module::CoreList loaded ok (v5.20150214)
forks is up to date (0.36).
Perl::Unsafe::Signals is up to date (0.02).
Bio::Root::Version is up to date (1.006924).
IO::All is up to date (0.86).
forks::shared is up to date (0.36).
Want is up to date (0.26).
```

**Comment by gawbul** [comment]
Doing a `sudo cpan -i forks Perl::Unsafe::Signals Bio::Root::Version IO::All forks::shared Want` and installing these prerequisites in the system perl installation fixed the problem.

I wonder if `/usr/bin/perl` is hard coded somewhere? The log shows `/usr/bin/env perl`, I wondered if that isn't picking up the `perlbrew` installation for some reason?

**Comment by iml** [comment]
The log showing `/usr/bin/env perl` is actually brew checking the perl module dependencies. When it comes to running the program it looks like Maker uses /usr/bin/perl. It's pretty common to see that hard-coded.

Does it work if you run something like `PERL5LIB=~/my-perlbrew/modules maker`? In other words can you use modules installed under Perlbrew with system Perl?

**Comment by iMichka** [comment]
@gawbul Could you try again? We are delivering a new version of maker since them and this may have been fixed. Thanks.

**Comment by gawbul** [comment]
@iMichka sure, will have a look when I have some free time :smile:

**Comment by iMichka** [comment]
Hi. I'm closing this issue, so it does not stay indefinitely open. Please open a new one if you still have trouble with `maker`. Thanks.
