### ISSUE TITLE
pymol vs. libpng

### ISSUE THREAD

**Issue by cowsandmilk** [Homebrew/homebrew-science#2273]
running pymol currently tells me it was built with libpng 1.6, but is running with 1.5

libpng warning: Application built with libpng-1.6.17 but running with 1.5.18
/usr/local/Cellar/pymol/1.7.4.0_1/libexec/bin/pymol: line 4: 98537 Segmentation fault: 11  "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.7.4.0_1/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"

The dump has:

       0x101060000 -        0x101080ff7 +libpng15.15.dylib (34) <18C9ACE0-084D-3DEA-8C02-57EEFD558161> /opt/X11/*/libpng15.15.dylib

So, it is using libpng from xquartz?? What can I do about this?

**Comment by noinil** [comment]
Same problem on my mac, PyMOL crashes.

libpng warning: Application built with libpng-1.6.17 but running with 1.5.18
/usr/local/Cellar/pymol/1.7.4.0_1/libexec/bin/pymol: line 4: 98556 Segmentation fault: 11  "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.7.4.0_1/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"

**Comment by lmorency** [comment]
I have exactly the same problem :

 libpng warning: Application built with libpng-1.6.17 but running with 1.5.18
/usr/local/Cellar/pymol/HEAD/libexec/bin/pymol: line 4: 58275 Segmentation fault: 11  "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/HEAD/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"

**Comment by iml** [comment]
Trying to fix this in an update: #2283 by paring down to mostly X11 and system dependencies. The issue here is the mismatch where it's building with brewed libpng but importing X11 libraries on launch. Not exactly sure why it cropped up now, though.

**Comment by dbobr** [comment]
Had a similar issue. Removed libpng and pymol via homebrew, reinstall pymol with homebrew letting it build with the 1.5.x that it was trying to run it with. Works fine.
