### ISSUE TITLE
R 3.2.0: libgfortran.3.dylib: image not found

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#2286]
After upgrading `gcc` to 5.1.0 I got the following error from R:

```
❯❯❯ R
dyld: Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/r/3.2.0/R.framework/Versions/3.2/Resources/lib/libR.dylib
  Reason: image not found
[1]    85177 trace trap  R
```

Installing `gcc49` should work around this issue, but `gcc49` is built without fortran by default. `brew install gcc49 --with-fortran` should work around this issue—I'm testing this now—but requires building `gcc49` from source.

@mikemcquaid What's the recommended way of rebuilding the R bottle with `gcc` 5.1.0? I'm guessing that we're going to need to do this for a lot of formulae.

**Comment by sjackman** [comment]
@Homebrew/science

**Comment by mikemcquaid** [comment]
@sjackman Bump the `revision` in a PR.

**Comment by sjackman** [comment]
Source `revision` or bottle `revision`?

**Comment by dpo** [comment]
We have a similar situation every time `gcc` is upgraded. Is there a good way to identify all the affected formulas? Something like `brew uses gcc`?

**Comment by jeremyash** [comment]
I still get the error after 'brew install gcc49 --with -fortran`

**Comment by sjackman** [comment]
There should be no space between `--with` and `-fortran`.
I can confirm that `brew install gcc49 --with-fortran` did work for me.

**Comment by jeremyash** [comment]
ahh...trying now.  thanks for following up!

**Comment by iml** [comment]
Octave will also need to be bumped and probably anything using `:fortran`. For reference see https://github.com/Homebrew/homebrew-science/commit/a9669cfd05129e9335b64c089d3bd3cd542ef390.

**Comment by dpo** [comment]
We should automate that...

**Comment by neverfox** [comment]
That gets R started again but then:
```
warning: directory not found for option '-L/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin14.3.0/4.9.2'\nld: warning: directory not found for option '-L/usr/local/Cellar/gcc/4.9.2_1/lib/gcc/4.9'\nld: library not found for -lgfortran\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\nmake: *** [SparseM.so] Error 1\nERROR: compilation failed for package 'SparseM'
```
gcc49 is in `/usr/local/Cellar/gcc49...` so...

**Comment by xu-cheng** [comment]
> Source revision or bottle revision?

@sjackman Source revision.

> Something like brew uses gcc?

@dpo Yes, `brew uses` is designed to do this. More specially you could use `brew uses gcc --skip-optional --skip-build`.

> We should automate that

`brew test-bot` will automatically check such dependency breakage. However, it doesn't work for cross-tap for now.

**Comment by sjackman** [comment]
```sh
for i in `brew uses gcc --skip-optional --skip-build`; do ls $i.rb; done
```

```
abinit.rb
arpack.rb
atomic-pseudopotential-engine.rb
cgns.rb
cmor.rb
coinmp.rb
coinutils.rb
dotwrp.rb
dynare.rb
etsf_io.rb
fgsl.rb
getdp.rb
gmsh.rb
hopdm.rb
hypre.rb
ipopt.rb
itsol.rb
lammps.rb
libctl.rb
lis.rb
mfusg.rb
moab.rb
mumps.rb
octave.rb
openblas.rb
p4est.rb
pastix.rb
petsc.rb
platanus.rb
plink2.rb
propack.rb
qr_mumps.rb
qrupdate.rb
r.rb
salt.rb
scalapack.rb
slepc.rb
slicot.rb
superlu.rb
superlu_dist.rb
tisean.rb
trilinos.rb
veclibfort.rb
xmi-msim.rb
```
