### ISSUE TITLE
insighttoolkit fails without clear reason

### ISSUE THREAD

**Issue by dewet22** [Homebrew/homebrew-science#2291]
$ brew update
Already up-to-date.
$ brew upgrade --all
$ brew install simpleitk
==> Installing simpleitk from homebrew/homebrew-science
==> Installing dependencies for simpleitk: insighttoolkit, pcre, swig
==> Installing simpleitk dependency: insighttoolkit
==> Downloading https://downloads.sourceforge.net/project/itk/itk/4.7/InsightToolkit-4.7.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/insighttoolkit-4.7.2.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/insighttoolkit/4.7.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=O
    linked by target "ITKIOTransformHDF5" in directory /tmp/insighttoolkit20150521-56195-m0byw3/InsightToolkit-4.7.2/Modules/IO/TransformHDF5/src

-- Configuring incomplete, errors occurred!
See also "/tmp/insighttoolkit20150521-56195-m0byw3/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/insighttoolkit20150521-56195-m0byw3/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
$ less /tmp/insighttoolkit20150521-52123-12b47pj/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeOutput.log
/tmp/insighttoolkit20150521-52123-12b47pj/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeOutput.log: No such file or directory
$ less /tmp/insighttoolkit20150521-52123-12b47pj/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeError.log
/tmp/insighttoolkit20150521-52123-12b47pj/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeError.log: No such file or directory
$

**Comment by dpo** [comment]
Please post the output of `brew gist-logs simpleitk`.

**Comment by dewet22** [comment]
It doesn't yield anything:

```
$ brew update
Already up-to-date.
$ brew upgrade --all
$ brew install simpleitk
==> Installing simpleitk from homebrew/homebrew-science
==> Installing dependencies for simpleitk: insighttoolkit, pcre, swig
==> Installing simpleitk dependency: insighttoolkit
==> Downloading https://downloads.sourceforge.net/project/itk/itk/4.7/InsightToolkit-4.7.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/insighttoolkit-4.7.2.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/insighttoolkit/4.7.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=O
    linked by target "ITKIOTransformHDF5" in directory /tmp/insighttoolkit20150526-73090-11xnkhz/InsightToolkit-4.7.2/Modules/IO/TransformHDF5/src

-- Configuring incomplete, errors occurred!
See also "/tmp/insighttoolkit20150526-73090-11xnkhz/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/insighttoolkit20150526-73090-11xnkhz/InsightToolkit-4.7.2/itk-build/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

$ brew gist-logs simpleitk
Error: No logs.
$
```

**Comment by dewet22** [comment]
When I untar the cached tarball and run cmake with the same command-line as above, it seems to configure just fine.

**Comment by dpo** [comment]
Sorry, my fault. It's `insighttoolkit` that fails. Try `brew gist-logs insighttoolkit`.

**Comment by dewet22** [comment]
Ah! Now we have something:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_hdf5_cpp_LIBRARY
    linked by target "ITKIOHDF5" in directory /tmp/insighttoolkit20150526-73090-11xnkhz/InsightToolkit-4.7.2/Modules/IO/HDF5/src
    linked by target "ITKIOHDF5" in directory /tmp/insighttoolkit20150526-73090-11xnkhz/InsightToolkit-4.7.2/Modules/IO/HDF5/src
    linked by target "ITKIOTransformHDF5" in directory /tmp/insighttoolkit20150526-73090-11xnkhz/InsightToolkit-4.7.2/Modules/IO/TransformHDF5/src
```

Gist log at https://gist.github.com/dewet-turn/1e69756f8761e58b0952

**Comment by iMichka** [comment]
Hi. Maybe try to uninstall/reinstall hdf5. Did you pass any specific options to your hdf5 installation ?

There were also some major improvements to hdf5 for the next ITK 4.8 release. You may try to install with: ```brew install insighttoolkit --HEAD```

**Comment by dewet22** [comment]
Reinstalling hdf5 seems to have been the thing indeed!

```
$ brew uninstall hdf5
Uninstalling /usr/local/Cellar/hdf5/1.8.14... (118 files, 9.9M)
$ brew install simpleitk
==> Installing simpleitk from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/simpleitk: hdf5, insighttoolkit, pcre, swig
==> Installing homebrew/science/simpleitk dependency: hdf5
==> Downloading https://homebrew.bintray.com/bottles-science/hdf5-1.8.14.yosemite.bottle.2.tar.gz
######################################################################## 100.0%

==> Pouring hdf5-1.8.14.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/hdf5/1.8.14: 174 files, 11M
==> Installing homebrew/science/simpleitk dependency: insighttoolkit
==> Downloading https://downloads.sourceforge.net/project/itk/itk/4.7/InsightToolkit-4.7.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/insighttoolkit-4.7.2.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/insighttoolkit/4.7.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD
==> make install
🍺  /usr/local/Cellar/insighttoolkit/4.7.2: 4485 files, 84M, built in 10.0 minutes
...
```
