### ISSUE TITLE
Track revisions for GCC 5

### ISSUE THREAD

**Issue by iml** [Homebrew/homebrew-science#2297]
~~Part 1: #2295~~
~~Part 2: #2296~~
~~Part 3: #2301~~
~~Part 4: #2303~~
~~Part 5: #2318~~
~~#2317~~

- [x] abinit
- [x] arpack
- [x] atomic-pseudopotential-engine
- ~~cgns~~
- ~~cmor~~
- ~~coinmp~~
- ~~coinutils~~
- ~~dotwrp~~
- ~~dynare~~
- [x] etsf_io
- [x] fgsl
- ~~getdp~~
- [x] gmsh
- [x] hopdm
- [x] hypre
- [x] ipopt
- ~~itsol~~
- [x] lammps
- ~~libctl~~
- ~~lis~~
- ~~mfusg~~
- ~~moab~~
- [x] mumps
- [x] octave
- [x] openblas
- ~~p4est~~
- [x] pastix
- [x] petsc
- ~~plink2~~
- ~~propack~~
- [x] qr_mumps
- [x] qrupdate
- [x] r
- ~~salt~~
- [x] scalapack
- [x] slepc
- ~~slicot~~
- [x] snid
- [x] superlu
- [x] superlu_dist
- [x] tisean
- ~~trilinos~~
- [x] veclibfort
- [x] xmi-msima

**Comment by dpo** [comment]
`trilinos` can be removed from the list as it takes more than 2 hours to build. It can't be bottled.

**Comment by dpo** [comment]
Here's a suggestion of the order in which they should be updated. I ticked those you have pushed already.

#### those for which order matters:

- [X] arpack
- [ ] etsf_io
- [X] fgsl
- [ ] gmsh
- [ ] hypre
- [ ] mumps
- [X] octave
- [X] openblas
- [ ] petsc
- [X] qrupdate
- [X] scalapack
- [ ] slepc
- [X] superlu
- [X] superlu_dist
- [X] veclibfort

#### those for which order doesn't matter (after those above have been installed):

- [ ] abinit
- [ ] atomic-pseudopotential-engine
- [ ] cgns
- [ ] cmor
- [ ] coinmp
- [ ] coinutils
- [ ] dotwrp
- [ ] dynare
- [ ] getdp
- [ ] hopdm
- [ ] ipopt
- [ ] itsol
- [ ] lammps
- [ ] libctl
- [ ] lis
- [ ] mfusg
- [ ] moab
- [ ] p4est
- [ ] pastix
- [ ] platanus
- [ ] plink2
- [ ] propack
- [ ] qr_mumps
- [X] r
- [ ] salt
- [ ] slicot
- [ ] snid
- [X] tisean
- [ ] ~~trilinos~~
- [X] xmi-msim

**Comment by iml** [comment]
Thanks, trying that batch now.

**Comment by iml** [comment]
Many of these aren't dynamically linked with gfortran, so for sanity I'm going to avoid those and also focus on bottled formulae.

**Comment by DomT4** [comment]
`snid` is linked apparently:

```
==> brew test --verbose snid						 FAILED
Testing snid
==> /usr/local/Cellar/snid/5.0_1/bin/snid inter=0 plot=0 /usr/local/Cellar/snid/5.0_1/test/sn2003jo.dat
dyld: Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/snid/5.0_1/bin/snid
  Reason: image not found
Error: snid: failed
```

**Comment by iml** [comment]
Thanks, added.
