### ISSUE TITLE
Add poretools formula to homebrew-science

### ISSUE THREAD

**Issue by gawbul** [Homebrew/homebrew-science#2299]
I've been working on a formula for [poretools](http://poretools.readthedocs.org/en/latest/index.html) today, but before submitting a pull request, I wanted to get some feedback on the formula, as its the first full formula I've created.

See https://gist.github.com/gawbul/17de72ef7a22db8de4c9.

Any comments/suggestions appreciated.

**Comment by dpo** [comment]
If you actually submit a PR, then we can insert comments directly in your code. Before doing so, please run `brew audit --strict your_formula.rb`.

**Comment by gawbul** [comment]
Thanks for the advice. I ran it and cleaned up all the recommendations, though it is still complaining that ` * `require "formula"` is now unnecessary` even though I have it in the file?

**Comment by gawbul** [comment]
Closing so comments can be made on PR https://github.com/Homebrew/homebrew-science/pull/2300
