### ISSUE TITLE
OpenCV 3 python bindings fail to build when Homebrew Python is installed

### ISSUE THREAD

**Issue by acdha** [Homebrew/homebrew-science#2302]
`brew install opencv --devel` currently fails to build the Python bindings at all if you have python installed from the main Homebrew. 

It detects the python binary in `/usr/local/bin` but when it runs `python-config` to get the lib and include paths it's apparently using a restricted `PATH` so it runs the system `/usr/bin/python-config` instead of `/usr/local/bin/python-config`, which returns the library under `/System/Library` which fails because it's for an older version (2.7.6) than `/usr/local/bin/python` (2.7.9).

The failing cmake invocation looks like this:
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_OSX_DEPLOYMENT_TARGET= -DBUILD_ZLIB=OFF -DBUILD_TIFF=OFF -DBUILD_PNG=OFF -DBUILD_OPENEXR=OFF -DBUILD_JASPER=OFF -DBUILD_JPEG=OFF -DJPEG_INCLUDE_DIR=/usr/local/opt/jpeg/include -DJPEG_LIBRARY=/usr/local/opt/jpeg/lib/libjpeg.dylib -DBUILD_opencv_python2.7.9=ON -DBUILD_opencv_java=OFF -DWITH_OPENEXR=ON -DWITH_EIGEN=ON -DWITH_TBB=ON -DWITH_FFMPEG=OFF -DWITH_QUICKTIME=OFF -DWITH_1394=OFF -DWITH_OPENGL=OFF -DWITH_JASPER=OFF -DWITH_QT=OFF -DWITH_GSTREAMER=OFF -DPYTHON2.7.9_LIBRARY=/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DPYTHON2.7.9_INCLUDE_DIR=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DWITH_CUDA=OFF -DENABLE_SSSE3=ON -DENABLE_SSE41=ON -DENABLE_SSE42=ON -DENABLE_AVX=ON
```

```
--   OpenCV modules:
--     To be built:                 hal core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d stitching videostab
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 androidcamera cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 python3 viz
…
--   Python 2:
--     Interpreter:                 /usr/local/bin/python2.7 (ver 2.7.9)
--     Libraries:                   NO
--     numpy:                       /usr/local/lib/python2.7/site-packages/numpy/core/include (ver 1.9.2)
--     packages path:               lib/python2.7/site-packages
```

(Full log: https://gist.github.com/acdha/ff701837e975075e4fc0)

If you kludge it by changing https://github.com/Homebrew/homebrew-science/blob/db5c2a0d62ed2d87e88c4ae4504750a6a2c921ff/opencv.rb#L108 to hard-code `/usr/local/bin/python-config` the relevant cmake output looks like this and everything works:

```
--   Python 2:
--     Interpreter:                 /usr/local/bin/python2.7 (ver 2.7.9)
--     Libraries:                   /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (ver 2.7.9)
--     numpy:                       /usr/local/lib/python2.7/site-packages/numpy/core/include (ver 1.9.2)
--     packages path:               lib/python2.7/site-packages
```
(Full log: https://gist.github.com/a6f25407c2e19c21ded1)

(OS X 10.10.3, current XCode, current brew, `brew doctor` reports no issues, etc.)

**Comment by tdsmith** [comment]
Thanks for the report!

> It detects the python binary in /usr/local/bin

IMO this is an opencv bug; opencv's build system should respect PATH. It is correct that Homebrew will always build bindings against system Python; they will subsequently work with any other Python 2.7.

**Comment by tdsmith** [comment]
Also, Homebrew should find a way to discourage this:

> -- ICV: Downloading ippicv_macosx_20141027.tgz...

**Comment by tdsmith** [comment]
OpenCV is ultimately relying on cmake's find_program for "python". The find_program precedence is explained here: http://www.cmake.org/cmake/help/v3.0/command/find_program.html

Adding `-DCMAKE_PREFIX_PATH=#{py_prefix}` to `args` (if `OS.mac?`) convinces cmake to do the right thing and should be harmless.
