### ISSUE TITLE
Formulae that can make use of OpenMP

### ISSUE THREAD

**Issue by dpo** [Homebrew/homebrew-science#2315]
In prevision of `clang` supporting OpenMP directives in a forthcoming release (see [this PR](https://github.com/Homebrew/homebrew/pull/39789#issuecomment-104886639)):

- [x] abinit.rb
- [x] abyss.rb
- [x] adol-c.rb
- [x] cd-hit.rb
- [x] cppad.rb
- [x] fasttree.rb
- [x] gal-sim.rb
- [x] harry.rb
- [ ] ~~hyphy.rb~~ (not clear that it makes sense)
- [x] idba.rb
- [ ] lammps.rb (apparently gives build failure)
- [x] mathgl.rb
- [x] metis.rb
- [x] nfft.rb
- [x] oases.rb
- [x] phlawd.rb
- [ ] propack.rb (needs a complete revision)
- [ ] ~~stacks.rb~~
- [x] sundials.rb
- [ ] symphony.rb (will be migrated to another tap)
- [x] tmv-cpp.rb
- [x] trilinos.rb
- [x] trinity.rb
- [x] velvet.rb
- [x] viennarna.rb
- [x] xrmc.rb

Edit: eliminated formulae that `needs :openmp`

**Comment by tseemann** [comment]
Won't be still need the directive in case people haven't upgraded clang?

**Comment by fran6co** [comment]
pcl supports openmp too

**Comment by sjackman** [comment]
ABySS supports OpenMP.
```ruby
  option "with-openmp", "Enable OpenMP multithreading"
  needs :openmp if build.with? "openmp"
```

**Comment by dpo** [comment]
I'm going to close this as the formulae that are left need more drastic measures.
