### ISSUE TITLE
brew install MUMPS fails

### ISSUE THREAD

**Issue by K0stIa** [Homebrew/homebrew-science#2327]
Hey guys,

brew fails to install lpopt and
brew gist-logs ipopt says Error: No logs.

Any ideas?
Thanks.

==> Installing ipopt from homebrew/homebrew-science
==> Installing ipopt dependency: mumps
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mumps-5.0.0.tar.gz
==> make alllib LIBEXT=.dylib AR=/usr/local/bin/gfortran -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.0.0_3/lib/$(not
==> make all LIBEXT=.dylib AR=/usr/local/bin/gfortran -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.0.0_3/lib/$(notdir
      _MAIN__ in csimpletest.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [csimpletest] Error 1
make: *** [cexamples] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

**Comment by dpo** [comment]
It's `mumps` that fails. Please try `brew gist-logs mumps`.

**Comment by K0stIa** [comment]
Here is brew gist-logs mumps result.

https://gist.github.com/ccc153dd1cfab29f5a62

**Comment by K0stIa** [comment]
This is strange though. If I do brew install mumps it says me it's installed already.

**Comment by dpo** [comment]
The error is related to gfortran. Try `brew uninstall mumps`. You have stray gfortran libs in your `/usr/local/lib`, perhaps remnants of a non-brew install?! The best would be to get rid of those.

**Comment by K0stIa** [comment]
removing gfortran libs worked out. Can I remove rest of them that brew doctor complains about?

**Comment by dpo** [comment]
Unless they point to something you're using, you can probably remove them. Note that `libpng` and `tcl` can be brewed anyways.
