### ISSUE TITLE
Octave: Upgrade to 4.0.0

### ISSUE THREAD

**Issue by robsonpeixoto** [Homebrew/homebrew-science#2330]
Please, upgrade octave to 4.0.0. It was released http://ftp.gnu.org/gnu/octave/octave-4.0.0.tar.gz

**Comment by tdsmith** [comment]
Care to submit a pull request?

**Comment by robsonpeixoto** [comment]
I'm a complete octave noob. =/

**Comment by mcg1969** [comment]
Then I'm afraid it's going to be awhile. I took a *lot* of time to get the 3.8 formula built. I haven't had success with a 4.0 formula yet.

**Comment by dpo** [comment]
Closing this, as upgrading octave is a long-winded adventure.
