### ISSUE TITLE
pcl --HEAD formula is broken on OS X Yosemite 

### ISSUE THREAD

**Issue by jmtatsch** [Homebrew/homebrew-science#2346]
any ideas how to fix this?

---
brew install homebrew/science/pcl --HEAD -v
==> Installing pcl from homebrew/homebrew-science
==> Cloning https://github.com/PointCloudLibrary/pcl.git
git --git-dir /Library/Caches/Homebrew/pcl--git/.git status -s
Updating /Library/Caches/Homebrew/pcl--git
git config remote.origin.url https://github.com/PointCloudLibrary/pcl.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at b60e20d Merge pull request #1239 from v4hn/point-normal-might-fail
==> Checking out branch master
==> Patching
patching file cmake/pcl_find_cuda.cmake
Hunk #2 succeeded at 45 (offset 8 lines).
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pcl/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_simulation:BOOL=AUTO_OFF -DBUILD_outofcore:BOOL=AUTO_OFF -DBUILD_people:BOOL=AUTO_OFF -DBUILD_global_tests:BOOL=OFF -DWITH_TUTORIALS:BOOL=OFF -DWITH_DOCS:BOOL=OFF -DWITH_CUDA:BOOL=OFF -DBUILD_apps=AUTO_OFF -DBUILD_apps_3d_rec_framework=AUTO_OFF -DBUILD_apps_cloud_composer=AUTO_OFF -DBUILD_apps_in_hand_scanner=AUTO_OFF -DBUILD_apps_modeler=AUTO_OFF -DBUILD_apps_optronic_viewer=AUTO_OFF -DBUILD_apps_point_cloud_editor=AUTO_OFF -DBUILD_examples:BOOL=OFF -DCMAKE_DISABLE_FIND_PACKAGE_OpenNI:BOOL=TRUE ..
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28") 
-- Performing Test HAVE_MM_MALLOC
-- Performing Test HAVE_MM_MALLOC - Success
-- Performing Test HAVE_POSIX_MEMALIGN
-- Performing Test HAVE_POSIX_MEMALIGN - Success
-- Performing Test HAVE_SSE4_2_EXTENSIONS
-- Performing Test HAVE_SSE4_2_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_1_EXTENSIONS
-- Performing Test HAVE_SSE4_1_EXTENSIONS - Success
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Success
-- Performing Test HAVE_SSE2_EXTENSIONS
-- Performing Test HAVE_SSE2_EXTENSIONS - Success
-- Performing Test HAVE_SSE_EXTENSIONS
-- Performing Test HAVE_SSE_EXTENSIONS - Success
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Not found OpenMP
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
-- checking for module 'eigen3'
--   found eigen3, version 3.2.4
-- Found Eigen: /usr/local/include/eigen3  
-- Eigen found (include: /usr/local/include/eigen3, version: 3.2.4)
-- checking for module 'flann>=1.7.0'
--   found flann, version 1.8.4
-- Found FLANN: /usr/local/lib/libflann_cpp.dylib (Required is at least version "1.7.0") 
-- FLANN found (include: /usr/local/include, lib: optimized;/usr/local/lib/libflann_cpp.dylib;debug;/usr/local/lib/libflann_cpp.dylib)
-- Found LIBUSB_1: /usr/local/lib/libusb-1.0.dylib  
-- checking for module 'libusb-1.0'
--   found libusb-1.0, version 1.0.19
-- Found USB_10: /usr/local/lib/libusb-1.0.dylib  
-- Could NOT find OpenNI2 (missing:  OPENNI2_LIBRARY OPENNI2_INCLUDE_DIRS) 
-- Could NOT find FZAPI (missing:  FZAPI_LIBS FZAPI_INCLUDE_DIR) 
-- Could NOT find ensenso (missing:  ENSENSO_LIBRARY ENSENSO_INCLUDE_DIR) 
-- Could NOT find davidSDK (missing:  DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
-- Could NOT find PXCAPI (missing:  PXCAPI_LIBS PXCAPI_INCLUDE_DIRS) 
-- checking for module 'metslib'
--   package 'metslib' not found
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.17") 
-- Found Qhull: /usr/local/lib/libqhull_p.dylib  
-- QHULL found (include: /usr/local/include, lib: optimized;/usr/local/lib/libqhull_p.dylib;debug;/usr/local/lib/libqhull_p.dylib)
-- VTK_MAJOR_VERSION 6
-- VTK found (include: /usr/local/Cellar/vtk/6.2.0/include/vtk-6.2;/usr/include;/usr/local/include;/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7;/usr/include/libxml2, lib: vtkalglib;vtkChartsCore;vtkCommonColor;vtkCommonDataModel;vtkCommonMath;vtkCommonCore;vtksys;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkInfovisCore;vtkFiltersExtraction;vtkCommonExecutionModel;vtkFiltersCore;vtkFiltersGeneral;vtkCommonComputationalGeometry;vtkFiltersStatistics;vtkImagingFourier;vtkImagingCore;vtkRenderingContext2D;vtkRenderingCore;vtkFiltersGeometry;vtkFiltersSources;vtkRenderingFreeType;vtkfreetype;/usr/lib/libz.dylib;vtkftgl;vtkDICOMParser;vtkDomainsChemistry;vtkIOXML;vtkIOGeometry;vtkIOCore;vtkjsoncpp;vtkIOXMLParser;/usr/lib/libexpat.dylib;vtkexoIIc;vtkNetCDF;vtkNetCDF_cxx;/usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/usr/local/lib/libhdf5_hl.dylib;vtkFiltersAMR;vtkParallelCore;vtkIOLegacy;vtkFiltersFlowPaths;vtkFiltersGeneric;vtkFiltersHybrid;vtkImagingSources;vtkFiltersHyperTree;vtkFiltersImaging;vtkImagingGeneral;vtkFiltersModeling;vtkFiltersParallel;vtkFiltersParallelImaging;vtkFiltersProgrammable;vtkFiltersPython;/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib;vtkWrappingPythonCore;vtkWrappingTools;vtkFiltersSelection;vtkFiltersSMP;vtkFiltersTexture;vtkFiltersVerdict;verdict;vtkGeovisCore;vtkInfovisLayout;vtkImagingHybrid;vtkIOImage;vtkmetaio;/usr/local/lib/libjpeg.dylib;/usr/local/lib/libpng.dylib;/usr/local/lib/libtiff.dylib;vtkInteractionStyle;vtkInteractionWidgets;vtkRenderingAnnotation;vtkImagingColor;vtkRenderingVolume;vtkViewsCore;vtkproj4;vtkgl2ps;vtkGUISupportQt;vtkRenderingOpenGL;vtkGUISupportQtOpenGL;vtkGUISupportQtSQL;vtkIOSQL;vtksqlite;vtkGUISupportQtWebkit;vtkViewsQt;vtkViewsInfovis;vtkRenderingLabel;vtkImagingMath;vtkImagingMorphological;vtkImagingStatistics;vtkImagingStencil;vtkInfovisBoostGraphAlgorithms;vtkInteractionImage;vtkIOAMR;vtkIOEnSight;vtkIOExodus;vtkIOExport;vtkRenderingGL2PS;vtkRenderingContextOpenGL;vtkIOImport;vtkIOInfovis;/usr/lib/libxml2.dylib;vtkIOLSDyna;vtkIOMINC;vtkIOMovie;vtkoggtheora;vtkIONetCDF;vtkIOParallel;vtkIOParallelXML;vtkIOPLY;vtkIOVideo;vtkRenderingFreeTypeFontConfig;vtkRenderingFreeTypeOpenGL;vtkRenderingImage;vtkRenderingLIC;vtkRenderingLOD;vtkRenderingQt;vtkRenderingVolumeOpenGL;vtkViewsContext2D
-- Found PCAP: /usr/lib/libpcap.dylib  
CMake Error at apps/modeler/CMakeLists.txt:100 (QT4_WRAP_UI):
  Unknown CMake command "QT4_WRAP_UI".

-- Configuring incomplete, errors occurred!
See also "/tmp/pcl20150602-36845-1bud23d/macbuild/CMakeFiles/CMakeOutput.log".
See also "/tmp/pcl20150602-36845-1bud23d/macbuild/CMakeFiles/CMakeError.log".
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007fab931bdca8>::Pcl (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure

**Comment by dpo** [comment]
`HEAD` can be a moving target. Are you able to build without `--HEAD`?

For future reference, please post build logs as gists, so as to not clutter the discussion.

**Comment by jmtatsch** [comment]
Yes building without `--HEAD` works, but  `--HEAD` seems to be needed for ROS compatibility...

**Comment by jmtatsch** [comment]
Building from trunk according to http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php#compiling-pcl-posix still works

**Comment by markusachtelik** [comment]
compiles with ```--HEAD --without-apps``` . not really nice though

**Comment by markusachtelik** [comment]
```--without-apps``` didn't do the trick, since some ros dependencies were missing the apps-lib. The main offender was apps/modeler, it seems like some QT checking/loading variables is not right. I disabled only modeler for now: https://github.com/markusachtelik/homebrew-science/commit/68175ddf1b6a8be3412e544781f4a025396f04de builds and ros-nodes seem to run

**Comment by dpo** [comment]
Please post the output of `brew gist logs`.

**Comment by markusachtelik** [comment]
https://gist.github.com/af522d08c6c2e107e958 

this may be related: http://answers.ros.org/question/211546/fatal-error-qmetatype-file-not-found-when-building-ros-indigo-on-os-x-10103/

**Comment by dpo** [comment]
Are those the right logs? I'm not seeing any error. I meant for @jmtatsch to post the logs that caused the build error.

**Comment by markusachtelik** [comment]
ahhh, sorry, I though you meant the ones that did the trick ;)

**Comment by fran6co** [comment]
Sorry for taking so long but I have been busy. Just submitted a PR with the fix

**Comment by tdsmith** [comment]
Closed by #2482.
