### ISSUE TITLE
lnstalling new lammps user modules with Hombrew

### ISSUE THREAD

**Issue by mcfwander** [Homebrew/homebrew-science#2354]
The standard lammps installation works fine. However, we are trying to code a new pair style for lammps. We have placed it in a subdirectory of the lamps--git/src/ directory called USER-VMM. How do we tell homebrew to compile this additional code?

thanks much
matthew

**Comment by tdsmith** [comment]
You would have to edit the part of the formula that enables and disables different modules. I can't offer much support for this use case.

**Comment by mcfwander** [comment]
We already edited the lammps.rb file to include a line for user-vmm but that appears to be insufficient. Any ideas?

**Comment by tdsmith** [comment]
None, sorry. Please let us know if there's anything in particular we can help with.
