### ISSUE TITLE
Clarification of formula style

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2380]
Lately I've gotten corrections about style in my submitted formulae. I tend to use other formula to base my new formula on where I am learning a new technique, but many of these are old formula and conventions have changed. So here I list the things I have learnt, and seek your feedback on their correctness:

* do **not** put ```require "formula.rb"``` at top anymore
* no blank line at top
* use ```if OS.mac? ... else ... end``` and assume Linux is fallback
* use ```sha256``` not ```sha1```
* add a ```desc "xxxx"``` as first tag
* use double-quotes instead of single-quotes wherever possible
* don't put spaces around the slash in ```(share/"package").install```
* put ```# doi``` before ```# tag``` (alphabetical order?)
* remember to run ```brew style formula.rb``` before submitting
* remember to run ```brew audit --strict formula.rb``` before submitting 

That's all I can think of for now.

**Comment by dpo** [comment]
`brew style` and `brew audit --strict` should really tell you almost all there is to know.

**Comment by iml** [comment]
>* use ```if OS.mac? ... else ... end``` and assume Linux is fallback

Could just as well be the inverse: assuming Mac to be the fallback from `OS.linux?`. If unsure, I'd just stick with whatever works simply with `if`.

**Comment by dpo** [comment]
@tseemann I'd suggest adding what's missing to the general formula howto and closing this if that's ok. `brew audit --strict --online` really tells everything.

**Comment by tseemann** [comment]
@dpo can you link the specific page here please?

**Comment by dpo** [comment]
I had https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md in mind.

**Comment by dpo** [comment]
I'm going to close this since `brew audit` handles everything.
