### ISSUE TITLE
r math standalone cannot be linked successfully

### ISSUE THREAD

**Issue by nilsbecker** [Homebrew/homebrew-science#2382]
I installed `R` `--with-librmath-only` and then tried to use it as a dynamic library, without success. See this SO question http://stackoverflow.com/questions/30706284/call-rmath-via-ctypes-from-ocaml-on-os-x . 
Xcode complains about missing `R_ext/Boolean.h`, the issue seems to be in this section of `Rmath.h`: 

    #ifdef MATHLIB_STANDALONE
    # ifndef R_EXT_BOOLEAN_H_
    /* "copy-paste" R_ext/Boolean.h if not already included: */
     #define R_EXT_BOOLEAN_H_
     #undef FALSE
     #undef TRUE
     typedef enum { FALSE = 0, TRUE } Rboolean;
    # endif
    #else
    # include <R_ext/Boolean.h>
    #endif

It seems as if MATHLIB_STANDALONE is not defined? But it should be if Rmath is used as a standalone library? Here is the test program

    #include <stdio.h>
    #include "Rmath.h"
    
    int main(int argc, const char * argv[]) {
        // insert code here...
        printf("Hello, World!\n");
        return pow_di(4.5, 2);
    }

**Comment by tdsmith** [comment]
I think that definition is the calling program's responsibility, per https://stat.ethz.ch/pipermail/r-help/2006-March/100604.html (Dirk is a core R contributor) and http://stat-www.berkeley.edu/classes/s243/rmath.html -- let me know if you can find documentation to the contrary or if we can help with anything else.

**Comment by nilsbecker** [comment]
wow, ok. thanks. if that's indeed so, then maybe these lines at the top of Rmath.h should be changed.

     * Rmath.h  should contain ALL headers from R's C code in `src/nmath'
       -------  such that ``the Math library'' can be used by simply

       ``#include <Rmath.h> ''

       and nothing else.

**Comment by tdsmith** [comment]
We just package it :) One of the R mailing lists would be a great place to make that suggestion.
