### ISSUE TITLE
htslib, bcftools: Don't override version

### ISSUE THREAD

**Issue by jmarshall** [Homebrew/homebrew-science#2389]
Summary: Please revert #733.

Prior to their initial 1.0 releases, development snapshots of htslib and bcftools correctly reported their versions as an early-development `0.0.1`.  Since the initial 1.0 release, the relevant makefile machinery has been updated to report the new version number with each release.

So overriding this in your formulae hasn't been necessary for many months.  Hence it would be good to remove the two lines in each formula added by 1e972cb4d2e720bc3e351d41214ee455fb40dba0.

**Comment by tseemann** [comment]
@jmarshall I've patched this, but also found an issue on your side: https://github.com/samtools/bcftools/issues/280

**Comment by tseemann** [comment]
I've now patched for htslib as well.

**Comment by jmarshall** [comment]
The htsfile documentation is clear that htsfile "identif[ies] high-throughput sequencing data files"; it is not a replacement for file(1).  It is for exercising htslib's `hts_format` machinery and for pipeline authors who apparently want to distinguish between SAM/BAM/CRAM.  So if your test is being limited by it reporting random non-bioinformatics text files as SAM, then you're testing the wrong thing.

(That said, as noted in the FIXME I pointed you at in that issue, I do intend to make it smarter about text files.  That's in progress and may make it into the next release.)

**Comment by tseemann** [comment]
Thanks for the heads up @jmarshall - all fixed now.
