### ISSUE TITLE
opencv should link against libc++ for recent CUDA

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2390]
Failed installation 1
-------------------------

    brew install opencv --c++11 --with-cuda --with-opengl --with-qt --with-tbb

and the installation failed. Here is the [relevant gist-log](https://gist.github.com/anonymous/7367bf3f15b23e414aba). It appears it failed to find qt5, even though I have it installed as well.

Failed installation 2
-------------------------
    brew install opencv --c++11 --with-cuda --with-opengl --with-tbb

[Failed installation 2 gist](https://gist.github.com/c257708b05adf8e6c961)

**Comment by tdsmith** [comment]
First failure: looks like the meaning of WITH_QT changed from qt4 to qt5 and we didn't catch up; we should figure out what the right switch for qt4 is and add a qt5 option.

Second failure: error is
```
In file included from /tmp/opencv20150609-22080-1b9t8rs/opencv-2.4.11/modules/flann/src/miniflann.cpp:1:
In file included from /tmp/opencv20150609-22080-1b9t8rs/opencv-2.4.11/modules/flann/src/precomp.hpp:21:
In file included from /tmp/opencv20150609-22080-1b9t8rs/opencv-2.4.11/modules/flann/include/opencv2/flann/all_indices.h:42:
In file included from /tmp/opencv20150609-22080-1b9t8rs/opencv-2.4.11/modules/flann/include/opencv2/flann/lsh_index.h:49:
/tmp/opencv20150609-22080-1b9t8rs/opencv-2.4.11/modules/flann/include/opencv2/flann/lsh_table.h:49:10: fatal error: 'unordered_map' file not found
#include <unordered_map>
         ^
```

Not sure what's going on but it seems weird that opencv is requesting `-stdlib libstdc++`.

**Comment by tdsmith** [comment]
Though can I ask why you're building with --c++11? The libraries are always built against libc++ on Mavericks and newer. Does the build succeed without it?

**Comment by iml** [comment]
> Not sure what's going on but it seems weird that opencv is requesting `-stdlib libstdc++`.

It's from the with-cuda option.

**Comment by tdsmith** [comment]
Oh, so it is. That's sad. I was wrong just above and `--with-cuda` and `--c++11` are incompatible, then.

**Comment by tdsmith** [comment]
The Qt stuff is working fine; both builds failed for the same reason, which is that you can't use cuda with libc++. Let us know if we can help with anything else.

**Comment by ahundt** [comment]
I don't think that is the case with the latest CUDA 7, which I have installed.

https://groups.google.com/forum/#!topic/caffe-users/HX6Tz3ggfSc

**Comment by ahundt** [comment]
From the horse's mouth:

http://devblogs.nvidia.com/parallelforall/cuda-7-release-candidate-feature-overview/

**Comment by tdsmith** [comment]
Great, thanks. How many CUDA users will be using CUDA 7? Should we attempt to detect CUDA version?

**Comment by ahundt** [comment]
I'm actually new to CUDA so I'm able to start with the latest version. Sorry that I can't answer that reliably.

**Comment by tdsmith** [comment]
The `opencv3` formula should handle this now.

**Comment by ahundt** [comment]
@tdsmith Thanks for working on progressing this issue! 

I tested the updates specified in #2398 and encountered a compiler error while some of the cuda components were being compiled. Here is the related [homebrew gist](https://gist.github.com/f22d34bb08dcb942ae5f).

My specific install command in this case was

    ± brew install opencv3 --c++11 --with-cuda --with-contrib --with-tbb --with-qt5 --with-gstreamer --with-opengl --with-openni

**Comment by ahundt** [comment]
I also ran without cuda since the compiler error seemed to be cuda related and an error still occurred.

[homebrew gist](https://gist.github.com/2e7c039750095f7078fc)

command:

    brew install opencv3 --c++11 --with-contrib --with-tbb --with-qt5 --with-gstreamer --with-opengl --with-openni

**Comment by ahundt** [comment]
The following worked, so the bugs lie somewhere in between the flags with failures above and this set of flags:

    brew install opencv3 --c++11 --with-contrib

**Comment by tdsmith** [comment]
I commented in #2391. I don't see a CUDA-related error in your logs. Is this working now?

**Comment by autosquid** [comment]
to further narrow the issue without cuda:

`brew install opencv3 --c++11 --with-qt5 --with-opengl --with-tbb` works
brew install opencv3 --with-contrib --c++11 --with-qt5 --with-opengl --with-tbb` does not work

**Comment by tdsmith** [comment]
@autosquid See https://github.com/Homebrew/homebrew-science/issues/2391#issuecomment-112959270 and https://github.com/Itseez/opencv_contrib/issues/272 -- the combination of contrib and Qt is broken.

**Comment by tdsmith** [comment]
I didn't see a response to my question in June about whether this is working now so I assume that it is. Let me know if it's still broken.
