### ISSUE TITLE
opencv_contrib support

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2391]
Is it possible for the [opencv build](https://github.com/Homebrew/homebrew-science/blob/master/opencv.rb) to include and option for the [opencv_contrib](https://github.com/Itseez/opencv_contrib) repository, which includes new and upcoming library modules?

**Comment by tdsmith** [comment]
Do you intend to use them? I see they have versioned releases so it's not out of the question.

**Comment by ahundt** [comment]
Yes, I'm intending to use them.

**Comment by ahundt** [comment]
@tdsmith Thanks for working on progressing this issue! 

I tested the updates specified in #2398 and encountered a compiler error while some of the cuda components were being compiled. Here is the related [homebrew gist](https://gist.github.com/f22d34bb08dcb942ae5f).

My specific install command in this case was

    ± brew install opencv3 --c++11 --with-cuda --with-contrib --with-tbb --with-qt5 --with-gstreamer --with-opengl --with-openni

**Comment by ahundt** [comment]
Actually, this is probably more appropriately addressed in #2390 I added the same comment over there.

**Comment by tdsmith** [comment]
Contrib seems broken (maybe only with Qt?):

```
In file included from /tmp/opencv320150617-87721-1o80hb4/opencv-3.0.0/opencv_contrib/modules/cvv/src/controller/view_controller.cpp:12:
In file included from /tmp/opencv320150617-87721-1o80hb4/opencv-3.0.0/opencv_contrib/modules/cvv/src/controller/../gui/overview_panel.hpp:12:
/tmp/opencv320150617-87721-1o80hb4/opencv-3.0.0/opencv_contrib/modules/cvv/src/controller/../gui/../stfl/stfl_engine.hpp:1056:30: error: use 'template' keyword to treat 'value' as a dependent template name
                return settings.value(key).value<QStringList>();
                                           ^
                                           template 
```

I don't think this is Homebrew-related. You can check if it's fixed in --HEAD; if it isn't, please report it to opencv-contrib.

**Comment by tdsmith** [comment]
Incidentally, `--c++11` should be a no-op on 10.9+.

**Comment by tdsmith** [comment]
Closing since support was added.
