### ISSUE TITLE
poretools - pkg_resources.DistributionNotFound: h5py>=2.0.0

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2392]
@gawbul  - It seemed to finish installing but running/testing it gives this error:

```
Traceback (most recent call last):
  File "/bio/linuxbrew/Cellar/poretools/0.5.1/libexec/bin/poretools", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/bio/python/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/bio/python/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/bio/python/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: h5py>=2.0.0
```

Here are the logs: https://gist.github.com/8b00ddc495ab8d656503

Here's a bit of the logs it must be related to:

```
running build_ext
Autodetection skipped [libhdf5.so: cannot open shared object file: No such file or directory]
```

I'm on Linux and not using the Python formula (because it is still broken with SSL) so I have it separately installed.

**Comment by tdsmith** [comment]
The h5py module is installing to "lib64/..." instead of "lib/..." so it's missing from PYTHONPATH. :/ Should it be doing that?

**Comment by gawbul** [comment]
@tseemann Sorry you're having issues with it. I've not managed to test it with linuxbrew yet. Will have a look at it this week.

**Comment by gawbul** [comment]
I think the brew installed version of `hdf5` is conflicting. I should probably add an `if OS.linux?` section in there to install HDF5? Or perhaps append `if OS.mac?` to `depends_on "hdf5"`?

**Comment by gawbul** [comment]
Adding the following didn't seem to make a difference:

```
if OS.linux?
  ENV.prepend "LDFLAGS", "-L" + Formula["hdf5"].lib
  ENV.prepend "CPPFLAGS", "-I" + Formula["hdf5"].include
```

**Comment by gawbul** [comment]
Strange! Compiling h5py manually using `LDFLAGS` and `CPPFLAGS` against the brew installed `hdf5` worked?

**Comment by gawbul** [comment]
I wonder if setting `HDF5INCLUDEDIR` and `HDF5LIBDIR` might help?

**Comment by tseemann** [comment]
I've just encountered this lib64 vs lib problem again on Linux :-(

See https://github.com/Homebrew/linuxbrew/issues/443

**Comment by gawbul** [comment]
Ah, thanks @tseemann and good call from @tdsmith. Will have a look over this when I get chance. Busy with viva prep this week :worried:

**Comment by gawbul** [comment]
Would amending `PYTHONPATH` in the formula fix this I wonder? E.g. `ENV.prepend_create_path "PYTHONPATH", libexec/"vendor/lib64/python2.7/site-packages"`
