### ISSUE TITLE
science/Blasr failed to build on 10.10.3"

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#2393]
_From @LCrossman on June 10, 2015 11:46_

failed to build, requires HDF5 libraries which are installed and working under a python program with fast5py module.

https://gist.github.com/anonymous/09687cab230ea0b29758

_Copied from original issue: Homebrew/homebrew#40549_

**Comment by iMichka** [comment]
Blasr is sort of dead, see #4254. Maybe we should remove it completely but for the moment the formula can stay as-is until somebody wants to work on this.
