### ISSUE TITLE
spades error on install Ubuntu 12.04

### ISSUE THREAD

**Issue by jrherr** [Homebrew/homebrew-science#2394]
Not sure what I am doing wrong -- should have gcc-4.7 and gcc-4.8 working just fine here.  

```
brew install spades
==> Installing spades from homebrew/homebrew-science
==> Downloading http://spades.bioinf.spbau.ru/release3.5.0/SPAdes-3.5.0.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/spades-3.5.0.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/home/ubun
  CMakeLists.txt:45 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/spades20150610-22049-2mofmo/SPAdes-3.5.0/src/build/CMakeFiles/CMakeOutput.log".
```

I can also post response from `brew install -vd spades`.  Any idea what I am doing wrong?

**Comment by iml** [comment]
Please post the output of `brew gist-logs spades`.

**Comment by jrherr** [comment]
Thanks -- didn't know about that `brew` feature!  [Here's the logs](https://gist.github.com/jrherr/bdc33b4771be2a32758e).  Thanks for all your help @iml!

**Comment by iml** [comment]
> The C compiler identification is GNU 4.6.3

Looks like it requires 4.7 but is using the older compiler from /usr/bin. Can you try with `--cc=gcc-4.8`?

**Comment by jrherr** [comment]
@iml, Thanks for your help!  This ran last night and everything went smoothly.  Thanks again!
