### ISSUE TITLE
octave failed to upgrade

### ISSUE THREAD

**Issue by jotwo** [Homebrew/homebrew-science#2401]
Hi,

I needed to use octave for the first time in months and I wasn't able to launch it. So I have updated and upgraded all the formulas I could on my system (after fixing some permissions and linking issues) but now octave doesn't want to upgrade. It seems that the problem is linked with gfortran but it is installed.

Here is the gist: https://gist.github.com/anonymous/6c770a85f6b3a367bd06

Thank you if you can help!

**Comment by dpo** [comment]
What is `ls -l /usr/local/bin/gfortran`?

**Comment by tdsmith** [comment]
> dyld: Library not loaded: /usr/local/lib/libisl.10.dylib
  Referenced from: /usr/local/Cellar/gcc/4.9.1/libexec/gcc/x86_64-apple-darwin13.2.0/4.9.1/f951
  Reason: image not found
gfortran: internal compiler error: Trace/BPT trap: 5 (program f951)

You should upgrade gcc and each of `brew deps gcc`. If you need gcc 4.9, you can additionally install the `homebrew/versions/gcc49` formula.

**Comment by jotwo** [comment]
Thanks a lot for replying!
@dpo: lrwxr-xr-x  1 Jo  admin  32 12 jui 15:10 /usr/local/bin/gfortran -> ../Cellar/gcc/4.9.1/bin/gfortran
@tdsmith gcc and all the listed dependecies (gmp, isl, libmpc, mpfr, xz) are up-to-date (at least it is what homebrew is telling me)... I think gcc 4.9(.1) is already installed, isn't it?

**Comment by tdsmith** [comment]
Current gcc is version 5.1; have you run `brew update` recently?

**Comment by jotwo** [comment]
Of course. Also up-to-date. Gcc is not shown as outdated...

**Comment by jotwo** [comment]
Ok it's really really weird. In my cellar I had several gcc versions (including 4.9 and 5.1) but the  compilers in /usr/local/bin were symlinked to executables of the version 4.9.1... I've run `brew unlink gcc` than `brew link gcc` but it linked again to version 4.9. How can that happen if I have a more recent version in my Cellar (I noticed after that that I also had other formula linked to older older versions although newer versions were installed)? Trying to solve this issue I've run `brew cleanup gcc` to only keep the more recent version and again `brew link gcc`. It worked this time but I really don't know why it didn't using only `unlink` and `link` so if somebody know...
After that i unlinked octave and upgraded it. It also completed but I had this message: 
>Warning: homebrew/science/octave dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.

If I understand well they are telling me that I compiled GCC with clang but I don't see how I could have done otherwise if clang is the only C++ complier installed with XCode at the beginning. Should i worry about this message?

**Comment by dpo** [comment]
No, the message shouldn't worry you. Does octave build and run now?

**Comment by jotwo** [comment]
Yes. I just don't understand why it did not link to the most recent version in the Cellar...

**Comment by iml** [comment]
`link` and `unlink` will only affect the pinned package version, which in this case was likely 4.9.1. Usually the newer version is pinned and linked upon upgrade, so I'm not exactly sure what happened, but you can use `brew switch` to pick the version that will be linked. IMO it's better just to cleaup those older versions and keep the latest one, as you have done, because all the bottles are built against the latest versions. Older versions are maintained as different formulae.

**Comment by jotwo** [comment]
Thanks!

**Comment by bugkiwi** [comment]
1. find where is `ls -l /usr/local/bin/gfortran`, that should been a soft link refer to a gfortran.
![image](https://cloud.githubusercontent.com/assets/1936250/21874729/c84481d6-d8b1-11e6-95bc-fbcc5a605bf8.png)

2. remove it and 
3. use `ln` to give a new link to your `gcc gfortran`, it looks like 
```
ln -s ../Cellar/gcc/5.3.0/bin/gfortran /usr/local/bin/gfortran
```

and everything work well.
