### ISSUE TITLE
Petsc version

### ISSUE THREAD

**Issue by timmyL17** [Homebrew/homebrew-science#2433]
Version 3.6 of Petsc is out. (I'm not sure if this is the correct place to report outdated formulae, let me know if there's a preferred way).

**Comment by dpo** [comment]
I might get to it in the next few days. In the mean time, the best way to get the formula updated is to submit a PR.

**Comment by vhuber** [comment]
@timmyL17 Are you working on a PR ? (No need to make the work twice) 
I'm interested on the last PETSc version.

**Comment by timmyL17** [comment]
@vhuber No, I haven't started on a PR.

**Comment by vhuber** [comment]
@timmyL17 Ok. I've found the doc about making a PR for homebrew, do you know if there is any differences for homebrew-science ?

**Comment by davydden** [comment]
it's very likely that the only thing you would need to change is a link to the file and its sha256. How to contribute is discussed in three links on this page: https://github.com/Homebrew/homebrew-science/wiki/Maintainers  In a nutshell:  you fork homebrew-science, create a branch, commit changes and create a PR. 
p.s. according to the changelog http://www.mcs.anl.gov/petsc/documentation/changes/36.html there are no changes in configure scripts, so it should all work OOB. However, dependent projects may fail to compile as some functions were renamed and location of include files were changed.

**Comment by davydden** [comment]
here's a PR https://github.com/Homebrew/homebrew-science/pull/2505
i guess this issue can be closed
