### ISSUE TITLE
Problem installing vtk

### ISSUE THREAD

**Issue by daveclucas** [Homebrew/homebrew-science#2442]
######################################################################## 100.0%
==> Installing dependencies for therion: cmake, boost, hdf5, vtk, wxmac
==> Installing therion dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.2.3.yosemite.bottle
######################################################################## 100.0%
==> Pouring cmake-3.2.3.yosemite.bottle.tar.gz
==> Caveats

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cmake/3.2.3: 1850 files, 32M
==> Installing therion dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.58.0.yosemite.bottl
######################################################################## 100.0%
==> Pouring boost-1.58.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.58.0: 10718 files, 486M
==> Installing therion dependency: hdf5
==> Downloading https://homebrew.bintray.com/bottles-science/hdf5-1.8.14.yosemit
######################################################################## 100.0%
==> Pouring hdf5-1.8.14.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/hdf5/1.8.14: 174 files, 11M
==> Installing therion dependency: vtk
==> Downloading http://www.vtk.org/files/release/6.2/VTK-6.2.0.tar.gz
######################################################################## 100.0%
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PR

-- Configuring incomplete, errors occurred!
See also "/tmp/vtk20150624-1189-1fv9twj/VTK-6.2.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/vtk20150624-1189-1fv9twj/VTK-6.2.0/build/CMakeFiles/CMakeError.log".

The above logs do not exist.

**Comment by tdsmith** [comment]
Why are you using that instead of the homebrew-science formula?

The logs are in ~/Library/Logs/Homebrew/vtk.

**Comment by dpo** [comment]
Please also gist `CMakeOutput.log` and `CMakeError.log`.

**Comment by dpo** [comment]
Given that `vtk` has been updated several times, I'll close this. Please feel free to open a new issue if there are still difficulties.
