### ISSUE TITLE
Policy on share.install versus (share/"formula").install ?

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2450]
My feeling is that there is rarely a reason in homebrew-science to use ```share.install``` rather than ```(share/"appname").install``` ?

But I seek opinions from the wiser team members?

**Comment by iml** [comment]
Yeah, there may be some special cases but with `man` etc. available I agree there's not much reason to use `share.install`. Especially for tests or example scripts.

**Comment by tseemann** [comment]
There's not many violations, but here's the `grep` result:

```
bowtie2.rb:    share.install %W[example scripts]
cmor.rb:    share.install "Test"
delly.rb:    share.install "test", "variantFiltering"
fwdpp.rb:    share.install "examples" # install examples
fwdpp.rb:    share.install "unit"     # install unit tests
gfan.rb:    share.install Dir['examples', 'homepage', 'testsuite']
grabix.rb:    share.install "simrep.chr1.bed"
harvest-tools.rb:    share.install "test"
hotspot.rb:    share.install "hotspot-distr/pipeline-scripts", "hotspot-distr/data"
hwloc.rb:    share.install "tests"
igvtools.rb:    share.install "genomes"
libsigrokdecode.rb:      share.install
mfusg.rb:    share.install "test"
ncl.rb:    share.install "data", "example", "test"
parmetis.rb:    share.install "Graphs" # Sample data for test
pastix.rb:      share.install "example"       # Contains all test programs.
petsc.rb:    share.install_symlink Dir["#{prefix}/#{petsc_arch}/share/*"]
phyml.rb:    share.install Dir['examples/*']
primer3.rb:      share.install "primer3_config"
sbagen.rb:    sbagen_share.install "examples", "scripts"
sbagen.rb:    sbagen_share.install resource("river") if build.with? "river"
slepc.rb:    share.install "share/slepc/datafiles"
snp_sites.rb:    share.install "tests/data"
snpeff.rb:    share.install "snpEff.config", "scripts", "galaxy"
swetest.rb:    share.install resource("seasnam")
swetest.rb:    share.install resource("sefstars")
swetest.rb:    share.install resource("seas")
swetest.rb:    share.install resource("semo")
swetest.rb:    share.install resource("sepl")
trimal.rb:    share.install "dataset"
weblogo.rb:    share.install "logo.pm", "template.pm"
wfdb.rb:    share.install prefix/"man" if stable?
z3.rb:    share.install "examples"
```

**Comment by sjackman** [comment]
This issue has bugged me as well. I'd suggesting adding a `pkgshare` function to `Formula` and changing pretty much every case of `share.install` to `pkgshare.install`.

**Comment by sjackman** [comment]
For what it's worth, `autotools` call this directory `pkgdatadir`.

**Comment by dpo** [comment]
I think it would be safer to have a dedicated attribute in Homebrew such as `pkgshare` rather than relying on `autotool`'s `pkgdatadir`. My experience is that few packages honor the latter.

**Comment by tdsmith** [comment]
Please see https://github.com/Homebrew/homebrew/pull/41333 for discussion re adding `Formula#pkgshare`.

**Comment by tdsmith** [comment]
The `pkgshare` method was added; I don't know if this requires further action.

**Comment by sjackman** [comment]
Replace all instances of `(share/"formula")` with `pkgshare`. We can just let this happen naturally over time, or do it in one fell swoop.

**Comment by sjackman** [comment]
Also the cases that Torsten @tseemann mentioned above.

**Comment by dpo** [comment]
Is there no `opt_pkgshare`?

**Comment by sjackman** [comment]
Guess not. Send a PR to Homebrew/homebrew?

**Comment by iml** [comment]
Pending a couple PRs all the improper uses of `share.install` should use `pkgshare` now.

**Comment by iml** [comment]
Whoops the `(share/"formula")` cases should be converted as well, but can be done in one commit without affecting bottles.

**Comment by sjackman** [comment]
Thanks, Ian.
