### ISSUE TITLE
scotch 6.0.4 seems to remove the direct link

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew-science#2459]
subj. 
When I try to use the link:
https://gforge.inria.fr/frs/download.php/file/34099/scotch_6.0.4.tar.gz
 in browser, i am redirected to a log-in page. 
Consequently, when one tries to update scotch, HSA256 mismatches.

p.s. i don't have solution so far, just wanted report it in case anyone knows how to update the formula

**Comment by davydden** [comment]
found one at Openfoam, but they seemd to have a patched version (sha does not match and patch fails): http://downloads.sourceforge.net/project/openfoam-extend/foam-extend-3.1/ThirdParty/

**Comment by davydden** [comment]
seriously, i think it's best to downgrade scotch to 6.0.3. so that for those who have scotch installed (6.0.3.) Homebrew does not try to re-download it. This happens for MUMPS and Trilinos, so it's kinda big... :(

**Comment by dpo** [comment]
Downgrading will not resolve anything. In fact, the same issue now happens with `scotch5` and might be due to recent GForge updates. I opened a discussion on their forum, asking for a direct download link.

**Comment by davydden** [comment]
right, that's is obviously a better solution.

**Comment by davydden** [comment]
the new link is available https://github.com/Homebrew/homebrew-science/pull/2508
