### ISSUE TITLE
Building opencv3 with CUDA 7.0 fails on Yosemite with: couldn't understand kern.osversion `14.4.0'

### ISSUE THREAD

**Issue by c4live** [Homebrew/homebrew-science#2484]
Dear All,
I recently upgraded to XCode 6.4 and OSX 10.10.4.

However, when I build opencv3 from source, that is what I get:
$ brew uninstall gcc
Uninstalling /usr/local/Cellar/gcc/5.1.0... (1351 files, 248M)
$ brew install --c++11 --with-contrib --with-cuda --with-ffmpeg --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni --with-python3 --with-qt5 --with-tbb --without-tests opencv3
==> Installing opencv3 from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/opencv3: ecj, gcc
==> Installing homebrew/science/opencv3 dependency: ecj
==> Downloading ftp://sourceware.org/pub/java/ecj-4.9.jar
######################################################################## 100.0%
🍺  /usr/local/Cellar/ecj/4.9: 2 files, 1.6M, built in 7 seconds
==> Installing homebrew/science/opencv3 dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-5.1.0.yosemite.bottle.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/gcc-5.1.0.yosemite.bottle.2.tar.gz
==> Pouring gcc-5.1.0.yosemite.bottle.2.tar.gz
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib

==> Summary
🍺  /usr/local/Cellar/gcc/5.1.0: 1351 files, 248M
==> Installing homebrew/science/opencv3
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3-3.0.0.tar.gz
==> Downloading https://github.com/Itseez/opencv_contrib/archive/3.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3--contrib-3.0.0.tar.gz
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20141027.tgz
Already downloaded: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv3/3.0.0 -DCMAKE_B
==> make
/usr/local/Library/ENV/4.3/clang++  -I/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include/darwin    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security  -Wmissing-prototypes -Wstrict-prototypes  -Winit-self -Wpointer-arith  -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -Wno-undef -Wno-missing-declarations -Wno-shadow   -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 3.0.0 -current_version 3.0.0 -o ../../lib/libopencv_cudafilters.3.0.0.dylib -install_name /tmp/opencv320150703-30746-g7iy7a/opencv-3.0.0/macbuild/lib/libopencv_cudafilters.3.0.dylib CMakeFiles/opencv_cudafilters.dir/src/filtering.cpp.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.16sc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.16sc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.16sc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.16uc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.16uc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.16uc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32fc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32fc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32fc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32sc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32sc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.32sc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.8uc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.8uc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_column_filter.8uc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_filter2d.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.16sc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.16sc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.16sc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.16uc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.16uc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.16uc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.32fc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.32fc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.32fc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.32sc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.32sc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.32sc4.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.8uc1.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.8uc3.cu.o CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_row_filter.8uc4.cu.o  -L/usr/local/include/../lib  -L/usr/local/cuda/lib ../../lib/libopencv_hal.a ../../lib/libopencv_cudaarithm.3.0.0.dylib ../../lib/libopencv_imgproc.3.0.0.dylib -framework AGL -framework OpenGL -ltbb ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a -lcudart -lnppc -lnppi -lnpps -lcufft -lcudart -lnppc -lnppi -lnpps ../../lib/libopencv_core.3.0.0.dylib ../../lib/libopencv_cudev.3.0.0.dylib ../../lib/libopencv_hal.a -framework AGL -framework OpenGL -ltbb ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a -lcudart -lnppc -lnppi -lnpps -lcufft -lcudart -lnppc -lnppi -lnpps -lcufft -Wl,-rpath,/usr/local/include/../lib -Wl,-rpath,/usr/local/cuda/lib 
cd /tmp/opencv320150703-30746-g7iy7a/opencv-3.0.0/macbuild/modules/cudafilters && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_symlink_library ../../lib/libopencv_cudafilters.3.0.0.dylib ../../lib/libopencv_cudafilters.3.0.dylib ../../lib/libopencv_cudafilters.dylib
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/opencv320150703-30746-g7iy7a/opencv-3.0.0/macbuild/CMakeFiles  22 23
[ 52%] Built target opencv_cudafilters
make: *** [all] Error 2
couldn't understand kern.osversion `14.4.0'

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

Everywhere I turn it seems that the "couldn't understand kern.osversion `14.4.0'" is caused by a wrong version of gcc/clang/clang++/whatever. Most places suggest to use xcode-select.
However if I type:
$ xcode-select --install 

I get:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

I am really puzzled with what to do. I also ran brew upgrade, to no avail.
Does anyone has the same issue?

**Comment by tdsmith** [comment]
The output of `brew gist-logs opencv3` would be helpful, please. What's `which gfortran` and `gfortran -v`, as well?

**Comment by c4live** [comment]
Here are the [logs](https://gist.github.com/08a31b400761a75ceeaf).

As for gfortran, `which gfortran` returns:

    /usr/local/bin/gfortran

while `gfortran -v` returns:

`Using built-in specs.`
`COLLECT_GCC=gfortran`
`COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.1.0/libexec/gcc/x86_64-apple-darwin14.3.0/5.1.0/lto-wrapper`
`Target: x86_64-apple-darwin14.3.0`
`Configured with: ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/usr/local/Cellar/gcc/5.1.0 --libdir=/usr/local/Cellar/gcc/5.1.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.1.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib`
`Thread model: posix`
`gcc version 5.1.0 (Homebrew gcc 5.1.0) `

**Comment by c4live** [comment]
The previous logs where generated with the following command:

    $ brew install --with-cuda --with-ffmpeg --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni --with-python3 --with-qt5 --with-tbb --without-tests --c++11 opencv3

Now, I tried a different set of options (mainly adding contrib but without python):

    $ brew install --with-cuda --with-ffmpeg --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni --with-python3 --with-qt5 --with-tbb --without-tests --c++11 --without-python --with-contrib opencv3

That also failed. Logs are [here](https://gist.github.com/670c1a0bb5dd97fe0e6d).
I am now going to try with a different set of options, and will post the results.

**Comment by c4live** [comment]
This last attempt worked:

    $ brew install --with-cuda --with-ffmpeg --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni --with-python3 --with-qt5 --with-tbb --without-tests --c++11 --without-python opencv3

There is no python support, nor contrib modules, but at least it compiles. Here are the [logs](https://gist.github.com/4ff523b075ad864ea95a).

**Comment by tdsmith** [comment]
Sorry for the late response. I think the problem is the old version of numpy you have in /Library. I would try removing that. `rm -rf /Library/Python/2.7/site-packages/numpy-*` should do it.

**Comment by tdsmith** [comment]
You should also remove apple-gcc42, if you have it installed. Let us know if this is still an issue or if we can help with anything else.
