### ISSUE TITLE
augustus misbuilds with clang

### ISSUE THREAD

**Issue by cacampbell** [Homebrew/homebrew-science#2485]
$ augustus --species=arabidopsis example.gb    

    augustus(4590,0x7fff7a500300) malloc: *** mach_vm_map(size=140735629918208) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    augustus(4590,0x7fff7a500300) malloc: *** error for object 0x7fff7b06ffe8: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

Working on Yosemite (10.10.4) -- have attempted to install by building from source and by using the bottle -- both seem to have this issue. I think that this is ... 14,000 GB of RAM? That can't possibly be right...

EDIT: Gist log

https://gist.github.com/6995753e04b03174d796

**Comment by tdsmith** [comment]
Have you spoken to the Augustus developers? It looks like you can reach them here: http://bioinf.uni-greifswald.de/bioinf/wiki/pmwiki.php?n=Forum.Forum

**Comment by cacampbell** [comment]
Well, I followed the advice of previous issues with Augustus and removed everything, then reinstalled it using gcc for it and its dependencies. Now it works, hurray. 

    brew uninstall -force augustus
    brew uninstall -force boost
    brew install -v augustus --build-from-source --cc=gcc-5
    augustus --species=arabidopsis example.gb

    [Expected Output]

Probably works with your gcc version of choice -- just not clang, as has been established

**Comment by tseemann** [comment]
Also looks like Augustus 3.1 was released May 2015: http://bioinf.uni-greifswald.de/augustus/binaries/
