### ISSUE TITLE
Octave: dyld: Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib

### ISSUE THREAD

**Issue by jmle** [Homebrew/homebrew-science#2516]
I've been trying to install octave for an hour without success. The issue seems to be the following:

    dyld: Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib
      Referenced from: /usr/local/Cellar/octave/3.8.2_1/bin/octave-cli-3.8.2
      Reason: image not found
    Trace/BPT trap: 5

I have tried everything on [here](https://github.com/Homebrew/homebrew-science/issues/1105), but nothing seems to work. Fortran seems to be correctly installed:

    $ ls -l /usr/local/lib/gcc
    lrwxr-xr-x  1 indio  admin  27 13 Jul 20:00 /usr/local/lib/gcc -> ../Cellar/gcc/4.9.2/lib/gcc

But octave doesn't pick it up...

Thank you in advance.

**Comment by tdsmith** [comment]
Is octave failing to build? If it is, can you provide the output of `brew gist-logs octave`? Does /usr/local/lib/gcc/5/libgfortran.3.dylib exist?

**Comment by jmle** [comment]
@tdsmith Octave is not failing to build. `/usr/local/lib/gcc/5/libgfortran.3.dylib` doesn't actually exist... Inside `/usr/local/lib/gcc/` I have only `x86_64-apple-darwin14.0.0`.

**Comment by dpo** [comment]
Could you try `brew reinstall gcc`?

**Comment by jmle** [comment]
@dpo Nope, still giving me the same error...

**Comment by tdsmith** [comment]
When did you last run `brew update`? Please run `brew update && brew upgrade`.

**Comment by jmle** [comment]
@tdsmith @dpo Finally working, I had to reinstall `qrupdate` and `octave` after that, but now it runs!

Thank you very much for your help!

**Comment by tdsmith** [comment]
Glad it's working; let us know if we can help with anything!

**Comment by suczako** [comment]
I had similar issue on OS X after upgrade to => Yosemite and then => El Capitan and then => Sierra---always the same ;)---but non of solutions above worked. Each time I solved it with command: brew reinstall octave --with-java

**Comment by jzw0025** [comment]
I tried tdsmith advice to run brew upgrade, and this solve the issue!
