### ISSUE TITLE
qhull fails to build on 10.11 (probably earlier)

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-science#2517]
_From @ejtttje on July 13, 2015 18:59_

I actually think this is failing earlier than 10.11, as it is already reported here: http://permalink.gmane.org/gmane.os.apple.fink.devel/22769

qhull is within homebrew-science.  Here's a qhull.rb with updated patch section:
https://gist.github.com/ejtttje/40b1fbb562bedd52dd10

_Copied from original issue: Homebrew/homebrew#41674_

**Comment by tdsmith** [comment]
Probably a duplicate of #2306.

**Comment by dpo** [comment]
Closing as `qhull` was updated since.
