### ISSUE TITLE
hdf5 configure error after reinstalling numpy

### ISSUE THREAD

**Issue by lasofivec** [Homebrew/homebrew-science#2518]
Yesterday I was having some issues with a *python/numpy* module (*f2py*). After looking in the internet, and trying a few options, it looked like the only solution left was to **reinstall numpy**.
To do so, I first uninstalled and the installed again (I didn't use the "reinstall" command).

I noticed that **homebrew was reinstalling gcc** as well. Which was already installed before. It took a long time but afterwards my *numpy* was working perfectly fine as well as the *f2py* module.

But, when I compiled my fortran library I got:

> Fatal Error: Cannot read module file 'hdf5.mod' opened at (1), because it was created by a different version of GNU Fortran

So homebrew update gcc but not all dependent modules!! So I try again to reinstall hdf5 using: `<brew reinstall hdf5 --with-fortran --with-mpi>`. And I get the following error:

>configure: error: Fortran high-level routines are not supported when the default REAL is DOUBLE PRECISION, use configure option --disable-hl.

I don't how to deal with this error. How can I change the configure option?
Any ideas ?

**Comment by tdsmith** [comment]
This doesn't fail for me:

`checking if Fortran default REAL is DOUBLE PRECISION... no`

Can you share the output of `brew gist-logs hdf5` after a failing build? Are you using open-mpi or mpich2?

**Comment by tdsmith** [comment]
Have you run `brew update && brew upgrade` recently?

**Comment by lasofivec** [comment]
I did. 
But in the mean time I reinstalled cmake, gcc, openmpi and hdf5. And now everything is working again!

> brew reinstall cmake
> brew reinstall gcc
> brew reinstall openmpi --enable-mpi-thread-multiple
> brew reinstall hdf5 --with-fortran --with-mpi

Thanks!
