### ISSUE TITLE
RFC: Add PyMOL.app to pymol formula

### ISSUE THREAD

**Issue by lambdalisue** [Homebrew/homebrew-science#2528]
I was so tired to use [PyMOL][] installed via homebrew (X11 version) while the version does not provide Mac OS X Application bundle, mean that I couldn't start the PyMOL by double clicking a PyMOL icon or double clicking PDB files.

That's why I made [macosx-pymol-app](https://github.com/lambdalisue/macosx-pymol-app) which just provide a bundle and use homebrewed pymol internally.

So I'm wondering if I could install the bundle with a option (say `--with-app`) in homebrew. While I don't really know it is an acceptable or not, I would like to ask you guys if I should make that PR or not.

[PyMOL]: http://pymol.org/

**Comment by lambdalisue** [comment]
And also, I don't really know where to put the `PyMOL.app` which I made. I can provide my git repository but there should be a better way to store that.

**Comment by dunn** [comment]
Do the developers distribute it as an app bundle?

**Comment by lambdalisue** [comment]
I'm not really sure but I think PyMOL have three versions. 

The 1st one is a commercial version which you can find at https://www.pymol.org/. The 2nd one is an educational version which you can also find at the website (but the version is really really old.). Both have an app bundle (I don't have a commercial version thus it is just guess from an educational version).

The 3rd one is an open source version which homebrew use, and I think that version does not provide an app bundle, that's why I made the bundle.

**Comment by lambdalisue** [comment]
If the open-source version provide the app bundle, I'd like to use that and I'd like to add an option to enable that :-)

**Comment by dunn** [comment]
Got it! I was hoping they'd have an up-to-date free version that could be submitted to [homebrew-cask](https://github.com/caskroom/homebrew-cask).

**Comment by lambdalisue** [comment]
Yeah, I thought so but I couldn't find it. And also, my bundle requires pymol executabe installed via homebrew thus I thought homebrew-science is the place to share.

**Comment by lambdalisue** [comment]
So who do I need to ask? Ping

**Comment by dunn** [comment]
The decision is up to @Homebrew/science

**Comment by sjackman** [comment]
My inclination is not to bundle the app unless upstream provides it. I'd suggest that you distribute the .app that you created on GitHub and submit it to Homebrew Cask.

**Comment by lambdalisue** [comment]
Ok. I think mine rely on the brewed pymol so I just distribute it in my repo then :-)
Thanks for reply.
