### ISSUE TITLE
bless fails to build on 10.10.3+

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2537]
```
==> Installing homebrew/science/bless
==> Downloading https://downloads.sourceforge.net/project/bless-ec/bless.v0p24.tgz
==> Downloading from http://skylink.dl.sourceforge.net/project/bless-ec/bless.v0p24.tgz
######################################################################## 100,0%
==> make
/usr/local/include/sparsehash/sparse_hash_map:358:7: error: request for member 'swap' in 'hm1', which is of non-class type 'int'
   hm1.swap(hm2);
       ^
make: *** [main.o] Error 1
make: *** [correct_errors.o] Error 1
```

Logs: https://gist.github.com/248643b8e9c061b6f05e

**Comment by apjanke** [comment]
Fails on 10.11 for me, too.

Several new releases are out, but they don't build out of the box. 1.02 is current, and has switched to vendoring all its dependencies, and fails on case-insensitive filesystems.

Boneyard time?

**Comment by dpo** [comment]
There's a 10.10 bottle for `bless`. Is this still relevant?

**Comment by bfontaine** [comment]
@dpo I don’t know; I don’t have 10.10 anymore :/

**Comment by dpo** [comment]
It builds for me and there's a bottle, so I'll go ahead and close this.
