### ISSUE TITLE
root fails to build on 10.10.4

### ISSUE THREAD

**Issue by lucasc896** [Homebrew/homebrew-science#2557]
MacBook-Pro:~ chrislucas$ brew install --with-x11 root
==> Installing root from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/root: openssl, xrootd, gsl
==> Installing homebrew/science/root dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.yosemite.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 18M
==> Installing homebrew/science/root dependency: xrootd
==> Downloading https://homebrew.bintray.com/bottles/xrootd-4.1.1.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring xrootd-4.1.1.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/xrootd/4.1.1: 214 files, 7.4M
==> Installing homebrew/science/root dependency: gsl
==> Downloading https://homebrew.bintray.com/bottles/gsl-1.16.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring gsl-1.16.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/gsl/1.16: 245 files, 8.2M
==> Installing homebrew/science/root
==> Downloading ftp://root.cern.ch/root/root_v5.34.26.source.tar.gz
######################################################################## 100.0%
==> ./configure --all --enable-builtin-glew --enable-builtin-freetype --prefix=/usr/local/Cellar/root/5.34.26 --etcdir=/usr/local/Cellar/root/5.34.26/etc/root --mandir=/usr/local/Ce
==> make
include/Reflex/Builder/CollectionProxy.h:732:68: error: unknown type name 'multimap'
   template <class K, class T, class R, class A> struct Proxy<std::multimap<K, T, R, A> > {
                                                                   ^
6 errors generated.
make: *** [cint/cintex/src/ROOTClassEnhancer.o] Error 1

**Comment by jgarofoli** [comment]
I think we just need a newer ROOT version.  See this comment in the ROOT forums.

https://root.cern.ch/phpBB3/viewtopic.php?t=19565

**Comment by dpo** [comment]
PR welcome.

**Comment by lucasc896** [comment]
OK, I'll have a crack at updating root.rb to v5.34.32

**Comment by dpo** [comment]
Resolved?

**Comment by lucasc896** [comment]
Yes, the build works with these changes. https://github.com/Homebrew/homebrew-science/pull/2569

**Comment by dpo** [comment]
Great. Thanks for the PR!
