### ISSUE TITLE
Building gal-sim on 10.10.4 and it can't find FFTW3

### ISSUE THREAD

**Issue by josePhoenix** [Homebrew/homebrew-science#2577]
```
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... 
Error: fftw file failed to link correctly
Check that the correct location is specified for FFTW_DIR

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at 
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ
```

I can't find anything relevant in the GalSim installation FAQ, and I can't figure out how to force HomeBrew to force scons to force the compiler to pass `-L/absolute/path/to/fftw/lib`.

Here's a [gist](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727) with:

  * [the output as seen in the terminal](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727#file-gistfile1-txt)
  * [the scons output](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727#file-01-scons)
  * [the scons config log](https://gist.github.com/josePhoenix/b3ba45d6df08a10c4727#file-config-log)

I tried adding `ENV['LDFLAGS']='-L/Users/jlong/homebrew/Cellar/fftw/3.3.4_1/lib'` to the `gal-sim.rb` formula, but that didn't appear to be passed to the scons configure process, even though you can see it in the `LDFLAGS` in the scons output.

**Comment by dpo** [comment]
It seems `fftw` was installed earlier. Could you try `brew reinstall fftw` and then `brew install gal-sim`?

**Comment by josePhoenix** [comment]
That's one of the things I tried, but the error is the same. I'm not familiar with how Homebrew exposes the include files / libraries to the build process, but `-Iinclude` seems to be enough to find fftw3 while `-Llib` doesn't find the library.

**Comment by dstndstn** [comment]
As an aside, I just updated the GalSim formula to pick up the new GalSim version v1.3.0 -- that formula is here, and there is a pull request to update homebrew-science.  It might be worth checking whether version 1.3.0 builds correctly...
https://github.com/camphogg/homebrew-science/blob/bump-gal-sim/gal-sim.rb
https://github.com/Homebrew/homebrew-science/pull/2587


Anyway, could you please send the output from running:

ls -l /usr/local/lib/libfftw3*

homebrew should have produced a bunch of symlinks to the fftw libraries that live in /usr/local/Cellar/fftw/VERSION/lib
and then the GalSim installer should be able to find them in that standard place.  I don't think it should be necessary to tell the GalSim scons where fftw is, assuming the symlinks are in place.

**Comment by josePhoenix** [comment]
I use a non-standard homebrew prefix (`~` instead of `/usr/local`), but everything appears to be there:

```
$ ls ~/lib/*fftw3*
/Users/jlong/lib/libfftw3.3.dylib          /Users/jlong/lib/libfftw3f_threads.3.dylib
/Users/jlong/lib/libfftw3.a                /Users/jlong/lib/libfftw3f_threads.a
/Users/jlong/lib/libfftw3.dylib            /Users/jlong/lib/libfftw3f_threads.dylib
/Users/jlong/lib/libfftw3_threads.3.dylib  /Users/jlong/lib/libfftw3l.3.dylib
/Users/jlong/lib/libfftw3_threads.a        /Users/jlong/lib/libfftw3l.a
/Users/jlong/lib/libfftw3_threads.dylib    /Users/jlong/lib/libfftw3l.dylib
/Users/jlong/lib/libfftw3f.3.dylib         /Users/jlong/lib/libfftw3l_threads.3.dylib
/Users/jlong/lib/libfftw3f.a               /Users/jlong/lib/libfftw3l_threads.a
/Users/jlong/lib/libfftw3f.dylib           /Users/jlong/lib/libfftw3l_threads.dylib
```

I'll check out the revised formula you linked and report back!

**Comment by dstndstn** [comment]
Ahh, the non-standard prefix explains it.

Could you try downloading the GalSim source and running scons as below?  If that works, I'll update the formula.

cd /tmp # or wherever
wget https://github.com/GalSim-developers/GalSim/archive/v1.3.0.tar.gz
tar xzf v1.3.0.tar.gz
cd GalSim-3.0
scons EXTRA_INCLUDE_PATH=/Users/jlong/include EXTRA_LIB_PATH=/Users/jlong/lib EXTRA_PATH=/Users/jlong/bin

thanks

**Comment by josePhoenix** [comment]
I actually got it to build yesterday from `master` using pretty much the steps you described above (and installing the dependencies through Homebrew).

**Comment by dstndstn** [comment]
Oh, you could have mentioned that.

Could you please try this formula and report whether it works:
https://github.com/camphogg/homebrew-science/blob/gal-sim-nonstandard-prefix/gal-sim.rb

thx

**Comment by josePhoenix** [comment]
Sorry!

I'm having the same problem with the formula you linked, and a modified version where I tried adding `"FFTW_DIR=#{HOMEBREW_PREFIX}"` to the end of the line where you have the `EXTRA_PATH`s.

* terminal output https://gist.github.com/josePhoenix/74ce5f5b93df422bb4ad 
* config.log https://gist.github.com/josePhoenix/ff5e1a0860946d2b1ec2

**Comment by josePhoenix** [comment]
Ah, if you stick the paths on the first `scons` line, not `scons "install", ...`, it builds!

**Comment by josePhoenix** [comment]
Successfully built v1.2.0 with this formula: https://gist.github.com/josePhoenix/ace9db817c31142d905d
Successfully built v1.3.0 with this formula: https://gist.github.com/josePhoenix/28794e9d852f6281057d

**Comment by dstndstn** [comment]
Great, thanks for the testing!  Pull request submitted.

**Comment by dpo** [comment]
@josePhoenix Does this version work for you: https://gist.github.com/931cc097d7385194edac ?

**Comment by josePhoenix** [comment]
@dpo no, it fails to find tmv-link:

```
$ brew install -v gal-sim
==> Installing gal-sim from homebrew/homebrew-science
/usr/bin/env python -c import pyfits
/usr/bin/env python -c import numpy
/usr/bin/env python -c import nose
Warning: Formula file is modified!
Building from source because homebrew/Library/Taps/homebrew/homebrew-science/gal-sim.rb has local changes
To install from a bottle instead, run with --force-bottle
/usr/bin/env python -c import pyfits
/usr/bin/env python -c import numpy
/usr/bin/env python -c import nose
==> Downloading https://github.com/GalSim-developers/GalSim/archive/v1.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/gal-sim-1.2.0.tar.gz
==> Verifying gal-sim-1.2.0.tar.gz checksum
tar xf /Library/Caches/Homebrew/gal-sim-1.2.0.tar.gz
==> /Users/jlong/opt/scons/bin/scons FFTW_DIR=/Users/jlong/opt/fftw
scons: Reading SConscript files ...
SCons is version 2.3.5 using python version 2.7.10
Python is from /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7
Using the following (non-default) scons options:
   FFTW_DIR = /Users/jlong/opt/fftw
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /usr/bin/env python
Using default PYPREFIX =  /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Using compiler: /usr/bin/g++
compiler version: 4.2.1
Determined that a good number of jobs = 8
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for boost header files... yes
Boost version is 1.58.0
Checking for C++ header file TMV.h... yes
TMV version is 0.72

No tmv-link file could be found

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ

Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Formula
Tap: homebrew/homebrew-science
Path: /Users/jlong/homebrew/Library/Taps/homebrew/homebrew-science/gal-sim.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: cb441ffefd115d37765c4efabc5f1cb9d0fd79be
Last commit: 7 days ago
HOMEBREW_PREFIX: /Users/jlong
HOMEBREW_CELLAR: /Users/jlong/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
MacPorts/Fink: /sw/bin/fink
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/jlong/bin/python => /Users/jlong/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/jlong/opt/ruby/bin/ruby => /Users/jlong/homebrew/Cellar/ruby/2.2.2/bin/ruby
Java: 1.8.0_51
==> ENV
CC: /usr/bin/clang
CXX: /usr/bin/clang++
OBJC: /usr/bin/clang
OBJCXX: /usr/bin/clang++
CFLAGS: -Os -w -pipe -march=native -mmacosx-version-min=10.10
CXXFLAGS: -Os -w -pipe -march=native -mmacosx-version-min=10.10
CPPFLAGS: -isystem/Users/jlong/include -F/Users/jlong/Frameworks
LDFLAGS: -L/Users/jlong/lib  -F/Users/jlong/Frameworks -Wl,-headerpad_max_install_names
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /Users/jlong
CMAKE_FRAMEWORK_PATH: /Users/jlong/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.10
PKG_CONFIG_LIBDIR: /Users/jlong/lib/pkgconfig:/Users/jlong/homebrew/Library/ENV/pkgconfig/10.10:/usr/lib/pkgconfig
PATH: /Users/jlong/opt/ruby/bin:/Users/jlong/bin:/usr/local/bin:/Applications/ST_sci/SM/bin:/sw/bin:/sw/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Users/jlong/homebrew/Library/ENV/scm
CPATH: /Users/jlong/include

Error: homebrew/science/gal-sim 1.2.0 did not build
Logs:
     /Users/jlong/Library/Logs/Homebrew/gal-sim/01.scons
     /Users/jlong/Library/Logs/Homebrew/gal-sim/config.log
```

**Comment by dstndstn** [comment]
@dpo you're probably going to need TMV_DIR, TMV_LINK, BOOST_DIR.  Frankly, I don't see the problem with using EXTRA_*.

**Comment by dpo** [comment]
@josePhoenix Thanks for testing! I updated the gist. Hopefully, everything is specified now.

@dstndstn Using `EXTRA_` is alright, but I've always found using `HOMEBREW_PREFIX` wholesale.

**Comment by dpo** [comment]
@josePhoenix Does #2617 work for you? It works on the bot. Note that the formula file is now called `galsim.rb`.
