### ISSUE TITLE
Octave documentation build failed

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew-science#2579]
https://gist.github.com/anonymous/bbf45a95f1836d93121e

**Comment by dpo** [comment]
For reference, the error is related to building documentation with `texinfo`:
```
/usr/bin/texi2dvi: Can't use option `--output' with more than one argument.
```

In the mean time, it should build with `--without-docs`.

**Comment by dpo** [comment]
Could you try to `brew install texinfo` and then reinstall `octave`?

**Comment by guoxiao** [comment]
@dpo I have installed `texinfo` already. It's keg-only and not linked so `octave` called the system `texi2dvi`

**Comment by guoxiao** [comment]
It could build with `--without-gui --without-doc`, but it cannot run under 10.11 because of the newer java version.
I tried to build with `--without-gui --without-doc --without-java` and it works.

**Comment by dpo** [comment]
Since you have already brewed `texinfo`, could you try
```
MKINFO=$(brew --prefix texinfo)/bin/makeinfo TEXI2DVI=$(brew --prefix texinfo)/bin/texi2dvi TEXI2PDF=$(brew --prefix texinfo)/bin/texi2pdf brew install -v octave
```
and look for the lines
```
checking for makeinfo... /usr/local/opt/texinfo/bin/makeinfo
checking for texi2dvi... /usr/local/opt/texinfo/bin/texi2dvi
checking for texi2pdf... /usr/local/opt/texinfo/bin/texi2pdf
```
in `configure`'s output? Does the build complete?

**Comment by dpo** [comment]
There's also #2660 to take for a spin.

**Comment by dpo** [comment]
@guoxiao Octave was just upgraded to version 4. Could you see if you're still experiencing problems?

**Comment by guoxiao** [comment]
@dpo No problems now.
