### ISSUE TITLE
pcl install failed

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2593]
I ran:

    brew install pcl --with-examples --with-openni2 --HEAD

[Here is the gist log](https://gist.github.com/3a9db53e17117f41be4d)

**Comment by ahundt** [comment]
apparently this is due to qt5

```

CMake Error at apps/modeler/CMakeLists.txt:100 (QT4_WRAP_UI):
  Unknown CMake command "QT4_WRAP_UI".

```

**Comment by ahundt** [comment]
I've confirmed [pcl supports qt5](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L371)

**Comment by ahundt** [comment]
[This line has to change based on Qt 4 or 5](https://github.com/Homebrew/homebrew-science/blob/master/pcl.rb#L100)

**Comment by tdsmith** [comment]
This is because cmake is preferring qt5 and searching /usr/local/bin explicitly and you have qt5 linked, which is an unsupported configuration: https://gist.github.com/anonymous/3a9db53e17117f41be4d#file-doctor-out-L1077-L1090

I recommend unlinking qt5 before installing pcl.

**Comment by tdsmith** [comment]
(with `brew unlink qt5`)

**Comment by ahundt** [comment]
I have other dependencies that require qt5, unfortunately. I might have fixed it with the pull request, although [i'm not sure if line 155 is right](https://github.com/ahundt/homebrew-science/commit/fd1d3e65b107231fad4a1a458e639d9022fcb6d4#diff-b4c927d4ea039e97b99094678c67fe73R155).

**Comment by tdsmith** [comment]
Unlinking qt5 from /usr/local will not uninstall it and will not affect builds of Homebrew formulas; `brew info qt5` provides advice for building external software against an unlinked qt5.

**Comment by ahundt** [comment]
I'm a developer and when I use qt, I use qt5. So unfortunately it would adversely affect me to unlink. :-)

**Comment by tdsmith** [comment]
You could of course relink it after installing pcl.

**Comment by ahundt** [comment]
I think with these commits it does the right thing

**Comment by ahundt** [comment]
There is also an issue where head and the current specified version differ, so the patch needs to be changed depending on the version. Is that currently possible with homebrew?

I've also created a related [issue to pull this upstream into pcl](https://github.com/PointCloudLibrary/pcl/issues/1288).

**Comment by ahundt** [comment]
I've re-patched it again to handle another small bug. Should be good now.

**Comment by ahundt** [comment]
However, the difference between the current patch in the script and --HEAD patch isn't yet resolved. However I think that can be handled separately from merging this issue.

**Comment by csparker247** [comment]
This isn't just a qt5 issue. `brew install pcl --without-qt` fails if you don't also include `--without-apps`. I would suggest setting the without apps flags [here](https://github.com/BrewTestBot/homebrew-science/blob/0c1c0f2366e04c71a5263f8ea1752197524f4abc/pcl.rb#L93) if neither QT is specified,

**Comment by ahundt** [comment]
ok, even so I think the patch adding qt5 support is a good one to have.

**Comment by ahundt** [comment]
@csparker247 After reading it again, are you saying that `--without-apps` should be set automatically if --without-qt is set?

**Comment by csparker247** [comment]
Yeah, the apps need either qt4 or qt5, so we need to make sure that either one of those is enabled. Since you already have `if build.with?("qt") || build.with?("qt5")` on line 84, the else (line 93) should be modified to disable apps.

**Comment by ahundt** [comment]
@csparker247 how do you set the flag on that line? sorry don't know ruby well enough

**Comment by csparker247** [comment]
Sorry, I looked closer and realized that would have been the wrong place to put it. It's better to just check to make sure QT is enabled in some way when you do the check for with-apps. I've submitted a PR to your fork.

**Comment by ahundt** [comment]
awesome, thanks! merged that

**Comment by ahundt** [comment]
I'm a little confused about what's actually correct and being merged, and what will be dropped among the following:
- https://github.com/Homebrew/homebrew-science/commit/f8f3b5bf8296037eccfdfcdd1951c8c68eee82d4
- https://github.com/BrewTestBot/homebrew-science/commit/4d8bf6f80a67ee6e0d2be60db75020f6b50c25f9
- https://github.com/Homebrew/homebrew-science/pull/2595
- https://github.com/Homebrew/homebrew-science/issues/2593
- https://github.com/Homebrew/homebrew-science/pull/2844 this looks like it may be the best option

**Comment by ahundt** [comment]
In other words, the #2844 changes look like a nice improvement, but can you specify that it should build in each of the following modes?
- qt mode
- qt5 mode
- disable both qt and qt5

**Comment by fran6co** [comment]
@ahundt First thing this change affects HEAD only, for 1.7.2 just do --without-qt and it's going to build it without qt. In the case of HEAD both of them are optional, so just add --with-qt or --with-qt5 to select the qt version. For no qt just don't add them.

The CUDA change was already merged, so it's not going to get dropped and it works with no qt at all if you disable the apps. The issue where apps fail when building with VTK but no QT, has to be forwarded upstream, I'll try to work on it if I get some spare time.

**Comment by jmtatsch** [comment]
`brew install homebrew/science/pcl --HEAD` without additional parameters has been broken since a few days due to:
```
CMake Error at apps/modeler/CMakeLists.txt:100 (QT4_WRAP_UI):
  Unknown CMake command "QT4_WRAP_UI".
```
Unfortunately  the Robot Operating System (ROS) relies on that formula to build. 
With the option --with-qt everything works as it should.
Could we maybe set --with-qt as default parameter?

**Comment by fran6co** [comment]
This is an upstream bug, just made the PR to fix it. I don't like with-qt to be the default parameter because it needs vtk with qt to work, I think it's better to keep it simple.

**Comment by fran6co** [comment]
If you are using it for ROS maybe you don't need the apps, so you can use ```--without-apps --without-qt```

**Comment by jmtatsch** [comment]
I don't actually know if qt and apps are needed, maybe @wjwwood can chime in on this.

**Comment by fran6co** [comment]
This can be closed now, https://github.com/PointCloudLibrary/pcl/issues/1377 got merged.

**Comment by ahundt** [comment]
@fran6co There are other issues in this thread, not just the one brought  up at the end, such as the addition of qt5 support. 

Please don't simply close it and forget about those parts, but whatever is appropriate :-)

**Comment by fran6co** [comment]
The current pcl formula now supports qt5, not sure what are you talking about.

**Comment by ahundt** [comment]
I thought there was one item still not addressed. I just went trough everything again and it looks good. Closing the issue. Thanks!
