### ISSUE TITLE
graph-tool fails to import on python3

### ISSUE THREAD

**Issue by itcarroll** [Homebrew/homebrew-science#2613]
I believe it's linking to libboost_python.dylib rather than libboost_python3.dylib. Gist logs are [here](https://gist.github.com/anonymous/1773277467c9bfe25759), the error is below. The import is successful if I manually symlink /usr/local/lib/libboost_python.dylib to the the python3 version.

    Python 3.4.3 (default, Jul 13 2015, 12:18:23) 
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import graph_tool
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.4/site-packages/graph_tool/__init__.py", line 102, in <module>
        dl_import("from . import libgraph_tool_core as libcore")
      File "/usr/local/lib/python3.4/site-packages/graph_tool/dl_import.py", line 57, in dl_import
        exec(import_expr, local_dict, global_dict)
      File "<string>", line 1, in <module>
    ImportError: dlopen(/usr/local/lib/python3.4/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: _PyClass_Type
      Referenced from: /usr/local/lib/libboost_python.dylib
      Expected in: flat namespace
     in /usr/local/lib/libboost_python.dylib
    >>>

**Comment by tdsmith** [comment]
Closed by #2616.
