### ISSUE TITLE
can one fetch --with-openblas option of petsc inside slepc?

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew-science#2631]
there is a minor problem currently. 
If a user installs PETSc with openblas and then tries to  install SLEPc, what should happen is that dependency of SLEPc (arpack) is built with openblas as well. That will fail on Linuxbrew unless arpack is installed beforehand with openblas.

Is there a way to fetch installation option of petsc and if there is `--with-openblas`, add it to `depends_on "arpack"`?

An alternative ugly option is to introduce `--with-openblas` option to SLEPc, but it will be used only for a single dependency.

**Comment by dpo** [comment]
Have a look at the formula for `ceres-solver`. There's no need for SLEPc to depend on OpenBLAS since it will have been installed when PETSc was installed.

**Comment by davydden** [comment]
cool. can't make it work though ;-) https://github.com/Homebrew/homebrew-science/pull/2632
