### ISSUE TITLE
Best way to retire 'tabix' with backward compatibility

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2634]
The 'tabix' formula is redundant now because 'htslib' provides it.

Can we replace 'tabix' with a simple formula that just 'depends_on htslib' ?

**Comment by iml** [comment]
I'd be fine with that as a temporary fix, but hopefully we'll have better formula renaming/alias support in the near future.

**Comment by tseemann** [comment]
@lml is there now a more formal way to handle this situation?

**Comment by dpo** [comment]
Could be an alias?

**Comment by dpo** [comment]
`tabix` was moved to the boneyard.
