### ISSUE TITLE
Download Failure for Emboss v.6.6.0

### ISSUE THREAD

**Issue by Yellow-Fever** [Homebrew/homebrew-science#2641]
Good morning.
I've been having some trouble getting the download for EMBOSS-6.6.0.tar.gz to work properly; there may be a combination of issues with expired certificates and reorganization of the download mirror directory structure.

System: OSX Lion (10.7.5), running homebrew v.0.9.5 with current update and system cURL v.7.21.4.

Issues:
________________________
1. Brew emits a curl (60) error for SSL certs, and curl (78) error for (I presume) file not found:

$ brew install emboss==> Installing emboss from homebrew/homebrew-science
==> Downloading ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.6.0.tar.gz

curl: (78) RETR response: 550
Trying a mirror...
==> Downloading ftp://ftp.ebi.ac.uk/pub/software/unix/EMBOSS/EMBOSS-6.6.0.tar.gz

curl: (78) RETR response: 550
Trying a mirror...
==> Downloading https://science-annex.org/pub/emboss/EMBOSS-6.6.0.tar.gz

curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "emboss"
Download failed: https://science-annex.org/pub/emboss/EMBOSS-6.6.0.tar.gz

2. I manually checked the mirrors attempted by the formula, and attempted to get a current EMBOSS version via ftp to brew locally from cache. A few things: The mirror located at ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.6.0.tar.gz does not contain the file at the specified location, and instead has implemented a link to a current version, which does not appear to be fully implemented and cannot be retrieved manually. The same behavior and apparent change in directory structure is replicated for the mirror at ftp://ftp.ebi.ac.uk/pub/software/unix/EMBOSS/EMBOSS-6.6.0.tar.gz.

3. The mirror located at https://science-annex.org/pub/emboss/EMBOSS-6.6.0.tar.gz appears to be using an SSL certificate that expired on May 7, 2015.

Thanks!

**Comment by tdsmith** [comment]
Please contact the emboss maintainers and ask where we should obtain this file. Thanks!

**Comment by iml** [comment]
I've replaced the mirror with something that doesn't track the upstream ftp. You'll have to email the EMBOSS folks to find out what's going on; their mailing lists are also down.

**Comment by Yellow-Fever** [comment]
Thanks so much. I've tried to get a hold of the maintainers through their mail lists, with no luck either. The new mirror worked fine this morning.

**Comment by Brainiarc7** [comment]
You can also do:

wget -c -v -nc --no-check-certificate https://science-annex.org/pub/emboss/EMBOSS-6.6.0.tar.gz

And it will download the same file without certificate checking.
