### ISSUE TITLE
opencv3 missing xz dependency in linuxbrew

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2642]
https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb

should have a dependency on "xz" when it is being installed via linuxbrew

**Comment by iMichka** [comment]
Current opencv3 builds fine without it. This issue was opened quite some time ago, and is probably obsolete. Please open a new issue and fill out the issue template if you still encounter problems.
