### ISSUE TITLE
suite-sparse: fails on ubuntu 14.04

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#2648]
_From @ahundt on August 11, 2015 21:16_

I'm not sure if this is the right place to put this issue due to the particulars of linuxbrew since this is a `homebrew-science` package, but `brew install suite-sparse` failed on ubuntu 14.04 as follows:

https://gist.github.com/50ee22b1ca6d754caed9

_Copied from original issue: Homebrew/linuxbrew#510_

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/50ee22b1ca6d754caed9#file-01-make-L3820-L3823
```
/home/peter/.linuxbrew/bin/g++-5 -fPIC -O3 -fno-common -fexceptions -DNTIMER -fopenmp -DHAVE_TBB -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_parallel.cpp
../Source/spqr_parallel.cpp:10:37: fatal error: tbb/task_scheduler_init.h: No such file or directory
compilation terminated.
make[2]: *** [spqr_parallel.o] Error 1
```

**Comment by sjackman** [comment]
My guess is that it will fail on any system including Mac where `HOMEBREW_PREFIX` is not `/usr/local`. The formula does not add the TBB include directory to `CPPFLAGS`. See https://github.com/Homebrew/homebrew-science/blob/master/suite-sparse.rb#L49-L50

**Comment by dpo** [comment]
@ahundt let's know if #2650 resolves the issue.

**Comment by dpo** [comment]
@sjackman Are you using Issue Mover in Linuxbrew? Should we authorize it here to move Linux issues in the other direction?

**Comment by sjackman** [comment]
Yes, I am, and yes, we should authorize it here.

**Comment by ahundt** [comment]
Thanks! I'm traveling at the moment but I hopefully can try it in a week or so.

**Comment by tdsmith** [comment]
superenv should take care of the search paths on OS X.

**Comment by sjackman** [comment]
Superenv isn't used on Linuxbrew, but I'm hoping to review and merge https://github.com/Homebrew/linuxbrew/pull/266 in the next month, which has been a long time coming.

**Comment by ahundt** [comment]
@dpo sorry for a beginner question, but where can I find instructions I can follow to test #2650?

**Comment by dpo** [comment]
@ahundt You can run these commands:
```
cd /tmp
wget https://raw.githubusercontent.com/dpo/homebrew-science/suite-sparse-tbb/suite-sparse.rb
brew install ./suite-sparse.rb [--with-options-you-want]
```

**Comment by dpo** [comment]
@ahundt bump

**Comment by ahundt** [comment]
I was using another person's computer at the time I originally submitted this, I'm working on getting a VM set up where I can test this again.

**Comment by davydden** [comment]
btw, an alternative way to isntall from `PR` is to take the raw file `brew install https://raw.githubusercontent.com/dpo/homebrew-science/suite-sparse-tbb/suite-sparse.rb [--with-some-options]`

**Comment by ahundt** [comment]
was this merged?

**Comment by davydden** [comment]
yes, if you go here https://github.com/Homebrew/homebrew-science/pull/2650 you'll see that the PR was merged. This issue is also currently closed.
