### ISSUE TITLE
Error: SHA256 mismatch for rrdtool-1.5.3

### ISSUE THREAD

**Issue by T-Bomb** [Homebrew/homebrew-science#2658]
Tried removing and retrying.  No change.
Tried manual download. No change.
Tried confirming the gzip. No change.
Tried different source for download. No change.
Tried brew update. No change.

Only discrepency I see is that OS shows file as 7.8mb but FTP download locations show 2.1mb

**Comment by dunn** [comment]
Same for me:
```
🔥  brew fetch -fs rrdtool
==> Downloading https://oss.oetiker.ch/rrdtool/pub/rrdtool-1.5.3.tar.gz
######################################################################## 100.0%
Downloaded to: /Library/Caches/Homebrew/rrdtool-1.5.3.tar.gz
SHA1: 1ccb4dde5839181d8f84998eb21bc4f0a85f83ac
SHA256: 1348ca138ba44ed62f5a4d0f57196c77991f62e19ac9841acd1f712feb8ca44c
Warning: Formula reports different SHA256: 79e7b2f5cf74843e89fe4d08925f955268fd21736cbea03e54ae83320fc6129f
```

**Comment by dunn** [comment]
1.5.4 is out, so the easiest fix is just to update the formula: http://oss.oetiker.ch/rrdtool/pub/?M=D

**Comment by T-Bomb** [comment]
Where can I find the ruby script to manually update the formula? Since trying to CDI it doesn't seem to work.
Tried brew update, brew upgrade, brew install rrdtool-1.5.4, etc but no change.

**Comment by dunn** [comment]
Oh, the formula file needs to be updated.  If you want to try a pull request, take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by T-Bomb** [comment]
I was thinking I could just edit the actual script to change the linked file/version it uses.

**Comment by T-Bomb** [comment]
So found the formula and looking at it, it shows SHA256 for Yosemite, Mavericks, and Mountain Lion. And as you would expect nothing for El Capitan (not supported since it's a beta/rc). Can I just put the SHA in manually and save it? or is there a command to have brew generate and add it?

**Comment by dpo** [comment]
@T-Bomb The `rrdtool` formula is not hosted here. It's in [Homebrew core](https://github.com/Homebrew/homebrew) so you need to open a pull request there.

What's going on is that the sha256 of the *source* tar ball is erroneous, not that of the *bottle*. In your previous message, you're talking about bottles (i.e., the binaries precompiled by the Homebrew bot).

Here are the lines you need to edit in the formula:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rrdtool.rb#L4-L5

Once you've done that, follow the instructions to open a pull request. See the url posted by @dunn above. You can use `brew edit rrdtool` to edit the formula file. Save it, create a git branch, commit your change and push it to your fork of Homebrew. Then head to your forked repository on Github and create the pull request.

**Comment by T-Bomb** [comment]
Yeah, I just edited the formula with the correct SHA and reran the install. That worked fine.

**Comment by dpo** [comment]
Please submit a pull request to fix it once and for all though.
