### ISSUE TITLE
Trilinos 12.0.1 on OSX 10.10.5 fails

### ISSUE THREAD

**Issue by cpraveen** [Homebrew/homebrew-science#2659]
Here is the gist

https://gist.github.com/cpraveen/25fdada903f6b70f99a5

**Comment by dpo** [comment]
Is this the error
```
Processing enabled TPL: SCALAPACK (enabled explicitly, disable with -DTPL_ENABLE_SCALAPACK=OFF)
-- Searching for libs in SCALAPACK_LIBRARY_DIRS=''
-- Searching for a lib in the set "scalapack":
--   Searching for lib 'scalapack' ...
--     Found lib '/usr/local/lib/libscalapack.dylib'
-- Searching for a lib in the set "blacs":
--   Searching for lib 'blacs' ...
-- ERROR: Did not find a lib in the lib set "blacs" for the TPL 'SCALAPACK'!
-- TPL_SCALAPACK_LIBRARIES='/usr/local/lib/libscalapack.dylib'
```
Your gist seems to have been truncated.

**Comment by cpraveen** [comment]
No. I have updated the gist which should now show the full log. It fails when compiling, here is the last portion

```
[ 28%] Generating unsmoothed1_epetra.gold
cd /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/build/packages/muelu/test/interface/Output && /usr/local/Cellar/cmake/3.3.1/bin/cmake -E copy /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/packages/muelu/test/interface/Output/unsmoothed1_epetra.gold /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/build/packages/muelu/test/interface/Output/unsmoothed1_epetra.gold
[ 28%] Generating unsmoothed1_tpetra.gold
cd /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/build/packages/muelu/test/interface/Output && /usr/local/Cellar/cmake/3.3.1/bin/cmake -E copy /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/packages/muelu/test/interface/Output/unsmoothed1_tpetra.gold /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/build/packages/muelu/test/interface/Output/unsmoothed1_tpetra.gold
[ 28%] Built target MueLu_ParameterList_Output_cp
make: *** [all] Error 2
```

**Comment by dpo** [comment]
What we'll need is the output of `brew gist-logs trilinos`.

**Comment by cpraveen** [comment]
Here is the log

https://gist.github.com/e2ac085c0936d0511254

**Comment by dpo** [comment]
I don't even see an error message in there. Is it the multitude of messages of the form
```
Dependee abc is newer than depender xyz
```
that makes it fail?

Could you give #2507 a try, see if you have better luck?

@davydden do you have any insight?

**Comment by davydden** [comment]
i reinstalled trilinos just yesterday, i also have 
```
-- ERROR: Did not find a lib in the lib set "blacs" for the TPL 'SCALAPACK'!
```
That's something we need to look at, but that's not what causes a problem. 

in the logs i don't see what's wrong as only thing which shows is:
```
cd /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/build/packages/Sundance/tests-pdeopt/LinearPDECO && /usr/local/Cellar/cmake/3.3.1/bin/cmake -E copy /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/packages/Sundance/Playa/etc/SolverParameters/amesos.xml /tmp/trilinos20150817-88418-1xecxi1/trilinos-12.0.1-Source/build/packages/Sundance/tests-pdeopt/LinearPDECO/amesos.xml
make[1]: *** [packages/zoltan/src/CMakeFiles/zoltan.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
and
```
[ 28%] Built target MueLu_ParameterList_Output_cp
make: *** [all] Error 2
```
but those are useless. It looks as if the error is truncated somewhat.

how do you install trilinos? what do you have installed already among dependencies? with what flags?
try installing with `-v` and see if you can get the compiler error.

**Comment by davydden** [comment]
btw, i compared your cmake log to mine and the only difference is that i use static scalapack library https://github.com/Homebrew/homebrew-science/pull/2653
but i've been installing against dynamic scalapack as well before (with the same version). 

what i'm saying is, it must have something to do with dependencies...

**Comment by cpraveen** [comment]
The log file was generated using -v, see 

https://gist.github.com/cpraveen/25fdada903f6b70f99a5

I did not install any of the dependencies myself.

**Comment by cpraveen** [comment]
I installed all dependencies automatically when I installed trilinos. Could you tell me what I could try ? Should I uninstall all dependencies of trilinos and try to reinstall ? How to do this ?

**Comment by cpraveen** [comment]
I have tried to install trilinos by disabling dependencies one by one

--without-mumps
--without-hypre
--without-suite-sparse
--without-eigen
--without-superlu --without-superlu_dist
--without-scotch
--without-scalapack
--without-boost
--without-metis
--without-parmetis
--without-hwloc
--without-fortran
--without-glm
--without-glpk
--without-hdf5
--without-doxygen
--without-cppunit

But the compilation still fails.

**Comment by davydden** [comment]
i noticed that you have a lot of cores. Perhpas, there is something wrong with Trilinos build. Could you please add `ENV.deparallelize` right after `def install` in `trilinos.rb`?
That should run make with a single core and we would hopefully finally see the compiler error.

**Comment by davydden** [comment]
for simplicity, you could try with all dependencies disabled.

**Comment by cpraveen** [comment]
--without-x11
--without-libmatio
--without-netcdf
--without-adol-c

**Comment by cpraveen** [comment]
So using ENV.deparallelize gave this error

```
[ 11%] Building C object packages/zoltan/src/CMakeFiles/zoltan.dir/zz/zz_util.c.o
cd /tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/build/packages/zoltan/src && /usr/local/bin/mpicc  -Dzoltan_EXPORTS -O3 -DNDEBUG -fPIC -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/build -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/build/packages/zoltan/src -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/include -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/all -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/coloring -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/graph -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/ha -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/hier -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/hsfc -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/lb -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/matrix -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/order -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/par -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/params -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/tpls -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/phg -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/rcb -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/reftree -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/simple -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/timer -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/Utilities/Communication -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/Utilities/DDirectory -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/Utilities/Timer -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/Utilities/shared -I/tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/zz -I/usr/local/opt/parmetis/include -I/usr/local/opt/metis/include -I/usr/local/include    -o CMakeFiles/zoltan.dir/zz/zz_util.c.o   -c /tmp/trilinos20150818-43821-1uds9ce/trilinos-12.0.1-Source/packages/zoltan/src/zz/zz_util.c
make[2]: *** No rule to make target `/usr/local/opt/parmetis/lib/libparmetis.a', needed by `packages/zoltan/src/libzoltan.12.0.1.dylib'.  Stop.
make[1]: *** [packages/zoltan/src/CMakeFiles/zoltan.dir/all] Error 2
make: *** [all] Error 2
```

I dont see libparmetis.a

```
$ ls /usr/local/opt/parmetis/lib/
libparmetis.dylib
```

**Comment by davydden** [comment]
Strangely enough on my homebrew i have only `libparmetis.a` and the formula is:
```
$ brew info parmetis
davydden/science/parmetis: stable 4.0.3 (bottled)
MPI-based library for graph/mesh partitioning and computing fill-reducing orderings
http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
/usr/local/Cellar/parmetis/4.0.3 (12 files, 24M) *
  Built from source
From: https://github.com/davydden/homebrew-science/blob/master/parmetis.rb
==> Dependencies
Build: cmake ✔
Required: metis ✔
```
@dpo could that  be that bottled versions are for whatever reason different than those compiled from sources?


i will try to fix it at the end of the week (currently away for 2 days).

**Comment by cpraveen** [comment]
I built parmetis from source

```
$ brew info parmetis
homebrew/science/parmetis: stable 4.0.3 (bottled)
MPI-based library for graph/mesh partitioning and computing fill-reducing orderings
http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
/usr/local/Cellar/parmetis/4.0.3 (12 files, 22M) *
  Built from source
From: https://github.com/homebrew/homebrew-science/blob/master/parmetis.rb
==> Dependencies
Build: cmake ✔
Required: metis ✔
```
but I still dont get libparmetis.a

```
$ ls /usr/local/opt/parmetis/lib/
libparmetis.dylib
```

**Comment by cpraveen** [comment]
I removed the "shared=1" option in parmetis.rb and I get the libparmetis.a file.

**Comment by cpraveen** [comment]
Trilinos also compiles. So the problem was the missing libparmetis.a file.

**Comment by dpo** [comment]
@davydden You must have altered the formula for `parmetis` because it only builds the shared library. I wonder why `trilinos` wouldn't compile against the shared library. It used to, didn't it?

**Comment by dpo** [comment]
@cpraveen Could you please try `brew uninstall $(brew deps trilinos); brew reinstall trilinos`? It's a bit drastic but let's see.

**Comment by davydden** [comment]
@dpo i surely didn't mess up with `parmetis`. my local formula has `shared=1`, so i assume it must have been changed since last October, when i installed it. 

Re-installing dependencies won't change anything as it's this line in `trilinos` which should be changed
https://github.com/Homebrew/homebrew-science/blob/master/trilinos.rb#L186

I did a quick fix in my PR to link against dynamic parmetis.

**Comment by davydden** [comment]
@dpo btw, i think we have troubles with trilinos because brew-bot times out so one can't test it on a fresh up-to-date homebrew-science.

**Comment by dpo** [comment]
@davydden Why can't that line just be
```
args << "-DTPL_ParMETIS_LIBRARIES=-L#{Formula["parmetis"].opt_lib} -lparmetis -L#{Formula["metis"].opt_lib} -lmetis"
```

**Comment by davydden** [comment]
@dpo it's not how Trilinos documentation says to use this filed. Remember, those guys have a whole configuration system build on top of Cmake for all the packages. I will see if what you write works, though...

**Comment by davydden** [comment]
@dpo it worked. I updated the PR.

**Comment by dpo** [comment]
Great. Thanks!

**Comment by davydden** [comment]
@cpraveen Could you please reset parmetis formula to shared library and try 'brew uninstall $(brew deps trilinos); brew reinstall trilinos' from my pull request to check that it also works for you? Then  @dpo could safely merge it.

**Comment by cpraveen** [comment]
I am bit lost here. How do I get your pull request.

**Comment by davydden** [comment]
@cpraveen just do `brew install https://raw.githubusercontent.com/davydden/homebrew-science/trilinos_openblas/trilinos.rb --without-python` (i assume you originally installed `--without-python`).

**Comment by cpraveen** [comment]
Yes, your trilinos compiles with libparmetis.dylib. I see this warning at the end

```
Warning: trilinos dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

I dont remember seeing this before. Is it harmless ? I have to recompile my deal.II to test all of this.

**Comment by cpraveen** [comment]
I could test my trilinos installation via deal.II and it works. Thanks a lot for your patience and help to resolve this issue.
