### ISSUE TITLE
libvips installation fails on OSX [make error]

### ISSUE THREAD

**Issue by abrel** [Homebrew/homebrew-science#2680]
Hello,

I am unable to unstall libvips through brew.
Below is what I get:

brew install homebrew/science/vips --with-webp --with-graphicsmagick
==> Installing vips from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/vips: libgsf, harfbuzz, sqlite
==> Installing homebrew/science/vips dependency: libgsf
==> Downloading https://homebrew.bintray.com/bottles/libgsf-1.14.34.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libgsf-1.14.34.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libgsf/1.14.34: 152 files, 2,7M
==> Installing homebrew/science/vips dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.0.1.yosemite.bottle.2.tar.gz
######################################################################## 100,0%
==> Pouring harfbuzz-1.0.1.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/harfbuzz/1.0.1: 79 files, 3,4M
==> Installing homebrew/science/vips dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.8.11.1.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring sqlite-3.8.11.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.8.11.1: 9 files, 2,8M
==> Installing homebrew/science/vips
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.0/vips-8.0.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.0.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.0.2 --with-magick --with-magickpackage=GraphicsMagick
==> make check
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

**Comment by dunn** [comment]
Can you post `brew gist-logs vips`, please?

**Comment by abrel** [comment]
it is just here:
https://gist.github.com/anonymous/0e65c6cf6924d002d736

**Comment by ksidpen** [comment]
+ 1
https://gist.github.com/anonymous/07008679bcfdcd43d503#file-doctor-out

**Comment by rubenjimenez** [comment]
Hi, i'm getting this error when trying to install libvips. Is already there some sort of solution?

**Comment by dpo** [comment]
I'm not sure why two tests are failing, but as a temporary measure, does `brew install vips --with-webp --with-graphicsmagick --without-check` work?

**Comment by rubenjimenez** [comment]
That worked!

The installation finally could end properly. Thanks.

**Comment by dpo** [comment]
Great to hear! Keep in mind that something somewhere might go wrong because of those test failures.

**Comment by rubenjimenez** [comment]
The main problem has been I updated OS X to El Capitan and I've reinstalled everything. I didn't remember the --without-check trick, but I remember use it a lot ago and it worked in the same way (I think libvips was in version ~7.30).

Despite the --without-check, I've been using libvips + sharp in production with no problem. I think the system has processed several Gbs of images and I've never got any sort of error from libvips.

I think that should be checked though.

**Comment by jcupitt** [comment]
It seems to install cleanly with current brew:

```
$ brew install homebrew/science/vips --with-webp --with-graphicsmagick
==> Installing vips from homebrew/homebrew-science
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.1/vips-8.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.1.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.1.0 --with-magick --with-magic
==> make check
==> make install
🍺  /usr/local/Cellar/vips/8.1.0: 183 files, 13M, built in 2.1 minutes
```

**Comment by nojvek** [comment]
I get the following:

➜  build git:(stage) ✗ brew install homebrew/science/vips
==> Installing vips from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles/vips-8.1.1.mavericks.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "vips"
Download failed: https://homebrew.bintray.com/bottles/vips-8.1.1.mavericks.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.1/vips-8.1.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.1.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.1.1
==> make check
  Reason: Incompatible library version: libtiff.5.dylib requires version 13.0.0 or later, but libjpeg.8.dylib provides version 9.0.0
Command '['./introspect', '--introspect-dump=/var/folders/ph/g1f69xdn7yqbg9gd8k0f6gv40000gn/T/tmp-introspectdK9Ow0/functions.txt,/var/folders/ph/g1f69xdn7yqbg9gd8k0f6gv40000gn/T/tmp-introspectdK9Ow0/dump.xml']' returned non-zero exit status -5
make[2]: *** [Vips-8.0.gir] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

**Comment by jcupitt** [comment]
Sorry, I can't help with Mavericks. 

It is working on El Capitan, I just wiped my homebrew and tried again, all seems fine.

**Comment by felixbuenemann** [comment]
Checks also fail for me on 10.11.4:
```
=====================================
   vips 8.1.1: test/test-suite.log
=====================================

# TOTAL: 4
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_cli.sh
=================

testing with IMG_4618.jpg
testing nearest ... (standard_in) 1: parse error
difference is 0,000000

FAIL: test_formats.sh
=====================

testing IMG_4618.jpg v ... (standard_in) 1: parse error
save / load difference is 0,000000
```

**Comment by jcupitt** [comment]
Hi @felixbuenemann, fixed in 8.2.2:

https://github.com/jcupitt/libvips/commit/af8b43b16d6b65796c994c18991f6fad9204b9fa

copied from your equivalent patch for vips.rb. Thanks for finding this dumbness!

**Comment by dpo** [comment]
Can this be closed now?

**Comment by felixbuenemann** [comment]
Yes, a workaround has been added in #3231(formula 8.2.1_1) and it will be fixed in libvips once 8.2.2 is released.

**Comment by dpo** [comment]
Great. Thank you!

**Comment by felixbuenemann** [comment]
@dpo I think you reopended this by accident.
