### ISSUE TITLE
Sundials formula is out of date

### ISSUE THREAD

**Issue by lukauskas** [Homebrew/homebrew-science#2687]
It seems that the sundials formula available here is quite out of date. 
The formula installs sundials 2.5.0, yet the latest available version of sundials is 2.6.2 as it can be seen in the [the official page](https://computation.llnl.gov/casc/sundials/download/download.php).

**Comment by dpo** [comment]
Feel like submitting a PR?

**Comment by sauliusl** [comment]
Will try. 

So far the immediate problem is the fact the download link is hidden behind 'enter your name & email' page.
I have emailed them asking for a direct link, we will see what they reply.

If they say no, is there a way to ask the user for this info form within `brew install`?

**Comment by dpo** [comment]
I don't believe that there is.

**Comment by Moisan** [comment]
The Fedora Project packages seems to have a [copy of the source](http://pkgs.fedoraproject.org/repo/extras/sundials/sundials-2.6.2.tar.gz/3deeb0ede9f514184c6bd83ecab77d95/). Could you base yourself on that?

**Comment by davydden** [comment]
there are a number of patches in the current version. You'll need to figure out if they got into the upstream or not.

p.s. macports uses the same `2.5.0`, won't be much help, i suppose.
