### ISSUE TITLE
RStudio Server login fails

### ISSUE THREAD

**Issue by lehneres** [Homebrew/homebrew-science#2691]
Hi,

I've installed R Studio using this formula without problems, however I am not able to login. Username/password is always wrong. I've tried different user accounts.

I would like to show you some logs, but it seems I am not able to find the files. Looking into https://github.com/rstudio/rstudio/blob/master/INSTALL there seem to be some additional steps for the regular rstudio installation in order to the the auth working, maybe I have to do something similar on OS X?

PS: When I follow this install script, https://iangow.wordpress.com/2013/05/01/rstudio-server-on-mac-os-x/ user authentification seems to work

**Comment by randy3k** [comment]
@lehneres This script only install rstudio for you, you have to follow the INSTALL file to finish the authentication step.

However, if you only want to test the server, you can run `sudo rstudio-server`. The `sudo` will give you the necessary privilege to run rstudio server.

**Comment by lehneres** [comment]
hm okay, but I would assume that a package which is installed, already gone through all install scripts... Anyway, thanks for your response!
