### ISSUE TITLE
cmake Modules directory needs to be writable for installation of other formulas

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2696]
[It seems pcl installs a script `FindCMinPack.cmake`](https://github.com/Homebrew/homebrew-science/pull/2595#issuecomment-136084509) into this directory:

`/usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindCMinpack.cmake`

However, this directory is not writable, and does not occur in the `allow file-write*` debug messages of jenkins. 

Is this possible to fix or does a workaround need to be found where `pcl` is patched to not copy the find script?

**Comment by xu-cheng** [comment]
Instead of writing files to another formula's Cellar, you should install them to `#{prefix}/share/cmake/Modules`, i.e. keeping files inside its own cellar.

**Comment by xu-cheng** [comment]
Actually that error message comes from `cminpack.rb`. And it hard coded the path for installing `FindCMinpack.cmake` [here](https://github.com/devernay/cminpack/blob/master/cmake/CMakeLists.txt#L8).

You should patch it and preferably sending the patch to upstream.

**Comment by ahundt** [comment]
The issue brought up here has now been resolved in #2701
