### ISSUE TITLE
brew install octave --head fails, dependencies not fully listed

### ISSUE THREAD

**Issue by whistlerbrk** [Homebrew/homebrew-science#2697]
Hi,

I've been struggling to get octave 4.0.0 installed on my MBP.

I've upgraded and updated brew and my doctor runs clean at the moment.

It appears that the latest version of python as well as `pip install hggit` are additional dependencies for the build to even start. That resolved some of my problems.

However I'm still unable to build:

```
$ brew install octave --HEAD --force-bottle
==> Installing octave from homebrew/homebrew-science
Warning: Formula file is modified!
Building from source because Library/Taps/homebrew/homebrew-science/octave.rb has local changes
To install from a bottle instead, run with --force-bottle
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Cloning http://www.octave.org/hg/octave
Updating /Library/Caches/Homebrew/octave--hg
==> Checking out branch default
==> Downloading https://savannah.gnu.org/patch/download.php?file_id=31072
Already downloaded: /Library/Caches/Homebrew/octave--patch-19f2dcaf636f1968c4b1639797415f83fb21d5a3.php
==> Patching
patching file src/mkoctfile.in.cc
Hunk #1 succeeded at 241 (offset 16 lines).
Hunk #2 succeeded at 491 (offset 22 lines).
patching file libinterp/corefcn/comment-list.h
patching file libinterp/corefcn/oct.h
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/octave/HEAD --with-x=no
==> make all
5 errors generated.
make[2]: *** [libinterp/corefcn/libinterp_corefcn_libcorefcn_la-symtab.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
```

Do note that I tried to edit the formula but that wasn't allowed in any case, despite me using the --force-bottle option (perhaps conflicts with --HEAD? seems like a separate issue)

**Comment by whistlerbrk** [comment]
I'm building from HEAD not from stable, the formula just needs to updated to reflect that 4.0.0 is stable...

**Comment by whistlerbrk** [comment]
Problem still exists when I try to build 4.0.0 from source too, so I'll keep this open.

Very hard to build =(

**Comment by dpo** [comment]
We don't really support HEAD builds; `brew install octave` installs octave 3.8.2, not 4.0.0. Octave 4.0 is (still a pull request)[#2660] at the moment. Also, there's no use specifying `--force-bottle` if you're building HEAD. Please test #2660 and report in that thread.
