### ISSUE TITLE
cminpack.rb installation broken

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2701]
As per:
https://github.com/Homebrew/homebrew-science/issues/2696

the cminpack cmake script installs files into a folder there is not permission for.

**Comment by dpo** [comment]
The `cminpack` formula is quite innocent. I think this should be reported upstream instead.

**Comment by tdsmith** [comment]
I agree but the net effect is that nothing can depend on it until it's fixed.

**Comment by tdsmith** [comment]
https://github.com/devernay/cminpack/pull/4
