### ISSUE TITLE
osx / gfortran / R / Makeconf : wrong FLIBS variable value (gfortran library path)

### ISSUE THREAD

**Issue by kpykc** [Homebrew/homebrew-science#2716]
I'm not sure if this is a bug or it (`gfortran` `FLIBS` parameter in R `Makeconf`) is expected to be configured manually.

I had a problems with installing some R packages which are dependent on `gfortran` (e.g. `mnormt`).
The problem was with linker not able to locate packages:

```
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.1.0/lib/gcc/5/gcc/x86_64-apple-darwin14.3.0/5.1.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.1.0/lib/gcc/5'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
 

My setup:

```{.bash}
0/~> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46

0/~> brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 1ed13e5711c1b4c1174bf5d7cdea35505efb397d
Last commit: 13 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.10.4-x86_64
Xcode: N/A
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_65

0/~> brew info gcc
gcc: stable 5.2.0 (bottled)
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/5.2.0 (1353 files, 248M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb
...

0/~> brew info r
homebrew/science/r: stable 3.2.2 (bottled), HEAD
Software environment for statistical computing
http://www.r-project.org/
/usr/local/Cellar/r/3.2.1_1 (2175 files, 60M) *
  Poured from bottle
From: https://github.com/homebrew/homebrew-science/blob/master/r.rb
...
```

`/usr/local/Frameworks/R.framework/Resources/etc/Makeconf ` configuration was:

```{.bash}
0/~> cat /usr/local/Frameworks/R.framework/Resources/etc/Makeconf | grep 'FLIBS ='
FLIBS =  -L/usr/local/Cellar/gcc/5.1.0/lib/gcc/5/gcc/x86_64-apple-darwin14.3.0/5.1.0 -L/usr/local/Cellar/gcc/5.1.0/lib/gcc/5 -lgfortran -lquadmath -lm
```

Became:

```{.bash}
0/~> cat /usr/local/Frameworks/R.framework/Resources/etc/Makeconf | grep 'FLIBS ='
FLIBS =  -L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin14.4.0/5.2.0 -L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 -lgfortran -lquadmath -lm
```

**Comment by dpo** [comment]
It seems like `r` needs to be re-bottled. Alternatively, you could build it from source with `brew reinstall r --build-from-source` to make sure it refers to the version of `gcc` you have. The issue here is that `gcc` has been upgraded since `r` was last bottled.

**Comment by kpykc** [comment]
Well, it seems for me that it would be better to add some caution note to R formula. I don't see a point to rebuild package from source if only thing that you need is to fix path in configuration file.
How do you think?
May be something like:
"If you experiencing problems  with building packages using gfortran try to check that R is configured to use right version of gfortran in Makeconf"

 I'm using R not so long, so maybe it is even possible to override this variables in user configuration, e.g. in `~/.R/Makevar`. I need to check this.

**Comment by tdsmith** [comment]
Please run `brew update && brew upgrade r`; this was fixed in the last couple weeks.

**Comment by tdsmith** [comment]
(It was fixed durably, so that it should not recur until we hit a major gcc version upgrade.)
