### ISSUE TITLE
arpack failed to built on 10.11: Fortran 77 compiler cannot create executables

### ISSUE THREAD

**Issue by adzenith** [Homebrew/homebrew-science#2741]
Trying to install Octave on El Capitan.
One of the dependencies, arpack, won't install because:
```
==> ./configure --prefix=/usr/local/Cellar/arpack/3.2.0/libexec --with-blas=-L/usr/local/opt/veclibfort/lib -lvecLibFort
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether the Fortran 77 compiler works... no
configure: error: in `/private/tmp/arpack20150916-61751-1vhkkr7/arpack-ng-3.2.0':
configure: error: Fortran 77 compiler cannot create executables
See `config.log' for more details
```
I first tried it with just the command-line tools installed; I see the same error with Xcode 6.4 from the App Store. I'm downloading Xcode 7 right now but I have slow internet.

https://gist.github.com/adzenith/2e843354f53ab90cb392

**Comment by davydden** [comment]
i think the issue is in `ld: library not found for -lSystem`. As far as I understand it should be in `/usr/lib/`. On `Yosemite` i have `/usr/lib/libSystem.dylib` symliked to `/usr/lib/libSystem.B.dylib`. Can you check that you have the same? If not try `ln -s /usr/lib/libSystem.B.dylib /usr/lib/libSystem.dylib`.

p.s. it's not `arpack` issue per-se.

**Comment by adzenith** [comment]
I don't have a `/usr/lib/libSystem.dylib`, just the `.B` version. I can't add one because of system integrity protection.

**Comment by adzenith** [comment]
I do already have a symlink at `/usr/lib/libSystem.dylib`. Any other ideas?

**Comment by tdsmith** [comment]
I see gcc was configured with `--with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk` (https://gist.github.com/adzenith/2e843354f53ab90cb392#file-config-log-L89) so I think gfortran will not work unless Xcode 7 is installed. How'd you build gcc?

**Comment by adzenith** [comment]
It's installed from a bottle! Good catch. I will try with Xcode 7, and if that doesn't work I will build `gcc` from source.

**Comment by tdsmith** [comment]
Oh, we might've mis-built the gcc bottle, then!

**Comment by adzenith** [comment]
Worked great with Xcode 7 installed. It did say this though:
```
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.

If you like the default optimization level of your compiler, ignore this
warning.
```
I'm not totally clear on what it means that it's building with the Homebrew-provided Fortran compiler but also an alternative one.

**Comment by dpo** [comment]
Those messages are "normal".

**Comment by adzenith** [comment]
Should I open a new ticket about the `gcc` bottle? I'm good on closing this now.
