### ISSUE TITLE
MINC executables can't find libhdf5.9.dylib

### ISSUE THREAD

**Issue by dpatriarche** [Homebrew/homebrew-science#2751]
The current head is 8a3a372. Package "minc" (installed from bottle) depends on libhdf5.9.dylib, which comes from package "hdf5". But package "hdf5" installs libhdf5.10.dylib. This results is that "minc" executables fail, e.g.:

    $ nii2mnc
    dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
      Referenced from: /usr/local/bin/nii2mnc
      Reason: image not found
    Trace/BPT trap: 5

Formula "hdf5" was updated on 2015-09-17. For some reason the bottle for "minc" is still out of date.

**Comment by ViralBShah** [comment]
I saw this issue with the octave 4.0.0 bottle too:

````
$ octave
dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /usr/local/Cellar/octave/4.0.0/bin/octave-cli-4.0.0
  Reason: image not found
Trace/BPT trap: 5
````

**Comment by ViralBShah** [comment]
I have `/usr/local/lib/libhdf5.10.dylib` after a `brew upgrade`.

**Comment by adityarajmane93** [comment]
Same Problem Here .. libhdf5.9.dylib Not Loaded and all I have is libhdf5.10.dylib in my Mac

dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /usr/local/Cellar/octave/4.0.0/bin/octave-cli-4.0.0
  Reason: image not found
Trace/BPT trap: 5

**Comment by dunn** [comment]
Does `brew reinstall --build-from-source octave` work?

**Comment by adityarajmane93** [comment]
@dunn Thank you :) it Started Working !!!

**Comment by ViralBShah** [comment]
I really would love the bottle to work. Happy to wait till it is sorted out.

**Comment by whistlerbrk** [comment]
This also worked for me once I built from source. Thanks

**Comment by dunn** [comment]
The octave bottle should work now.  Other HDF5 dependents are being re-bottled in #2757.

**Comment by Luthaf** [comment]
I have the same issue with NetCDF lib, which can not find the `/usr/local/lib/libhdf5_hl.9.dylib` library. Was it updated too ? I can not find it in #2757.

**Comment by dunn** [comment]
The revision bumps were split into two PRs.  First one's here now #2758; second will come once that's merged.

**Comment by puiseux** [comment]
same problem for me while loading vtk5 : 
Traceback (most recent call last):
  File "/Volumes/developpement/Axille-simulation/sources/preferences.py", line 20, in <module>
    import vtk
  File "/usr/local/lib/python2.7/site-packages/vtk/__init__.py", line 43, in <module>
    from vtkIOPython import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/vtk/vtkIOPython.so, 2): Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /usr/local/Cellar/vtk5/5.10.1_1/lib/vtk-5.10/libvtkIO.5.10.dylib
  Reason: image not found
