### ISSUE TITLE
octave 4.0.0 fails to run on OSX10.10.  hdf5 dependency broken

### ISSUE THREAD

**Issue by yaise** [Homebrew/homebrew-science#2754]
Hi There, 
I'm trying to get octave running on my OSX 10.10
brew install octave ran fine and installed a prebuilt 4.0.0 package including one of it's dependencies hdf5

but I get the following error when I try to run octave: 
dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /usr/local/Cellar/octave/4.0.0/bin/octave-cli-4.0.0
  Reason: image not found
zsh: trace trap  octave

Turns out that the prebuilt octave depends on hdf5.9 but the hdf5 that is installed as a prerequisite when you run brew install octave is version hdf5.10

**Comment by dpo** [comment]
For now, it's necessary to `brew install octave --build-from-source`. There's an issue with the `hdf5` bottles. Sorry the inconvenience.

**Comment by dunn** [comment]
Won't rebuilding the octave bottles work? That's what I'm doing in #2756

**Comment by dpo** [comment]
Sure, it should. The bottle of every `hdf5` dependent should be rebuilt, I suppose. The issue is more general and applies to every package I think.

**Comment by yaise** [comment]
Thanks for the quick turnaround! :+1:

**Comment by nicelifeBS** [comment]
I have the same issue with openimagiio and **brew reinstall --build-from-source openimageio** is giving me following error:
´´´[ 95%] Built target testtex
[ 96%] Building CXX object src/python/CMakeFiles/PyOpenImageIO.dir/py_imagebuf.cpp.o
cd /tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/build/macosx/src/python && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++   -DOIIO_PYMODULE_NAME=OpenImageIO -DPyOpenImageIO_EXPORTS -DUSE_FIELD3D=1 -DUSE_FREETYPE -DUSE_OCIO=1 -DUSE_OPENEXR_VERSION2=1 -D__STDC_LIMIT_MACROS -isystem /usr/local/include -I/usr/local/include/OpenEXR -I/tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/src/include -I/tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/build/macosx/include/OpenImageIO -I/usr/include/python2.7  -Os -w -pipe -march=native -mmacosx-version-min=10.10  -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -fPIC   -Wall -Werror -fno-math-errno -Wno-unused-function -Wno-overloaded-virtual -Wno-unneeded-internal-declaration -Wno-unused-private-field -Qunused-arguments -Wunknown-warning-option -Wno-array-bounds -o CMakeFiles/PyOpenImageIO.dir/py_imagebuf.cpp.o -c /tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/src/python/py_imagebuf.cpp
[ 96%] Building CXX object src/python/CMakeFiles/PyOpenImageIO.dir/py_imagebufalgo.cpp.o
cd /tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/build/macosx/src/python && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++   -DOIIO_PYMODULE_NAME=OpenImageIO -DPyOpenImageIO_EXPORTS -DUSE_FIELD3D=1 -DUSE_FREETYPE -DUSE_OCIO=1 -DUSE_OPENEXR_VERSION2=1 -D__STDC_LIMIT_MACROS -isystem /usr/local/include -I/usr/local/include/OpenEXR -I/tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/src/include -I/tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/build/macosx/include/OpenImageIO -I/usr/include/python2.7  -Os -w -pipe -march=native -mmacosx-version-min=10.10  -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -fPIC   -Wall -Werror -fno-math-errno -Wno-unused-function -Wno-overloaded-virtual -Wno-unneeded-internal-declaration -Wno-unused-private-field -Qunused-arguments -Wunknown-warning-option -Wno-array-bounds -o CMakeFiles/PyOpenImageIO.dir/py_imagebufalgo.cpp.o -c /tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/src/python/py_imagebufalgo.cpp
1 error generated.
make[3]: *** [src/python/CMakeFiles/PyOpenImageIO.dir/py_imagecache.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 97%] Linking CXX executable oiiotool
cd /tmp/openimageio20160115-57349-ufbk6u/oiio-Release-1.5.14/build/macosx/src/oiiotool && /usr/local/Cellar/cmake/3.4.1/bin/cmake -E cmake_link_script CMakeFiles/oiiotool.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++   -Os -w -pipe -march=native -mmacosx-version-min=10.10  -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -L/usr/local/opt/openssl/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names CMakeFiles/oiiotool.dir/oiiotool.cpp.o CMakeFiles/oiiotool.dir/diff.cpp.o CMakeFiles/oiiotool.dir/imagerec.cpp.o CMakeFiles/oiiotool.dir/printinfo.cpp.o  -o oiiotool  ../libOpenImageIO/libOpenImageIO.1.5.14.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIlmThread.dylib /usr/local/lib/libOpenColorIO.dylib /usr/local/lib/libfreetype.dylib /usr/local/lib/libpng.dylib /usr/lib/libz.dylib /usr/local/lib/libtiff.dylib /usr/local/lib/libjpeg.dylib /usr/lib/libz.dylib /usr/local/lib/libtiff.dylib /usr/local/lib/libjpeg.dylib /usr/local/lib/libField3D.dylib /usr/local/lib/libhdf5.dylib /usr/local/lib/libopenjpeg.dylib /usr/local/lib/libwebp.dylib /usr/local/lib/libIlmImf.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIlmThread.dylib 
[ 97%] Built target oiiotool
make[2]: *** [src/python/CMakeFiles/PyOpenImageIO.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [cmake] Error 2´´´

Any ideas how to fix this?
