### ISSUE TITLE
netcdf fails to build on OS X 10.10.5

### ISSUE THREAD

**Issue by jhcsu** [Homebrew/homebrew-science#2760]
When trying to build netcdf with Fortran (specifically, the brew-installed gfortran) support:
`brew install netcdf --with-fortran --with-cxx-compat`

I get error the following error:
`checking if Fortran "byte" is C "signed char"... configure: error: Could not link conftestf.o and conftest.o`

gist follows...
https://gist.github.com/b3acad026e5b659eac00

**Comment by tdsmith** [comment]
I can't reproduce this and we didn't capture the debug log of the failed configure run; can you build with `-d` and then, when it fails, drop into a shell from the menu that pops up, copy config.log out of the fortran build directory, and then post it as a gist?

**Comment by jhcsu** [comment]
Done:
https://gist.github.com/anonymous/69d15eaa46e0a87b1c29

**Comment by dpo** [comment]
Could you please update and try again? I just updated the `netcdf` bottle.

**Comment by jhcsu** [comment]
I updated and tried again... but same error. This might not be surprising because the `--enable-fortran` option bypasses the bottle to build from source.

**Comment by jhcsu** [comment]
I reinstalled gcc using homebrew  - same version as I had before (5.2.0), but this time installed from the bottle - and now netcdf builds from source without error.  I'm not sure exactly what this means, but I will close this issue.
