### ISSUE TITLE
OpenCascade and OCE build incorrectly with recent XCodes

### ISSUE THREAD

**Issue by samitbasu** [Homebrew/homebrew-science#2764]
Hi,

There is an issue in OpenCascade up through (and including 6.9.0) and OCE (up through an including 0.17) where the libraries built are badly broken.  The only solution is to compile in debug mode only.  Here is my ticket on the issue:

https://github.com/tpaviot/oce/issues/576

And here is the original one in OpenCascade where the issue is identified:

http://tracker.dev.opencascade.org/view.php?id=26042

It might make sense to ammend both recipes with Debug builds as a workaround?

Samit

**Comment by dpo** [comment]
Is this Xcode 7 on OSX 10.11?

**Comment by samitbasu** [comment]
No.  It happens with at least 6.3 as well.  Not sure about how far back you
have to go before the optimization was added to clang that breaks
opencascade.

**Comment by github4uw** [comment]
Hi, I also run into trouble when I try to compile apps that base on opencascade or oce. I tried to install gmsh with oce and opencascade. Here are the make logs.
oce: https://cybernetics.spdns.org/owncloud/index.php/s/AmsFTO21moOzTPR
opencascade: https://cybernetics.spdns.org/owncloud/index.php/s/yylJDI8MsaVqZgz

Mac OS 10.10.5 with Xcode 7.0.1 

I build elmerfem from https://github.com/ElmerCSC/homebrew-elmerfem which depends on oce as well. However, it compiled without error.

**Comment by schoeps** [comment]
Can you check if #2885 works for you?

**Comment by samitbasu** [comment]
Unfortunately, it does not.  I had to work out all the paths where home-brew was passing optimization flags to clang.  There were many.  Here are the critical parts of the recipe that works.

```
  def install
    # be conservative since 6.9 has problems with clang if -O2
    # see http://tracker.dev.opencascade.org/print_bug_page.php?bug_id=26042
    ENV.append_to_cflags "-g"
    ENV.remove_from_cflags(/O./)
    ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "g"

    # recent xcode stores it's sdk in the application folder
    sdk_path = Pathname.new `xcrun --show-sdk-path`.strip

    # setting DYLD causes many issues; all tests work fine without; suppress
    inreplace "env.sh", "export DYLD_LIBRARY_PATH", "export OCCT_DYLD_LIBRARY_PATH" if OS.mac?

    cmake_args = std_cmake_args
    cmake_args = cmake_args.map{|s| s.gsub(/RELEASE/,'DEBUG')}.map{|s| s.gsub(/Release/,'Debug')}
    cmake_args << "-DBUILD_CONFIGURATION=Debug"
    cmake_args << "-DCMAKE_PREFIX_PATH:PATH=#{HOMEBREW_PREFIX}"
```
Note the filtering on the CMAKE flags, and the use of BUILD_CONFIGURATION (which is used by open cascade to set build flags also).    I also had to chase down the HOMEBREW_OPTIMIZATION_LEVEL environment flag.  Then I made the following change to the post-install:

```
    bin.install_symlink Dir["#{loc}/bind/*"]
    lib.install_symlink Dir["#{loc}/libd/*"]
```

Note that the failure is _not_ a compilation error (to the earlier posts) - its much worse.  The code compiles with warnings, and then fails at runtime.

FWIW, I tried blacklisting clang in the recipe, and the compilation failed with gcc 5.2.0.  If you want me to send you the recipe, I can do that too.

Samit

**Comment by schoeps** [comment]
yes, please do or open your own pull request. Can you also explain what exactly did not work with my formula? (I do only use a few function of open cascade via gmsh and they seemed to be fine).

**Comment by cpraveen** [comment]
Dear all, is there a fix for this ? I am on el capitan and latest xcode 7.2 and I am stuck with seg faults when running step-54 example from deal.II 8.3.0

**Comment by davydden** [comment]
@cpraveen : I tried what @samitbasu proposed, and indeed the following patch solved segmentation fault in step-54:
```
diff --git a/opencascade.rb b/opencascade.rb
index 9d3b90b..6842bb6 100644
--- a/opencascade.rb
+++ b/opencascade.rb
@@ -29,7 +29,10 @@ class Opencascade < Formula
   def install
     # be conservative since 6.9 has problems with clang if -O2
     # see http://tracker.dev.opencascade.org/print_bug_page.php?bug_id=26042
-    ENV.append_to_cflags "-O1"
+    #ENV.append_to_cflags "-O1"
+    ENV.append_to_cflags "-g"
+    ENV.remove_from_cflags(/O./)
+    ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "g"
 
     # recent xcode stores it's sdk in the application folder
     sdk_path = Pathname.new `xcrun --show-sdk-path`.strip
@@ -38,6 +41,8 @@ class Opencascade < Formula
     inreplace "env.sh", "export DYLD_LIBRARY_PATH", "export OCCT_DYLD_LIBRARY_PATH" if OS.mac?
 
     cmake_args = std_cmake_args
+    cmake_args = cmake_args.map{|s| s.gsub(/RELEASE/,'DEBUG')}.map{|s| s.gsub(/Release/,'Debug')}
+    cmake_args << "-DBUILD_CONFIGURATION=Debug"
     cmake_args << "-DCMAKE_PREFIX_PATH:PATH=#{HOMEBREW_PREFIX}"
     cmake_args << "-DCMAKE_INCLUDE_PATH:PATH=#{HOMEBREW_PREFIX}/lib"
     cmake_args << "-DCMAKE_FRAMEWORK_PATH:PATH=#{HOMEBREW_PREFIX}/Frameworks" if OS.mac?
@@ -81,8 +86,8 @@ class Opencascade < Formula
     # add symlinks to be able to compile against OpenCascade
     loc = OS.mac? ? "#{prefix}/mac64/clang" : "#{prefix}/lin64/gcc"
     include.install_symlink Dir["#{prefix}/inc/*"]
-    bin.install_symlink Dir["#{loc}/bin/*"]
-    lib.install_symlink Dir["#{loc}/lib/*"]
+    bin.install_symlink Dir["#{loc}/bind/*"]
+    lib.install_symlink Dir["#{loc}/libd/*"]
   end
 
   def caveats; <<-EOF.undent
```
I will experiment further to see if `6.9.1` is any better...

**Comment by davydden** [comment]
`6.9.1` does not help, the patch still has to be applied in full..

**Comment by davydden** [comment]
@dpo i think this issue can be closed now

**Comment by cpraveen** [comment]
Thanks a lot. opencascade 6.9.0_3 works for me with the deal.II example step-54
