### ISSUE TITLE
brew install OpenCV fails

### ISSUE THREAD

**Issue by Definiter** [Homebrew/homebrew-science#2767]
Trying to install OpenCV by homebrew but always getting this message.

[/Users/Definiter] > brew install opencv
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing opencv from homebrew/homebrew-science
==> Downloading https://github.com/Itseez/opencv/archive/2.4.9.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv-2.4.9.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/u
==> make
[ 28%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/bitstrm.cpp.o
cd /tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/macbuild/modules/highgui && /usr/local/Library/ENV/4.3/clang++   -DCVAPI_EXPORTS -DHIGHGUI_EXPORTS -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -fno-omit-frame-pointer -msse -msse2 -mavx -Wno-deprecated-declarations   -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fPIC -I/tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/modules/imgproc/include -I/tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/modules/core/include -I/tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/macbuild/modules/highgui -I/tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/modules/highgui/src -I/tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/modules/highgui/include -I/tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/macbuild -isystem /usr/local/include/eigen3 -isystem /usr/local/opt/jpeg/include -isystem /usr/local/include -isystem /usr/local/include/OpenEXR    -o CMakeFiles/opencv_highgui.dir/src/bitstrm.cpp.o -c /tmp/opencv20150922-84053-1t2dpuk/opencv-2.4.9/modules/highgui/src/bitstrm.cpp
[ 28%] Built target opencv_video
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make: *** [all] Error 2

**Comment by tdsmith** [comment]
Can we have the output of `brew gist-logs opencv` please?

**Comment by Definiter** [comment]
@tdsmith it's the output: https://gist.github.com/1f91672e0b74500bd4ba

**Comment by tdsmith** [comment]
Does this succeed after `brew reinstall jpeg`?

**Comment by Definiter** [comment]
@tdsmith Yes, it succeeds after reinstall jpeg. Thank you!
