### ISSUE TITLE
pcl 1.7.2 + openni2

### ISSUE THREAD

**Issue by flipphillips** [Homebrew/homebrew-science#2773]
## One liner
Building PCL w/ support for openni2 is causing me angst.

## Description
I am trying to build pcl v 1.7.2 with OpenNI2 support.

```
$ brew install pcl --with-openni2
```

However, when I debug/verbose the build, I see:

```
--   apps
       building: 
       |_ cloud_composer
       |_ modeler
       |_ point_cloud_editor
       not building: 
       |_ in_hand_scanner: OpenNI was not found or was disabled by the user.
       |_ optronic_viewer: FZAPI was not found.
```

Well, yes, I suppose that is true, in that this is OpenNI2 and not OpenNI. 

## Regressions / desperate flailing

If in install OpenNI (not OpenNI2) I can build w/ OpenNI but 1) nothing from OpenNI2 gets built (even if I specify it on the bulld line) and 2) of course, this is useless because I have an OpenNI2 compatible scanner.

## Configuration
Mac OS X El Capitan
Mac Book Pro Retina
latest HB
Command line tools

**Comment by fran6co** [comment]
This is not a bug it's a limitation of PCL, in_hand_scanner only works with OpenNI 1.x and not OpenNI 2.x. This problem should be reported upstream to https://github.com/PointCloudLibrary/pcl

**Comment by flipphillips** [comment]
OK. so why is it a build option then? Wishful thinking?

**Comment by fran6co** [comment]
No, it actually builds the openni2 grabber so you can use it directly in your code but PCL currently doesn't have any internal app/tool that uses it.

**Comment by fran6co** [comment]
For example there is a PR to add OpenNi2 support to the Kinfu app https://github.com/PointCloudLibrary/pcl/pull/1038
