### ISSUE TITLE
Testing requires the latest version of lammps

### ISSUE THREAD

**Issue by rpthomps** [Homebrew/homebrew-science#2775]
Hello,

I installed Lammps but I get the following message when I try to test it. Any suggestions on how to obtain latest version of Lammps?

Thanks
Ryan

**Comment by dpo** [comment]
Could you try `brew update; brew reinstall lammps` and let me know if the problem persists?

**Comment by rpthomps** [comment]
Hello,

got the following message...

==> Reinstalling lammps
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://lammps.sandia.gov/tars/lammps-12Feb14.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "lammps"
Download failed: http://lammps.sandia.gov/tars/lammps-12Feb14.tar.gz
ryans-air:~ rpthomps$

**Comment by rpthomps** [comment]
that worked. Thank you!
