### ISSUE TITLE
gmsh 2.10 does not open main window

### ISSUE THREAD

**Issue by github4uw** [Homebrew/homebrew-science#2785]
Hi,

I installed gmsh 2.10 via brew on a Mac OS 10.10. homebrew and xcode is up to date.
When I call gmsh from a terminal I only get a list of options and gmsh quits.
But no main window (GUI) opens. However, it does not show any error message.
Any ideas how I could get the GUI running? 
I just involed $ brew install gmsh and the compilation was really fast.
What do I miss?

Thank you!

**Comment by saketkc** [comment]
`brew install gmsh --with-fltk`

**Comment by github4uw** [comment]
Thanks, I tried this but I get an error like:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libGmsh.a(ACISFace.cpp.o) has no symbols

Here is the full make report. https://cybernetics.spdns.org/owncloud/index.php/s/E5UlBQbjnfjOe6Y

How could I fix this?

**Comment by dpo** [comment]
For reference, the first error is
```
Undefined symbols for architecture x86_64:
  "BRepBndLib::Add(TopoDS_Shape const&, Bnd_Box&, unsigned int)", referenced from:
      OCCEdge::bounds() const in OCCEdge.cpp.o
      OCCFace::bounds() const in OCCFace.cpp.o
      OCCFace::buildSTLTriangulation(bool) in OCCFace.cpp.o
      OCCRegion::bounds() const in OCCRegion.cpp.o
```

**Comment by dpo** [comment]
On my machine, the missing symbol is defined in `libTkTopAlgo.dylib`, which is part of `opencascade`. Do you have that library?

**Comment by github4uw** [comment]
I think I fixed it.
I changed the gmsh.rb and downloaded gmsh 2.10.1 instead of 2.10.0.
Furthermore I used oce instead of opencascade. 
Now I can launch gmsh with GUI. I will try an example soon.

To your question: Yes, I have opencascade installed. But it conflicts with oce. I can link either oce or opencascade. However, I need oce enabled in order to use elmerfem.

**Comment by dpo** [comment]
@schoeps Can `gmsh` use either `oce` or `opencascade`? If yes, it might be worth updating the formula.

@github4uw Please feel free to submit a PR with an updated `gmsh` formula!

**Comment by schoeps** [comment]
I am surprised that 2.10.1 works but 2.10.0 not. However, newer is better :) Please submit your file!

... and yes, to my knowdledge oce and opencascade should both work. I will give it a test.

**Comment by github4uw** [comment]
Ok, here is the edited gmsh.rb I used.
https://cybernetics.spdns.org/owncloud/index.php/s/mqvQaXlWDOYqrE7

**Comment by dpo** [comment]
`gmsh` was recently updated, so I'll close this. Please open a new issue if the problem persists.
