### ISSUE TITLE
netcdf --with-fortran failed to build on OSX 10.10.5

### ISSUE THREAD

**Issue by zils25** [Homebrew/homebrew-science#2787]
I'm trying to install petsc and this builds hypre and netcdf as dependencies but fails to build netcdf as it fails the test suite. I find this strange that it installs these dependencies as I already have both installed.

$ brew install netcdf
Warning: homebrew/science/netcdf-4.3.3.1_1 already installed

$ brew install hypre
Warning: homebrew/science/hypre-2 already installed

I uninstalled netcdf and tried reinstalling --with-fortran and this causes the same failure.

Here's the Gist for the netcdf failed build.
https://gist.github.com/anonymous/0703de8b5968c09ccca4

**Comment by dpo** [comment]
Might be an Xcode 7 issue?! Not sure. Could you try again? I just updated the `netcdf` bottle.

**Comment by jhcsu** [comment]
See #2760.  I'm not sure this is related, but looking at the Gist I see you also had an error with conftest.c.  I was able to build netcdf with gfortran only after removing homebrew's gcc and then installing it again using the bottled version.

**Comment by zils25** [comment]
Tried again with the update. Still seeing the same issue. Tried uninstalling and reinstalling gcc and that didn't fix it either. I'm pretty confident that Xcode 7 did indeed cause this as this problem showed up as soon as OSX automatically updated Xcode.

Here is a new Gist
https://gist.github.com/anonymous/3687e414f94c5b629261

**Comment by zils25** [comment]
I resolved the issue by uninstalling all of the petsc dependencies and reinstalling them. Whatever netcdf --with-fortran needed must have been broken by the Xcode update. Thanks.
