### ISSUE TITLE
Error when installing R

### ISSUE THREAD

**Issue by SplashDance** [Homebrew/homebrew-science#2795]
I tried uninstalling **R** and then reinstalling it with OpenBlas support and at the end of the installation process I got this error:

https://gist.github.com/SplashDance/fb7367b94dac4b937929

{% gist fb7367b94dac4b937929 %}

I'm not sure what this means or what the implications of it are but **R** _seems_ to be working so far.

**Comment by tdsmith** [comment]
The build failed; if you had run `brew reinstall`, your previous build was re-linked after the failure.

FWIW openblas probably isn't generally more performant than Apple's Accelerate framework, which is what you get without --with-openblas.

Can you paste the output of `brew gist-logs r` if you want to troubleshoot this?

**Comment by SplashDance** [comment]
Sorry for the delay--I appreciate your help.

I ran the command: https://gist.github.com/anonymous/7c798aa163c599e25af1#file-01-configure

I figured that *something* had gone wrong but what I didn't (and still don't) understand is that when I ran `brew info r` all the dependencies listed have a green check mark next to them except for "valgrind" whereas before there wasn't a check mark next to openblas.

I didn't realize that Accelerate was on par with OpenBlas--I guess I'll just stick with the basic **R** installation.

**Comment by dpo** [comment]
Is this on 10.11? It's not finding `X11/Xlib.h`. Possibilities I see at this point:

* you don't have XQuartz installed
* you can build `--without-x11 --without-tcltk`.

**Comment by SplashDance** [comment]
No, I'm using 10.9.5

**Comment by lmullen** [comment]
I ran into this same problem. Have you run `brew doctor`? That command may complain about a bunch of files related to tcl/tk in `/usr/local/`. The problem is that the CRAN binary version of R installs those header and other files to `/usr/local/` and simply removing the version of R from CRAN does not remove those files. So when you try to build R from source, it uses the wrong version of tcl/tk. If those files exist, removing them may do the trick.

**Comment by iMichka** [comment]
Hi. This issue is pretty old and probably outdated. R has been updated multiple times since the initial report. If you still have troubles  installing R, please open a new issue and fill out the issue template. Thanks.
