### ISSUE TITLE
ROS install fails on OS X 10.10 on qhull step

### ISSUE THREAD

**Issue by mrkaroshi** [Homebrew/homebrew-science#2823]
While installing ROS on an OS X machine I'm getting this error, which also tells me to report the problem here:

$ rosdep install --from-paths src --ignore-src --rosdistro jade -y
Error: undefined method `desc' for Formulary::Formulae::Qhull:Class
Error: undefined method `desc' for Formulary::Formulae::Opencv:Class
executing command [brew install qhull]
Error: undefined method `desc' for Formulary::Formulae::Qhull:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/qhull.rb:2:in `<class:Qhull>'
/usr/local/Library/Taps/homebrew/homebrew-science/qhull.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:42:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
ERROR: the following rosdeps failed to install
  homebrew: command [brew install qhull] failed

Is this something that can be sorted at Brew's end or does it look like an ROS problem?

Thanks in advance.

**Comment by dpo** [comment]
Does `brew install qhull` cause you any trouble?

**Comment by mrkaroshi** [comment]
It prevents the installation of ROS on my system, I've only just started using it but qhull seems to be a necessary dependency.

**Comment by dpo** [comment]
I'm just wondering if `brew install qhull` by itself is problematic, in order to determine whether there's anything on the Homebrew side of things. If not, I'm afraid we don't have anything to do with ROS.

**Comment by mrkaroshi** [comment]
Is there anything more I can give you in terms of logs etc that would be of help?

**Comment by dpo** [comment]
Yes:

1. please try `brew install qhull` directly at the command line and let me know if that completes correctly (no ROS involved)
2. please post here the output of `brew gist-logs qhull`.

**Comment by dpo** [comment]
Bump

**Comment by mrkaroshi** [comment]
Unrelated to this problem I had to completely remove Brew from my system, and now brew install qhull executes fine. I will try on my laptop also, which has a slightly different mixture of software.
