### ISSUE TITLE
can't install ea-utils on el capitan

### ISSUE THREAD

**Issue by alexstaj** [Homebrew/homebrew-science#2826]
MBP:~ Staj$ brew install ea-utils
==> Installing ea-utils from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/ea-utils: gsl
==> Installing homebrew/science/ea-utils dependency: gsl
==> Downloading https://homebrew.bintray.com/bottles/gsl-1.16.el_capitan.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring gsl-1.16.el_capitan.bottle.2.tar.gz
🍺  /usr/local/Cellar/gsl/1.16: 245 files, 8.2M
==> Installing homebrew/science/ea-utils
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU
==> Downloading from https://doc-04-5g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0e71iltu3go42ga2oo5ukqhadk9hs2
######################################################################## 100.0%
==> Patching
patching file sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
==> make install PREFIX=/usr/local/Cellar/ea-utils/1.1.2-806
Last 15 lines from /Users/Staj/Library/Logs/Homebrew/ea-utils/01.make:
  friend void swap(HashtableInterface_DenseHashMap<K2,T2,Empty2,H2,E2,A2>& a,
              ^
./src/hash_test_interface.h:876:15: note: candidate template ignored: could not match 'HashtableInterface_DenseHashSet' against 'HashtableInterface_DenseHashtable'
  friend void swap(HashtableInterface_DenseHashSet<K2,Empty2,H2,E2,A2>& a,
              ^
./src/hash_test_interface.h:1007:15: note: candidate template ignored: substitution failure [with V2 = const char *, K2 = const char *]: deduced non-type template argument does not have the same type as the its corresponding template parameter ('const char *' vs 'const char *const &')
  friend void swap(
              ^
clang++ -Wall -W -Wwrite-strings -Woverloaded-virtual -Wshadow -g -O2   -o simple_compat_test simple_compat_test.o      
6 errors generated.
make[2]: *** [hashtable_test.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/time_hash_map-time_hash_map.Tpo .deps/time_hash_map-time_hash_map.Po
make[1]: *** [all] Error 2
make: *** [sparsehash] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

**Comment by iml** [comment]
Updated the patch; should work after `brew update`.

**Comment by alexstaj** [comment]
Many thanks.
