### ISSUE TITLE
clustal-w install fails on el capitan

### ISSUE THREAD

**Issue by alexstaj** [Homebrew/homebrew-science#2831]
MBP:n5 Staj$ brew install clustal-w
==> Installing clustal-w from homebrew/homebrew-science
==> Downloading http://www.clustal.org/download/2.1/clustalw-2.1.tar.gz
###### ################################################################## 100.0%

==> ./configure --prefix=/usr/local/Cellar/clustal-w/2.1
==> make install
Last 15 lines from /Users/Staj/Library/Logs/Homebrew/clustal-w/02.make:
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
In file included from ./general/VectorOutOfRange.cpp:9:
./general/VectorOutOfRange.h:14:38: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        VectorOutOfRange(std::string vectorName, int index, int max)
                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
clang++ -DHAVE_CONFIG_H -I.     -g -O2 -c -o Stats.o `test -f './general/Stats.cpp' || echo './'`./general/Stats.cpp
2 errors generated.
make[2]: **\* [VectorOutOfRange.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [install-recursive] Error 1
make: **\* [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

Warning:

**Comment by tseemann** [comment]
I can confirm the same error.

Here are my logs created with `brew gist-logs clustal-w`:  https://gist.github.com/6a55dab1c8816f4186d9

I'm not sure if it is El Capitan or Xcode 7.0.1 or a specific new clang++ setting needed.

**Comment by iMichka** [comment]
Has been fixed with b1a12b52277346741e31794cb6ea36fba64e5bcf. We have bottles too now. Closing.
