### ISSUE TITLE
Problem installing Octave

### ISSUE THREAD

**Issue by D063520** [Homebrew/homebrew-science#2835]
Hi, 

I tried to install octave and got the following error:

brew install octave
==> Installing octave from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/octave: veclibfort, arpa
==> Installing homebrew/science/octave dependency: veclibfort
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/mcg1969/vecLibFort/archive/0.4.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/veclibfort-0.4.2.tar.gz
==> make all
==> make check
Last 15 lines from /Users/Dennis/Library/Logs/Homebrew/veclibfort/02.make:
2015-10-05 21:48:15 +0200

make
check

gfortran -o tester -O tester.f90 vecLibFort.o -framework Accelerate 
dyld: Library not loaded: /usr/local/lib/libisl.13.dylib
  Referenced from: /usr/local/Cellar/gcc/5.2.0/libexec/gcc/x86_64-apple-darwin14.4.0/5.2.0/f951
  Reason: image not found
gfortran: internal compiler error: Trace/BPT trap: 5 (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make: *** [check] Error 4

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

Warning: 

OS: 10.11

Thank you
Dennis

**Comment by iml** [comment]
You can try `brew reinstall isl`; that should have been installed along with GCC/gfortran or perhaps it was not linked.

**Comment by D063520** [comment]
Thank you very much for the fast answer!!!! It worked. Now unfortunately when I launch octave I get the following error:

octave
dyld: Library not loaded: /usr/local/lib/libpng16.16.dylib
  Referenced from: /usr/local/lib/libfreetype.6.dylib
  Reason: Incompatible library version: libfreetype.6.dylib requires version 35.0.0 or later, but libpng16.16.dylib provides version 31.0.0
Trace/BPT trap: 5

**Comment by D063520** [comment]
Ok, I had to reinstall freetype. Now it works : ) . Thank you very much!!!!!!!
