### ISSUE TITLE
Add MKL as an alternative to openblas?

### ISSUE THREAD

**Issue by zachmayer** [Homebrew/homebrew-science#2840]
Intel just released MKL for free: https://software.intel.com/en-us/articles/free_mkl

I was wondering if someone would be willing to look into adding MKL to homebrew?  I'm currently using and loving openblas through brew and would love to compare to MKL.

**Comment by dpo** [comment]
MKL for OSX isn't free.

**Comment by zachmayer** [comment]
Boooooo

**Comment by dpo** [comment]
I know.

**Comment by zachmayer** [comment]
Why would they release it for free on Windows and Linux, but not mac?  That sucks!

**Comment by tdsmith** [comment]
I asked and they mostly didn't answer: https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/590743#comment-1838284

**Comment by zachmayer** [comment]
Well then, :+1: for open-source software.  I'll keep using open blas.

**Comment by dpo** [comment]
Seems like I convinced Intel to release MKL for OSX under the Community License terms.

**Comment by zachmayer** [comment]
Awesome!  Let's put it in homebrew



—

**Comment by cbrnr** [comment]
Any update on this one? It would be great if we could use Homebrew Python using MKL just like in Anaconda.

**Comment by robsalasco** [comment]
+1

**Comment by iMichka** [comment]
FYI homebrew science will be closed end of December. So if you want add MKL, a pull request is welcome, but in homebrew-core. You can also host formulae in your own taps.
