### ISSUE TITLE
PCL needs to be rebottled

### ISSUE THREAD

**Issue by mikepurvis** [Homebrew/homebrew-science#2852]
The [update from VTK 6.2 to 6.3](https://github.com/Homebrew/homebrew-science/pull/2765) removed the `vtkRenderingFreeTypeOpenGL` library, but it's still baked into the PCL bottle's pkgconfig file, eg:

https://github.com/PointCloudLibrary/pcl/blob/2da3198a0b28e98bff18d881c6cb247de6458496/PCLConfig.cmake.in#L404

This means there are linker errors building stuff dependent on PCL with the current bottles for VTK 6.3 and PCL 1.7.2. Building from source fixes the issue.

**Comment by dpo** [comment]
Please try again. I just updated the bottle.

**Comment by mikepurvis** [comment]
Looks good now, thanks.
