### ISSUE TITLE
brew install opencv --with-ffmpeg fails

### ISSUE THREAD

**Issue by RababamSabou** [Homebrew/homebrew-science#2862]
On Yosemite OSX I get this:

$ brew install opencv --with-ffmpeg

==> Installing opencv from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/2.4.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv-2.4.11.tar.gz
==> Downloading https://gist.githubusercontent.com/tdsmith/484553cd2d0c19a4baa7/
Already downloaded: /Library/Caches/Homebrew/opencv--patch-cfe31c32d5a4ef0e89df684e210360602fb2d295b19f9ca4791731a9e274d776.diff
==> Patching
patching file modules/python/CMakeLists.txt
==> Installing opencv from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/2.4.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv-2.4.11.tar.gz
==> Downloading https://gist.githubusercontent.com/tdsmith/484553cd2d0c19a4baa7/
Already downloaded: /Library/Caches/Homebrew/opencv--patch-cfe31c32d5a4ef0e89df684e210360602fb2d295b19f9ca4791731a9e274d776.diff
==> Patching
patching file modules/python/CMakeLists.txt
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL
==> make
cd /tmp/opencv20151009-5902-10czmie/opencv-2.4.11/macbuild/modules/video && /usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_symlink_library ../../lib/libopencv_video.2.4.11.dylib ../../lib/libopencv_video.2.4.dylib ../../lib/libopencv_video.dylib
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /tmp/opencv20151009-5902-10czmie/opencv-2.4.11/macbuild/CMakeFiles  98
[ 17%] Built target opencv_video
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make: *** [all] Error 2

And this is the output of brew gist-logs opencv:

https://gist.github.com/c207df6fe08ccc47be70

**Comment by danfitz7** [comment]
I have the same issue. Did you resolve it?

**Comment by joeangel** [comment]
On OSX EI Caption I install succeed!

```
brew install ffmpeg
brew tap homebrew/science
brew install --HEAD opencv --with-ffmpeg
```

**Comment by dimatteomaurizio** [comment]
I can confirm @joeangel 's solution works on OSX 10.11.5

**Comment by heinemml** [comment]
This problem should be fixed with the latest release (published June 4. on homebrew).

**Comment by dpo** [comment]
Please update and open a new issue if problems still exist.
