### ISSUE TITLE
getdp does not build due of conflicting formula

### ISSUE THREAD

**Issue by github4uw** [Homebrew/homebrew-science#2872]
Hi,

I want to use the following packages: 
elmerfem from ElmerCSC/homebrew-elmerfem --> installed --> depends on oce
gmsh from homebrew-science --> installed --> build with oce
getdp from homebrew-science --> not installed

This is what I get when I try to install getdp:
$ brew install getdp
==> Installing getdp from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/getdp: opencascade, hypre
==> Installing homebrew/science/getdp dependency: opencascade
Error: Cannot install homebrew/science/opencascade because conflicting formulae are installed.

  oce: because OCE is a fork for patches/improvements/experiments over OpenCascade

Please `brew unlink oce` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

Ok, I could unlink oce and link again later. But I am not sure if this a working or good solution.
Here is the issue: elmerfem depens on oce and need it to be active/ linked at runtime.
Gmsh can be build using oce instead of opencascade, which is a good thing.
Getdp seems to depend on opencascade and can not be build with oce.
The question is: Can I build it using opencascade and then link oce again? Or would getdp require opencascade at runtime? Or could I build getdp with oce?
How can I have oce and opencascade at the same time and each program "calls" what it needs? Or would it be possible to build all packages in homebrew-science with oce?

How could I resolve this conflict generally?

Thank you for your help!

**Comment by dpo** [comment]
`getdp` depends on `gmsh` and that's where the dependency on `opencascade` comes from. However, you can `brew install gmsh --with-oce --without-opencascade` to build it against `oce` instead. Let me know if that resolves your issue.

**Comment by github4uw** [comment]
Yes, this resolves the issue.
$ brew install gmsh --without-opencascade --with-oce
$ brew install getdp --without-opencascade --with-oce --with-gmsh

However, I seems that I need to give the same options to getdp as to gmsh. $ brew install getdp alone gives the error mentioned above.

**Comment by dpo** [comment]
There's no need to specify `--with-gmsh` when you build `getdp`, it's the default. You only need to specify non-default options. See `brew options getdp`. By default, `gmsh` builds against `opencascade`, and that's what will happen if you don't specify otherwise.
