### ISSUE TITLE
Lammps image not found

### ISSUE THREAD

**Issue by raymound** [Homebrew/homebrew-science#2874]
Hi,
I just installed LAMMPS and I'm getting this error any idea how to fix it?
I'm on OS X Yosemite.

dyld: Library not loaded: /usr/local/lib/libmpi_cxx.1.dylib
  Referenced from: /usr/local/bin/lammps
  Reason: image not found

**Comment by dpo** [comment]
Please post the output of `brew gist-logs lammps`. Did you build from source or bottle?

**Comment by dpo** [comment]
@raymound

**Comment by raymound** [comment]
https://gist.github.com/anonymous/1a4a823b19f8d5355b7d

**Comment by chrisjsewell** [comment]
FYI I have the same problem (from bottle on Yosemite), thanks Chris

**Comment by demkowicz** [comment]
I had the same problem on El Capitan (OS 10.11.1). brew gist-logs lammps returns: https://gist.github.com/75dd50b642a465ad1a94

**Comment by dpo** [comment]
This should be resolved by recent MPI updates. Please reopen if still having issues.

**Comment by jianqixi** [comment]
Hi I meet the similar issue when running lammps, it shows
"dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib
  Referenced from: /usr/local/Cellar/lammps/2017.08.11/bin/lammps
  Reason: image not found

the brew gist-logs lammps returns: 
https://gist.github.com/17bf367fde7af97a348489bee45ab4b4
