### ISSUE TITLE
Versioned Tap Hackathon Proposal

### ISSUE THREAD

**Issue by jmchilton** [Homebrew/homebrew-science#2876]
All, so me and other members of the Galaxy community are still interested in using Homebrew/Linuxbrew to do dependency management. There was a long discussion of this on #1191 and ultimate decision that this particular tap is not appropriate #1215. The consensus was that the appropriate choice for solving the reproduciblity problem is a version-ed variant of homebrew science, I think we should start hacking on it.

I want to get the two communities talking and working on the same page and I think a virtual hackathon (contribution feast) might be the way to do that. We have some experience doing this in Galaxy (galaxyproject/tools-iuc#239) and I like to extend the idea to span both communities if possible.

I think frequently the problem with such efforts is a lack of incentives - I would like to propose a two pronged incentive structure to get everyone hacking.

The primary incentive would be to put together a publication (maybe for F1000 for instance) on the idea of using version-ed homebrew taps. Everyone who contributes to the new tap during the hackathon will get to be a co-author on the publication (an approach I first noticed done by the [khmer project](http://f1000research.com/articles/4-900/v1)). To tie the paper together, we could find some older article with interesting and accessible data analysis using older versions of tools and ensure we have both the old and new versions available in the new tap and reanalyze the data with both the older and newer versions of the software.

There is a [NIH BD2K hackathon funding opportunity] (https://datascience.nih.gov/bd2k/news/17SEPT2015-BD2KCC-hackathons) that must be submitted in a few days that we could also apply for. This would give the hackathon more attention, could cover open access fees associated with the paper described above, and maybe even cover the costs of t-shirts or food for the people involved - providing a little more incentive to participate.

Anyone from the homebrew-science community interested in working with us on this effort (at any level, the tap, the hackathon, or the proposal).

**Comment by saketkc** [comment]
John, count me in for the hackathon and the proposal.

**Comment by jmchilton** [comment]
@saketkc Proposal isn't done yet, not even close - but I have work in progress here (https://docs.google.com/document/d/1WZrSg_P9YwCh9n3JUoyae9TyFP-8tt3MTdMKzsrf5QI/edit?usp=sharing). I've tentatively added your name as a co-organizer - hope this is okay with you. Anton or Dave may decide that people with actual PhDs instead of you and I should be listed on the final document - hope that is okay also. In the meantime, any help on the proposal would be greatly appreciated.

I'm completely arbitrarily listing January 13 to January 15th of 2016 as the dates of the hackathon, if that doesn't work for you we should change it.

**Comment by tdsmith** [comment]
My unsolicited advice is that I think maintaining formulas indefinitely as the platforms (Homebrew and OS) change beneath them is a bigger problem than writing formulas, but that's not easily solved by a hackathon.

Ultimately, dockerizing tools seems like a much cleaner solution to me since it freezes all the moving parts from the underlying package manager and OS, and there's already infrastructure for distributing dependency-complete binary images (which don't depend on historical source tarballs for each tool and dependency continuing to be available on the Web).

That said, I think it probably is possible to write versioned formulas that build today with plausible ergonomics.

I would consider attending an event in Socal.

**Comment by jmchilton** [comment]
Forgot about this issue. We did land up submitting a proposal and the NIH did not even respond :angry:. Closing this issue now and thanks everyone for the feedback.
