### ISSUE TITLE
Opencv pulls gcc and does not use clang

### ISSUE THREAD

**Issue by spaghetti-** [Homebrew/homebrew-science#2891]
Is there any particular reason for it?

Since I don't want to build gcc I did `brew install gcc --force-bottle` however it'll give warnings like

```
Warning: homebrew/science/opencv dependency gcc was built with a different C++ standard              
library (libstdc++ from clang). This may cause problems at runtime.
```
I would like to avoid this and just use clang to begin with.

**Comment by iml** [comment]
Probably it was from a Fortran-using dependency such as numpy. The warning above is normal, as gcc is built with libstdc++ but clang uses libc++ by default.

**Comment by spaghetti-** [comment]
Alright, but why should we pull gcc in the first place?

**Comment by iml** [comment]
For GFortran, clang doesn't have a fortran compiler.

**Comment by spaghetti-** [comment]
Ah, thanks for clearing that up. Closing issue.
