### ISSUE TITLE
Brew doesn't complete the compilation of OCTAVE

### ISSUE THREAD

**Issue by apstein** [Homebrew/homebrew-science#2895]
Here are the last process messages:

[ 89%] Linking C static library libqhullstatic_p.a
/usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/qhullstatic_p.dir/cmake_clean_target.cmake
/usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/qhullstatic_p.dir/link.txt --verbose=1
/usr/local/bin/ar cq libqhullstatic_p.a  CMakeFiles/qhullstatic_p.dir/src/libqhull/global.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/stat.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/geom2.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/poly2.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/merge.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/libqhull.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/geom.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/poly.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/qset.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/mem.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/random.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/usermem.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/userprintf.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/io.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/user.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/rboxlib.c.o CMakeFiles/qhullstatic_p.dir/src/libqhull/userprintf_rbox.c.o
/usr/local/bin/ranlib libqhullstatic_p.a
[ 89%] Built target qhullstatic_p
/usr/local/bin/ranlib libqhullcpp.a
[ 89%] Built target qhullcpp
make: *** [all] Error 2

**Comment by schoeps** [comment]
You have a problem with qhull. Try `brew install qhull` before installing octave. Please post the result of `brew gist-logs qhull` if the problem persists.

**Comment by dpo** [comment]
`qhull` is a `:recommended` dependency, so `brew install octave` should have installed it. Let's see the gist logs indeed.

**Comment by dpo** [comment]
@apstein

**Comment by mlaneuville** [comment]
same problem here

running "brew upgrade octave" leads to the following error message:
[...]
==> make install
or do a web search for TeX and your operating system or distro.
make[3]: *** [octave.dvi] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

"brew install qhull" leads to "Warning: qhull-2012.1 already installed" and 
"brew gist-logs qhull" is empty
"brew gist-logs octave" is here: https://gist.github.com/0edebe9daa2dfa2cadc3

For information, the initial "brew upgrade octave" lead to
"Error: You must `brew link ghostscript imagemagick' before octave can be installed"
which I successfully did

any thoughts?

**Comment by schoeps** [comment]
can you do an `brew update` and `brew upgrade`? The gist says that you trying to install the outdated octave 3.8.x.

**Comment by mlaneuville** [comment]
This worked thank you! For education sake, what did you look for in the gist? I had a quick look and did not find anything relevant (that file is huge!).

Now I have this problem when running octave:

    dyld: Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
      Referenced from: /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib
      Reason: image not found
    Trace/BPT trap: 5

Which seems to be related to update to el capitan... I'll investigate and open a new thread if i can't figure it out.

**Comment by dpo** [comment]
It seems you're still running an outdated version. Could you do `brew uninstall -f octave` followed by `brew uninstall $(brew deps octave)`, `brew update` and finally `brew install octave`?

**Comment by mlaneuville** [comment]
~$ brew uninstall -f octave
    Uninstalling octave... (4288 files, 107M)

    ~$ brew uninstall $(brew deps octave)
    Error: No such keg: /usr/local/Cellar/d-bus

    ~$ brew update  
    Updated Homebrew from fccd36e9 to c6ca4a1f.

    ~$ brew install octave
    ==> Installing octave from homebrew/homebrew-science
    ==> Downloading https://homebrew.bintray.com/bottles-science/octave-4.0.0_1.el_capitan.bottle.tar.gz
    [...no issue...]
    ==> Summary
    🍺  /usr/local/Cellar/octave/4.0.0_1: 2178 files, 53M

I am not sure what the brew gist-logs are supposed to show, but I did it on octave again and it shows the same file as yesterday. For info:

    ~$ brew info octave
    homebrew/science/octave: stable 4.0.0 (bottled), HEAD

**Comment by schoeps** [comment]
>For education sake, what did you look for in the gist?

I was lucky: the second line line `./configure [...] --prefix=/usr/local/Cellar/octave/3.8.2`told me that you are installing octave 3.8.2 instead of 4.00

> I am not sure what the brew gist-logs are supposed to show, but I did it on octave again ...

There are no new log files. You asked homebrew for latest version of Octave with standard options and in this case the binary was not compiled locally on your computer but a precompiled version ("bottle") was downloaded. Hence no need for additional log files.

**Comment by supreetSinghBhatia** [comment]
@dpo I'm facing a problem in installing octave through brew can you please help me

**Comment by schoeps** [comment]
@supreetSinghBhatia if your problem is different, then please open a new issue. In either case you need to explain the problem. Please read http://docs.brew.sh/Troubleshooting.html before doing so.

**Comment by supreetSinghBhatia** [comment]
@schopes brew doctor is showing me these warnings

**Comment by supreetSinghBhatia** [comment]
@schoeps 
Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (8.0) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.
