### ISSUE TITLE
R install jpeg fails with prefixed Homebrew

### ISSUE THREAD

**Issue by elmar-hinz** [Homebrew/homebrew-science#2906]
My issue seems a little complex. It may be related to Homebrew, it may be not. If I am in the wrong place please close the ticket.

I run Homebrew on a prefix  `/Users/ElmarHinz/Homebrew/` to control everything in my User directory as far as possible.

### Includes

All R packages did build well so far, but the package `jpeg` fails. It does not find `jpeglib.h` which is in `/Users/ElmarHinz/Homebrew/Cellar/jpeg/8d/include/`. I downloaded the sources from https://github.com/s-u/jpeg to run `R CMD check .`

From `..Rcheck/00install.out`:
```
* installing *source* package ‘jpeg’ ...
** libs
clang -I/Users/ElmarHinz/Homebrew/Cellar/r/3.2.2_1/R.framework/Resources/include -DNDEBUG  -I/Users/ElmarHinz/Homebrew/opt/gettext/include -I/Users/ElmarHinz/Homebrew/opt/readline/include -I/Users/ElmarHinz/Homebrew/opt/openssl/include    -fPIC  -g -O2  -c write.c -o write.o
In file included from write.c:1:
./rjcommon.h:11:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
```

The missing part in the `clang` call  seems ` -I/Users/ElmarHinz/Homebrew/Cellar/jpeg/8d/include/`. If I run the line manually and add this include directory, there is no error.

**What is the reason, that `R CMD check` and `R CMD install` don't add the jpeg include directory while it finds those others?**

Where to go to fix this?

Note: This is similar to the following post, but `xcode-select --install` doesn't fix it in my case.

http://dequeue.blogspot.de/2015/04/trouble-installing-jpeg-r-package-on-osx.html

### Linking

I can workaround the include issues by symlinking the missing header files into an available include directory. That doesn't finally fix it, as now linking errors occur:

```
> ...
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Users/ElmarHinz/Homebrew/Cellar/r/3.2.2_1/R.framework/Resources/lib -L/Users/ElmarHinz/Homebrew/opt/gettext/lib -L/Users/ElmarHinz/Homebrew/opt/readline/lib -L/Users/ElmarHinz/Homebrew/opt/openssl/lib -o jpeg.so read.o write.o -ljpeg -F/Users/ElmarHinz/Homebrew/Cellar/r/3.2.2_1/R.framework/.. -framework R -lintl -Wl,-framework -Wl,CoreFoundation
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [jpeg.so] Error 1
ERROR: compilation failed for package ‘jpeg’
* removing ‘/Users/ElmarHinz/Library/R/3.2/library/jpeg’
```

Do I need to set up a link path as an environment variable? To my understanding that should only be an option for debugging, but not as a final solution.

**Comment by elmar-hinz** [comment]
I did some hours of debugging and came to a file  `[path-to-R.framewort]/Resources/etc/Makeconf`.

```
CPPFLAGS = -I/Users/ElmarHinz/Homebrew/opt/gettext/include -I/Users/ElmarHinz/Homebrew/opt/readline/include -I/Users/ElmarHinz/Homebrew/opt/openssl/include
LDFLAGS = -L/Users/ElmarHinz/Homebrew/opt/gettext/lib -L/Users/ElmarHinz/Homebrew/opt/readline/lib -L/Users/ElmarHinz/Homebrew/opt/openssl/lib
```

Obviously this file is written by the brewing process but it doesn't include the pathes to build and link the **CRAN jpeg package**.

 I don't fully understand home-brew. I think I would not have this issue if **jpeg** would be added in `homebrew-science/r.rb` line 109 ff:

    # Help CRAN packages find gettext, readline, and openssl
    %w[gettext readline openssl].each do |f|
      ENV.append "CPPFLAGS", "-I#{Formula[f].opt_include}"
      ENV.append "LDFLAGS", "-L#{Formula[f].opt_lib}"
    end

Now the question is if **jpeg** should be added? I argue YES, because there is a dependency declared in line 39: `  depends_on "jpeg"`. I think this is a strong indicator that the CRAN package **jpeg** is intended to be installable.

**Comment by tdsmith** [comment]
I think the best fix is to add HOMEBREW_PREFIX/include and HOMEBREW_PREFIX/lib to Makeflags after R is installed, because we don't want those flags present for the build, but it is convenient to have them specified for package builds.

**Comment by elmar-hinz** [comment]
@tdsmith Probably you are right. I am not deep enough in this to understand it.

I tested my approach now. I can install the CRAN **jpeg** now:

https://github.com/elmar-hinz/homebrew-science/commit/d07e19f787bbfdcfe666fc9ab8ca8c62018756cd

```
CPPFLAGS = -I/Users/ElmarHinz/Homebrew/opt/gettext/include -I/Users/ElmarHinz/Homebrew/opt/readline/include -I/Users/ElmarHinz/Homebrew/opt/openssl/include -I/Users/ElmarHinz/Homebrew/opt/jpeg/include
LDFLAGS = -L/Users/ElmarHinz/Homebrew/opt/gettext/lib -L/Users/ElmarHinz/Homebrew/opt/readline/lib -L/Users/ElmarHinz/Homebrew/opt/openssl/lib -L/Users/ElmarHinz/Homebrew/opt/jpeg/
```

Should I send a pull request?

**Comment by tdsmith** [comment]
This should Just Work now. Thanks for reporting!

**Comment by elmar-hinz** [comment]
Confirmed. It works. Thank you.
