### ISSUE TITLE
UPDATE LAMMPS WITH COLVARS

### ISSUE THREAD

**Issue by jmatha2** [Homebrew/homebrew-science#2911]
I have tried updating my lammp with colvar so that I can have colvar working with my lammps. I have downloaded the colvar files and executables and stored them in folder called colvar.
My question is, how do I update it?

**Comment by dpo** [comment]
I'm not a Lammps user and it's hard for me to tell if you're asking a Homebrew question or a Lammps question.

**Comment by dpo** [comment]
This seems to be a Lammps question, and not a Homebrew question. Please reopen if I'm mistaken.
