### ISSUE TITLE
version extraction fails for Hypre

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2916]
_From @davydden on October 19, 2015 21:43_

subj.

Here's what Homebrew does
```
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/externalpackages/hypre-2.10.0b-p2.tar.gz
Already downloaded: /Library/Caches/Homebrew/hypre-2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/hypre/2
```
as you see it's `2` instead of `2.10.0b`.

_Copied from original issue: Homebrew/homebrew#45161_

**Comment by bfontaine** [comment]
_From @davydden on October 19, 2015 22:10_

the worst is that it keeps re-installing `hypre` when installing any formulae which uses it even when one specifies `version "2.10.0b"`. @dpo any ideas?

**Comment by dpo** [comment]
#2917 apparently fixes it for me. I did `brew install petsc` and it did not re-install `hypre`. I'm not sure why `version "2.10.0b" causes rebuilds because that's the version encoded in the bottle file name.
