### ISSUE TITLE
"No Java runtime present, requesting install."

### ISSUE THREAD

**Issue by arvestad** [Homebrew/homebrew-science#2919]
Can octave.rb be instructed to download the appropriate JRE when installing? It is a bit disappointing to start up Octave after finally having GCC 5.2 compiled, only to see that it also needs a Java runtime. :-)

Also: why does Octave need a java runtime? This drives me crazy. Octave worked just fine as a C program back when I last used it.

**Comment by dpo** [comment]
`brew install octave --without-java`.

Java isn't managed by Homebrew. It must be installed as a prerequisite.

**Comment by tseemann** [comment]
@arvestad Lars - you can type `brew info octave` to see all the build options, and `octave` has *many*.

**Comment by arvestad** [comment]
Thanks, yeah, I found I could install without JRE. It is strange to me why Octave would need a JRE though. 

	Thanks,
	Lars
