### ISSUE TITLE
VecLibFort install error

### ISSUE THREAD

**Issue by ifuchs** [Homebrew/homebrew-science#2921]
I am trying to install the latest Octave for a class and the install is failing thus:
brew install octave
==> Installing octave from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/octave: veclibfort, arpack, jpeg, libtiff, jbig2dec, little-cms2, libpng, freetype, ghostscript, epstool, fftw, glpk, gl2ps, fontconfig, gd, lua, gnuplot, libtool, graphicsmagick, szip, hdf5, cmake, qhull, qrupdate, plotutils, 
==> Installing homebrew/science/octave dependency: veclibfort
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/mcg1969/vecLibFort/archive/0.4.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/veclibfort-0.4.2.tar.gz
==> make all
==> make check
Last 15 lines from /Users/ihf/Library/Logs/Homebrew/veclibfort/02.make:
check

gfortran -o tester -O tester.f90 vecLibFort.o -framework Accelerate 
Undefined symbols for architecture x86_64:
  "__gfortran_set_options", referenced from:
      _main in ccd0lD80.o
  "__gfortran_transfer_character_write", referenced from:
      _MAIN__ in ccd0lD80.o
  "__gfortran_transfer_complex_write", referenced from:
      _MAIN__ in ccd0lD80.o
  "__gfortran_transfer_real_write", referenced from:
      _MAIN__ in ccd0lD80.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [check] Error 1
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

Before I try to figure out how best to uninstall MacPorts/Fink and possibly create new problems, can anyone tell me if the above error is perhaps fixable some other way? If uninstalling Macports is the likely culprit, what is the best way to do that?

**Comment by dpo** [comment]
It would help if you posted the output of `brew gist-logs veclibfort` here.

You'll have to check the MacPorts documentation to learn how to uninstall it (I've never used it). If you use MacPorts to install gfortran, then that is a likely culprit.

**Comment by ifuchs** [comment]
Thanks for the reply.
brew gist-logs veclibfort
https://gist.github.com/325c4b75e5529387ec8a

**Comment by ifuchs** [comment]
Also, gfortran seems to be pointing to the Homebrew version.

**Comment by dpo** [comment]
`brew doctor` says that there are gcc/gfortran-related libraries in `/usr/local/lib`, so that might be the problem. If it's feasible for you, the next thing to try is to uninstall Macports gcc and gfortran.

**Comment by ifuchs** [comment]
I do not seem to have a proper Macports installation. I may; however, have the remnants of a previous install. Question is, what is the best way to remove whatever is causing the problem with brew?

**Comment by dpo** [comment]
You could move `/opt/local` out of the way, as suggested by Dr. Brew, as well as all links in `/usr/local/bin`, `/usr/local/lib`, `/usr/local/include`, `/usr/local/share`, etc., that point to that location. Check also Fink (Dr. Brew says there's `/sw/bin/fink`. You'll have to refer to the Macports and Fink documentation because I haven't used either in years.

**Comment by ifuchs** [comment]
Brew Doctor says to sudo mv /opt/local ~/macports but I have no /opt/local directory. /sw/bin/fink says:
/sw/bin/fink
arch: /usr/bin/perl5.10.0 isn't executable

probably another remnant from an earlier install. I don't know what to delete to get the install to complete.

**Comment by ifuchs** [comment]
I moved everything that Brew Doctor listed as potentially problematic out of the way and was then able to successfully install Octave 4.0.
