### ISSUE TITLE
Octave: problems installing io package

### ISSUE THREAD

**Issue by ifuchs** [Homebrew/homebrew-science#2926]
I am running v4.0 and trying to install the io package. My output:

octave:1> pkg install -forge io
xmltree_read.l:407:34: warning: multiple unsequenced modifications to 'pcdata'
      [-Wunsequenced]
  LEAVE; STag_scalar(); pcdata = BUFFERSET(pcdata); ENTER(IN_scalar);
                               ~ ^
xmltree_read.l:145:26: note: expanded from macro 'BUFFERSET'
#define BUFFERSET(P)  (P = next)
                         ^
xmltree_read.l:492:34: warning: multiple unsequenced modifications to 'pcdata'
      [-Wunsequenced]
  LEAVE; STag_string(); pcdata = BUFFERSET(pcdata); ENTER(IN_string);
                               ~ ^
xmltree_read.l:145:26: note: expanded from macro 'BUFFERSET'
#define BUFFERSET(P)  (P = next)
                         ^
xmltree_read.l:627:37: warning: multiple unsequenced modifications to 'pcdata'
      [-Wunsequenced]
  LEAVE; STag_structure(); pcdata = BUFFERSET(pcdata); ENTER(IN_structure);
                                  ~ ^
xmltree_read.l:145:26: note: expanded from macro 'BUFFERSET'
#define BUFFERSET(P)  (P = next)
                         ^
xmltree_read.l:673:32: warning: multiple unsequenced modifications to 'pcdata'
      [-Wunsequenced]
  LEAVE; STag_list(); pcdata = BUFFERSET(pcdata); ENTER(IN_list);
                             ~ ^
xmltree_read.l:145:26: note: expanded from macro 'BUFFERSET'
#define BUFFERSET(P)  (P = next)
                         ^
xmltree_read.l:726:32: warning: multiple unsequenced modifications to 'pcdata'
      [-Wunsequenced]
  LEAVE; STag_cell(); pcdata = BUFFERSET(pcdata); ENTER(IN_cell);
                             ~ ^
xmltree_read.l:145:26: note: expanded from macro 'BUFFERSET'
#define BUFFERSET(P)  (P = next)
                         ^
5 warnings generated.
csv2cell.cc:219:57: warning: '&&' within '||' [-Wlogical-op-parentheses]
    if ((i==len) || ((str[i] == sep) || (str[i] == 10)) && (!inside))
                 ~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
csv2cell.cc:219:57: note: place parentheses around the '&&' expression to
      silence this warning
    if ((i==len) || ((str[i] == sep) || (str[i] == 10)) && (!inside))
                                                        ^
                    (                                               )
1 warning generated.
For information about changes from previous versions of the io package, run 'news io'.

Can anyone tell me what is wrong?

**Comment by dpo** [comment]
I get similar output. However they only seem to be warnings, and `news io` seems to say that `io` was indeed installed. @schoeps might be able to tell us if those warnings are harmful.

**Comment by ifuchs** [comment]
Yes, I wondered the same but then I tried:
A = xlsread('test4.xls', '2nd_sheet', 'C3:AB40');
warning: Functions for spreadsheet style I/O (.xls .xlsx .sxc .ods .dbf .wk1
etc.) are provided in the io package. See `http://octave.sf.net/io/'.

Please read `http://www.octave.org/missing.html' to learn how you can
contribute missing functionality.
warning: called from
    __unimplemented__ at line 524 column 5
error: 'xlsread' undefined near line 1 column 5

**Comment by ifuchs** [comment]
NM. Neglected to do pkg load io (only did install). Still new to Octave. xlsread now works.

**Comment by dpo** [comment]
Good. Enjoy.
