### ISSUE TITLE
installing lammps homebrew error

### ISSUE THREAD

**Issue by mah65** [Homebrew/homebrew-science#2935]
I received this error while installing lammps on my mac:

...
patching file python/lammps.py
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file python/lammps.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1

It seems that I am able to run and use lammps, but is there any package missing by this error?

**Comment by dpo** [comment]
`brew` shouldn't have installed `lammps` at all if there's such an error. Did you already have a version of `lammps` installed in some other way? Is there a reason why you're building from source and not using a bottle?

I tried building from source anyways and the patch works for me. Could you post the output of `brew gist-logs lammps`?

**Comment by mah65** [comment]
I think I had another version, but I unlinked it before installing a new version.

This is the output as your requested:

Error: No logs.

I need the latest version of lammps installed on my mac (26 Oct 2015). How can I do that?

**Comment by dpo** [comment]
`brew install lammps --force-bottle` should simply install the bottle even if you've set `HOMEBREW_BUILD_FROM_SOURCE=1` in your environment.

**Comment by tseemann** [comment]
@mah65 make sure you have run `brew update` recently too.

**Comment by mah65** [comment]
Thanx dpo and tseemann,

So, I think I have this version installed: 
homebrew/science/lammps-2015.02.10_2 already installed

But I need the latest version of lammps (26 Oct 2015), if it is available on homebrew.

**Comment by dpo** [comment]
We don't have it. I recall trying to update the formula and running into build errors. Another user had the same issues. If you're familiar with the `lammps` code, we'd gladly accept a pull request.

**Comment by mah65** [comment]
I updated it.
Thank you so much

**Comment by dpo** [comment]
If you updated the formula, please submit a pull request.

**Comment by mah65** [comment]
I'm sorry. I'm new to these coding stuff! I may need more explanations to
understand things!
I just meant: I updated brew update.

**Comment by saketkc** [comment]
You might try a `brew cleanup` before doing a `brew install` just to ensure, it is not picking wrong version from the cache.
