### ISSUE TITLE
Installing OpenCV attempts to reinstall gcc 5.2

### ISSUE THREAD

**Issue by aaarbk** [Homebrew/homebrew-science#2938]
I'm on OS X 10.11 (El Capitan).
I'm trying to install OpenCV using Homebrew, but as soon as the installation starts, it starts installing gcc as a dependency. 

> ==> Installing opencv from homebrew/homebrew-science
> ==> Installing dependencies for homebrew/science/opencv: gcc, cmake, eige
> ==> Installing homebrew/science/opencv dependency: gcc
> ==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2

The problem is, I already have gcc 5.2.0 installed via Homebrew:

> gcc-5 --version
> gives "gcc-5 (Homebrew gcc5 5.2.0) 5.2.0"

I tried poking in the opencv formula, but I couldn't even find a mention of gcc there. 

What should I do?

PS 
If it matters, I had some version of OpenCV installed previously via brew, but later removed it.

**Comment by tseemann** [comment]
@aaarbk Can you try `brew install opencv --c++11" ?

**Comment by aaarbk** [comment]
@tseemann 
I tried your suggestion, but I'm getting exactly the same output as before.
FWIW, I tried installing opencv3 with brew and even that logs the same output.

**Comment by dpo** [comment]
Could you `brew update` and let us know if you're still having this issue?

**Comment by dpo** [comment]
@aaarbk

**Comment by tibaes** [comment]
Well, I am having this issue. I tested it today in two different machines and it still reinstall gcc (which requires an annoying long time to compile).

**Comment by iMichka** [comment]
I will close this bug because the initial bug report is very old.

@tibaes Please open a new issue and fill out the issue template so that we can try to help you.
