### ISSUE TITLE
Can't install openBlas on new macbook pro with El Capitan

### ISSUE THREAD

**Issue by dkouzoup** [Homebrew/homebrew-science#2941]
I am trying to install open blas on a new mac book pro and get the error:

==> Installing openblas from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/xianyi/OpenBLAS/archive/v0.2.14.tar.gz
Already downloaded: /Library/Caches/Homebrew/openblas-0.2.14.tar.gz
==> make FC=/usr/local/bin/gfortran libs netlib shared
Last 15 lines from /Users/diehl/Library/Logs/Homebrew/openblas/01.make:
    printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
                                                                   ^
getarch_2nd.c:69:50: error: use of undeclared identifier 'CGEMM_DEFAULT_Q'
    printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
                                                 ^
getarch_2nd.c:69:68: error: use of undeclared identifier 'CGEMM_DEFAULT_UNROLL_N'
    printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
                                                                   ^
getarch_2nd.c:70:50: error: use of undeclared identifier 'ZGEMM_DEFAULT_Q'
    printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
                                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [getarch_2nd] Error 1
Makefile:131: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

**Comment by dpo** [comment]
Are you able to instal OpenBLAS outside of Homebrew by following the OpenBLAS instructions?

**Comment by dkouzoup** [comment]
Well, I was hoping to avoid installing openBLAS twice on my new system. Is it not possible somehow to set the target via the brew install command? Or is this not the main reason why it fails?

**Comment by dpo** [comment]
That's why it says it fails. Usually the target is auto-detected. I'm just wondering if it's not detected during the brewing, or if it's not detected at all.

**Comment by dkouzoup** [comment]
Hmm, it seems that my processor (Intel® Core™ i5-5287U, aka Broadwell) is not even in the list of supported targets (TargetList.txt in openBlas). Is there any workaround on that or do I have to wait for support? For another architecture, could I just do brew install openBlas --target=XXX or this doesn't work? Thanks for your help

**Comment by iml** [comment]
Can you use the bottle? It should be built with `ENV["DYNAMIC_ARCH"]`

**Comment by iml** [comment]
Ah, there's no 10.11 bottle.

**Comment by a7744hsc** [comment]
I can't install openblas on 2016th MacbookPro,too. @dkouzoup did you resolve this problem?

**Comment by dkouzoup** [comment]
No solution from my side yet.

**Comment by a7744hsc** [comment]
@dkouzoup maybe you can try to edit the formula by 
"brew edit homebrew/science/opebblas".
You can either switch to openblas 0.2.15 or add TARGET=HASWELL .

**Comment by dkouzoup** [comment]
Thanks! Setting the TARGET to HASWELL worked! to be more precise:

brew edit homebrew/science/openblas

and inside the file:

    ENV["TARGET"] = "HASWELL"
