### ISSUE TITLE
Cannot install wopr - MacBook Air - El Capitan 10.11.1 - Xcode 7.1

### ISSUE THREAD

**Issue by ezorzin** [Homebrew/homebrew-science#2946]
Hi, 

I am trying to install the package "wopr" (home-brew/science) on a MacBook Air, El Capitan 10.11.1 - Xcode 7.1.
Everything goes well (dependency apparently correctly installed) till the wopr installation:

==> make install
Last 15 lines from /Users/Erik/Library/Logs/Homebrew/wopr/02.make:
src/util.cc:61:5: note: candidate function
int stoi(const std::string& str ) {
    ^
src/util.cc:323:12: error: call to 'stoi' is ambiguous
  int mn = stoi( d.substr(14, 2) );
           ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:4077:37: note: candidate function
_LIBCPP_FUNC_VIS int                stoi  (const string& __str, size_t\* __idx = 0, int __base = 10);
                                    ^
src/util.cc:61:5: note: candidate function
int stoi(const std::string& str ) {
    ^
7 errors generated.
make: **\* [src/util.o] Error 1
make: **\* Waiting for unfinished jobs....

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

As far as I can understand the core of the problem might be related to the fact that ni addition to the standard C++ headers in /usr/include/c++, Apple clang is including the headers in the Xcode application tool chain:

http://stackoverflow.com/questions/24314053/stop-apple-clang-from-adding-xcode-paths-to-standard-include-paths

If this is the case, could that be fixed?

Best regards,

Erik

**Comment by bfontaine** [comment]
FWIW I tried upgrading the formula and fix the issue as described in the StackOverflow answer but it fails later in the process:

```diff
diff --git a/wopr.rb b/wopr.rb
index f64a217..b4edd8d 100644
--- a/wopr.rb
+++ b/wopr.rb
@@ -1,12 +1,16 @@
 class Wopr < Formula
+  desc "Memory-based word prediction and language modeling"
   homepage "http://ilk.uvt.nl/wopr"
-  url "http://software.ticc.uvt.nl/wopr-1.34.2.tar.gz"
-  sha256 "bc271bcdd92bf28809e0f2e7ef47b739ff69f47c6b974222741b7682250d07be"
+  url "http://software.ticc.uvt.nl/wopr-1.36.1.tar.gz"
+  sha256 "ffcf2ce85f18dcce86a45ecdd9f3066e4c1f8043b8b33bf4bc71bfe91ae32e49"
 
   depends_on "pkg-config" => :build
+  depends_on "libfolia" => :build
+  depends_on "icu4c" => :build
   depends_on "timbl"
 
   def install
+    ENV["CXXFLAGS"] = "--stdlib=libstdc++"
     system "./configure", "--disable-debug", "--disable-dependency-tracking",
                           "--prefix=#{prefix}"
     system "make", "install"
```

```
Last 15 lines from /Users/baptiste/Library/Logs/Homebrew/wopr/02.make:
  "Timbl::operator<<(std::ostream&, Timbl::Vfield const*)", referenced from:
      pplx(Logfile&, Config&) in runrunrun.o
  "folia::FoliaElement::settext(std::string const&, std::string const&)", referenced from:
      xmlserver(Logfile&, Config&) in server.o
  "folia::getArgs(std::string const&)", referenced from:
      folia::FoliaImpl::classInit(std::string const&) in server.o
  "folia::Document::declare(folia::AnnotationType::AnnotationType, std::string const&, std::string const&)", referenced from:
      xmlserver(Logfile&, Config&) in server.o
  "folia::Document::Document(std::string const&)", referenced from:
      xmlserver(Logfile&, Config&) in server.o
  "folia::operator<<(std::ostream&, folia::Document const*)", referenced from:
      xmlserver(Logfile&, Config&) in server.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wopr] Error 1
```

([full logs](https://gist.github.com/d1fdf21b1e6852bd405db5b9ce43dc11))

**Comment by ilovezfs** [comment]
This fixes it and uses current versions:
https://gist.github.com/ilovezfs/03699d8b59334520cd114f94cc27bb39

**Comment by ilovezfs** [comment]
@bfontaine so based on that, I guess libfolia-0.12.tar.gz may need to be vendored if upstream has no fix yet?

**Comment by bfontaine** [comment]
@ilovezfs It seems so 😐

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-science/pull/6162.
