### ISSUE TITLE
vips 8.1.1

### ISSUE THREAD

**Issue by mahnunchik** [Homebrew/homebrew-science#2977]
Could you please update [vips](https://github.com/Homebrew/homebrew-science/blob/master/vips.rb) to 8.1.1

http://www.vips.ecs.soton.ac.uk/supported/8.1/

**Comment by dpo** [comment]
Thanks for the suggestion. It usually speeds things up if you're able to submit a pull request.

**Comment by mahnunchik** [comment]
@dpo Could you point me to the documentation for creating/updating packages?

**Comment by dpo** [comment]
You can start reading here: https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#contributing but replace Homebrew with Homebrew-Science. In your case, all you should need (assuming the new version of `vips` builds out of the box) is fork Homebrew-Science, create a branch (say `vips-811`), edit `vips.rb` and update the `url` and `sha256`. Then push to your fork, head to Github, and send us the pull request.
