### ISSUE TITLE
Error with C++ lib installing graph-tool in OSX El Capitan

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2982]
_From @sandrofsousa on November 5, 2015 23:1_

After trying to install graph-tool with Homebrew to python3 (brewed version) I had the following warning:

```Warning: homebrew/science/graph-tool dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.```

and importing the package, the following error was shown:
```
Python 3.5.0 (default, Oct 14 2015, 14:56:38) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graph_tool as gt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/graph_tool/__init__.py", line 105, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/usr/local/lib/python3.5/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python.dylib
```

I'm trying to install this package for several times to use it at my MsC. research but it looks like almost impossible to do it. Everything is standard and installed via Brew or Pip. I'm new at programming and Homebrew usage, so please help me understanding what is happening with these C++ compilers and how to avoid this in future.

Thanks!

_Copied from original issue: Homebrew/homebrew#45736_

**Comment by count0** [comment]
Could you verify the libraries that are linked with `/usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so` (with `otool -L`)?

**Comment by sandrofsousa** [comment]
The result is:
```
| => otool -L /usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so
/usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so:
	/usr/local/opt/boost/lib/libboost_iostreams.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost-python/lib/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_coroutine-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/cgal/lib/libCGAL.11.dylib (compatibility version 11.0.0, current version 11.0.1)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

During the installation, I had the following message, not sure if tit can help:
```
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.

If you like the default optimization level of your compiler, ignore this
warning.
```

Thanks for your help.

**Comment by count0** [comment]
The boost python library `/usr/local/opt/boost-python/lib/libboost_python.dylib` is probably linked with python 2, not python 3. Can you verify if there is a file `libboost_python3.dylib` in that directory?

**Comment by sandrofsousa** [comment]
Using find a hadn't any result. This is the content of the folder:
```
| /usr/local/opt/boost-python/lib @ ***
| => ls
libboost_python-mt.a		libboost_python.a
libboost_python-mt.dylib	libboost_python.dylib
```
Should I reinstall boost for python 3 or something like that? I checked the package info and there's no option "--with-python3".

**Comment by count0** [comment]
I think there is... You should do `brew install boost-python --with-python3`.

**Comment by sandrofsousa** [comment]
I already did this, the error persist importing the lib. I will try reinstalling graph-tool with the `libboost_python3.dylib` now.

**Comment by sandrofsousa** [comment]
After removing and installing graph-tool again it worked !
So the solution is:
1 - `brew install boost-python --with-python3` before installing graph-tool (or reinstall it using `--with-python3` option.
2 - `brew Install graph-tool`

Thanks a lot @count0, couldn't make it without your help !

I'd will try to contribute and propose an update on the formula to set the `--with-python3` for boost-python when this option is used for graph-tool.

**Comment by dpo** [comment]
Can this be closed?

**Comment by sandrofsousa** [comment]
Yes @dpo please close it !
