### ISSUE TITLE
error installing octave packages under Mac OS 10.10.5

### ISSUE THREAD

**Issue by PeterNSteinmetz** [Homebrew/homebrew-science#2984]
Using octave 4.0.0 (bottled) under Mac OS 10.10.5, an attempt to install the control package produces the following error:

    ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin14.4.0/5.2.0/../../..'
    ld: library not found for -lgfortran
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

the darwin14.5.0 directories are installed instead so the -L option is incorrect. 

A temporary workaround is to create a symlink for the darwin14.4.0 version to the darwin14.5.0 version that is installed. It would be good however for the installation not to depend on hardcoded prior versions, or perhaps to have a dependency on the older version of the drawin libraries.

**Comment by dpo** [comment]
The octave bottle probably needs to be rebuilt against the latest `gcc`. In the mean time, you could `brew install octave --from-source`.

**Comment by dpo** [comment]
A new `octave` bottle was uploaded yesterday? Could you please upgrade and let us know if you are still having the same issue?

**Comment by PeterNSteinmetz** [comment]
Seems to have fixed the problem, thanks.
