### ISSUE TITLE
pcl support for HEAD failing

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2995]
There is a bug in the pcl cmake scripts which means it can't be used by other libraries when installed via homebrew. 

The following patch to pcl solves the problem:
https://github.com/PointCloudLibrary/pcl/pull/1416
The problem is outlined at:
https://github.com/PointCloudLibrary/pcl/issues/1289

It may be worth integrating the patch into the formulae (if possible) until the upstream fix is merged, but perhaps this can't be accepted to brew because it is a patch for --HEAD which already carries no guarantees?

**Comment by dpo** [comment]
Is this still relevant?

**Comment by ahundt** [comment]
@dpo It has been fixed upstream, thanks!
