### ISSUE TITLE
"ld: library not found for -lveclibfort" when brew install qrupdate

### ISSUE THREAD

**Issue by DavidKopecky** [Homebrew/homebrew-science#2996]
==> make lib solib FC=/usr/local/bin/gfortran FFLAGS= BLAS=-L/usr/local/opt/veclibfort/lib -lveclibfort LAPACK=-L/usr/local/opt/veclibfort/lib -lveclibfort
Last 15 lines from /Users/dkopecky/Library/Logs/Homebrew/qrupdate/01.make:
/usr/local/bin/gfortran  -fPIC -c dlu1up.f
/usr/local/bin/gfortran  -fPIC -c slu1up.f
/usr/local/bin/gfortran  -fPIC -c zlu1up.f
/usr/local/bin/gfortran  -fPIC -c clup1up.f
/usr/local/bin/gfortran  -fPIC -c dlup1up.f
/usr/local/bin/gfortran  -fPIC -c slup1up.f
/usr/local/bin/gfortran  -fPIC -c zlup1up.f
ar -cr ../libqrupdate.a caxcpy.o cch1dn.o cch1up.o cchdex.o cchinx.o cchshx.o cgqvec.o cqhqr.o cqr1up.o cqrdec.o cqrder.o cqrinc.o cqrinr.o cqrot.o cqrqh.o cqrshc.o cqrtv1.o dch1dn.o dch1up.o dchdex.o dchinx.o dchshx.o dgqvec.o dqhqr.o dqr1up.o dqrdec.o dqrder.o dqrinc.o dqrinr.o dqrot.o dqrqh.o dqrshc.o dqrtv1.o sch1dn.o sch1up.o schdex.o schinx.o schshx.o sgqvec.o sqhqr.o sqr1up.o sqrdec.o sqrder.o sqrinc.o sqrinr.o sqrot.o sqrqh.o sqrshc.o sqrtv1.o zaxcpy.o zch1dn.o zch1up.o zchdex.o zchinx.o zchshx.o zgqvec.o zqhqr.o zqr1up.o zqrdec.o zqrder.o zqrinc.o zqrinr.o zqrot.o zqrqh.o zqrshc.o zqrtv1.o clu1up.o dlu1up.o slu1up.o zlu1up.o clup1up.o dlup1up.o slup1up.o zlup1up.o
make -C src/ solib
/usr/local/bin/gfortran   -dynamiclib -o ../libqrupdate.dylib -install_name /usr/local/lib/libqrupdate.1.dylib caxcpy.o cch1dn.o cch1up.o cchdex.o cchinx.o cchshx.o cgqvec.o cqhqr.o cqr1up.o cqrdec.o cqrder.o cqrinc.o cqrinr.o cqrot.o cqrqh.o cqrshc.o cqrtv1.o dch1dn.o dch1up.o dchdex.o dchinx.o dchshx.o dgqvec.o dqhqr.o dqr1up.o dqrdec.o dqrder.o dqrinc.o dqrinr.o dqrot.o dqrqh.o dqrshc.o dqrtv1.o sch1dn.o sch1up.o schdex.o schinx.o schshx.o sgqvec.o sqhqr.o sqr1up.o sqrdec.o sqrder.o sqrinc.o sqrinr.o sqrot.o sqrqh.o sqrshc.o sqrtv1.o zaxcpy.o zch1dn.o zch1up.o zchdex.o zchinx.o zchshx.o zgqvec.o zqhqr.o zqr1up.o zqrdec.o zqrder.o zqrinc.o zqrinr.o zqrot.o zqrqh.o zqrshc.o zqrtv1.o clu1up.o dlu1up.o slu1up.o zlu1up.o clup1up.o dlup1up.o slup1up.o zlup1up.o \
		-L/usr/local/opt/veclibfort/lib -lveclibfort -L/usr/local/opt/veclibfort/lib -lveclibfort
ld: library not found for -lveclibfort
collect2: error: ld returned 1 exit status
make[1]: *** [../libqrupdate.dylib] Error 1
make: *** [solib] Error 2

Any ideas where it might go wrong? I already tried reinstalling gcc and all gcc dependencies. This is currently blocking me from installing Octave... 
Thanks much for any suggestions!

**Comment by dpo** [comment]
Do you use a case-sensitive OS?

**Comment by DavidKopecky** [comment]
Yes, I have a case sensitive file system on the system volume. Please don't tell me there's no workaround for that :(.

ls -l $(brew --prefix veclibfort)/lib:
-r--r--r--  1 dkopecky  admin    24K Nov  9 20:42 libvecLibFort.a
-r--r--r--  1 dkopecky  admin    25K Nov  9 20:42 libvecLibFort.dylib
-r--r--r--  1 dkopecky  admin    20K Nov  9 20:42 libvecLibFortI.dylib

**Comment by dpo** [comment]
Could you try `brew edit qrupdate` and change every occurrence of `veclibfort` to `vecLibFort` (except the line that says `depends_on`)?

**Comment by DavidKopecky** [comment]
Oh, wonderful! Thank you, this solved it.

**Comment by dpo** [comment]
Great!
