### ISSUE TITLE
Problem installing Bowtie2

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#3006]
_From @pig-raffles on November 12, 2015 11:9_

Hi,

I have a problem installing bowtie2 (or TopHat, of which bowtie2 is a dependency) on a Mac running el Capitan.

I have tried brew update and brew doctor, but it gives me no clear indication of whats wrong.

The program is part of homebrew/science

So when I brew install bowtie2 I get the following warning:

==> Installing bowtie2 from homebrew/homebrew-science
==> Downloading https://github.com/BenLangmead/bowtie2/archive/v2.2.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz
Error: SHA256 mismatch
Expected: fb4d09a96700cc929e8191659ee8509bb2f19816235322d1f012338d4a177358
Actual: 06d584040d9ce457873c59e4a5889aafe1a5f74ada207793335765d7abdf4eeb
Archive: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz
To retry an incomplete download, remove the file above.

Any idea what the problem could be?

Many thanks

Alan

_Copied from original issue: Homebrew/homebrew#45928_

**Comment by DomT4** [comment]
@pig-raffles I suspect an upstream retag, but you or the Science team will want to ask them before updating the checksum, just in case there's anything less innocent there.

There git repo is https://github.com/BenLangmead/bowtie2/issues is anyone wants to file an Issue there on the checksum change.

**Comment by tseemann** [comment]
OK, it is confirmed they were a bit naughty but it is a legitimate SHA change: https://github.com/BenLangmead/bowtie2/issues/32

**Comment by DomT4** [comment]
Thanks for checking up @tseemann. Upstream silent checksum changes are one of the harder things to deal with in package management. People *(not in this case)* tend to pressure us to just "fix" them, when obviously there's a potential threat there that has to be ruled out first :cry:.

**Comment by pig-raffles** [comment]
Thanks for sorting that!

**Comment by TJonCooper** [comment]
Issue is still persisting:

Error: SHA256 mismatch
Expected: fb4d09a96700cc929e8191659ee8509bb2f19816235322d1f012338d4a177358
Actual: 06d584040d9ce457873c59e4a5889aafe1a5f74ada207793335765d7abdf4eeb
Archive: /Library/Caches/Homebrew/bowtie2-2.2.6.tar.gz
To retry an incomplete download, remove the file above.

Has a fix been issued or are we still waiting on that?

**Comment by DomT4** [comment]
Nobody has filed a PR to fix it yet. If you wanted to, that'd be appreciated by the Science team here I'm sure.

**Comment by tseemann** [comment]
@TJonCooper I'm fixing it now, with any luck it will pass the tests.
