### ISSUE TITLE
Pastix does not build with MPICH installed

### ISSUE THREAD

**Issue by goxberry** [Homebrew/homebrew-science#3007]
The issue is that PaStiX will not build with MPICH, when it should. This issue is related to #376, which notes that `depends_on :mpi` prefers (requires?) `open-mpi` to `mpich`.

PaStiX depends on MPI; having installed `mpich` on my machine, this dependency should be satisfied. When trying to install Pastix, I see that Homebrew attempts to install `open-mpi` when it shouldn't:

```
bash-3.2$ brew install pastix
==> Installing pastix from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/pastix: open-mpi
==> Installing homebrew/science/pastix dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.

  mpich: because both install mpi__ compiler wrappers

Please `brew unlink mpich` before continuing.
```

I know that PaStiX will build with MPICH because it builds as part of a PETSc install from source with MPICH.

**Comment by dpo** [comment]
I have noticed this behavior before. I think `:mpi` needs to be revised somehow, but time is short.

**Comment by goxberry** [comment]
@dpo Agreed.

**Comment by goxberry** [comment]
Looking at https://github.com/Homebrew/homebrew/issues/41517, maybe this sort of issue should be raised with the core devs (again)?

**Comment by dpo** [comment]
@goxberry Could you please `brew update` and try again?
