### ISSUE TITLE
hdf5 - download fails

### ISSUE THREAD

**Issue by pkoppstein** [Homebrew/homebrew-science#3009]
$ date
Thu Nov 12 17:57:44 EST 2015

$ brew install hdf5
==> Installing hdf5 from homebrew/homebrew-science
==> Downloading http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.bz2

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "hdf5"
Download failed: http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.bz2

**Comment by dpo** [comment]
Should be fixed.
