### ISSUE TITLE
Make error when installing homebrew/science/mumps

### ISSUE THREAD

**Issue by t4y** [Homebrew/homebrew-science#3019]
On El Capitan, running ```brew install homebrew/science/mumps```
```
==> Installing homebrew/science/mumps
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.0.1.tar.gz
######################################################################## 100.0%
==> make alllib LIBEXT=.dylib AR= -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.0.1_1/lib/$(notdir $@) -undefined dynamic_lookup -o  RANLIB=echo OPTF=-O CDEFS=-DAdd_ ORDERINGSF=-Dpord CC= -fPIC FC= -fPIC FL= -fPIC SCALAP=-L/usr/l
Last 15 lines from /Users/<user>/Library/Logs/Homebrew/mumps/01.make:
make[2]: [sort.o] Error 1 (ignored)
fPIC -I../include -O  -c minpriority.c -o minpriority.o
make[2]: fPIC: No such file or directory
make[2]: [minpriority.o] Error 1 (ignored)
dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.0.1_1/lib/libpord.dylib -undefined dynamic_lookup -o libpord.dylib graph.o gbipart.o gbisect.o ddcreate.o ddbisect.o nestdiss.o multisector.o gelim.o bucket.o tree.o symbfac.o interface.o sort.o minpriority.o
make[2]: dynamiclib: No such file or directory
make[2]: [libpord.dylib] Error 1 (ignored)
echo libpord.dylib
libpord.dylib
if [ "./PORD/lib/" != "" ] ; then \
	  cp ./PORD/lib//libpord.dylib lib/libpord.dylib; \
	fi;
cp: ./PORD/lib//libpord.dylib: No such file or directory
make[1]: *** [lib/libpord.dylib] Error 1
make: *** [c] Error 2
```

**Comment by dpo** [comment]
Do you have gfortran? What does `brew doctor` say?

**Comment by ohinder** [comment]
I have the same problem

**Comment by ohinder** [comment]
My error is slightly different:
==> Installing mumps from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.

If you like the default optimization level of your compiler, ignore this
warning.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.

If you like the default optimization level of your compiler, ignore this
warning.
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/mumps-5.0.1.tar.gz
==> make alllib LIBEXT=.dylib AR=/usr/local/bin/gfortran -dynamiclib -Wl,-install_name -
Last 15 lines from /Users/Oliver/Library/Logs/Homebrew/mumps/01.make:
gfortran: error: gbisect.o: No such file or directory
gfortran: error: ddcreate.o: No such file or directory
gfortran: error: ddbisect.o: No such file or directory
gfortran: error: nestdiss.o: No such file or directory
gfortran: error: multisector.o: No such file or directory
gfortran: error: gelim.o: No such file or directory
gfortran: error: bucket.o: No such file or directory
gfortran: error: tree.o: No such file or directory
gfortran: error: symbfac.o: No such file or directory
gfortran: error: interface.o: No such file or directory
gfortran: error: sort.o: No such file or directory
gfortran: error: minpriority.o: No such file or directory
make[2]: *** [libpord.dylib] Error 1
make[1]: *** [lib/libpord.dylib] Error 2
make: *** [c] Error 2

**Comment by ohinder** [comment]
Here is the gist
https://gist.github.com/faceb4917aaff7212a24

**Comment by dpo** [comment]
It seems you're experiencing a known issue with the current `open-mpi` bottle. You should be able to either build with `--without-mpi`, or to build `mumps` normally after building `open-mpi` from source (with `brew install open-mpi --build-from-source`).

**Comment by ohinder** [comment]
Thanks! Following your instructions I have managed to successfully install mumps. Interestingly the MUMPS package works fine on command line, but fails in juno, am a little puzzled as to why.
