### ISSUE TITLE
Support for SDSL-lite

### ISSUE THREAD

**Issue by karel-brinda** [Homebrew/homebrew-science#3039]
Hello, would it be possible to add support for SDSL-lite (https://github.com/simongog/sdsl-lite)?

**Comment by dpo** [comment]
Though we do take requests, it's typically more efficient to submit a pull request. See our [CONTRIBUTING]() guilde.

**Comment by tseemann** [comment]
@karel-brinda I am working on a formula for this, and once I sort out #1035 it should be available.

**Comment by sjackman** [comment]
@tseemann I also need SDSL. Could you please post a WIP pull request?

**Comment by iMichka** [comment]
sdsl-lite has been added to homebrew-science since some time now. Closing here.
