### ISSUE TITLE
Fail to install opencv3 --with-python3 --with-contrib on El Capitan

### ISSUE THREAD

**Issue by starcolon** [Homebrew/homebrew-science#3051]
# System configurations

**brew**
    Homebrew 0.9.5 (git revision 9b85e; last commit 2015-11-23)

**gcc**
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin15.0.0
    Thread model: posix

**clang**
    Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin15.0.0
    Thread model: posix
**xcode command line tool**
    xcode-select version 2343
# Installation command

```
brew install opencv3 --with-python3 --with-contrib
```
# Output message with errors

==> Installing opencv3 from homebrew/homebrew-science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3-3.0.0.tar.gz
==> Downloading https://github.com/Itseez/opencv_contrib/archive/3.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3--contrib-3.0.0.tar.gz
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ip
Already downloaded: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/u
==> make
Last 15 lines from /Users/pataoengineer/Library/Logs/Homebrew/opencv3/02.make:
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
@interface NSArray<ObjectType> (NSExtendedArray)
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ 25%] Linking CXX shared library ../../lib/libopencv_shape.dylib
cd /tmp/opencv320151124-31684-t4ajdu/opencv-3.0.0/macbuild/modules/shape && /usr/local/Cellar/cmake/3.4.0/bin/cmake -E cmake_link_script CMakeFiles/opencv_shape.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++     -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden   -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 3.0.0 -current_version 3.0.0 -o ../../lib/libopencv_shape.3.0.0.dylib -install_name /tmp/opencv320151124-31684-t4ajdu/opencv-3.0.0/macbuild/lib/libopencv_shape.3.0.dylib CMakeFiles/opencv_shape.dir/src/aff_trans.cpp.o CMakeFiles/opencv_shape.dir/src/emdL1.cpp.o CMakeFiles/opencv_shape.dir/src/haus_dis.cpp.o CMakeFiles/opencv_shape.dir/src/hist_cost.cpp.o CMakeFiles/opencv_shape.dir/src/precomp.cpp.o CMakeFiles/opencv_shape.dir/src/sc_dis.cpp.o CMakeFiles/opencv_shape.dir/src/tps_trans.cpp.o ../../lib/libopencv_hal.a ../../lib/libopencv_video.3.0.0.dylib ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a ../../lib/libopencv_imgproc.3.0.0.dylib ../../lib/libopencv_core.3.0.0.dylib ../../lib/libopencv_hal.a ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a 
cd /tmp/opencv320151124-31684-t4ajdu/opencv-3.0.0/macbuild/modules/shape && /usr/local/Cellar/cmake/3.4.0/bin/cmake -E cmake_symlink_library ../../lib/libopencv_shape.3.0.0.dylib ../../lib/libopencv_shape.3.0.dylib ../../lib/libopencv_shape.dylib
[ 25%] Built target opencv_shape
20 errors generated.
make[2]: **\* [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
make[1]: **\* [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: **\* [all] Error 2

**

**Comment by tdsmith** [comment]
Please give the output of `brew gist-logs opencv3`; thanks.

**Comment by ahundt** [comment]
I can confirm this

**Comment by ahundt** [comment]
https://gist.github.com/311a5cfda8d769cd70fe9f9cdecf6c0a

**Comment by peteroid** [comment]
I have the same issue as well. Here is my gist: https://gist.github.com/peteroid/1d3c14e85cf2efb70c9cb8512eff8361

**Comment by mo3000** [comment]
i have the same issue a year later -_-

**Comment by tdsmith** [comment]
Please open a new issue with the output of `brew gist-logs opencv`. Note that the contrib libraries do not always play well with other formula options.
