### ISSUE TITLE
install openni error

### ISSUE THREAD

**Issue by herdiansah** [Homebrew/homebrew-science#3058]
Hi,

I have tried to setup sensor-kinect but failed:
brew install sensor-kinect
==> Installing sensor-kinect from totakke/homebrew-openni
==> Installing dependencies for totakke/openni/sensor-kinect: openni
==> Installing totakke/openni/sensor-kinect dependency: openni
==> Downloading https://github.com/OpenNI/OpenNI/archive/Stable-1.5.7.10.tar.gz
Already downloaded: /Library/Caches/Homebrew/openni-1.5.7.10.tar.gz
==> Downloading https://github.com/OpenNI/OpenNI/pull/92.diff
Already downloaded: /Library/Caches/Homebrew/openni--patch-f125b7bdcdcd68db682bf26c31a64a6b1d0b92dd.diff
==> Patching
patching file Samples/NiViewer/glh/glh_convenience.h
==> ./RedistMaker
Last 15 lines from /Users/Herdiansah/Library/Logs/Homebrew/openni/01.RedistMaker:
make: **\* [OpenNI] Error 2

---
-   PrimeSense OpenNI Redist    *
-     2015-11-27 16:20:59       *
  *********************************

Target: MacOSX
Version: 1.5.7.10
Num of compile jobs: 4
- Building OpenNI...
  failed to execute: make  -j4 -C /private/tmp/openni20151127-2449-5qo9gu/OpenNI-Stable-1.5.7.10/Platform/Linux/CreateRedist/../Build > /private/tmp/openni20151127-2449-5qo9gu/OpenNI-Stable-1.5.7.10/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
  Building Failed!

This is my brew config:
brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 89a3c9893e797a480dde85488d185252406346d3
Last commit: 64 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.11.1-x86_64
Xcode: 6.1
CLT: N/A
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_65, 1.8.0_60, 1.6.0_65-b14-468

**Comment by dpo** [comment]
Please post the output of `brew gist-logs openni`.

**Comment by UncleFatBacon** [comment]
Newbie here.
I am having the same issue. You can find my log here: https://gist.github.com/anonymous/da39295af15f0184fab2

Any idea how to fix this? :)

**Comment by iMichka** [comment]
> EDIT: the issue was fixed by upgrading to the last version command line tools for mac.

Closing here.
