### ISSUE TITLE
Installing openimageio on Mac OS X el capitan

### ISSUE THREAD

**Issue by allomike** [Homebrew/homebrew-science#3063]
clang: note: diagnostic msg:
    ********************

    PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
    Preprocessed source(s) and associated run script(s) are located at:
    clang: note: diagnostic msg: /var/folders/jf/7c35czj57s377sq73m6mspbw0000gn/T/imagebufalgo_pixelmath-f6cb2c.cpp
    clang: note: diagnostic msg: /var/folders/jf/7c35czj57s377sq73m6mspbw0000gn/T/imagebufalgo_pixelmath-f6cb2c.sh
    clang: note: diagnostic msg:

    ********************
    make[3]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_pixelmath.cpp.o] Error 70
    make[3]: *** Waiting for unfinished jobs....
    make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
    make[1]: *** [all] Error 2
    make: *** [cmake] Error 2

**Comment by dunn** [comment]
Can you post your `brew gist-logs openimageio`, please? Thanks!

**Comment by allomike** [comment]
Sorry for the delay!
    https://gist.github.com/74d914175ad6bf2fd416

**Comment by skycaptain** [comment]
Had the same on Yosemite. The HEAD version seams to work properly.

**Comment by tdsmith** [comment]
Ah, clang is crashing, cool

```
fatal error: error in backend: Do not know how to split this operator's operand!

clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

**Comment by jaguarondi** [comment]
I updated the formula to the latest version of OpenImageIO (1.6.9) and added the option to compile the bindings for python3, see the [pull request #3213](https://github.com/Homebrew/homebrew-science/pull/3213).

Unfortunately, the CI fails for Yosemite and Mavericks, though it succeeds for El Capitan on which I'm now so I have no way to test for the other OS versions.

Also, that's my first attempt at formula writing without knowledge of Ruby so I'm lost at this point. What's the proper way to get help for this? Should I open an issue on this tracker, or is there a forum or channel somewhere to ask?

Here's the error: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/3967/testReport/

It's a failed attempt at finding `/usr/local/lib/libhdf5.9.dylib`(see below) though `hdf5`is part of the dependencies. On El Capitan, the library is present but it's a different version: `/usr/local/lib/libhdf5.10.dylib`

Also, there's a [brew doctor](http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/3967/version=yosemite/testReport/brew-test-bot/yosemite/doctor/) dependency failure on Yosemite which does look weird and I don't know what to do there either.

Any idea what to do next?

```
Error Details
failed: brew test --verbose homebrew/science/openimageio
 Stack Trace
        Testing homebrew/science/openimageio
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160114-34917-1fpn1r6.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/openimageio.rb --verbose
==> /usr/local/Cellar/openimageio/1.6.9/bin/oiiotool --info /usr/local/Library/Homebrew/test/fixtures/test.jpg
dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /usr/local/opt/field3d/lib/libField3D.dylib
  Reason: image not found
Error: homebrew/science/openimageio: failed
Failed executing: /usr/local/Cellar/openimageio/1.6.9/bin/oiiotool --info /usr/local/Library/Homebrew/test/fixtures/test.jpg
/usr/local/Library/Homebrew/formula.rb:1472:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1409:in `open'
/usr/local/Library/Homebrew/formula.rb:1409:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/openimageio.rb:144:in `block in <class:Openimageio>'
/usr/local/Library/Homebrew/formula.rb:1318:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1314:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by tdsmith** [comment]
Going to close this issue because it doesn't look like there's anything actionable here; hopefully the new version won't be affected.
