### ISSUE TITLE
Failed to install fastml with El Capitan 

### ISSUE THREAD

**Issue by brooksph** [Homebrew/homebrew-science#3068]
I'm trying to install gubbins but it it keeps failing because fastml won't install. The report can be found in the following location https://github.com/brooksph/gubbins/blob/master/fastml_failed_install

I contacted the developers of gubbins an it was suggested that I install fastml using 

brew install https://raw.githubusercontent.com/andrewjpage/homebrew-science/master/fastml.rb

but this did not resolve the issue.

**Comment by tseemann** [comment]
Can you run `brew gist-logs fastml` and post the link here please?

**Comment by dunn** [comment]
I'm seeing the same failure with Clang: https://gist.github.com/dunn/8e70cc2939428ba1c64d

It builds for me with GCC, though.  This should be reported upstream to the developers.

**Comment by tseemann** [comment]
@andrewjpage has provided a patch https://github.com/Homebrew/homebrew-science/pull/3031 but I he needs to slightly revise it.

**Comment by brooksph** [comment]
https://gist.github.com/ad0fa25ce074a4b968c6

**Comment by brooksph** [comment]
https://gist.github.com/anonymous/3c1865aba06fdc3026d9
