### ISSUE TITLE
Make OpenCV 3 available for Python 3

### ISSUE THREAD

**Issue by nszceta** [Homebrew/homebrew-science#3072]
Currently, only Python 2 linking is described after installing OpenCV 3

I don't know where to include this help text, but here is what needs to be done to `import cv2` from the homebrew-installed system Python 3.5

```
echo /usr/local/opt/opencv3/lib/python3.5/site-packages >> /usr/local/lib/python3.5/site-packages/opencv3.pth
```

**Comment by hsiaoyi0504** [comment]
Agree

**Comment by tdsmith** [comment]
Thanks for filing; this is a duplicate of #2665.
