### ISSUE TITLE
Cufflinks won't load

### ISSUE THREAD

**Issue by chamachinga20** [Homebrew/homebrew-science#3076]
diego-macbookpro:lib Diego$ cufflinks 
dyld: Symbol not found: __ZN5boost7archive21basic_binary_iarchiveINS0_15binary_iarchiveEE13load_overrideERNS0_15class_name_typeEi
  Referenced from: /usr/local/bin/cufflinks
  Expected in: libboost_serialization-mt.dylib
 in /usr/local/bin/cufflinks
Trace/BPT trap: 5

I keep getting this error every time I try to run cufflinks. This was installed using Homebrew. Someone please help. 

Thanks!

**Comment by chamachinga20** [comment]
https://gist.github.com/5c02d76c049fc105e667

output log file for anyone that needs it

**Comment by tseemann** [comment]
You have a lot of errors and warnings in your Brew log. Can you run `brew doctor` ?

**Comment by dpo** [comment]
@tseemann https://gist.github.com/anonymous/5c02d76c049fc105e667#file-00-doctor-out

**Comment by tseemann** [comment]
@dpo Thanks - i realise now that *was* the gist file I was looking at! Whoops.

**Comment by tdsmith** [comment]
Cufflinks declares a :build dependency for a special boost, which can't be correct if it's linking to the dynamic libraries, which -l will do, by default. :/ My favorite fix here is to fix LIBS.

**Comment by tdsmith** [comment]
Actually, it builds fine against a modern boost, so... yolo?
