### ISSUE TITLE
Mercaulous cannot find boost

### ISSUE THREAD

**Issue by milicchio** [Homebrew/homebrew-science#3078]
Current homebrew version of Meraculous assembly cannot find `boost` libraries. However, they are installed and working:

	% brew list | grep boost
	boost
	% brew info boost
	boost: stable 1.59.0 (bottled), HEAD
	Collection of portable C++ source libraries
	http://www.boost.org
	/usr/local/Cellar/boost/1.58.0 (10636 files, 140M)
	  Built from source with: --without-single --without-static --with-mpi --c++11
	/usr/local/Cellar/boost/1.59.0 (10851 files, 144M) *
	  Built from source with: --without-single --without-static --with-mpi --c++11
	From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb
	==> Dependencies
	Optional: icu4c ✘
	==> Options
	--c++11
		Build using C++11 mode
	--universal
		Build a universal binary
	--with-icu4c
		Build regexp engine with icu support
	--with-mpi
		Build with MPI support
	--without-single
		Disable building single-threading variant
	--without-static
		Disable building static library variant
	--HEAD
		Install HEAD version

[Gist for Meraculous 2.0.4](https://gist.github.com/anonymous/78abe2617012ceaa37a8)

**Comment by dpo** [comment]
What's the output of `ls -l $(brew prefix boost)/libboost_thread*` and `ls -l $(brew prefix boost)/libboost_filesystem*`?

**Comment by dpo** [comment]
ps: `brew info boost` says that you built `--without-static`, but [CMake says](https://gist.github.com/anonymous/78abe2617012ceaa37a8#file-01-cmake-L75) that it's looking for static libraries.

**Comment by milicchio** [comment]
Yes, it's there boost (both libraries), and they've been built without static libraries. Shouldn't be meraculous agnostic?

**Comment by tdsmith** [comment]
Guess not. If you can get meraculous to build without the static libraries, we'll be happy to review a pull request, but your best bet for now is to rebuild boost.
