### ISSUE TITLE
cant install clustal-w on el capitan

### ISSUE THREAD

**Issue by alexstaj** [Homebrew/homebrew-science#3089]
MiniPro:~ Staj$ brew install clustal-w
==> Installing clustal-w from homebrew/homebrew-science
==> Downloading http://www.clustal.org/download/2.1/clustalw-2.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/clustal-w/2.1
==> make install
Last 15 lines from /Users/Staj/Library/Logs/Homebrew/clustal-w/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
In file included from ./general/VectorOutOfRange.cpp:9:
./general/VectorOutOfRange.h:14:38: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        VectorOutOfRange(std::string vectorName, int index, int max)
                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
2 errors generated.
make[2]: *** [VectorOutOfRange.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

**Comment by dpo** [comment]
Please post the output of `brew gist-logs clustal-w`.

**Comment by tseemann** [comment]
I can confirm same issue on my El Capitan laptop:

https://gist.github.com/4fd6386d5d426c2f57f9

**Comment by alexstaj** [comment]
https://gist.github.com/573ecef76a33abab4a31

**Comment by tdsmith** [comment]
Looks like a clustal bug; can you report this to the clustal developers?

**Comment by tdsmith** [comment]
Nevermind; I did.
