### ISSUE TITLE
Upgrade gdcm formula to use newer version

### ISSUE THREAD

**Issue by cancan101** [Homebrew/homebrew-science#3095]
[Currently the formula installs v2.4.4](https://github.com/Homebrew/homebrew-science/blob/88a5b7eeec868fc0477a7444046abf68aa25b4d8/gdcm.rb) but the [newest version is 2.6.1](http://sourceforge.net/projects/gdcm/files/gdcm%202.x/). The python SWIGing in the current version [is broken](http://sourceforge.net/p/gdcm/bugs/345/).

**Comment by dpo** [comment]
Please feel free to submit a pull request if you get a chance. None of us seems to have much free time these days. Thanks!

**Comment by dpo** [comment]
Can this be closed? You were mentioning version 2.6.1 but only upgraded to 2.4.6 in the end?!

**Comment by cancan101** [comment]
Leave open, I'll PR the 2.6.1 version. I wanted to test if first since it was more a of a version jump.

**Comment by dpo** [comment]
Thanks. Close?

**Comment by cancan101** [comment]
Sure.
