### ISSUE TITLE
superlu_dist wandering checksum

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#3107]
```
==> Verifying superlu_dist--patch-09dcd7de83ef9d2590465742df76753cb7c61bfe8e7819c02613d9bcf20ed255 checksum
Error: SHA256 mismatch
Expected: 09dcd7de83ef9d2590465742df76753cb7c61bfe8e7819c02613d9bcf20ed255
Actual: 67e2966e1a9b4e3471374d1e720946c2ef34403d00e796767b51718e4d50604f
```

Looks like the patch's checksum has wandered off. Any chance someone can check that out? :heart:

**Comment by dpo** [comment]
Thanks. It's in #3098 but the current MPI glitches are getting in the way. No free time at the moment unfortunately.

**Comment by DomT4** [comment]
Ah, thanks @dpo. Apologies for missing that.

You may be interested in https://github.com/Homebrew/homebrew/issues/46832. The new Xcode changed an internal version number, looks like `petsc` needs a revision.

**Comment by dpo** [comment]
Would love to. Unfortunately, `petsc` has been blocked for quite a while for the same reason: #2924.

**Comment by DomT4** [comment]
*Ah*. The joys of software :/
