### ISSUE TITLE
Problem installing lammps

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#3112]
_From @goytia54 on December 10, 2015 20:0_

I get his error when trying to hombrew lammps, a molecular dynamics program

```
patching file python/lammps.py
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file python/lammps.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

Any ideas what is wrong?

_Copied from original issue: Homebrew/homebrew#46884_

**Comment by DomT4** [comment]
_From @apjanke on December 10, 2015 21:34_

> READ THIS: https://git.io/brew-troubleshooting

Could you read through the troubleshooting instructions and use them to post a full bug report?

**Comment by dpo** [comment]
Patching works for me. Please post the output of `brew --config` and  `brew doctor`.

**Comment by dpo** [comment]
Please upgrade. LAMMPS was just upgraded and rebottled.
