### ISSUE TITLE
Pymol does not start: 

### ISSUE THREAD

**Issue by tritemio** [Homebrew/homebrew-science#3113]
I've installed homebrew and litteraly the first command I run was installing pymol via:

    brew install homebrew/science/pymol

After installation, pymol fails to start with the following error:

```
$ pymol
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 71, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 521, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /usr/local/lib/libGLEW.1.12.0.dylib
  Referenced from: /usr/local/Cellar/pymol/1.7.6.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: image not found
```

System OS X 10.10.4

**Comment by tritemio** [comment]
It turns out that the installed GLEW version is 1.13:

```
$ ls /usr/local/lib/libGLEW*
/usr/local/lib/libGLEW.1.13.0.dylib@   /usr/local/lib/libGLEWmx.1.13.0.dylib@
/usr/local/lib/libGLEW.1.13.dylib@     /usr/local/lib/libGLEWmx.1.13.dylib@
/usr/local/lib/libGLEW.a@              /usr/local/lib/libGLEWmx.a@
/usr/local/lib/libGLEW.dylib@          /usr/local/lib/libGLEWmx.dylib@
```

but the previous error messages shows that pymol is trying to load 1.12.

**Comment by tritemio** [comment]
@dpo, how can I try the new version? I still get the same error removing and reinstalling pymol.

**Comment by valasatava** [comment]
Similar issue on OS X 10.11.5
ImportError: dlopen(/usr/local/Cellar/pymol/1.8.2.1/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.0.0.dylib
  Referenced from: /usr/local/Cellar/pymol/1.8.2.1/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: image not found

**Comment by ilovezfs** [comment]
@valasatava You should open your own issue, but most likely you need to upgrade your local glew.
