### ISSUE TITLE
graphicsmagick to be updated on homebrew/homebrew will require dependencies to be rebuilt

### ISSUE THREAD

**Issue by carandraug** [Homebrew/homebrew-science#3123]
I have reported homebrew/homebrew#46101 about changing the default quantum-depth option of GraphicsMagick to 16 (see that for reasoning). I then made the pull request homebrew/homebrew#46248 with those changes where I was asked to ping homebrew/science since this may break several applications here that build against graphicsmagick. These are:

    homebrew/science/bioformats-cpp
    homebrew/science/dgtal
    homebrew/science/gnudatalanguage
    homebrew/science/octave
    homebrew/science/vips
    homebrew/science/vips7

That pull request has now been moved to homebrew/homebrew#47014

On a related note, I will point out that it is possible for users to change the default quantum depth. In such cases, formulas may have to figure out the options used to build  the dependencies and adapt to it. This is an existing problem, and not due to the change of default (see existing issue #2737).

**Comment by schoeps** [comment]
A similar problem occurs with openblas vs. Apple's blas.

**Comment by carandraug** [comment]
For what is worth, Homebrew/homebrew#47014 got finally accepted. It is likely that the revision numbers for the recipes mentioned should be bumped.

**Comment by dpo** [comment]
Thanks!
