### ISSUE TITLE
Octave odepkg installation fails 

### ISSUE THREAD

**Issue by sennevanbaelen** [Homebrew/homebrew-science#3127]
I installed Octave through homebrew for OS X 10.11.2. When I try to install de odepkg (odepkg-0.8.5) I get the following error: 

pkg: error running `make' for the odepkg package.
error: called from 'configure_make' in file /usr/local/Cellar/octave/4.0.0_3/share/octave/4.0.0/m/pkg/private/configure_make.

My "Command line tools" are updated and I have no problem installing other packages. 
I already tried brew install octave --build-from-source but this does't seem te work. 

Any thoughts? 

S.

**Comment by dpo** [comment]
Could you indicate the commands you issue to install odepkg. Is it possible to get verbose output?

**Comment by sennevanbaelen** [comment]
In octave I tried "pkg install -forge odepkg" and got the following output: 

*ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0/../../..'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0/../../..'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dldsolver.oct] Error 1*

*Unpacking external packages: hairer.tgz
Unpacking external packages: cash.tgz
Unpacking external packages: daskr.tgz
Applying patches from file: hairer.diff
Applying patches from file: cash.diff
(Stripping trailing CRs from patch.)
patching file cash/mebdfdae.f
(Stripping trailing CRs from patch.)
patching file cash/mebdfi.f
Applying patches from file: daskr.diff
(Stripping trailing CRs from patch.)
patching file daskr/ddaskr.f
(Stripping trailing CRs from patch.)
patching file daskr/dlinpk.f
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_mebdfdae.cc -o odepkg_octsolver_mebdfdae.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_mebdfi.cc -o odepkg_octsolver_mebdfi.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_ddaskr.cc -o odepkg_octsolver_ddaskr.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_radau.cc -o odepkg_octsolver_radau.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_radau5.cc -o odepkg_octsolver_radau5.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_rodas.cc -o odepkg_octsolver_rodas.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_octsolver_seulex.cc -o odepkg_octsolver_seulex.o
/usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c odepkg_auxiliary_functions.cc -o odepkg_auxiliary_functions.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c cash/mebdfdae.f -o cash/mebdfdae.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c cash/mebdfi.f -o cash/mebdfi.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c daskr/ddaskr.f -o daskr/ddaskr.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c daskr/dlinpk.f -o daskr/dlinpk.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c hairer/decsol.f -o hairer/decsol.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c hairer/dc_decsol.f -o hairer/dc_decsol.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c hairer/radau.f -o hairer/radau.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c hairer/radau5.f -o hairer/radau5.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c hairer/rodas.f -o hairer/rodas.o
FFLAGS="-ff2c -O" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0 -c hairer/seulex.f -o hairer/seulex.o
LFLAGS="-L/usr/local/Cellar/octave/4.0.0_3/lib/octave/4.0.0 -L/usr/local/Cellar/octave/4.0.0_3/lib -lblas -llapack -L/usr/local/opt/readline/lib -L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0 -L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0/../../.. -lreadline -lgfortran -lquadmath -lm" /usr/local/Cellar/octave/4.0.0_3/bin/mkoctfile-4.0.0  odepkg_octsolver_mebdfdae.o  odepkg_octsolver_mebdfi.o  odepkg_octsolver_ddaskr.o  odepkg_octsolver_radau.o  odepkg_octsolver_radau5.o  odepkg_octsolver_rodas.o  odepkg_octsolver_seulex.o  odepkg_auxiliary_functions.o  cash/mebdfdae.o  cash/mebdfi.o  daskr/ddaskr.o  daskr/dlinpk.o  hairer/decsol.o  hairer/dc_decsol.o  hairer/radau.o  hairer/radau5.o  hairer/rodas.o  hairer/seulex.o -o dldsolver.oct \
        -lblas -llapack -L/usr/local/opt/readline/lib -L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0 -L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.2.0/../../.. -lreadline -lgfortran -lquadmath -lm*
pkg: error running `make' for the odepkg package.
error: called from 'configure_make' in file /usr/local/Cellar/octave/4.0.0_3/share/octave/4.0.0/m/pkg/private/configure_make.m*

 (I also tried downloading the .tar and do "pkg install odepkg-0.8.5.tar.gz")

**Comment by dpo** [comment]
`octave` needs to be rebottled because it currently references the previous version of `gcc`. You can either wait for `3129` or `brew install octave --build-from-source`.
