### ISSUE TITLE
Failed to run lampps on EI Capitian

### ISSUE THREAD

**Issue by Daniel199111** [Homebrew/homebrew-science#3132]
The process or installation seems to no problem. But when I test it use 
cd /usr/local/share/lammps/bench
  lammps -in in.lj
  # with mpi
  mpiexec -n 2 lammps -in in.lj
It doesn't work and print the below prompting.
dyld: Library not loaded: /usr/local/lib/libmpi.1.dylib
  Referenced from: /usr/local/bin/lammps
  Reason: image not found
Could someone tell me how to solve this problem? Thank you .

**Comment by dpo** [comment]
We just updated the MPI formulas. Could you please run
```
brew update
brew uninstall $(brew deps lammps)
brew install lammps
```
and let me know if that works?

**Comment by Daniel199111** [comment]
Thank you!
After I run the serial commands you have post. The lammps code works well now. But I still have a little confuse about when I run the code, the notice shown in the attached picture will be prompted. Could you tell me how to chose it. Thank you.
<img width="465" alt="screen shot 2015-12-21 at 4 27 21 pm" src="https://cloud.githubusercontent.com/assets/16364423/11941827/4a4f4794-a800-11e5-958e-0e3f44d96c6c.png">

**Comment by dpo** [comment]
That's your firewall wondering about MPI connections. It's safe to allow the connection.
