### ISSUE TITLE
Pymol does not start

### ISSUE THREAD

**Issue by tritemio** [Homebrew/homebrew-science#3134]
I reported an issue on pymol not starting  (#3113) which has been closed after a new build has been release.

With the new version still get an error trying to start pymol:

```
 $ pymol
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 71, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 521, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /opt/X11/lib/libpng15.15.dylib
  Referenced from: /usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: Incompatible library version: _cmd.so requires version 39.0.0 or later, but libpng15.15.dylib provides version 34.0.0
```

This time the problem seems to be with the library `libpng15`.

**Comment by dpo** [comment]
Sorry about that. I missed your message in the other thread. Could you try `brew uninstall $(brew deps pymol)` followed by `brew install pymol`, and let me know if you're still having the same problem?

**Comment by tritemio** [comment]
The the list returned by

```
brew deps pymol
```

has some packages which are not installed (e.g. berkeley-db4, icu4c), so `brew uninstall $(brew deps pymol)` fails. Maybe these are optional dependencies. 

Anyway, I manually uninstalled all the dependencies I had + pymol itself, then installed pymol again. Still getting the same error message about libpng15.

Can you reproduce this issue?

**Comment by dpo** [comment]
I can't reproduce the problem. I just installed `pymol`, ran `brew test pymol`, and ran PyMOL from the command line. The GUI pops up and all seems fine.

The `libpng15.15` is in reference to X11. Did you install XQuartz? Perhaps you need to reinstall it. If that doesn't work, please post the output of `brew --config` and `brew doctor`.

**Comment by dpo** [comment]
Your issue seems related to #3110.

**Comment by tritemio** [comment]
@dpo, yes I had installed XQuartz some time ago (before brew). I now updated XQuartz to the latest version and pymol started working.

For the record I'm using OS X 10.10.5 (Yosemite) and XQuartz 2.7.8 (xorg-server 1.16.4). Hopefully, I will not encounter the instabilities reported in #3110.

Thanks for the help!
