### ISSUE TITLE
iGraph wants to use libglpk.35 instead of installed libglpk.36 (mavericks build)

### ISSUE THREAD

**Issue by chrisjcameron** [Homebrew/homebrew-science#3146]
After updating homebrew recently, I am not longer able to import iGraph in a Python session.

    >>> import igraph
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/igraph/__init__.py", line 34, in <module>
        from igraph._igraph import *
    ImportError: dlopen(/usr/local/lib/python2.7/site-packages/igraph/_igraph.so, 2):
         Library not loaded: /usr/local/lib/libglpk.35.dylib
      Referenced from: /usr/local/lib/libigraph.0.dylib
      Reason: image not found

I do have a `/usr/local/lib/libglpk.36.dylib`. I did `brew update && brew upgrade` and reinstalled gmp, glpk and igraph and the issue persists. I am not sure if this is a formula issue or something that should be directed at iGraph team.

**Comment by dpo** [comment]
Should be resolved.

**Comment by chrisjcameron** [comment]
Thanks for your quick resolution!
