### ISSUE TITLE
opencv3 (3.1) failing to build

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#3147]
There seems to be a failure in the OpenCL and OpenGL components of the build, as recorded by these [gist logs](https://gist.github.com/ab3db9cd2cd23ea28a05). 

I'm building with the following command:
```
○ brew install opencv3 --with-contrib --with-cuda --with-opengl --with-libdc1394 --with-tbb --with-openni2 --with-qt5 --c++11
==> Installing opencv3 from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3-3.1.0.tar.gz
==> Downloading https://github.com/Itseez/opencv_contrib/archive/3.1.0.tar.gz
==> Downloading from https://codeload.github.com/Itseez/opencv_contrib/tar.gz/3.1.0
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_mac
Already downloaded: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local
==> make
Last 15 lines from /Users/athundt/Library/Logs/Homebrew/opencv3/02.make:
/tmp/opencv320151225-42107-1mfusgp/opencv-3.1.0/modules/core/src/opengl.cpp:1646:14: error: use of undeclared identifier 'clGetGLContextInfoKHR'; did you mean 'clGetContextInfo'?
        if (!clGetGLContextInfoKHR)
             ^~~~~~~~~~~~~~~~~~~~~
             clGetContextInfo
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:633:1: note: 'clGetContextInfo' declared here
clGetContextInfo(cl_context         /* context */,
^
/tmp/opencv320151225-42107-1mfusgp/opencv-3.1.0/modules/core/src/opengl.cpp:1669:52: error: use of undeclared identifier 'CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR'
        status = clGetGLContextInfoKHR(properties, CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR, sizeof(cl_device_id), (void*)&device, NULL);
                                                   ^
6 errors generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/science/issues
```

**Comment by ahundt** [comment]
I've been able to compile by cloning the repositories and using cmake manually, so I'm fairly certain this is an issue with homebrew.

**Comment by Boazrciasn** [comment]
I am having the same issue. Hope it will be solved soon.

**Comment by dpo** [comment]
Does it build with `--env=std`?

**Comment by Boazrciasn** [comment]
Unfortunately not for me, actually what it comes up with is this, 

CMake Error at 3rdparty/ippicv/downloader.cmake:77 (message):
  ICV: Failed to download ICV package: ippicv_macosx_20151201.tgz.
  Status=28;"Timeout was reached"
Call Stack (most recent call first):
  3rdparty/ippicv/downloader.cmake:110 (_icv_downloader)
  cmake/OpenCVFindIPP.cmake:237 (include)
  cmake/OpenCVFindLibsPerf.cmake:12 (include)
  CMakeLists.txt:537 (include)

**Comment by ahundt** [comment]
@dpo what does `--env=std` do? need to confirm it will work with my system

**Comment by Boazrciasn** [comment]
gist-log for me when I try --env=std , nothing changes. though ,

https://gist.github.com/33082d6a026223942adc

**Comment by krishnakumar-kapil** [comment]
Having the same issue as well, where the ippicv_macosx_20151201.tgz...
fails to download at all..

**Comment by phirestalker** [comment]
I am also unable to compile when using --with-opengl. I however get different output if I remove --with-cuda

here is the make log for brew install opencv3 --with-qt5 --with-ffmpeg --with-contrib --with-opengl --with-opencl

[02.make.txt](https://github.com/Homebrew/homebrew-science/files/85251/02.make.txt)

**Comment by phirestalker** [comment]
ahundt, you mentioned you could get it to work manually. Have you compared what you did with the commands run by homebrew? Maybe that will help find this problem.

Or could you post what you did manually, so I can do some testing as well?

**Comment by Boazrciasn** [comment]
I have installed 3.0 instead of 3.1 since it was urgent for me. I exactly did the same steps as given here : 
http://www.pyimagesearch.com/2015/06/15/install-opencv-3-0-and-python-2-7-on-osx/

hope it helps.

**Comment by JohnTian** [comment]
@ahundt I am having the same issue. without brew. 
```cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D PYTHON2_PACKAGES_PATH=~/.virtualenvs/cv/lib/python2.7/site-packages -D PYTHON2_LIBRARY=/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin -D PYTHON2_INCLUDE_DIR=/usr/local/Frameworks/Python.framework/Headers -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D OPENCV_EXTRA_MODULES_PATH=~/bin/opencv/opencv_contrib-3.1.0/modules -D WITH_TBB=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_V4L=ON ..```

**Comment by ahundt** [comment]
Well it seems this is an upstream issue... This may have to wait for a patch is available there.

**Comment by ahundt** [comment]
There is an upstream patch now, though I'm not sure how long it will be until it is actually in a release. Should we include it directly in the .rb? 

https://github.com/Itseez/opencv/pull/6060

**Comment by heinemml** [comment]
I think this is fixed by 417bd3f

**Comment by dpo** [comment]
@ahundt confirm?

**Comment by ahundt** [comment]
@dpo works great! Thanks!

**Comment by dpo** [comment]
Thanks
