### ISSUE TITLE
vtk5 shouldn't link directly to python

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-science#3150]
Per https://github.com/Homebrew/homebrew-science/pull/3145#issuecomment-167444931, an importable vtk5 module links directly to a Python framework, [which is bad](http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/); we should remove that linkage if we can.

I've self-assigned to indicate that I intend to follow through with this but anyone should feel free to lend a hand.

**Comment by iMichka** [comment]
VTK5 is gone since #3616. Nobody complained about this, at least not to my knowledge. The python linking problem has been fixed here #3811, for VTK 7.1.0.

There is nothing more to be done here; closing.
