### ISSUE TITLE
opencv 3 (3.1.0) with java doesn't produce dylib

### ISSUE THREAD

**Issue by binarious** [Homebrew/homebrew-science#3153]
I don't know if the error has to be reported here or in the opencv repo:
Installing OpenCV 3.0.0 with `--with-java` placed a `libopencv_java300.dylib` inside `/usr/local/Cellar/opencv3/3.0.0/share/OpenCV/java`.
Since 3.1.0 this file is called `libopencv_java310.so`. The java apps using OpenCV stopped working.

**Comment by shredmaster** [comment]
I resolved this problem by simply rename file extension to dylib. but man, this issue took forever to figure out because I'm completely new to JNI.

**Comment by josehenriqueventura** [comment]
I had the same problem. Renaming the libopencv_java310.so to libopencv_java310.dylib resolved the problem. Thanks.

**Comment by dpo** [comment]
It's not clear that this can be resolved in the Homebrew formula. Have you reported the issue upstream?

**Comment by binarious** [comment]
Renaming works as a workaround for me, too. I opened an issue: https://github.com/Itseez/opencv/issues/5941

**Comment by binarious** [comment]
Issue has been resolved upstream.
