### ISSUE TITLE
Dealii: Compile error

### ISSUE THREAD

**Issue by ashkan2200** [Homebrew/homebrew-science#3158]
Hi,
When upgrading dealii I get this error 

    make[2]: *** No rule to make target `/usr/local/opt/openblas/lib/libopenblas.dyld', needed by `li    b/libdeal_II.8.3.0.dylib'.  Stop.
    633 make[2]: *** Waiting for unfinished jobs....
    634 make[1]: *** [source/CMakeFiles/deal_II.dir/all] Error 2
    635 make[1]: *** Waiting for unfinished jobs....

The linker doesn't look in the correct place for openblas. I looked around in the formula and I don't see where it is telling the linker to look for openblas.

**Comment by dpo** [comment]
You're building from source. There's a typo on line 62 of `dealii.rb`: `dyld` should be `dylib`.
