### ISSUE TITLE
OpenCV - The source directory "/tmp/opencv20151229-62159-gcc7d1/opencv-2.4.11/macbuild/changes" does not exist.

### ISSUE THREAD

**Issue by tsugua** [Homebrew/homebrew-science#3160]
I'm trying to install OpenCV on OSX 10.11.2 using homebrew and here is the error I'm getting:

==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
Last 15 lines from /Users/user/Library/Logs/Homebrew/opencv/01.cmake:
-DWITH_OPENGL=OFF
-DWITH_JASPER=OFF
-DWITH_QT=OFF
-DWITH_GSTREAMER=OFF
-DPYTHON_LIBRARY=/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
-DPYTHON_INCLUDE_DIR=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
-DCMAKE_PREFIX_PATH=/System/Library/Frameworks/Python.framework/Versions/2.7
-DWITH_CUDA=OFF
-DENABLE_SSSE3=ON
-DENABLE_SSE41=ON
-DENABLE_SSE42=ON
-DENABLE_AVX=ON

CMake Error: The source directory "/tmp/opencv20151229-62159-gcc7d1/opencv-2.4.11/macbuild/changes" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by dpo** [comment]
`opencv` was updated on Jan 8th. Are you still having the same problem? If so, please post the output of `brew gist-logs opencv`. Thanks.

**Comment by tsugua** [comment]
I am no longer having this issue. Thanks for the fix!
