### ISSUE TITLE
insighttoolkit bottle has stale HDF5 dependency

### ISSUE THREAD

**Issue by lantiga** [Homebrew/homebrew-science#3164]
The insighttoolkit bottle for El Capitan links to /usr/local/opt/hdf5/lib/libhdf5_cpp.10.dylib, but hdf5 now provides /usr/local/opt/hdf5/lib/libhdf5_cpp.11.dylib, resulting in the following error message when trying to dlopen:

```
loaded: /usr/local/opt/hdf5/lib/libhdf5_cpp.10.dylib
  Referenced from: /usr/local/opt/insighttoolkit/lib/libITKIOHDF5-4.8.1.dylib
  Reason: image not found
```

**Comment by yan12125** [comment]
I've encountered some problems in building ITK, too. (#3162) I guess we should have a rebuild list. For example, if HDF5 is upgraded, we should rebuild ITK. If Python is upgraded, we should rebuild applications using Python C API such as VTK, and so on.

**Comment by lantiga** [comment]
@dpo the fix works for me, although it hasn't landed in homebrew-science yet.

@yan12125 a rebuild list sounds very useful, all the info are already in the formula.

**Comment by lantiga** [comment]
Awesome, thanks!
