### ISSUE TITLE
netcdf.mod missing

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#3168]
_From @ryofurue on January 1, 2016 10:53_

netcdf.mod seems to be missing from the netcdf package.  (Is the whole Fortran interface missing? or is it just netcdf.mod ?  Under homebrew, I guess it makes sense to include interfaces for gfortran, both F77 and F90.)

Thank you

_Copied from original issue: Homebrew/homebrew#47582_

**Comment by DomT4** [comment]
_From @dunn on January 1, 2016 17:5_

We'd love a pull request, if you're up for fixing this!  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by DomT4** [comment]
CC @ryofurue - Moved here because it's a Science formula rather than a core one.

Please check you're building `brew install netcdf --with-fortran` and see if the issue persists.

**Comment by ryofurue** [comment]
Thank you for your response.

> Moved here because it's a Science formula rather than a core one.

Thank you!  How is homebrew issue reporting subdivided?

> Please check you're building `brew install netcdf --with-fortran` and see if the issue persists.

Oops, of course!  How stupid of me!  I've confirmed that `--with-fortran` works.  (I wasn't able to find any comments on this issue by searching Google, which made me off the track.  Perhaps very few people use the Fortran-netCDF/Homebrew combination or those who do use it are all clever enough to look for the option. . . .

**Comment by DomT4** [comment]
> Thank you! How is homebrew issue reporting subdivided?

Essentially whichever tap maintains the formula handles the Issues/PRs for it. If you run `brew info` on a formula it should tell you where it lives in terms of core/tap.

> I've confirmed that --with-fortran works.

Great! No worries. All the options are listed in `brew info` as well if you want to poke around anything in future and you can `brew cat` a formula name to dump it on the terminal for quick inspection. Let us know if we can help further at all :smiley:.
