### ISSUE TITLE
I wanna use pyROOT with python3. 

### ISSUE THREAD

**Issue by david-july1991** [Homebrew/homebrew-science#3172]
I wanna use pyROOT with python3. How should I do to use it. Is these anyone has a good solution?

**Comment by WortPixel** [comment]
I'm assuming standard brew location as well as root & python versions as of now. Maybe this helps.
`brew install cmake`
`brew install python3`
`cd /usr/local`
`curl https://root.cern.ch/download/root_v6.06.08.source.tar.gz | tar xz `
`mkdir root6`
`cd root6`
`cmake ../root-6.06.08 -DPYTHON_EXECUTABLE=/us/local/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Version/3.5/Headers -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Version/3.5/lib/libpython3.5.dylib`
`make`
Now add 
`cd /usr/local/root06.06.08`
`source bin/thisroot.sh`
`cd $HOME`
to your `.bash_profile` and source it or restart your terminal.

In case you're still having problems with certain root libraries you might need to change
`if ( ! pyfunc )
return kFALSE;`
to
`if ( ! pyfunc ) {
PyErr_Clear();
return kFALSE;
}`
in line `222` within `/usr/local/root-6.06.08/bindings/pyroot/src/Utility.cxx` before compiling root.

**Comment by dpo** [comment]
Thanks for the tip. It would be immensely cleaner to modify the `root` formula to build correctly against Python3. It would be great if you could submit a pull request in that direction.

**Comment by samcunliffe** [comment]
+1 to this. 
Can we have homebrew use python3 either by default or by a simple option.
I hate building root from source. It's got to be one of my least favourite things to do.

**Comment by dpo** [comment]
Python3 cannot be the default because Homebrew's policy is to use System Python, but there should be a `--with-python3` option when building `root` (it will be a source build.)

**Comment by samcunliffe** [comment]
Ah right! I take it back, system python makes much more sense. I agree that a `--with-python3` option would be best.


For the benefit of others finding this thread, my version(?) of python3 from Homebrew has a `3.5.2_1` so the paths are different (updated?) from @WortPixel 's recipe above. I think all that is required is to replace the seventh line of the above with:

`
cmake ../root-6.06.08 -DPYTHON_EXECUTABLE=/usr/local/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Headers -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5.dylib -Droofit=ON -Dtmva=ON
`

n.b. I also have `-Droofit=ON -Dtmva=ON` to enable [RooFit](https://root.cern.ch/roofit) and [TMVA](https://root.cern.ch/tmva).

**Comment by dpo** [comment]
I really don't encourage users to employ the "fix" above as that actively interferes with the HOMEBREW_PREFIX. What I meant is to modify the formula.

**Comment by samcunliffe** [comment]
I don't have the ruby skills to do that.

**Comment by david-july1991** [comment]
I've added few lines following @samcunliffe 's advice! Please check out #5204 !

**Comment by iMichka** [comment]
#5204 has been merged. Closing here.
