### ISSUE TITLE
Travis issues

### ISSUE THREAD

**Issue by dpo** [Homebrew/homebrew-science#3191]
I regularly encounter false negatives on Travis but typically forget to make a gist and document them. I'll add them here as I encounter them to remember and so we can improve the docker instances.

@sjackman @Homebrew/maintainers 

1. `brew tests` fails. Example: https://gist.github.com/aa4961daec309f366c88
2. Builds often take a bit longer on 10.10 for some reason, resulting in occasional timeouts (while 10.9 and 10.11 complete normally)
3. `Xcode and/or the CLT appear to be misconfigured` on 10.9. Example: https://travis-ci.org/Homebrew/homebrew-science/jobs/101942766#L2372

**Comment by UniqMartin** [comment]
> `brew tests` fails. Example: https://gist.github.com/aa4961daec309f366c88

Does this instance have issues using the GitHub API? Is there anything special about it? The failing test relies on the GitHub API being available to give the expected result.

**Comment by mikemcquaid** [comment]
@dpo Please don't ping all Homebrew maintainers for science issues, thanks.

**Comment by sjackman** [comment]
We have a bit of a way to go with `brew tests`, but I'd like to get it working.
```
brew tests
..........................................................................................................................E..................................F....F..F..F....F....................................................................FFFFFFFFFFF..................................................FE.....................SS..EEE....E..........E.E.............E........................................F..........................................F.........E....EE.......................................................................................................................F.......F.................................................................................E......E..........
```

**Comment by sjackman** [comment]
How do I run a single test by name? e.g. to test `test_utils.rb UtilTests#test_popen_write_with_block`, which fails.

**Comment by bfontaine** [comment]
Run `brew tests TEST=test_utils.rb`. I don’t know how to run only one test.

**Comment by dpo** [comment]
@mikemcquaid I don't think the issue is science specific. Rather related to the docker instances themselves. It seems the same should happen in other taps.

**Comment by mikemcquaid** [comment]
> @mikemcquaid I don't think the issue is science specific. Rather related to the docker instances themselves. It seems the same should happen in other taps.

_should_ is the key word here. Unless you can reproduce this in core: my previous comment stands, thanks.

**Comment by dpo** [comment]
@mikemcquaid Correct me if I'm wrong, but `brew tests` also sometimes fails in core when running on Travis while the brew bot doesn't complain. For example: https://travis-ci.org/Homebrew/homebrew/jobs/101229534#L277.

**Comment by mikemcquaid** [comment]
@dpo I'm not sure what you mean by "the brew bot doesn't complain"; that job failed due to those tests and that was a legimate issue that was fixed.

**Comment by UniqMartin** [comment]
I imagine in this context “the brew bot” refers to our Jenkins installation at <http://bot.brew.sh>. So the same job/test might have succeeded on Jenkins but failed on Travis.

**Comment by dpo** [comment]
@mikemcquaid As @UniqMartin says, by "brew bot", I meant Jenkins. So indeed, jobs may succeed on one, but not on the other.

**Comment by mikemcquaid** [comment]
@dpo Yep; they don't run at identical times and have different constraints so that's (somewhat) expected.

**Comment by dpo** [comment]
I'm not sure how the fact that they run at different times explains it. `brew tests` hardly ever seems to fail on Jenkins. It does feel like something's up with the Travis setup, but I'm not sure what.

**Comment by mikemcquaid** [comment]
@dpo Ok. If you can debug it and submit a PR, that'd be welcome. I'm sure you've debugged enough science issues to know that the current reproduction instructions are lacking here :wink:
