### ISSUE TITLE
opencv3 is missing caveat message about python3

### ISSUE THREAD

**Issue by LinusU** [Homebrew/homebrew-science#3192]
When installing `opencv3`, it presents the following very helpful message:

```
If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
```

However, when building with `--with-python3` I would love for it to print this message as well:

```
If you need Python 3.x to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python3.5/site-packages >> /usr/local/lib/python3.5/site-packages/opencv3.pth
```

**Comment by dpo** [comment]
It seems to be Homebrew itself, and not the `opencv3` formula that outputs this message. Please open an issue over at [Homebrew core](https://github.com/Homebrew/homebrew/issues).

**Comment by dpo** [comment]
See https://github.com/Homebrew/homebrew/blob/29c40fa3d94929b0d62986a1ed0fbdae97228512/Library/Homebrew/caveats.rb#L102.
