### ISSUE TITLE
Build error when installing PETSc on Mac OSX El Capitan

### ISSUE THREAD

**Issue by joshburkart** [Homebrew/homebrew-science#3214]
I tried:
```
brew install petsc
```
and everything went fine until it wanted to install `netcdf`, whereupon I received this error:
```
ld: file not found: /usr/local/lib/libmpi.1.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
[Here's](https://gist.github.com/joshburkart/2cfee0037f593b6d362c) a full gist.

I have `open-mpi` installed, and `brew install netcdf` works fine. Any help would be appreciated!

**Comment by dpo** [comment]
Hm. It works for me on 10.9. You might have an old `open-mpi`. Just to be sure, please try `brew uninstall $(brew deps petsc); brew install petsc`.

If that doesn't work, please post the output of `brew gist-logs netcdf`.

**Comment by joshburkart** [comment]
Worked! Thanks a bunch!
