### ISSUE TITLE
openimageio 1.5.14 hdf5 dependency broken. OS X 10.10.5

### ISSUE THREAD

**Issue by nicelifeBS** [Homebrew/homebrew-science#3224]
I have the similar issue like [#2754] (https://github.com/Homebrew/homebrew-science/issues/2754) with openimagiio. I tried brew reinstall --build-from-source openimageio but the build fails:

[long error text elided - @tdsmith]

Any ideas how to fix this?

**Comment by tdsmith** [comment]
If you're having trouble building openimageio, please paste the output of `brew gist-logs openimageio`, which will share your complete build logs; the section you posted wasn't very informative.

The issue that you're running into that led you to try this may have been fixed; what was it, exactly?

**Comment by nicelifeBS** [comment]
My issue is the image not found error because there is no hdf5.9 library
$ oiiotool
dyld: Library not loaded: /usr/local/lib/libhdf5.9.dylib
  Referenced from: /usr/local/bin/oiiotool
  Reason: image not found
Trace/BPT trap: 5

Sorry for the not helpful log message. Here the gist: https://gist.github.com/anonymous/354d03d741d897bb7c81

I did a brew update and upgrade before.

**Comment by nicelifeBS** [comment]
I fixed the formula locally to point at the 1.6.9 version of oiio. That worked for me.

**Comment by devernay** [comment]
openimageio has to be updated anyway, because 1.5.14 doesn't compile with the latest libraw.
Either point to the latest 1.5 version (1.5.23) or to the current release (1.6.9).
Note that the pre-built binaries are broken too, because boost was updated to 1.60.

**Comment by devernay** [comment]
Note that openimageio.rb should also diable building Nuke plugins, even if Nuke is found (it fails with the latest clang):
```
    ENV.append "MY_CMAKE_FLAGS", "-DUSE_NUKE=OFF"
```

**Comment by dpo** [comment]
Should get fixed when #3213 is merged.

**Comment by tdsmith** [comment]
Bottles were re-built; please open an issue if this is not resolved.
