### ISSUE TITLE
ea-utils can not be compiled

### ISSUE THREAD

**Issue by JeremiasBrand** [Homebrew/homebrew-science#3226]
I have tried to install ea-utils using brew but the process fails.:

brew install ea-utils                                                   │    /usr/local/lib/libvalid.a
==> Installing ea-utils from homebrew/science                                                         │    /usr/local/lib/libvariation.a
==> Installing dependencies for homebrew/science/ea-utils: gsl                                        │    /usr/local/lib/libwritedb.a
==> Installing homebrew/science/ea-utils dependency: gsl                                              │    /usr/local/lib/libxalgoblastdbindex.a
==> Downloading http://ftpmirror.gnu.org/gsl/gsl-1.16.tar.gz                                          │    /usr/local/lib/libxalgodustmask.a
==> Downloading from http://mirror.switch.ch/ftp/mirror/gnu/gsl/gsl-1.16.tar.gz                       │    /usr/local/lib/libxalgosegmask.a
###### ################################################################## 100.0%                       │    /usr/local/lib/libxalgowinmask.a

==> ./configure --prefix=/home/USER/.linuxbrew/Cellar/gsl/1.16                                    │    /usr/local/lib/libxalnmgr.a
==> make                                                                                              │    /usr/local/lib/libxblast.a
==> make install                                                                                      │    /usr/local/lib/libxblastformat.a
/home/USER/.linuxbrew/Cellar/gsl/1.16: 245 files, 9M, built in 44 seconds                         │    /usr/local/lib/libxcgi.a
==> Installing homebrew/science/ea-utils                                                              │    /usr/local/lib/libxcleanup.a
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU           │    /usr/local/lib/libxcompress.a
==> Downloading from https://doc-04-5g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksu│    /usr/local/lib/libxconnect.a
###### ################################################################## 100.0%                       │    /usr/local/lib/libxconnserv.a

==> Patching                                                                                          │    /usr/local/lib/libxcser.a
patching file sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h                              │    /usr/local/lib/libxfcgi.a
patching file sparsehash-2.0.2/src/hashtable_test.cc                                                  │    /usr/local/lib/libxformat.a
==> make install PREFIX=/home/USER/.linuxbrew/Cellar/ea-utils/1.1.2-806                           │    /usr/local/lib/libxhtml.a
Last 15 lines from /home/USER/.cache/Homebrew/Logs/ea-utils/01.make:                              │    /usr/local/lib/libxncbi.a
sam-stats.cpp:37:81: fatal error: sparsehash/sparse_hash_map: No such file or directory               │    /usr/local/lib/libxnetblast.a
 #include <sparsehash/sparse_hash_map> // or sparse_hash_set, dense_hash_map, ...                     │    /usr/local/lib/libxnetblastcli.a
                                                                                 ^                    │    /usr/local/lib/libxobjedit.a
compilation terminated.                                                                               │    /usr/local/lib/libxobjmgr.a
make: **\* [sam-stats] Error 1                                                                         │    /usr/local/lib/libxobjread.a
varcall.cpp:33:29: fatal error: gsl/gsl_randist.h: No such file or directory                          │    /usr/local/lib/libxobjreadex.a
 #include <gsl/gsl_randist.h>                                                                         │    /usr/local/lib/libxobjsimple.a
                             ^                                                                        │    /usr/local/lib/libxobjutil.a
compilation terminated.                                                                               │    /usr/local/lib/libxregexp.a
fastq-stats.cpp:78:81: fatal error: sparsehash/sparse_hash_map: No such file or directory             │    /usr/local/lib/libxregexp_template_tester.a
 #include <sparsehash/sparse_hash_map> // or sparse_hash_set, dense_hash_map, ...                     │    /usr/local/lib/libxser.a
                                                                                 ^                    │    /usr/local/lib/libxthrserv.a
compilation terminated.                                                                               │    /usr/local/lib/libxutil.a
make: **\* [varcall] Error 1                                                                           │    /usr/local/lib/libxxconnect.a
make: **\* [fastq-stats] Error 1     

How can I resolve this issue?

**Comment by tseemann** [comment]
I confirm the same error:

Here are the logs:  https://gist.github.com/bfb347a25d93404a7eda

**Comment by jwhite007** [comment]
I'm having issues as well. Here are my logs... https://gist.github.com/jwhite007/35639f1229f8c990e4db

**Comment by chrisgulvik** [comment]
I agree with Torsten. It makes sense to simply add the google-sparsehash formula as a dependency:
`depends_on "google-sparsehash"`

Also, the sam header file is required for compiling sam-stats, so something like this `-I~/.linuxbrew/Cellar/htslib/1.3.1/include/htslib` needs to be added when configuring... I think this would be sufficient for that purpose:
`depends_on "htslib" => :build`

**Comment by ilovezfs** [comment]
please try again now that https://github.com/Homebrew/homebrew-science/pull/4185 has shipped.

**Comment by tseemann** [comment]
Still broken:

```
==> Installing ea-utils from homebrew/science
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU
Already downloaded: /home/linuxbrew/.cache/Homebrew/ea-utils-1.1.2-806
==> Patching
patching file sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
patching file sparsehash-2.0.2/src/hashtable_test.cc
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/ea-utils/1.1.2-806_1
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/ea-utils/01.make:
make[2]: Leaving directory `/tmp/ea-utils-20160901-52962-qqe6if/ea-utils.1.1.2-806/sparsehash-2.0.2'
make[1]: Leaving directory `/tmp/ea-utils-20160901-52962-qqe6if/ea-utils.1.1.2-806/sparsehash-2.0.2'
mkdir sparsehash
cp -r sparsehash-2.0.2/src/sparsehash/* sparsehash/
g++ -Os -w -pipe -march=native fastq-mcf.cpp fastq-lib.cpp -o fastq-mcf
g++ -Os -w -pipe -march=native fastq-multx.cpp fastq-lib.cpp -o fastq-multx
g++ -Os -w -pipe -march=native fastq-join.cpp fastq-lib.cpp -o fastq-join
g++ -Os -w -pipe -march=native fastq-lib.cpp gcModel.cpp -o fastq-stats fastq-stats.cpp
g++ -Os -w -pipe -march=native fastq-clipper.cpp fastq-lib.cpp -o fastq-clipper
g++ -Os -w -pipe -march=native samtools/*.o -lz -lpthread fastq-lib.cpp sam-stats.cpp -o sam-stats
g++ -Os -w -pipe -march=native fastq-lib.cpp tidx/tidx-lib.cpp -o varcall varcall.cpp -lgsl -lgslcblas
sam-stats.cpp:40:50: fatal error: samtools/sam.h: No such file or directory
compilation terminated.
make: *** [sam-stats] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by ilovezfs** [comment]
Cool thanks for checking. I think it just needs to depend on htslib.

**Comment by ilovezfs** [comment]
hmm no that file is in there... wonder if it's superenv that's making it work magically on macOS

**Comment by tseemann** [comment]
@ilovezfs it worked whenI compiled it in Linux manually with `make` but not when I go via Brew. I am working on a new formula using the new version but no luck so far.

**Comment by andersgs** [comment]
@tseemann I think this still broken...

```
linuxbrew@zaphod:~ $ brew install homebrew/science/ea-utils
==> Installing ea-utils from homebrew/science
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU
==> Downloading from https://doc-04-5g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/hg01snevhs5v1pm3q4ngvvov5g08l886/1487210400000/05687074833748560484/*/0B7KhouP0YeRAc2
######################################################################## 100.0%
==> Patching
patching file sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
patching file sparsehash-2.0.2/src/hashtable_test.cc
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/ea-utils/1.1.2-806_1
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/ea-utils/01.make:
make[1]: Leaving directory `/tmp/ea-utils-20170216-18860-1fh1do9/ea-utils.1.1.2-806/sparsehash-2.0.2'
mkdir sparsehash
cp -r sparsehash-2.0.2/src/sparsehash/* sparsehash/
g++ -Os -w -pipe -march=native fastq-mcf.cpp fastq-lib.cpp -o fastq-mcf
g++ -Os -w -pipe -march=native fastq-multx.cpp fastq-lib.cpp -o fastq-multx
g++ -Os -w -pipe -march=native fastq-join.cpp fastq-lib.cpp -o fastq-join
g++ -Os -w -pipe -march=native fastq-lib.cpp gcModel.cpp -o fastq-stats fastq-stats.cpp
g++ -Os -w -pipe -march=native fastq-clipper.cpp fastq-lib.cpp -o fastq-clipper
g++ -Os -w -pipe -march=native samtools/*.o -lz -lpthread fastq-lib.cpp sam-stats.cpp -o sam-stats
g++ -Os -w -pipe -march=native fastq-lib.cpp tidx/tidx-lib.cpp -o varcall varcall.cpp -lgsl -lgslcblas
sam-stats.cpp:40:50: fatal error: samtools/sam.h: No such file or directory
compilation terminated.
cp fastq-clipper /home/linuxbrew/.linuxbrew/Cellar/ea-utils/1.1.2-806_1/bin/fastq-clipper
make: *** [sam-stats] Error 1
make: *** Waiting for unfinished jobs....
```

Running:
```
Homebrew 1.1.9-dirty
Homebrew/homebrew-core (git revision e2629; last commit 2017-02-15)
```

**Comment by jonchang** [comment]
Superenv for Linuxbrew will fix it. You can wait until that happens (maybe a few weeks) or get it now with `brew install <formula> --env=super`

std env

```
 $ brew install homebrew/science/ea-utils --env=std
==> Installing ea-utils from homebrew/science
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU
Already downloaded: /home/jonchang/.cache/Homebrew/ea-utils-1.1.2-806
==> Patching
patching file sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
patching file sparsehash-2.0.2/src/hashtable_test.cc
==> make install PREFIX=/home/jonchang/.linuxbrew/Cellar/ea-utils/1.1.2-806_1
Last 15 lines from /home/jonchang/.cache/Homebrew/Logs/ea-utils/01.make:
fastq-mcf.cpp:29:81: fatal error: sparsehash/sparse_hash_map: No such file or directory
compilation terminated.
make: *** [fastq-mcf] Error 1
make: *** Waiting for unfinished jobs....
tidx/tidx-lib.cpp:12:37: fatal error: sparsehash/dense_hash_map: No such file or directory
compilation terminated.
sam-stats.cpp:37:81: fatal error: sparsehash/sparse_hash_map: No such file or directory
compilation terminated.
make: *** [sam-stats] Error 1
varcall.cpp:41:81: fatal error: sparsehash/sparse_hash_map: No such file or directory
compilation terminated.
make: *** [varcall] Error 1
fastq-stats.cpp:78:81: fatal error: sparsehash/sparse_hash_map: No such file or directory
compilation terminated.
make: *** [fastq-stats] Error 1
```

with superenv

```
 $ brew install homebrew/science/ea-utils --env=super
==> Installing ea-utils from homebrew/science
==> Installing dependencies for homebrew/science/ea-utils: gsl
==> Installing homebrew/science/ea-utils dependency: gsl
==> Downloading https://linuxbrew.bintray.com/bottles/gsl-2.3.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gsl-2.3.x86_64_linux.bottle.tar.gz
/home/jonchang/.linuxbrew/Cellar/gsl/2.3: 275 files, 10.2M
==> Installing homebrew/science/ea-utils 
==> Downloading https://drive.google.com/uc?export=download&id=0B7KhouP0YeRAc2xackxzRnFrUEU
==> Downloading from https://doc-04-5g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/997
######################################################################## 100.0%
==> Patching
patching file sparsehash-2.0.2/src/sparsehash/internal/sparsehashtable.h
patching file sparsehash-2.0.2/src/hashtable_test.cc
==> make install PREFIX=/home/jonchang/.linuxbrew/Cellar/ea-utils/1.1.2-806_1
/home/jonchang/.linuxbrew/Cellar/ea-utils/1.1.2-806_1: 15 files, 1.6M, built in 1 minute 40 seconds
```
```
