### ISSUE TITLE
The pig-config doesn't work for opencv3 even though there is a pc file 

### ISSUE THREAD

**Issue by xning** [Homebrew/homebrew-science#3233]
There are two issues
1. No link to the pc file in the /usr/local/lib/pkgconfig
2. No configuration for using the library in the share/OpenCV/3rdparty/lib

I fixed the above two issues by the following commands
1. link the pc file
cd /usr/local/lib/pkgconfig && ln -s ../../Cellar/opencv3/3.1.0_1/lib/pkgconfig/opencv.pc .
2. Fix the Libs setting of the pc file by adding the following option 
-L${exec_prefix}/lib -L${exec_prefix}/share/OpenCV/3rdparty/lib

**Comment by tdsmith** [comment]
Hi; thanks for the feedback!

# 1 is expected; that's a good fix.
I'm not sure about # 2; that sounds like something that you should consider raising with the OpenCV developers.

Let us know if we can help with anything else.
