### ISSUE TITLE
homebrew/python/scipy: Lapack_src on Linuxbrew

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3238]
_From @jwhite007 on January 19, 2016 18:42_

I'm attempting an install of scipy via pip in the brew-installed python. Numpy is claiming that it can't find lapack or blas resources even though I've installed lapack and openblas with brew. I could point numpy to them with the environment variables BLAS and LAPACK_SRC, however I don't find the lapack source in the brew install. Any suggestions on getting this to work? Thanks.

_Copied from original issue: Linuxbrew/linuxbrew#727_

**Comment by sjackman** [comment]
I'm going to move your issue to Homebrew-science. I think you'll have better luck getting your question answered there. Please post the output of `brew gist-logs homebrew/python/scipy`.

**Comment by tdsmith** [comment]
The homebrew/python/scipy formula should work; if you don't want to use those, you can look at the numpy and scipy formulas in homebrew/python to see how to configure them for a brewed openblas yourself.

**Comment by dpo** [comment]
See https://github.com/Homebrew/homebrew-python/blob/master/scipy.rb#L58-L66
