### ISSUE TITLE
ipopt build fails on 10.11.3

### ISSUE THREAD

**Issue by MarkCatherall** [Homebrew/homebrew-science#3241]
I've done `update` and `upgrade` and `doctor` and all that and this is the end of the output that I get  when I run `brew install asl`: https://gist.github.com/b67c4e23fd8edbb76fe1

I've already done everything I can find on the internets about this, including the [Matlab fix for getting `mex -setup` to recognise Xcode 7](http://www.mathworks.com/matlabcentral/answers/246507-why-can-t-mex-find-a-supported-compiler-in-matlab-r2015b-after-i-upgraded-to-xcode-7-0) which I found from issue #3011, none of which has worked. Please help me GitHub, you're my only hope!

**Comment by MarkCatherall** [comment]
This was resolved when I noticed from the gist that it was looking in the matlab2012a.app folder, instead of the matlab2014b.app folder. I deleted 2012a from my machine and it installed fine! Now I just have to build the matlab interface somehow!

**Comment by dpo** [comment]
The best would be to amend the formula to build the Matlab interface as an option. See, e.g., `superlu43.rb`. A PR would be very welcome.
