### ISSUE TITLE
rstudio-server commands and login issue

### ISSUE THREAD

**Issue by SangHLee** [Homebrew/homebrew-science#3243]
Once, I installed studio-server via homebrew, how do I evoke rstudio-server commands? i.e. in linux, I can use:

sudo rstudio-server version
or
sudo rstudio-server suspend-all

Also, I can go to localhost:8787 after the homebrew install of rstudio-server, but my login with Mac OS X user account credentials...

thank you for all your help in advance.

**Comment by tdsmith** [comment]
Please consult the rstudio-server community for help using the package.

**Comment by randy3k** [comment]
Unfortunately, RStudio Server doesn't ship with an administrative script on Mac OSX. You may be able to make one from the template
https://github.com/rstudio/rstudio/blob/ebb054efe3e650de818a251b11087311e5169ed8/src/cpp/server/extras/admin/rstudio-server.in
