### ISSUE TITLE
Brew uses and brew leaves ignore R deps

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew-science#3246]
I have R installed, it depends on gcc, and homebrew knows this because `brew deps r` includes gcc, but when I run `brew uses gcc --installed` or `brew leaves` that dep is ignored. I'm not 100% sure where the issue lies, but I figured it's likely related to this being a tap and since this is the only occurrence of the problem I see I'm reporting it here.

**Comment by dpo** [comment]
`r` depends on gcc because of its `:fortran` dependency, and perhaps also indirectly via other dependencies. Very few formulas actually state `depends_on "gcc"` (you can find those with grep).

What are you trying to accomplish?

**Comment by CamJN** [comment]
I just like to uninstall unnecessary packages whenever possible to save space, and since I don't have a use for gcc outside of serving other packages I have installed, I have to make the effort to remember that I need it for R to be able to build packages. It'd be nice to not have to know that.

**Comment by dpo** [comment]
Feel free to take this up with Homebrew Core, but there's nothing that can be done in this tap. `brew uses` is a core command. So I'll close this.
