### ISSUE TITLE
cuffdiff 2.2.1 with Segmentation fault: 11

### ISSUE THREAD

**Issue by pandaman55** [Homebrew/homebrew-science#3252]
please give me some help! I had struggled with the problem for a long time. my script and output:

perfect_match_hit bioinformatic$ cuffdiff -L wt,tg -p 20 -o cuffdiffOutputS /usr/local/Mus_musculus_UCSC_mm10/Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gtf \ perfect_hits_WT1.bam,perfect_hits_WT2.bam \ perfect_hits_tKO1.bam,perfect_hits_tKO2.bam,perfect_hits_tKO3.bam You are using Cufflinks v2.2.1, which is the most recent release.

    [18:30:07] Loading reference annotation.

    [18:30:13] Inspecting maps and determining fragment length distributions.

Segmentation fault: 11

I am using cufflinks 2.2.1, boost 1.55.01 under homebrew, os x 10.10.5 with Xcode 7.2.

Most weird things were that I can use cuffdiff if I tried a very small .bam file and no replicates, but didn't work if I tried any bigger(more that 100 MB) or more than 1 replicates. I tried boost 1.58.0,1.59 even 1.60, also lower version, failed. My computer's memory is 16 GB 1600 MHz DDR3. So I don't think it's memory ability.

Please give me some ideas. A little bit crazy now! Thanks!

**Comment by tdsmith** [comment]
Please report this to the cufflinks developers; thanks.
