### ISSUE TITLE
graph-tool: symbol binding failed

### ISSUE THREAD

**Issue by itcarroll** [Homebrew/homebrew-science#3259]
Python package imports okay, by calling `graph_draw` gives a runtime error message:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN10graph_tool6detail15action_dispatchIN5boost6lambda14lambda_functorINS3_19lambda_functor_baseINS3_12other_actionINS3_17assignment_actionEEENS2_6tuples5tupleINS4_INS3_8identityIRmEEEENS4_INS5_INS3_6actionILi2ENS3_15function_actionILi2EmEEEENSA_IKNS_15HardNumVerticesEKNS4_INS3_11placeholderILi1EEEEENS9_9null_typeESP_SP_SP_SP_SP_SP_SP_EEEEEESP_SP_SP_SP_SP_SP_SP_SP_EEEEEEN4mpl_5bool_ILb0EEEJNS0_15all_graph_viewsEEEC1ERKS10_
  Referenced from: /usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so
  Expected in: flat namespace

dyld: Symbol not found: __ZN10graph_tool6detail15action_dispatchIN5boost6lambda14lambda_functorINS3_19lambda_functor_baseINS3_12other_actionINS3_17assignment_actionEEENS2_6tuples5tupleINS4_INS3_8identityIRmEEEENS4_INS5_INS3_6actionILi2ENS3_15function_actionILi2EmEEEENSA_IKNS_15HardNumVerticesEKNS4_INS3_11placeholderILi1EEEEENS9_9null_typeESP_SP_SP_SP_SP_SP_SP_EEEEEESP_SP_SP_SP_SP_SP_SP_SP_EEEEEEN4mpl_5bool_ILb0EEEJNS0_15all_graph_viewsEEEC1ERKS10_
  Referenced from: /usr/local/lib/python3.5/site-packages/graph_tool/libgraph_tool_core.so
  Expected in: flat namespace
```

I uninstalled all the dependencies then built up from source with:

```
brew install --build-from-source boost
brew install --build-from-source boost-python --with-python3 --without-python
brew install --build-from-source graph-tool --HEAD --with-python3 --without-python
```

The graph-tool install issued the warning

```
Warning: homebrew/science/graph-tool dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

I tried to get more info by adding `ENV.append "CXXFLAGS" << "-fsanitize=undefined"` to the formula, which caused graph-tool compilation to stop with

```
checking whether clang++ supports C++14 features by default... no
checking whether clang++ supports C++14 features with -std=gnu++14... no
checking whether clang++ supports C++14 features with -std=gnu++0x... no
configure: error: *** A compiler with support for C++14 language features is required.
```

Alright ... how do I get one? Or is this a red herring?

**Comment by tdsmith** [comment]
The C++ stdlib warning isn't relevant; it's displayed because something, somewhere uses gfortran.

I think this is effectively a dupe of #3237 (boost 1.60 breaks graph-tool) and will be fixed by a forthcoming graph-tool release so I'll close this for now. Sorry for the hassle.

**Comment by itcarroll** [comment]
I should have referenced the issue I closed over at the graph-tool site:
https://git.skewed.de/count0/graph-tool/issues/266
The author, @count0, believes the incompatibility with boost_1.60 is fixed (not released, but I installed with --HEAD version).

So, sorry for the delayed additional info, but maybe not a dupe?

**Comment by tdsmith** [comment]
Did the --HEAD build actually fail?

**Comment by dwintergruen** [comment]
Head build worked. Importing works but drawing gives
dyld: lazy symbol binding failed: Symbol not found: __ZN10graph_tool6detail15action_dispatchINSt3__16__bindI19populate_edge_attrsJRNS2_12placeholders4__phILi1EEERN5boost6python4dictENS2_17reference_wrapperI11gt_hash_mapIiNS9_3anyENS2_4hashIiEENS2_8equal_toIiEENS2_9allocatorIiEEEEESC_SN_EEEN4mpl_5bool_ILb0EEEJNS0_15always_directedEEEC1ERKST_
  Referenced from: /usr/local/lib/python3.5/site-packages/graph_tool/draw/libgraph_tool_draw.so
  Expected in: flat namespace

dyld: Symbol not found: __ZN10graph_tool6detail15action_dispatchINSt3__16__bindI19populate_edge_attrsJRNS2_12placeholders4__phILi1EEERN5boost6python4dictENS2_17reference_wrapperI11gt_hash_mapIiNS9_3anyENS2_4hashIiEENS2_8equal_toIiEENS2_9allocatorIiEEEEESC_SN_EEEN4mpl_5bool_ILb0EEEJNS0_15always_directedEEEC1ERKST_
  Referenced from: /usr/local/lib/python3.5/site-packages/graph_tool/draw/libgraph_tool_draw.so
  Expected in: flat namespace

**Comment by dwintergruen** [comment]
Forgot max osx 10.11.2

**Comment by itcarroll** [comment]
Yep, it's the drawing that gets the dyld failure. Compile works, import works.
I'm getting the reference from libgraph_tool_core.so is the only difference form dwintergruen.

**Comment by tdsmith** [comment]
I think the correct incantation would be `ENV.append "CXXFLAGS", "-fsanitize=undefined"` fwiw

**Comment by tdsmith** [comment]
Can you give me a small example program that makes graph-tool fail?

**Comment by itcarroll** [comment]
Will test this when back at a computer, but pretty sure the following will
do it:

from graph_tool.all import *

g = Graph()
v1 = g.add_vertex()
v2 = g.add_vertex()
g.add_edge(v1, v2)
graph_draw(g, output='test.png')

--
Ian Carroll | carroll.ian@gmail.com | 805-291-7933
On Jan 28, 2016 6:08 PM, "tim smith" <notifications@github.com> wrote:

Can you give me a small example program that makes graph-tool fail?

—
Reply to this email directly or view it on GitHub
<https://github.com/Homebrew/homebrew-science/issues/3259#issuecomment-176474233>
.

**Comment by tdsmith** [comment]
I can duplicate the failure; the error I see is:

```
Dyld Error Message:
  Symbol not found: __ZN10graph_tool6detail15action_dispatchINSt3__16__bindI19populate_edge_attrsJRNS2_12placeholders4__phILi1EEERN5boost6python4dictENS2_17reference_wrapperI11gt_hash_mapIiNS9_3anyENS2_4hashIiEENS2_8equal_toIiEENS2_9allocatorIiEEEEESC_SN_EEEN4mpl_5bool_ILb0EEEJNS0_15always_directedEEEC1ERKST_
  Referenced from: /usr/local/lib/python2.7/site-packages/graph_tool/draw/libgraph_tool_draw.so
  Expected in: flat namespace
```

so I infer that the call which is failing is here: https://git.skewed.de/count0/graph-tool/blob/master/src/graph/draw/graph_cairo_draw.cc#L1820-1822

```cpp
    run_action<graph_tool::detail::always_directed>()
        (gi, std::bind(populate_edge_attrs(), std::placeholders::_1, oeattrs,
                       std::ref(eattrs), oedefaults, std::ref(edefaults)))();
```

**Comment by tdsmith** [comment]
I have no idea how to debug this further.

**Comment by itcarroll** [comment]
I don't either, but I need this to work, so I'm shooting blindly.

In the graph-tool build log (02.config.cc), I see a lot of "superenv add .... -std=c++11" flag for clang.
If that's really forcing c++11, that's not right. Not sure how to stop it though, because it doesn't seem to be coming from the brew formula.

btw, thanks very much for your help.

**Comment by mistydemeo** [comment]
> In the graph-tool build log (02.config.cc), I see a lot of "superenv add .... -std=c++11" flag for clang.
If that's really forcing c++11, that's not right.

I don't *think* that's the problem; if both `-std=c++11` and `-std=gnu++14` are specified, the later `std` declaration wins. In this case `-std=gnu++14` comes later, so it is being built in C++14 mode.

**Comment by mistydemeo** [comment]
I backported the [boost 1.60](https://git.skewed.de/count0/graph-tool/commit/248b086187808d0bbda27bde8a1efe12a15bddaa) fix from the upstream repository to the stable release and tested that, and it's working fine, so it looks like something else in `--HEAD` broke it.

My guess, to make a stab in the dark, is that it's probably this commit which refactors `run_action<>`: https://git.skewed.de/count0/graph-tool/commit/61421243a25eefac0f8330d57fdfab4686a5ac13

**Comment by count0** [comment]
I'm using HEAD with boost 1.60 on GNU/Linux and I cannot reproduce the problem. Whatever it is, it must be triggered only in Mac OS, or maybe with the clang compiler.

**Comment by count0** [comment]
I can confirm that this problems does not occur on HEAD with clang on GNU/Linux...

**Comment by mistydemeo** [comment]
After some testing, I can confirm that this was introduced by [61421243a25eefac0f8330d57fdfab4686a5ac13](https://git.skewed.de/count0/graph-tool/commit/61421243a25eefac0f8330d57fdfab4686a5ac13), the commit that refactored `run_action<>`. It works fine using the preceding commit, but this bug repros at that commit.

**Comment by itcarroll** [comment]
#3267 working here too.
@count0 , happy to run tests on OSX if you can suggest any.

**Comment by tdsmith** [comment]
Building with `-undefined dynamic_lookup` without `-bundle_loader` is probably hiding an interesting linker error message.

**Comment by mistydemeo** [comment]
Updated the stable version to work with boost 1.60, in the meantime.

**Comment by count0** [comment]
It is hard to understand how an undefined symbol can be generated in this manner. Can anyone confirm if this occurs using the latest clang version?

**Comment by count0** [comment]
It turns out this is a compiler bug. An actual (vanilla) clang version (e.g. 3.7.1) is needed for proper compilation. See https://git.skewed.de/count0/graph-tool/issues/266 for more details.

**Comment by itcarroll** [comment]
I'd like to replicate this, and have gotten as far as installing llvm37 from homebrew\versions. What would I do to make `brew install --HEAD` use clang-3.7?

**Comment by dpo** [comment]
@itcarroll `graph-tool` was just updated to 2.18. Could you check and report if you're still having the same issue? Note that if you're on 10.9, you'll have to build `boost` and `boost-python` from source with gcc-5 (`brew install homebrew/versions/gcc5`). `graph-tool` will also be compiled from source and gcc-5 will be automatically selected (gcc-6.1 is buggy).

**Comment by iMichka** [comment]
With 2.19, this still fails. Happens on the buildbots when making changes to matplotlib, see #4910
Error message is slightly different, but may help.

```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170125-62752-1o7dm0k.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/graph-tool.rb --verbose
==> python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import graph_tool.all as gt
  File "/usr/local/lib/python2.7/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/usr/local/lib/python2.7/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
Error: homebrew/science/graph-tool: failed
Failed executing: python test.py
```
