### ISSUE TITLE
Trouble installing pcl

### ISSUE THREAD

**Issue by magusverma** [Homebrew/homebrew-science#3274]
I tried installing with command : brew install homebrew/science/pcl --HEAD 

make log : https://gist.github.com/magusverma/73c8d92fe8e26beebd96

**Comment by dpo** [comment]
It would help to see the output of `brew gist-logs pcl`, but we normally can't offer support for HEAD builds. Such issues should be reported upstream.

**Comment by iMichka** [comment]
This has been open for one year now (without activity). If there are problems with HEAD versions, it is up to the user to sort that out with upstream. We are focusing on having stable working releases, and this is already a lot of work. I'll close this for now.

If you encounter problems with the stable release, please open a new issue, and we will have a look at that. Thanks.
