### ISSUE TITLE
meme  dyld: Library not loaded: /usr/local/lib/libmpi.1.dylib

### ISSUE THREAD

**Issue by crazyhottommy** [Homebrew/homebrew-science#3275]
I installed meme by:

```
brew install meme
```
when I evoke meme on command:

```
dyld: Library not loaded: /usr/local/lib/libmpi.1.dylib
  Referenced from: /usr/local/Cellar/meme/4.10.1/bin/meme
  Reason: image not found

```

It has to do with the mpi similar to this issue https://github.com/Homebrew/homebrew-science/issues/2314

How can I solve this?

Thanks,
Ming

**Comment by dpo** [comment]
The bottles probably need to be rebuilt. In the mean time, you can build from source if you'd like.
