### ISSUE TITLE
SHA256 mismatch error with el capitan.

### ISSUE THREAD

**Issue by LewisChoi** [Homebrew/homebrew-science#3289]
Hello 

I have problem to install libccd. After downloading it, I got error message below

==> Downloading from https://github.com/danfis/libccd
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 513e212fbb22cf720cf16ba911e8a8ccb1050c006789631ff2474ecc2f12b47a
Actual: 80cb4c7dd6741f2030fbf416e4820f2536dfe1bb1e1ace7826d413b92d572a21
Archive: /Library/Caches/Homebrew/libccd-2.0.tar.gz
To retry an incomplete download, remove the file above.

**Comment by LewisChoi** [comment]
I solved this problem by downloading it manually.

**Comment by atuleu** [comment]
@LewisChoi I think this issue should be re-open. I think there is a misconfiguration of the server at www.danfis.cz. I tried to download it several time using brew, and removing the file each time. The file always had a different checksum. If I change the sha in the recipe to ensure that the file would be validated, homebrew is unable to extract it.

Downloading it manually fixes the issue, but I think it would be easier to download it directly from github, there would be less error, and people that uses homebrew does not want to download fiel manually. Indeed I need libccd for dartsim for installing gazebo. If I have to download manually the 20 dependencies, I would switch to another package manager.

**Comment by dpo** [comment]
>  I think there is a misconfiguration of the server at www.danfis.cz. I tried to download it several time using brew, and removing the file each time. The file always had a different checksum. 

Sorry for the trouble. Does the checksum also change when you download manually?

**Comment by LewisChoi** [comment]
No, it was fine when I downloaded it manually. But, as Atuleu mentioned the checksum problem above, downloading it by using brew gives always different checksum.

**Comment by dpo** [comment]
Please `brew update` and let me know if the issue is fixed.

**Comment by LewisChoi** [comment]
Yes, it is fixed! Thanks

Wooseok-MacBook:~ Wooseok$ brew install libccd
==> Installing libccd from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/libccd-2.0_1.el_cap
######################################################################## 100.0%
==> Pouring libccd-2.0_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libccd/2.0_1: 10 files, 93.7K
Wooseok-MacBook:~ Wooseok$

**Comment by atuleu** [comment]
Fixed for me too

```bash
$ brew reinstall libccd
==> Reinstalling homebrew/science/libccd
==> Downloading https://homebrew.bintray.com/bottles-science/libccd-2.0_1.el_capitan.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libccd-2.0_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libccd/2.0_1: 10 files, 93.7K
$ brew reinstall --build-from-source libccd
==> Reinstalling homebrew/science/libccd
==> Downloading https://github.com/danfis/libccd/archive/v2.0.tar.gz
==> Downloading from https://codeload.github.com/danfis/libccd/tar.gz/v2.0
######################################################################## 100,0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/libccd/2.0_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
==> make install
🍺  /usr/local/Cellar/libccd/2.0_1: 10 files, 91.9K, built in 3 seconds
```
