### ISSUE TITLE
Installing masurca error ` No rule to make target `jellyfish/jellyfish.hpp' `

### ISSUE THREAD

**Issue by rob2go** [Homebrew/homebrew-science#3291]
Hi guys,
I can't really undertand what is the matter
I've even installed jellyfish separated with brew but nothing changes

Here is the Log
https://gist.github.com/a8b55c46c685015c55c8

thank you

**Comment by Moisan** [comment]
This seems to be related to #1593.

**Comment by greenstick** [comment]
I'm facing the same problem, I checked out issue [#1593](https://github.com/Homebrew/homebrew-science/issues/1593), but it doesn't seem there's a good answer there. It's been about a year; is anyone aware of any updates?

Thanks
