### ISSUE TITLE
opencv3 python3 wrappers can not be generated

### ISSUE THREAD

**Issue by Azygote** [Homebrew/homebrew-science#3302]
When I'm trying to install opencv3:

`brew install opencv3 --c++11 --with-contrib --with-cuda --with-ffmpeg --with-gphoto2 --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni --with-openni2 --with-python3 --with-qt5 --with-quicktime --with-tbb --with-vtk`

I got following messages:
`==> Installing opencv3 from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3-3.1.0.tar.gz
==> Downloading https://github.com/Itseez/opencv_contrib/archive/3.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv3--contrib-3.1.0.tar.gz
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages"
     You should`unset PYTHONPATH`to fix this.
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages"
     You should`unset PYTHONPATH`to fix this.
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20141027.tgz
Already downloaded: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv3/3.1.0_1 -DCMAK
==> make
Last 15 lines from /Users/tianyuge/Library/Logs/Homebrew/opencv3/02.make:
/tmp/opencv320160211-55945-r1p0se/opencv-3.1.0/modules/core/src/opengl.cpp:1646:14: error: use of undeclared identifier 'clGetGLContextInfoKHR'; did you mean 'clGetContextInfo'?
        if (!clGetGLContextInfoKHR)
             ^~~~~~~~~~~~~~~~~~~~~
             clGetContextInfo
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:633:1: note: 'clGetContextInfo' declared here
clGetContextInfo(cl_context         /* context */, 
^
/tmp/opencv320160211-55945-r1p0se/opencv-3.1.0/modules/core/src/opengl.cpp:1669:52: error: use of undeclared identifier 'CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR'
        status = clGetGLContextInfoKHR(properties, CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR, sizeof(cl_device_id), (void*)&device, NULL);
                                                   ^
6 errors generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2`

And here is the gist-log: [https://gist.github.com/anonymous/4872fa71996885b03c85](gist-log)

**Comment by saolsen** [comment]
I'm not getting any error message but only python2.7  packages are building even with the --with-python3 flag.

**Comment by amckinlay** [comment]
Your error message has something to do with `--with-opengl`. I had the same error when compiling with OpenGL on Mac OS 10.11. I also opened a new [issue](#3329) regarding the Python 3 wrapper.

**Comment by iMichka** [comment]
Hi. There has been some opencv3 updates since the initial issue report. Most of the python3 problems have been solved.

It seems that the actual failure was due to the `--with-opengl`. If you still have trouble installing with that flag, please open a new issue (with a build log for opencv3 using only that flag, so that the log file is not cluttered with unnecessary information). Thanks.
