### ISSUE TITLE
bamtools 2.4.0 does not provide libbamtools-utils.so

### ISSUE THREAD

**Issue by heuermh** [Homebrew/homebrew-science#3309]
On linuxbrew bamtools 2.4.0 does not appear provide libbamtools-utils.so

``` bash
$ ls ~/.linuxbrew/opt/bamtools/lib
libbamtools.a
libbamtools.so
libbamtools.so.2.4.0
```

Wasn't sure which repo against which to report this issue, please let me know if I should report it upstream (bamtools) or downstream (linuxbrew).

**Comment by iMichka** [comment]
Hi. This bug report is pretty old. Seems nobody worked on this since then. bamtools is now at version 2.4.1, please try again there. Please open a new issue if you still encounter this problem. Thanks.
