### ISSUE TITLE
Minced error un prokka pipeline 

### ISSUE THREAD

**Issue by ejuscamaytal** [Homebrew/homebrew-science#3316]
Hello!!! I am a beginner. I installed the prokka pipeline and all the dependence software. However, when I am running the pipeline I have a error: línea 33: can't find the minced.java but my minced.java is in the same location that the minced file. Also, when I want to install the minced program I have the same error. I can't install the java program. 

Please, can you help me.

Thanks,

**Comment by tdsmith** [comment]
Please reach out to the prokka community; you can find their website by running `brew home prokka`.
