### ISSUE TITLE
opencv failed to build against QuickTime on 10.11

### ISSUE THREAD

**Issue by amckinlay** [Homebrew/homebrew-science#3322]
Using `--with-quicktime` to build `opencv` compiles against the QuickTime API, which appears to have been deprecated in Mac OS X since 10.9.

https://gist.github.com/anonymous/f6b22596a00e310b95b6

This issue affects `opencv3` as well.

**Comment by tdsmith** [comment]
Thanks for filing an issue. I propose removing the `--with-quicktime` option from the formula; do you see another solution?

**Comment by amckinlay** [comment]
Since Homebrew officially supports only 10.9 and above, I don't see why not.

**Comment by tdsmith** [comment]
:+1:

**Comment by dpo** [comment]
Should be fixed in #4336.
