### ISSUE TITLE
PETSc and SLEPc need rebuilding after open MPI upgrade

### ISSUE THREAD

**Issue by mattia-** [Homebrew/homebrew-science#3336]
Hello all,

when building a third-party program based on PETSc I got the following error.

`-- PETSC_DIR is /usr/local/Cellar/petsc/3.6.3_1/real
-- PETSC_ARCH is empty
-- Found petscconf.h
-- Include directory /usr/local/Cellar/open-mpi/1.10.1_1/include does not exist
-- Unable to find library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin
-- Unable to find library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin
-- Unable to find library gfortran
-- Unable to find library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin
-- Performing test PETSC_TEST_RUNS - Failed
-- Performing test PETSC_TEST_3RD_PARTY_LIBS_RUNS - Failed
-- PETSc configured without Cusp support
-- PETSc could not be found. Be sure to set PETSC_DIR and PETSC_ARCH. (missing:  PETSC_TEST_RUNS) (Required is at least version "3.4")`

The problem is it is looking for /usr/local/Cellar/open-mpi/1.10.1_1/include but the open MPI version currently available via homebrew is 1.10.2. 
Or did I completely misunderstood the issue here?

If I am correct, then the same goes for SLEPc

**Comment by dpo** [comment]
Thanks for reporting! Your assessment is correct. This is particularly annoying because 38 formulas in this tap are potentially affected...

**Comment by dpo** [comment]
Should be good to go, at least as far as `petsc` and `slepc` are concerned.

**Comment by mattia-** [comment]
I confirm that everything works. Thanks for the quick fix!
