### ISSUE TITLE
colpack errors out on El Capitan (simple fix)

### ISSUE THREAD

**Issue by hlokavarapu** [Homebrew/homebrew-science#3343]
When executing:
   brew install colpack
The following output is generated:
[output.txt](https://github.com/Homebrew/homebrew-science/files/139085/output.txt)

To fix this, I had to manually edit the formula and pass the CXX=/usr/bin/clang++ as part of the configure options.

**Comment by dpo** [comment]
Could you please post the output of `brew gist-logs colpack` and `brew doctor` just to be sure? Thanks!

**Comment by dpo** [comment]
I just updated the `colpack` bottles and it built fine on the bot. Please feel free to open a new issue if problems persist.
