### ISSUE TITLE
PCL, Error 2 for pcl_filters

### ISSUE THREAD

**Issue by dmitrievk** [Homebrew/homebrew-science#3347]
I use `brew install pcl --with-example` to build pcl 1.7.2 with vtk 7.0 on el capitan. I got the following error:
cd /tmp/pcl20160221-37183-u6tl42/pcl-pcl-1.7.2/macbuild/filters && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_symlink_library ../lib/libpcl_filters.1.7.2.dylib ../lib/libpcl_filters.1.7.dylib ../lib/libpcl_filters.dylib
[ 23%] Built target pcl_filters
make: *** [all] Error 2

Here are the build logs:
[https://gist.github.com/anonymous/302b50543d251421b80d](url)

**Comment by earthflat** [comment]
Same error for me on Yosemite!

**Comment by dmitrievk** [comment]
Works with --HEAD though

**Comment by earthflat** [comment]
I need to use recent stable version 1.7.2 of PCL with regards to some dependencies. Could somebody fix or help with the problem of VTK 7.0 with stable PCL 1.7.2?

**Comment by drhalftone** [comment]
I get the error with "brew install pcl --without-apps --without-tools --without-vtk --without-qt"

**Comment by dpo** [comment]
`pcl` was updated to 1.8.0 which should build against vtk7. Please feel free to open a new issue if problems persist.
