### ISSUE TITLE
mlpack downloading armadillo fails

### ISSUE THREAD

**Issue by RuochenFENG** [Homebrew/homebrew-science#3351]
when using `brew install homebrew/science/mlpack`, I got the following error

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "armadillo"
Download failed: https://sourceforge.net/projects/arma/files/armadillo-3.6.2.tar.gz

I don't understand why it's downloading version 3.6.2 of armadillo ?

**Comment by dunn** [comment]
Your version of Homebrew may be out of date. Try running `brew update` and installing again.

**Comment by RuochenFENG** [comment]
That was the problem, thanks for the reply.

**Comment by dunn** [comment]
No problem, glad things are working again!
