### ISSUE TITLE
What's the point of the smrtanalysis package?

### ISSUE THREAD

**Issue by amckinlay** [Homebrew/homebrew-science#3352]
In `smrtanalysis.rb`: `raise "SMRT Analysis cannot be installed on Mac OS" if OS.mac?`.

What's the point?

**Comment by dpo** [comment]
Linuxbrew presumably. @sjackman

**Comment by amckinlay** [comment]
I had a feeling, thanks.

I got excited when I thought I could install this package on Mac. :(

**Comment by sjackman** [comment]
Yes, that's right. For Linuxbrew.
