### ISSUE TITLE
qhull version scheme changed

### ISSUE THREAD

**Issue by tomyun** [Homebrew/homebrew-science#3353]
`qhull` used to be versioned like `2012.1`, but the latest brew formula somehow changed it to `7.2.0` (#3349) which is not detected by `brew upgrade` because 2012 is greater than 7.

Seems like qhull adopts two different versioning schemes and it's supposed to be `2015.2` for the current release according to the [changelog](http://www.qhull.org/src/Changes.txt). I wonder if Homebrew wanted to change its scheme or bring back the original scheme for compatibility.

**Comment by dpo** [comment]
Thanks for noticing! How annoying. It seems the naming scheme of the archive might have changed what `brew` thinks the version number is. It used to be `qhull-2012.1-src.tgz` and now it is `qhull-2015-src-7.2.0.tgz`. Strangely, the Windows archive is named `qhull-2015.2.zip`. I think simply adding a `version` field to the formula should fix it.

**Comment by dpo** [comment]
should be good to go.
