### ISSUE TITLE
shogun on OS El Capitan (too many template arguments for class template 'matrix_base')

### ISSUE THREAD

**Issue by gdoura** [Homebrew/homebrew-science#3358]
Hello,

When I'm trying to install shogun on mac El Captain version 10.11.2 
with : brew reinstall shogun

I get the following error :

==> Downloading http://shogun-toolbox.org/archives/shogun/releases/4.0/sources/shogun-4.0.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/shogun-4.0.0.tar.bz2
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PRE
==> make
Last 15 lines from /Users/abdel/Library/Logs/Homebrew/shogun/02.make:
In file included from /tmp/shogun20160223-21939-1sc9h7q/shogun-4.0.0/src/shogun/mathematics/linalg/internal/implementation/ElementwiseSquare.h:45:
/tmp/shogun20160223-21939-1sc9h7q/shogun-4.0.0/src/shogun/lib/GPUMatrix.h:81:20: error: too many template arguments for class template 'matrix_base'
 typedef viennacl::matrix_base<T, viennacl::column_major, std::size_t, std::ptrdiff_t> VCLMatrixBase;
                   ^                                                   ~~~~~~~~~~~~~~~
/usr/local/include/viennacl/forwards.h:372:9: note: template is declared here
  class matrix_base;
        ^
2 errors generated.
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/kernel/CustomKernel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: optimization flag '-finline-functions' is not supported
clang: warning: optimization flag '-finline-functions' is not supported
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [all] Error 2

I will greatly appreciate any help for the proper installation of shogun.
Thank you very much in advance.

AG

**Comment by dpo** [comment]
Please post the output of `brew gist-logs shogun`. Thanks.

**Comment by gdoura** [comment]
thank you. 
https://gist.github.com/anonymous/55036d40ec7469d9aab3

**Comment by gdoura** [comment]
I've uninstalled viennaCL with brew uninstall viennaCL and it seems to be compiling fine. 
Now I just have a minor issue  when I do brew link shogun, it is not able to symlink.

Linking /usr/local/Cellar/shogun/4.0.0... 
Error: Could not symlink share/shogun/examples/cmdline
/usr/local/share/shogun/examples is not writable.

**Comment by gdoura** [comment]
https://gist.github.com/573afbba20d8154eef14

**Comment by gdoura** [comment]
the minor issue is resolved with:

sudo chown -R 'whoami' /usr/local/share/shogun/examples
brew link --overwrite --dry-run shogun
brew unlink shogun && brew link shogun
brew unlink shogun && brew link shogun

**Comment by dpo** [comment]
I'm not sure why that folder had wrong permissions. Does `brew doctor` complain about anything at this point? If not, and if the issue is resolved, feel free to close.
