### ISSUE TITLE
opencv3 --with-contrib --with-ffmpeg --HEAD build error with Mac OS X El Capitan 10.11

### ISSUE THREAD

**Issue by drakaris** [Homebrew/homebrew-science#3367]
MacBook-Air:~ mraghura$ brew install opencv3 --with-contrib --with-ffmpeg --HEAD
==> Installing opencv3 from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/Itseez/opencv.git
Cloning into '/Library/Caches/Homebrew/opencv3--git'...
remote: Counting objects: 5539, done.
remote: Compressing objects: 100% (4821/4821), done.
remote: Total 5539 (delta 847), reused 3058 (delta 482), pack-reused 0
Receiving objects: 100% (5539/5539), 70.28 MiB | 266.00 KiB/s, done.
Resolving deltas: 100% (847/847), done.
Checking connectivity... done.
Checking out files: 100% (4654/4654), done.
==> Checking out branch master
==> Cloning https://github.com/Itseez/opencv_contrib.git
Cloning into '/Library/Caches/Homebrew/opencv3--contrib--git'...
remote: Counting objects: 2038, done.
remote: Compressing objects: 100% (1612/1612), done.
remote: Total 2038 (delta 433), reused 1586 (delta 318), pack-reused 0
Receiving objects: 100% (2038/2038), 47.93 MiB | 826.00 KiB/s, done.
Resolving deltas: 100% (433/433), done.
Checking connectivity... done.
Checking out files: 100% (1717/1717), done.
==> Checking out branch master
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty
Already downloaded: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/Primary/Library/Logs/Homebrew/opencv3/02.make:
@property (readonly, copy) NSArray<ObjectType> *allObjects;
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ 27%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.o
cd /tmp/opencv320160225-78559-xiarob/macbuild/modules/dnn && /usr/local/Library/ENV/4.3/clang++   -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -D__OPENCV_BUILD=1 -I/tmp/opencv320160225-78559-xiarob/3rdparty/ippicv/unpack/ippicv_osx/include -I/tmp/opencv320160225-78559-xiarob/macbuild -isystem /usr/local/include/eigen3 -I/tmp/opencv320160225-78559-xiarob/opencv_contrib/modules/dnn/include -I/tmp/opencv320160225-78559-xiarob/opencv_contrib/modules/dnn/src -I/tmp/opencv320160225-78559-xiarob/macbuild/modules/dnn -I/tmp/opencv320160225-78559-xiarob/modules/core/include -I/tmp/opencv320160225-78559-xiarob/modules/imgproc/include -I/tmp/opencv320160225-78559-xiarob/opencv_contrib/modules/dnn/3rdparty/protobuf/src  -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security   -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow  -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -Wno-shadow -Wno-parentheses -Wno-maybe-uninitialized -Wno-sign-promo -Wno-missing-declarations -Wno-missing-prototypes -Wno-unused-parameter -DNDEBUG  -DNDEBUG -fPIC   -o CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.o -c /tmp/opencv320160225-78559-xiarob/macbuild/modules/dnn/opencl_kernels_dnn.cpp
[ 27%] Linking CXX shared library ../../lib/libopencv_dnn.dylib
cd /tmp/opencv320160225-78559-xiarob/macbuild/modules/dnn && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_link_script CMakeFiles/opencv_dnn.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++     -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security   -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow  -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -Wno-shadow -Wno-parentheses -Wno-maybe-uninitialized -Wno-sign-promo -Wno-missing-declarations -Wno-missing-prototypes -Wno-unused-parameter -DNDEBUG  -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 3.1.0 -current_version 3.1.0 -o ../../lib/libopencv_dnn.3.1.0.dylib -install_name /tmp/opencv320160225-78559-xiarob/macbuild/lib/libopencv_dnn.3.1.dylib CMakeFiles/opencv_dnn.dir/caffe.pb.cc.o CMakeFiles/opencv_dnn.dir/src/blob.cpp.o CMakeFiles/opencv_dnn.dir/src/caffe/caffe_importer.cpp.o CMakeFiles/opencv_dnn.dir/src/caffe/caffe_io.cpp.o CMakeFiles/opencv_dnn.dir/src/dnn.cpp.o CMakeFiles/opencv_dnn.dir/src/init.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/concat_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/convolution_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/fully_connected_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/im2col.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/layers_common.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/lrn_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/mvn_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/pooling_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/reshape_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/slice_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/softmax_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/layers/split_layer.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/THDiskFile.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/THFile.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/THGeneral.cpp.o CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.o ../../lib/libopencv_imgproc.3.1.0.dylib ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a ../../3rdparty/lib/liblibprotobuf.a ../../lib/libopencv_core.3.1.0.dylib 
20 errors generated.
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
cd /tmp/opencv320160225-78559-xiarob/macbuild/modules/dnn && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_symlink_library ../../lib/libopencv_dnn.3.1.0.dylib ../../lib/libopencv_dnn.3.1.dylib ../../lib/libopencv_dnn.dylib
[ 27%] Built target opencv_dnn
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-science/issues

That's the output that's thrown on my terminal. I've tried without --HEAD and it's the same. Any help ?

**Comment by dpo** [comment]
Note that we don't support `HEAD` builds. `ffmpeg` was updated in the past few days. Did you upgrade? If you did, or if upgrading doesn't resolve the issue, please post the output of `brew gist-logs opencv3`. Thanks.

**Comment by autosquid** [comment]
@drakaris  I read you also tried without --HEAD. By now, have you resolved the problem?  I met the same (I think) problem, and here is the log:  https://gist.github.com/autosquid/ca0db9e8c52165acf0e33d13fce45c00


@dpo  would you kindly have a look at it ?

please ignore the proxychains things, 'cause I need it to download the 3rd parties.

**Comment by heinemml** [comment]
@autosquid the link to your gist is not working. Is the problem still existing?

**Comment by autosquid** [comment]
@heinemml   I adjusted the sequences of options I added, and then the problem is gone. (I do not understand why... :( )

**Comment by dpo** [comment]
Please open a new issue if the problem persists.
