### ISSUE TITLE
Option to build static opencv libraries

### ISSUE THREAD

**Issue by solosuper** [Homebrew/homebrew-science#3373]
Hi everyone,
Is it possible for [opencv3](https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb) to include an option to build static libraries, e.g. `--build-static`?

The CMake option would be `BUILD_SHARED_LIBS=OFF`.

**Comment by dpo** [comment]
It seems like it should be possible. Do you want to submit a PR? You can imitate existing options and add `option "with-static", "Build static libraries"`. It should be 1 or 2 lines of code. Make sure to test locally before submitting though.

**Comment by solosuper** [comment]
Yes, I can try. Right now I am having the VTK issue #3371, so I won't be
able to test all options combined, but I'll try later.

fre. 26. feb. 2016 kl. 18.37 skrev Dominique <notifications@github.com>:

**Comment by ysolovyov** [comment]
Where are those static libs? I can't find them in /usr/local/opt/opencv3/lib It does not work
