### ISSUE TITLE
OpenCV3 failed to build with opengl on OSX

### ISSUE THREAD

**Issue by pro404** [Homebrew/homebrew-science#3383]
System:
>HOMEBREW_VERSION: 0.9.5
CPU: 2-core 64-bit
OS X: 10.11.3-x86_64
Xcode: 7.2

I used this command
>brew install opencv3 --with-contrib --c++11 --with-ffmpeg --with-tbb --with-qt5 --with-gphoto2 --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni2 --with-python3

got this error:
>==> Installing homebrew/science/opencv3
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
==> Downloading from https://codeload.github.com/Itseez/opencv/tar.gz/3.1.0
######################################################################## 100.0%
==> Downloading https://github.com/Itseez/opencv_contrib/archive/3.1.0.tar.gz
==> Downloading from https://codeload.github.com/Itseez/opencv_contrib/tar.gz/3.
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty
==> Downloading from http://netix.dl.sourceforge.net/project/opencvlibrary/3rdpa
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/umar/Library/Logs/Homebrew/opencv3/02.make:
/tmp/opencv320160229-40693-1bccocx/opencv-3.1.0/modules/core/src/opengl.cpp:1646:14: error: use of undeclared identifier 'clGetGLContextInfoKHR'; did you mean 'clGetContextInfo'?
        if (!clGetGLContextInfoKHR)
             ^~~~~~~~~~~~~~~~~~~~~
             clGetContextInfo
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:633:1: note: 'clGetContextInfo' declared here
clGetContextInfo(cl_context         /* context */, 
^
/tmp/opencv320160229-40693-1bccocx/opencv-3.1.0/modules/core/src/opengl.cpp:1669:52: error: use of undeclared identifier 'CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR'
        status = clGetGLContextInfoKHR(properties, CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR, sizeof(cl_device_id), (void*)&device, NULL);
                                                   ^
6 errors generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/opengl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2`

**Comment by dpo** [comment]
We'll need the output of `brew gist-logs opencv` but please check that your issue isn't already the same as in #3371. For building against `ffmpeg`, there's already a patch in #3380.

**Comment by dpo** [comment]
Sorry, this is `opencv3`. I got confused by the subject line. We'll still need `brew gist-logs opencv3`.

**Comment by pro404** [comment]
https://gist.github.com/anonymous/4883481abd482f7c5661

**Comment by heinemml** [comment]
Is this problem still existing? On my system installation works.
```
brew info opencv3
homebrew/science/opencv3: stable 3.1.0 (bottled), HEAD [keg-only]
Open source computer vision library, version 3
http://opencv.org/
/usr/local/Cellar/opencv3/3.1.0_3 (485 files, 133.4M)
  Built from source with: --with-contrib --c++11 --with-ffmpeg --with-tbb --with-qt5 --with-gphoto2 --with-gstreamer --with-jasper --with-java --with-libdc1394 --with-opengl --with-openni2 --with-python3
```

**Comment by dpo** [comment]
@heinemml Are you on 10.11?
@pro404 Any news?

**Comment by heinemml** [comment]
@dpo I'm on 10.11.4

**Comment by dpo** [comment]
I'll close this now that #4336 has been merged. Please open a new issue if problems remain. Thanks.
