### ISSUE TITLE
OpenCV and OpenCV3 fail to build with ximea camera support

### ISSUE THREAD

**Issue by vilim** [Homebrew/homebrew-science#3395]
Hello,

I tried to build opencv or opencv3 with ximea camera support (with changing the opencv3 formula to include -DWITH-XIMEA option) but the build fails at a linker error "ld: framework not found m3api". The framework however is installed (from the manufacturers website) and located in /Library/Frameworks/, as everything else. I also tried copying and symlinking the m3api framework to /usr/local/Frameworks, but it did not help.
opencv and opencv3 build fine without ximea, and I tried all the troubleshooting steps.

The command issued was: `brew install opencv --with-ximea`
The complete log is at  [https://gist.github.com/anonymous/8c7b3f4af2135cdd60f2](https://gist.github.com/anonymous/8c7b3f4af2135cdd60f2)

**Comment by dpo** [comment]
Did the [new issue guidelines](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md) not show up when you opened this issue? Please follow the instructions in there to help us help you.

**Comment by vilim** [comment]
Sorry about not posting the gist the first time around, somehow I missed the step.

**Comment by heinemml** [comment]
@vilim Could you try with the recent releases if the problem still exists? On my 10.11.5 System `brew install opencv --with-ximea` completed without error.

**Comment by iMichka** [comment]
Tested on my setup, and it worked.

Since you opened this issue, opencv 2.4.13.2 has been release. Please open a new issue if you still have trouble with that version.
