### ISSUE TITLE
usr/local

### ISSUE THREAD

**Issue by DarrellL** [Homebrew/homebrew-science#3412]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue:
- Please state the complete command that you issued.
- Please do not post lengthy build output here. Instead provide a link to a gist.
- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Did you have a specific issue?

**Comment by DarrellL** [comment]
Sorry, my mistake. Cheers.
