### ISSUE TITLE
Bowtie2 doesn't install on CentOS

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3440]
_From @grandeabobora on March 11, 2016 19:5_

I tried to install bowtie2 on a CentOS machine and I couldn't. Here is the link with the gist log: https://gist.github.com/anonymous/a1b3d4bc12e9c928faf6

It was the first time I tried to use brew on a Linux machine, but I've been using it on a Mac since 2010.

Also, 

$ brew doctor
Your system is ready to brew.

_Copied from original issue: Linuxbrew/linuxbrew#914_

**Comment by sjackman** [comment]
It looks as though it fails to build with GCC 4.8.
Try `brew install gcc bowtie2`

**Comment by sjackman** [comment]
_From @grandeabobora on March 14, 2016 12:25_

I tried to compile with gcc 5.3.0, but still doesn't work.

**Comment by sjackman** [comment]
See https://github.com/BenLangmead/bowtie2/issues/34

**Comment by sjackman** [comment]
As a workaround, try `brew install bowtie2 --without-tbb`

**Comment by sjackman** [comment]
`bowtie2 2.2.8` fails to build with `tbb 4.4`. See #3441 and https://github.com/BenLangmead/bowtie2/issues/34

**Comment by BenLangmead** [comment]
Thanks, Shaun.  @val-antonescu is looking into it now.

**Comment by sjackman** [comment]
Great. Thanks, Ben, Val!

**Comment by sjackman** [comment]
Fixed by #3441
