### ISSUE TITLE
qgis failed to build on OS 10.10.5

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#3442]
_From @ceedave on January 4, 2016 19:37_

Hello,

The log reported qgis_gui build than crashed with an (uninformative) error message.

Brew doctor reported all okay except possible problems with case-sensitive OS.

Brew was updated, upgraded and pruned before the attempted build.

Many, many other brew formulae work beautifully (thanks!).

Gist log at:
https://gist.github.com/ceedave/2b9e8ea71bac458d5dc1

Thanks,
Chris

_Copied from original issue: Homebrew/homebrew#47682_

**Comment by DomT4** [comment]
_From @batic on January 5, 2016 13:16_

I confirm - I get the same error.

**Comment by DomT4** [comment]
_From @mikemcquaid on January 5, 2016 13:46_

@batic Can you also paste your Gist log?

**Comment by DomT4** [comment]
_From @batic on January 5, 2016 13:55_

https://gist.github.com/batic/17ae745923f9369722f4

Basically it is the same as from ceedave.

**Comment by DomT4** [comment]
_From @mikemcquaid on January 5, 2016 16:21_

@batic I'd like to see your `doctor` output too?

**Comment by DomT4** [comment]
_From @krishagel on January 25, 2016 23:50_

I am seeing the same problem.  Here is my log:

https://gist.github.com/krishagel/c52b87ab9107f66837d6

And here is the output from brew doctor

https://gist.github.com/krishagel/a152413d37cf7d111568

**Comment by DomT4** [comment]
_From @jarandaf on February 26, 2016 8:8_

Same error

**Comment by DomT4** [comment]
_From @henrywuxad on March 2, 2016 21:40_

same error here

**Comment by DomT4** [comment]
_From @eric-p on March 8, 2016 17:36_

Hi,
Same error for me. gist log : https://gist.github.com/53559863fe7f30c8e245
Nothing on brew doctor.

**Comment by creade** [comment]
I'm getting an error as well on osx 10.9.5:
https://gist.github.com/creade/37e2d195404593de6949

**Comment by shrx** [comment]
Same here.

**Comment by mghouse** [comment]
+1.  (10.10.5)
Last lines:
```
[ 52%] Built target qgis_gui
make: *** [all] Error 2
```
Appears to be widespread:

qgis failed to build on 10.11 https://github.com/Homebrew/homebrew-science/issues/2914
qgis install error https://github.com/Homebrew/homebrew-science/issues/1866
Multiple taps for qgis https://github.com/Homebrew/homebrew-science/issues/1036
qgis failed to build on OS 10.10.5 https://github.com/Homebrew/homebrew-science/issues/3442
qgis build error on 10.9.5 https://github.com/Homebrew/homebrew-science/issues/2915
Error when trying to install qgis through brew on Yosemite https://github.com/Homebrew/homebrew-science/issues/2692

**Comment by iMichka** [comment]
`qgis` was removed from `homebrew-science` with #4688. Closing.
