### ISSUE TITLE
Problems installing spades

### ISSUE THREAD

**Issue by rob2go** [Homebrew/homebrew-science#3445]
I get this when I try to brew spades

 brew install spades
==> Installing spades from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/spades-3.7.1.el_capitan.bottle.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "spades"
Download failed: https://homebrew.bintray.com/bottles-science/spades-3.7.1.el_capitan.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://spades.bioinf.spbau.ru/release3.7.1/SPAdes-3.7.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/spades-3.7.1.tar.gz
Error: SHA256 mismatch
Expected: 4d9b114150c4d37084967a5a3264d36a480394996197949fb72402f2d65b42a3
Actual: e904f57b08c5790c64406763b29650ffba872da47ec5a3e659396fcfcbc9b35a
Archive: /Library/Caches/Homebrew/spades-3.7.1.tar.gz
To retry an incomplete download, remove the file above.

**Comment by dpo** [comment]
I don't have a 10.11 system to test but something's off because your log indicates that `brew` tries to download a bottle or the source for version 3.7.1, while the formula is only for version 3.7.0. Did you modify `spades.rb`?

**Comment by ilovezfs** [comment]
this should be fixed if you brew update and brew install spades, since spades is at 3.9.0 now
