### ISSUE TITLE
Problems of `brew install arpack`

### ISSUE THREAD

**Issue by Dtrycode** [Homebrew/homebrew-science#3451]
I don't know what the issues are. I just can't install the octave. Please give me some help.
<img width="566" alt="screen shot 2016-03-17 at 1 50 42 pm" src="https://cloud.githubusercontent.com/assets/14356517/13860781/5065d1c6-ec47-11e5-9332-714ee5864d5d.png">

**Comment by dpo** [comment]
Try `brew upgrade gcc`. If that doesn't work, please post the output of `brew gist-logs arpack`.
