### ISSUE TITLE
Ceres Solver bottle uses old Eigen version

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#3454]
### Indicate troubleshooting steps taken

- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x ] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

- Brief summary of issue:

Identical to https://github.com/Homebrew/homebrew-science/issues/3195, except now eigen is at 3.2.8

> Ceres Solver seems to be compiled with Eigen 3.2.[7], but the latest Homebrew version is 3.2.[8]. This can cause build errors downstream.

**Comment by dpo** [comment]
Feel free to submit a PR to bump `ceres`.

**Comment by ahundt** [comment]
@dpo is a pull request really required? couldn't just re-running the bot take care of it?

**Comment by dpo** [comment]
It's a PR that will run the bot. The bottles need to be rebuilt apparently.

**Comment by ahundt** [comment]
yeah that's right, but no actual source needs to change I think?

**Comment by davesque** [comment]
What's the status on this?  I think I'm having issues building with ceres and cmake because of this.
