### ISSUE TITLE
tRNAscan error: 404 Not Found Error: Failed to download resource "trnascan"

### ISSUE THREAD

**Issue by nextgenusfs** [Homebrew/homebrew-science#3463]
`brew install trnascan` failed due to the url being dead, seems like trnascan is no longer hosted at janelia?  
```
==> Installing trnascan from homebrew/science
==> Downloading http://selab.janelia.org/software/tRNAscan-SE/tRNAscan-SE.tar.Z

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "trnascan"
Download failed: http://selab.janelia.org/software/tRNAscan-SE/tRNAscan-SE.tar.Z
```

**Comment by nextgenusfs** [comment]
I looked around a little bit more and it seems the Eddy lab website as moved, tRNAscan-SE can be found here: http://eddylab.org/software/tRNAscan-SE/tRNAscan-SE.tar.Z

And the homepage is now:
http://eddylab.org/software.html

**Comment by tseemann** [comment]
@nextgenusfs thanks for letting us know! i'm making a new formula: https://github.com/Homebrew/homebrew-science/pull/3479
