### ISSUE TITLE
Jenkins (bot.brew.sh) sporadically fails

### ISSUE THREAD

**Issue by heinemml** [Homebrew/homebrew-science#3476]
Jenkins builds seem to fail sporadically on `brew doctor`

What did I do?

* I added pull request #3460 and Jenkins ran successfully for all platforms.
* I changed some things and the Jenkins build failed when executing `brew doctor` (http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/4383/). 
* I changed the comment on the commit and pushed again, changing nothing in the commit itself. The build ran successfully. (http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/4384/)

I posted the results of the 2nd and the 3rd run here: https://gist.github.com/heinemml/3982bd3de43bc8472520

Since it fails before building anything I think this is a general issue. Is this known?

**Comment by dpo** [comment]
Those are sporadic failures. The build just needs to be restarted when they happen. I'm not sure what they're due to. Feel free to report on Homebrew/core.

**Comment by heinemml** [comment]
Is there a way for me as non-admin to restart the build? Or ist amend/force-push the only way for me?

I will open an issue at core.

**Comment by dpo** [comment]
Adding a commit to your PR will fire up a new build. Or you can ping one of us to do it manually.

**Comment by dpo** [comment]
I'll close this. Please reopen if there's anything that can be done here.
