### ISSUE TITLE
seqan missing cmake module, pkg-config file?

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-science#3502]
Received an email:

> Dear Tim,
> you previously contacted us about Seqan and homebrew. I just wanted to write
> that I looked at the formula and I think that you are currently not installing
> the FindSeqAn.cmake module and the pkgconfig-file (the latter is new since
> 2.1.1).
> Could you add those to the next releases? Thanks!
> [...]
> Thank you,
> Hannes Hauswedell

**Comment by ilovezfs** [comment]
Should be fixed now.
