### ISSUE TITLE
blast failed to install - Prokka 

### ISSUE THREAD

**Issue by maculatus** [Homebrew/homebrew-science#3508]
I tried to install prokka but if failed during the installation of blast and ncbi-blast. I brew update my system and it is updated to today (06/04/2016) 

brew install prokka
==> Installing prokka from homebrew/science
==> Installing dependencies for homebrew/science/prokka: blast, infernal,
==> Installing homebrew/science/prokka dependency: blast
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-
Already downloaded: /home/gybazeta/.cache/Homebrew/blast-2.2.31.tar.gz
==> Patching
patching file c++/include/corelib/ncbimtx.inl
==> ./configure --prefix=/mnt/data/Programs/.linuxbrew/Cellar/blast/2.2.31_1 --l
==> make
Last 15 lines from /home/gybazeta/.cache/Homebrew/Logs/blast/02.make:
                                        ^
compilation terminated.
make[3]: **\* [test_boost.o] Error 1
make[3]: Leaving directory `/tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
FAILED: src/corelib/Makefile.test_boost.lib
make[3]: Entering directory`/tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
/bin/rm -f libtest_boost.a .test_boost.dep .libtest_boost.a.stamp
/bin/rm -f /tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libtest_boost.a /tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.test_boost.dep \
        /tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libtest_boost-static.a /tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.test_boost-static.dep
make[3]: Leaving directory `/tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
make[2]: *** [all.nonusr] Error 2
make[2]: Leaving directory`/tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/corelib'
make[1]: **\* [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast20160406-26774-1osf55r/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build'
make: **\* [all] Error 2

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-science/issues
### Brew doctor

We will consider your request but it may be closed if it's something we're not actively planning to work on.
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_\* vars can break dynamic linking.
Set variables:
    LD_LIBRARY_PATH: /mnt/data/Programs/.linuxbrew/lib64:/mnt/data/Programs/.linuxbrew/lib:

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/htslib/faidx.h
    /usr/local/include/htslib/khash.h
    /usr/local/include/htslib/hfile.h
    /usr/local/include/htslib/vcf_sweep.h
    /usr/local/include/htslib/hts_defs.h
    /usr/local/include/htslib/kseq.h
    /usr/local/include/htslib/klist.h
    /usr/local/include/htslib/synced_bcf_reader.h
    /usr/local/include/htslib/khash_str2int.h
    /usr/local/include/htslib/bgzf.h
    /usr/local/include/htslib/hts.h
    /usr/local/include/htslib/kstring.h
    /usr/local/include/htslib/tbx.h
    /usr/local/include/htslib/ksort.h
    /usr/local/include/htslib/vcfutils.h
    /usr/local/include/htslib/regidx.h
    /usr/local/include/htslib/vcf.h
    /usr/local/include/htslib/sam.h
    /usr/local/include/htslib/knetfile.h
    /usr/local/include/htslib/kfunc.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/htslib.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libhts.a

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
    /mnt/data/nanopore-paper-analysis-master/wgs-8.2/Linux-amd64/bin/
    /mnt/data/nanopore-paper-analysis-master/samtools/
    /mnt/data/nanopore-paper-analysis-master/wgs-8.2/Linux-amd64/bin/
    /mnt/data/nanopore-paper-analysis-master/samtools/

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

```
brew install openblas
```

Run `brew missing` for more details.

**Comment by maculatus** [comment]
brew missing

homebrew/science/gubbins: openblas
homebrew/python/numpy: openblas

**Comment by tseemann** [comment]
Try
```
brew install blast --without-check --without-static`
```
before you install Prokka.

**Comment by maculatus** [comment]
Thanks, however it failed again...
brew install blast --without-check -without-static
==> Installing blast from homebrew/science
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-
Already downloaded: /home/gybazeta/.cache/Homebrew/blast-2.2.31.tar.gz
==> Patching
patching file c++/include/corelib/ncbimtx.inl
==> ./configure --prefix=/mnt/data/Programs/.linuxbrew/Cellar/blast/2.2.31_1 --l
==> make
Last 15 lines from /home/gybazeta/.cache/Homebrew/Logs/blast/02.make:
make[4]: *** [seqfeat__.o] Error 1
make[4]: Leaving directory `/tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/objects/seq'
FAILED: src/objects/seq/Makefile.seq.lib
make[4]: Entering directory `/tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/objects/seq'
/bin/rm -f libseq.a .seq.dep .libseq.a.stamp
/bin/rm -f /tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libseq.a /tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.seq.dep \
	    /tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/lib/libseq-static.a /tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/status/.seq-static.dep
make[4]: Leaving directory `/tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/objects/seq'
make[3]: *** [all.nonusr] Error 2
make[3]: Leaving directory `/tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/objects/seq'
make[2]: *** [all_r.real] Error 5
make[2]: Leaving directory `/tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build/objects'
make[1]: *** [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast20160411-5972-wu5rf5/ncbi-blast-2.2.31+-src/c++/ReleaseMT/build'
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-science/issues

**Comment by ilovezfs** [comment]
Please try
````
brew pull https://github.com/Homebrew/homebrew-science/pull/3537
brew install --build-from-source -dv blast
```

**Comment by maculatus** [comment]
Hello,
Thanks for your email. I tried the command and the patch failed to apply.
It is asking my for an identification.

When I tried to identified my self using:
git config --global "My email"
I got:
error: invalid key: "My email"

**Comment by ilovezfs** [comment]
You can do this instead
```
cd ~/.linuxbrew/Library/Taps/homebrew/homebrew-science
git fetch ilovezfs
git merge ilovezfs/blast-2.3.0
brew install --build-from-source -dv blast
```

**Comment by ilovezfs** [comment]
Saw you're on OS X like me.
```
cd /usr/local/Library/Taps/homebrew/homebrew-science
```

Otherwise, the same as above.

**Comment by maculatus** [comment]
Nope, I have a linux box.
cd  ~/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science
>git fetch ilovezfs
#got this:

fatal: 'ilovezfs' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by ilovezfs** [comment]
git remote add ilovezfs git://github.com/ilovezfs/homebrew-science.git

**Comment by ilovezfs** [comment]
@maculatus did you get it working?

FYI:
```
==> Summary
/home/openzfs/.linuxbrew/Cellar/blast/2.3.0: 346 files, 881.4M, built in 104 minutes 36 seconds
```

**Comment by maculatus** [comment]
git remote add ilovezfs git://github.com/ilovezfs/homebrew-science.git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by ilovezfs** [comment]
@maculatus you have to be in the tap directory

**Comment by maculatus** [comment]
It worked, blast was installed. However, in the process of installing boost my device run out of space. I checked with df and is plenty of free space. I am going to check this with our IT department.
Thanks

 git fetch ilovezfs
remote: Counting objects: 15674, done.
remote: Compressing objects: 100% (6777/6777), done.
remote: Total 15674 (delta 9795), reused 14748 (delta 8870), pack-reused 0
Receiving objects: 100% (15674/15674), 4.00 MiB | 408.00 KiB/s, done.
Resolving deltas: 100% (9795/9795), completed with 531 local objects.
From git://github.com/ilovezfs/homebrew-science
 * [new branch]      blast-2.3.0 -> ilovezfs/blast-2.3.0
 * [new branch]      delly-0.7.2 -> ilovezfs/delly-0.7.2
 * [new branch]      gh-pages   -> ilovezfs/gh-pages
 * [new branch]      master     -> ilovezfs/master
 * [new branch]      mlst-2.4   -> ilovezfs/mlst-2.4
 * [new branch]      tbl2asn-24.9 -> ilovezfs/tbl2asn-24.9
 * [new tag]         2014-01    -> 2014-01
 * [new tag]         2014-02    -> 2014-02
 * [new tag]         2014-03    -> 2014-03
 * [new tag]         2014-04    -> 2014-04
 * [new tag]         2014-05    -> 2014-05
 * [new tag]         2014-06    -> 2014-06
 * [new tag]         2014-07    -> 2014-07
 * [new tag]         2014-08    -> 2014-08
 * [new tag]         2014-09    -> 2014-09
 * [new tag]         2014-10    -> 2014-10
 * [new tag]         2014-11    -> 2014-11
 * [new tag]         2014-12    -> 2014-12
 * [new tag]         2015-01    -> 2015-01
 * [new tag]         2015-02    -> 2015-02
 * [new tag]         2015-03    -> 2015-03
 * [new tag]         2015-04    -> 2015-04
 * [new tag]         2015-05    -> 2015-05
 * [new tag]         2015-06    -> 2015-06
gybazeta@mint1 ~/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science $ git merge/blast-2.3.0
git: 'merge/blast-2.3.0' is not a git command. See 'git --help'.
gybazeta@mint1 ~/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science $ git merge ilovezfs/blast-2.3.0
Updating e70dfb4..30246cd
Fast-forward
 blast.rb | 109 +++++++++++++++++++++++++++++++++++++++++----------------------
 mlst.rb  |  15 +++++----
 2 files changed, 80 insertions(+), 44 deletions(-)
gybazeta@mint1 ~/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science $ brew install --build-from-source -dv blast
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science/blast.rb
==> Installing blast from homebrew/science
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/jpeg.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/libpng.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/xz.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/zlib.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/pcre.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/bzip2.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/freetype.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/gnutls.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science/hdf5.rb
/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/lzo.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /mnt/data/Programs/.linuxbrew/Library/Taps/homebrew/homebrew-science/blast.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/jpeg.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/libpng.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/zlib.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/pcre.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/bzip2.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/xz.rb
/mnt/data/Programs/.linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/python.rb
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.3.0/ncbi-blast-2.3.0+-src.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.3.0-0; x86_64-linux) ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.3.0/ncbi-blast-2.3.0+-src.tar.gz -C 0 -o /home/gybazeta/.cache/Homebrew/blast-2.3.0.tar.gz.incomplete --connect-timeout 5
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.3M  100 18.3M    0     0   791k      0  0:00:23  0:00:23 --:--:--  718k
==> Verifying blast-2.3.0.tar.gz checksum
tar xf /home/gybazeta/.cache/Homebrew/blast-2.3.0.tar.gz
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
==> Downloading from http://nbtelecom.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.3.0-0; x86_64-linux) http://nbtelecom.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2 -C 0 -o /home/gybazeta/.cache/Homebrew/blast--boost158-1.58.0.tar.bz2.incomplete
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67.1M  100 67.1M    0     0   395k      0  0:02:54  0:02:54 --:--:--  586k
==> Verifying blast--boost158-1.58.0.tar.bz2 checksum
tar xf /home/gybazeta/.cache/Homebrew/blast--boost158-1.58.0.tar.bz2
tar: boost_1_58_0/boost/bimap/relation/detail/to_mutable_relation_functor.hpp: Cannot write: No space left on device
tar: boost_1_58_0/boost/bimap/relation/member_at.hpp: Cannot write: No space left on device
tar: boost_1_58_0/boost/bimap/relation/mutant_relation.hpp: Cannot write: No space left on device
tar: boost_1_58_0/boost/bimap/relation/pair_layout.hpp: Cannot write: No space left on device
tar: boost_1_58_0/boost/bimap/relation/structured_pair.hpp: Cannot write: No space left on device
tar: boost_1_58_0/boost/bimap/relation/support: Cannot mkdir: No space left on device
tar: boost_1_58_0/boost/bimap/relation/support: Cannot mkdir: No space left on device
tar: boost_1_58_0/boost/bimap/relation/support/data_extractor.hpp: Cannot open: No such file or directory
tar: boost_1_58_0/boost/bimap/relation/support: Cannot mkdir: No space left on device
tar: boost_1_58_0/boost/bimap/relation/support/get.hpp: Cannot open: No such file or directory
tar: boost_1_58_0/boost/bimap/relation/support: Cannot mkdir: No space left o No such file or directory
tar: boost_1_58_0/doc: Cannot mkdir: No space left on device
tar: boost_1_58_0/doc/html/images/accumulators/inherit_graph_1.png: Cannot open: No such file or directory
tar: boost_1_58_0/doc: Cannot mkdir: No space left on device
tar: boost_1_58_0/doc/html/images/accumulators/inherit_graph_10.png: Cannot open: No such file or directory
(...)

**Comment by ilovezfs** [comment]
@maculatus You probably just need to set the brew temporary directory to somewhere where's there's space:
```
openzfs@openzfs ~ $ cat .brewprofile 
export HOMEBREW_EDITOR=vi
export PATH=/home/openzfs/.linuxbrew/bin:$PATH
export HOMEBREW_TEMP=~/tmp
```

**Comment by ilovezfs** [comment]
echo 'export HOMEBREW_TEMP=~/tmp >> ~/.bash_profile' will probably fix it.

**Comment by maculatus** [comment]
...but df indicates plenty of space...do I need to identify an specific space for Home-brew?

Filesystem                             1K-blocks        Used   Available Use% Mounted on
/dev/vda1                              264091652    53010936   197642612  22% /mnt/data

**Comment by ilovezfs** [comment]
@maculatus I think the default is probably your tmpfs which too small.

**Comment by maculatus** [comment]
Thanks, I changed my profile and it is "pouring" boost now...

**Comment by maculatus** [comment]
It failed again...

/mnt/data/Programs/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /mnt/data/Programs/.linuxbrew/Library/Formula/lzo.rb
Error: No such file or directory @ dir_s_mkdir - /home/gybazeta/tmp/homebrew20160413-3383-1pz44l8
/mnt/data/Programs/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
/mnt/data/Programs/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
/mnt/data/Programs/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
/mnt/data/Programs/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/formula_installer.rb:611:in `build'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/formula_installer.rb:232:in `install'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/cmd/install.rb:232:in `install_formula'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/mnt/data/Programs/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/mnt/data/Programs/.linuxbrew/Library/brew.rb:83:in `<main>'

**Comment by ilovezfs** [comment]
try without the tests
`brew install --build-from-source --without-test blast`

**Comment by maculatus** [comment]
Thanks, it worked. I continued with the prokka installation and all the other programs were installed (barrnap, minced, parallel, tbl2asn, prodigal, aragorn, hmmer, infernal and blast) but prokka is failing to download
brew install prokka
==> Installing prokka from homebrew/science
==> Downloading http://www.vicbioinformatics.com/prokka-1.11.tar.gz
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/curl: /mnt/data/Programs/.linuxbrew/lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
########################                                                  33.7%
curl: (23) Failed writing body (2627 != 8688)
Error: Failed to download resource "prokka"
Download failed: http://www.vicbioinformatics.com/prokka-1.11.tar.gz

**Comment by tseemann** [comment]
@maculatus That server had catastrophic disk failure a few days ago - it has been restored by @drpowell.

However, I recommend now `brew reinstall prokka --HEAD` to get the latest version from GitHub. it has many many bug fixes.

**Comment by maculatus** [comment]
Thanks! I was able to install prokka. I have some issues with space and I have to redirect my cache to a place with more space. After that the prokka installed without problem
Cheers

**Comment by michaelbarton** [comment]
Could you provide an update on this issue is this now fixed? I currently get the following error:

```
brew install --build-from-source --without-test blast
.
.
.
configure: loading site script ./src/build-system/config.site

configure: creating cache config.cache
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... /home/linuxbrew/.linuxbrew/bin/gcc
checking for C compiler default output file name... configure: error: C compiler cannot create executables
See `config.log' for more details.
```

**Comment by maculatus** [comment]
Yes, the issue was resolved. I have not upgrade my homebrew since last week.

**Comment by michaelbarton** [comment]
I'm currently getting an error, has something changed in the mean time? I am unable to build blast from source. When using the bottled version I get the errror:

```
[22:34:51] Looking for 'makeblastdb' - found /home/linuxbrew/.linuxbrew/bin/makeblastdb
makeblastdb: error while loading shared libraries: libblastinput.so: cannot open shared object file: No such file or directory
[22:34:51] Could not determine version of makeblastdb - please install version 2.2 or higher
Warning: The post-install step did not complete successfully
```

**Comment by iMichka** [comment]
I just tested the installation of prokka. A lot of version updates have been made meanwhile, and everything is now provided as bottles. Seems to work well.

Please open a new issue if you have still problems with this (and fill out the issue template). Thanks.
