### ISSUE TITLE
Travis builds of pull requests are broken

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3510]
See for example https://travis-ci.org/sjackman/homebrew-science/builds/121238071

https://travis-ci.org/sjackman/homebrew-science/jobs/121238075#L194-L200
```
==> git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
==> PASSED
Error: Formulae found in multiple taps: 
 * homebrew/science/hdf5
 * sjackman/science/hdf5
```

**Comment by dpo** [comment]
I get the same on my fork.

**Comment by sjackman** [comment]
I believe this was happening because Travis tests were enabled for my fork `sjackman/homebrew-science`. I didn't even realize builds of my fork were enabled. I've disabled Travis for my fork.
