### ISSUE TITLE
lammps: Missing files

### ISSUE THREAD

**Issue by KingGeorgeWang** [Homebrew/homebrew-science#3518]
Hi all,

I have an issue while installing Lammps on OS X 10.11.4.

Some files may be lost during the installing procedure. Here is the detail.

```
KunWangdeMacBook-Air:~ george$ ls -a /usr/local/share/lammps
.       ..      bench       doc     examples             potentials tools

```

And the procedure is shown below.

```
KunWangdeMacBook-Air:~ george$  brew install homebrew/science/lammps
==> Installing lammps from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/lammps-2015.02.10_2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lammps-2015.02.10_2.el_capitan.bottle.tar.gz
==> Caveats
You should run a benchmark test or two. There are plenty available.

  cd /usr/local/share/lammps/bench
  lammps -in in.lj
  # with mph
  mpiexec -n 2 lammps -in in.lj

The following directories could come in handy

  Documentation:
  /usr/local/share/lammps/doc/Manual.html

  Potential files:
  /usr/local/share/lammps/potentials

  Python examples:
  /usr/local/share/lammps/python-examples

  Additional tools (may require manual installation):
  /usr/local/share/lammps/tools

To use the Python module with Python, you may need to amend your
PYTHONPATH like:
  export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

==> Summary
🍺  /usr/local/Cellar/lammps/2015.02.10_2: 3,687 files, 154M
```

I'm curious where can I find the folder "src". Thanks for your help!

**Comment by dpo** [comment]
What folder `src`? After installing, it's discarded.

**Comment by KingGeorgeWang** [comment]
Thanks for your reply! @dpo 
But according to the Manual, there should be the folder `src` under the `lammps` dir, and without folder `src`, I cannot use the Makefile.mpi or Makefile.serial files in src/MAKE. (which seems to be important in the following steps) 

Here's what Manual says about `Lammps` dir:

> When you download a LAMMPS tarball you will need to unzip and untar the downloaded file with the following commands, after placing the tarball in an appropriate directory.

gunzip lammps*.tar.gz 
tar xvf lammps*.tar 
This will create a LAMMPS directory containing two files and several sub-directories:

README	  text file
LICENSE	  the GNU General Public License (GPL)
bench	  benchmark problems
doc	          documentation
examples  simple test problems
potentials  embedded atom method (EAM) potential files
src	         source files
tools	 pre- and post-processing tools
Note that the download page also has links to download Windows exectubles and installers, as well as pre-built executables for a few specific Linux distributions. **It also has instructions for how to download/install LAMMPS for Macs (via Homebrew)**, and to download and update LAMMPS from SVN and Git repositories, which gives you the same files that are in the download tarball.

Hope for your early reply~

**Comment by dpo** [comment]
I'm a bit confused. Homebrew has already gone through the entire installation procedure for you. LAMMPS is ready to be used. Try `brew test lammps`.

**Comment by KingGeorgeWang** [comment]
Thanks for your reply! @dpo 

The problem is that after installation the dir `lammps` is different from what Manual says. (missing dir `src`, etc. ) You've said that

> After installing, it's discarded.

But it seems that `src` shouldn't be deleted since it will be used in the further calculation. And in Windows system folder `src` can be found after installing Lammps. So I wonder what mistake I've made.

And I've tried the command you told me. Here's the result:
`KunWangdeMacBook-Air:~ george$ brew test lammps`
`Testing homebrew/science/lammps`
`==> Using the sandbox`
`==> lammps -in /usr/local/share/lammps/bench/in.lj`
`==> python -c from lammps import lammps ; lammps().file('/usr/local/share/lammps`

By the way, I copied the folder `src` from installation package for Windows, and that seems to work. (At present LOL)

**Comment by dpo** [comment]
The output from `brew test lammps` seems normal. Could you provide a link to the part of the manual you are referring to?

**Comment by KingGeorgeWang** [comment]
Thanks for your reply! @dpo

Here is the link of the manual:

> http://lammps.sandia.gov/doc/Section_start.html#start-1

The quotation is from the section

> 2.1. What’s in the LAMMPS distribution

(PS. The installation package for Windows seemed incompatible on Mac /sad )

**Comment by KingGeorgeWang** [comment]
By the way, here's the screenshot of what dir `Lammps` contains in my Mac. @dpo 

![2016-04-24 16 01 23](https://cloud.githubusercontent.com/assets/18363288/14766288/ec48cb64-0a35-11e6-9441-63c54810bcdc.png)

**Comment by iMichka** [comment]
We are distribution version 2016.11.17. If this does not solve your problem, please open a new issue. You may also double-check with upstream if the manual is up to date, or if there are some changes to be made to formula to get this to work. Thanks.
