### ISSUE TITLE
GDCM 2.6.3 compiled with VTK 6 (possibly 7) formula

### ISSUE THREAD

**Issue by tfmoraes** [Homebrew/homebrew-science#3525]
Hi,

I updated the gdcm formula to 2.6.3 version. Also, I adapted it to compile with VTK 6 (possibly with 7). I had to apply some patches, because gdcm is not adapted to compile with VTK 6. I submitted a pull request to gdcm repo with these patches. The formula is here https://gist.github.com/tfmoraes/f780c5c46f2fdd5a87eca8d7fbdac9e6 and the patches https://gist.github.com/tfmoraes/5489a2473c1ed6cc296aa646432a8536

Thanks.

**Comment by dpo** [comment]
Feel free to submit a pull request.

**Comment by tfmoraes** [comment]
Ok. Pull request submitted.
