### ISSUE TITLE
trinity: Fails to build with GCC 5

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3527]
https://gist.github.com/sjackman/fb183909c1469102bff8b78215f9450e#file-01-make-L40
```
g++-5 -DHAVE_CONFIG_H -I. -I..    -std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -I/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/include/darwin -fopenmp -MT sequenceUtil.o -MD -MP -MF .deps/sequenceUtil.Tpo -c -o sequenceUtil.o sequenceUtil.cpp
sequenceUtil.cpp: In function 'std::__cxx11::string read_sequence_from_file(std::__cxx11::string)':
sequenceUtil.cpp:55:18: error: no match for 'operator==' (operand types are 'std::ifstream {aka std::basic_ifstream<char>}' and 'int')
   if (fileReader == 0) { // couldn't open file
```

**Comment by sjackman** [comment]
Bumped `trinity` to version `2.2.0`. New error:
```
gcc -g -Wall -O2 -o bamcheck bamcheck.o -L.. -lm -lbam -lpthread -lz
Undefined symbols for architecture x86_64:
  "_bam_aux2i", referenced from:
      _collect_stats in bamcheck.o
```
https://gist.github.com/sjackman/ef765ef28e168496aa025c32d2319e55#file-01-make-L1071

**Comment by sjackman** [comment]
See also #2801 and #2913

**Comment by ilovezfs** [comment]
@sjackman This is fixed by https://github.com/Homebrew/homebrew-science/pull/3540

**Comment by baumeist** [comment]
Hi @sjackman,
It appears my issue was related to using gcc 5 and that it has been resolved. Can you please tell me if I need to reinstall Trinity now? I'm not sure how to resolve the build issue I'm having.
Thanks for your help.

**Comment by sjackman** [comment]
@baumeist Try `brew update && brew upgrade && brew install trinity`
