### ISSUE TITLE
would you accept the following admb formula 

### ISSUE THREAD

**Issue by joethorley** [Homebrew/homebrew-science#3542]
I'm willing to submit the following formula for ADMB as a pull request.
```
class Admb < Formula
  desc "AD Model Builder"
  homepage "http://www.admb-project.org"
  url "https://github.com/admb-project/admb/releases/download/admb-11.5/admb-11.5-src.zip"
  sha256 "bd522d9478156f4640dfcd77fb35e3e009dc94f011620ea4b588ffffb852115f"

  def install
    system "make"
    system "mv build/dist/* #{prefix}"
  end

  test do
    system "admb", "--help"
  end
end
```

It works on El Capitan with three seeminly minor audit problems

```
Joes-iMac:bin joe$ brew audit --strict --online admb
==> brew style admb

1 file inspected, no offenses detected

==> audit problems
admb:
 * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
 * Use the `mv` Ruby method instead of `system "mv `
 * Non-executables were installed to "/usr/local/Cellar/admb/11.5/bin"
The offending files are:
  /usr/local/Cellar/admb/11.5/bin/admb-cfg.sh
  /usr/local/Cellar/admb/11.5/bin/seddf1b2
  /usr/local/Cellar/admb/11.5/bin/seddf1b2dll
  /usr/local/Cellar/admb/11.5/bin/seddf1b3
  /usr/local/Cellar/admb/11.5/bin/seddf1b3dll
  /usr/local/Cellar/admb/11.5/bin/seddf1b4
  /usr/local/Cellar/admb/11.5/bin/sedf1b2a
  /usr/local/Cellar/admb/11.5/bin/sedf1b2c
  /usr/local/Cellar/admb/11.5/bin/sedf1b2c2
  /usr/local/Cellar/admb/11.5/bin/sedf1b2d

Error: 3 problems in 1 formula
```
Would you accept it? Does it need any modifications?

**Comment by dpo** [comment]
Seems interesting. I'm not worried about the "not notable enough" comment. Scientific packages often don't get starred as other packages do. But please address the `mv` issue. The non-executables in `bin` are also annoying. Do those files really have to be in `bin` when you run the code or can they be relocated? Does `admb` have a `make install`?

**Comment by joethorley** [comment]
Can you point me to an example with the Ruby mv method?

**Comment by dpo** [comment]
It should just be something like
```ruby
mv Dir["build/dist/*"], prefix
```
See, e.g, [here](https://github.com/Homebrew/homebrew-science/blob/master/asl.rb#L38) and [here](https://github.com/Homebrew/homebrew-science/blob/master/asl.rb#L42).

**Comment by joethorley** [comment]
That got rid of the mv comment.
I couldn't get a `make install` working but I'm far from an expert on these matters.
This is about as far as I can take it.
Can I do a pull request with what I have?

**Comment by dpo** [comment]
Well, only you will be able to change your pull request, so it would be great to know that you're very comfortable with the software you're submitting a PR for ;-).

**Comment by joethorley** [comment]
I'm comfortable enough with it and think it represents a substantial improvement over the current state of affairs - I'll submit a PR in the next 24 hours

**Comment by dpo** [comment]
See #3554.
