### ISSUE TITLE
suite-sparse failing --with-tbb on Linux

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#3543]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

- Brief summary of issue:

I tried installing suite-sparse with linuxbrew again on ubuntu 14.04 and it is still failing, here is a previous related issue:
https://github.com/Homebrew/homebrew-science/issues/2648

- Please state the complete command that you issued.

brew install suite-sparse
- Please do not post lengthy build output here. Instead provide a link to a gist.
- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).

https://gist.github.com/4ece9ffc0a110e9ecbbe140f5a58fa4a

**Comment by dpo** [comment]
Does it build `--without-tbb`?

**Comment by ahundt** [comment]
looks like it may just be linker errors when using `--without-tbb`, though still broken.

https://gist.github.com/047da4b674c6f170cde2950bcec5d521

```
brew tap homebrew/science
brew install suite-sparse --without-tbb
```

**Comment by dpo** [comment]
Doesn't look like you installed BLAS and LAPACK Ubuntu packages. Use apt. Or else build `--with-openblas`.

**Comment by ahundt** [comment]
Perhaps that info should be printed as a warning/note? It would be cool to find this out easily when compared to raw compiler errors!

the following worked for me:
`brew install suite-sparse --without-tbb --with-openblas`

**Comment by dpo** [comment]
That's probably something to think about in Linuxbrew. OSX ships with a BLAS and LAPACK, while Linux doesn't.

**Comment by ahundt** [comment]
fair enough, at least I can install it now, moved to https://github.com/Linuxbrew/linuxbrew/issues/1075. Thanks!

**Comment by sjackman** [comment]
I'm reopening this issue because I'm seeing the same error compiling with `tbb` as mentioned above. @ahundt was using GCC 4.8, and I'm using Homebrewed GCC 5.

I had `suite-sparse` 4.2.1 and 4.4.4_2 installed on this machine with default options. I haven't looked into what's changed since then.

Either `--with-tbb` can be fixed for Linuxbrew, or the default options on Linux could be changed to `--without-tbb --with-openmp`.

**Comment by sjackman** [comment]
https://gist.github.com/sjackman/5005e63c4eaf263b312a772b39280fcf#file-01-make-L1949
```
ranlib libspqr.a
spqr_parallel.o: In function `spqr_zippy<double>::execute()':
spqr_parallel.cpp:(.text._ZN10spqr_zippyIdE7executeEv[_ZN10spqr_zippyIdE7executeEv]+0x81): undefined reference to `tbb::internal::allocate_child_proxy::allocate(unsigned long) const'
spqr_parallel.cpp:(.text._ZN10spqr_zippyIdE7executeEv[_ZN10spqr_zippyIdE7executeEv]+0xc9): undefined reference to `tbb::task::spawn_and_wait_for_all(tbb::task_list&)'
spqr_parallel.o: In function `spqr_zippy<double>::~spqr_zippy()':
spqr_parallel.cpp:(.text._ZN10spqr_zippyIdED0Ev[_ZN10spqr_zippyIdED5Ev]+0x1): undefined reference to `operator delete(void*)'
```

**Comment by dpo** [comment]
Does it work if you apply [this patch](https://gist.github.com/8bbf739ac4ac9fd9e7afda5a2648a1a7)?

**Comment by dpo** [comment]
See #3578

**Comment by sjackman** [comment]
`brew install suite-sparse --with-openmp --without-tbb` worked.
I'm testing #3578 now. Thanks for the patch, Dominique.

**Comment by dpo** [comment]
It fixed the first two issues, but others remain.

**Comment by sjackman** [comment]
Many fewer error this time though:
```
/gsc/btl/linuxbrew/bin/gcc-5 -L/gsc/btl/linuxbrew/lib -Wl,--dynamic-linker=/gsc/btl/linuxbrew/lib/ld.so -Wl,-rpath,/gsc/btl/linuxbrew/lib -L/var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib -L/var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib -L/var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib -L/var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib -shared -Wl,-soname -Wl,libspqr.so.2 -Wl,--no-undefined spqr_rmap.o SuiteSparseQR_C.o SuiteSparseQR_expert.o spqr_parallel.o spqr_kernel.o spqr_analyze.o spqr_assemble.o spqr_cpack.o spqr_csize.o spqr_fcsize.o spqr_debug.o spqr_front.o spqr_factorize.o spqr_freenum.o spqr_freesym.o spqr_freefac.o spqr_fsize.o spqr_maxcolnorm.o spqr_rconvert.o spqr_rcount.o spqr_rhpack.o spqr_rsolve.o spqr_stranspose1.o spqr_stranspose2.o spqr_hpinv.o spqr_1fixed.o spqr_1colamd.o SuiteSparseQR.o spqr_1factor.o spqr_cumsum.o spqr_shift.o spqr_happly.o spqr_panel.o spqr_happly_work.o SuiteSparseQR_qmult.o spqr_trapezoidal.o spqr_larftb.o spqr_append.o spqr_type.o spqr_tol.o -o /var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib/libspqr.so.2.0.5 -lm -lrt -Wl,-rpath=/var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib -lamd -lcolamd -lcholmod -lsuitesparseconfig -L/gsc/btl/linuxbrew/opt/tbb/lib -ltbb -lblas -llapack -lblas -llapack
spqr_parallel.o: In function `spqr_zippy<double>::~spqr_zippy()':
spqr_parallel.cpp:(.text._ZN10spqr_zippyIdED0Ev[_ZN10spqr_zippyIdED5Ev]+0x1): undefined reference to `operator delete(void*)'
spqr_parallel.o: In function `spqr_zippy<std::complex<double> >::~spqr_zippy()':
spqr_parallel.cpp:(.text._ZN10spqr_zippyISt7complexIdEED0Ev[_ZN10spqr_zippyISt7complexIdEED5Ev]+0x1): undefined reference to `operator delete(void*)'
spqr_parallel.o:(.data.rel.ro._ZTI10spqr_zippyIdE[_ZTI10spqr_zippyIdE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
spqr_parallel.o:(.data.rel.ro._ZTI10spqr_zippyISt7complexIdEE[_ZTI10spqr_zippyISt7complexIdEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
spqr_parallel.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
Makefile:246: recipe for target '/var/tmp/sjackman/suite-sparse20160420-143026-lycfli/SuiteSparse/lib/libspqr.so.2.0.5' failed
```

**Comment by sjackman** [comment]
I think it's failing because it's linking a C++ solib using `gcc-5` rather than `g++-5`.

**Comment by dpo** [comment]
The `operator` stuff appears related to CUDA. I'll try disabling that.

> I think it's failing because it's linking a C++ solib using gcc-5 rather than g++-5.

On OSX, it uses clang and not clang++ and somehow it works, but then again, it's a mystery how it found `libtbb` before the patch.

**Comment by sjackman** [comment]
Changing `gcc-5` to `g++-5` in the above command using `brew instal --debug` does fix that particular linking error.

**Comment by sjackman** [comment]
The error message that I see now is:
```
/gsc/btl/linuxbrew/bin/g++-5 -Os -w -pipe -march=core2 -isystem/gsc/btl/linuxbrew/include  -O3 -fexceptions -fPIC -fopenmp    -I../../include   qrdemo.cpp -o qrdemo -L/gsc/btl/linuxbrew/lib -Wl,--dynamic-linker=/gsc/btl/linuxbrew/lib/ld.so -Wl,-rpath,/gsc/btl/linuxbrew/lib -L/var/tmp/sjackman/suite-sparse20160420-13786-5xiweh/SuiteSparse/lib -L/var/tmp/sjackman/suite-sparse20160420-13786-5xiweh/SuiteSparse/lib -L/var/tmp/sjackman/suite-sparse20160420-13786-5xiweh/SuiteSparse/lib -L../../lib -lspqr -lsuitesparseconfig -lcholmod -lamd -lcolamd -lccolamd -lcamd -lmetis  -lm -lrt -Wl,-rpath=/var/tmp/sjackman/suite-sparse20160420-13786-5xiweh/SuiteSparse/lib -llapack -lopenblas  
qrdemo.cpp:8:29: fatal error: SuiteSparseQR.hpp: No such file or directory
compilation terminated.
Makefile:176: recipe for target 'qrdemo' failed
make[2]: *** [qrdemo] Error 1
make[2]: Leaving directory '/var/tmp/sjackman/suite-sparse20160420-13786-5xiweh/SuiteSparse/SPQR/Demo'
```

**Comment by dpo** [comment]
[Here](https://travis-ci.org/Homebrew/homebrew-science/jobs/124585780) it worked, but the test fails because the libraries can't be found. I wonder if anyone has ever bothered to build SuiteSparse on Linux before!

**Comment by dpo** [comment]
Maybe related to https://github.com/Homebrew/homebrew-science/pull/3515#issuecomment-212136979?!

**Comment by sjackman** [comment]
I've built it twice on Linux before with no options. Versions 4.2.1 and 4.4.4_2.

**Comment by dpo** [comment]
Those versions didn't have shared libraries.

**Comment by sjackman** [comment]
Ah. That would explain it.

**Comment by dpo** [comment]
Does #3578 build for you? I don't have access to a Linux machine, so it's difficult to debug the test.

**Comment by sjackman** [comment]
Yes, it builds. `brew test suite-sparse` fails though.
```
$ brew test suite-sparse
Testing homebrew/science/suite-sparse
==> /gsc/btl/linuxbrew/bin/gcc-5 -o amd_demo -O /gsc/btl/linuxbrew/Cellar/suite-
Last 15 lines from /home/sjackman/.cache/Homebrew/Logs/suite-sparse/01.gcc-5:
2016-04-20 16:45:09 -0700

/gsc/btl/linuxbrew/bin/gcc-5
-o
amd_demo
-O
/gsc/btl/linuxbrew/Cellar/suite-sparse/4.5.1_1/share/suite-sparse/demo/AMD/amd_demo.c
-L/gsc/btl/linuxbrew/Cellar/suite-sparse/4.5.1_1/lib
-I/gsc/btl/linuxbrew/Cellar/suite-sparse/4.5.1_1/include
-lsuitesparseconfig
-lamd

/gsc/btl/linuxbrew/bin/ld: cannot find -lsuitesparseconfig
/gsc/btl/linuxbrew/bin/ld: cannot find -lamd
collect2: error: ld returned 1 exit status
```

**Comment by sjackman** [comment]
Perhaps I spoke too soon. It built successfully, but `$prefix/lib` is empty.

**Comment by dpo** [comment]
That would explain it ;-).

**Comment by dpo** [comment]
What did [this line](https://github.com/Homebrew/homebrew-science/pull/3578/files#diff-3b0bc9b28f67d5681f6abb5e9e99875fR79) do?

**Comment by dpo** [comment]
Do you have a gist for this last attempt? The Travis log doesn't show everything.

**Comment by sjackman** [comment]
Hi, @dpo. I think it's because `*.so` installs all the `.so` symlinks, but not the actual libraries, which are named `*.so.1.2.3` on Linux. The dead symlinks then get pruned. I think it's a silly naming scheme, but we're stuck with it. Try (untested)
```ruby
    lib.install Dir[OS.mac? ? "lib/*.dylib" : "lib/*.so*"]
```

**Comment by dpo** [comment]
Success: https://travis-ci.org/Homebrew/homebrew-science/jobs/124781828

**Comment by dpo** [comment]
I don't think the Travis images like BLAS libraries though: https://travis-ci.org/Homebrew/homebrew-science/jobs/124789335#L677

**Comment by schoeps** [comment]
> `lib.install Dir[OS.mac? ? "lib/*.dylib" : "lib/*.so*"]`

coming back to my comment in #3515; we might need to call `make install`? or is it now working for everyone but me? :)
