### ISSUE TITLE
HDF5 1.10.0 stable is out

### ISSUE THREAD

**Issue by aldanor** [Homebrew/homebrew-science#3544]
The 1.10.0 stable has been out for a few weeks now, wonder if it makes sense to have the recipe updated?

**Comment by dpo** [comment]
Sure, but there's a truckload of dependents to update along with it. An update of HDF5 typically breaks 5-10 other formulas. Try `brew uses hdf5` and you'll have an idea.

**Comment by iMichka** [comment]
Done with 918528e3e98999626c6650fc76407260c6c25214

Here is the list of formula which are currently being rebuilt: #5011
