### ISSUE TITLE
Vips 8.3 can't be installed (with GraphicsMagick)

### ISSUE THREAD

**Issue by winstonma** [Homebrew/homebrew-science#3558]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
==> ./configure --prefix=/usr/local/Cellar/vips/8.3.0 --with-magick --with-magickpackage=GraphicsMagick
==> make install
Last 15 lines from /Library/Logs/Homebrew/vips/02.make:
                read->image_info->scene = read->page;
                ~~~~~~~~~~~~~~~~  ^
magick2vips.c:227:21: error: no member named 'number_scenes' in 'struct _ImageInfo'
                read->image_info->number_scenes = 1;
                ~~~~~~~~~~~~~~~~  ^
magick2vips.c:229:21: error: no member named 'scenes' in 'struct _ImageInfo'
                read->image_info->scenes = strdup( page );
                ~~~~~~~~~~~~~~~~  ^

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue:
- Please state the complete command that you issued.
- Please do not post lengthy build output here. Instead provide a link to a gist.
- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by mywaystar** [comment]
I did brew uninstall vips and and brew install vips and it's worked

**Comment by felixbuenemann** [comment]
This is fixed in https://github.com/jcupitt/libvips/commit/23eaf93867cf73de691a9b68611d01664f30e8bd I'll make a PR.

**Comment by felixbuenemann** [comment]
@winstonma Could you append "with GraphicsMagick" to the issue title?

**Comment by winstonma** [comment]
@mywaystar I just did what you have mentioned and it works

@felixbuenemann Since the other way works so I will close this issue without testing
