### ISSUE TITLE
VTK forces the directory `.../include/python3.5m`

### ISSUE THREAD

**Issue by michiexile** [Homebrew/homebrew-science#3577]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [?] Looked up the software bug tracker if reporting a build error?
- [NA] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

Building VTK 7.0.0 fails with Python 3.4.3 installed through Homebrew.

```
CMake Error at CMake/FindPythonLibs.cmake:183 (FILE):
  file STRINGS file
  "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/incl
ude/python3.5m/patchlevel.h"
  cannot be read.
Call Stack (most recent call first):
  CMake/vtkWrapPython.cmake:164 (find_package)
  Utilities/Python/CMakeLists.txt:4 (include)


-- Found PythonLibs: /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework
/Versions/3.4/lib/libpython3.5.dylib  
CMake Error at CMake/FindPythonLibs.cmake:183 (FILE):
  file STRINGS file
  "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/incl
ude/python3.5m/patchlevel.h"
  cannot be read.
Call Stack (most recent call first):
  CMake/vtkPythonWrapping.cmake:1 (find_package)
  Wrapping/PythonCore/CMakeLists.txt:2 (include)


CMake Warning at CMake/vtkPythonWrapping.cmake:7 (message):
  Python library .  mismatches python 3.4.
Call Stack (most recent call first):
  Wrapping/PythonCore/CMakeLists.txt:2 (include)

```

I traced this down to the lines
```
        args << "-DPYTHON_INCLUDE_DIR='#{`python3-config --prefix`.chomp}/include/python3.5m'"
        args << "-DPYTHON_LIBRARY='#{`python3-config --prefix`.chomp}/lib/libpython3.5.dylib'"
        args << "-DVTK_INSTALL_PYTHON_MODULE_DIR='#{lib}/python3.5/site-packages'"
```
in `vtk.rb`. This produces the wrong include dir -- because with 3.4.3, the corresponding include dir is `/python3.4m`.

It seems like the best approach should be to detect which Python is installed, and to adapt these directories accordingly?

**Comment by iMichka** [comment]
I wrote part of these lines. They are from the time were brewed python was the default python when you used brew (I guess that has changed lately, @tdsmith ?). VTK was linked against the current version of brewed python that was there. So the current setup is still consistent: brew installs python 3.5, and VTK is linked against it.

This has 2 disadvantages:
- if you still need to use python 3.4, you need to rewrite the formula yourself for your needs. I do not know if we just want to take any random python in your PATH. Also, even if giving the Python from the PATH to cmake, it will mess it up and take the wrong libraries ... so this is why these explicit lines have been written.
- we wan't to prevent VTK to link against a specific python (still this would not solve your python 3.5 vs 3.4 problem). See #3401 for discussion.

**Comment by michiexile** [comment]
This is exactly why it threw me off though: I *am* using brewed Python. There’s nothing in the formula that gets Homebrew to *force a minor-version update* of its Python though, and these kinds of build errors is a really opaque way of telling me “please update your Python”.



> On Apr 30, 2016, at 4:40 PM, Michka Popoff <notifications@github.com> wrote:
> 
> I wrote part of these lines. They are from the time were brewed python was the default python when you used brew (I guess that has changed lately, @tdsmith <https://github.com/tdsmith> ?). VTK was linked against the current version of brewed python that was there. So the current setup is still consistent: brew installs python 3.5, and VTK is linked against it.
> 
> This has 2 disadvantages:
> 
> if you still need to use python 3.4, you need to rewrite the formula yourself for your needs. I do not know if we just want to take any random python in your PATH. Also, even if giving the Python from the PATH to cmake, it will mess it up and take the wrong libraries ... so this is why these explicit lines have been written.
> we wan't to prevent VTK to link against a specific python (still this would not solve your python 3.5 vs 3.4 problem). See #3401 <https://github.com/Homebrew/homebrew-science/issues/3401> for discussion.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/Homebrew/homebrew-science/issues/3577#issuecomment-215970691>

--
Mikael Vejdemo-Johansson
mikael@johanssons.org
