### ISSUE TITLE
augustus `--proteinprofile` or PPX method fails

### ISSUE THREAD

**Issue by nextgenusfs** [Homebrew/homebrew-science#3583]
`brew install augustus` on the surface appears to install correctly, and `augustus` runs normally for 95% of what the program is suppose to do.  However, I keep getting an error when trying to run a protein profile prediction using Augustus installed from Homebrew.  This same method works find on Linux - and actually even Augustus installed with LinuxBrew.  Perhaps this is a compilation error?  Here is the version:

```
jon@Jons-MacBook-Pro:~$ augustus --version
AUGUSTUS (3.2.1) is a gene prediction tool
written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
```

And an example of command and error:

```
augustus --proteinprofile=profile/PF00995.16.prfl --species=generic example.fa
```

Then the failed output is below:

```
# This output was generated with AUGUSTUS (version 3.2.1).
# AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
# O. Keller, S. König, L. Gerischer and L. Romoth.
# Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
# Using native and syntenically mapped cDNA alignments to improve de novo gene finding
# Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
# No extrinsic information on sequences given.
# Initialising the parameters using config directory /usr/local/opt/augustus/libexec/config/ ...

augustus: ERROR
    PP::Profile: Error parsing pattern file"profile/PF00995.16.prfl", line 9.
```

The error seems to imply that it cannot parse/read the `prlf` file - this file is an example distributed with augustus (`/usr/local/opt/augustus/libexec/examples`).

**Comment by nextgenusfs** [comment]
It seems like this is a compilation issue.  I was able to install manually by changing the augustus `src/Makefile` to use `g++-5` and then manually configured the `bamtools` includes for `filterBam` and `bam2hints`.  When I do this, then the `--proteinprofile=` option is functional again.  The PPX problem seems to exists in both the bottle and if you try to install with `--build-from-source`, moreover I could not get it to compile by doing the following:
```
brew install augustus --build-from-source --cc=gcc-5
```
This resulted in a compilation error `ld: symbol(s) not found for architecture x86_64`

**Comment by nextgenusfs** [comment]
Also of note.  The same error occurs is augustus-3.2.2.  However, in that distribution I'm unable to compile manually and get it to work.  If I try to compile manually (same way as augustus-3.2.1 above) using `g++-5`, I then get a different error:
```
augustus(90272,0x7fff78370300) malloc: *** error for object 0x7fff579b0000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by dpo** [comment]
`augustus` was just updated. Does the issue persist?

**Comment by nextgenusfs** [comment]
Yes, v3.2.2 has same problem if installed via home-brew (`brew installl augustus`).
