### ISSUE TITLE
openCV_contrib needs update

### ISSUE THREAD

**Issue by kosmasK** [Homebrew/homebrew-science#3588]
My computer is a MacBook Pro with osx 10.11.3

### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
brew is updated to 421cd53.

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
no issues

- [x] Checked that a similar issue hasn't already been filed?
There are issues with the aruco library that is in the opencv contributions. 

- [x] Looked up the software bug tracker if reporting a build error?
It is not a build error, but there is a missing function in the library, that should be there.

### Bug reports / build errors:

There is an issue with aruco lib when installing opencv3 with contributions from homebrew. What I figured out are 2 things.

1)The aruco header file from the homebrew install of the opencv_contrib that is downloaded in "/Library/Caches/Homebrew/", does not contain the declaration of the DetectorParameters::create function, and it seems that in general it is not implemented neither in the aruco.cpp source file, even though they are implemented in the Itseez/opencv_contrib git repo. (https://github.com/Itseez/opencv_contrib/blob/master/modules/aruco/include/opencv2/aruco.hpp , 
https://github.com/Itseez/opencv_contrib/blob/master/modules/aruco/src/aruco.cpp)

2)The current SHA of the opencv_contrib master branch is 745b12eed354fa9e9960f5338e111a9d6d684aaf56f34ab38fa92cfeaa533ca6

while homebrew is requesting for download another.. probably older ef2084bcd4c3812eb53c21fa81477d800e8ce8075b68d9dedec90fef395156e5

and I believe that this is the root of the problem here... Homebrew has to update the opencv3 installer file, since the missing method is an integral part of the core functionality of the aruco lib, thus affecting its proper utilisation:
https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb

**Comment by tdsmith** [comment]
We install the tagged 3.1.0 version. Please ask them to make a release or submit a pull request with a patch isolated to the commit that fixes the build issue you're encountering. Thanks!
