### ISSUE TITLE
nexusformat : install fails by error occurred while make check

### ISSUE THREAD

**Issue by hitorigochi** [Homebrew/homebrew-science#3593]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
Hello all,
I tried to install nexusformat on MacOS X 10.11.4, but it failed by error occurred while make check process as below:

> ==> make check
> Last 15 lines from /Users/mlfdev/Library/Logs/Homebrew/nexusformat/04.make:
>  testsuite.log was created. 
>  -------------------------- 
> 
> Please send `test/testsuite.log' and all information you think might help:
> 
>    To: <nexus-developers@nexusformat.org>
>    Subject: [NeXus Library 4.3.2-20160426svn] testsuite: 15 16 failed
> 
> You may investigate any problem if you feel able to do so, in which
> case the test suite provides a good starting point.  Its output may
> be found below `test/testsuite.dir'.
> 
> make[2]: *** [check-local] Error 1
> make[1]: *** [check-am] Error 2
> make: *** [check-recursive] Error 1

Link to a gist-logs
 https://gist.github.com/anonymous/2e0523bad41f68e0ecb83def4d77350f/revisions

**Comment by dpo** [comment]
Is this resolved now?

**Comment by hitorigochi** [comment]
Thanks a lot. I confirmed that this issue was fixed.
