### ISSUE TITLE
OSX 10.9.5 (Mavericks) openCV3 not finding cocoa

### ISSUE THREAD

**Issue by Halo-5** [Homebrew/homebrew-science#3601]
Installed Anaconda python 2.7.11

Installed opencv3 thusly
`brew install opencv3 --with-contrib --with-cuda --with-ffmpeg --with-tbb --with-qt5 --with-static-option
`

Added this to .bash_profile

```
export PYTHONPATH=/usr/local/Cellar/opencv3/3.1.0_3/lib/python2.7/site-packages:$PYTHONPATH
export PKG_CONFIG_PATH=/usr/local/Cellar/opencv3/3.1.0_3/lib/pkgconfig

```
This works

`python >>>import cv2 `

ran a simple opencv python script and got
```
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
Abort trap: 6
```

**Comment by Halo-5** [comment]
this works

brew install opencv3 --with-cuda --with-ffmpeg --with-tbb

**Comment by autosquid** [comment]
what is your original `PYTHONPATH `?   The python binding is not generate in my case, could you provide your `PYTHONPATH` kindly?

**Comment by Halo-5** [comment]
pythonpath is in the first post.
