### ISSUE TITLE
OpenCV not building --with-qt --with-ffmpeg --without-python

### ISSUE THREAD

**Issue by zacsketches** [Homebrew/homebrew-science#3620]
mac OS X 10.9.5

- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x ] Checked that a similar issue hasn't already been filed?
- [ x ] Looked up the software bug tracker if reporting a build error?

### Bug reports / build errors:
In file included from /tmp/opencv-20160502-36884-18f7ab9/opencv-2.4.12/modules/highgui/src/cap_ffmpeg.cpp:45:
/tmp/opencv-20160502-36884-18f7ab9/opencv-2.4.12/modules/highgui/src/cap_ffmpeg_impl.hpp:1590:25: error: use of undeclared identifier 'PIX_FMT_YUV422P'; did you mean 'AV_PIX_FMT_YUV422P'?
        codec_pix_fmt = PIX_FMT_YUV422P;
                        ^~~~~~~~~~~~~~~
                        AV_PIX_FMT_YUV422P
/usr/local/include/libavutil/pixfmt.h:67:5: note: 'AV_PIX_FMT_YUV422P' declared here
    AV_PIX_FMT_YUV422P,   ///< planar YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

- Brief summary of issue:  I'm trying to build opencv with the qt backend to highgui and ffmpeg so I can produce videos from images.  I write in c++ so I don't need python.

- Please state the complete command that you issued.
  `brew install opencv --with-qt --with-ffmpeg --without-python

**Comment by tdsmith** [comment]
share `brew gist-logs opencv` please! Do you experience this error building `brew install opencv --with-ffmpeg`?

**Comment by QCTW** [comment]
Hi guys,

I have the following error when building with --with-ffmpeg
`brew install opencv3 --c++11 --with-contrib --with-ffmpeg --with-quicktime
==> Installing opencv3 from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/3.1.0.tar.gz
==> Downloading from https://codeload.github.com/Itseez/opencv/tar.gz/3.1.0
######################################################################## 100.0%
==> Downloading https://github.com/Itseez/opencv/commit/a2bda999211e8be9fbc5d40038fdfc9399de31fc.diff
######################################################################## 100.0%
==> Downloading https://github.com/Itseez/opencv/commit/c7bdbef5042dadfe032dfb5d80f9b90bec830371.diff
######################################################################## 100.0%
==> Patching
==> Applying a2bda999211e8be9fbc5d40038fdfc9399de31fc.diff
patching file modules/videoio/src/cap_qtkit.mm
==> Applying c7bdbef5042dadfe032dfb5d80f9b90bec830371.diff
patching file modules/core/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp
Hunk #1 succeeded at 45 (offset 4 lines).
Hunk #2 succeeded at 58 (offset 4 lines).
patching file modules/core/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp
patching file modules/core/src/opencl/runtime/autogenerated/opencl_gl_impl.hpp
patching file modules/core/src/opencl/runtime/generator/common.py
patching file modules/core/src/opencl/runtime/generator/template/opencl_gl.hpp.in
Hunk #1 succeeded at 12 (offset 4 lines).
patching file modules/core/src/opencl/runtime/generator/template/opencl_gl_impl.hpp.in
patching file modules/core/src/opencl/runtime/generator/template/opencl_gl_wrappers.hpp.in
patching file modules/core/src/opencl/runtime/opencl_core.cpp
Hunk #1 succeeded at 283 (offset -3 lines).
Hunk #2 succeeded at 305 (offset -3 lines).
patching file modules/core/src/opengl.cpp
==> Downloading https://github.com/Itseez/opencv_contrib/archive/3.1.0.tar.gz
==> Downloading from https://codeload.github.com/Itseez/opencv_contrib/tar.gz/3.1.0
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Itseez/opencv_3rdparty/81a676001ca8075ada498583e4166079e5744668/ippicv/ippicv_macosx_20151201.tgz
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv3/3.1.0_3 -DCMAKE_BUILD_TYPE=Release 
==> make
Last 15 lines from /Users/Quincy/Library/Logs/Homebrew/opencv3/02.make:
                                ^
/tmp/opencv3-20160521-20556-1lkn34l/opencv-3.1.0/modules/videoio/src/cap_qt.cpp:408:68: error: use of undeclared identifier 'nextTimeStep'
                    GetMovieNextInterestingTime (capture->myMovie, nextTimeStep, 1, & myType, capture->next_frame_time,
                                                                   ^
/tmp/opencv3-20160521-20556-1lkn34l/opencv-3.1.0/modules/videoio/src/cap_qt.cpp:410:29: error: use of undeclared identifier 'GetMoviesError'
                    myErr = GetMoviesError();
                            ^
/tmp/opencv3-20160521-20556-1lkn34l/opencv-3.1.0/modules/videoio/src/cap_qt.cpp:450:13: error: use of undeclared identifier 'GetMoviesError'
    myErr = GetMoviesError();
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qt.cpp.o] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues`

**Comment by QCTW** [comment]
Sorry, it seems to because of  --with-quicktime

I can build with command "brew install opencv3 --c++11 --with-contrib --with-ffmpeg"

**Comment by heinemml** [comment]
`brew install opencv --with-qt --with-ffmpeg --without-python` runs through on my 10.11.5 System.  @zacsketches could you retry with the latest release?

**Comment by tdsmith** [comment]
Okay, thanks. Quicktime is deprecated on recent OS X releases; we'll remove it from the formula soon.
