### ISSUE TITLE
--with-oce nglib fails to build on Mac OSX 10.11.4

### ISSUE THREAD

**Issue by rogermc2** [Homebrew/homebrew-science#3624]
### Indicate troubleshooting steps taken
- [yes ] Ran `brew update` and retried your prior step?
- [ yes] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
         But unsure about deleting things from /usr/local affecting other installed programs.
- [yes ] Checked that a similar issue hasn't already been filed?
- [ yes] Looked up the software bug tracker if reporting a build error?
- [n/a ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:

brew install --with-oce nglib failed.
- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build):
  https://gist.github.com/9cfe4a7b8d9807c319ecda7c0d6b2c55

**Comment by ianrrees** [comment]
Hmm, that seems like a lot of warnings, is that normal for these sort of logs?

The first real errors I'm seeing have to do with clang not having openmp support - you can see in the configure.log that openmp support is not detected.  I don't have access to a machine with Homebrew at the moment, will try to dig a bit further soon.

In the meantime, http://stackoverflow.com/questions/29057437/compile-openmp-programs-with-gcc-compiler-on-os-x-yosemite might have some helpful information.

**Comment by rogermc2** [comment]
I've now managed to install nglib with HomeBrew

**Comment by ianrrees** [comment]
Good to hear!  Could you elaborate a bit on how you fixed your problem?

**Comment by rogermc2** [comment]
brew install nglib
This installed nglib in /usr/local/Cellar/nglib/5.3.1
I then had to set nglib paths in cmake e.g. NGLIB_LIBNGLIB = /usr/local/Cellar/nglib/5.3.1/lib/libnglib.dylib

So, HomeBrew provides version 5.3.1.
The version I was trying to build and which failed was today's git clone

**Comment by hannekum** [comment]
er, so what about --with-oce like the title states and your 'solution' does not have!?!!?!?

**Comment by garykac** [comment]
AFAICT, this bug shouldn't be closed since the problem still occurs: Running
`brew install --with-oce nglib`
still fails with
`ld: Assertion failed: (counter() < 0xffff), function nextCounter, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-264.3.102/src/ld/ld.hpp, line 108.`
whereas:
`brew install nglib`
installs without errors.

**Comment by ianrrees** [comment]
This issue was to do with someone failing to install nglib from the latest git source rather than the recipe, is that the same issue you're having?

Could you confirm that you can't install nglib without the --with-oce?  What version of oce do you have installed?

**Comment by rogermc2** [comment]
I've forgotten the original details.
I just ran
:~ Roger$brew install --with-oce nglib
Warning: homebrew/science/nglib-5.3.1 already installed
I then uninstalled nglib and again ran brew install --with-oce nglib
which failed as commented by garykac.
So, as suggested, I'll reopen it.

**Comment by rogermc2** [comment]
brew install nglib
subsequently ran without problem.

**Comment by macfree** [comment]
I had the same problem and have some additional information, maybe it could help. Ld gets a serious memory leak while trying to install, going up to 30 gb of memory acc to actvity monitor.

**Comment by ianrrees** [comment]
Sorry this took me so long to get to!

The second issue in this ticket (@garykac's issue) comes from the linker - I think it might actually be an ld bug.  Will try to make a simplified test case later.  The clue came after setting `export RC_TRACE_DYLIB_SEARCHING=YES` before running the problematic link command and seeing what looks like ld going in to an infinite loop .  Have submitted PR #4587 - if @macfree and @garykac could confirm whether it works for them, that would be great!

**Comment by macfree** [comment]
Hey! Sorry I missed the email that this thread was updated, now the "stale bot" reminded me.  

I just tried now and it worked on Sierra v10.12.6. /M
