### ISSUE TITLE
rstudio server command line issues

### ISSUE THREAD

**Issue by tehrandavis** [Homebrew/homebrew-science#3634]
I'm having the problems raised in issue #3243.

Using this on OSX el capitan, cannot manage the server from command line using the rstudio-server commands.

I get the following error: too many positional options have been specified on the command line

Any ideas?

**Comment by tdsmith** [comment]
What command are you entering and what makes you think it's Homebrew-related? Thanks!

**Comment by randy3k** [comment]
It is not related to homebrew. So this thread should be closed.

Unfortunately, RStudio Server doesn't ship with an administrative script on Mac OSX,
check:
https://github.com/rstudio/rstudio/tree/ebb054efe3e650de818a251b11087311e5169ed8/src/cpp/server/extras/init.d

**Comment by tehrandavis** [comment]
Okay. Thanks for the clarification.

**Comment by randy3k** [comment]
I have added an admin script in the next iteration of Rstudio-server

https://github.com/Homebrew/homebrew-science/pull/3663
