### ISSUE TITLE
undefined method `clang_version' for OS::Mac:Module

### ISSUE THREAD

**Issue by boatmaker** [Homebrew/homebrew-science#3635]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x ] Checked that a similar issue hasn't already been filed?

I went to run brew doctor and brew update and then it threw this error:

Error: undefined method `clang_version' for OS::Mac:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:32:in `<class:Octave>'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:171:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/formulary.rb:230:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1141:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1139:in `map'
/usr/local/Library/Homebrew/formula.rb:1139:in `installed'
/usr/local/Library/Homebrew/diagnostic.rb:886:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'

I didn't see an already opened issue so I reported it as the prompt requested. 

Thanks!

**Comment by j9ac9k** [comment]
I'm having the same issue.

**Comment by dunn** [comment]
I think https://github.com/Homebrew/brew/commit/ed9f7308b265944c27c833b9a2aaa0e911ff5667 fixed this; run `brew update` and try again, please!

**Comment by j9ac9k** [comment]
@dunn ran ```brew update``` getting a slightly different error now.

```
~ ❯❯❯ brew update && brew upgrade                                                                                                                                    ⏎
Already up-to-date.
Error: uninitialized constant OS::Mac::DeveloperTools
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/compat/macos.rb:87:in `clang_version'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:32:in `<class:Octave>'
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:171:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/formulary.rb:230:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1141:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1139:in `map'
/usr/local/Library/Homebrew/formula.rb:1139:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:
```

**Comment by dunn** [comment]
Ah, sorry.  I think with https://github.com/Homebrew/brew/commit/c6dc50fcf05c8c4956ac86345360fefcb00f664e you'll be good.

**Comment by hpcraink** [comment]
Hi @dunn sorry https://github.com/Homebrew/brew/commit/c6dc50fcf05c8c4956ac86345360fefcb00f664e does not help; still get:
`Error: uninitialized constant OS::Mac::DeveloperTools`

**Comment by dunn** [comment]
😭 https://github.com/Homebrew/brew/commit/4059d5fc2634e24a0b5f9f02a416bda1a7016435

**Comment by j9ac9k** [comment]
4059d5f fixed it for me!

**Comment by boatmaker** [comment]
Thanks! Fixed now!
