### ISSUE TITLE
CEGMA 2.5 ?

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3637]
_From @aviantask on May 9, 2016 22:24_

Can we update the CEGMA version to 2.5 which fixed some bugs in the genewise module? 

_Copied from original issue: Linuxbrew/linuxbrew#1106_

**Comment by ilovezfs** [comment]
I was actually just about to ask about this formula, when I noticed this issue. It seems to me that we should boneyard CEGMA and create a new formula for BUSCO, as CEGMA has been discontinued and the (former) upstream recommends switching to BUSCO: http://korflab.ucdavis.edu/datasets/cegma/

**Comment by ilovezfs** [comment]
Either way: https://github.com/Homebrew/homebrew-science/pull/3687

**Comment by sjackman** [comment]
For repeatability of old pipelines, I prefer to keep `cegma` in `homebrew-science`. Thanks for updating it to 2.5. I'm all for creating a formula for `busco`.
