### ISSUE TITLE
R fails to build on 10.11.4

### ISSUE THREAD

**Issue by brentonk** [Homebrew/homebrew-science#3647]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

`brew install r --with-openblas` fails with the following error:

```
==> Downloading https://rcompletion.googlecode.com/svn-history/r31/trunk/bash_completion/R

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "r--completion"
Download failed: https://rcompletion.googlecode.com/svn-history/r31/trunk/bash_completion/R
```

See https://gist.github.com/brentonk/3d596ea46dfd13e06a46036f5f3beb7a for full output. It looks like the problem is that the above link is broken. #836 reported a similar issue that seemed to be a temporary server error, but that was before Google Code shut down.

This occurred for me with the `--with-openblas` flag but it looks like any installation from source will trigger it.

**Comment by ilovezfs** [comment]
The bash completion used in the formula is now deprecated: https://code.google.com/archive/p/rcompletion/

Remove
```
  # This is the same script that Debian packages use.
  resource "completion" do
    url "https://rcompletion.googlecode.com/svn-history/r31/trunk/bash_completion/R", :using => :curl
    sha256 "2b5cac905ab5dd4889e8a356bbdf2dddff60f718a4104b169e48ca856716e705"
    version "r31"
  end
```

and

```
      bash_completion.install resource("completion")
```
and it should work again until we address this.

**Comment by andrea-capri** [comment]
using that code i get 
```
Error: undefined local variable or method `bash_completion' for Formulary::FormulaNamespace71dd7048e8349c08377e5607f1a3c61b::R:Class
Please report this bug:
```
