### ISSUE TITLE
spades: error: 'uint128' does not name a type

### ISSUE THREAD

**Issue by svanhal71** [Homebrew/homebrew-science#3650]
Spades fails to install on Ubuntu 14.04 - please help

brew install spades

Find link to gist below:
https://gist.github.com/anonymous/91922c21dc68f1beffa6f34f15c620c0

Thanks

**Comment by svanhal71** [comment]
I have managed to download spades and compile it from source
using the following 
wget http://spades.bioinf.spbau.ru/release3.7.1/SPAdes-3.7.1.tar.gz
tar -xzf SPAdes-3.7.1.tar.gz
cd SPAdes-3.7.1
PREFIX=path to Linux.brew ./spades_compile.sh

the problem must be with the cmake.

I wish to install with brew as I am trying to install nullarbor which requires spades to install with all pointers (this doesn't happen with the above).

Thanks

**Comment by sjackman** [comment]
```
/tmp/spades-20160513-8855-1l2xxa3/SPAdes-3.7.1/ext/include/city/citycrc.h:34:1: error: 'uint128' does not name a type
 uint128 CityHashCrc128(const char *s, size_t len);
```
https://gist.github.com/anonymous/91922c21dc68f1beffa6f34f15c620c0#file-02-make-L152

**Comment by sjackman** [comment]
Fixed!
