### ISSUE TITLE
Octave build error with texi2dvi

### ISSUE THREAD

**Issue by thekoc** [Homebrew/homebrew-science#3669]
I installed mactex through brew cask and `/Library/TeX/texbin/` is in my PATH:

> echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:**/Library/TeX/texbin**:/opt/X11/bin:/usr/texbin/:/usr/local/sbin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
which tex
/Library/TeX/texbin/tex

But still it tell me:

> ==> ./configure --prefix=/usr/local/Cellar/octave/4.0.2 --enable-dependency-tracking --enable-link-al
==> make all DOC_TARGETS=
==> make check DOC_TARGETS=
Last 15 lines from /Users/koc/Library/Logs/Homebrew/octave/03.make:
  TEXI2DVI octave.dvi
  MAKEINFO octave.html
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.
For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
make[3]: *** [octave.dvi] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

My octave is installed via homebrew and when I upgrade it to 4.02 the error occurred.

**Comment by dpo** [comment]
TeX shouldn't be required any more. Is `texinfo` installed? What does `ls $(brew --prefix texinfo)/bin` say?

**Comment by thekoc** [comment]
>  ls $(brew --prefix texinfo)/bin
> info         makeinfo     pod2texi     texi2dvi     texindex
> install-info pdftexi2dvi  texi2any     texi2pdf

**Comment by dpo** [comment]
Please post the output of `brew doctor` and `brew gist-logs octave` (a link).

**Comment by thekoc** [comment]
brew doctor said ready and git-log said [https://gist.github.com/5f41c8a77d3de5b6c318d80d9453544d](url)

**Comment by dpo** [comment]
@thekoc Out of curiosity, does it work if you say `brew install octave --without-test`?

@schoeps Any idea why `make all DOCTARGETS=` succeeds but `make check DOCTARGETS=` fails because LaTeX can't be found?
https://gist.githubusercontent.com/thekoc/5f41c8a77d3de5b6c318d80d9453544d/raw/16e8aae56c8aa8662872648802a491de26c1007c/03.make

**Comment by schoeps** [comment]
I think this also occured on Jenkins, right? I did not observe this locally and obviously it should not happen since doctargets='' surpresses building of the manual. Possibly it's an Octave bug. 

One would have to dive into the makefiles and disable doctargets manually but this is not fun to debug.... let's see if we can get around it :)

**Comment by dpo** [comment]
At least in the most recent update, I don't think Jenkins complained (and it doesn't have LaTeX installed). How can we work around it?

**Comment by schoeps** [comment]
Let's try to help thekic and then let's try ignoring the issue :) My reasoning is as follows: standard users do not recompile and most advanced (scientific) users will have latex anyway....

**Comment by thekoc** [comment]
`brew upgrade octave --without-test`
makes no difference

> Last 15 lines from /Users/koc/Library/Logs/Homebrew/octave/03.make:
  TEXI2DVI octave.dvi
  MAKEINFO octave.html
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.

For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
make[3]: *** [octave.dvi] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by thekoc** [comment]
I uninstalled and installed again with no argument,then  it seems that the bug just had disappeared = =

**Comment by dpo** [comment]
Glad to hear you got it to work. Feel free to close the issue if all is well now, and don't hesitate to open a new one if anything else comes up.

**Comment by thekoc** [comment]
Alright, thanks for your time.

**Comment by ashi009** [comment]
I still have the issue.

> $ brew install octave
> ==> Installing octave from homebrew/science
> ==> Tapping homebrew/x11
> Cloning into '/Users/xshi/homebrew/Library/Taps/homebrew/homebrew-x11'...
> remote: Counting objects: 63, done.
> remote: Compressing objects: 100% (63/63), done.
> remote: Total 63 (delta 0), reused 7 (delta 0), pack-reused 0
> Unpacking objects: 100% (63/63), done.
> Checking connectivity... done.
> Tapped 59 formulae (145 files, 157.3K)
> ==> Installing dependencies for homebrew/science/octave: homebrew/x11/imake, transfig
> ==> Installing homebrew/science/octave dependency: homebrew/x11/imake
> ==> Downloading http://xorg.freedesktop.org/releases/individual/util/imake-1.0.7.tar.bz2
> ==> Downloading from https://www.x.org/releases/individual/util/imake-1.0.7.tar.bz2
> ######################################################################## 100.0%
> ==> Downloading https://raw.githubusercontent.com/Homebrew/patches/a0bb3a4/imake/patch-imakemdep.h.diff
> ######################################################################## 100.0%
> ==> Patching
> ==> Applying patch-imakemdep.h.diff
> patching file imakemdep.h
> Hunk #1 succeeded at 259 (offset -8 lines).
> Hunk #2 succeeded at 324 (offset -15 lines).
> ==> ./configure --prefix=/Users/xshi/homebrew/Cellar/imake/1.0.7_1
> ==> make install
> ==> Downloading http://xorg.freedesktop.org/releases/individual/util/xorg-cf-files-1.0.5.tar.bz2
> ==> Downloading from https://www.x.org/releases/individual/util/xorg-cf-files-1.0.5.tar.bz2
> ######################################################################## 100.0%
> ==> ./configure --with-config-dir=/Users/xshi/homebrew/Cellar/imake/1.0.7_1/lib/X11/config --prefix=/Users/xshi/hom
> ==> make install
> 🍺  /Users/xshi/homebrew/Cellar/imake/1.0.7_1: 143 files, 1.2M, built in 24 seconds
> ==> Installing homebrew/science/octave dependency: transfig
> ==> Downloading https://downloads.sourceforge.net/mcj/transfig.3.2.5e.tar.gz
> ==> Downloading from https://sourceforge.net/projects/mcj/files/mcj-source/transfig.3.2.5e.tar.gz/download?use_mirr
> ######################################################################## 100.0%
> ==> make clean
> ==> xmkmf
> ==> make Makefiles
> ==> make
> ==> make install
> ==> make install.man
> 🍺  /Users/xshi/homebrew/Cellar/transfig/3.2.5e: 81 files, 686.9K, built in 15 seconds
> ==> Installing homebrew/science/octave
> ==> Using Homebrew-provided fortran compiler.
> This may be changed by setting the FC environment variable.
> ==> Downloading http://ftpmirror.gnu.org/octave/octave-4.0.2.tar.gz
> Already downloaded: /Library/Caches/Homebrew/octave-4.0.2.tar.gz
> ==> Downloading http://hg.savannah.gnu.org/hgweb/octave/raw-rev/e870a68742a6
> Already downloaded: /Library/Caches/Homebrew/octave--patch-0ddcd8dd032be79d5a846ad2bc190569794e4e1a33ce99f25147d70ae6974682
> ==> Patching
> ==> Applying e870a68742a6
> patching file libgui/src/octave-dock-widget.cc
> ==> ./configure --prefix=/Users/xshi/homebrew/Cellar/octave/4.0.2_2 --enable-dependency-tracking --enable-link-all-
> ==> make all DOC_TARGETS=
> ==> make check DOC_TARGETS=
> Last 15 lines from /Users/xshi/Library/Logs/Homebrew/octave/03.make:
>   TEXI2DVI octave.dvi
>   MAKEINFO octave.html
> You don't have a working TeX binary (tex) installed anywhere in
> your PATH, and texi2dvi cannot proceed without one.  If you want to use
> this script, you'll need to install TeX (if you don't have it) or change
> your PATH or TEX environment variable (if you do).  See the --help
> output for more details.
> 
> For information about obtaining TeX, please see http://tug.org/texlive,
> or do a web search for TeX and your operating system or distro.
> make[3]: *** [octave.dvi] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all-recursive] Error 1
> make: *** [all] Error 2
> 
> READ THIS: https://git.io/brew-troubleshooting
> If reporting this issue please do so at (not Homebrew/brew):
>   https://github.com/Homebrew/homebrew-science/issues
> 
> These open issues may also help:
> Octave (--with-gui) failed to build on 10.11 https://github.com/Homebrew/homebrew-science/issues/3387
> Octave "pkg install -forge signal control" traverses nonexistent directory for -lgfortran https://github.com/Homebrew/homebrew-science/issues/3167
> `

**Comment by schoeps** [comment]
please try this 
```
brew uninstall octave 
brew install octave --without-test
```

**Comment by Dewdrops** [comment]
I still have the issue in OSX 10.11.5 when install octave 4.0.3 .

The command I use is
```
brew install octave --with-openblas --without-test
```

Error output
```
==> make all DOC_TARGETS=
==> make install DOC_TARGETS=
Last 15 lines from /Users/dewdrops/Library/Logs/Homebrew/octave/03.make:
  TEXI2DVI octave.dvi
  MAKEINFO octave.html
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.

For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
make[3]: *** [octave.dvi] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
Octave formula causes a deprecation warning https://github.com/Homebrew/homebrew-science/issues/3920
Trouble installing octave to mac os 10.11.5 https://github.com/Homebrew/homebrew-science/issues/3829
Octave (--with-gui) failed to build on 10.11 https://github.com/Homebrew/homebrew-science/issues/3387
```

**Comment by schoeps** [comment]
Actually Octave should not build the docs (`DOC_TARGETS=`). However, one could enforce the correct path in the formula by adding a line like `ENV.prepend_path "PATH", "/Library/TeX/texbin"`, 
see [here](https://gist.githubusercontent.com/schoeps/21005e50dff49fdf31bd0b2fef85bc67/raw/9a1c06d6bada9c5a8a82eff21b93d6feaedc4c6a/octave.rb). You can modify your local file accordingly or install the gist 

`brew install https://gist.githubusercontent.com/schoeps/21005e50dff49fdf31bd0b2fef85bc67/raw/9a1c06d6bada9c5a8a82eff21b93d6feaedc4c6a/octave.rb`

Does this fix your problem?

**Comment by Dewdrops** [comment]
@scoeps
Thanks for the gist. Works great.

In fact this issue only happens to me when `--with-openblas` is specified. Don't know why though.

**Comment by schoeps** [comment]
This can be explained: if you use no switches then homebrew will fetch a precompiled binary. Therefore the problem does not show up. This also means that installing `--with-openblas` should be significantly slower than without.

Regarding openblas: Actually I prefer it, too but recently, people have seen strange problems in Octave on various platforms due to openblas (e.g. unexpected crashes while plotting, ctrl+c does not work in the GUI etc). We do not know yet why. However, if you see this behavior, it might be an option to switch to Apple's blas implementation.

**Comment by filipefigcorreia** [comment]
I've faced this same issue today when trying to use the switches `--with-gui --HEAD` and, inspired by @schoeps' workaround, solved it by adding this to my formula: 
`ENV.prepend_path "PATH", "/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin"`

It appears to have installed fine. I'm now facing [another issue](http://stackoverflow.com/questions/39289903/unable-to-open-files-in-octave-gui), but I'm assuming that it has more to do with this version of octave and not so much with homebrew.

**Comment by schoeps** [comment]
Most users want the function help (to e.g. call `help sin` in Octave). Most users will probably not care to build the pdf documentation locally (since the pdf can be downloaded from the internet). In former times Octave <=4.3 this could not be achieved. However, in `--HEAD` and thus in the next release (4.2 is due in one week or so) `--without-docs` will only disable the pdf documentation. Therefore, the best way to get octave is:

`brew install --HEAD --with-gui --without-docs`

**Comment by schoeps** [comment]
@filipefigcorreia: I suggest to post your question to the octave mailing list instead of stackoverflow (however, crossposting is not favoured...).
