### ISSUE TITLE
r.rb : rcompletion link is no longer valid ( googlecode) but found alternative

### ISSUE THREAD

**Issue by rafsanm** [Homebrew/homebrew-science#3670]
### Indicate troubleshooting steps taken
Because googlecode is no longer an active code repository, the link is not valid. You can download the source from there. Instead, I used rcompletion found in https://github.com/deepayan/rcompletion. It builds and installs correctly after we do the adjustments.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-science/issues/3647
