### ISSUE TITLE
nglib --with-oce failed

### ISSUE THREAD

**Issue by josuemercado** [Homebrew/homebrew-science#3699]
"brew install --with-oce nglib" failed

=> ./configure --prefix=/usr/local/Cellar/nglib/5.3.1 --disable-gui --enable-nglib --enable-occ --with-occ=/usr/local/opt/o
==> make install
Last 15 lines from /Users/josue/Library/Logs/Homebrew/nglib/02.make:
libtool: link: clang++ -dynamiclib -Wl,-flat_namespace -Wl,-undefined -Wl,suppress -o .libs/libocc.0.dylib  .libs/Partition_Inter2d.o .libs/Partition_Inter3d.o .libs/Partition_Loop.o .libs/Partition_Loop2d.o .libs/Partition_Loop3d.o .libs/Partition_Spliter.o .libs/occconstruction.o .libs/occgenmesh.o .libs/occgeom.o .libs/occmeshsurf.o   -L/usr/local/opt/oce/lib/ -L/usr/local/opt/oce/include/oce/lib -lTKernel -lTKGeomBase -lTKMath -lTKG2d -lTKG3d -lTKXSBase -lTKOffset -lTKFillet -lTKShHealing -lTKMesh -lTKMeshVS -lTKTopAlgo -lTKGeomAlgo -lTKBool -lTKPrim -lTKBO -lTKIGES -lTKBRep -lTKSTEPBase -lTKSTEP -lTKSTL -lTKSTEPAttr -lTKSTEP209 -lTKXDESTEP -lTKXDEIGES -lTKXCAF -lTKLCAF -lFWOSPlugin  -O2   -install_name  /usr/local/Cellar/nglib/5.3.1/lib/libocc.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
0  0x10b28d97e  __assert_rtn + 144
1  0x10b2d5c72  ld::tool::InputFiles::findDylib(char const*, char const*) + 1140
2  0x10b26fe14  generic::dylib::File<x86_64>::processIndirectLibraries(ld::dylib::File::DylibHandler*, bool) + 82
3  0x10b2d687b  ld::tool::InputFiles::createIndirectDylibs() + 271
4  0x10b2d77f0  ld::tool::InputFiles::forEachInitialAtom(ld::File::AtomHandler&, ld::Internal&) + 504
5  0x10b2e1dec  ld::tool::Resolver::resolve() + 44
6  0x10b28e787  main + 940
A linker snapshot was created at:
	/tmp/libocc.0.dylib-2016-04-27-194825.ld-snapshot
ld: Assertion failed: (counter() < 0xffff), function nextCounter, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-264.3.101/src/ld/ld.hpp, line 108.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libocc.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

https://gist.github.com/anonymous/e541c0c5ccf46debd8af3b31d363aa8e

**Comment by ibloomfield** [comment]
same issue

**Comment by tdsmith** [comment]
It looks like the code is triggering an assert in Apple's linker; please consult with the upstream developer and/or Apple. If you can successfully build this outside of Homebrew, please let us know and we can evaluate whether we're contributing to this failure.

**Comment by christofferGT** [comment]
same issue. Any luck in solving the problem?

**Comment by epiphytexx** [comment]
I have the same issue - but with the next ld version (ld64-264.3.102) 

ld: Assertion failed: (counter() < 0xffff), function nextCounter, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-264.3.102/src/ld/ld.hpp, line 108.
