### ISSUE TITLE
spades: error: 'uint128' does not name a type

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#3705]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?

### Problem

https://gist.github.com/8e6aee43061a39dbd35e65c2849e17b8

This is older but sort of related perhaps? 
https://github.com/Homebrew/homebrew-science/issues/3650

Other colleagues had issues with `int128()` etc.

**Comment by sjackman** [comment]
```
/tmp/spades-20160601-9085-1rlp57i/SPAdes-3.8.0/ext/include/city/citycrc.h:34:1: error: 'uint128' does not name a type
 uint128 CityHashCrc128(const char *s, size_t len);
```
https://gist.github.com/tseemann/8e6aee43061a39dbd35e65c2849e17b8#file-02-make-L2-L464

**Comment by asl** [comment]
Sorry, we branched the release after fixing this stuff.

Get rid of #ifdef __SSE4_2__ inside assembler/ext/src/cityhash/city.cc - we're not using CRC-variants of CityHash anyway.

**Comment by sjackman** [comment]
This looks to me to be an upstream issue, but I'm not sure why it compiles fine on Mac OS.

The following gets it to compile for me:
```diff
--- a/spades.rb
+++ b/spades.rb
@@ -22,6 +22,11 @@ class Spades < Formula
   end
 
   def install
+    inreplace "ext/include/city/citycrc.h", "uint128", "city_uint128"
+    inreplace "ext/include/city/citycrc.h", "uint64", "uint64_t"
+    inreplace "ext/src/cityhash/city.cc", "<uint32>", "<uint32_t>"
+    inreplace "ext/src/cityhash/city.cc", " uint128", " city_uint128"
+
     mkdir "src/build" do
       system "cmake", "..", *std_cmake_args
       system "make", "install"
```

**Comment by asl** [comment]
Shaun, this will work as well.

**Comment by sjackman** [comment]
I missed your comment above. Thanks for the quick response, Anton.

**Comment by sjackman** [comment]
Fixed!

**Comment by asl** [comment]
Some followup - this should not be necessary for SPAdes 3.8.1. See https://github.com/ablab/spades/commit/c535e9c4adeac975c28b71dbacdf8feba8ab10a6

**Comment by sjackman** [comment]
Thanks! Could you also add `#!/usr/bin/env python` to the top of `spades_init.py`?

**Comment by sjackman** [comment]
I've opened a PR for SPAdes 3.8.1: https://github.com/Homebrew/homebrew-science/pull/3756

**Comment by asl** [comment]
> Thanks! Could you also please add #!/usr/bin/env python to the top of spades_init.py?
Why do you need this? The file is never executed, always included.

**Comment by sjackman** [comment]
`make install` installs `spades_init.py` in `$PREFIX/bin`. The Homebrew audit scripts complain about non-executable files installed in `$PREFIX/bin`. It ought be installed in `$PREFIX/share/spades/spades_init.py` if it's not intended to be executed.

**Comment by sjackman** [comment]
I've merged 3.8.1 into Homebrew https://github.com/Homebrew/homebrew-science/pull/3756

**Comment by alexeigurevich** [comment]
Hi Shaun, we made `spades_init.py` executable and added `#!/usr/bin/env python` to the top of it. This change will be available since next SPAdes release.
This file should be in the same dir with spades.py for development purposes, so we can't install it in `$PREFIX/share/spades/`.

**Comment by sjackman** [comment]
Okay. Thanks, Alex.
