### ISSUE TITLE
R dylib load references gcc 5 dir, but gcc 6 is installed

### ISSUE THREAD

**Issue by kallewoof** [Homebrew/homebrew-science#3718]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

- Brief summary of issue: Installing latest version of R results in a `dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib` error. 
- Please state the complete command that you issued: `R`

The problem is in the fact GCC 6 is installed, and the directory `/usr/local/opt/gcc/lib/gcc/5` does not exist at all. The file in question (`libgfortran.3.dylib`) exists in `.../6/`.

Errors about dylib appear when doing `brew reinstall r` as well.

**Comment by randy3k** [comment]
I confirm this. The update of gcc usually will break many other softwares.

**Comment by adamaltmejd** [comment]
Same thing happens to me. Tried the commands that you posted @randy3k and I still get an error (below), but at least R starts. Also tried to `brew install homebrew/versions/gcc5` and then reinstall R but that doesn't help at all.

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/Cellar/r/3.3.0/R.framework/Versions/3.3/Resources/library/stats/libs/stats.so':
  dlopen(/usr/local/Cellar/r/3.3.0/R.framework/Versions/3.3/Resources/library/stats/libs/stats.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/r/3.3.0/R.framework/Versions/3.3/Resources/library/stats/libs/stats.so
  Reason: image not found
During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found
```

**Comment by dpo** [comment]
Seems like it's just a matter of bumping up `r`. Anybody for a pull request?

**Comment by randy3k** [comment]
@adamaltmejd 
you have to continuously apply the `install_name_tool` patch to `/usr/local/Cellar/r/3.3.0/R.framework/Versions/3.3/Resources/library/stats/libs/stats.so`
and any other similar files.

**Comment by zhiboz** [comment]
another "workaround" is to reinstall R, and all affected packages against gcc6.

**Comment by randy3k** [comment]
To reinstall R, make sure you are not reinstalling to bottle but building from source

```
brew reinstall r --build-from-source
```

**Comment by sjackman** [comment]
Thanks, Tim.

**Comment by tdsmith** [comment]
Cheers!

**Comment by zhiboz** [comment]
Ran into issues when installing the `igraph` package with R 3.3.0_1. 

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/3.3/site-library/igraph/libs/igraph.so':
  dlopen(/usr/local/lib/R/3.3/site-library/igraph/libs/igraph.so, 6): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEcm
  Referenced from: /usr/local/lib/R/3.3/site-library/igraph/libs/igraph.so
  Expected in: flat namespace
 in /usr/local/lib/R/3.3/site-library/igraph/libs/igraph.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.3/site-library/igraph’

The downloaded source packages are in
	‘/private/var/folders/pl/gq71wn4x269f_5f_cs0dn0940000gn/T/RtmpidWSsi/downloaded_packages’
Warning message:
In install.packages("igraph") :
  installation of package ‘igraph’ had non-zero exit status
```

I got stuck now as I did not figure out a way to switch back to gcc 5.3.0 and R 3.3.0 :(

**Comment by tdsmith** [comment]
Works for me; you might have to nuke your installed packages with `rm -rf /usr/local/lib/R/3.3/site-library/*` but I'm not sure why you'd see that particular error.

**Comment by zhiboz** [comment]
out of luck :(; `rm -rf /usr/local/lib/R/3.3/site-library/*` did not work for me. tried to remove R and reinstall R; it did not work either. bummer!

is it possible to install R 3.3.0 with gcc5? thanks!

**Comment by tdsmith** [comment]
It is not. Please open a new ticket with more information about the failure you're seeing and how you can reproduce it.

**Comment by sjackman** [comment]
Is the problem perhaps with `igraph`?

**Comment by zhiboz** [comment]
I suspect so. some other packages like `dplyr` install fine.

**Comment by sjackman** [comment]
Just a shot in the dark. Try `brew remove igraph` and then `install.packages("igraph")`

**Comment by zhiboz** [comment]
Thanks @sjackman! just tried with no luck.

I just installed the R binary for Mac OSX from https://www.r-project.org/, which fits my urgent need for now ...

**Comment by randy3k** [comment]
I have no problem of installing igraph on R 3.3.0 with gcc 6. It looks like you are linking against libstdc++ instead of libc++.

**Comment by sjackman** [comment]
@zhiboz You can install the R binary using cask as well `brew cask install r`

**Comment by benjaminjack** [comment]
I'm having the same issue with the lme4 package. I tried removing and reinstalling it with no luck:

`** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.3/site-library/minqa/libs/minqa.so':
  dlopen(/usr/local/lib/R/3.3/site-library/minqa/libs/minqa.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.3/site-library/minqa/libs/minqa.so
  Reason: image not found
ERROR: lazy loading failed for package ‘lme4’
* removing ‘/usr/local/lib/R/3.3/site-library/lme4’
Warning in install.packages :
  installation of package ‘lme4’ had non-zero exit status`

**Comment by randy3k** [comment]
I guess you have to also reinstall the package `minqa`.

**Comment by randy3k** [comment]
I used these commands to fix the gcc issues **USE WITH CAUTION**

```
find /usr/local/Cellar/r -name *.so | xargs -L1 install_name_tool -change /usr/local/opt/gcc/lib/gcc/5/libquadmath.0.dylib /usr/local/opt/gcc/lib/gcc/6/libquadmath.0.dylib

find /usr/local/Cellar/r -name *.so | xargs -L1 install_name_tool -change /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib

find /usr/local/Cellar/r -name *.dylib | xargs -L1 install_name_tool -change /usr/local/opt/gcc/lib/gcc/5/libquadmath.0.dylib /usr/local/opt/gcc/lib/gcc/6/libquadmath.0.dylib

find /usr/local/Cellar/r -name *.dylib | xargs -L1 install_name_tool -change /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
```

**Comment by benjaminjack** [comment]
Reinstalling `minqa` fixed it! Thanks!

**Comment by vd4mmind** [comment]
Can anyone guide me with this issue posted in this link below. It would be of great help.

[https://github.com/igraph/rigraph/issues/174](https://github.com/igraph/rigraph/issues/174)

**Comment by dpo** [comment]
@vd4mmind It's not clear that your question is related to Homebrew. Please only post Homebrew-related issues on this tracker. Thank you.

**Comment by vd4mmind** [comment]
I am very sorry. This is not homebrew related but related to libstdc++.so.6: version `GLIBCXX_3.4.15' while installing igraph. I am removing my reference.

**Comment by weilu** [comment]
Had a similar issue with gcc 7:

```
dyld: Library not loaded: /usr/local/lib/gcc/7/libgcc_s.1.dylib
  Referenced from: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
  Reason: image not found
Trace/BPT trap: 5
```

Solved it by `ln -s /usr/local/opt/gcc/lib/gcc/7 /usr/local/lib/gcc/7`

**Comment by mintisan** [comment]
@weilu Thanks, it works for me.
