### ISSUE TITLE
PETSc/SLEPc rebuild needed after open-MPI and gcc update

### ISSUE THREAD

**Issue by mattia-** [Homebrew/homebrew-science#3719]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

I am sorry to bring this up again, but the same issue as https://github.com/Homebrew/homebrew-science/issues/3336 just resurfaced after the latest open-MPI upgrade (from version 1.10.2 to 1.10.2_1).

Also, the issue related to gcc version reported in https://github.com/Homebrew/homebrew-science/issues/3718 also applies to software builds that use PETSc and SLEPc. The error I get is
```
-- Unable to find library gfortran
-- Unable to find library gfortran
-- Unable to find library gcc_ext.10.5
-- Unable to find library quadmath
```

**Comment by dpo** [comment]
#3710 should take care of this

**Comment by mattia-** [comment]
Thanks for the fix, and sorry for the late reply!

Unfortunately, I'm still facing the following error when configuring an application for build (using CMake):
```
-- Checking for package 'PETSc'
-- PETSC_DIR is /usr/local/opt/petsc/real
-- PETSC_ARCH is empty
-- Found petscconf.h
-- Unable to find library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/lib/darwin
-- Unable to find library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin
-- Unable to find library gfortran
-- Unable to find library -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin
-- Performing test PETSC_TEST_RUNS - Failed
-- Performing test PETSC_TEST_3RD_PARTY_LIBS_RUNS - Failed
-- PETSc configured without Cusp support
-- PETSc could not be found. Be sure to set PETSC_DIR and PETSC_ARCH. (missing:  PETSC_TEST_RUNS) (Required is at least version "3.4")
```
Is this in any way related to the PETSc package? This same application used to configure and compile fine before this gcc-openmpi-petsc update, so I am not sure what is going wrong now.

**Comment by dpo** [comment]
I'm not sure what `PETSC_TEST_RUNS` is. What's that folder supposed to contain?

**Comment by dpo** [comment]
Please update and give it another try. Some dependencies of PETSc still needed to be updated. Check that `brew test petsc` works.

**Comment by mattia-** [comment]
Ok, that solved the problem for PETSc. The same goes for SLEPc, I'm afraid:
$ brew test slepc --keep-tmp
Testing homebrew/science/slepc
==> Using the sandbox
==> mpicc ex1.c -I/usr/local/opt/slepc/include -I/usr/local/opt/petsc/include -L/usr/local/opt/petsc/lib -lpetsc -L/usr/local/opt/slepc/lib -lslepc -o ex1
==> mpirun -np 3 ex1 2>&1 | tee ex1.out
==> Kept temporary files
Temporary files retained at /tmp/slepc-test-20160610-95479-30nyra
Error: homebrew/science/slepc: failed
Failed assertion, no message given.
$  cat /tmp/slepc-test-20160610-95479-30nyra/tutorials/ex1.out 
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libparpack.2.dylib
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libparpack.2.dylib
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libparpack.2.dylib
  Reason: image not found
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 95496 on node endor exited on signal 5 (Trace/BPT trap: 5).
--------------------------------------------------------------------------

**Comment by dpo** [comment]
Yes. I'm working on it in #3732.

**Comment by mattia-** [comment]
Great! Thanks a lot!

**Comment by dpo** [comment]
Ok. Let's try again.

**Comment by mattia-** [comment]
Everything looks good now, thank you very much!

**Comment by dpo** [comment]
You're welcome.
