### ISSUE TITLE
Failed installing transfig (xmkmf) 10.8.5

### ISSUE THREAD

**Issue by bennytrill** [Homebrew/homebrew-science#3735]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
- Brief summary of issue: 

When installing transfig, I keep running into an issue with xmkmf (its blank)

- Please state the complete command that you issued: 
   
 brew install transfig

- Please do not post lengthy build output here. Instead provide a link to a gist:

https://gist.github.com/bennytrill/364477e9a801aecb7afd8e8f4cb6b9be

Below is the brew config:
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11d47e8325f50ab7993f3fca0432876da0ea1c11
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dfca578eed4d93eb74e27d2863f3bec863586636
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
GCC-4.2: build 5666
Clang: 5.1 build 503
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65-b14-462
System Ruby: 1.8.7-p358
OS X: 10.8.5-x86_64
Xcode: 5.1.1
CLT: 5.1.0.0.1.1396320587
X11: 2.7.9 => /opt/X11

**Comment by dpo** [comment]
Could you post the output of `brew gist-logs transfig`?

**Comment by bennytrill** [comment]
I run into this when running `brew gist-logs transfig`: 

Error: Problems parsing JSON

**Comment by dpo** [comment]
Try `brew install -sv transfig` and create a gist with the complete output.

**Comment by bennytrill** [comment]
Heres the gist for `brew install -sv transfig`:

https://gist.github.com/c1ee4d1825b43d48fc96f36f18650297.git

**Comment by dpo** [comment]
I'm guessing `/homebrew/x11/imake` needs to be rebottled against gcc6. Could you try installing `imake` from source using `brew install -s imake` and then `brew install transfig` again?

**Comment by bennytrill** [comment]
That seemed to have work! The `transfig` installed fine after installing `imake` from the source. Thanks so much really appreciate the help

**Comment by dpo** [comment]
You're welcome.
