### ISSUE TITLE
openblas for linux boottle installation problem

### ISSUE THREAD

**Issue by randy3k** [Homebrew/homebrew-science#3737]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

- Brief summary of issue:

I got the following erorr when installing the openblas error
```
(bootstrap)-~$ brew install openblas
==> Installing openblas from homebrew/science
==> Downloading https://linuxbrew.bintray.com/bottles-science/openblas-0.2.18.x86_64_li
Already downloaded: /home/ubuntu/.cache/Homebrew/openblas-0.2.18.x86_64_linux.bottle.tar.gz
==> Pouring openblas-0.2.18.x86_64_linux.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /home/ubuntu/.linuxbrew
No such file or directory @ realpath_rec - /home/linuxbrew
Error: No such file or directory @ realpath_rec - /home/linuxbrew
```

However, the `--build-from-source` option works fine.

**Comment by dpo** [comment]
@sjackman any ideas?

**Comment by sjackman** [comment]
Yep, I see the problem. For some reason there's an absolute symlink rather than a relative symlink in `lib`.
```
lrwxrwxrwx 1 linuxbrew linuxbrew       68 Apr 12 19:29 libblas.so -> /home/linuxbrew/.linuxbrew/Cellar/openblas/0.2.18/lib/libopenblas.so
lrwxrwxrwx 1 linuxbrew linuxbrew       68 Apr 12 19:29 liblapack.so -> /home/linuxbrew/.linuxbrew/Cellar/openblas/0.2.18/lib/libopenblas.so
```

I thought absolute symlinks like this were automatically cleaned up though when bottling. I guess not.

Here's the bug:
```ruby
    ln_s lib/"libopenblas.#{so}", lib/"libblas.#{so}"
    ln_s lib/"libopenblas.#{so}", lib/"liblapack.#{so}"
```

It should be either:
```ruby
    ln_s "libopenblas.#{so}", lib/"libblas.#{so}"
    ln_s "libopenblas.#{so}", lib/"liblapack.#{so}"
```
or
```ruby
    lib.install_symlink "libopenblas.#{so}", "libblas.#{so}"
    lib.install_symlink "libopenblas.#{so}", "liblapack.#{so}"
```
I believe this latter form is preferred now.

@randy3k As a workaround, you can install Linuxbrew in `/home/linuxbrew/.linuxbrew`, which also gives you let's you use non-relocatable bottles.

**Comment by sjackman** [comment]
@randy3k Please report `ruby --version`. I believe this bug may only affect old versions of Ruby.

**Comment by sjackman** [comment]
This issue, oddly, does not affect Mac. I'm not sure why.
```
lrwxr-xr-x  1 sjackman  staff        17 12 Apr 12:29 libblas.dylib -> libopenblas.dylib
lrwxr-xr-x  1 sjackman  staff        17 12 Apr 12:29 liblapack.dylib -> libopenblas.dylib
```

**Comment by sjackman** [comment]
Thanks for the fix, Dominique. I'll rebuild the Linuxbrew bottle.
