### ISSUE TITLE
Trouble installing openblas --with-openmp

### ISSUE THREAD

**Issue by michaelsbradleyjr** [Homebrew/homebrew-science#3743]
I've tried installing openblas `--with-openmp` and with/without `--HEAD`. In either case, I get the following build error:

```
make
FC=/usr/local/bin/gfortran
libs
netlib
shared

<built-in>:0: error: Unknown value ‘10.11’ of -mmacosx-version-min
<built-in>:0: error: Unknown value ‘10.11’ of -mmacosx-version-min
make: *** [getarch] Error 1
Makefile.system:409: *** OpenBLAS: Clang didn't support OpenMP yet..  Stop.
```

I'm not sure to what degree the `mmacosx-version-min` is tangled with the clang related error. Now, I re/installed the latest version of gcc via homebrew using the `--without-multilib` option, so it should support OpenMP; also, I've installed `clang-omp` with brew, and I have the latest XCode, etc.

**Comment by dpo** [comment]
The formula should specify the C compiler to the Makefile and it doesn't. However, compiling with gcc-6 produces an error for me on 10.9. Feel free to give it a try yourself. All that's needed is to `brew edit openblas`, change lines 29 and 30 so they read
```
system "make", "CC=#{ENV["CC"]}", "FC=#{ENV["FC"]}", "libs", "netlib", "shared"                     
system "make", "CC=#{ENV["CC"]}", "FC=#{ENV["FC"]}", "tests"
```
and run `brew install -sv openblas --with-openmp`. I get the same error with `--HEAD`.

**Comment by michaelsbradleyjr** [comment]
I made the suggested edits, and before running `brew install -sv openblas --with-openmp`, I did:

```
export CC=gcc-6
export CXX=g++-6
export HOMEBREW_CC=gcc-6
export HOMEBREW_CXX=g++-6
```

The install then completed successfully. I'm running mac osx `10.11`.

**Comment by dpo** [comment]
Sounds good. #3744 officializes the fix.

**Comment by michaelsbradleyjr** [comment]
The only thing I would note is that I had to export the `HOMEBREW_CC` and `...CXX` variables, otherwise the install did not work, even with the changes made to the homebrew formula.

**Comment by dpo** [comment]
That's odd. They're already set to the correct values:
```
$ brew install -si openblas --with-openmp
==> Installing openblas from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/xianyi/OpenBLAS/archive/v0.2.18.tar.gz
Already downloaded: /Users/dpo/Library/Caches/Homebrew/openblas-0.2.18.tar.gz
==> Entering interactive mode
Type `exit' to return and finalize the installation
Install to this prefix: /usr/local/Cellar/openblas/0.2.18_1
bash-3.2$ echo $CC
gcc-6
bash-3.2$ echo $HOMEBREW_CC
gcc-6
bash-3.2$ echo $CXX
g++-6
bash-3.2$ echo $HOMEBREW_CXX
g++-6
```

**Comment by dpo** [comment]
@xianyi

**Comment by dpo** [comment]
@michaelsbradleyjr Could you post the logs of the failed build, with just the changes made to the formula?

**Comment by michaelsbradleyjr** [comment]
I will do a re/install to see if I can reproduce the problem I encountered earlier and report back. However, I can't afford to "break" my r+openblas right at this moment; hopefully I can let you know something by the end of the day.

**Comment by dpo** [comment]
I just tried on 10.10 and it worked for me so I'll pull. Please open a new issue if you get a chance to try again and there are difficulties. Thanks.
