### ISSUE TITLE
Installed R from source with gcc, RStudio reports Plots is disabled

### ISSUE THREAD

**Issue by michaelsbradleyjr** [Homebrew/homebrew-science#3745]
I just successfully re/installed R from source, using gcc-6 / g++-6, and RStudio now warns me:

```
WARNING: The version of R you are running against does not support the quartz
graphics device (which is required by RStudio for graphics). The Plots tab will
be disabled until a version of R that supports quartz is installed. 
```
Perhaps that is an expected difficulty, perhaps not... I'm not sure.

**Comment by michaelsbradleyjr** [comment]
FYI, I did another compile-install with brew, using clang instead of gcc, and RStudio works as normal – no warnings or problems re: "Plots".

**Comment by tdsmith** [comment]
I'm not sure why this doesn't work with gcc and we'll consider PRs to make it work but if it works with clang I'm happy :) Thanks for reporting; let us know if you have any more questions.
