### ISSUE TITLE
Segmentation fault when trying to run mkdssp

### ISSUE THREAD

**Issue by egarpor** [Homebrew/homebrew-science#3751]
### Indicate troubleshooting steps taken

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew update` and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

- Brief summary of issue: segmentation fault when trying to run mkdssp
- Command:
    ```
brew install homebrew/science/dssp

mkdssp --help
```
- Output: ``Segmentation fault: 11``

**Comment by tdsmith** [comment]
Did dssp install a bottle? Can you give the output of `brew config` and `brew gist-logs mkdssp`?

**Comment by egarpor** [comment]
It *seems* like the bottle is not being installed.

If I run `brew install homebrew/science/dssp` I get:
> ==> Installing dssp from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/dssp-2.2.1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring dssp-2.2.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/dssp/2.2.1: 5 files, 844K

My `brew-config`:
> HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 01b514f57a01293c770b6dc63b17c838ff34ce0c
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c168d60b8b9a2c0ae02679fad2e449332f2057a8
Core tap last commit: 2 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Clang: 7.0 build 700
Perl: /usr/bin/perl
Python: /Users/egarpor/anaconda/bin/python => /Users/egarpor/anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_05, 1.6.0_65-b14-466.1
System Ruby: 2.0.0-p481
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.9 => /opt/X11

When I do `brew gist-logs mkdssp`:
> Error: No available formula with the name "mkdssp"

**Comment by dpo** [comment]
The output you pasted shows that the bottle **is** being installed. Note that the formula name is `dssp`, there's no formula with the name `mkdssp`, which seems to be an executable installed as part of `dssp`.

I can reproduce the segmentation fault. However, it went away when I built from source with `brew install -s dssp`. Could you confirm that that also works for you?

**Comment by egarpor** [comment]
Thanks for the fix :) It works as expected now.
