### ISSUE TITLE
Bcftools plugins missing

### ISSUE THREAD

**Issue by gtamazian** [Homebrew/homebrew-science#3757]
### Troubleshooting steps taken

- [x] Ran `brew update` and retried to install **bcftools**.
- [x] Ran `brew doctor`, fixed as many issues as possible and retried to install **bcftools**.
- [x] Checked that a similar issue hasn't already been filed.
- [x] Looked up the software bug tracker if reporting a build error.

### Bug report

The formula does not install **bcftools** plugins. The following error message is shown if one tries to get the list of installed plugins using `bcftools plugin -l`:

```
No functional bcftools plugins were found in
	BCFTOOLS_PLUGINS="/usr/local/lib/bcftools_plugins".

- Is the plugin path correct?

- Are all shared libraries, namely libhts.so, accessible? Verify with
   on Mac OS X: `otool -L your/plugin.so` and set DYLD_LIBRARY_PATH if they are not
   on Linux:    `ldd your/plugin.so` and set LD_LIBRARY_PATH if they are not

- If not installed systemwide, set the environment variable LD_LIBRARY_PATH (linux) or
DYLD_LIBRARY_PATH (mac) to include directory where *libhts.so* is located.

- Run "bcftools plugin -lv" for more detailed error output.
```

I suppose that the **bcftools** formula should be modified to copy the plugin files to the appropriate directory and make them accessible to **bcftools**.

**Comment by tdsmith** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? [This document](https://git.io/vo2xc) should give you a head start and we'd be more than happy to walk you through it if you have any questions.

**Comment by gtamazian** [comment]
Sorry, it seems that there was something wrong with my local installation of **bcftools**. I reinstalled the formula and the plugins worked perfectly. I am closing the issue.

**Comment by tdsmith** [comment]
No problem!
