### ISSUE TITLE
arpack install fails - cross compiling configure error

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew-science#3758]
brew is failing to install slepc. It is hard for me to follow the output, but it looks like it fails trying to install arpack, which I already successfully installed.

    $ brew install arpack
    Warning: homebrew/science/arpack-3.2.0_1 already installed

    $ brew install slepc
    ==> Installing slepc from homebrew/science
    ==> Installing dependencies for homebrew/science/slepc: arpack
    ==> Installing homebrew/science/slepc dependency: arpack
    ==> Using Homebrew-provided fortran compiler.
    This may be changed by setting the FC environment variable.
    ==> Downloading https://github.com/opencollab/arpack-ng/archive/3.2.0.tar.gz
    Already downloaded: /Users/jquick/Library/Caches/Homebrew/arpack-3.2.0.tar.gz
    ==> ./configure F77=/usr/local/bin/mpif77 --prefix=/usr/local/Cellar/arpack/3.2.0_1/libexec --enable-mpi --with-blas=-L/usr/local/opt/veclibfo
    Last 15 lines from /Users/jquick/Library/Logs/Homebrew/arpack/01.configure:
    checking for a thread-safe mkdir -p... ./install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking whether the Fortran 77 compiler works... yes
    checking for Fortran 77 compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/private/tmp/arpack-20160617-31177-1xcr2y1/arpack-ng-3.2.0':
    configure: error: cannot run Fortran 77 compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/brew):
      https://github.com/Homebrew/homebrew-science/issues
    
    $ brew gist-logs slepc
    Error: No logs.

    $ brew gist-logs arpack
    https://gist.github.com/6fa46f8e922f708d9d0ee8b1a87f60cd

**Comment by dpo** [comment]
It works for me and it worked on the  bot. It could be due to the fact that gcc was updated recently. Could you try `brew upgrade gcc open-mpi`, `brew uninstall -f arpack` and then `brew install slepc`?

**Comment by kilojoules** [comment]
Thanks for the tip! That didn't work. Also, I have confirmed I can compile and run fortran 77 files.

    $ brew upgrade gcc open-mpi
    Error: gcc 6.1.0 already installed
    Error: open-mpi 1.10.2_1 already installed

    $ brew upgrade

    $ brew uninstall -f arpack

    $ brew install slepc
    ==> Installing slepc from homebrew/science
    ==> Installing dependencies for homebrew/science/slepc: arpack
    ==> Installing homebrew/science/slepc dependency: arpack
    ==> Using Homebrew-provided fortran compiler.
    This may be changed by setting the FC environment variable.
    ==> Downloading https://github.com/opencollab/arpack-ng/archive/3.2.0.tar.gz
    Already downloaded: /Users/jquick/Library/Caches/Homebrew/arpack-3.2.0.tar.gz
    ==> ./configure F77=/usr/local/bin/mpif77 --prefix=/usr/local/Cellar/arpack/3.2.0_1/libexec --enable-mpi --with-blas=-L/usr/local/opt/veclibfo
    Last 15 lines from /Users/jquick/Library/Logs/Homebrew/arpack/01.configure:
    checking for a thread-safe mkdir -p... ./install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking whether the Fortran 77 compiler works... yes
    checking for Fortran 77 compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/private/tmp/arpack-20160617-49748-1tepjr3/arpack-ng-3.2.0':
    configure: error: cannot run Fortran 77 compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/brew):
      https://github.com/Homebrew/homebrew-science/issues
    
    These open issues may also help:
    arpack install fails - cross compiling configure error https://github.com/Homebrew/homebrew-science/issues/3758

**Comment by dpo** [comment]
Something else is out of date. Perhaps `veclibfort`?

**Comment by kilojoules** [comment]
$ brew upgrade veclibfort
    Error: homebrew/science/veclibfort 0.4.2_3 already installed

I ran `brew update`. doesn't that mean all my packages are up-do-date?

**Comment by dpo** [comment]
`brew update` means the formulas are up to date. `brew upgrade` would bring all the installed packages up to date.

I just tried on 10.10 and it worked fine. Something's up. Do you have another gfortran lying around? Or another gcc from MacPorts or Fink?

**Comment by kilojoules** [comment]
I have not installed any packages with macports or fink. I'm pretty sure that I only have the brew versions of gcc and fortran installed. I ran `brew upgrade` and all my packages are up-to-date but the error is persisting. I don't understand - I already have arpack installed. Why is slepc trying to install arpack in the first place, and why does this install fail but  `brew install arpack` work?

**Comment by dpo** [comment]
`slepc` needs to install `arpack` with MPI support. Because that's not what the default `arpack` install does, it needs to be recompiled. Plain `brew install arpack` just installs the precompiled binaries. You'd get the same error with `brew install arpack --with-mpi`.

**Comment by kilojoules** [comment]
I found that to be true. Is there any way I can test for another gfortran or gcc? The only thing I can think of is that, for another project, I was using gcc/g++ as my homebrew compiler. It's possible that I still have a package compiled using gcc/g++, although I have confirmed that gcc and openmpi were built with clang.

**Comment by dpo** [comment]
I don't know of a sure shot method but how about just typing `gfortran` at the command line and, without inserting a space, just tabbing to see what completions come up? In my case,
```bash
$ gfortran  # here I hit TAB twice
gfortran    gfortran-6  
```

**Comment by kilojoules** [comment]
reinstalling all my homebrew packages solved this problem. I suspect it was in the netcdf package, but it's just a hunch
