### ISSUE TITLE
Installing lammps using homebrew

### ISSUE THREAD

**Issue by aadrych** [Homebrew/homebrew-science#3791]
Hi, 
I've just been trying to install lammps using hombrew. 
When I tried running it, there was no links to lammps, after running the brew doctor there were some errors with the keg links so I ran the keg links to the lammps library and gcc but I get the following error:
Alexs-MacBook-Pro:~ mbdxkaa8$ brew test lammps -v
Testing homebrew/science/lammps
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160629-4414-v4p3my.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb -v
==> lammps -in /usr/local/share/lammps/bench/in.lj
dyld: Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/bin/lammps
  Reason: image not found
Error: homebrew/science/lammps: failed
Failed executing: lammps -in /usr/local/share/lammps/bench/in.lj
/usr/local/Library/Homebrew/formula.rb:1494:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1431:in `open'
/usr/local/Library/Homebrew/formula.rb:1431:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb:212:in `block (2 levels) in <class:Lammps>'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb:211:in `block in <class:Lammps>'
/usr/local/Library/Homebrew/formula.rb:1336:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1330:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>' 

Also, the next step would be to link the lammps library so that python can run it. How do I do this without knowledge of where the library is for lammps? Or does homebrew automatically link this with python? 

Thanks in advance.

**Comment by dpo** [comment]
Try to upgrade your gcc: `brew upgrade gcc`.

**Comment by ouojeda** [comment]
Sorry, I tried brew upgrade gcc,
Same error.
Thanks

**Comment by dpo** [comment]
The lammps bottles should point to gcc6, not 5. Could you uninstall lammps and show us the entire procedure you went through? The output of `brew doctor` would also help. Thanks.

**Comment by tdsmith** [comment]
Be sure to run `brew update` before you reinstall lammps.

**Comment by mariecd** [comment]
Hi,
I've tried all the above and I still get the same error message as aadrych.
I've also tried to uninstall home-brew, reinstall it and then reinstall lammps but it's not working. Also, when I run brew doctor, my system is ready to brew.
Thanks :)

**Comment by dpo** [comment]
Could you try `brew uninstall -f $(brew deps lammps)` followed by `brew update` and `brew install lammps`? If you're still getting the same error, you can always build from source with `brew install -s lammps` while I look into the issue.

**Comment by mariecd** [comment]
Thanks for the help,
I've uninstall homebrew then reinstall it and install lammps from the source. It's now working so thanks a lot!

**Comment by ouojeda** [comment]
Mine work too!. I had to uninstall LAMMPS, the dependencies and do the brew update. After installing again from source, it worked.

**Comment by dpo** [comment]
LAMMPS was just upgraded to the newer version and bottles rebuilt. Let's know if it works for you now.
