### ISSUE TITLE
Update LAMMPS to latest version (May 2016)

### ISSUE THREAD

**Issue by sterlingzhan** [Homebrew/homebrew-science#3809]
Hi!

Would it be possible to update the version of LAMMPS available through homebrew-science to the latest version (May 2016, instead of February 2015)? 

Thanks in advance! I know that this is probably a relatively simple task, but I'm a bit of a newbie here and I'm just figuring out how things work. I enthusiastically look forward to contributing once I get the hang of things!

Sterling

**Comment by dpo** [comment]
Done! Enjoy!
