### ISSUE TITLE
HDF5 Compiler Reports Incorrect Include Path

### ISSUE THREAD

**Issue by breannansmith** [Homebrew/homebrew-science#3823]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

- Brief summary of issue:

The h5cc executable installed with HDF5 1.8.16_1 reports an incorrect include path of '/usr/include' -- this should instead be '/usr/local/include'. This leads to build failures when used with the latest version of CMake provided by Homebrew.

- Please state the complete command that you issued.

Command:
````
/usr/local/bin/h5cc -show
````

Result:
````
clang -I/usr/include -I/usr/local/opt/szip/include -L/usr/local/Cellar/hdf5/1.8.16_1/lib /usr/local/Cellar/hdf5/1.8.16_1/lib/libhdf5_hl.a /usr/local/Cellar/hdf5/1.8.16_1/lib/libhdf5.a -L/usr/lib -L/usr/local/opt/szip/lib -lsz -lz -ldl -lm
````

The first include '-I/usr/include' is incorrect.

**Comment by tdsmith** [comment]
It includes the path to the hdf5 headers just fine; I don't see that it's wrong. Can you be more specific about the problem you're encountering?

**Comment by breannansmith** [comment]
h5cc reports '/usr/include', while Homebrew installs under '/usr/local' -- the second include path to szip above is correct, but the path to the core Homebrew include path is not. Under El Capitan:
````
$ ls /usr/include/hdf5.h
ls: /usr/include/hdf5.h: No such file or directory
$ ls /usr/local/include/hdf5.h
/usr/local/include/hdf5.h
````

Looking further down the output of 'h5cc -show', the library path is reported incorrectly as well:
````
$ ls /usr/lib/libhdf5.a
ls: /usr/lib/libhdf5.a: No such file or directory
$ ls /usr/local/lib/libhdf5.a
/usr/local/lib/libhdf5.a
````

**Comment by tdsmith** [comment]
Oh, odd! Sorry, I didn't look closely enough and assumed your output was the same as mine:

```
tim@rocketman:homebrew-core (master)$ h5cc -show
clang -I/usr/include -I/usr/local/opt/szip/include -L/usr/local/Cellar/hdf5/1.8.16_1/lib /usr/local/Cellar/hdf5/1.8.16_1/lib/libhdf5_hl.a /usr/local/Cellar/hdf5/1.8.16_1/lib/libhdf5.a -L/usr/lib -L/usr/local/opt/szip/lib -lsz -lz -ldl -lm
```

Mine does look correct. Have you updated Homebrew lately? What's the output of `brew config`?

**Comment by tdsmith** [comment]
Which is ALSO wrong, nevermind

**Comment by tdsmith** [comment]
My mistake; the include path does look incorrect. The path to the static hdf5 library is reported correctly, though.

OTOH: if you run `h5cc -show -c`, the include path is printed correctly. I don't know how to use h5cc but if this is a bug I don't think it's Homebrew's doing and I'd encourage you to report it to the hdf5 developers.

**Comment by tdsmith** [comment]
In fact, if you give it a non-empty .c file on the command line, the include path is also included correctly; check with:

```
echo foo > dummy.c
h5cc -echo dummy.c
```

I think this is working fine; will close. Thanks!
