### ISSUE TITLE
Building express fails: library not found for -lprotobuf

### ISSUE THREAD

**Issue by lparsons** [Homebrew/homebrew-science#3828]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
### Bug reports / build errors:
- The build fails with the error `ld: library not found for -lprotobuf`
- `brew install express`
- https://gist.github.com/4f0c5eefe78fdb26ef9d9e447e90529d

**Comment by dpo** [comment]
I'm on 10.9 but I can't reproduce this. Could you try `brew uninstall -f $(brew deps -r express)` followed by `brew update` and `brew install express`?

**Comment by tseemann** [comment]
I get the same problem on Linux.

https://gist.github.com/2663310d4e6d8bf18c431963218be55a

**Comment by ilovezfs** [comment]
The difference is probably due to superenv on Homebrew making protobuf findable, but we may need to give cmake a little more help with the location on Linuxbrew. In any case, you should be able to work around it by building --without-protobuf.

**Comment by ilovezfs** [comment]
Hmm, no I see it found it in your log.

@tseemann is your protobuf installed from the bottle by any chance?

**Comment by tseemann** [comment]
Yes:
```
brew info protobuf
protobuf: stable 2.6.1 (bottled), devel 3.0.0-beta-4, HEAD
Protocol buffers (Google's data interchange format)
https://github.com/google/protobuf/
/home/linuxbrew/.linuxbrew/Cellar/protobuf/2.6.1 (124 files, 8.7M) *
  Poured from bottle on 2016-07-29 at 22:31:59
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/protobuf.rb
==> Dependencies
Build: gpatch ✔, homebrew/dupes/unzip ✔
```

**Comment by ilovezfs** [comment]
@tseemann do you mind trying rebuilding that from source, and then seeing if the express issue still occurs?

**Comment by ilovezfs** [comment]
Also worth noting that Google just released protobuf 3.0.0:
https://github.com/google/protobuf/releases/tag/v3.0.0
https://github.com/Homebrew/homebrew-core/pull/3415

**Comment by tseemann** [comment]
@ilovezfs that seemed to work!
```
brew reinstall protobuf -s
brew install express

==> Summary
  /home/linuxbrew/.linuxbrew/Cellar/protobuf/2.6.1: 152 files, 9.0M, built in 38 seconds
...
==> Pouring express-1.5.1_3.x86_64_linux.bottle.tar.gz
  /home/linuxbrew/.linuxbrew/Cellar/express/1.5.1_3: 4 files, 3.9M
```

**Comment by ilovezfs** [comment]
@tseemann OK, that's good news. So the question is whether regenerating the bottles will actually fix anything, or if it'll still persist due to conflicting C++ standards or some such problem like that.

**Comment by rafaeltiveron** [comment]
Hello again

I tryed to install express when at make event I've got this error message:

`brew install express`

`==> Installing express from homebrew/science`

`
==> Downloading http://bio.math.berkeley.edu/eXpress/downloads/express-1.5.1/express-1.5.1-src.tgz
Already downloaded: /home/bioroot/.cache/Homebrew/express-1.5.1.tgz
`

`==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/bio`

`
==> make install
Last 15 lines from /home/bioroot/.cache/Homebrew/Logs/express/02.make:
/home/bioroot/.linuxbrew/bin/g++-5   -Wall -DNDEBUG   -L/home/bioroot/.linuxbrew/lib -Wl,--dynamic-linker=/home/bioroot/.linuxbrew/lib/ld.so -Wl,-rpath,/home/bioroot/.linuxbrew/lib CMakeFiles/express.dir/biascorrection.cpp.o CMakeFiles/express.dir/bundles.cpp.o CMakeFiles/express.dir/directiondetector.cpp.o CMakeFiles/express.dir/fragments.cpp.o CMakeFiles/express.dir/lengthdistribution.cpp.o CMakeFiles/express.dir/main.cpp.o CMakeFiles/express.dir/mapparser.cpp.o CMakeFiles/express.dir/markovmodel.cpp.o CMakeFiles/express.dir/mismatchmodel.cpp.o CMakeFiles/express.dir/robertsfilter.cpp.o CMakeFiles/express.dir/sequence.cpp.o CMakeFiles/express.dir/targets.cpp.o CMakeFiles/express.dir/threadsafety.cpp.o CMakeFiles/express.dir/alignments.pb.cc.o CMakeFiles/express.dir/targets.pb.cc.o  -o express -rdynamic /home/bioroot/.linuxbrew/lib64/libboost_thread-mt.so /home/bioroot/.linuxbrew/lib64/libboost_system-mt.so /home/bioroot/.linuxbrew/lib64/libboost_filesystem-mt.so /home/bioroot/.linuxbrew/lib64/libboost_program_options-mt.so /home/bioroot/.linuxbrew/lib64/libboost_date_time-mt.so /home/bioroot/.linuxbrew/lib64/libboost_chrono-mt.so /home/bioroot/.linuxbrew/lib64/libboost_atomic-mt.so /home/bioroot/.linuxbrew/lib64/libz.so ../bamtools/lib/libbamtools.a -lz -lpthread -Wl,-Bstatic -lprotobuf -Wl,-Bdynamic -Wl,-rpath,/home/bioroot/.linuxbrew/lib64 
`
```
CMakeFiles/express.dir/mapparser.cpp.o: In function `MapParser::MapParser(Library*, bool)':
mapparser.cpp:(.text+0x3ca): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
mapparser.cpp:(.text+0x4a0): undefined reference to `BamTools::BamWriter::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BamTools::SamHeader const&, std::vector<BamTools::RefData, std::allocator<BamTools::RefData> > const&)'
CMakeFiles/express.dir/mapparser.cpp.o: In function `BAMParser::header[abi:cxx11]() const':
mapparser.cpp:(.text._ZNK9BAMParser6headerB5cxx11Ev[_ZNK9BAMParser6headerB5cxx11Ev]+0x2e): undefined reference to `BamTools::BamReader::GetHeaderText[abi:cxx11]() const'
CMakeFiles/express.dir/mapparser.cpp.o: In function `bool BamTools::BamAlignment::AddTag<float>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float const&)':
mapparser.cpp:(.text._ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_[_ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_]+0x52): undefined reference to `BamTools::BamAlignment::IsValidSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
mapparser.cpp:(.text._ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_[_ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_]+0xe6): undefined reference to `BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'
```

`collect2: error: ld returned 1 exit status`
`make[2]: ** [src/express] Erro 1`
`make[2]: Saindo do diretório '/tmp/express-20160803-22305-11g4yt5/express-1.5.1-src'`
`make[1]: ** [src/CMakeFiles/express.dir/all] Erro 2`
`make[1]: Saindo do diretório '/tmp/express-20160803-22305-11g4yt5/express-1.5.1-src'`
`make: ** [all] Erro 2`


```
READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues
```

```
These open issues may also help:
Building express fails: library not found for -lprotobuf https://github.com/Homebrew/homebrew-science/issues/3828
```

I tried to reinstall -protobuf, but it didn't resolve! Any idea?
My system: Centos 7 x64 bits / 8 gb RAM / 4 CPUs
* I have updated and upgraded Linuxbrew recently.

**Comment by ilovezfs** [comment]
>I tried to reinstall -protobuf, but it didn't resolve! Any idea?

@rafaeltiveron  Did you
A)
`brew reinstall protobuf`
or
B)
`brew reinstall  protobuf -s`
or
C) something else

**Comment by miltontan** [comment]
Hello, I am having a problem installing express as well, and it led me here. I have gone through the typical brew update, brew doctor, and such as instructed. I also used 
`brew reinstall protobuf -s`
as mentioned above, but that did not solve the problem.

```
==> Installing express from homebrew/science
==> Downloading http://bio.math.berkeley.edu/eXpress/downloads/express-1.5.1/express-1.5.1-src.tgz
Already downloaded: /data1/home/mtan/.cache/Homebrew/express-1.5.1.tgz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/data1/home/mtan/.linuxbrew/Cellar/express/1.5.1_5 -DCMAKE_BUILD_TYPE=Relea
==> make install
Last 15 lines from /data1/home/mtan/.cache/Homebrew/Logs/express/02.make:
CMakeFiles/express.dir/main.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/express.dir/mapparser.cpp.o: In function `MapParser::MapParser(Library*, bool)':
mapparser.cpp:(.text+0x3ca): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
mapparser.cpp:(.text+0x4a0): undefined reference to `BamTools::BamWriter::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BamTools::SamHeader const&, std::vector<BamTools::RefData, std::allocator<BamTools::RefData> > const&)'
CMakeFiles/express.dir/mapparser.cpp.o: In function `BAMParser::header[abi:cxx11]() const':
mapparser.cpp:(.text._ZNK9BAMParser6headerB5cxx11Ev[_ZNK9BAMParser6headerB5cxx11Ev]+0x2e): undefined reference to `BamTools::BamReader::GetHeaderText[abi:cxx11]() const'
CMakeFiles/express.dir/mapparser.cpp.o: In function `bool BamTools::BamAlignment::AddTag<float>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float const&)':
mapparser.cpp:(.text._ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_[_ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_]+0x52): undefined reference to `BamTools::BamAlignment::IsValidSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
mapparser.cpp:(.text._ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_[_ZN8BamTools12BamAlignment6AddTagIfEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_RKT_]+0xe6): undefined reference to `BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [src/express] Error 1
make[2]: Leaving directory `/tmp/express-20160912-12295-1m446ak/express-1.5.1-src'
make[1]: *** [src/CMakeFiles/express.dir/all] Error 2
make[1]: Leaving directory `/tmp/express-20160912-12295-1m446ak/express-1.5.1-src'
make: *** [all] Error 2
```

**Comment by jonchang** [comment]
There's some sort of symbol visibility issue happening, I suspect that it's specific to g++-5. I'll try to dig into this deeper later this week. I think Linuxbrew is having a gcc version bump soon so maybe that will fix things.

**Comment by ckeeling** [comment]
I am having the same issue with `brew install express`

I tried without success:
`brew reinstall protobuf -s`
`brew install express`

https://gist.github.com/54f9c21b993cda49b216c6e75d3d8a0e

**Comment by ckeeling** [comment]
Found a solution--install express binary manually into Cellar:
`cd ~/.linuxbrew/Cellar/express`
`wget http://bio.math.berkeley.edu/eXpress/downloads/express-1.5.1/express-1.5.1-linux_x86_64.tgz`
`tar zxvf express-1.5.1-linux_x86_64.tgz`
`cd ~/.linuxbrew/bin`
`link -s ~/.linuxbrew/Cellar/express/express-1.5.1-linux_x86_64/express express`

Now, I can successfully install trinity without it trying to install express from source:
`brew install homebrew/science/trinity --without-express`

**Comment by sjackman** [comment]
I'm attempting to build bottles for `express` at PR https://github.com/Homebrew/homebrew-science/pull/5244

**Comment by sjackman** [comment]
@ckeeling The bottle build was successful, and the bottle is relocatable, so from now on you'll be able to simply `brew install express` and install the binary rather than build from source.
