### ISSUE TITLE
Trouble installing octave to mac os 10.11.5

### ISSUE THREAD

**Issue by casperla01** [Homebrew/homebrew-science#3829]
Hi. I am having trouble installing octave on mac el capitan 10.11.5
I have run 'brew update' and 'brew upgrade'
I have fixed all issues from running 'brew doctor' 
Thre are no permission errors

I used the command 'brew install octave'

this is the output

-----------

Last 15 lines from /Users/casperla/Library/Logs/Homebrew/octave/02.make:
      F__magick_finfo__(octave_value_list const&, int) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
      fill_exif(octave_scalar_map&, Magick::Image&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
      fill_exif_ints(octave_scalar_map&, Magick::Image&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
      fill_exif_floats(octave_scalar_map&, Magick::Image&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
      octave_value_list read_images<boolNDArray>(std::__1::vector<Magick::Image, std::__1::allocator<Magick::Image> >&, Array<int> const&, int const&, octave_scalar_map const&) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
      octave_value_list read_images<intNDArray<octave_int<unsigned char> > >(std::__1::vector<Magick::Image, std::__1::allocator<Magick::Image> >&, Array<int> const&, int const&, octave_scalar_map const&) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
      ...
  "Magick::CoderInfo::CoderInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      F__magick_formats__(octave_value_list const&, int) in libcorefcn.a(corefcn_libcorefcn_la-__magick_read__.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [liboctinterp.la] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by dpo** [comment]
Could you post the output of `brew gist-logs octave`?

**Comment by casperla01** [comment]
Yes. it can be found here
https://gist.github.com/anonymous/8e7c3e32287150bbd282318b481ddf80

**Comment by dpo** [comment]
Sorry for the delay. Could you try `brew uninstall -f $(brew deps -r octave)` followed by `brew install octave`?

**Comment by dpo** [comment]
We just updated `octave` so I'm going to close this. Please try the solution above and open a new issue if problems persist. Thanks.
