### ISSUE TITLE
problem passing argument with `=` to formula

### ISSUE THREAD

**Issue by houtanb** [Homebrew/homebrew-science#3847]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?

### Bug reports / build errors:
- Brief summary of issue:
Install options containing an `=` are not correctly read via `ARGV.value`. For example, insert
```
    puts args
    abort
```
on line 51 of `abyss.rb` and run `brew install abyss --enable-maxk=44`. This will output:
```
--enable-maxk=
--prefix=/usr/local/Cellar/abyss/1.9.0
--disable-dependency-tracking
```
when it should output
```
--enable-maxk=44
--prefix=/usr/local/Cellar/abyss/1.9.0
--disable-dependency-tracking
```

- Please state the complete command that you issued.
`brew install abyss --enable-maxk=44`

- Please do not post lengthy build output here. Instead provide a link to a gist.
https://gist.github.com/houtanb/4497e74bb8a42a35da2554423e75d2fb

- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).
https://gist.github.com/anonymous/c255205cc5fdf483b9f6ded7d741bdf7

**Comment by Moisan** [comment]
This does not seem to be Formula dependent, I can reproduce this on other formulas such as cantera.

**Comment by houtanb** [comment]
@Moisan yes, I noticed it on another formula originally. I just posted about this one because it dealt with this type of option in a very simple and direct way.

**Comment by dpo** [comment]
Pinging @UniqMartin @xu-cheng

**Comment by UniqMartin** [comment]
Sorry for introducing this bug and massive thanks to @xu-cheng for the quick fix!
