### ISSUE TITLE
Weird random memory error in cddlib (both 0.94g and 0.94h) when built through homebrew (no issues if manually build)

### ISSUE THREAD

**Issue by enriquefernandez** [Homebrew/homebrew-science#3852]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Tried newer version of library (0.94h) than the one in homebrew/science (0.94g) with homebrew build system and got the same problem
### Bug reports / build errors:
- Brief summary of issue:

Building cddlib through homebrew works fine and the library seems to get build properly.

However, the built library seems to have some memory corruption issues somewhere.
My code works fine with this library about half the time, if not less.

I've checked and checked my code for errors to see if I'm doing anything wrong but can't figure it out.

Replacing the homebrew built library of cddlib (libcdd.dylib) by a manually built one completely eliminates the issues.

The steps to build the library by hand are
1. Download and extract the code from https://www.inf.ethz.ch/personal/fukudak/cdd_home/
2. Run ./configure
3. Run make
4. In the lib-src/.libs folder of cddlib, run `cp libcdd.0.dylib /usr/local/lib/libcdd.dylib`

My code works perfectly with this hand-built library. I am running the same code 100 times with no errors. With the homebrew-built library, I get a memory fault error almost immediately or in the first 5 runs of the exact same code.

I'm using lisp SBCL to call the cddlib library and the error I get is a `#<SB-SYS:MEMORY-FAULT-ERROR {10067CE2E3}>` in a foreign function call.

Again, this error never happens with the cdd library built by hand.
- Please state the complete command that you issued.

`brew install -v cddlib`

vs hand building with `./configure`, then `make`, gives me the following output:

https://gist.github.com/enriquefernandez/74952e790389f9b8c33c5a53309a2640

Looking at the logs it seems like the hand building of the library is using gcc, while homebrew is trying to use clang?
I don't think I have changed the compiler defaults of this computer in any way.

Also, both libraries seem to have fairly different sizes.

homebrew built cddlib.dylib: 119628
hand built cddlib.dylib: 148960

I'm running 10.11.5.

```
$ brew --config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b9a2833bc3c6bc8e7b7344e8178ce98e29ebe4b
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 51f948dc11b2380a4c9211d0cec8d16726a6739a
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/efernan/miniconda2/bin/python => /Users/efernan/miniconda2/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.8.0_91
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

```
$ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dpo** [comment]
Does it work if you run `brew install cddlib --gcc=gcc-6.1`?

**Comment by enriquefernandez** [comment]
I won't have access to my computer until Monday night, but I don't think so. 

I tried building the formula with 'fails with clang' and I think this is exactly what it did. 

Does brew setup environment variables before running configure and make? How do I know what those variables are?

Just trying to understand why running commands that look the same produce different builds...

**Comment by dpo** [comment]
You can see all environment variables by running `brew install -i cddlib`. You'll drop to a shell, where you can run `env`. What you can also try is `brew install cddlib --env=std`.

**Comment by enriquefernandez** [comment]
Perfect, thanks. 
I'll try that tomorrow and report back.

**Comment by enriquefernandez** [comment]
Ok, I just tried this, and I'm still getting weird results.

Doing `brew install cddlib --env=std` produces no changes. It seems like brew is still using `clang` as the compiler, and I get the same repeatable random crashes when using the library.

What is also weird, is that if I force homebrew to use the gcc-6 compiler with `brew install -v --cc=gcc-6 cddlib`, homebrew uses gcc-6, but I still get the same crashes when using the library.

However, if I compile the library on my own with gcc-6 by unzipping the cddlib source and doing:

- `./configure CC=gcc-6`
- `make`
- copying `cp libcdd.0.dylib /usr/local/lib/libcdd.dylib`

then I don't get any crashes at all, no matter how many times I run the app.

It also looks like the binary .dylib that I get doing this is significantly bigger than the one I get when compiling through homebrew.

Any ideas?

**Comment by dpo** [comment]
How about `--cc=gcc-6 --env=std`?

**Comment by enriquefernandez** [comment]
Nop, it doesn't work either. Same memory crash error.

Worth noting that `brew install --cc=gcc-6 --env=std -v cddlib` produces `libcdd.0.dylib` with size 139376, while the manual building method with `./configure CC=gcc-6` produces `libcdd.0.dylib` with size 172500.

I really don't understand why...

**Comment by enriquefernandez** [comment]
By the way, I also tried manually building with `./configure CC=clang` and then copying the library (`cp libcdd.0.dylib /usr/local/lib/libcdd.dylib` from `lib-src/.libs/` and it also works perfectly.

So it is not the compiler, it seems...

**Comment by dpo** [comment]
One would need to carefully compare the full Homebrew logs with the output of a manual compilation.

**Comment by iMichka** [comment]
@enriquefernandez Nobody really worked on this since July 2016. As long as we don't have both log files requested by @dpo, we will not be able to make progress on this.
