### ISSUE TITLE
CGNS 3.3

### ISSUE THREAD

**Issue by q-p** [Homebrew/homebrew-science#3867]
### Update CGNS to version 3.3?

CGNS has been updated in January, and I for one use it occasionally. :)

This update might pose some problems though, as with no additional configuration settings, the cg_sizet type is changed from `int` to `unsigned long` (I think), so some code using this library may no longer compile if it assumes `int` and `cg_sizet` are the same type.

Also, the names of configuration options seems to have changed. I successfully build 3.3 with the following formula. Changes made include:
- Updated homepage
- Making fortran bindings optional
- Updating the names of the defines / configuration parameters for cmake

```ruby
class Cgns < Formula
  homepage "http://cgns.org/"
  url "https://github.com/CGNS/CGNS/archive/v3.3.0.tar.gz"
  sha256 "8422c67994f8dc6a2f201523a14f6c7d7e16313bdd404c460c16079dbeafc662"
  revision 1

  depends_on :fortran => :optional
  depends_on "cmake" => :build
  depends_on "hdf5" => :recommended
  depends_on "szip"

  def install
    args = std_cmake_args + [
      "-DCGNS_ENABLE_TESTS=YES",
    ]

    args << "-DCGNS_ENABLE_64BIT=YES" if Hardware.is_64_bit? && MacOS.version >= :snow_leopard
    args << '-DCGNS_ENABLE_FORTRAN=YES' if build.with? "fortran"

    if build.with? "hdf5"
      args << "-DCGNS_ENABLE_HDF5=YES"
      args << "-DHDF5_NEED_ZLIB=YES"
      args << "-DHDF5_NEED_SLIB=YES"
      args << "-DCMAKE_SHARED_LINKER_FLAGS=-lhdf5"
    end

    mkdir "build" do
      system "cmake", "..", *args
      system "make"
      system "ctest --output-on-failure"
      system "make", "install"
    end
  end
end
```

**Comment by dpo** [comment]
Thanks. It would be great if you could submit a PR with a test added to the formula.

**Comment by q-p** [comment]
Not sure what the deal is with the ParaView test. It seems a bit like it is linked to old versions of the libraries (e.g. some ffmpeg ones which certainly don't have anything to do with cgns).

**Comment by q-p** [comment]
Depends on #3880
