### ISSUE TITLE
paraview failed to build on os x 10.11.5

### ISSUE THREAD

**Issue by thomasfangyi** [Homebrew/homebrew-science#3880]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

brew install paraview failed on os x 10.11.5

gist-logs at https://gist.github.com/thomasfangyi/9810b3322cfdd3581c8d1f222917e9fe

According to @ilovezfs 

> This has already been fixed upstream: http://www.paraview.org/Bug/view.php?id=16001

**Comment by dpo** [comment]
Should be fixed.
