### ISSUE TITLE
Octave formula causes a deprecation warning

### ISSUE THREAD

**Issue by ararslan** [Homebrew/homebrew-science#3920]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

- Brief summary of issue:

```
Updated Homebrew from 209d9e8 to a5a930c.
Warning: Calling MacOS.clang_version is deprecated!
Use DevelopmentTools.clang_version instead.
/usr/local/Library/Taps/homebrew/homebrew-science/octave.rb:23:in `<class:Octave>'
Please report this to the homebrew/science tap!
```
- Please state the complete command that you issued.

```
brew update
```

**Comment by stefanofiorentino** [comment]
Same warning here, will try to find out the recipe which causes the warning.

**Comment by stefanofiorentino** [comment]
@ararslan octave.rb already point to DevelopmentTools as you can see [here](https://github.com/Homebrew/homebrew-science/blob/master/octave.rb#L23).
Regards.

**Comment by ilovezfs** [comment]
Yup this was fixed already, so you shouldn't see it the next time you brew update.

**Comment by ararslan** [comment]
Awesome, thanks @ilovezfs!

**Comment by ilovezfs** [comment]
@loeksnokes you are probably a victim of https://twitter.com/MacHomebrew/status/763686348041641984
