### ISSUE TITLE
augustus: undefined reference to BamTools::BamAlignment::RemoveTag

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#3929]
https://gist.github.com/anonymous/8168e5866e8f3ac1e28635f19a327546

```
/home/ubuntu/.linuxbrew/bin/g++-5 -Os -w -pipe -march=native -isystem/home/ubuntu/.linuxbrew/include -L/home/ubuntu/.linuxbrew/lib -Wl,--dynamic-linker=/home/ubuntu/.linuxbrew/lib/ld.so -Wl,-rpath,/home/ubuntu/.linuxbrew/lib  -std=c++0x -L/home/ubuntu/.linuxbrew/lib -Wl,--dynamic-linker=/home/ubuntu/.linuxbrew/lib/ld.so -Wl,-rpath,/home/ubuntu/.linuxbrew/lib filterBam.o MatePairs.o getReferenceName.o initOptions.o SingleAlignment.o printElapsedTime.o sumMandIOperations.o sumDandIOperations.o PairednessCoverage.o -o filterBam -lbamtools -lz 
filterBam.o: In function `processQuery(std::vector<BamTools::BamAlignment, std::allocator<BamTools::BamAlignment> >&, std::vector<BamTools::RefData, std::allocator<BamTools::RefData> > const&, globalOptions_t, BamTools::BamWriter*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, optionalCounters_t&, std::vector<PairednessCoverage, std::allocator<PairednessCoverage> >&, std::vector<int, std::allocator<int> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::multimap<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::multimap<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > > >&)':
filterBam.cc:(.text+0x408e): undefined reference to `BamTools::BamAlignment::RemoveTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

**Comment by sjackman** [comment]
I can reproduce this build error.

**Comment by sjackman** [comment]
Perhaps `augustus` 3.2.2 is not compatible with `bamtools` 2.4.0?

**Comment by sjackman** [comment]
No, I don't think that's it. `bamtools` was updated to 2.4.0 on 2015-06-24 and `augustus` was updated to 3.2.2 on 2016-04-19.

**Comment by sjackman** [comment]
The bottle built successfully on Ubuntu 14 with GCC 4.8. It fails for me with GCC 5.3. Perhaps it's a compiler version issue.

**Comment by bstamps** [comment]
I've got the same error on Ubuntu 16.04- any luck on your end getting this to compile?

**Comment by sjackman** [comment]
No, I haven't had a chance to trouble shoot this build error. There's a precompiled binary bottle, but it's marked as being non-relocatable. If you install Linuxbrew in `/home/linuxbrew/.linuxbrew` that precompiled binary bottle will be used by default. If you want to live dangerously, `brew install --force-bottle augustus` *may* work (no promises), but it's worth a shot.

**Comment by andrewyatz** [comment]
I managed to get augustus to compile by recompiling bamtools from source. This was after a prod from another GitHub issue https://github.com/jts/sga/issues/122. Anyway do `brew install -s bamtools` and then augustus compiles.

**Comment by stephenwilliams22** [comment]
@andrewyatz this worked for me. Thanks!

**Comment by sjackman** [comment]
Superseded by https://github.com/Homebrew/homebrew-science/pull/5158
