### ISSUE TITLE
Change MacOS.clang_version to DevelopmentTools.clang_version

### ISSUE THREAD

**Issue by CodeMaxx** [Homebrew/homebrew-science#4015]
I got this error while updating today.
![image](https://s32.postimg.org/tz8hx7hut/Screen_Shot_2016_08_05_at_1_33_39_PM.png)

I would like to fix this and contribute 😄 Can someone give me pointers where to start?

**Comment by ilovezfs** [comment]
Thanks for wanting to contribute! In this case, you can run `brew update` again and then it will be fixed.

**Comment by CodeMaxx** [comment]
I didn't get an error this time. But I don't see any recent Pull Request regarding this?
