### ISSUE TITLE
mfem 3.2 build crashes

### ISSUE THREAD

**Issue by goxberry** [Homebrew/homebrew-science#4018]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue: mfem 3.2 fails to build because the KLU and BTF solvers aren't linked from SuiteSparse. I know how to fix this issue, so I will submit a patch shortly.

- Please state the complete command that you issued: `brew upgrade`

- Please do not post lengthy build output here. Instead provide a link to a gist.
See https://gist.github.com/goxberry/d55c9bfffde3c366e0cee3772016bd14

- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).
See https://gist.github.com/f656ddb0b6dc7b8ce408a908ededa026 (possibly same output as previous gist)

**Comment by dpo** [comment]
Thanks for the fix!
