### ISSUE TITLE
brew install vtk --with-qt5 fails

### ISSUE THREAD

**Issue by BertDeDeckere** [Homebrew/homebrew-science#4021]
Hi all,

I've been trying to install vtk with qt5 support for a long time now, unfortunately without much luck. Here are the steps I took:
- Ran 'brew update'
- Updated all formulas
- Ran 'brew doctor' and fixed all issues

Then in the terminal
$brew install vtk --c++11 --with-examples --with-qt5

I tried before without c++11 and exampled, but that doesn't make any difference. The brew gist logs can be found here: https://gist.github.com/d886874611aaf5c8811af5673151ed10

Unfortunately I was unable to find a solution online. Any help would be greatly appreciated!

**Comment by ilovezfs** [comment]
It doesn't look like the build is actually failing? Where's the error?

**Comment by BertDeDeckere** [comment]
The error is at the end of the make file, here is an excerpt:
-- [download 0% complete]
-- [download 100% complete]
-- Downloaded object: "/tmp/vtk-20160806-78090-11hfs8w/VTK-7.0.0/build/ExternalData/Objects/MD5/5f7cae168c119b40ab9a4cc5d6ca14f2"
-- [download 0% complete]
-- [download 100% complete]
-- Downloaded object: "/tmp/vtk-20160806-78090-11hfs8w/VTK-7.0.0/build/ExternalData/Objects/MD5/b3ae26450af0105afb8177590d83c463"
-- [download 0% complete]
-- [download 100% complete]
-- Downloaded object: "/tmp/vtk-20160806-78090-11hfs8w/VTK-7.0.0/build/ExternalData/Objects/MD5/a7a4103bd6c690db0c5031d3115ed386"
[ 47%] Built target VTKData
make: *** [all] Error 2

**Comment by ilovezfs** [comment]
@sjackman looks like this lovely formula is downloading random things off the Internets.

**Comment by ilovezfs** [comment]
It will use these formulae with those options:
```
cmake
xz
dbus
qt5
boost
libpng
freetype
fontconfig
szip
hdf5
jpeg
libtiff
sip
pyqt5
```
So you could try uninstalling all of them first.

**Comment by BertDeDeckere** [comment]
It works! I came across this thread: https://github.com/Homebrew/homebrew-science/issues/3401
When uninstalling everything (including the brewed Python) and installing VTK, it works. Upon doing so, the system Python is used and not the Python from Brew.

Jeej :-)

**Comment by ilovezfs** [comment]
@BertDeDeckere I'm glad you got it working. I think we can close this in favor of

http://www.vtk.org/Bug/view.php?id=16068
https://gitlab.kitware.com/vtk/vtk/merge_requests/1713
https://github.com/Homebrew/homebrew-science/issues/3401
https://github.com/Homebrew/homebrew-science/pull/3811

I'm still not thrilled to put it mildly with the random downloading but :see_no_evil: for now.
