### ISSUE TITLE
Trilinos download failed: 502 Bad Gateway

### ISSUE THREAD

**Issue by ashishbhole** [Homebrew/homebrew-science#4035]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x ] Checked that a similar issue hasn't already been filed?

I am facing a problem in building Trilinos12.6.2, as it is not connecting to remote server.
I am using following command
brew install trilinos --with-openblas --without-scotch --without-x11 --without-superlu_dist --without-adol-c

The error I am getting is as follows:
---------------------------------------------------
==> Downloading http://trilinos.csbsju.edu/download/files/trilinos-12.6.2-Source.tar.bz2

curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "trilinos"
Download failed: http://trilinos.csbsju.edu/download/files/trilinos-12.6.2-Source.tar.bz2
--------------------------------------------------------
What will be a remedy of this error?
Can I provide brew installer trilinos-12.6.2-Source.tar.bz2, if I separately download it from other place. If yes, how can I do this?

**Comment by ashishbhole** [comment]
I think url for downloading trilinos is wrong:
 http://trilinos.csbsju.edu/download/files/trilinos-12.6.2-Source.tar.bz2

I tried with changing it with working url. It downloads trilinos. But throws some other errors. Anybody can suggest anything?

**Comment by dpo** [comment]
Could you show what you changed and what the other errors were? Remember that if you update the `url` you also need to update the `sha256`. Brew tells you what it shoudl be.

**Comment by ashishbhole** [comment]
I changed url in trilinos.rb file to following:
https://trilinos.org/oldsite/download/files/trilinos-12.6.4-Source.tar.bz2

This url is able to download trilinos. I also changed SHA256 as suggested by brew. But still I got an error.

Output link to brew gist-logs trilinos is as follows:
https://gist.github.com/4a652e4433cde05ef9782b0a84c5d41e

I can't make out what's wrong here.

**Comment by dpo** [comment]
It seems to be a compiler issue: https://gist.github.com/anonymous/4a652e4433cde05ef9782b0a84c5d41e#file-02-cmake-L717

Could you try `brew uninstall -f $(brew deps -r trilinos)` and then `brew install trilinos`?

**Comment by dpo** [comment]
@ashishbhole ping

**Comment by ashishbhole** [comment]
Hello, I followed your guidelines brew uninstall -f $(brew deps -r trilinos) and brew install trilinos.
But received other errors. I have kind of lost the track. I will become specific with those errors shortly.
However, this was the case when I change the url and SHA for trilinos. If you could fix the original code for url of trilinos, I guess problem will be solved.

**Comment by dpo** [comment]
I'll fix this very soon but first I need to merge #4072. Thanks for your patience.

**Comment by dpo** [comment]
Should be good now. Please `brew update`.
