### ISSUE TITLE
Bottles files missing 

### ISSUE THREAD

**Issue by gaoyifan** [Homebrew/homebrew-science#4049]
The following bottles files is missing (HTTP code 404):
```
http://homebrew.bintray.com/bottles-science/edirect-3.60.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles-science/edirect-3.60.yosemite.bottle.tar.gz
http://homebrew.bintray.com/bottles-science/edirect-3.60.mavericks.bottle.tar.gz
http://homebrew.bintray.com/bottles-science/sfscode-20140719.yosemite.bottle.tar.gz
http://homebrew.bintray.com/bottles-science/sfscode-20140719.mavericks.bottle.tar.gz
http://homebrew.bintray.com/bottles-science/sfscode-20140719.mountain_lion.bottle.tar.gz
```
Could someone fix it?

**Comment by ilovezfs** [comment]
The edirect thing is a duplicate issue:
https://github.com/Homebrew/homebrew-science/issues/3793
https://github.com/Homebrew/homebrew-science/pull/3794

I'll investigate the sfscode thing, though.

**Comment by ilovezfs** [comment]
@gaoyifan sfscode should be fixed in https://github.com/Homebrew/homebrew-science/commit/5bcea95aab72e987c4074cd89a0bf3278b597e72 if you brew update.

**Comment by gaoyifan** [comment]
Thanks a lot! 
sfscode works now.

**Comment by ilovezfs** [comment]
@gaoyifan you're welcome
