### ISSUE TITLE
opencv3 fails to create '/usr/local/opt/opencv3/python3.5' folder with 'without numpy' and 'with python3' options

### ISSUE THREAD

**Issue by lendenmc** [Homebrew/homebrew-science#4082]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
- Brief summary of issue:

Without numpy support (`--without-numpy`), I observe this strange behavior. 
The `/usr/local/opt/opencv3/python2.7` folder is the only one created even though python3 support was asked as well (`--with-python3`). Why is the `/usr/local/opt/opencv3/python3.5` folder missing ?

Notice that _I don't have numpy installed while running the brew install, neither for python2 nor for python3_. 
Now whenever numpy is aready installed for python3, via pip or homebrew, then both folders will be created.
- Please state the complete command that you issued.

````
$ brew install opencv3 --with-python3 --without-numpy
[...]
$ ls /usr/local/opt/opencv3/lib/python2.7
site-packages
$ ls /usr/local/opt/opencv3/lib/python3.5
ls: cannot access '/usr/local/opt/opencv3/lib/python3.5': No such file or directory
```
However with the following:
````
$ brew install numpy --with--python3 --without-python
$ brew install opencv3 --with-python3 --without-numpy
[...]
$ ls /usr/local/opt/opencv3/lib/python2.7
site-packages
$ ls /usr/local/opt/opencv3/lib/python3.5
site-packages
```
Well it seems that numpy is not required to install python2 support for opencv3, whereas it is required for python3 support, which doesn't make sense.

This is unfortunate for those who only want to install and use numpy within python3-virtualenvs. The option `--without-numpy` would have made sense in this case.

**Comment by tdsmith** [comment]
You need numpy one way or another; you should install numpy if you want this to work. Sorry!

**Comment by tdsmith** [comment]
(it appears to work for 2.x because you're using the ancient numpy Apple ships with system Python)

**Comment by lendenmc** [comment]
No problem thank you, your explanation in your last comment made me understand that it doesn't seem to be a bug. I didn't think system Python could have an influence on this, even less that Apple already shipped an ancient numpy with it ! This is good to know.
