### ISSUE TITLE
lammps: Pypar install with homebrew.

### ISSUE THREAD

**Issue by aadrych** [Homebrew/homebrew-science#4086]
Hi, 
I am trying to run lammps using python scripts.  I've got it to work with the serial version of lammps and I've tested to see that the mpi does work with brew installed lammps but when I try to run the mpi lammps with a python script, using the recommended pypar module, it says no module available. 
How can I get homebrew to include this pypar module so I can run lammps with mpi in a python script?

Thanks in advance

**Comment by tdsmith** [comment]
Sorry, there's not enough information here to help me troubleshoot. I'm not familiar with pypar or lammps. Is pypar a Python extension module or something that lammps can be configured with?

**Comment by aadrych** [comment]
I think it is.  I recently found more documentation on what lammps recommends (this is another software recently installed with homebrew). Apparently its for getting a computer to split it's processor usage and now they've made a new module to do that called MPI4PY which did install.



________________________________

**Comment by iMichka** [comment]
This issue has been without activity for more than 6 months now. This is clearly not something we are working on or plan to work on. It is not really clear what the homebrew team is supposed to do here. 

We do not provide Pypar, so you should ask Pypar questions upstream: https://github.com/daleroberts/pypar
