### ISSUE TITLE
octave 4.0.3_1 and 4.0.3_2 are missing many files

### ISSUE THREAD

**Issue by vicnorton** [Homebrew/homebrew-science#4088]
### Bug reports / build errors:
- Brief summary of issue:
octave 4.0.3_1 and 4.0.3_2 are missing many files contained in 4.0.3
- Please state the complete command that you issued.
octave> help svd
error: unable to open /usr/local/Cellar/octave/4.0.3_2/share/octave/4.0.3/etc/macros.texi for reading
error: called from
    __makeinfo__ at line 103 column 5
    help at line 102 column 22

The file "macros.texi" is simply missing from octave 4.0.3_1 and 4.0.3_2 along with many other files and directories. Octave 4.0.3 was the last good version of octave at homebrew.

**Comment by dpo** [comment]
See #4077.
