### ISSUE TITLE
pathvisio doesn't install with java8

### ISSUE THREAD

**Issue by egonw** [Homebrew/homebrew-science#4108]
(ping @kozo2)

### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

- Brief summary of issue: the pathvisio homebrew does not install after installing java8
- we freshly installed Homebrew
- we did: `brew install homebrew/science/pathvisio`
- we observed the notice that Java was not installed
- we did: `brew cask install java` (as suggested). This install a Java8 version
- we did: `brew install homebrew/science/pathvisio` again, but same error.

The below screenshot shows some of the steps, excluding the installation of Java, as we had to reproduce the error this morning and the above steps we did yesterday.

![homebrewpverror](https://cloud.githubusercontent.com/assets/26721/17962233/20a1f432-6ab0-11e6-8bd5-260ffeb4534e.png)

We did note that the configuration file does say `>= 1.7` and are not sure why the error occurs (see https://github.com/Homebrew/homebrew-science/blob/master/pathvisio.rb#L12).

**Comment by tdsmith** [comment]
Fixed; thanks for reporting!

**Comment by egonw** [comment]
Thanks for fixing! We'll try it later today. Can I use it immediately with "brew" or does it need propagation of some kind, before people will see the change on their machine with "brew"?

**Comment by tdsmith** [comment]
You can run `brew update` but for most users Homebrew will auto-update before install.

**Comment by egonw** [comment]
Cool, thanks! (I'm not an OS/X user myself :)
