### ISSUE TITLE
brew tap homebrew-science fails because of undefined methods in formulas

### ISSUE THREAD

**Issue by predmijat** [Homebrew/homebrew-science#4155]
### Indicate troubleshooting steps taken

- [✓] Ran `brew update` and retried your prior step?
- [✓] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [✓] Checked that a similar issue hasn't already been filed?
- [✓] Looked up the software bug tracker if reporting a build error?
- [✓] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

`brew tap homebrew/science` fails because of the recent update with the following output:

```
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/jellyfish-1.1.rb
undefined method `rebuild' for #<BottleSpecification:0x007fa019afb8e0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/p4est.rb
undefined method `rebuild' for #<BottleSpecification:0x007fa018ba6138>
Error: Cannot tap homebrew/science: invalid syntax in tap!
```

Both are updates since yesterday.

**Comment by ilovezfs** [comment]
Your main brew repository is outdated. `revision` within the bottle block was renamed `rebuild`.

```
brew update
```

**Comment by predmijat** [comment]
`brew update` was telling me that I already have the latest version, hence the confusion.

Fixed it by following http://stackoverflow.com/questions/20133587/brew-update-not-working-after-mac-10-9

Sorry for the alarm and thanks!

**Comment by ilovezfs** [comment]
@predmijat you were probably bitten by this bug: https://twitter.com/MacHomebrew/status/763686348041641984
