### ISSUE TITLE
I have 32bit  windows7  laptop. I have downloaded the LAMMPS accordingly and installed too. But unfortunately it is not working on my laptop, I mean all the files are produced but the command windows is not showing. I want to ask that what is the actual problem?or should I install C++ to run LAMMPS in my laptop?

### ISSUE THREAD

**Issue by gullzaib** [Homebrew/homebrew-science#4158]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue:
- Please state the complete command that you issued.
- Please do not post lengthy build output here. Instead provide a link to a gist.
- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Please take this to a lammps tracker. Homebrew does not support Windows. Also, next time, please don't write your entire message in the title. Thanks.

**Comment by gullzaib** [comment]
okay sorry for this time. could you please tell me what is the LAMMPS tracker?
