### ISSUE TITLE
brew tap homebrew/science error

### ISSUE THREAD

**Issue by dhcn** [Homebrew/homebrew-science#4159]
bogon:~ denghui$ brew tap homebrew/science
==> Tapping homebrew/science
正克隆到 '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 624, done.
remote: Compressing objects: 100% (620/620), done.
remote: Total 624 (delta 1), reused 65 (delta 0), pack-reused 0
接收对象中: 100% (624/624), 542.33 KiB | 11.00 KiB/s, 完成.
处理 delta 中: 100% (1/1), 完成.
检查连接... 完成。
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/circlator.rb
uninitialized constant Language::Python::Virtualenv
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/jellyfish-1.1.rb
undefined method `rebuild' for #<BottleSpecification:0x007ffd9c40f6e0>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/p4est.rb
undefined method `rebuild' for #<BottleSpecification:0x007ffd9d0f20b0>
Error: Cannot tap homebrew/science: invalid syntax in tap!

**Comment by ilovezfs** [comment]
Please see https://github.com/Homebrew/homebrew-science/issues/4155
