### ISSUE TITLE
Vtk build fails to work

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#4165]
_From @rambalachandran on August 29, 2016 21:6_

I installed vtk in Mac 10.10.5 with homebrew. These are the steps that I followed for installation
```
brew update
brew doctor
brew install --with-icu --build-from-source boost
brew install --with-python --with-qt vtk
```

However when I try to start python and do `import vtk` it fails with an error that says
```
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```
I ran gist-logs for the last step and it is located in the following location [https://gist.github.com/20e2f5181f2601a7aafa13aa83286e13]

_Copied from original issue: Homebrew/homebrew-core#4337_

**Comment by dpo** [comment]
@rambalachandran See #3401. If it's feasible for you, uninstall Homebrew Python and build VTK against system Python. I'm closing this, but please reopen if the issue persists, or comment in the other issue.

**Comment by rambalachandran** [comment]
Unfortunately uninstalling Homebrew Python is not an option, since it has too many other packages in it and in its virtualenvs. Please update  this issue when a solution emerges that does not involve uninstalling Homebrew Python

**Comment by dpo** [comment]
PLease follow #3401. This issue is a duplicate.
