### ISSUE TITLE
brew breakage?

### ISSUE THREAD

**Issue by jtconnor** [Homebrew/homebrew-science#4211]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Note that the last two items aren't applicable for this issue.

### Bug reports / build errors:

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue:

I tried to use brew to install octave but the installation fails because of errors reported in other formulae.

- Please state the complete command that you issued.

`$ brew install homebrew/science/octave`

- Please do not post lengthy build output here. Instead provide a link to a gist.

https://gist.github.com/jtconnor/d6d22df546da02e9b84ed0b768855965

- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build).

brew gist-logs itself failed but you can see the full terminal output in the linked gist above.

**Comment by dpo** [comment]
You need https://github.com/Homebrew/brew/issues/829#issuecomment-243006354

**Comment by jtconnor** [comment]
Indeed!  Thanks so much for your help @dpo !
