### ISSUE TITLE
GalSim depends on pyfits instead of astropy

### ISSUE THREAD

**Issue by josePhoenix** [Homebrew/homebrew-science#4232]
The `galsim` formula includes a line

```
depends_on "pyfits" => :python
```

However, PyFITS has been [deprecated](http://www.stsci.edu/institute/software_hardware/pyfits) in favor of `astropy.io.fits`. People with `astropy` available should not be required to install a deprecated package. It should be possible to depend on either PyFITS *or* Astropy, but I'm not familiar enough with the formula syntax to say whether that dependency can be expressed.

I just replaced "pyfits" with "astropy" in my local copy of the formula, and it installed with passing tests, so it should be fine.

**Comment by dpo** [comment]
Thanks for pointing that out. Would you like to submit a pull request?

**Comment by josePhoenix** [comment]
Is there a way to depend on either pyfits **or** astropy? I think I'd be trading one problem for another (for users of PyFITS) if I just changed the name of the dependency, but I would be happy to open a PR with that change.
