### ISSUE TITLE
'brew install plink' build failure

### ISSUE THREAD

**Issue by cacampbell** [Homebrew/homebrew-science#4234]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?  **Not exactly sure where to look**

**Could it be that XCode is very outdated? i.e. would have an ancient version cause the build to fail?** The current version on this machine is 4.6.3.

### Bug reports / build errors:

_Erase any parts of this template not applicable to your Issue._

- Brief summary of issue: **Clang appears to be causing the build to fail?**
- Please state the complete command that you issued: **brew install plink / brew install homebrew/science/plink**
- Please do not post lengthy build output here. Instead provide a link to a gist: **[Gist Link](https://gist.github.com/cacampbell/2992ee8c7ff45e05521f6d9a48be1676)**
- If reporting a build failure paste the output of `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed to build). **brew gist-logs plink
[brew gist-logs plink
https://gist.github.com/5739af567eeb7d456679a6c8949ef13f
](https://gist.github.com/5739af567eeb7d456679a6c8949ef13f)**

**Comment by jonchang** [comment]
Hi Chris, that's a really old version of Xcode and clang. It builds fine
for me with Xcode 7.3 clang 703.

**Comment by cacampbell** [comment]
Yes, this makes sense -- I'll update and see if this fixes the problem.

**Comment by cacampbell** [comment]
Yep, that was the problem. Sorry to waste your time! 

Upgrading XCode to the most recent version resulted in the build finishing without error.
