### ISSUE TITLE
pcl exec run issue

### ISSUE THREAD

**Issue by nizar-sallem** [Homebrew/homebrew-science#4241]
Homebrew was updated on Sep 8th 2016

I did:

 Ran brew update and retried
 Ran brew doctor, no real issues there
Bug reports:

I installed PCL from brew with qt support: brew install homebrew/science/pcl --with-qt, this installed jpeg among other things.

Trying to run pcl_vlp_viewer results in this error: 
dyld: Symbol not found: __cg_jpeg_resync_to_restart
Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Expected in: /usr/local/lib/libjpeg.8.dylib
in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Trace/BPT trap: 5

Seems that something is trying to load Framework JPEG library but it is actually built with brew jpeg.

Not sure what would be the appropriate fix.

PS: the program I am trying to build shows exactly same error

**Comment by jonchang** [comment]
Hi @nizar-sallem, could you please [check the Issue Template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md) and link the output of `brew gist-logs pcl` and the output of `brew config`? This will help us diagnose the issue. Thanks!

**Comment by iMichka** [comment]
Closing here. No response since Oct 15.
