### ISSUE TITLE
Formulae with missing "desc" tag

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#4251]
We have 619 formulae. 413 of them have a `desc` and 206 don't. These are listed below. I think a `desc` is important for `brew search` and `brew info` as well as any web pages that are generated from the database. Ideall we would add `# tag "bioinformatics"` and `# doi "xxxx"` where appropriate at the same time.

@sjackman what is the best way to tackle this in terms of commits?  The bottles won't change. How can we be sure we didn't break anything?

Found with: `grep -L desc *.rb  | sed 's/^/- \[ \] /' | sed 's/.rb$//'`
- [ ] arow++
- [ ] ate-pairing
- [ ] atomic-pseudopotential-engine
- [ ] atpdec
- [ ] cantera
- [ ] ccfits
- [ ] cddlib
- [ ] celera-assembler
- [ ] cerulean
- [ ] circos
- [ ] clonalframeml
- [ ] clustal-omega
- [ ] clustal-w
- [ ] cminpack
- [ ] coinmp
- [ ] crfsuite
- [ ] crlibm
- [ ] cuba
- [ ] cube
- [ ] cufflinks
- [ ] cvblob
- [ ] dadadodo
- [ ] data-science-toolbox
- [ ] dotwrp
- [ ] dwgsim
- [ ] dynare
- [ ] edena
- [ ] elemental
- [ ] elph
- [ ] emboss
- [ ] enblend-enfuse
- [ ] ensembl-tools
- [ ] etsf_io
- [ ] fann
- [ ] fasta
- [ ] fastq-tools
- [ ] fasttree
- [ ] fastuniq
- [ ] fastx_toolkit
- [ ] fcgene
- [ ] fermi
- [ ] fermi2
- [ ] field3d
- [ ] flux-simulator
- [ ] fqzcomp
- [ ] freec
- [ ] fsa
- [ ] gaemr
- [ ] galfit
- [ ] galib
- [ ] genet
- [ ] gfan
- [ ] giira
- [ ] gingr
- [ ] glimmer3
- [ ] glimmerhmm
- [ ] gmcloser
- [ ] gmt4
- [ ] graph-tool
- [ ] hisat
- [ ] hopdm
- [ ] hyphy
- [x] idba
- [ ] idcoefs
- [ ] infernal
- [ ] inter-views
- [ ] itsol
- [ ] jblas
- [ ] jellyfish-1.1
- [ ] jmol
- [ ] joinx
- [ ] kalign
- [ ] kissplice
- [ ] kraken
- [ ] lapack-manpages
- [ ] lastz
- [ ] libccd
- [ ] libctl
- [ ] libdivsufsort
- [ ] libgpkg
- [ ] liblbfgs
- [ ] libpll
- [ ] libsbml
- [ ] lightstringgraph
- [ ] links-scaffolder
- [ ] lis
- [ ] littler
- [ ] lmfit
- [ ] lmod
- [ ] lola
- [ ] lp_solve
- [ ] lumpy-sv
- [ ] mafft
- [ ] maker
- [ ] maq
- [ ] megam
- [ ] meraculous
- [ ] methpipe
- [ ] mfusg
- [ ] minc
- [ ] mir-prefer
- [ ] mira
- [ ] mitofy
- [ ] mlpack
- [ ] moab
- [ ] mpsolve
- [ ] mrbayes
- [ ] mrfast
- [ ] mtl
- [ ] mummer
- [ ] ncbi-c++-toolkit
- [ ] newick-utils
- [ ] nfft
- [ ] niftilib
- [ ] nusmv
- [ ] oases
- [ ] openfst
- [ ] opengrm-ngram
- [ ] opengrm-thrax
- [ ] openmeeg
- [ ] openni
- [ ] openni2
- [ ] orocos-kdl
- [ ] pcap
- [ ] pear
- [ ] perf
- [ ] phylip
- [ ] plink2
- [ ] pnapi
- [ ] poa
- [ ] pocl
- [ ] populations
- [ ] prodigal
- [ ] propack
- [ ] pulseview
- [ ] pykep
- [ ] qcl
- [ ] qgis
- [ ] qrupdate
- [ ] quake
- [ ] quest
- [ ] quicktree
- [ ] quip
- [ ] quorum
- [ ] rainbow
- [ ] rampart
- [ ] readsim
- [ ] recon
- [ ] repeatmasker
- [ ] repeatscout
- [ ] rml-mmc
- [ ] ropebwt
- [ ] sais
- [ ] sally
- [ ] salt
- [ ] samtools-0.1
- [ ] sara
- [ ] sbagen
- [ ] scamp
- [ ] scarpa
- [ ] scotch5
- [ ] seq-gen
- [ ] seqdb
- [ ] sextractor
- [ ] shrimp
- [ ] sickle
- [ ] sigrok-cli
- [ ] sisl
- [ ] slicot
- [ ] sllib
- [ ] snap-aligner
- [ ] snid
- [ ] spatialite-gis
- [ ] squeezambler
- [ ] ssake
- [ ] sspace-longread
- [ ] statismo
- [ ] stiff
- [ ] sundials
- [ ] swetest
- [ ] symphony
- [ ] t-coffee
- [ ] tetgen
- [ ] therion
- [ ] tmv-cpp
- [ ] topcat
- [ ] transtermhp
- [ ] triangle
- [ ] unafold
- [ ] uniqtag
- [ ] uproc
- [ ] utgb
- [ ] vcake
- [ ] vcfanno
- [ ] velvet
- [ ] velvetoptimiser
- [ ] viennarna
- [ ] vigra
- [ ] voro++
- [ ] wcslib
- [ ] weblogo
- [ ] wopr
- [ ] xbyak
- [ ] xmgredit
- [ ] xmi-msim
- [ ] yeppp

**Comment by ilovezfs** [comment]
If you think this needs a tracking issue, you should lobby for it to be a non-strict audit failure.

**Comment by tseemann** [comment]
That needs to be done at the Brew level, this is homebrew-science.

**Comment by sjackman** [comment]
> @sjackman what is the best way to tackle this in terms of commits? The bottles won't change. How can we be sure we didn't break anything?

If all you've done is add a `desc` line, then `brew audit` and `brew style` are a good check that you haven't broken anything. You can still submit a PR though. Mention in the PR that the bottle should not be updated. It could also be a good opportunity for building Linuxbrew bottles for any formula that are missing them.

**Comment by ilovezfs** [comment]
Closing since this is now a hard failure during CI for `brew style` so it should take care of itself over time.
