### ISSUE TITLE
Formulae with inappropriate test

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#4252]
There are 47 formulae with a "null" test that just runs the binary and checkes for return value 0. This is better than nothing of course, but perhaps a 

```
assert_match "foo" shell_output("#{bin}/command options", retval)
```

would be better?

Found via: 

```
grep 'test do' -A 1 *.rb | grep system | grep -v '[|,<>]'  | sed 's/^/- [ ] /' | sed 's/.rb-/ : /' | sed 's/  *system/ `system/g' | sed 's/$/`/'
```
- [ ] astrometry-net : `system "solve-field"`
- [ ] atpdec : `system "atpdec"`
- [ ] bcalm : `system bin/"bcalm"`
- [ ] blasr : `system "#{bin}/blasr"`
- [ ] bless : `system "#{bin}/bless"`
- [ ] celera-assembler : `system "#{bin}/runCA"`
- [ ] cube : `system "#{bin}/cube-config --version"`
- [ ] deeplearning4j-cli : `system "#{bin}/dl4j"`
- [ ] edena : `system "edena"`
- [ ] fasta : `system "#{bin}/fasta36"`
- [ ] fqzcomp : `system "#{bin}/fqz_comp -h"`
- [ ] gaemr : `system "PYTHONPATH=#{libexec} #{bin}/GAEMR.py --help"`
- [ ] gfan : `system "gfan --help"`
- [ ] gtsam : `system bin/"wrap"`
- [ ] hyphy : `system libexec/"HYPHYGTEST"`
- [ ] igvtools : `system bin/"igvtools"`
- [ ] jsbsim : `system "#{bin}/JSBSim"`
- [ ] kissplice : `system "kissplice --version"`
- [ ] kmc : `system "#{bin}/kmc"`
- [ ] lmod : `system "#{prefix}/lmod/lmod/init/sh"`
- [ ] maker : `system "maker --version"`
- [ ] mathgl : `system "#{bin}/mgl_example"`
- [ ] mir-prefer : `system "python #{bin}/miR_PREFeR.py -h"`
- [ ] mira : `system "#{bin}/mira --version"`
- [ ] mitofy : `system "#{bin}/mitofy"`
- [ ] nexusformat : `system "#{bin}/nxdir"`
- [ ] ococo : `system "#{bin}/ococo -v"`
- [ ] ogdraw : `system "#{bin}/drawgenemap"`
- [ ] osgearth : `system "#{bin}/osgearth_version"`
- [ ] quip : `system "quip --version"`
- [ ] rampart : `system "#{bin}/rampart --version"`
- [ ] readseq : `system "#{bin}/readseq"`
- [ ] readsim : `system "#{bin}/readsim.py"`
- [ ] repeatmasker : `system "RepeatMasker"`
- [ ] sais : `system "pkg-config --modversion libsais"`
- [ ] seqdb : `system "seqdb"`
- [ ] smrtanalysis : `system "#{prefix}/install/smrtanalysis_#{version}/analysis/bin/blasr"`
- [ ] snp-sites : `system "snp-sites"`
- [ ] soapdenovo : `system "#{bin}/SOAPdenovo-63mer"`
- [ ] t-coffee : `system "#{bin}/t_coffee -version"`
- [ ] uniqtag : `system "#{bin}/uniqtag --version"`
- [ ] utgb : `system "#{bin}/utgb"`
- [ ] vcftools : `system "#{bin}/vcftools"`
- [ ] velvetoptimiser : `system "VelvetOptimiser.pl --version"`
- [ ] xcdf : `system "#{bin}/xcdf-append-test"`
- [ ] yaha : `system "yaha"`
- [ ] yass : `system "yass"`

**Comment by ilovezfs** [comment]
These tests are usually perfectly valid, and I don't think having a general tracking issue like this makes much sense. If you think a given test should be improved, feel free to open a PR for that.

**Comment by tseemann** [comment]
@ilovezfs all these tests should be improved. there are probably < 50 "real tests" in homebrew-science.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/208#issuecomment-217734009

This topic is well covered terrain.
