### ISSUE TITLE
Blast fails to build on linux

### ISSUE THREAD

**Issue by ACharbonneau** [Homebrew/homebrew-science#4306]
#### Brief summary of issue:
> /tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/include/corelib/ncbifile.hpp:2855: error: ‘contents’ was not declared in this scope
make[3]: *** [ncbifile.o] Error 1
make[3]: *** [ncbiargs.o] Error 1
make[3]: *** [ncbidiag.o] Error 1
make[3]: Leaving directory `/tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/build/corelib'
FAILED: src/corelib/Makefile.corelib.lib
make[3]: Entering directory `/tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/build/corelib'
/bin/rm -f libxncbi.so libxncbi.so .xncbi.dep .libxncbi.so.stamp
/bin/rm -f /tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/lib/libxncbi.so /tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/status/.xncbi.dep
make[3]: Leaving directory `/tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/build/corelib'
make[2]: *** [all.nonusr] Error 2
make[2]: Leaving directory `/tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/build/corelib'
make[1]: *** [all_r.real] Error 5
make[1]: Leaving directory `/tmp/blast-20160914-19060-1k2dcbw/ncbi-blast-2.4.0+-src/c++/ReleaseMT/build'
make: *** [all] Error 2

#### The complete command that you issued:

I've tried both:

brew install homebrew/science/blast
brew install homebrew/science/blast --without-check 

with the same result

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/24ca790bb5575741c7beaa192e421a50

#### Other relevant info
Running in a home directory on a linux HPC, so I can't edit `/opt`. 
Error may be similar to #2705

I'm actually trying to install BUSCO, and it just gets stuck on this pre-req. I'd be equally pleased with help fixing this error or a workaround to get BUSCO going :)

**Comment by jonchang** [comment]
Hi Amanda, it looks like your version of gcc is quite old (version 4.4). It seems like you have gcc version 5 installed via Linuxbrew, could you try setting your compiler to `gcc-5` like:

```
brew install --verbose blast --cc=gcc-5 -cxx=g++-5
```

**Comment by ACharbonneau** [comment]
Hey Jon, that doesn't seem to run.
>$ brew install --verbose blast --cc=gcc-5 -cxx=g++-5
==> Installing blast from homebrew/science
git config --replace-all homebrew.private true
Error: Failure while executing: git config --replace-all homebrew.private true

**Comment by jonchang** [comment]
That seems to be unrelated to your build failure. Is it possible that you don't have write access to your homebrew repository? What happens if you run

```
cd `brew --repo homebrew/science` && git config --replace-all homebrew.private true; cd -
```

**Comment by ACharbonneau** [comment]
I definitely have write access to my brew repo. I just fixed my Git config problem, and now forcing brew to use the newer version of gcc seems to have fixed it!

Thanks, I never would have noticed it was trying to compile with the old gcc.

**Comment by sjackman** [comment]
Thanks for the troubleshooting, Jon! Linuxbrew is supposed to prefer and default to gcc-5 over gcc-4.4. I'm not sure why it defaulted to the latter.

**Comment by jonchang** [comment]
It seems like there's a fails_with gcc-5 block in the formula? I'm not sure how exactly compiler selection works on Linuxbrew but that might be the source of the problem.

**Comment by tseemann** [comment]
@ACharbonneau Amanda - make sure Linuxbrew is the first thing in your `PATH` or all sort of hell will occur. And just like "don't drink and drive" I would add "don't brew and conda" :)

**Comment by ACharbonneau** [comment]
Hey Torsten...no conda is easy, but the HPC tacks modules onto the front of my path rather than the end so, although brew starts as first in my path, it's nearly impossible to keep it there :(

**Comment by jonchang** [comment]
This will be less of an issue when we get superenv running for Linux...
