### ISSUE TITLE
STAR 2.5.2b

### ISSUE THREAD

**Issue by mjsteinbaugh** [Homebrew/homebrew-science#4307]
I'm interested in updating the rna-star.rb formula to STAR 2.5.2b but I'm not sure how to do this correctly. Would someone be willing to help?

**Comment by dpo** [comment]
Sure. The steps go like this in the terminal:

1. If not already done, fork Homebrew-Science to your account (use the button on the top right of this page)
2. In the terminal, `cd $(brew --prefix)/Library/Taps/homebrew/homebrew-science`
3. Add your fork to the list of remotes so you can push your changes there later: `git remote add myfork https://github.com/mjsteinbaugh/homebrew-science.git`
4. Create a branch to work on your formula: `git checkout -b rna-star-252b`
5. Edit `rna-star.rb` in your favorite editor and set the `url` to the URL of the new release
6. Back in the terminal ask `brew` to fetch the new release: `brew fetch rna-star`. It will complain that the `sha256` is wrong (the formula still has the old one) but it will print the new one. Copy it, and paste it in the `sha256` field of the formula.
7. If the formula had a `revision` field, you would remove it. In this case, there isn't one.

In the best case scenario, that's it. Now cross your fingers that the new release compiled just like the old one and give it a go: `brew install -vd rna-star`

Here, `-v` turns on verbose mode so you can see what's going on, and `d` enables debugging so you can drop into the source dir in case of trouble and have a look around.

#### If the build/install succeeds

If it appears to build and install without trouble, you can run the test (which isn't the best test in the case of `rna-star`) with `brew test -v rna-star`.

If that works, have a look at `ls $(brew --prefix rna-star)` to see if there's nothing unexpected in there.

Check that the style and syntax of the formula are still up to date with `brew audit --strict --online rna-star`. Fix any issue reported.

You're done! Add your changes to the repository and push to your fork:
```bash
git add rna-star.rb
git commit -m 'rna-star 2.5.2b'  # embellish a little if you had to make other updates
git push myfork rna-star-252b
```

Now head to www.github.com and select your fork of Homebrew-Science. There should be an indication there that you just pushed a new branch accompanied by a button to open a pull request.

Don't forget to `git checkout master` after pushing. When your pull request is accepted, you can delete your local branch with `git branch -D rna-star-252b`.

#### If the build fails

The `-d` flag passed to `brew install` command will allow you to drop to a shell and have a look at why the build failed. It's hard to give general guidance here as almost anything can happen. If you can't discover what went wrong, have a look at the documentation and release notes to see if anything's changed in the build procedure.

In difficult cases, I find it useful to try and reproduce the build steps outside of Homebrew. The archive of the new release is in `ls $(brew --cache)`. Unpack it anywhere and try to build. Don't hesitate to ask for help, here or on the `rna-star` tracker.

Off the top of my head, that's about it. Let me know if it helps or if anything is missing or inconsistent.

Good luck!

**Comment by dpo** [comment]
Of course, it's also a good idea to read the [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md).

**Comment by mjsteinbaugh** [comment]
Thanks I have a working update on my personal homebrew tap but just wanted to check before I attempt a pull request of the new version. Thanks.
