### ISSUE TITLE
After running brew install node, I get "-bash: node: command not found" in command line

### ISSUE THREAD

**Issue by darrenbrett** [Homebrew/homebrew-science#4315]
I've been troubleshooting this for hours now. Seems to be a location/permissions issue. After successfully running ""brew install node", when I run "node -v" I get "-bash: node: command not found". When I try and re-run "brew install node" I get "Warning: node-6.6.0 already installed, it's just not linked". Does this suggest a location issue, or a permissions issue? Any help would be greatly appreciated. Thanks!

**Comment by dpo** [comment]
The issue template has suggestions related to permissions issues. It also asks that you submit some information. Please submit all you can so we can try to help you.

**Comment by darrenbrett** [comment]
My initial problem was that I couldn't update the angular-cli, because I had rogue node nodules. Even when I would run "brew uninstall node", afterwards, when I would run "node -v", it still showed up on my system. After going to various folders and manually deleting any node files, I finally got it removed from my system (i.e. running "node -v" returned "command not found". So after having that done I re-ran "brew install node". When I now run "node -v" I get "-bash: node: command not found". When I try and re-run "brew install node" I get "Warning: node-6.6.0 already installed, it's just not linked". If there's anything else you'd like to know, please let me know.

**Comment by darrenbrett** [comment]
Is there anything else you'd like me to submit?

**Comment by darrenbrett** [comment]
"Warning: node-6.6.0 already installed, it's just not linked"

How should I troubleshoot this?

**Comment by darrenbrett** [comment]
==> Summary
🍺  /usr/local/Cellar/node/6.6.0: 3,669 files, 40.9M
Darrens-Air:~ darrenking$ node -v
-bash: node: command not found

**Comment by dpo** [comment]
I'm going to close this. Please open a new issue. You'll see the issue template. Please fill out all required information in there. Thank you.

**Comment by jwhubert91** [comment]
Hey Darren - Did you get this figured out? I'm having such a problem getting node and npm to work properly. I've tried installing manually and with Homebrew. Nothing seems to get it consistently working. Would love to know if you have any updates on this.

**Comment by davidglbr** [comment]
@jwhubert91 @darrenbrett Having this problem too.
Trying to find the node exec to link, any insight?

**Comment by iggirex** [comment]
Anyone figure this out? or this just got closed with no solution????

**Comment by davidglbr** [comment]
Not sure why it was closed (@dpo?). Linking it shouldn't be difficult. Are we missing something or is it a bug?

**Comment by jonchang** [comment]
Please file a new issue according to the issue template. We closed the original issue because it didn't provide sufficient information to help us diagnose the problem.

**Comment by darrenbrett** [comment]
For me it ended up being a permissions issue. After making some tweaks everything ran/installed as expected. I'd copy in exactly what I changed, but it's been a couple of weeks now.
