### ISSUE TITLE
netcdf fortran fails configure stage with brew installed gfortran

### ISSUE THREAD

**Issue by powellb** [Homebrew/homebrew-science#4316]
### Indicate troubleshooting steps taken
- [X ] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] Checked that a similar issue hasn't already been filed?
- [X ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:

==> Upgrading 1 outdated package, with result:
homebrew/science/netcdf 4.3.3.1_5
==> Upgrading homebrew/science/netcdf
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz
Already downloaded: /Users/powellb/Library/Caches/Homebrew/netcdf-4.3.3.1.tar.gz
==> ./configure --disable-dap-remote-tests --prefix=/usr/local/Cellar/netcdf/4.3.3.1_5 --enable-st
==> make
==> make check
==> make install
==> Downloading https://github.com/Unidata/netcdf-cxx4/archive/v4.2.1.tar.gz
Already downloaded: /Users/powellb/Library/Caches/Homebrew/netcdf--cxx-4.2.1.tar.gz
==> ./configure --disable-dap-remote-tests --prefix=/usr/local/Cellar/netcdf/4.3.3.1_5 --enable-st
==> make
==> make check
==> make install
==> Downloading ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.2.tar.gz
Already downloaded: /Users/powellb/Library/Caches/Homebrew/netcdf--fortran-4.4.2.tar.gz
==> ./configure --disable-dap-remote-tests --prefix=/usr/local/Cellar/netcdf/4.3.3.1_5 --enable-st
Last 15 lines from /Users/powellb/Library/Logs/Homebrew/netcdf/09.configure:
checking if /usr/local/bin/gfortran supports -c -o file.o... (cached) yes
checking whether the /usr/local/bin/gfortran linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
configure: finding other utilities
configure: trying to set fortran flags for this platform
checking what FC is set to... /usr/local/bin/gfortran
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for /usr/bin/nm... /usr/bin/nm -B
checking nm flags...
checking for C-equivalent to Fortran routine "SUB"... sub_
checking for Fortran "byte"... yes
checking for Fortran "integer*2"... yes
checking if Fortran "byte" is C "signed char"... configure: error: Could not link conftestf.o and conftest.o
#### Brief summary of issue:

Just did a 'brew update' and 'brew upgrade', and it rebuilt netcdf, netcdf-cxx, and netcdf-fortran; however, netcdf-fortran failed (as per above).
#### The complete command that you issued:

% brew update
% brew upgrade
#### Gist with output of `brew doctor`:

% brew doctor
Your system is ready to brew.
#### Output of `brew config`:

% brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c419f928ba5d152fc41a8abc8f33f88bfe3e1971
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c90554642dfda156c2356539c942809278a4fc0e
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
OS X: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Please also give:

> Link output by brew gist-logs <formula>

**Comment by powellb** [comment]
Sorry for the delay:

https://gist.github.com/db748ba3652eceb6f9fa3bb4e5fe012b

**Comment by dpo** [comment]
I'm not sure if this is an Xcode 8 issue. Could you try `brew uninstall -f $(brew deps -r netcdf)` followed by `brew install netcdf`?

**Comment by powellb** [comment]
Thanks Dominique. I tried this and get the same results. Exact same error.

**Comment by dpo** [comment]
I suppose we can blame Xcode 8 then. If that's a possibility for you, you could revert to the previous version of Xcode, where it was known to compile. I believe `xcode-select` will let you install an earlier version.

**Comment by iMichka** [comment]
`netcdf` was migrated to homebrew-core, and is building fortran bindings by default now. If you still encounter problems, please open an issue there, thanks.
