### ISSUE TITLE
Failed to download resource "hdf5"

### ISSUE THREAD

**Issue by levi106** [Homebrew/homebrew-science#4318]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
% brew install hdf5  
==> Installing hdf5 from homebrew/science
==> Downloading https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "hdf5"
Download failed: https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2
```

#### Brief summary of issue:
Failed to download hdf5-1.8.17.tar.bz2.

#### The complete command that you issued:
```
brew install hdf5
```

**Comment by tomasdikk** [comment]
Hey levi106, here's my solution to that issue. Manually edit the hdf5 formula

`brew edit hdf5`

Change the URL from `https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2` which causes a 404, to `https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2`

The only difference being `www.hdfgroup.org` -> `support.hdfgroup.org`

**Comment by ilovezfs** [comment]
no ... brew update since the url has been updated
