### ISSUE TITLE
vtk: Build with options fails linking due to missing OpenGL symbols

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-science#4322]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

This is using

```
brew install vtk --c++11 --with-examples --with-matplotlib --with-python3 --without-python --with-tcl --with-x11
```

[Gist](https://gist.github.com/aw1621107/a515e5ba1d953bc8547ea679fd103014)

Unfortunately, I appear to be having issues producing a gist when fewer options are used -- something about the gist holding output only up to ~25% through the CMake build (error usually happens in the 70% range) and without any sign of why the build stopped. I'll be tinkering with it further, and will update with a better gist if I can.

I've also tried, `brew install vtk --with-tcl` and `brew install vtk --with-x11`, with the install completing both times.

**Comment by aw1621107** [comment]
Looks like the minimum failing command is `brew install vtk --c++11 --with-x11`. Logs coming up shortly

**Comment by aw1621107** [comment]
"Shortly"... `gist-logs` succeeds, while `install` fails. Not sure what is going on

**Comment by aw1621107** [comment]
Also, gist-logs appears to be cutting off part of the log? Also happens to be a pretty important part of the log...

```
[  2%] Building C object ThirdParty/libproj4/vtklibproj4/CMakeFiles/vtkproj4.dir/proj_tmerc.c.o
cd /tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/build/ThirdParty/libproj4/vtklibproj4 && /usr/local/Homebrew/Library/Homebrew/shims/super/clang  -DVTK_IN_VTK -Dvtkproj4_EXPORTS -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/ThirdParty/libproj4/vtklibproj4 -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/build/ThirdParty/libproj4/vtklibproj4 -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/build/ThirdParty/libproj4 -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/ThirdParty/libproj4  -w -w -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -o CMakeFiles/vtkproj4.dir/proj_tmerc.c.o   -c /tmp/vtk-20160920-30310-2bzchv/
[...snip...]
-20160920-30310-2bzchv/VTK-7.0.0/build/Rendering/Volume -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/Rendering/Volume -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/build/Interaction/Widgets -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/Interaction/Widgets  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -fvisibility=hidden -fvisibility-inlines-hidden -o CMakeFiles/vtkInteractionWidgets.dir/vtkCurveRepresentation.cxx.o -c /tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/Interaction/Widgets/vtkCurveRepresentation.cxx
[ 81%] Building CXX object Interaction/Widgets/CMakeFiles/vtkInteractionWidgets.dir/vtkDijkstraImageContourLineInterpolator.cxx.o
cd /tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/build/Interaction/Widgets && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DVTK_IN_VTK -DvtkInteractionWidgets_EXPORTS -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/build/Filters/Hybrid -I/tmp/vtk-20160920-30310-2bzchv/VTK-7.0.0/Filters/Hybrid -
```

**Comment by ilovezfs** [comment]
Yeah the build with X seems broken.
