### ISSUE TITLE
Possible fix for reported issues with VTK linking to wrong Python

### ISSUE THREAD

**Issue by fish2000** [Homebrew/homebrew-science#4334]
This has been previously reported:

* https://github.com/Homebrew/homebrew-science/issues/3401
* https://github.com/Homebrew/homebrew-science/issues/4165

… with messy proposed solutions (removing the brewed Python installation altogether, messing with DYLD runtime paths, etc) that in some cases were unfeasable.

BUT SO: After many months of running into the `PyThreadState_Get` problem (q.v. #4165) I managed to produce a completely functional and non-problematic HEAD build of VTK by updating line 123 of `vtk.rb` to call `/usr/local/bin/python-config` instead of just `python-config`. 

I would normally send this report as a PR, but this formula is a complex beast, to the point where updating it is above my paygrade. But the fix was easy enough‡ and the issue troublesome enough (I have dealt with it in some form for quite some time now) to warrant some feedback. 

Apologies for eschewing some of the finer points of issue-reporting, then, in this case. HTH!

<hr>
‡ … if you can call suffering through VTK’s from-scratch compile time “easy”, that is

**Comment by jonchang** [comment]
Hi @fish2000, thanks for the report. The issue with that change is that it would require everyone to use Homebrew's copy of Python for VTK, even if they are using the system copy. Could you please try the fix in https://github.com/Homebrew/homebrew-science/issues/3401#issuecomment-249333818 and see if VTK still crashes for you?

**Comment by jonchang** [comment]
Fixed by #4342.
