### ISSUE TITLE
discovardenovo: /usr/bin/g++-4.8: No such file or directory on Ubuntu 16.04

### ISSUE THREAD

**Issue by kingcohn1** [Homebrew/homebrew-science#4335]
```
$ brew install discovardenovo
==> Installing discovardenovo from homebrew/science
==> Downloading ftp://ftp.broadinstitute.org/pub/crd/DiscovarDeNovo/latest_sourc
Already downloaded: /home/molecularecology/.cache/Homebrew/discovardenovo-52488.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/molecularecology/.linuxbre
Last 15 lines from /home/molecularecology/.cache/Homebrew/Logs/discovardenovo/01.configure:
checking whether the /usr/bin/g++-4.8 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether byte ordering is bigendian... no
./configure: line 15723: /usr/bin/g++-4.8: No such file or directory
Failed...
configure: Configure failed with the error message: You must compile this with g++ 4.7 or higher.
configure: 
configure: Common error conditions in the build process are documented
configure: on our wiki page:
configure: http://www.broadinstitute.org/crd/wiki/index.php/Build_FAQ
configure: We also offer email support at crdhelp@broadinstitute.org
configure: error: in `/tmp/discovardenovo-20160922-25761-126k0vi/discovardenovo-52488':
configure: error: Configure failed.
See `config.log' for more details.If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
```

gcc --version output: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
and 
after running brew update (2x) and brew doctor I was unable to set the path at 

echo 'export PATH="/home/molecularecology/.linuxbrew/bin:$PATH"' >> ~/.bash_profile 
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
Hi @kingcohn1, could you please do these steps? This will help us determine the cause of your build problems. 

```
Gist with output of brew doctor:
Link output by brew gist-logs <formula>:
Output of brew config:
```

**Comment by kingcohn1** [comment]
https://gist.github.com/kingcohn1/9a1d52ad551645ab1f00d32368f4652b

**Comment by kingcohn1** [comment]
https://gist.github.com/9634b8ea75532af7e1f3ff8931fde778

**Comment by sjackman** [comment]
`./configure: line 15723: /usr/bin/g++-4.8: No such file or directory`

Try `sudo apt-get install build-essential curl git python-setuptools ruby`
See http://linuxbrew.sh/#dependencies

**Comment by kingcohn1** [comment]
OK thanks Shaun, but should I specify the path for the updated gcc? 

Here's what I'm getting: 

molecularecology@molecular-ecology:~$ sudo apt-get install build-essential curl git python-setuptools ruby
[sudo] password for molecularecology: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
git is already the newest version (1:2.7.4-0ubuntu1).
git set to manually installed.
python-setuptools is already the newest version (20.7.0-1).
python-setuptools set to manually installed.
ruby is already the newest version (1:2.3.0+1).
ruby set to manually installed.
curl is already the newest version (7.47.0-1ubuntu2.1).
curl set to manually installed.
The following package was automatically installed and is no longer required:
  xserver-xorg-legacy
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
molecularecology@molecular-ecology:~$ brew install gcc
==> Auto-updated Homebrew!
Updated Homebrew from f2df16c to a7cc67f.
Updated 1 tap (homebrew/science).
==> Updated Formulae
homebrew/science/radx

==> Installing dependencies for gcc: zlib, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.8.x86_64_linux.bo
######################################################################## 100.0%
==> Pouring zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
🍺  /home/molecularecology/.linuxbrew/Cellar/zlib/1.2.8: 11 files, 398.6K
==> Installing gcc dependency: gmp
==> Downloading https://linuxbrew.bintray.com/bottles/gmp-6.1.1.x86_64_linux.bot
######################################################################## 100.0%
==> Pouring gmp-6.1.1.x86_64_linux.bottle.tar.gz
🍺  /home/molecularecology/.linuxbrew/Cellar/gmp/6.1.1: 19 files, 3.6M
==> Installing gcc dependency: mpfr
==> Downloading https://linuxbrew.bintray.com/bottles/mpfr-3.1.4.x86_64_linux.bo
######################################################################## 100.0%
==> Pouring mpfr-3.1.4.x86_64_linux.bottle.tar.gz
🍺  /home/molecularecology/.linuxbrew/Cellar/mpfr/3.1.4: 26 files, 3.8M
==> Installing gcc dependency: libmpc
==> Downloading https://linuxbrew.bintray.com/bottles/libmpc-1.0.3.x86_64_linux.
######################################################################## 100.0%
==> Pouring libmpc-1.0.3.x86_64_linux.bottle.tar.gz
🍺  /home/molecularecology/.linuxbrew/Cellar/libmpc/1.0.3: 12 files, 466.3K
==> Installing gcc dependency: isl
==> Downloading https://linuxbrew.bintray.com/bottles/isl-0.15.x86_64_linux.bott
######################################################################## 100.0%
==> Pouring isl-0.15.x86_64_linux.bottle.tar.gz
🍺  /home/molecularecology/.linuxbrew/Cellar/isl/0.15: 71 files, 4.6M
==> Installing gcc
==> Downloading https://linuxbrew.bintray.com/bottles/gcc-5.3.0.x86_64_linux.bot
######################################################################## 100.0%
==> Pouring gcc-5.3.0.x86_64_linux.bottle.tar.gz
==> Creating the GCC specs file: /home/molecularecology/.linuxbrew/Cellar/gcc/5.
🍺  /home/molecularecology/.linuxbrew/Cellar/gcc/5.3.0: 1,352 files, 253.2M
molecularecology@molecular-ecology:~$ brew install discovardenovo
==> Installing discovardenovo from homebrew/science
==> Downloading ftp://ftp.broadinstitute.org/pub/crd/DiscovarDeNovo/latest_sourc
Already downloaded: /home/molecularecology/.cache/Homebrew/discovardenovo-52488.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/molecularecology/.linuxbre
Last 15 lines from /home/molecularecology/.cache/Homebrew/Logs/discovardenovo/01.configure:
checking whether the /usr/bin/g++-4.8 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether byte ordering is bigendian... no
./configure: line 15723: /usr/bin/g++-4.8: No such file or directory
Failed...
configure: Configure failed with the error message: You must compile this with g++ 4.7 or higher.
configure: 
configure: Common error conditions in the build process are documented
configure: on our wiki page:
configure: http://www.broadinstitute.org/crd/wiki/index.php/Build_FAQ
configure: We also offer email support at crdhelp@broadinstitute.org
configure: error: in `/tmp/discovardenovo-20160922-8289-1f1ctus/discovardenovo-52488':
configure: error: Configure failed.
See `config.log' for more details.

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
discovardenovo: /usr/bin/g++-4.8: No such file or directory on Ubuntu 16.04 https://github.com/Homebrew/homebrew-science/issues/4335
molecularecology@molecular-ecology:~$ sudo apt-get install build-essential
[sudo] password for molecularecology: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
The following package was automatically installed and is no longer required:
  xserver-xorg-legacy
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
molecularecology@molecular-ecology:~$ brew install gcc
Warning: gcc-5.3.0 already installed

**Comment by jonchang** [comment]
So the formula has `fails_with gcc: "5"` which is why Linuxbrew is preferring gcc 4.8 over gcc 5. I can confirm that it builds fine with gcc 4.8.5 on CentOS 7. It's possible that your gcc-4.8 install is busted somehow? What do you get when you run `/usr/bin/g++-4.8 --version`, or try to install something that requires compilation with `brew install <formula> --cc=/usr/bin/gcc-4.8 --cxx=/usr/bin/g++-4.8`?

**Comment by kingcohn1** [comment]
Hello Jonathan,

I get:
$ /usr/bin/g++-4.8
bash: /usr/bin/g++-4.8: No such file or directory

but when I type:
$ /usr/bin/g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by sjackman** [comment]
Feel free to comment if this issue is still relevant.

**Comment by kingcohn1** [comment]
Thanks, will do.
