### ISSUE TITLE
R upgrade fails on macOS 10.11.6

### ISSUE THREAD

**Issue by dagola** [Homebrew/homebrew-science#4338]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running sudo chown -R $(whoami) $(brew --prefix)?

#### Brief summary of issue:
I updated to Xcode8. Than I ran `brew update` and `brew upgrade`, but `R` fails to upgrade to 3.3.1_2.

#### The complete command that you issued:
```
➜  ~  brew update
Already up-to-date.
➜  ~  brew upgrade
==> Upgrading 1 outdated package, with result:
homebrew/science/r 3.3.1_2
==> Upgrading homebrew/science/r
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://cran.rstudio.com/src/base/R-3/R-3.3.1.tar.gz
Already downloaded: /Users/DGola/Library/Caches/Homebrew/r-3.3.1.tar.gz
==> Patching
patching file src/modules/lapack/vecLibg95c.c
==> ./configure --prefix=/usr/local/Cellar/r/3.3.1_2 --with-libintl-prefix=/usr/local/op
==> make
Last 15 lines from /Users/DGola/Library/Logs/Homebrew/r/02.make:
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /private/tmp/r-20160923-23736-1h3hlz5/R-3.3.1/lib/libR.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/tmp/r-20160923-23736-1h3hlz5/R-3.3.1/lib/libR.dylib
  Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 37879 Done                    echo "tools:::sysdata2LazyLoadDB(\"./R/sysdata.rda\",\"../../../library/tools/R\")"
     37880 Trace/BPT trap: 5       | R_DEFAULT_PACKAGES=NULL LC_ALL=C ../../../bin/R --vanilla --slave
make[4]: *** [sysdata] Error 133
make[3]: *** [all] Error 2
make[2]: *** [R] Error 1
make[1]: *** [R] Error 1
make: *** [R] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
Error when installing R https://github.com/Homebrew/homebrew-science/issues/2795
r: error while loading shared libraries: libncursesw.so.5 https://github.com/Homebrew/homebrew-science/issues/3484
Homebrew should support formulae that install R packages https://github.com/Homebrew/homebrew-science/issues/2559
```

#### Gist with output of `brew doctor`:
[Gist](https://gist.github.com/dagola/ed082f3b8e9b516d02416ed775690a32#file-00-doctor-out)

#### Link output by `brew gist-logs r`:
[Gist](https://gist.github.com/dagola/ed082f3b8e9b516d02416ed775690a32)

#### Output of `brew config`:
```
➜  ~  brew config
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: bbed7246bc5c5b7acb8c1d427d10b43e090dfd39
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 966383f9e13e03c53290f38bea3a94f6fa4bddc6
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102, 1.8.0_92, 1.7.0_80, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

Any advice is appreciated.
Thanks

**Comment by pooranis** [comment]
Same here with 10.11.6.  Homebrew forced me to upgrade to Xcode 8.0, and then I have this same error which seems associated with running Xcode 8 on 10.11.

**Comment by andrewblim** [comment]
I also ran into this problem today, and although this is clearly not helpful if you need to stay on El Capitan, things worked for me after upgrading to Sierra.

**Comment by pooranis** [comment]
Because I really needed to install R with x11, and upgrading the OS is not an option right now, I edited the R formula with a cheap fix [similar to this one](https://github.com/Homebrew/homebrew-core/commit/4ae579c3c830f7febf6c1098d241c77e90066274).  I still think it's kind of lame for Homebrew to force everyone to Xcode 8.  It was only released 10 days ago, and Sierra was only released **3 days ago**.  

    +    if MacOS.version == "10.11" && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
    +      inreplace %w[src/main/times.c], "HAVE_CLOCK_GETTIME", "UNDEFINED_GIBBERISH"
    +    end

**Comment by ilovezfs** [comment]
>I still think it's kind of lame for Homebrew to force everyone to Xcode 8. It was only released 10 days ago, and Sierra was only released 3 days ago.

Feel free to open an issue in homebrew/brew with your concerns, but I'd suggest not referring to the unpaid efforts of volunteers as lame while you're at it.

**Comment by dagola** [comment]
Thanks for your replies so far.
I can confirm that upgrading to Sierra resolves this problem.

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-science/pull/4374.
