### ISSUE TITLE
ArrayFire Formula Requests: Ver 3.4 is out

### ISSUE THREAD

**Issue by bruce3141** [Homebrew/homebrew-science#4346]
## Any near-term plans to update the build formula to Ver. 3.4 of ArrayFire?

Current ArrayFire Ver. is 3.3.2; significant performance improvements have been implemented in Ver. 3.4.

**Comment by jonchang** [comment]
Hi Bruce, please feel free to submit a pull request for the change. You'll need to update the download URL and sha256 hash. Refer to the contributing document if you need more information: 

https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md

**Comment by ilovezfs** [comment]
I believe the vendored `glew1` will have to be overhauled as well, amongst other significant changes.

**Comment by dpo** [comment]
@bruce3141 See [these instructions](https://github.com/Homebrew/homebrew-science/issues/4307#issuecomment-247170702) for how to update a formula and submit a PR.
