### ISSUE TITLE
graph-tool fails to compile with --with-python3

### ISSUE THREAD

**Issue by mbahri** [Homebrew/homebrew-science#4351]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
Last 15 lines from ~/Library/Logs/Homebrew/graph-tool/02.make:
../../../../src/graph/generation/graph_triangulation.hh:117:27: note: in instantiation of member function 'CGAL::Periodic_3_Delaunay_triangulation_3<CGAL::Periodic_3_triangulation_traits_3<CGAL::Epick, CGAL::Periodic_3_offset_3, true>, CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_3<CGAL::Periodic_3_triangulation_traits_3<CGAL::Epick, CGAL::Periodic_3_offset_3, true>, CGAL::Periodic_3_triangulation_ds_vertex_base_3<void> >, CGAL::Triangulation_cell_base_3<CGAL::Periodic_3_triangulation_traits_3<CGAL::Epick, CGAL::Periodic_3_offset_3, true>, CGAL::Periodic_3_triangulation_ds_cell_base_3<void> >, CGAL::Sequential_tag> >::insert' requested here
            vertex_map[*T.insert(p)] = v;
                          ^
../../../../src/graph/generation/graph_triangulation.cc:101:17: note: in instantiation of function template specialization 'graph_tool::get_triangulation<CGAL::Periodic_3_Delaunay_triangulation_3<CGAL::Periodic_3_triangulation_traits_3<CGAL::Epick, CGAL::Periodic_3_offset_3, true>, CGAL::Triangulation_data_structure_3<CGAL::Triangulation_vertex_base_3<CGAL::Periodic_3_triangulation_traits_3<CGAL::Epick, CGAL::Periodic_3_offset_3, true>, CGAL::Periodic_3_triangulation_ds_vertex_base_3<void> >, CGAL::Triangulation_cell_base_3<CGAL::Periodic_3_triangulation_traits_3<CGAL::Epick, CGAL::Periodic_3_offset_3, true>, CGAL::Periodic_3_triangulation_ds_cell_base_3<void> >, CGAL::Sequential_tag> >, std::__1::integral_constant<bool, true> >::operator()<boost::UndirectedAdaptor<boost::adj_list<unsigned long> >, boost::multi_array_ref<double, 2>, boost::checked_vector_property_map<std::__1::vector<double, std::__1::allocator<double> >, boost::typed_identity_property_map<unsigned long> > >' requested here
                (g, points_array, pos_map);
                ^
/usr/local/include/CGAL/internal/Static_filters/Side_of_oriented_sphere_3.h:40:3: note: candidate function not viable: requires 5 arguments, but 10 were provided
  operator()(const Point_3 &p, const Point_3 &q, const Point_3 &r,
  ^
1 error generated.
make[3]: *** [graph_triangulation.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

#### Brief summary of issue:

graph-tool compilation fails on El Capitan with --with-python3

#### The complete command that you issued:
brew install boost-python --with-python3
brew install --with-python3

#### Gist with output of `brew doctor`:
https://gist.github.com/mbahri/2d9f944f18f568c89abddd8b83482c9c

#### Link output by `brew gist-logs <formula>`: 
https://gist.github.com/19b4dc2c0cdd5a13f19feb37af5bf468

#### Output of `brew config`:
HOMEBREW_VERSION: 1.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 817bc2746e594761911edd78f743a640f089494f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fc7bac40d41b5f13810c61c41ea4c89ad89bbe55
Core tap last commit: 50 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
For reference, the error is
```
In file included from ../../../../src/graph/generation/graph_triangulation.cc:56:
/usr/local/include/CGAL/Periodic_3_Delaunay_triangulation_3.h:266:12: error: no matching function for call to object of type 'Side_of_oriented_sphere_3' (aka 'Side_of_oriented_sphere_3<CGAL::Filtered_kernel_base<CGAL::Type_equality_wrapper<CGAL::Cartesian_base_no_ref_count<double, CGAL::Epick>, CGAL::Epick> > >')
    return geom_traits().side_of_oriented_sphere_3_object()(
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
@count0 Can you tell if this is an issue with `graph-tool`? It seems related to https://git.skewed.de/count0/graph-tool/issues/333. Here's a link to the detailed error message:
https://gist.github.com/anonymous/19b4dc2c0cdd5a13f19feb37af5bf468#file-02-make-L118

**Comment by count0** [comment]
Yes, this is the same issue. It is already fixed in git, and will be available in the next release. In the mean time, there is a patch that fixes it here: https://aur.archlinux.org/cgit/aur.git/tree/0001-Fix-compilation-problem-with-newer-CGAL.patch?h=python-graph-tool

**Comment by dpo** [comment]
Thanks! Should be fixed. Please `brew update`.
