### ISSUE TITLE
RepeatScout broken link

### ISSUE THREAD

**Issue by nextgenusfs** [Homebrew/homebrew-science#4356]
The download link to `repeatscout` seems to be broken (http://repeatscout.bioprojects.org/RepeatScout-1.0.5.tar.gz).  The alternative link is still active from the RepeatMasker website here: http://www.repeatmasker.org/RepeatScout-1.0.5.tar.gz.

**Comment by dpo** [comment]
Thanks for the heads up! It would be great if you could submit a pull request to fix the URL.

**Comment by nextgenusfs** [comment]
I tried to do this, but never done it before, hopefully I didn't screw up.... https://github.com/Homebrew/homebrew-science/pull/4357
