### ISSUE TITLE
brew tap homebrew/science on macOS 10.12

### ISSUE THREAD

**Issue by vincentqiu** [Homebrew/homebrew-science#4363]
brew tap homebrew/science

qxf:caffe qxf$ brew tap homebrew/science
==> Tapping homebrew/science
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 638, done.
remote: Compressing objects: 100% (634/634), done.
remote: Total 638 (delta 1), reused 66 (delta 0), pack-reused 0
Receiving objects: 100% (638/638), 557.50 KiB | 474.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/hdf5.rb
undefined method `rebuild' for #<BottleSpecification:0x007faa67135e98>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/jellyfish-1.1.rb
undefined method `rebuild' for #<BottleSpecification:0x007faa66ae47d8>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/p4est.rb
undefined method `rebuild' for #<BottleSpecification:0x007faa672dd390>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/plink.rb
undefined method `rebuild' for #<BottleSpecification:0x007faa6835da08>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/sortmerna.rb
invalid attribute for formula 'homebrew/science/sortmerna': version (nil)
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/transfig.rb
undefined method `rebuild' for #<BottleSpecification:0x007faa66479a88>
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-science/xraylib.rb
undefined method `rebuild' for #<BottleSpecification:0x007faa68446f50>
Error: Cannot tap homebrew/science: invalid syntax in tap!

**Comment by jonchang** [comment]
Hi @vincentqiu, could you please fill out the [Issue Template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md)? This will help us diagnose this problem. Thanks!

**Comment by dpo** [comment]
Try
```
cd /usr/local/Library/Taps/homebrew/homebrew-science && git fetch && git reset --hard origin/master
```
If that doesn't do it, please open a new issue and fill out the issue template. Thanks.
