### ISSUE TITLE
scotch on macOS 10.12 Sierra gives "internal link edit command failed"

### ISSUE THREAD

**Issue by johnsonea** [Homebrew/homebrew-science#4382]
### Indicate troubleshooting steps taken

- [Y] Ran `brew update` and retried your prior step?
- [Y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [Y] Checked that a similar issue hasn't already been filed?
- [?] Looked up the software bug tracker if reporting a build error?
- [N] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
libtool -lm -lz -lpthread -lbz2 -dynamic -install_name /usr/local/Cellar/scotch/6.0.4_3/lib/libscotcherrexit.dylib -undefined dynamic_lookup -o  libscotcherrexit.dylib library_error_exit.o
ld: file not found: <98>}+¹ÿ^?
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: internal link edit command failed

#### Brief summary of issue:
installing scotch seems to give some linking error for a file that does not exist -- sometimes, the "file not found:" is followed by nothing, and sometimes with gobbledygook as in the example above. This is a brand new system with a clean install of macOS 10.12 Sierra.

#### The complete command that you issued:
brew install scotch

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/daf007261855106e27f2cebddf45c71b

#### Output of `brew config`:
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6246278859f76ee1142754412d44a80eb1da0c6
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e2f1387198a64963239c098d62584e1be1d27e05
Core tap last commit: 39 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: N/A

[01.make.txt](https://github.com/Homebrew/homebrew-science/files/502258/01.make.txt)

**Comment by dpo** [comment]
Thanks for the report. That seems odd. I opened #4383 to see if the same happens on the bot as I don't have access to a 10.12 system.

**Comment by dpo** [comment]
Should be good now. Please `brew update` and try again.

**Comment by johnsonea** [comment]
Works. Thx!

On Oct 2, 2016, at 3:39 PM, Dominique <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be good now. Please brew update and try again.
