### ISSUE TITLE
Octave install fails in Ubuntu

### ISSUE THREAD

**Issue by nir-krakauer** [Homebrew/homebrew-science#4387]
The message is `configure: error: unrecognized option: '-lblas -llapack'`

[Gist](https://gist.github.com/62bf06cd9f47902de1ad0aaa0a536d09)

**Comment by dpo** [comment]
Thanks for the report. #4394 should fix it.

**Comment by dpo** [comment]
Please `brew update`. It should be alright now.

**Comment by nir-krakauer** [comment]
It works now. Thanks!
