### ISSUE TITLE
Build LAMMPS as a shared directory on Mac

### ISSUE THREAD

**Issue by graz90** [Homebrew/homebrew-science#4392]
### Indicate troubleshooting steps taken
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
#### Brief summary of issue:

Hi,

I am trying to build LAMMPS as a Shared Directory on MAC OS X Yosemite after installation with Homebrew. On LAMMPS tutorial is specified that I should launch the following command on terminal:
make foo mode=shlib  

where foo is the machine name or serial. After several trials the command doesn't work; for each trial I receive the following output: make: **\* No rule to make target <machine_name_trial>.
I moreover tried to use 'brew' or 'brew config' instead of make but I am still unable to call Lammps library in my Python script.
What command should I use and what should I use instead of foo?

Thanks a lot for your help.

Graziano
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Hi. I am not sure what you are trying to achieve. When you installed lammps with brew, brew already compiled it as a shared library for you. The command `make mac mode=shlib` is [already in the brew formula](https://github.com/Homebrew/homebrew-science/blob/master/lammps.rb#L180), so you don't need to do that again. You can just start using lammps.

**Comment by graz90** [comment]
I see, maybe the issue is related to something else.
What I am trying to do is to launch this basic Python script from Mac, that should load my LAMMPS file whose name is passed from command line and run it at once.

---------------------------

from __future__ import print_function
import sys

# parse command line

argv = sys.argv
if len(argv) != 2:
  print("Syntax: trivial.py in.lammps")
  sys.exit()

infile = sys.argv[1]

from lammps import lammps
lmp = lammps()

# run infile all at once

lmp.file(infile)

------------------------------------

But when launch the script I receive the following output:

Traceback (most recent call last):
  File "trivial.py", line 21, in <module>
    from lammps import lammps
ImportError: No module named lammps

------------------------------

The script works fine on a Ubuntu system that has been configured adding manuallly LAMMPS as a shared library; that's the reason why I was thinking that the issue was related to that.

Thanks for your help,

Graziano

**Comment by graz90** [comment]
Ah sorry for the strange layout, the comments on my script seem to be reported as giant words here.

**Comment by graz90** [comment]
Maybe the issue is solved, I tried to install the Homebrew version of Python by simply requiring:
brew install python 
and the LAMMPS library is correctly loaded in my Python script. Is it possible that the problem was just related to the fact that my Python version was obsolete, or at least non compatible with Homebrew configurations?

**Comment by dpo** [comment]
It probably means that Homebrew LAMMPS links by default with Homebrew Python, which is actually a bug (though I'm glad your script is now working).

**Comment by dpo** [comment]
Confirmed that that's the problem:
<pre>
$ otool -L /usr/local/opt/lammps/lib/python2.7/site-packages/liblammps.so
/usr/local/opt/lammps/lib/python2.7/site-packages/liblammps.so:
	/usr/local/opt/lammps/lib/python2.7/site-packages/liblammps_mac.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libfftw3.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/local/opt/jpeg/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	<b>/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)</b>
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.17.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/opt/open-mpi/lib/libmpi_cxx.1.dylib (compatibility version 3.0.0, current version 3.3.0)
	/usr/local/opt/open-mpi/lib/libmpi.12.dylib (compatibility version 13.0.0, current version 13.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
</pre>

**Comment by iMichka** [comment]
That was fixed by deeb5e3a23ea5fa581175a52ceff47a3bfa586d0, by using `-undefined dynamic_lookup`. Closing here.
