### ISSUE TITLE
GMT4 update from SOEST

### ISSUE THREAD

**Issue by cll12** [Homebrew/homebrew-science#4410]
GMT4 has been updated (as of Oct 1, 2016). The download url for gmt-4.5.14 in gmt4.rd no longer points to a file that exists. This is also true of the gshhg-gmt2.3.4 file, which has also be updated. The lines should now read:

url "ftp://ftp.soest.hawaii.edu/gmt/gmt-4.5.15-src.tar.bz2"
and
url "ftp://ftp.soest.hawaii.edu/gmt/gshhg-gmt-2.3.6.tar.gz"

I tried to alter the gmt4.rd code and go through the proper pull request steps. Since I have never used github before, however, I do not think I did that correctly.

### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Closing in view of #4409.
