### ISSUE TITLE
octave pkg install error

### ISSUE THREAD

**Issue by santhosh1993** [Homebrew/homebrew-science#4425]
octave:1> pkg install -forge general control signal image
In file included from __control_helper_functions__.cc:7:
./lti_input_idx.cc:65:48: warning: 'nelem' is deprecated
      [-Wdeprecated-declarations]
    octave_idx_type len = args(0).cell_value().nelem();
                                               ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:360:19: note: 
      'nelem' has been explicitly marked deprecated here
  octave_idx_type nelem (void) const { return numel (); }
                  ^
1 warning generated.
clang: warning: argument unused during compilation: '-pthread'
In file included from __control_slicot_functions__.cc:24:
./sl_tg04bx.cc:79:33: warning: 'length' is deprecated
      [-Wdeprecated-declarations]
        octave_idx_type ip = pr.length ();  // ip: number of finite poles
                                ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:354:19: note: 
      'length' has been explicitly marked deprecated here
  octave_idx_type length (void) const { return numel (); }
                  ^
In file included from __control_slicot_functions__.cc:24:
./sl_tg04bx.cc:80:33: warning: 'length' is deprecated
      [-Wdeprecated-declarations]
        octave_idx_type iz = zr.length ();  // iz: number of zeros
                                ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:354:19: note: 
      'length' has been explicitly marked deprecated here
  octave_idx_type length (void) const { return numel (); }
                  ^
In file included from __control_slicot_functions__.cc:42:
./sl_ident.cc:184:40: warning: 'nelem' is deprecated [-Wdeprecated-declarations]
        octave_idx_type n_exp = y_cell.nelem ();            // number o...
                                       ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:360:19: note: 
      'nelem' has been explicitly marked deprecated here
  octave_idx_type nelem (void) const { return numel (); }
                  ^
In file included from __control_slicot_functions__.cc:43:
./sl_ib01cd.cc:97:40: warning: 'nelem' is deprecated [-Wdeprecated-declarations]
        octave_idx_type n_exp = y_cell.nelem ();            // number o...
                                       ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:360:19: note: 
      'nelem' has been explicitly marked deprecated here
  octave_idx_type nelem (void) const { return numel (); }
                  ^
In file included from __control_slicot_functions__.cc:44:
./sl_ib01ad.cc:148:40: warning: 'nelem' is deprecated
      [-Wdeprecated-declarations]
        octave_idx_type n_exp = y_cell.nelem ();            // number o...
                                       ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:360:19: note: 
      'nelem' has been explicitly marked deprecated here
  octave_idx_type nelem (void) const { return numel (); }
                  ^
5 warnings generated.
clang: warning: argument unused during compilation: '-pthread'
ld: warning: could not create compact unwind for _sb10yd_: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _mb03xp_: stack subq instruction is too different from dwarf stack size
SHA1.cc:63:7: warning: 'usage' is deprecated [-Wdeprecated-declarations]
      usage("SHA1");
      ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/error.h:58:6: note: 
      'usage' has been explicitly marked deprecated here
void usage (const char *fmt, ...);
     ^
SHA1.cc:68:16: warning: 'length' is deprecated [-Wdeprecated-declarations]
      if (init.length() != 20) 
               ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:354:19: note: 
      'length' has been explicitly marked deprecated here
  octave_idx_type length (void) const { return numel (); }
                  ^
SHA1.cc:84:17: warning: 'length' is deprecated [-Wdeprecated-declarations]
   int len=data.length();
                ^
/usr/local/Cellar/octave/4.2.0-rc2/include/octave-4.2.0-rc2/octave/Array.h:354:19: note: 
      'length' has been explicitly marked deprecated here
  octave_idx_type length (void) const { return numel (); }
                  ^
clang: warning: argument unused during compilation: '-pthread'
3 warnings generated.
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
configure: error: *** A compiler with support for C++11 is required
checking for a sed that does not truncate output... /usr/local/bin/gsed
checking for octave... /usr/local/Cellar/octave/4.2.0-rc2/bin/octave-4.2.0-rc2
checking for mkoctfile... /usr/local/Cellar/octave/4.2.0-rc2/bin/mkoctfile-4.2.0-rc2
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -std=gnu++11 accepts -g... yes
checking for clang++ -std=gnu++11 option to enable C++11 features... unsupported

pkg: error running the configure script for image.
error: called from
    install at line 200 column 5
    pkg at line 392 column 9
octave:1>

**Comment by dpo** [comment]
Please fill out the issue template. Thank you.

**Comment by santhosh1993** [comment]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

#### Brief summary of issue:

#### The complete command that you issued:

#### Gist with output of `brew doctor`:

#### Link output by `brew gist-logs <formula>`:

#### Output of `brew config`:

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sunilshah** [comment]
I did manage to install and run control and signal packages from forge on Octave 4.2-rc2 on Sierra. 

See post #4418.

**Comment by dpo** [comment]
Closing this. Please open a new issue and fill out the issue template if there are still problems.
