### ISSUE TITLE
command not found: pcl_viewer after install pcl on Macos

### ISSUE THREAD

**Issue by universewill** [Homebrew/homebrew-science#4437]
I install pcl using command "brew install pcl".
I run command "pcl_viewer 1.pcd" in terminal but the command is not found.

I find the pcl_viewer binary file in path:
/usr/local/Cellar/pcl/1.8.0_2/pcl_viewer.app/Contents/MacOS

How can i fix this problem?

**Comment by dpo** [comment]
`pcl` is built as an app by default. If you want to use it from the command line, try `brew install pcl --without-apps`.

**Comment by universewill** [comment]
I uninstall pcl using "brew uninstall pcl", and then install pcl with command "brew install pcl --without-apps"
But the error still exists

**Comment by pbrazdil** [comment]
Tried as well, not working.

**Comment by adamwtow** [comment]
Issue exists for me also. Is there a fix yet to get pcl_viewer on macos sierra?

**Comment by iMichka** [comment]
pcl has been migrated to homebrew-core (#6153). Please open a new issue there if you still encounter problems.
