### ISSUE TITLE
Failed building netcdf, missing open-mpi

### ISSUE THREAD

**Issue by duytruong27** [Homebrew/homebrew-science#4459]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
ld: file not found: /usr/local/opt/open-mpi/lib/libmpi.12.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libnetcdf.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

#### Brief summary of issue:
libmpi.12.dylib not found, but the version 2.0 of open-mpi was installed, the "find" command returned the result for libmpi.20.dylib

#### The complete command that you issued:
brew install netcdf

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/c20824f56beca3f74d6baae1839d03c3

#### Output of `brew config`:
HOMEBREW_VERSION: 1.0.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0546d90e3dbdae30407e5256d680be5ed5f5f000
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 38f88a7683ed1a9f4e072752266a3f5b06daa7b7
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_73
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: 2.7.9 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Did you previously install `hdf5` `--with-mpi`? If so, you'll need to recompile `hdf5` from source because it's still pointing to an outdated version of OpenMPI.

**Comment by duytruong27** [comment]
Sorry for the late response.

By removing `hdf5` and run `brew install netcdf` again, the problem is solved. Thank you very much for your help!
Now I am able to install `petsc`, whose dependencies are hdf5 and netcdf.

**Comment by dpo** [comment]
Enjoy!
