### ISSUE TITLE
CASROOT suggestion for oce is incorrect (opt_prefix does not exist)

### ISSUE THREAD

**Issue by henrybaxter** [Homebrew/homebrew-science#4482]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:

Homebrew says:
    Some apps will require this enviroment variable:
        CASROOT=/usr/local/opt/oce/share/oce-0.17.2

But

```
henry$ ls /usr/local/opt/oce/share/oce-0.17.2
    ls: /usr/local/opt/oce/share/oce-0.17.2: No such file or directory
```

However

```
henry$ ls /usr/local/opt/oce/share/oce-0.17/
    src
```
#### Brief summary of issue:

CASROOT suggestion is wrong (opt_prefix in .rb file corresponds to directory that is not there)
#### The complete command that you issued:

```
brew install oce
ls /usr/local/opt/oce/share/oce-0.17.2
```
#### Output of `brew config`:

HOMEBREW_VERSION: 1.0.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0546d90e3dbdae30407e5256d680be5ed5f5f000
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aa3faec5ab195f2c5c278b44f704649cd1dbfdb4
Core tap last commit: 48 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 12-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/henry/.rbenv/shims/ruby => /Users/henry/.rbenv/versions/2.2.3/bin/ruby
Java: 1.8.0_05
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: 2.7.8 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
There may not be a cleaner solution to this than defining the version in the preamble of the formula, in the form
```
ver_major = "0.17"
ver_minor = "2"
version = "#{ver_major}.#{ver_minor}
```
and then in the caveats, use only `ver_major`.

Do you want to submit a PR with those changes?

**Comment by ilovezfs** [comment]
Isn't this because it's just dumping stuff in share?

**Comment by dpo** [comment]
`pkgshare` would still contain the minor version number I believe.
