### ISSUE TITLE
asl (3.1.0_1) failed to build on 10.12

### ISSUE THREAD

**Issue by drdv** [Homebrew/homebrew-science#4490]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

mex: compile of asl/solvers/examples/amplfunc.c failed

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/anonymous/52d844b0df5081c6e732b587aaa8d6ef

**Comment by dpo** [comment]
That's an interesting error:
```
cd /tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src/cp && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DMP_DATE=20141202 -DMP_SYSINFO="\"Darwin x86_64\"" -DMP_USE_ATOMIC -DMP_USE_HASH -DMP_USE_UNIQUE_PTR -Dcp_EXPORTS -I/tmp/asl-20161019-73152-1021ilp/mp-3.1.0/include -I/tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src/asl/include -I/tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src/asl/solvers -I/tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src/asl -I/tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src  -Wall -Wextra -pedantic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -std=c++11 -o CMakeFiles/cp.dir/cp.cc.o -c /tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src/cp/cp.cc
clang: error: unable to find utility "clang", not a developer tool or in PATH

    mex: compile of ' "/tmp/asl-20161019-73152-1021ilp/mp-3.1.0/src/asl/solvers/examples/spamfunc.c"' failed.
```
Did you run `mexopts` locally to tell Matlab about clang?

**Comment by drdv** [comment]
Thanks dpo, I don't know how I missed this!
I updated SDKROOT and MACOSX_DEPLOYMENT_TARGET in mexopts.sh and this fixed the issue.

**Comment by dpo** [comment]
👍
