### ISSUE TITLE
Install Graph-Tool

### ISSUE THREAD

**Issue by matthisk** [Homebrew/homebrew-science#4491]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
>>> import graph_tool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/graph_tool/__init__.py", line 106, in <module>
    dl_import("from . import libgraph_tool_core as libcore")
  File "/usr/local/lib/python2.7/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so, 8): Symbol not found: __ZNK5boost16re_detail_10610031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/lib/python2.7/site-packages/graph_tool/libgraph_tool_core.so
```

#### Brief summary of issue:

Yesterday I have tried to install graph-tool on OS X (10.10.5) using Brew, unfortunately I keep on running into the following issue (see bug reports/build errors) once I load graph-tool in Python.

I have been going to several related issues and tried some of the suggestions:
- install with --build-from-source 
- separately install boost and boost-python using brew (and --build-from-source)
- updating llvm (and reinstall graph_tool from source)
- using homebrew/versions/boost155

For the complete commands see the next section

#### The complete command that you issued:

Standard install
```
brew install graph-tool
```

Build from source (same c++ compiler)
```
brew install boost --build-from-source
brew install boost-python --build-from-source
brew install graph-tool --build-from-source
```

Build from source with HEAD of graph-tool package
```
brew install boost --build-from-source
brew install boost-python --build-from-source
brew install graph-tool --build-from-source --HEAD
```

Build with boost155
```
brew install homebrew/versions/boost155 --build-from-source
brew install graph-tool --build-from-source --HEAD
```
(I am not sure if graph-tool will actually select boost155 in this scenario?)

#### Gist with output of `brew doctor`:

"Your system is ready to use brew"

#### Link output by `brew gist-logs <formula>`:

"Error: No Logs"
? This is weird no idea why brew is not giving me any logs for graph-tool

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.0.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0296439c832a915be9b73456c0c26bc6c79c271d
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c724d397591d27f729978d3ed5872ba0e35ca85
Core tap last commit: 81 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.6.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/matthisk/.rvm/rubies/ruby-2.2.1/bin/ruby
Java: 1.8.0_65, 1.8.0_60
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: N/A
```

**Comment by dpo** [comment]
Same as #3237.
