### ISSUE TITLE
octave control package fails to install on 4.2_rc2 on sierra

### ISSUE THREAD

**Issue by sunilshah** [Homebrew/homebrew-science#4494]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sunilshah** [comment]
Following up on #4418 and #4425

On Mac OS Sierra, 
brew update

brew uninstall octave
brew install octave 

This completed with no errors.  Both gui version and cli run and produce plots using qt. 

However, control package does not install any more. 

in Octave, 

pkg uninstall control signal
pkg  install -forge control singal

clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin16.0.0/6.2.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin16.0.0/6.2.0/../../..'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [__control_slicot_functions__.oct] Error 1
tar -xzf slicot.tar.gz
/usr/local/Cellar/octave/4.2.0-rc2_1/bin/mkoctfile-4.2.0-rc2 __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp; /usr/local/Cellar/octave/4.2.0-rc2_1/bin/mkoctfile-4.2.0-rc2 -c *.f
ar -rc slicotlibrary.a ./sltmp/*.o
rm -rf sltmp slicot
LFLAGS="-L/usr/local/Cellar/octave/4.2.0-rc2_1/lib/octave/4.2.0-rc2 -L/usr/local/Cellar/octave/4.2.0-rc2_1/lib  -L/usr/local/opt/veclibfort/lib -lvecLibFort  -L/usr/local/opt/readline/lib -L/usr/local/opt/suite-sparse/lib -L/usr/local/opt/metis/lib -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin16.0.0/6.2.0 -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin16.0.0/6.2.0/../../.. -lreadline -lsuitesparseconfig -lmetis -lgfortran -lquadmath -lm" \
    /usr/local/Cellar/octave/4.2.0-rc2_1/bin/mkoctfile-4.2.0-rc2 __control_slicot_functions__.cc common.cc slicotlibrary.a

pkg: error running `make' for the control package.
error: called from
    install at line 200 column 5
    pkg at line 392 column 9

brew doctor gives no errors / warnings

I notices that both octave 4.0.3 and 4.2-rc2 are installed
So are gcc 6.1.0 and 6.2.0

**Comment by dpo** [comment]
For good measure, could you tell us if it still fails after doing `brew uninstall -f $(brew deps --recursive octave); brew install octave`?

**Comment by sunilshah** [comment]
I did the following before I saw your comment:

brew uninstall -force octave
brew uninstall -force gcc
brew install gcc
brew install octave

Then in octave

pkg load -forge control signal 

worked.  

Dominque, what will the command you gave do now? Or do you already have your answer?

Thnx

**Comment by dpo** [comment]
I have my answer. My suggestion is the sledgehammer that removes everything `octave` depends on to install a fresh copy with fresh (unique) dependencies. Thank you and enjoy!
