### ISSUE TITLE
Octave struct package fails to install on 4.2.0-rc2

### ISSUE THREAD

**Issue by houtanb** [Homebrew/homebrew-science#4497]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
I am having difficulty installing octave packages. I followed the instructions in #4494 and still cannot install the package. Specifically, I ran the instructions listed [here](https://github.com/Homebrew/homebrew-science/issues/4494#issuecomment-254919604) and could not install the package. I then ran the instruction listed [here](https://github.com/Homebrew/homebrew-science/issues/4494#issuecomment-254905170) and still could not install the package. The error I encounter is listed [here](https://gist.github.com/houtanb/477478495ccb39955ae8a537b898b80d).

#### The complete command that you issued:
In Octave: `pkg install -forge struct`

#### Gist with output of `brew doctor`:
https://gist.github.com/houtanb/479f685a9e377f5f10d58a43ba259ace

#### Output of `brew config`:
https://gist.github.com/houtanb/d2ffbff0ececf8b6392eed8c254d5f77

**Comment by dpo** [comment]
Could you please try https://github.com/Homebrew/homebrew-science/issues/4494#issuecomment-254905170?

**Comment by houtanb** [comment]
@dpo yes, I tried both the comment you referenced (modified to be `brew uninstall -f $(brew deps --recursive octave); brew uninstall octave; brew install octave`) AND [the one after it](https://github.com/Homebrew/homebrew-science/issues/4494#issuecomment-254919604). The problem persists.

**Comment by ilovezfs** [comment]
seems fine here
<img width="665" alt="screen shot 2016-10-21 at 3 41 17 am" src="https://cloud.githubusercontent.com/assets/5268928/19595798/7e743874-9740-11e6-9bb4-e09fd6ad96cb.png">

**Comment by houtanb** [comment]
It is not fine here:
https://gist.github.com/houtanb/c16f9c2ec36d997a0f74c7acf9d9465b

**Comment by ilovezfs** [comment]
Have you set anything in your environment related to compilation?

**Comment by houtanb** [comment]
```
• env
TERM_PROGRAM=Apple_Terminal
HOMEBREW_TEMP=/Users/houtanb/scratch/homebrew_tmp
SHELL=/bin/bash
TERM=xterm-256color
CLICOLOR=1
HISTSIZE=10000
TMPDIR=/var/folders/76/9j1x4d452yn1z1bm2605y5k80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.3BtcYSgzwg/Render
TERM_PROGRAM_VERSION=377
MATLABROOT=/Applications/MATLAB_R2016b.app
OLDPWD=/Users/houtanb/Documents/DYNARE/dseries/src/utilities/str
TERM_SESSION_ID=E559318B-FC97-4948-83DB-728F7AA34F68
USER=houtanb
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Bcbri4nBNv/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PAGER=less
LSCOLORS=ExfxBxDxbxegedabagacad
PATH=/Users/houtanb/anaconda2/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/usr/texbin
PWD=/Users/houtanb
EDITOR=emacs
LANG=en_US.UTF-8
XPC_FLAGS=0x0
PS1=\n\e[4;31m\w\[\033[0m\]\n\[\033[1;31m\]•\[\033[0m\] 
HISTIGNORE=&:pwd:ls:ll:lal:[bf]g:exit:rm*:sudo rm*
HISTCONTROL=erasedups
CXX=g++
PS2=\[\033[1;31m\]•\[\033[0m\] 
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/houtanb
FC=gfortran
LOGNAME=houtanb
VISUAL=emacs
PROMPT_COMMAND=set_my_prompt
ALTERNATE_EDITOR=emacs
CC=gcc
DISPLAY=/private/tmp/com.apple.launchd.7SYN0bI2fZ/org.macosforge.xquartz:0

• gfortran --version
GNU Fortran (Homebrew gcc 6.2.0) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

• gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

• g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ilovezfs** [comment]
OK, so let's not set those ...
```
unset CXX
unset FC
unset CC
<try again>
```

**Comment by houtanb** [comment]
That worked. Thanks so much.

**Comment by ilovezfs** [comment]
You're welcome :)
