### ISSUE TITLE
Installing nedit using homebrew 

### ISSUE THREAD

**Issue by aadrych** [Homebrew/homebrew-science#4499]
Hi, 

I recently installed nedit using homebrew and it successfully installed but whenever I call it I get the error:
Error: Couldn't find per display information
I Ran brew doctor but there was nothing recommended that might fix this?
Could you please recommend a way for nedit to work?

Thanks in advance

**Comment by ilovezfs** [comment]
You'll need to downgrade to Xquartz 2.7.8 and then rebuild openmotif from source. Then nedit will run (just tested that procedure here and it worked).

This issue duplicates https://github.com/Homebrew/homebrew-x11/issues/255.

**Comment by aadrych** [comment]
I also installed python using homebrew with no problem but when I try to import numpy I get the error
Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
Is this also a problem of Xquartz? Or an unrelated problem?
