### ISSUE TITLE
Downgrading to xquartz fails lammps call?

### ISSUE THREAD

**Issue by aadrych** [Homebrew/homebrew-science#4501]
Hi, 
I recently tried to install nedit again after it failed because of an xquartz upgrade. 
I did the recommended steps on https://github.com/Homebrew/homebrew-x11/issues/255
but when I did the brew upgrade && brew update step and then tried to call lammps through the python interface I get the error :

> > > from lammps import lammps
> > > lmp=lammps()
> > > Exception AttributeError: "'lammps' object has no attribute 'lmp'" in <bound method lammps.__del__ of <lammps.lammps object at 0x105e29190>> ignored
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/site-packages/lammps.py", line 63, in **init**
> > >     if not name: self.lib = CDLL("liblammps.so",RTLD_GLOBAL)
> > >   File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/**init**.py", line 362, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: dlopen(liblammps.so, 10): Library not loaded: /usr/local/opt/open-mpi/lib/libmpi_cxx.1.dylib
> > >   Referenced from: /usr/local/lib/liblammps.so
> > >   Reason: image not found

Before the brew upgrade, the lammps call through python was working fine. 
Could you recommend a way to fix this please? 
There was no advice recommended by brew doctor as well. 

Thanks in advance

**Comment by dpo** [comment]
Try `brew reinstall  open-mpi`.

**Comment by dpo** [comment]
Please fill out the issue template, including the output of `brew doctor` and the link output by `brew gist-logs lammps`.

**Comment by iMichka** [comment]
I will close this issue for now, as there was no response since Oct. 2016. Please open a new one and fill out the detailed issue template if this is still not working for you. Thanks.
