### ISSUE TITLE
Error install dynare Octave mac OSX 10.11

### ISSUE THREAD

**Issue by paulcahu** [Homebrew/homebrew-science#4513]
### Indicate troubleshooting steps taken

- [X ] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
'checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/dynare-20161024-50387-ivwjcp/dynare-4.4.3':
configure: error: C compiler cannot create executables'
#### Brief summary of issue:
I am trying to install dynare using Octave on Mac OSX.11
It seems that the gcc compiler does not work:

Could you help me with that?
Cheers.

#### The complete command that you issued:
'brew install dynare'
#### Gist with output of `brew doctor`:
'Your system is ready to brew.'
#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/anonymous/a8abcf296ab19661f49f2c741cc7a7e6

#### Output of `brew config`:
'HOMEBREW_VERSION: 1.0.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0296439c832a915be9b73456c0c26bc6c79c271d
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 245e7f5265ded9b082d3a1f9e44fff694ccb76f5
Core tap last commit: 15 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.10 => /opt/X11'
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
#4184 should fix it.

**Comment by paulcahu** [comment]
Thank you for your help. However, I am not sure to understand the answer. What should I do exactly?
Thanks again!

**Comment by ilovezfs** [comment]
You can `brew update` and `brew install dynare`

As for the error above, you can fix that by running
```
sudo xcode-select -r
```

**Comment by paulcahu** [comment]
Thank you very much. This fixed the problem indeed.
Best regards,
--
Paul Cahu
education@helloworld.bzh
