### ISSUE TITLE
Installation of ROOT complains about location of gcc

### ISSUE THREAD

**Issue by mckunkel** [Homebrew/homebrew-science#4515]
### Indicate troubleshooting steps taken

- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ X] Checked that a similar issue hasn't already been filed?
- [ X] Looked up the software bug tracker if reporting a build error?

### Bug reports / build errors:
No Build errors
#### Brief summary of issue:
For some reason "ilovezfs " calls this a ROOT issue and not a gcc issue. Maybe he/she did not read my post [https://github.com/Homebrew/homebrew-core/issues/6225](url) thoroughly. 

Regardless,  I just upgraded from OSX 10.10 Yosemite to 10.12 Sierra. Upgraded homebrew. Had to force remove gcc 5 and install gcc 6. 
However, when I build ROOT from source or Homebrew I see the following:

> ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5'

Since I have tried to build ROOT from their source, and I see the same error, I can only conclude that this has to be a gcc via homebrew issue.
Here is come brew info gcc
> michaelkunkel:QFactor_MK$ brew info gcc
gcc: stable 6.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/6.2.0 (1,435 files, 274.7M) *
  Poured from bottle on 2016-10-24 at 12:04:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-all-languages
	Enable all compilers and languages, except Ada
--with-java
	Build the gcj compiler
--with-jit
	Build the jit compiler
--with-nls
	Build with native language support (localization)
--without-fortran
	Build without the gfortran compiler
--without-multilib
	Build without multilib support
--HEAD
	Install HEAD version
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib

Here is some system info

> michaelkunkel:QFactor_MK$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323

Here is my homebrew configuation

> michaelkunkel:QFactor_MK$ brew config
HOMEBREW_VERSION: 1.0.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0296439c832a915be9b73456c0c26bc6c79c271d
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ccbfe2ae35a3dfb9eda2d83f939509ad0ec7b4f9
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_51
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: 2.7.9 => /opt/X11

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
You must have an old `gcc` lying around. Try `brew uninstall -f gcc` followed by `brew install root`.

**Comment by mckunkel** [comment]
I have already performed this action. To no avail. The error still appears.

**Comment by dpo** [comment]
Let's make sure some other dependency isn't still linking with an old gcc-5: `brew uninstall -f $(brew deps -r roots)`. Then let's `brew install roots` (pass options if you need to).

**Comment by ilovezfs** [comment]
@mckunkel did dpo's suggestion work?

**Comment by mckunkel** [comment]
I live in Europe, so my replies are a bit time disorienting. 
Here is the output of the first command

> michaelkunkel:QFactor_MK$ brew uninstall -f $(brew deps -r roots)
Error: No available formula with the name "roots"
brew uninstall, rm, remove [--force] formula:
    Uninstall formula.
 If --force is passed, and there are multiple versions of formula
    installed, delete all installed versions.
Error: Invalid usage: This command requires a keg argument

For 

> michaelkunkel:QFactor_MK$ brew install roots
Error: No available formula with the name "roots"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

If I assume dpo meant root and not roots

> michaelkunkel:QFactor_MK$ brew uninstall -f $(brew deps -r root)
Uninstalling gsl... (519 files, 16.5M)
Uninstalling openssl... (4,928 files, 36.4M)
Uninstalling xrootd... (236 files, 6.9M

and installing gave 

> michaelkunkel:QFactor_MK$ brew install root
Warning: homebrew/science/root-5.34.36_2 already installed

And now if I compile my macro the error of gcc 5 is gone. However gsl, openssl and xrootd was never reinstalled. If I do a full 

> brew uninstall root
> brew install root

gsl, openssl and xrootd are installed but the error of gcc 5 appears. Not sure the next course of action.

**Comment by ilovezfs** [comment]
```
grep -r gcc /usr/local/Cellar | grep 5.2.0
```
What's the output?

**Comment by mckunkel** [comment]
michaelkunkel:skimmer$ grep -r gcc /usr/local/Cellar | grep 5.2.0
/usr/local/Cellar/gcc/6.2.0/NEWS:   7. http://gcc.gnu.org/onlinedocs/5.2.0/

**Comment by ilovezfs** [comment]
ok, now try /usr/local
```
grep -r gcc /usr/local | grep 5.2.0
```

**Comment by mckunkel** [comment]
michaelkunkel:~$ grep -r gcc /usr/local | grep 5.2.0
/usr/local/Cellar/gcc/6.2.0/NEWS:   7. http://gcc.gnu.org/onlinedocs/5.2.0/
grep: /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/fuse.pc: No such file or directory
grep: /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/osxfuse.pc: No such file or directory
/usr/local/opt/gcc/NEWS:   7. http://gcc.gnu.org/onlinedocs/5.2.0/
grep: /usr/local/texlive/2014/bin/universal-darwin/man/man: No such file or directory
grep: /usr/local/texlive/2014/bin/x86_64-darwin/man/man: No such file or directory
grep: /usr/local/texlive/2014/texmf-dist/doc/man/man: No such file or directory
grep: /usr/local/texlive/2016/bin/universal-darwin/man/man: No such file or directory
grep: /usr/local/texlive/2016/bin/x86_64-darwin/man/man: No such file or directory
grep: /usr/local/texlive/2016/texmf-dist/doc/man/man: No such file or directory
%AI9_PrivateDataEndp%fI;;k=X<:75$UrGh=Pf_>i*0(DBEsQDXQ5L_Y)*kJ$k1N%hIl9D*Pii`Tp:rjn5n-0#%73r!u-POe@!1
/usr/local/var/homebrew/linked/gcc/NEWS:   7. http://gcc.gnu.org/onlinedocs/5.2.0/

**Comment by ilovezfs** [comment]
do you have any compilation related variables set in your environment?

**Comment by mckunkel** [comment]
I did, I removed it and everything is well.
Sorry for all this.

**Comment by ilovezfs** [comment]
@mckunkel it's no problem at all. Thanks for reporting the issue!
