### ISSUE TITLE
wrong superlu version dependency in homebrew-science/armadillo.rb

### ISSUE THREAD

**Issue by conradsnicta** [Homebrew/homebrew-science#4529]
@LogicalKnight @frownmonkey 
line 19 of homebrew-science/armadillo.rb has
    `depends_on "superlu43"`
This is not right.  Armadillo 7.x requires superlu 5.2, not 4.3.

I'd also recommend updating the formula to Armadillo 7.500, which is the latest upstream version.

**Comment by dpo** [comment]
Want to submit a pull request?

**Comment by conradsnicta** [comment]
I don't use Homebrew (or a mac).  I'm the upstream author of Armadillo.
I've filed this bug report after an email report from a user.

**Comment by dpo** [comment]
Thanks! See #4534.
