### ISSUE TITLE
Make error found when installing ABySS

### ISSUE THREAD

**Issue by lfunderburk** [Homebrew/homebrew-science#4532]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step? Yes
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? Yes. Did not remove anaconda temporarily from my $PATH even though was told this might cause issues while home-brew build. I do not know how to remove it from my $PATH. If this would solve my problem kindly direct me. I have installed programs through Home-brew before even though anaconda is in my $PATH so I am not 100% sure this is the issue. 
- [x] Checked that a similar issue hasn't already been filed? Yes
- [ ] Looked up the software bug tracker if reporting a build error? No
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`? No
### Bug reports / build errors:

==> make
Last 15 lines from /Users/crcadmin/Library/Logs/Homebrew/abyss/02.make:
        bidirectionalBFS(g, startKmer, goalKmer, visitor);
        ^
konnector.cc:740:3: note: in instantiation of function template specialization 'connectPairs<DBGBloom<BloomFilter> >' requested here
                connectPairs(opt::k, read1, read2, g, params);
                ^
konnector.cc:903:4: note: in instantiation of function template specialization 'connectPair<DBGBloom<BloomFilter>, BloomFilter>' requested here
                        connectPair(g, bloom, a, b, params, mergedStream, read1Stream,
                        ^
konnector.cc:1202:3: note: in instantiation of function template specialization 'connectPairs<DBGBloom<BloomFilter>, FastaConcat, BloomFilter>' requested here
                connectPairs(g, _bloom, in, params, mergedStream, read1Stream,
                ^
2 errors generated.
make[2]: *_\* [konnector-konnector.o] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2
#### Brief summary of issue:

I am trying to install ABySS on Mac OS Sierra and have bumped into these two errors after running brew update and brew doctor
#### The complete command that you issued:

brew install homebrew/science/abyss
#### Gist with output of `brew doctor`:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
MacVim, due to bundling many duplicates of system and Homebrew-available
tools.

If you encounter a build failure please temporarily remove Anaconda
from your $PATH and attempt the build again prior to reporting the
failure to us. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/crcadmin/anaconda/bin/curl-config
  /Users/crcadmin/anaconda/bin/freetype-config
  /Users/crcadmin/anaconda/bin/icu-config
  /Users/crcadmin/anaconda/bin/libdynd-config
  /Users/crcadmin/anaconda/bin/libpng-config
  /Users/crcadmin/anaconda/bin/libpng16-config
  /Users/crcadmin/anaconda/bin/python-config
  /Users/crcadmin/anaconda/bin/python2-config
  /Users/crcadmin/anaconda/bin/python2.7-config
  /Users/crcadmin/anaconda/bin/xml2-config
  /Users/crcadmin/anaconda/bin/xslt-config
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

THANK YOU FOR ALL YOUR WORK! IT IS HIGHLY APPRECIATED :)
- Laura

**Comment by jonchang** [comment]
Hi @lfunderburk, it probably is caused by anaconda in your PATH. You should be able to temporarily remove it from your PATH on macOS by running `unset PATH && source /etc/profile`.

**Comment by jonchang** [comment]
I assume that this problem has been fixed. Feel free to file a new issue or reopen this one if it hasn't.
