### ISSUE TITLE
revisions for icu4c 58.1 needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#4560]
- [x] libfolia (libfolia 1.8 #6160)
- [x] ucto (ucto 0.9.6 #6163)
- [x] vislcg3 (vislcg3 1.0.1-alpha1 #6165)

RE: https://github.com/Homebrew/homebrew-core/pull/6505

CC @dpo @sjackman

**Comment by dpo** [comment]
cf. #3522, #4092
