### ISSUE TITLE
picard tools specify java memory usage.

### ISSUE THREAD

**Issue by ccshao** [Homebrew/homebrew-science#4562]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
I installed the picard-tools via brew, it works fine. 
type `picard` give help information and commands to use
However, how to specify java memory and other java related options, 
like:
`java -Xmx10g  -jar picard.jar`

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment]
Is this a Homebrew question or a pucard-tools question?

**Comment by ccshao** [comment]
@dpo I think it is a homebrew question as picard is packed by in homebrew/science. In the official site of picard-tools they only provide the picard.jar.

**Comment by iMichka** [comment]
Hi.

Homebrew only downloads the .zip from the official site, extracts it, and copies the .jar to /usr/local/share/java/picard.jar. Not sure how we could something about it.

When you just run ```picard```, it will use whatever defaults the picard developers have set, or the default set by the JVM.
It's up to you to call it with the right flags: ```java -Xmx10g -jar /usr/local/share/java/picard.jar```.

If you want to run that automatically when calling picard in the terminal, you could have a bash script doing this for you, or use a tool like launch4j (```brew install launch4j```). I never used it though, so you may need to play around with it and see if it fits your needs.

**Comment by iMichka** [comment]
I will close this issue to keep the issue tracker clean.

I do believe that this is not a Homebrew issue. I gave a detailed solution on how you could handle this problem.

If you think I am wrong, please open a new issue with more details, so that we might reconsider the problem.
