### ISSUE TITLE
how to run lammps on Mac OS X

### ISSUE THREAD

**Issue by tonyxy1992** [Homebrew/homebrew-science#4572]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
 Desktop mpirun -np 4 lmp_mpi < input.in
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       wirelessprv-10-193-12-248
Executable: lmp_mpi
--------------------------------------------------------------------------
4 total processes failed to start
#### Brief summary of issue:
cannot run lammps on Mac OS X
#### The complete command that you issued:
Desktop mpirun -np 4 lmp_mpi < input.in   desktop is where the file is stored
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
Hi @tonyxy1992, we don't provide support for how to run Homebrew formula. But I note that there is no `lmp_mpi` file installed with `lammps`. I would recommend emailing the lammps mailing list or filing a support ticket with their developers.
