### ISSUE TITLE
gmap-gsnap: Depends on perl [macOS Sierra]

### ISSUE THREAD

**Issue by nextgenusfs** [Homebrew/homebrew-science#4584]
On Mac 10.12.1 - there is no bottle for Sierra in the formula and building from source apparent fails.  I also tried the more recent version available with similar errors.

```
~$ brew doctor
Your system is ready to brew.
~$ brew update
Already up-to-date.
~$ brew install gmap-gsnap
==> Installing gmap-gsnap from homebrew/science
==> Downloading http://research-pub.gene.com/gmap/src/gmap-gsnap-2016-05-01.tar.gz
Already downloaded: /Users/ngs/Library/Caches/Homebrew/gmap-gsnap-2016-05-01.tar.gz
==> ./configure --prefix=/usr/local/Cellar/gmap-gsnap/2016-05-01
==> make
==> make check
Last 15 lines from /Users/ngs/Library/Logs/Homebrew/gmap-gsnap/03.make:
Total annotation length: 80 + 3 separators
Saw 0 distinct divisions/chromosomes
Saw 3 distinct tags/types
No divs/chromosomes provided, so storing as IIT version 1
Writing IIT file header information...coordinates require 4 bytes each...done
Processing null division/chromosome...sorting...writing...done (3 intervals)
Writing IIT file footer information...done
PASS: iit.test
=========================================
2 of 4 tests failed
Please report to Thomas Wu <twu@gene.com>
=========================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

I've sent an email to the developer.

**Comment by nextgenusfs** [comment]
After communicating with developer, I was able to build the most recent version outside of home-brew on OS Sierra with a simple `./configure; make; make check; make install` - so seems to be a home-brew specific problem?  Anybody else have this problem?

**Comment by cmdcolin** [comment]
Maybe not helpful for diagnosing issue but I tried this on macOS Sierra and didn't see this

The "last 15 lines" of the 03.make file in /Users/ngs/Library/Logs/Homebrew/gmap-gsnap/ for my comp for example had same info as yours too, so you might have to dig into those log files in that folder more thoroughly to find the error

Maybe also notable but the current gmap-gsnap could be updated too. Current is may 01-16, latest is nov 07-16

**Comment by cmdcolin** [comment]
Full build from here

```
$ brew install GMAP-GSNAP
Updating Homebrew...
==> Installing gmap-gsnap from homebrew/science
==> Installing dependencies for homebrew/science/gmap-gsnap: htslib, samtools
==> Installing homebrew/science/gmap-gsnap dependency: htslib
==> Downloading https://github.com/samtools/htslib/archive/1.3.1.tar.gz
==> Downloading from https://codeload.github.com/samtools/htslib/tar.gz/1.3.1
######################################################################## 100.0%
==> make install prefix=/usr/local/Cellar/htslib/1.3.1
🍺  /usr/local/Cellar/htslib/1.3.1: 103 files, 6.5M, built in 27 seconds
==> Installing homebrew/science/gmap-gsnap dependency: samtools
==> Downloading https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/3666841/94dfe70a-0895-11e6-8856-070f81e24fde.bz2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIS
######################################################################## 100.0%
brew install java==> ./configure --with-htslib=/usr/local/opt/htslib

==> make
🍺  /usr/local/Cellar/samtools/1.3.1: 52 files, 924.9K, built in 29 seconds
==> Installing homebrew/science/gmap-gsnap
==> Downloading http://research-pub.gene.com/gmap/src/gmap-gsnap-2016-05-01.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/gmap-gsnap/2016-05-01
==> make
==> make check
==> make install
==> Caveats
You will need to either download or build indexed search databases.
See the readme file for how to do this:
  http://research-pub.gene.com/gmap/src/README

Databases will be installed to:
  /usr/local/Cellar/gmap-gsnap/2016-05-01/share
==> Summary
🍺  /usr/local/Cellar/gmap-gsnap/2016-05-01: 52 files, 105.6M, built in 4 minutes 1 second
```

**Comment by nextgenusfs** [comment]
Ok, well maybe something here, seems like the compiler is not finding perl for some reason, this is from the `config.log`
```
configure:4425: checking for a working version of perl
configure:4460: result: not found
```
When I compile outside of home-brew it obviously works okay.  I have 2 versions of perl installed, system perl, and then home brewed perl.  So my guess is it is looking in the wrong place?

**Comment by nextgenusfs** [comment]
So I've had this problem now with a few other formulas as well, I think that some external configure scripts are getting perl/python versions from elsewhere and not using the same method as `brew config`.  Thus if you have installed necessary perl modules in your brewed version of perl (`/usr/local/bin/perl`), they aren't available to system perl when building the formula.  

Any ideas on how I can change this?  `/usr/local/bin` is in front of `/usr/bin` in my $PATH.

Here's another example when trying to install `bcftools`, Note that the perl and python paths are different.
```
$ brew config
HOMEBREW_VERSION: 1.1.5-33-g8f85eb6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8f85eb64c4875fed514150dec755cb267a96df74
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abe487189e767d1ebf41b68c417e0d44791f92fe
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 24-core 64-bit arrandale
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /Users/ngs/miniconda2/bin/python => /Users/ngs/miniconda2/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111
macOS: 10.12.1-x86_64
Xcode: N/A
CLT: 8.1.0.0.1.1476494586
X11: N/A
```
But the make file log has this listed for brew configuration:
```
HOMEBREW_VERSION: 1.1.5-33-g8f85eb6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8f85eb64c4875fed514150dec755cb267a96df74
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abe487189e767d1ebf41b68c417e0d44791f92fe
Core tap last commit: 21 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 24-core 64-bit arrandale
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111
macOS: 10.12.1-x86_64
Xcode: N/A
CLT: 8.1.0.0.1.1476494586
X11: N/A
```

**Comment by nextgenusfs** [comment]
Okay, finally got an answer to this https://github.com/Homebrew/brew/issues/1810

So the formula needs to add `depends on perl => :build` option in order for the local version of Perl to be added to the filtered PATH.

**Comment by nextgenusfs** [comment]
While this works for me to add the `depends_on "perl" => :build` to the formula, I'm not sure this is what others would want?  As it will install brew perl if it is not installed, which may not be what some users want if system perl is what they are using.  So should I do a pull request for this formula and add the depends on perl?  OR is there another way to add as an option?

**Comment by sjackman** [comment]
I'm closing this issue as it's stale. Feel free however to respond to continue the discussion.
Can you elaborate why it's not finding `/usr/bin/perl`, when `/usr/bin` should always be in the `PATH`?

**Comment by nextgenusfs** [comment]
It certainly finds `/usr/bin/perl` but the build requires some perl module that are not installed by default.  So if you have local home-brew perl installation, i.e. `/usr/local/bin/perl` where you've installed your perl modules, the default build here won't find that version unless you include the `depends_on "perl" => :build` in the formula.  Does that make sense?

**Comment by sjackman** [comment]
Yep, that makes sense. Have you determined which Perl modules are needed? I'm confused why it passes CI on Mac (at least I think it does, see PR #5655) if `/usr/bin/perl` does not provide these modules.

**Comment by nextgenusfs** [comment]
It seems like in the `util` folder of gmap-gsnap are several perl scripts.
```
#find which modules are being used
for file in *.pl.in; do grep '^use' $file; done | sort | uniq
use File::Copy;	
use Getopt::Long;
use Getopt::Std;
use IO::File;
use warnings;
```
Now test to see which are missing in system Perl on Mac OS Sierra:
```
#first test functional home-brew perl
for i in File::Copy Getopt::Long Getopt::std IO::File; do echo $i; /usr/local/bin/perl -M$i -e 1; done
File::Copy
Getopt::Long
Getopt::std
IO::File

#now try with system Perl
for i in File::Copy Getopt::Long Getopt::std IO::File; do echo $i; /usr/bin/perl -M$i -e 1; done
File::Copy
Getopt::Long
Getopt::std
IO::File
Usage: DynaLoader::dl_find_symbol(libhandle, symbolname) at /Users/ngs/perl5/lib/perl5/darwin-thread-multi-2level/XSLoader.pm line 89.
Compilation failed in require at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/Handle.pm line 269.
BEGIN failed--compilation aborted at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/Handle.pm line 269.
Compilation failed in require at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/Seekable.pm line 101.
BEGIN failed--compilation aborted at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/Seekable.pm line 101.
Compilation failed in require at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/File.pm line 133.
BEGIN failed--compilation aborted at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/File.pm line 133.
Compilation failed in require.
BEGIN failed--compilation aborted.
```
Okay, so this suggests that `IO::File` is the Perl module causing problems (at least on my system).  So does it makes sense to add that as a dependency?

**Comment by sjackman** [comment]
The real question is why your host macOS `IO::File` is not working.

**Comment by sjackman** [comment]
```
❯❯❯ /usr/bin/perl -MIO::File -e1 && echo good
good
```

**Comment by nextgenusfs** [comment]
Yeah, I can fix that.  I just had made a point (I thought) to not mess with the system Perl on this particular machine, thus had installed home-brew perl.  So sounds like there isn't a problem then with this build, but more my Perl env.... I guess that is reassuring in some ways...
