### ISSUE TITLE
Transition to Qt 5

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#4595]
Updates are needed for formulae that depend on "qt" (Qt 4) due to the transition to Qt 5 (see Homebrew/homebrew-core#1705), and the imminent removal of the Qt 4 formula.

- [x] alglib: required
- [x] opencascade: required, gmsh (optional)
- [ ] qgis: required
- [x] populations: required
- [ ] biopp: recommended
- [ ] osgearth: recommended
- [x] paraview: recommended
- [ ] amos: optional
- [x] g2o: optional
- [ ] moose: optional
- [ ] opencv: optional
- [x] openimageio: optional
- [ ] root: optional
- [ ] mathgl: still has a qt4 option
- [ ] opencv3: still has a qt4 option
- [x] pcl: still has a qt4 option
- [x] vtk: still has a qt4 option

**Comment by iMichka** [comment]
FYI I have prepared a PR for pcl, which I can push as soon as vtk has been merged.

**Comment by iMichka** [comment]
For root (and root6), it seems they are stuck at qt3 anyway. Root6 has no qt option so this is not a problem.

I would propose to move root to homebrew/versions, and rename it as root5 (and remove the qt option). root6 could be renamed as root in homebrew science. Or maybe keep it as root6. Not sure how homebrew-science/tap_migrations.json should be written in that case.

**Comment by iMichka** [comment]
vtk, pcl and openimageio aro done.

**Comment by MikeMcQuaid** [comment]
> qgis: required

This looks like the last one with a hard dependency. It'll probably need boneyarded unfortunately if it gets to e.g. Christmas and there's no workaround here.

**Comment by MikeMcQuaid** [comment]
Looks possible but unsupported: https://htmlpreview.github.io/?https://raw.github.com/qgis/QGIS/master/doc/INSTALL.html#toc12

**Comment by ilovezfs** [comment]
Upstream has Qt 5 support: https://github.com/qgis/QGIS/blob/master/.travis.yml#L4

`$someone` "just" needs to do the work.

**Comment by ilovezfs** [comment]
@MikeMcQuaid sounds like it's time to move on then. I think people are using this tap now instead: https://github.com/OSGeo/homebrew-osgeo4mac. Note our formula is 1.8.0 and the tap's is 2.18
