### ISSUE TITLE
OpenCV 3.1 failed to build

### ISSUE THREAD

**Issue by vhad500** [Homebrew/homebrew-science#4598]
### Indicate troubleshooting steps taken

- [Yes ] Ran `brew update` and retried your prior step?
- [Yes ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [Yes ] Checked that a similar issue hasn't already been filed?
- [Yes ] Looked up the software bug tracker if reporting a build error?
- [Yes ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
`Last 15 lines from /Users/anhdo/Library/Logs/Homebrew/opencv3/02.make:
  /tmp/opencv3-20161115-77990-kie857/macbuild/modules/matlab/src/estimateAffine2D.cpp:49:68:
  error: no member named 'toSizeT' in 'cv::bridge::Bridge'

    size_t refineIters = inputs[6].empty() ? (size_t) 10 : inputs[6].toSizeT();
                                                           ~~~~~~~~~ ^
  2 errors generated.
make[2]: *** [modules/matlab/compile.proxy] Error 1
make[1]: *** [modules/matlab/CMakeFiles/opencv_matlab.dir/all] Error 2
make: *** [all] Error 2`
#### Brief summary of issue:
Tried to install OpenCV but failed to build
#### The complete command that you issued:
brew reinstall opencv3 --HEAD --with-python3 --with-ffmpeg --with-tbb --with-contrib

#### Gist with output of `brew doctor`:

#### Link output by `brew gist-logs <formula>`:

#### Output of `brew config`:

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
Hi @vhad500, unfortunately we don't provide support for `HEAD` builds. It's kind of expected that they will break from time to time. Do you know if this errors on a stable release?

**Comment by gjl991** [comment]
I met this problem also：
 error: ‘__gnu_cxx::__alloc_traits<std::allocator<cv::bridge::Bridge>
  >::value_type {aka class cv::bridge::Bridge}’ has no member named
  ‘toSizeT’
     size_t refineIters = inputs[6].empty() ? (size_t) 10 : inputs[6].toSizeT();

And my complete command is as follows:
sudo cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D BUILD_EXAMPLES=ON WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D FORCE_VTK=ON -D WITH_XINE=ON -D WITH_GDAL=ON ..

**Comment by BGR360** [comment]
I have the same issue. How can I disable installation of opencv's videoio via homebrew? I know how to do it if I were installing opencv manually, but not using homebrew

**Comment by BGR360** [comment]
Should I make an upstream issue?

**Comment by jonchang** [comment]
If this only happens on a `HEAD` build that might be the best course of action. What is the complete command you are running?

**Comment by BGR360** [comment]
I have alleviated the bug by excluding the problematic opencv modules

**Comment by vhad500** [comment]
The problem seems to be opencv3 incompatibility with Sierra. So I installed opencv2 instead and everything works fine.

**Comment by gjl991** [comment]
@vhad500, you are right. Now I installed opencv 3.0.0 on Ubuntu 16.04 LTS.
