### ISSUE TITLE
ceres-solver bottle uses old Eigen version

### ISSUE THREAD

**Issue by ayonsen** [Homebrew/homebrew-science#4603]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

#### Brief summary of issue:
This appears to be the same as issue 3195 and 3454, but now the latest version of Eigen is 3.3.0, and ceres-solver is built against 3.2.10.

#### The complete command that you issued:
brew install ceres-solver

**Comment by jonchang** [comment]
Hi @ayonsen, if you can open a pull request that increases the `revision` line this will help fix the issue. I'm currently on mobile and can't do it myself.

**Comment by ayonsen** [comment]
Hi @jonchang - sorry, didn't get your message until today. Is there anything you'd still like me to do? It looks like the issue has been resolved.

**Comment by jonchang** [comment]
Yup, looks like this is resolved.

**Comment by ilovezfs** [comment]
Now it's resolved. I just shipped https://github.com/Homebrew/homebrew-science/pull/4628.
