### ISSUE TITLE
brew install netcdf --with-fortran fails

### ISSUE THREAD

**Issue by sebastianbeyer** [Homebrew/homebrew-science#4639]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
brew install netcdf --with-fortran
==> Installing netcdf from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz
Already downloaded: /home/beyer/.cache/Homebrew/netcdf-4.3.3.1.tar.gz
==> ./configure --disable-dap-remote-tests --prefix=/home/beyer/.linuxbrew/Cellar/netcdf/4.3.3
==> make
==> make check
==> make install
==> Downloading https://github.com/Unidata/netcdf-cxx4/archive/v4.2.1.tar.gz
Already downloaded: /home/beyer/.cache/Homebrew/netcdf--cxx-4.2.1.tar.gz
==> ./configure --disable-dap-remote-tests --prefix=/home/beyer/.linuxbrew/Cellar/netcdf/4.3.3
==> make
==> make check
==> make install
==> Downloading ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.2.tar.gz
Already downloaded: /home/beyer/.cache/Homebrew/netcdf--fortran-4.4.2.tar.gz
==> ./configure --disable-dap-remote-tests --prefix=/home/beyer/.linuxbrew/Cellar/netcdf/4.3.3
Last 15 lines from /home/beyer/.cache/Homebrew/Logs/netcdf/09.configure:
checking for size_t... (cached) yes
checking for off_t... yes
checking for ssize_t... yes
checking for ptrdiff_t... yes
checking for uchar... no
checking for longlong... no
checking whether char is unsigned... no
checking size of short... 0
checking size of int... 0
checking size of long... 0
checking size of float... 0
checking size of double... 0
checking size of off_t... configure: error: in `/tmp/netcdf--fortran-20161124-15650-kl4u6u/netcdf-fortran-4.4.2':
configure: error: cannot compute sizeof (off_t)
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
netcdf failed to find hdf5 on Linux https://github.com/Homebrew/homebrew-science/issues/2235
netcdf fortran fails configure stage with brew installed gfortran https://github.com/Homebrew/homebrew-science/issues/4316
NetCDF fails to link using Homebrew-installed GCC https://github.com/Homebrew/homebrew-science/issues/3536
CLUSTER2015 - beyer@login01:~> ls /tmp/netcdf--fortran-20161124-15650-kl4u6u/netcdf-fortran-4.4.2
ls: cannot access /tmp/netcdf--fortran-20161124-15650-kl4u6u/netcdf-fortran-4.4.2: No such file or directory
```

#### Brief summary of issue:
I can `brew install netcdf` with with fortran it fails with `error: cannot compute sizeof (off_t)`

#### The complete command that you issued:
`brew install netcdf --with-fortran`

#### Gist with output of `brew doctor`:
https://gist.github.com/sebastianbeyer/b093d66cb786e1703808535c3468dba5

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/anonymous/33a8d756ef01d68a64d108ef609e2d43

#### Output of `brew config`:
```
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 15ab5de6dc4434c8cc92cf7a78cae5eacff5583c
Last commit: 6 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 30ad1920ddc304e1558e92541afaa73c2e117a9c
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /home/beyer/.linuxbrew
HOMEBREW_REPOSITORY: /home/beyer/.linuxbrew
HOMEBREW_CELLAR: /home/beyer/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 48-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648 => /home/beyer/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 1.7.12.4 => /usr/bin/X11/git
Perl: /home/beyer/.linuxbrew/bin/perl => /home/beyer/.linuxbrew/Cellar/perl/5.24.0_2/bin/perl
Python: /home/beyer/.linuxbrew/bin/python => /home/beyer/.linuxbrew/Cellar/python/2.7.12_3/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_45
Kernel: Linux 3.0.101-0.47.52-default x86_64 GNU/Linux
OS: SUSE Linux Enterprise Server 11 (x86_64)
Codename: n/a
OS glibc: 2.11
OS gcc: 4.3.4
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A
```

**Comment by sebastianbeyer** [comment]
okai, I have the same error (`cannot compute sizeof (off_t)`), when compiling netcdf manually...

**Comment by sebastianbeyer** [comment]
I found this: https://github.com/Homebrew/homebrew-science/issues/2521#issuecomment-121851582
seems like it is the same then?

**Comment by nbren12** [comment]
I am getting this same error on Mac OS. Here is my gist log https://gist.github.com/2be5525b9403707234d95aa79783205b.

**Comment by nbren12** [comment]
I am not sure if this is reproducible, but I got it to work when I ran `brew install hdf5 --with-fortran --c++11 ` before `brew install netcdf --with-fortran`. Maybe something is wrong with how homebrew is compiling hdf5.

**Comment by sebastianbeyer** [comment]
@nbren12 that did not work in my case...

**Comment by nbren12** [comment]
fwiw this is the output of `brew gist-logs netcdf`
[gist](https://gist.github.com/3976ba08d09baf738bb56b0a95bad5a9
)

And this my `brew gist-logs hdf5`:
[gist](https://gist.github.com/de29e697b0a570cb34c443767c532c08)

Maybe that will help. The main differences I see are the compilers. I am using gcc-6 for fortran and clang for c. Sorry, I couldn't track down specifically how i fixed it. It just worked all of a sudden.

**Comment by iMichka** [comment]
Hi. Thanks for all your investigations.

The error was a ./configure error. We just switched the setup to cmake, see #4932.
With this the `--with-fortran` flag is working again. I do believe that this problem is fixed for us, so I will close this issue. If there are still problems, please open a new bug. Thanks.
