### ISSUE TITLE
Java support for Octave without Apple's Legacy Java 6

### ISSUE THREAD

**Issue by tobiasherzke** [Homebrew/homebrew-science#4643]
This is a low-priority feature request.

### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, **brew doctor is happy**
- [x] Checked that a similar issue hasn't already been filed? **There is a related issue. I reference it below**
- [X] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

"No Java runtime present, requesting install"

#### Brief summary of issue:

When building Octave with Java support, with Oracle JDK 1.8 installed, the produced binaries will still request the installation of the legacy Java 6 from Apple. 

This will normally also prevent the installation of Octave with Java support through homebrew, as the compiled binary is executed during the "make check" phase, and it exits with non-zero there.

This has been discussed in issue #1899. The solution reached there is to not compile octave with java support by default.

The fact that octave, although compiled with JDK 1.8, requests installation of Legacy Java 6 upon startup, is probably caused by this Java bug: https://bugs.openjdk.java.net/browse/JDK-7131356 .
The same bug was also encountered by rJava: https://github.com/s-u/rJava/issues/37 . The bug seems to have been fixed in OpenJDK source only recently. Current Oracle JDK 1.8 (112) seems to be still affected.

My feature request here is to enable compilation of octave with Java support with Java 9 prereleases from https://jdk9.java.net/download . This does not work out of the box and needs attention:
When I tried compiling octave with homebrew with Java 9, the java_version detection code in configure.ac and configure of the octave source code needed adaptation. I simply hardcoded that with java_version=1.9.0_0 in the configure script, but a more intelligent solution would be required for homebrew in general. Furthermore, although the compiled octave binary would not request the installation of Legacy Java on startup, it was still not usable because it crashed with segfault as soon as a java function (javaMethod, javaObject,...) was used inside octave.

This is low priority, because users still have the option to install Legacy Java 6. Octave Users are then also limited to use only Java 6: Although compiled with Java 1.8, octave won't run until Legacy Java 6 is installed, and then it would use Java 6 and not Java 1.8.

For anyone confused by the Java version numbers in here (I know I am): Java Version 1.X is sometimes just called Version X and sometimes 1.X. This way, 1.8 is a later version than 6. 6 is unmaintained and contains errors.

#### The complete command that you issued:

    brew install --debug --build-from-source --with-java octave

**Comment by Cnd-North** [comment]
This was great!! Thanks so much!

**Comment by iMichka** [comment]
@ilovezfs This may interest you, as I saw that somebody is asking about this in homebrew-core.

I'll close this issue in homebrew-science, as it now lies in the hands of homebrew-core. Just add me to the discussion in core if there is a new issue added :)

**Comment by schoeps** [comment]
@tobiasherzke Can you try this https://gist.github.com/schoeps/2e81683de2f26065883383dec3b549aa, please? Should work with java 1.9.

**Comment by tobiasherzke** [comment]
@schoeps https://gist.github.com/schoeps/2e81683de2f26065883383dec3b549aa works fine with jdk 9, thank you!
