### ISSUE TITLE
update PEAR

### ISSUE THREAD

**Issue by chrisgulvik** [Homebrew/homebrew-science#4644]
Could the formula for PEAR be updated to the latest version?

A new option `-k, --keep-original` resolves a serious bug in previous versions that had the R2 sequences and their associated Phred scores incorrectly reversed when they weren't paired.

http://sco.h-its.org/exelixis/web/software/pear/files/pear-0.9.10.tar.gz
sha256:  ebb0a1a26300b4d54e6a470b0dd17c364aedcf8d4bfab1106649a2d502a76203

**Comment by jonchang** [comment]
Fixed by #4648.
