### ISSUE TITLE
hdf5 --with-mpi failed to build on OS 10.11.6

### ISSUE THREAD

**Issue by nbren12** [Homebrew/homebrew-science#4652]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [NA] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

hdf5 fails to configure with mpi. It complains that

```
checking for gcc... /usr/local/bin/mpicc
checking whether the C compiler works... no
configure: error: in `/private/tmp/hdf5-20161128-9971-9ijs2q/hdf5-1.8.17':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Maybe this fails because mpicc is calling clang rather than gcc? 

#### The complete command that you issued:

brew install hdf5 --with-mpi

#### Gist with output of `brew doctor`:

[https://gist.github.com/bc29646673d6ad67ef3ee20c74efaf1b](https://gist.github.com/bc29646673d6ad67ef3ee20c74efaf1b)

#### Link output by `brew gist-logs <formula>`:

[https://gist.github.com/bc29646673d6ad67ef3ee20c74efaf1b](https://gist.github.com/bc29646673d6ad67ef3ee20c74efaf1b)

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.1.1-95-g84b3c57
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 84b3c57086d201ea07070a1b4d1b0520e2d7134a
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 158decbf79ffbd01893cb78ee6756680a977a9fc
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_51, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

**Comment by ilovezfs** [comment]
I believe this is the same behavior I described here: https://github.com/Homebrew/brew/pull/1130#issuecomment-261881626

Do you have gcc installed?

**Comment by nbren12** [comment]
I do, but I think hdf5 is trying to compile with clang

**Comment by ilovezfs** [comment]
what's the output of
```
xcode-select -p
```

**Comment by nbren12** [comment]
It gives `/Library/Developer/CommandLineTools`

**Comment by ilovezfs** [comment]
```
sudo xcode-select -r
```

then try the build again

**Comment by nbren12** [comment]
ha! it works. it successfully configured and is now compiling. thanks so much!

 So xcode-select needs to have the "/Applications/Xcode.app/Contents/Developer" directory selected?

**Comment by ilovezfs** [comment]
@nbren12 yeah it should no longer be an issue after the 8.2 CLT ships for El Capitan or you upgrade to Sierra. Incidentally, did it end up actually using gcc-6?

**Comment by nbren12** [comment]
No. I stuck with clang, since it successfully compiled hdf5.

However, now netcdf-fortran is now complaining. Maybe I should open a new
issue.

**Comment by ilovezfs** [comment]
How did you stick with clang? Pass --cc= or an envvar or something else?

**Comment by nbren12** [comment]
I ran  "brew install hdf5 --with-mpi", so I assumed that it compiled
against clang? I could be mistaken.

**Comment by ilovezfs** [comment]
Mind posting the link from running the following?

brew gist-logs hdf5

**Comment by nbren12** [comment]
Sure thing. Here it is: [
https://gist.github.com/anonymous/14f11808eea224c3a7122116b41d3e70](https://gist.github.com/anonymous/14f11808eea224c3a7122116b41d3e70)

**Comment by ilovezfs** [comment]
Cool thanks. Yes please open a new issue for the problem you're now seeing.

**Comment by iMichka** [comment]
We provide now hdf5 1.10.0-patch1 now. Our CI built it `--with-mpi` on 10.12, 10.11 and 10.10 with success. Please open a new issue if you still encounter problems.
