### ISSUE TITLE
Octave 4.2.0 using 100% CPU

### ISSUE THREAD

**Issue by robsonpeixoto** [Homebrew/homebrew-science#4658]
Sometimes the octave are using 100% CPU without run any script.
And I always need to use `Force Quit`to close the octave.

Any idea how to solve it?

I installed the octave using:
```
❯ brew install gnuplot --with-qt5 --with-aquaterm octave --with-qt5
```

And I created the lancher app using this doc: http://wiki.octave.org/Octave_for_MacOS_X#Create_a_launcher_app_with_AppleScript

**Comment by jonchang** [comment]
Hi @robsonpeixoto, I'm not sure that this is a bug with Homebrew. Please consider filing a bug with the Octave project.
