### ISSUE TITLE
CMake files of vtk and insighttoolkit bottles reference wrong Xcode SDK

### ISSUE THREAD

**Issue by dakcarto** [Homebrew/homebrew-science#4662]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
   (though had to revert homebrew-science due to #4660)
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

Generated CMake files in the following bottles:
* [insighttoolkit-4.10.1_1.el_capitan.bottle.tar.gz](https://homebrew.bintray.com/bottles-science/insighttoolkit-4.10.1_1.el_capitan.bottle.tar.gz)
* [vtk-7.0.0_6.el_capitan.bottle.tar.gz](https://homebrew.bintray.com/bottles-science/vtk-7.0.0_6.el_capitan.bottle.tar.gz)

reference a wrong macOS SDK (newer) in Xcode than the bottle target OS. The CMake files in question, those generated for _other_ software to build against the packages, are located in `prefix/lib/cmake`, e.g. `/Users/larrys/Library/Caches/Homebrew/insighttoolkit/4.10.1_1/lib/cmake/ITK-4.10/Modules/*.cmake`

Specifically, these frameworks present the issue:

* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/**OpenCL.framework**
* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/**Python.framework**/Versions/2.7/include/python2.7

The latter is present in CMake files for both packages, though in `insighttoolkit` it appears to be copied over from `vtk`'s CMake files.

Doing a find/replace for `MacOSX10.12.sdk`/`MacOSX10.11.sdk` in the CMake files allow for other software to built against the packages' CMake setup.

Seems like it can be overcome with the `"-DCMAKE_FRAMEWORK_PATH=#{MacOS.sdk_path}"` CMake option. However, I do not have Xcode 8 installed, so could not test this (no MacOSX10.12.sdk, in addition to MacOSX10.11.sdk.)

I also wonder if it is not an issue with `brew-test-bot`'s environment, selecting the latest Xcode SDK, instead of the target OS version.

While this may seem like only a generated CMake file error, I believe the packages themselves are also being built against the incorrect SDK (though this is hard to determine via `otool`, since the install names and versions are the same across SDKs).  

#### The complete command that you issued:

`brew install -dv osgeo/osgeo4mac/orfeo5` (though this is unrelated to the issue)

#### Gist with output of `brew doctor`:

```
Warning: Your Xcode (7.3.1) is outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store.
```

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4709f466b7d8ef16ef831a449188bf5ddaf206a
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.7.0_79
macOS: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

**Comment by jonchang** [comment]
Hi @dakcarto, thanks for opening such a detailed issue. I looked into it and I think the issue can be resolved if you update Xcode to the latest version. I tested on an El Capitan machine with Xcode 8 and the SDK path points to `MacOSX10.12.sdk` even though El Capitan itself is 10.11.

If for some reason you need to use an older version of Xcode you can build these from source with `brew install -s vtk` or similar but please note that this is not supported by Homebrew.

**Comment by dakcarto** [comment]
> Hi @dakcarto, thanks for opening such a detailed issue. I looked into it and I think the issue can be resolved if you update Xcode to the latest version. I tested on an El Capitan machine with Xcode 8 and the SDK path points to MacOSX10.12.sdk even though El Capitan itself is 10.11.

Hi. Hmm. See your point there. Still, doesn't seem like the`MacOSX10.12.sdk` _should_ be the referenced SDK. I'd call that a bug; not sure where it occurs, though.

> If for some reason you need to use an older version of Xcode you can build these from source with brew install -s vtk or similar but please note that using an old Xcode is not supported by Homebrew.

The main issue is that a bottle for 10.11 is being built against an incorrect SDK. Using an older Xcode, and building from source will work for me (if I have an extra hour 😉); but, this really just masks some other issue that is causing the wrong SDK to be selected.

Could even be CMake that is incorrectly selecting the SDK.

**Comment by jonchang** [comment]
> Hi. Hmm. See your point there. Still, doesn't seem like the MacOSX10.12.sdk should be the referenced SDK. I'd call that a bug; not sure where it occurs, though.

To reduce our support burden, we build bottles using the latest version of Xcode that is available on supported platforms (Yosemite, El Capitan, and Sierra). Since Xcode 8 is available on El Capitan this correctly points to the `MacOSX10.12.sdk`. On Yosemite, which only supports Xcode 7, this instead points to the `MacOSX10.11.sdk` as expected.

The "bug", then, results from either Homebrew or Apple policy, depending on your point of view. I do not think that we will change the way we bottle formulae and I can't speak for what Apple might do.

**Comment by dakcarto** [comment]
> To reduce our support burden, we build bottles using the latest version of Xcode that is available on supported platforms (Yosemite, El Capitan, and Sierra). Since Xcode 8 is available on El Capitan this correctly points to the MacOSX10.12.sdk. On Yosemite, which only supports Xcode 7, this instead points to the MacOSX10.11.sdk as expected.

Hmm. Not seeing your point here. Why would the default referenced SDK of a _higher_ version than the OS's or the target's be consider correct or expected?

**Comment by dakcarto** [comment]
@jonchang Ok, never mind, my mistake. There is _no MacOSX10.11.sdk_ in Xcode >= 8.0 (even though 10.11.5 is the minimum OS). So, yeah, I definitely see your point now. Obviously, I'm a little late to the party. Thanks!
