### ISSUE TITLE
Upgrade to BLAST+ 2.5.0?

### ISSUE THREAD

**Issue by nextgenusfs** [Homebrew/homebrew-science#4670]
There appears to be two major problems on some systems with BLAST+ 2.4.0, one is that tblastn core-dumps if run in multi-threaded mode.  Here are release notes for 2.5.0: https://www.ncbi.nlm.nih.gov/books/NBK131777/

I tried to just edit the link to the new version in the formula put couldn't get it to build.  

Alternatively, is there a way to install the older version 2.3.0 from home-brew?

**Comment by iMichka** [comment]
Just gave this a try; got the following error during the install step with 2.5.0:

>==> make install
if test -d /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/bin/gbench; then \
	    /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j install-gbench; \
	else \
	    /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j install-toolkit; \
	fi
/bin/rm -rf /usr/local/Cellar/blast/2.5.0/include/ncbi-tools++
/usr/bin/install -c -d /usr/local/Cellar/blast/2.5.0/bin /usr/local/Cellar/blast/2.5.0/libexec /usr/local/Cellar/blast/2.5.0/include/ncbi-tools++
/usr/bin/install -c /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/bin/* /usr/local/Cellar/blast/2.5.0/bin
/usr/bin/install -c -m 644 /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/lib/*.* /usr/local/Cellar/blast/2.5.0/libexec
if test -d /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/lib/ncbi; then \
	    cp -pPR /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/lib/ncbi /usr/local/Cellar/blast/2.5.0/libexec/; \
	fi
rm -f /usr/local/Cellar/blast/2.5.0/libexec/lib*-static.a
cd /usr/local/Cellar/blast/2.5.0/libexec  && \
	    for x in *.a; do \
	        /bin/ln -s "$x" "`/usr/bin/basename \"$x\" .a`-static.a"; \
	    done
cd /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/include && find * -name CVS -prune -o -print |\
            cpio -pd /usr/local/Cellar/blast/2.5.0/include/ncbi-tools++
51112 blocks
/usr/bin/install -c -m 644 /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/inc/* /usr/local/Cellar/blast/2.5.0/include/ncbi-tools++
install: /private/tmp/blast-20161205-18326-1yiany2/ncbi-blast-2.5.0+-src/c++/ReleaseMT/inc/common: Inappropriate file type or format
make[1]: *** [install-toolkit] Error 71
make: *** [install] Error 2

**Comment by iMichka** [comment]
Blast 2.5.0 was merged. Please test :)

**Comment by nextgenusfs** [comment]
Thanks!  Seems to be working fine for me on El Capitan and OS Sierra.

**Comment by iMichka** [comment]
@nextgenusfs don't forget to close this if this is OK for you :)

**Comment by nextgenusfs** [comment]
ah, sorry.  yes working for me.  Thanks!

**Comment by storer1017** [comment]
@iMichka What do you mean that Blast 2.5.0 was merged? I'm getting this same error, and I don't know how to fix it, but I don't see the fix on here!

**Comment by iMichka** [comment]
@storer1017 I mean that we updated blast to version 2.5.0, which should have fixed the problem. If this is not the case, please open a new issue, and fill out the issue template so that we can help you.

**Comment by ponomarevsy** [comment]
Hello! I am using RHEL 7.3 and the latest release of RMBlast, ncbi-blast-2.6.0+-src.tar.gz, with patch isb-2.6.0+-changes-vers2.patch.gz as described here: 
http://www.repeatmasker.org/RMBlast.html and I am getting similar error "make[1]: *** [install-toolkit] Error 1". How can I fix it? Thanks!

» make install
if test -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then \
    make  install-gbench; \
else \
    make  install-toolkit; \
fi
make[1]: Entering directory `/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++'
/bin/rm -rf /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++
/bin/install -c -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/bin /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++
/bin/install -c /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/bin
/bin/install -c -m 644 /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/*.* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib
if test -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi; then \
    cp -pPR /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib/; \
fi
rm -f /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib/lib*-static.a
cd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib  && \
    for x in *.a; do \
        /bin/ln -s "$x" "`/bin/basename \"$x\" .a`-static.a"; \
    done
cd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/include && find * -name CVS -prune -o -print |\
            cpio -pd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++
51193 blocks
/bin/install -c -m 644 /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++
/bin/install: omitting directory ‘/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/common’
make[1]: *** [install-toolkit] Error 1
make[1]: Leaving directory `/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++'
make: *** [install] Error 2

**Comment by iMichka** [comment]
Please do not hijack unrelated old issues and open a new one.

We provide a working blast 2.6.0 version. If that special patch you are mentioning is not working, I am not sure we can help you, but you should ask upstream to help you.

**Comment by ponomarevsy** [comment]
Thanks for your feedback, Michka. Where can I submit this request (I was google for RMBlast and that’s how I came across that discussion)?

Sincerely Yours,

Sergei Y. Ponomarev (NIH/NIAID) [C], PhD,  Contractor
Senior Systems Administrator - Linux and High Performance Computing Team
SRA International, Inc., A CSRA Company
Operations and Engineering Branch
Email: sergei.ponomarev@nih.gov<mailto:sergei.ponomarev@nih.gov>
Work phone: 301-761-6731, Mobile: 301-502-1673
5601 Fishers Lane, 6A66, Rockville, MD 20852
NIAID, National Institutes of Health, DHHS

Disclaimer:
The information in this e-mail and any of its attachments is confidential and may contain sensitive information.  It should not be used by anyone who is not the original intended recipient.  If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage devices.  National Institute of Allergy and Infectious Diseases shall not accept liability for any statements made that are sender’s own and not expressly made on behalf of the NIAID by one of its representatives.

**Comment by iMichka** [comment]
@ponomarevsy Please don't delete message and keep the discussion on GitHub, thanks. 

We have a documentation on how to open a pull request which you can follow.
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

With this you should be able to modify the blast.rb file and add a patch.
If not, you can still open a new issue, I can have a look too but probably not in the next days.
