### ISSUE TITLE
Failed to download v3.1.0/protobuf-cpp-3.1.0.tar.gz.  Status=28;"Timeout   was reached"

### ISSUE THREAD

**Issue by 03128crz** [Homebrew/homebrew-science#4690]
cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv3/HEAD -DCMAKE_BUIL
Last 15 lines from /Users/james_cai/Library/Logs/Homebrew/opencv3/01.cmake:

CMake Error at cmake/OpenCVUtils.cmake:1025 (message):
  Failed to download v3.1.0/protobuf-cpp-3.1.0.tar.gz.  Status=28;"Timeout
  was reached"
Call Stack (most recent call first):
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  opencv_contrib/modules/dnn/CMakeLists.txt:35 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/opencv3-20161208-81025-a6p71w/macbuild/CMakeFiles/CMakeOutput.log".
See also "/tmp/opencv3-20161208-81025-a6p71w/macbuild/CMakeFiles/CMakeError.log".

**Comment by blueclowd** [comment]
I have the same problem,

use **cmake -DBUILD_opencv_dnn=OFF** if you don't actually need the module

**Comment by Schultzer** [comment]
Are you installing against `--head` ?
else #4759

**Comment by wyx006** [comment]
i download the protobuf-cpp-3.1.0.tar.gz. but i do not know put it to which dir.

**Comment by tornadomeet** [comment]
any update? same problem here, even with ```cmake -DBUILD_opencv_dnn=OFF```, it still do ```-- Downloading v3.1.0/protobuf-cpp-3.1.0.tar.gz...```

**Comment by jinfagang** [comment]
Same issue, anyone had figured this out?

**Comment by ilovezfs** [comment]
I suggest reporting this to upstream since it's about a HEAD spec, which we don't really support in any way.

**Comment by jinfagang** [comment]
Solve it, directly build it from source code, works fine.

**Comment by SonofFaker** [comment]
@jinfagang Can you explain more specifically?

**Comment by blueclowd** [comment]
@jinfagang Can you share more details?

**Comment by blueclowd** [comment]
@wyx006 protobuf-cpp-3.1.0.tar.gz should be under ../opencv_contrib/modules/dnn/.downloads/bd5e3eed635a8d32e2b99658633815ef/

**Comment by jinfagang** [comment]
@blueclowd I am not install opencv from brew anymore, just download macOS platform source code and build it, it should work properly.

**Comment by alexshires** [comment]
same issue - any suggestions?

**Comment by A7medAbdeldaim** [comment]
@blueclowd This solution is working with me without any problem but it is 
-D BUILD_opencv_dnn=OFF
 not 
-DBUILD_opencv_dnn=OFF

**Comment by aeoleader** [comment]
-DBUILD_opencv_dnn=OFF works on ubuntu 16.04

**Comment by desperinter** [comment]
actually we have to put protobuf-cpp-3.1.0.tar.gz into 
../opencv_contrib/modules/dnn/.downloads/bd5e3eed635a8d32e2b99658633815ef/v3.1.0/ 
instead of @jinfagang 's directory
../opencv_contrib/modules/dnn/.downloads/bd5e3eed635a8d32e2b99658633815ef/
and the problem will be solved. But another problem will occur:
CMake Error at /media/tungps/diskb/opencv3.2/opencv-3.2.0/cmake/OpenCVUtils.cmake:1047 (message):
  Failed to download vgg_generated_48.i.  Status=1;"Unsupported protocol"

**Comment by jinfagang** [comment]
@desperinter  Not bother, just build from source code, no problem, I tried.

**Comment by desperinter** [comment]
@jinfagang As I know this ton of issues occurs when cmake can not download these 3rd party files corresponding to opencv extra modules. I am working in my company and I guess some connections has been block by administrators. So there are only 2 ways to fix this:
- Try building opencv+extra with a fully connection as @jinfagang has
- Manually download many files, and put each files to the right directory. It will take a lot of time and I give up

**Comment by JindongJiang** [comment]
For homebrew user, you could simply download [protobuf-cpp-3.1.0.tar.gz](https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-cpp-3.1.0.tar.gz) and store copy it to `/Users/Jd/Library/Caches/Homebrew/` before brew (re)install opencv3.

**Comment by LiangKim** [comment]
@JindongJiang 
it doesn't work.

**Comment by k-lam** [comment]
closed? I does'n work!
