### ISSUE TITLE
using openmp by default in my formula

### ISSUE THREAD

**Issue by lock042** [Homebrew/homebrew-science#4700]
I'm the maintainer of siril formula in homebrew/science.
Yet to use siril with openmp, user need to install it with
`brew install siril --with-openmp`
But I have to admit I would prefer the opposite behavior:
`brew install siril`
--> install siril with openmp
`brew install siril --without-openmp`
--> install siril without openmp

Is it possible to do it ?

**Comment by Moisan** [comment]
Look at [this section](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#specifying-other-formulae-as-dependencies) of the Formula guide. You probably want `:recommended` instead of `:optional` in the `openmp` dependency.

**Comment by ilovezfs** [comment]
You'll want to look at these:
```
Josephs-MacBook-Pro:homebrew-science joe$ ag openmp|grep without|grep opt
einspline.rb:17:  option "without-openmp", "Disable OpenMP"
fasttree.rb:19:  option "without-openmp", "Disable multithreading support"
libbi.rb:40:  option "without-openmp", "Disable OpenMP"
nest.rb:23:  option "without-openmp", "Build without OpenMP support."
```

**Comment by lock042** [comment]
Thanks but it's difficult to understand. Because by default siril is compiled with clang in homebrew, but clang cannot compile with openmp option.
So, if I only replace
`  option "with-openmp", "Enable OpenMP multithreading"`
by
`  option "without-openmp", "Disable OpenMP"`
as suggested in einspline.rb, it would work ? (I have no Mac to test it except by pulling a request)

**Comment by ilovezfs** [comment]
yeah because it also has ` needs :openmp if build.with? "openmp"`

**Comment by lock042** [comment]
OK thanks. I pulled a request.
Hope it is ok

**Comment by lock042** [comment]
Thanks a lot !!!
