### ISSUE TITLE
Update opencv3 to OpenCV 3.2, it has been released today

### ISSUE THREAD

**Issue by ysolovyov** [Homebrew/homebrew-science#4758]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by reneklacan** [comment]
There's also https://github.com/Homebrew/homebrew-science/pull/4776
