### ISSUE TITLE
KmerStreamEstimate.py  depends_on "scipy" => :python

### ISSUE THREAD

**Issue by chrisgulvik** [Homebrew/homebrew-science#4778]
### Bug reports / build errors:
Traceback (most recent call last):
  File "~/.linuxbrew/bin/KmerStreamEstimate.py", line 4, in <module>
    from scipy.optimize import brentq
ImportError: No module named scipy.optimize

#### Brief summary of issue:
-- python module scipy dependency absent in formula
-- proper installation test is lacking https://github.com/Homebrew/homebrew-science/blob/master/kmerstream.rb#L29

#### The complete command that you issued:
`KmerStreamEstimate.py --help`
`echo $?` #returns 1

## Suggested quick fix:
Just below L18  `needs :openmp` in https://github.com/Homebrew/homebrew-science/blob/master/kmerstream.rb#L18, needs to include `depends_on "scipy" => :python`

**Comment by jonchang** [comment]
@chrisgulvik please open a pull request for this change. You can just use `depends_on "scipy"` since https://github.com/Homebrew/homebrew-python has the `scipy` bottle.

**Comment by iMichka** [comment]
I opened a PR for that: #5125

**Comment by iMichka** [comment]
I added the missing dependency. There are no Linux bottles for the moment as the scripy installation is currently broken, but the mac bottles are still valid.
