### ISSUE TITLE
Edirect ftp download error

### ISSUE THREAD

**Issue by joshualoving** [Homebrew/homebrew-science#4780]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:

==> Installing edirect from homebrew/science
==> Downloading ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/2016-08-09/edirect.tar.gz

curl: (9) Server denied you to change to the given directory
Error: Failed to download resource "edirect"
Download failed: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/versions/2016-08-09/edirect.tar.gz

#### Brief summary of issue:

edirect will not download. The ftp link appears to be broken. 

#### The complete command that you issued:
brew install edirect

**Comment by cmdcolin** [comment]
Looks like the whole directory naming system on their ftp server changed leading to download failed.

**Comment by joshualoving** [comment]
Yeah, using brew edit to replace the URL and updating the SHA hash to match the new file worked.

**Comment by jonchang** [comment]
Hi @joshualoving, thanks for figuring this out! Could you please open a pull request to update the url and hash so that other users can benefit from your help?

**Comment by joshualoving** [comment]
I created a fork and tried to create a pull request, but I'm having trouble figuring out what information to give. This is my commit: 

https://github.com/joshualoving/homebrew-science/commit/d7aa291537c205a89b45e2c8cb49c279644d9165

**Comment by iMichka** [comment]
Hi. Looks almost good. Where exactly are you stuck?
There is a tutorial on how to open a pull request here: http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

Some comments:
- You should make your changes on a separate branch. This will allow you to open multiple pull requests, and is good practice.
- The title (first line of commit message) should be: `edirect 6.00` (see the docs)

Hope that helps. If you have any questions don't hesitate to ask.

**Comment by iMichka** [comment]
Meanwhile, somebody else opened a pull request, with an even newer version: #4868. I merged that in instead. @joshualoving Thanks for your contribution.
