### ISSUE TITLE
update homebrew-science/armadillo.rb to Armadillo 7.600.2

### ISSUE THREAD

**Issue by conradsnicta** [Homebrew/homebrew-science#4782]
@ilovezfs @dpo  - I recommend updating armadillo.rb to Armadillo 7.600.2. 

The updated version fixes a memory leak when compiling in C++11/C++14 mode.

**Comment by jonchang** [comment]
Feel free to open a pull request for this update. You'll need to update the `sha256` and `url` fields assuming nothing else has changed.

**Comment by conradsnicta** [comment]
@jonchang - pull request: https://github.com/Homebrew/homebrew-science/pull/4801
