### ISSUE TITLE
octave failed to build on 10.12.2

### ISSUE THREAD

**Issue by drdv** [Homebrew/homebrew-science#4784]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

brew install octave
==> Installing octave from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
Error: wrong number of arguments (1 for 0)
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:331:in `set_cpu_flags'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/shared.rb:254:in `fortran'
/usr/local/Homebrew/Library/Homebrew/requirements/fortran_requirement.rb:8:in `block in <class:FortranRequirement>'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:77:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:77:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:55:in `call'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:55:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:88:in `each'
/usr/local/Homebrew/Library/Homebrew/build.rb:88:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'

#### Gist with output of `brew doctor`:

Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:

Error: No logs.

#### Output of `brew config`:

HOMEBREW_VERSION: 1.1.5-90-g760a4601a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 760a4601aa07e993c0ccb9ef01257da7361016e1
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ec905acb98521bb73f71c972b0ebdec21d93fe2
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

**Comment by jonchang** [comment]
This looks like Homebrew/brew#1761 so it should be fixed by running `brew update`. Feel free to re-open or file a new issue if that isn't the case.
