### ISSUE TITLE
qrupdate fails to install from source on 10.9

### ISSUE THREAD

**Issue by berquist** [Homebrew/homebrew-science#4785]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
==> Installing qrupdate from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
Error: wrong number of arguments (1 for 0)
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:331:in `set_cpu_flags'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/shared.rb:254:in `fortran'
/usr/local/Homebrew/Library/Homebrew/requirements/fortran_requirement.rb:8:in `block in <class:FortranRequirement>'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:77:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:77:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:55:in `call'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:55:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:88:in `each'
/usr/local/Homebrew/Library/Homebrew/build.rb:88:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

#### Brief summary of issue:

The command fails immediately, and it pretty clearly is related to Homebrew (maybe core, not science). I don't recall having issues with Homebrew-provided gfortran in the past.

I've left the `brew doctor` box unchecked because 1. the unlinked dylibs are related to `aspell`, and 2. I'm on Mavericks and am not knowledgeable enough in Ruby to submit a PR.

Using git hashes:
- `brew`: ad593cf42cfcd4bb795b457d6787cf89382017d8
- `homebrew-core`': 8ddf7ca53dac04ee1a0f0b4859c145d118d5368d
- `homebrew-science`: b0350e62de1deb3ccf20face10e11c1df1bd4820

#### The complete command that you issued:

```
brew install qrupdate
```

#### Gist with output of `brew doctor`:

https://gist.github.com/berquist/a84607a4bdd2c6ea34ac2371d7d1e74f

#### Link output by `brew gist-logs <formula>`:

```
Error: No logs.
```

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.1.5-111-gad593cf42
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad593cf42cfcd4bb795b457d6787cf89382017d8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ddf7ca53dac04ee1a0f0b4859c145d118d5368d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
Clang: 6.0 build 600
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25, 1.6.0_65-b14-462
macOS: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
X11: 2.7.11 => /opt/X11
```

**Comment by jonchang** [comment]
This looks like Homebrew/brew#1761 so it should be fixed by running `brew update`. Note that we don't officially support 10.9 so it may be best to start planning to migrate to 10.12 as building from source can lead to a lot of problems.

**Comment by berquist** [comment]
It is fixed, thanks.
