### ISSUE TITLE
openimageio bottles broken since last boost upgrade: upgrade to 1.7.9?

### ISSUE THREAD

**Issue by devernay** [Homebrew/homebrew-science#4791]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
no build error, but when compiling + running a program that uses OIIO:

```
Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/opt/openimageio/lib/libOpenImageIO.1.7.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/opt/openimageio/lib/libOpenImageIO.1.7.dylib
```
#### Brief summary of issue:

openimageio bottles are broken because of boost upgrade.

openimageio 1.7.9 was released upstream: why not upgrade it?

**Comment by jonchang** [comment]
There's a current pull request open at #4687 so we'll get around to it soon.

**Comment by devernay** [comment]
Shouldn't at least 1.7.8 bottles be invalidated, since they are corrupted?

**Comment by ilovezfs** [comment]
>Shouldn't at least 1.7.8 bottles be invalidated

No, we never do that.
