### ISSUE TITLE
brew install opencv3: error: '_mm_cvtph_ps' was not declared in this scope

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-science#4825]
same as https://github.com/Homebrew/homebrew-science/issues/4788 but but @jonchang incorrectly closed this issue; and because of https://github.com/isaacs/github/issues/583 we can't reopen issues. My fix https://github.com/Homebrew/homebrew-science/pull/4750 was enough to fix opencv3 a couple weeks ago but this new error crept up in the meantime

**Comment by timotheecour** [comment]
the culprit: https://github.com/Homebrew/homebrew-science/commit/42b72dda3e8507148159d642b69ce2d53a533602 introduced the regression

**Comment by timotheecour** [comment]
related: https://aur.archlinux.org/packages/opencv-git/?comments=all also mentions same error

**Comment by jonchang** [comment]
Hi @timotheecour, do you know if this error only occurs on 3.2, or did the removed patches in the 3.2 formula cause this error?

**Comment by timotheecour** [comment]
no idea, but could we revert to previous state where things weren't broken?

**Comment by timotheecour** [comment]
is this normal?

```
brew reinstall opencv3 --verbose --HEAD

-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "3.5.2")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/katrina/home/timothee/ubuntu1604/brew/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/katrina/home/timothee/ubuntu1604/brew/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/katrina/home/timothee/ubuntu1604/brew/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/katrina/home/timothee/ubuntu1604/brew/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/katrina/home/timothee/ubuntu1604/brew/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /katrina/home/timothee/ubuntu1604/brew/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

```

**Comment by timotheecour** [comment]
https://gist.github.com/d752621eff5844eee4cc47ff5e9147cf

**Comment by jonchang** [comment]
Looks like this is an upstream issue with opencv 3.2

**Comment by timotheecour** [comment]
sent out PR: https://github.com/Homebrew/homebrew-science/pull/5186

**Comment by iMichka** [comment]
And with #5348 we had some more changes, the formula builds on circle and travis. Closing here.
