### ISSUE TITLE
Armadillo with option to leave out superlu and arpack

### ISSUE THREAD

**Issue by pdondl** [Homebrew/homebrew-science#4829]
Just a suggestion: Armadillo is perfectly fine without those two dependencies (and they are very heavy themselves, depending on gcc, for example). It might be nice to make them 'recommended'.

**Comment by iMichka** [comment]
Hi. The balance between options/non-options is always difficult. With the bottles, compilation time is no more a reason to make things optional. Also, options are never tested during the build process on our bots, and often get broken.

So I think that we are going in the direction to make things mandatory than making things optional, which will help make things more stable for our users in the long run. This is still up to discussion of course. I'll close this as the current state is working for armadillo.
