### ISSUE TITLE
ART formula is out-of-date

### ISSUE THREAD

**Issue by niemasd** [Homebrew/homebrew-science#4835]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

#### Brief summary of issue:
The current [ART formula](https://github.com/Homebrew/homebrew-science/blob/master/art.rb) installs [ART-ChocolateCherryCake-03-19-2015](http://www.niehs.nih.gov/research/resources/assets/docs/artsrcchocolatecherrycake031915macostgz.tgz), which is a few versions out-of-date. The newest version is [ART-MountRainier-2016-06-05](https://www.niehs.nih.gov/research/resources/assets/docs/artsrcmountrainier20160605macostgz.tgz). It would be great if the formula could be updated.

#### The complete command that you issued:
```brew install art```

#### Gist with output of `brew doctor`:
```brew doctor``` is irrelevant here: the existing formula compiled and installed just fine.

#### Link output by `brew gist-logs <formula>`:
Again irrelevant: the existing formula compiled and installed just fine.

#### Output of `brew config`:
Again irrelevant: the existing formula compiled and installed just fine.

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by niemasd** [comment]
I created a Pull Request resolving the out-of-date issue:
https://github.com/Homebrew/homebrew-science/pull/4836

**Comment by iMichka** [comment]
I merged the pull request, you can now update to get the new version. Thanks.
