### ISSUE TITLE
netCDF and authentication/authorization

### ISSUE THREAD

**Issue by lesserwhirls** [Homebrew/homebrew-science#4843]
When accessing remote data with `netCDF` tools, like `ncdump`, users occasionally need to be able to use client side certificates for authentication and/or authorization. Currently, the homebrew build of netCDF links to the system copy of `libcurl`, which isn't built against `openssl` (in favor of `SecureTransport` alone). The result is that certificates, in PEM format, are not picked up properly by the `SecureTransport` libs and authentication/authorization fails.

If `netCDF` is built against the homebrew version of `libcurl` (supplied by the `curl` package), then we should be good, as it is built against `openssl`. Note that the homebrew version of `curl` is built against `openssl`, and curl commands to servers requiring the authorization/authentication work as expected.

Not sure if this is as simple as adding a dependency on `curl`, as I am not familiar with homebrew recipes.

edited - I meant curl, not wget.

**Comment by iMichka** [comment]
Hi. Thanks for the explanation.

> Not sure if this is as simple as adding a dependency on curl, as I am not familiar with homebrew recipes.

You can build with the `-v` flag to see what is going on. Maybe the logs will help you see with which curl netcdf gets compiled. And did you try this yourself? You seem not sure that this will fix the problem.

**Comment by lesserwhirls** [comment]
Hi @iMichka - I wasn't sure it would work until I tried it locally, and it does indeed work. I thought a patch would be more involved than one line (plus a revision bump), but when it turned out to be that easy, I went ahead and made a PR. I forgot to update this issue to make clear that the PR I submitted links to the correct (i.e. homebrew) version of curl.

**Comment by iMichka** [comment]
For ref PR opened here: #4847

**Comment by iMichka** [comment]
Closing here, see #4847 for discussion and possible solutions.
