### ISSUE TITLE
Installation of homebrew/science/vips fails

### ISSUE THREAD

**Issue by korya** [Homebrew/homebrew-science#4845]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I just tried to run `brew upgrade` and the command failed. I uninstalled the package, ran `brew cleanup -s` and installed it back, same problem remains. I followed the instructions at https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting, nothing helped.

The problem seems to be with `homebrew/science/vips` package. I have not installed it, it comes as a dependency for other package. 

Here is `brew gist-logs`: https://gist.github.com/24d4d89ef4af67cdf52dd36ef27f0ab3

**Comment by jonchang** [comment]
What other package are you trying to install? It seems like this specific combination of options:

```
--without-fftw --without-gobject-introspection --without-libexif --without-libgsf --without-little-cms2 --without-orc --without-pango --without-pygobject3 --without-python
```

is causing the `vips` build to fail. Specifically it's looking for `libexif` symbols and can't find them:

```
In file included from vips2jpeg.c:148:
./jpeg.h:80:32: error: unknown type name 'ExifData'
int vips__set_exif_resolution( ExifData *ed, VipsImage *im );
```

We recommend installing using bottles whenever possible.

**Comment by korya** [comment]
I am not sure when it got broken. Suddenly I started seeing this error couple months ago, but back then I said may be I have to upgrade Xcode, and if I am going to upgrade Xcode it makes sense to upgrade the OS and a lot of other applications. So I waited until last week, when I finally have upgrade OSX, Xcode and a lot of other software. But the problem remained.

What does 'installing using bottles' mean?

**Comment by iMichka** [comment]
Hi. `bottles` are binaries that we precompile for the users, so that they do not need to rebuild the packages. But as soon as you use optional flags it will recompile the library. And this often fails because all these options flags are sort of "untested".
