### ISSUE TITLE
ceres-solver built against old eigen3

### ISSUE THREAD

**Issue by at-2500** [Homebrew/homebrew-science#4852]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

When trying to use ceres in cmake, the result is
```
CMake Error at /usr/local/lib/cmake/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Found Eigen dependency, but the version of Eigen
  found (3.3.1) does not exactly match the version of Eigen Ceres was
  compiled with (3.3.0).  This can cause subtle bugs by triggering violations
  of the One Definition Rule.  See the Wikipedia article
  http://en.wikipedia.org/wiki/One_Definition_Rule for more details
```

homebrews eigen:
```
brew info eigen                                                                                                                                    (master)
eigen: stable 3.3.1 (bottled), HEAD
C++ template library for linear algebra
https://eigen.tuxfamily.org/
/usr/local/Cellar/eigen/3.3.1 (486 files, 6.4M) *
  Poured from bottle on 2016-12-19 at 13:16:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/eigen.rb
==> Dependencies
Build: cmake ✔
==> Options
--universal
	Build a universal binary
--HEAD
	Install HEAD version
```

#### Brief summary of issue:

Looks like ceres-solver needs to be rebuilt against the newer version of eigen.

#### The complete command that you issued:

`cmake ..`

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by djazo** [comment]
This happens almost always when eigen is updated. Workaround is to:
brew install --build-from-source ceres-solver

**Comment by ilovezfs** [comment]
>This happens almost always when eigen is updated

Considering that the reverse dependencies get revision bumped when there's an upgrade, that's not really a particularly helpful thing to say, as it's demonstrably false.

**Comment by ilovezfs** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-science/pull/4961.

**Comment by ilovezfs** [comment]
should be fixed now.
