### ISSUE TITLE
viennarna is outdated

### ISSUE THREAD

**Issue by twogee** [Homebrew/homebrew-science#4854]
viennarna in mac brew is version 2.1.9, but the latest version is 2.3.1 and the URL is different.
I tried "brew edit viennarna" and change the URL + checksum to rebuild from source, but the source archive is sent as an attachment and brew seems unable to handle it properly.
There's a dmg available for download, so maybe viennarna shoould move to the caskroom.
What do you think?

**Comment by iMichka** [comment]
Hi. Thanks for letting us know.

Looking at their homepage (http://www.tbi.univie.ac.at/RNA/#download), the new url seems to be:
`http://www.tbi.univie.ac.at/RNA/download/sourcecode/2_3_x/ViennaRNA-2.3.1.tar.gz`

I am not sure what you mean by: `but the source archive is sent as an attachment and brew seems unable to handle it properly`? Do you have a specific error message that you could share?

If you want to contribute, you can follow the instructions on how to open a pull request [here](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html).

**Comment by twogee** [comment]
What I meant was that if I try to run brew install on updated formula, the contents of ViennaRNA-2.3.1.tar.gz are those of the web page, that is, it contains the HTML code. I believe the reason for this is that the actual tar.gz file is sent as an attachment to the web page.

**Comment by twogee** [comment]
I tried again and noticed that brew is getting redirected

```
==> Upgrading homebrew/science/viennarna 
==> Downloading https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_3_x/ViennaRNA-2.3.1.tar.gz
==> Downloading from https://www.tbi.univie.ac.at/RNA/
```

but wget is not... is Vienna University blocking homebrew?

**Comment by iMichka** [comment]
I had a look at this.

Homebrew tries to setup the url here:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/download_strategy.rb#L401-L408

Here is the output:
```
curl -I -L https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_3_x/ViennaRNA-2.3.1.tar.gz 

HTTP/1.1 302 Found
Date: Tue, 17 Jan 2017 18:09:19 GMT
Server: Apache/2.2.22
X-Powered-By: PHP/5.3.10-1ubuntu3.25
Location: https://www.tbi.univie.ac.at/RNA
Content-Type: text/html

HTTP/1.1 301 Moved Permanently
Date: Tue, 17 Jan 2017 18:09:19 GMT
Server: Apache/2.2.22
Location: https://www.tbi.univie.ac.at/RNA/
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Tue, 17 Jan 2017 18:09:19 GMT
Server: Apache/2.2.22
Last-Modified: Tue, 15 Nov 2016 13:34:49 GMT
ETag: "2ca5df6-360ca-54157054595ac"
Accept-Ranges: bytes
Content-Length: 221386
Vary: Accept-Encoding
Content-Type: text/html
```

So the output from curl is weird, and the urls get wrongly setup. This will probably need to be made more robust. Or the server setup is really weird. But this explains why the html page gets downloaded.

**Comment by iMichka** [comment]
The time being, I tried and by guessing, using the pattern of the old URL:
`http://www.tbi.univie.ac.at/~ronny/RNA/packages/source/ViennaRNA-2.3.1.tar.gz`

That one works. Please use that in your pull request.

**Comment by iMichka** [comment]
Even better (with the help of @ilovezfs):

Get info in the Finder: `http://www.tbi.univie.ac.at/RNA/packages/source/ViennaRNA-2.3.1.tar.gz`
Url in the browser: `http://www.tbi.univie.ac.at/RNA/download/sourcecode/2_3_x/ViennaRNA-2.3.1.tar.gz`

So the best is to use `http://www.tbi.univie.ac.at/RNA/packages/source/ViennaRNA-2.3.1.tar.gz`

**Comment by twogee** [comment]
Thanks for helping out with the URL. What should I do about the bottle?

**Comment by iMichka** [comment]
As stated in the [doc](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html):
> If there’s a bottle do block in the formula: don’t remove or change it; we’ll update it when we pull your PR.
