### ISSUE TITLE
WCSLIB is now outdated

### ISSUE THREAD

**Issue by rlancaste** [Homebrew/homebrew-science#4856]
WCSLIB 5.12 does not exist anymore at ftp://ftp.atnf.csiro.au/.  Therefore running brew install wcslib fails.  They are now on version 5.16.

Please update the formula.

Thanks!

**Comment by iMichka** [comment]
Hi

Thanks for the notification. Would you like to edit the formula yourself and submit a pull request? It is pretty easy. There is a tutorial on how to open a pull request here: http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

**Comment by rlancaste** [comment]
Hi, thank you for responding so quickly.  On my own machine, I edited the wcslib.rb file earlier today to reflect the new version number and removed the checksum and it seemed to work.  The problem is that while I could probably change zip file's name and submit a pull request, I don't know where the sha256 checksum comes from to enter it correctly.  I also don't know if there is anything else that would need to change with the new version (but I don't think so, particularly since it worked on my machine).

**Comment by iMichka** [comment]
You can use ```shasum -a 256 /filepath/downloadedfile```. You can also run the formula; it will fail at the sha256 check and tell you which one to use.

Also, don't worry about other changes. If you just update the version number, in simple cases, there is often nothing else to do (only if there are failures or you want to explicitly change something). For changes we leave that up to the users: they know best what options they want to have for a formula.

**Comment by rlancaste** [comment]
I attempted the pull request.  Please let me know if there are any issues.

**Comment by iMichka** [comment]
@rlancaste thanks for your contribution to Homebrew.

Closed by a907fabfd52f9a139408f6e8cc7ce9394a687e66
