### ISSUE TITLE
R -- any reason not to use CRAN's build env variables?

### ISSUE THREAD

**Issue by gwerbin** [Homebrew/homebrew-science#4865]
The ["R Installation and Administration" manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html) says that the official CRAN binary is built using the following environment variables:

```shell
CC=clang
CXX=clang++
F77=gfortran-4.8
FC=$F77
OBJC=clang
CFLAGS='-Wall -mtune=core2 -g -O2'
CXXFLAGS='-Wall -mtune=core2 -g -O2'
OBJCFLAGS='-Wall -mtune=core2 -g -O2'
F77FLAGS='-Wall -g -O2'
FCFLAGS=$F77FLAGS
```

See https://cran.r-project.org/doc/manuals/r-release/R-admin.html#macOS for more.

It looks like this change would be easy; I think you'd just have to add

```ruby
# Use the same build variables as the official CRAN binary
args << "CFLAGS=-Wall -mtune=core2 -g -O2"
args << "CXXFLAGS=-Wall -mtune=core2 -g -O2"
args << "OBJCFLAGS=-Wall -mtune=core2 -g -O2"
args << "F77FLAGS=-Wall -g -O2"
args << "FCFLAGS=-Wall -g -O2"
```

somewhere before the line

```ruby
system "./configure", *args
```

Then the only difference being that instead of always using `gfortran-4.8`, Homebrew would just use the latest version installed with GCC.

Is there any reason this shouldn't be in the R formula? I made this change to my local Homebrew version and it certainly didn't seem to break anything.

**Comment by greg-rocketrip** [comment]
Sorry to double-post (on a different account no less), but this is what the change might look like:

https://github.com/Homebrew/homebrew-science/compare/master...greg-rocketrip:r-cran-build-parity

**Comment by iMichka** [comment]
Closing here too. The question was answered in the PR. We already pass the right flags.
