### ISSUE TITLE
Update bottles for Linuxbrew

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#4926]
+ [x] bedops #4912
+ [x] circlator #4907
+ [ ] cppad #4890
+ [ ] dgtal #4891
+ [x] mothur #4904
+ [x] openfst #4902
+ [x] opengrm-ngram #4902
+ [x] opengrm-thrax #4902
+ [ ] orocos-kdl #4892
+ [x] packmol #4914
+ [ ] shogun #4893
+ [x] stringtie #4909
+ [x] viennarna #4917
+ [ ] vtk #4919

**Comment by sjackman** [comment]
Bioinformatics formula: bedops circlator diamond gubbins iva mothur nextflow quast sratoolkit stringtie viennarna

**Comment by iMichka** [comment]
vtk was done with #5050 :)
