### ISSUE TITLE
moab: sha256 mismatch when building from source

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-science#4933]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
brew install moab -sv
==> Installing moab from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/fathom/moab-4.9.2.tar.gz
Already downloaded: /Users/michkapopoff/Library/Caches/Homebrew/moab-4.9.2.tar.gz
==> Verifying moab-4.9.2.tar.gz checksum
Error: SHA256 mismatch
Expected: 5d79e299dd9bf76d7cade434cde478bb6dc8290e5b574b25cc30ee96f35a203d
Actual: 26611b8cc24f6b7df52eb4ecbd31523d61523da0524b5a2d066a7656e2e82ac5
Archive: /Users/michkapopoff/Library/Caches/Homebrew/moab-4.9.2.tar.gz
To retry an incomplete download, remove the file above.
```

#### Brief summary of issue:

When building moab from source, the sha256 is not correct / or has changed.

#### The complete command that you issued:

`brew install moab -s`

#### Gist with output of `brew doctor`:

Not relevant

#### Link output by `brew gist-logs <formula>`:

Not relevant / no logs produced

#### Output of `brew config`:

Not relevant

**Comment by ilovezfs** [comment]
original tarball was added to the formula in 5820cb647, which was 11th Sep 2016, but the tarball was re-uploaded on  6th Jan 2017, so we have a misbehaving, or hacked, upstream.

**Comment by ilovezfs** [comment]
updated checksum in https://github.com/Homebrew/homebrew-science/pull/4946

**Comment by iMichka** [comment]
I opened an issue upstream: https://bitbucket.org/fathomteam/moab/issues/55/moab-492-targz-checksum-has-changed

Let's wait until we get an answer.

**Comment by iMichka** [comment]
Close with #4946
