### ISSUE TITLE
BUSCO brew not working

### ISSUE THREAD

**Issue by sablokg** [Homebrew/homebrew-science#4962]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
==> Installing busco from homebrew/science
==> Downloading http://busco.ezlab.org/files/BUSCO_v1.22.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "busco"
Download failed: http://busco.ezlab.org/files/BUSCO_v1.22.tar.gz
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
Should be fixed now if you `brew update`
