### ISSUE TITLE
Unable to install `littler`

### ISSUE THREAD

**Issue by genos** [Homebrew/homebrew-science#4969]
Hi all! I'm trying to install the `littler` formula for running `R` scripts from the command line.

### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- ~~[ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~ (N/A)

### Bug reports / build errors:
```
brew install littler
==> Installing littler from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://dirk.eddelbuettel.com/code/littler/littler-0.2.3.tar.gz
Already downloaded: /Users/graham/Library/Caches/Homebrew/littler-0.2.3.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/littler/0.2.3_6
==> make littler.h
Error: inreplace failed
littler.h:
  expected replacement of #<Pathname:/usr/local/opt/r> with #<Pathname:/usr/local/opt/r>
```
#### Brief summary of issue:
Unable to install `littler` formula.
#### The complete command that you issued:
`brew install littler`
#### Gist with output of `brew doctor`:
`Your system is ready to brew.`
#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/genos/fe36db12097dffa877feac83ccb5dee2
#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f86798d5e6b61b5928ef3bd803ad302550b49d3b
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.7.0_79
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by iMichka** [comment]
Hi. Thanks for reporting. A fix is underway, you can test it if you want: #5074

**Comment by iMichka** [comment]
Patch has been merged and bottles rebuild.

Please `brew update` and `brew upgrade` to test this. I do believe this is fixed for now, I'll close this issue. Please tell us if you still encounter problems. Thanks.

**Comment by genos** [comment]
Looks great, thanks very much!
