### ISSUE TITLE
ld: library not found -lgfortran, during pkg install -forge control in octave 4.2.0_2

### ISSUE THREAD

**Issue by sunilshah** [Homebrew/homebrew-science#4972]
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] Checked that a similar issue hasn't already been filed?
- [ x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
octave 4.2.0_2 and gcc6.3.0_1 have been installed with no errors.  Brew is updated and upgraded.  

In octave 
octave:1> pkg install -forge control
... some warnings about deprecated octave declarations
5 warnings generated.
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin16.3.0/6.3.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin16.3.0/6.3.0/../../..'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [__control_slicot_functions__.oct] Error 1
tar -xzf slicot.tar.gz
/usr/local/Cellar/octave/4.2.0_2/bin/mkoctfile-4.2.0 __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp; /usr/local/Cellar/octave/4.2.0_2/bin/mkoctfile-4.2.0 -c *.f
ar -rc slicotlibrary.a ./sltmp/*.o
rm -rf sltmp slicot
LFLAGS="-L/usr/local/Cellar/octave/4.2.0_2/lib/octave/4.2.0 -L/usr/local/Cellar/octave/4.2.0_2/lib  -L/usr/local/opt/veclibfort/lib -lvecLibFort  -L/usr/local/opt/readline/lib -L/usr/local/opt/suite-sparse/lib -L/usr/local/opt/metis/lib -L/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin16.3.0/6.3.0 -L/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin16.3.0/6.3.0/../../.. -lreadline -lsuitesparseconfig -lmetis -lgfortran -lquadmath -lm" \
    /usr/local/Cellar/octave/4.2.0_2/bin/mkoctfile-4.2.0 __control_slicot_functions__.cc common.cc slicotlibrary.a

pkg: error running `make' for the control package.
error: called from
    install at line 200 column 5
    pkg at line 394 column 9. 
#### Brief summary of issue:
Can not install control package in octave 4.2.0_2
#### The complete command that you issued:
See above
#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
brew gist-logs octave
 Error: No logs.
brew gist-logs gcc
https://gist.github.com/371e5c11de0def4315112ecd217b1866

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 19e51bb34aadf41021eba91eed508eaf3300da47
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.11 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sunilshah** [comment]
Checked that  gfortan was installed on the machine.

**Comment by sunilshah** [comment]
Clang default target on the machine is 
clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0

Yet, pkg install script is using the old target of x86_64-apple-darwin16.3.0.  So, the corresponding directories under

/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin16.3.0

do not exist but instead they are  

/usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6/gcc/x86_64-apple-darwin16.4.0

**Comment by schoeps** [comment]
Your octave seems to have been build on an older macOS version (16.3 instead 16.4). At that time `.../x86_64-apple-darwin16.3.0` was correct. Now you update macOS and gcc but not octave. You can check where octave expects Fortran libs to be located by running `mkoctfile -p FLIBS` on the command line. 

As I explained on the octave mailing list: reinstalling octave from source should fix this problem: `brew install --build-from-source octave`. Octave's configure script should find the correct libs.

**Comment by sunilshah** [comment]
Thanks.  

Re-building from source worked fine.  

I suppose at some point the bottled version on homebrew will be updated so that it works with the latest gcc on homebrew-core.

**Comment by olalonde** [comment]
Had a similar issue:

```
~$ octave
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib
  Reason: image not found
octave exited with signal 6
~$ readlink $(which gfortran)
../Cellar/gcc/6.3.0_1/bin/gfortran
~$ brew reinstall qrupdate
==> Reinstalling homebrew/science/qrupdate
==> Downloading https://homebrew.bintray.com/bottles-science/qrupdate-1.1.2_4.sierra.bottle.1.tar.gz
Already downloaded: /Users/olalonde/Library/Caches/Homebrew/qrupdate-1.1.2_4.sierra.bottle.1.tar.gz
==> Pouring qrupdate-1.1.2_4.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/qrupdate/1.1.2_4: 8 files, 337.9KB
~$ octave
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib
  Reason: image not found
octave exited with signal 6
~$ ll /usr/local/opt/gcc/lib/gcc/
total 0
drwxr-xr-x   3 olalonde  admin   102B Dec 21 01:56 .
drwxr-xr-x   3 olalonde  admin   102B Dec 21 01:56 ..
drwxr-xr-x  52 olalonde  admin   1.7K Mar 22 13:09 6
```

Tried a bunch of stuff but the only thing that worked was re-building from source with `brew install --build-from-source octave`.

**Comment by itsayellow** [comment]
Looks like now the octave bottle is referencing gcc 6, but now homebrew-core has updated gcc to 7:
`birchtree:~$ octave
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/opt/qrupdate/lib/libqrupdate.1.dylib
  Reason: image not found
octave exited with signal 6`

I can fix this by `brew install gcc@6` and then making a symlink from /usr/local/opt/gcc/lib/gcc/6 to its lib/gcc/6.

But it would be nice if the bottled octave used the current gcc 7 in homebrew-core.

**Comment by ilovezfs** [comment]
The revisions for the new gcc will take some time to all go through.

**Comment by sunilshah** [comment]
Before you close the issue, can you please list the commands a non-expert user of homebrew needs to issue in the workaround?  

For example, to get back to gcc@6 and "creating symlink from /usr/local/opt/gcc/lib/gcc/6 to its lib/gcc/6" , what is the exact incantation for the un-initiated?

**Comment by sunilshah** [comment]
In my case, because gcc  6.3.0_1 was already installed (for the last working octave build)

>> ln -s   /usr/local/Cellar/gcc/6.3.0_1/lib/gcc/6      /usr/local/lib/gcc/6

works.

Does that sound right in general?

**Comment by ilovezfs** [comment]
No. You should not do any of these workarounds. You should simply install the lastest gcc, and brew install --build-from-source anything that has not already had its revision bump go through.

**Comment by sunilshah** [comment]
In my case, that did not work- it gave the same error of not finding the library.  

See http://octave.1599824.n4.nabble.com/Octave-gcc-problem-Homebrew-Mac-td4683174.html

**Comment by ilovezfs** [comment]
Please file a new issue if it's still broken.
