### ISSUE TITLE
libtiff.so.5 installed from libtiff-4.0.7_2 , version mismatch?

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-science#4975]
while trying to debug https://github.com/Homebrew/homebrew-science/issues/4974 I found that libtiff.so.5 is installed from libtiff-4.0.7_2 , isn't that a version mismatch?

eg:
```
$ ldd lib/libopencv_highgui.so.2.4.13
lib/libopencv_highgui.so.2.4.13: /home/timothee/m/katrina/brew/lib/libtiff.so.5: no version information available (required by lib/libopencv_highgui.so.2.4.13)
        libtiff.so.5 => /home/timothee/m/katrina/brew/lib/libtiff.so.5 (0x00007f3e8c32a000)

ls brew/lib/libtiff.so.5
brew/lib/libtiff.so.5 -> ../Cellar/libtiff/4.0.7_2/lib/libtiff.so.5 
```

**Comment by iMichka** [comment]
Is this on Linux?

And please, please, use the issue template. It helps us standardise the bug reports.

**Comment by jonchang** [comment]
Hi @timotheecour, please use the issue template. `libtiff` is in core so you'd have been better off reporting this there; regardless, the version number of dynamic libraries does not necessarily have to match the version number of the actual software.
