### ISSUE TITLE
The new source of actual code for Therion: https://github.com/therion/therion.git May you change the cask, please?

### ISSUE THREAD

**Issue by martinsluka** [Homebrew/homebrew-science#4996]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
Hello. I am not sure what you are requesting. Could you be more explicit?

If you want an update to a newer version, the project needs to tag an official release. We do not deliver releases from a random commit.

**Comment by martinsluka** [comment]
> 6. 2. 2017 v 23:24, Michka Popoff <notifications@github.com>:
> 
> If you want an update to a newer version, the project needs to tag an official release. We do not deliver releases from a random commit.
> 
> 

That is not random commit, it is official git repository of Therion software. New one. The static source of Therion window’s version is linked to this repository yet - check therion.speleo.sk - download page. The git repository is managed by the same people as static page - Martin Budaj and Stacho Mudrak.

Regards

Martin Sluka

**Comment by iMichka** [comment]
I understand that this is not a "random commit", but the website is saying:
> The current stable version is 5.3.16, released on Dec 28, 2014
This is the version we deliver

And also:
>  The current Therion for Windows [built on Feb 10, 2017 from the commit 32eecee;

If this is a stable version, it needs to be tagged on GitHub first. The Therion authors need to sort this out. And we are not running after the different projects managers to get stuff tagged, we have no time for this (we do it sometimes, but it is rather exceptional). You could gently ask them to do it.

I'll close this. You can notify us as soon as the stable version is update or open a pull request yourself to get this updated, which is the more efficient way. Thanks.
