### ISSUE TITLE
Remove CoinUtils from homebrew/science?

### ISSUE THREAD

**Issue by dpo** [Homebrew/homebrew-science#505]
`coinutils` is already contained in `coinmp`. I just opened a [coinor](https://github.com/dpo/homebrew-coinor) tap for [Coin-OR](http://www.coin-or.org) packages that conflict with one another. I'm thinking `coinutils` should move there. Homebrew/Science would be left with `coinmp`, which is the most comprehensive.

Because of the way Coin-OR packages stuff, ~~coinutils~~ `coinmp` does not necessarily contain the most recent version of CLP, CBC, or other sub-packages. If users are interested in those latest versions, they can obtain them from the Coin-OR tap.

Pinging @sjackman and @samueljohn for opinions.

**Comment by dpo** [comment]
Moving COIN formulas to https://github.com/coin-or-tools/homebrew-coinor little by little. Affected formulas:
- [ ] `coinutils`
- [ ] `ipopt`
- [ ] `coinmp`
- [ ] `adol-c`
- [ ] `cppad`
- [ ] `symphony`

**Comment by tkelman** [comment]
coinmp should be split into a 6-part stack:

- coinutils
- osi
- clp
- cgl
- cbc
- coinmp

I've also got formulae for bonmin, couenne, and optimization services at https://github.com/staticfloat/homebrew-juliadeps

**Comment by dpo** [comment]
Yes I know ;). Great that also have some formulae. I have CGL, CBC, CLP, and some others.

**Comment by iMichka** [comment]
As homebrew-science will disappear under it's current form (see #6365), are there any volunteers to move some more formulae to taps?

**Comment by dpo** [comment]
This is already taken care of in https://github.com/coin-or-tools/homebrew-coinor.

**Comment by iMichka** [comment]
Thx.
