### ISSUE TITLE
After vtk update to vtk-7.1.0_4.sierra.bottle: ImportError: No module named vtkIOAMRPython

### ISSUE THREAD

**Issue by butala** [Homebrew/homebrew-science#5062]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

After the update, I can no longer "import vtk" from python. I get the error:

Python 2.7.13 (default, Dec 19 2016, 19:59:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/vtk/__init__.py", line 99, in <module>
    from .vtkIOAMR import *
  File "/usr/local/lib/python2.7/site-packages/vtk/vtkIOAMR.py", line 9, in <module>
    from vtkIOAMRPython import *
ImportError: No module named vtkIOAMRPython

#### The complete command that you issued:

See above code run from python interpreter (built from homebrew).

#### Gist with output of `brew doctor`:

https://gist.github.com/butala/c6011850737dd606a58e8ba080d6aa29

#### Link output by `brew gist-logs <formula>`:

brew gist-logs vtk

Error: No logs.

#### Output of `brew config`:

HOMEBREW_VERSION: 1.1.9-31-g11abfc39a
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 11abfc39ab593a525663c9dc7f24a9a93fb895e4
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b9a729619e1e6998bc309ebcf7ba18a21255d0c
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_65
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
Hi. Thanks for reporting. Revision 5 is out, but this should not change anything to your problem.

Does the `/usr/local/lib/python2.7/site-packages/vtk/vtkIOAMRPython.so` file exist?
Could you make sure your `/usr/local/lib/python2.7/site-packages/` is in your path?
Please look at the output of `import sys` and then `sys.path` for this.

Thanks.

**Comment by butala** [comment]
Hmm. Now works post revision 5.

Sorry to have bothered you.

**Comment by iMichka** [comment]
No problem. Thanks for the feedback.
