### ISSUE TITLE
ncview startup error

### ISSUE THREAD

**Issue by joergsteinkamp** [Homebrew/homebrew-science#5068]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
When calling `ncview` it complains about incompatible netcdf library:
> ncview 
dyld: Library not loaded: /usr/local/opt/netcdf/lib/libnetcdf.11.dylib
  Referenced from: /usr/local/bin/ncview
  Reason: Incompatible library version: ncview requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0
Abort trap: 6

#### Brief summary of issue:
ncview does not start
#### The complete command that you issued:
ncview

#### Gist with output of `brew doctor`:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/Pygame/_camera.h
  /usr/local/include/python2.7/Pygame/_pygame.h
  /usr/local/include/python2.7/Pygame/_surface.h
  /usr/local/include/python2.7/Pygame/bitmask.h
  /usr/local/include/python2.7/Pygame/camera.h
  /usr/local/include/python2.7/Pygame/fastevents.h
  /usr/local/include/python2.7/Pygame/font.h
  /usr/local/include/python2.7/Pygame/freetype.h
  /usr/local/include/python2.7/Pygame/mask.h
  /usr/local/include/python2.7/Pygame/mixer.h
  /usr/local/include/python2.7/Pygame/pgarrinter.h
  /usr/local/include/python2.7/Pygame/pgbufferproxy.h
  /usr/local/include/python2.7/Pygame/pgcompat.h
  /usr/local/include/python2.7/Pygame/pgopengl.h
  /usr/local/include/python2.7/Pygame/pygame.h
  /usr/local/include/python2.7/Pygame/scrap.h
  /usr/local/include/python2.7/Pygame/surface.h

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b9a729619e1e6998bc309ebcf7ba18a21255d0c
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
This will be fixed by https://github.com/Homebrew/homebrew-science/pull/4949.

**Comment by joergsteinkamp** [comment]
Thanks. I didn't find #4949 due to "is:issue" filter, which is active by default. Should I close this one?

**Comment by ilovezfs** [comment]
@joergsteinkamp Yes, this can be closed. Also I just updated #4949 so it should actually succeed this time :)
