### ISSUE TITLE
Inappropriate file type or format BLAST v.2.6.0

### ISSUE THREAD

**Issue by storer1017** [Homebrew/homebrew-science#5105]
Here is the error that I keep getting when I run:
sudo make install 
For RMBlast

install: /Users/batzer/Documents/RepeatMasker/NCBI_BLAST/c++/ReleaseMT/inc/common: Inappropriate file type or format
make[1]: *** [install-toolkit] Error 71
make: *** [install] Error 2

Does anyone know how to fix this?

**Comment by fxcoudert** [comment]
Can you please fill out the [issue template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md)? This will help us better diagnose the problem you're experiencing.

**Comment by iMichka** [comment]
I will close this issue, you will have to open a new one, with the issue template properly filled out.
