### ISSUE TITLE
Inappropriate file type or format Blast 2.6.0

### ISSUE THREAD

**Issue by storer1017** [Homebrew/homebrew-science#5127]
### Indicate troubleshooting steps taken
I ran brew update, brew doctor, checked that a similar issues hasn't already be filed, and tried sudo make install. 
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
For Blast 2.6.0 documentation see:
http://www.repeatmasker.org/RMBlast.html

For Blast 2.6.0 I get the following error when I try to enter:
sudo make install 
 
batzer$ sudo make install
if test -d /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then \
	    /Library/Developer/CommandLineTools/usr/bin/make  install-gbench; \
	else \
	    /Library/Developer/CommandLineTools/usr/bin/make  install-toolkit; \
	fi
/bin/rm -rf /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install -c -d /usr/local/rmblast/bin /usr/local/rmblast/lib /usr/local/rmblast/include/ncbi-tools++
/usr/bin/install -c /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/* /usr/local/rmblast/bin
/usr/bin/install -c -m 644 /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/*.* /usr/local/rmblast/lib
if test -d /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi; then \
	    cp -pPR /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi /usr/local/rmblast/lib/; \
	fi
rm -f /usr/local/rmblast/lib/lib*-static.a
cd /usr/local/rmblast/lib  && \
	    for x in *.a; do \
	        /bin/ln -s "$x" "`/usr/bin/basename \"$x\" .a`-static.a"; \
	    done
cd /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/include && find * -name CVS -prune -o -print |\
            cpio -pd /usr/local/rmblast/include/ncbi-tools++
51199 blocks
/usr/bin/install -c -m 644 /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/* /usr/local/rmblast/include/ncbi-tools++
install: /Users/batzer/Documents/RepeatMasker/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/common: Inappropriate file type or format
make[1]: *** [install-toolkit] Error 71
make: *** [install] Error 2
#### Brief summary of issue:
The error I keep getting tells me that I have the inappropriate file or format. I confirmed that the file were executable. 

#### The complete command that you issued:
I was having issues with permission for make install, so I used:

sudo make install 

instead. This got me past the permission error, but as stated above, I'm getting a different error now. 

#### Gist with output of `brew doctor`:
I ran the following command:
brew doctor 

and the output was:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libdbapi_driver-dll.dylib
  /usr/local/lib/libncbi_xcache_dbapi-dll.dylib
  /usr/local/lib/libncbi_xcache_netcache-dll.dylib
  /usr/local/lib/libncbi_xloader_genbank-dll.dylib
  /usr/local/lib/libncbi_xreader-dll.dylib
  /usr/local/lib/libncbi_xreader_cache-dll.dylib
  /usr/local/lib/libncbi_xreader_id1-dll.dylib
  /usr/local/lib/libncbi_xreader_id2-dll.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/compo_heap.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/compo_mode_condition.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/composition_adjustment.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/composition_constants.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/matrix_frequency_data.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/nlm_linear_algebra.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/optimize_target_freq.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/redo_alignment.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/smith_waterman.h
  /usr/local/include/ncbi-tools++/algo/blast/composition_adjustment/unified_pvalues.h
  /usr/local/include/ncbi-tools++/algo/blast/core/aa_ungapped.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_aalookup.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_aascan.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_def.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_diagnostics.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_encoding.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_engine.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_export.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_extend.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_filter.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_gapalign.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_hits.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_hspfilter.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_hspstream.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_kappa.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_lookup.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_message.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_nalookup.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_nascan.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_options.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_parameters.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_program.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_psi.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_query_info.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_rps.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_seg.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_seqsrc.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_seqsrc_impl.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_setup.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_stat.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_sw.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_toolkit.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_traceback.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_tune.h
  /usr/local/include/ncbi-tools++/algo/blast/core/blast_util.h
  /usr/local/include/ncbi-tools++/algo/blast/core/gapinfo.h
  /usr/local/include/ncbi-tools++/algo/blast/core/gencode_singleton.h
  /usr/local/include/ncbi-tools++/algo/blast/core/greedy_align.h
  /usr/local/include/ncbi-tools++/algo/blast/core/hspfilter_besthit.h
  /usr/local/include/ncbi-tools++/algo/blast/core/hspfilter_collector.h
  /usr/local/include/ncbi-tools++/algo/blast/core/hspfilter_culling.h
  /usr/local/include/ncbi-tools++/algo/blast/core/hspfilter_mapper.h
  /usr/local/include/ncbi-tools++/algo/blast/core/link_hsps.h
  /usr/local/include/ncbi-tools++/algo/blast/core/lookup_util.h
  /usr/local/include/ncbi-tools++/algo/blast/core/lookup_wrap.h
  /usr/local/include/ncbi-tools++/algo/blast/core/mb_indexed_lookup.h
  /usr/local/include/ncbi-tools++/algo/blast/core/na_ungapped.h
  /usr/local/include/ncbi-tools++/algo/blast/core/ncbi_math.h
  /usr/local/include/ncbi-tools++/algo/blast/core/ncbi_std.h
  /usr/local/include/ncbi-tools++/algo/blast/core/pattern.h
  /usr/local/include/ncbi-tools++/algo/blast/core/phi_extend.h
  /usr/local/include/ncbi-tools++/algo/blast/core/phi_gapalign.h
  /usr/local/include/ncbi-tools++/algo/blast/core/phi_lookup.h
  /usr/local/include/ncbi-tools++/algo/blast/core/split_query.h
  /usr/local/include/ncbi-tools++/common/config/ncbiconf_msvc.h
  /usr/local/include/ncbi-tools++/common/config/ncbiconf_universal.h
  /usr/local/include/ncbi-tools++/common/config/ncbiconf_xcode.h
  /usr/local/include/ncbi-tools++/common/metamodules_doxygen.h
  /usr/local/include/ncbi-tools++/common/ncbi_export.h
  /usr/local/include/ncbi-tools++/common/ncbi_package_ver.h
  /usr/local/include/ncbi-tools++/common/ncbi_skew_guard.h
  /usr/local/include/ncbi-tools++/common/ncbi_source_ver.h
  /usr/local/include/ncbi-tools++/common/ncbiconf_impl.h
  /usr/local/include/ncbi-tools++/common/test_assert.h
  /usr/local/include/ncbi-tools++/common/test_assert_impl.h
  /usr/local/include/ncbi-tools++/common/test_data_path.h
  /usr/local/include/ncbi-tools++/connect/connect_export.h
  /usr/local/include/ncbi-tools++/connect/ncbi_base64.h
  /usr/local/include/ncbi-tools++/connect/ncbi_buffer.h
  /usr/local/include/ncbi-tools++/connect/ncbi_connection.h
  /usr/local/include/ncbi-tools++/connect/ncbi_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_connutil.h
  /usr/local/include/ncbi-tools++/connect/ncbi_core.h
  /usr/local/include/ncbi-tools++/connect/ncbi_file_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_ftp_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_gnutls.h
  /usr/local/include/ncbi-tools++/connect/ncbi_heapmgr.h
  /usr/local/include/ncbi-tools++/connect/ncbi_host_info.h
  /usr/local/include/ncbi-tools++/connect/ncbi_http_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_memory_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_sendmail.h
  /usr/local/include/ncbi-tools++/connect/ncbi_server_info.h
  /usr/local/include/ncbi-tools++/connect/ncbi_service.h
  /usr/local/include/ncbi-tools++/connect/ncbi_service_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_socket.h
  /usr/local/include/ncbi-tools++/connect/ncbi_socket_connector.h
  /usr/local/include/ncbi-tools++/connect/ncbi_socket_unix.h
  /usr/local/include/ncbi-tools++/connect/ncbi_types.h
  /usr/local/include/ncbi-tools++/connect/ncbi_util.h
  /usr/local/include/ncbi-tools++/corelib/hash_impl/_hash_fun.h
  /usr/local/include/ncbi-tools++/corelib/hash_impl/_hash_map.h
  /usr/local/include/ncbi-tools++/corelib/hash_impl/_hash_set.h
  /usr/local/include/ncbi-tools++/corelib/hash_impl/_hashtable.h
  /usr/local/include/ncbi-tools++/corelib/hash_impl/_relops_hash_cont.h
  /usr/local/include/ncbi-tools++/corelib/impl/ncbi_atomic_defs.h
  /usr/local/include/ncbi-tools++/corelib/impl/ncbi_java.h
  /usr/local/include/ncbi-tools++/corelib/impl/ncbi_os_mswin.h
  /usr/local/include/ncbi-tools++/corelib/impl/ncbi_panfs.h
  /usr/local/include/ncbi-tools++/corelib/mswin_export.h
  /usr/local/include/ncbi-tools++/corelib/mswin_no_popup.h
  /usr/local/include/ncbi-tools++/corelib/ncbi_base64.h
  /usr/local/include/ncbi-tools++/corelib/ncbi_limits.h
  /usr/local/include/ncbi-tools++/corelib/ncbi_strings.h
  /usr/local/include/ncbi-tools++/corelib/ncbiatomic.h
  /usr/local/include/ncbi-tools++/corelib/ncbicfg.h
  /usr/local/include/ncbi-tools++/corelib/ncbifloat.h
  /usr/local/include/ncbi-tools++/corelib/ncbitype.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/odbcinst.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/sql.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/sqlext.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/sqlfront.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/sqlspi.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/sqltypes.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/sqlucode.h
  /usr/local/include/ncbi-tools++/dbapi/driver/odbc/unix_odbc/unixodbc_conf.h
  /usr/local/include/ncbi-tools++/ncbi_source_ver.h
  /usr/local/include/ncbi-tools++/ncbiconf.h
  /usr/local/include/ncbi-tools++/objects/gbproj/gbproj_export.h
  /usr/local/include/ncbi-tools++/objects/trackmgr/trackmgr_export.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/cache/reader_cache_params.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/gbloader_params.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/gicache/reader_gicache_params.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/id1/reader_id1_params.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/id2/reader_id2_params.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/reader_params.h
  /usr/local/include/ncbi-tools++/objtools/data_loaders/genbank/reader_service_params.h
  /usr/local/include/ncbi-tools++/util/bitset/bm.h
  /usr/local/include/ncbi-tools++/util/bitset/bmalgo.h
  /usr/local/include/ncbi-tools++/util/bitset/bmalgo_impl.h
  /usr/local/include/ncbi-tools++/util/bitset/bmalloc.h
  /usr/local/include/ncbi-tools++/util/bitset/bmblocks.h
  /usr/local/include/ncbi-tools++/util/bitset/bmconst.h
  /usr/local/include/ncbi-tools++/util/bitset/bmdbg.h
  /usr/local/include/ncbi-tools++/util/bitset/bmdef.h
  /usr/local/include/ncbi-tools++/util/bitset/bmfunc.h
  /usr/local/include/ncbi-tools++/util/bitset/bmfwd.h
  /usr/local/include/ncbi-tools++/util/bitset/bmgamma.h
  /usr/local/include/ncbi-tools++/util/bitset/bmrandom.h
  /usr/local/include/ncbi-tools++/util/bitset/bmserial.h
  /usr/local/include/ncbi-tools++/util/bitset/bmsse2.h
  /usr/local/include/ncbi-tools++/util/bitset/bmsse4.h
  /usr/local/include/ncbi-tools++/util/bitset/bmsse_util.h
  /usr/local/include/ncbi-tools++/util/bitset/bmtrans.h
  /usr/local/include/ncbi-tools++/util/bitset/bmundef.h
  /usr/local/include/ncbi-tools++/util/bitset/bmutil.h
  /usr/local/include/ncbi-tools++/util/bitset/bmvmin.h
  /usr/local/include/ncbi-tools++/util/bitset/encoding.h
  /usr/local/include/ncbi-tools++/util/compress/bzip2/bzlib.h
  /usr/local/include/ncbi-tools++/util/compress/zlib/zconf.h
  /usr/local/include/ncbi-tools++/util/compress/zlib/zlib.h
  /usr/local/include/ncbi-tools++/util/compress/zlib/zutil.h
  /usr/local/include/ncbi-tools++/util/creaders/alnread.h
  /usr/local/include/ncbi-tools++/util/creaders/creaders_export.h
  /usr/local/include/ncbi-tools++/util/math/miscmath.h
  /usr/local/include/ncbi-tools++/util/miscmath.h
  /usr/local/include/ncbi-tools++/util/regexp/pcre.h
  /usr/local/include/ncbi-tools++/util/regexp/pcrecpp.h
  /usr/local/include/ncbi-tools++/util/regexp/pcrecpparg.h
  /usr/local/include/ncbi-tools++/util/regexp/pcreposix.h
  /usr/local/include/ncbi-tools++/util/tables/raw_scoremat.h
  /usr/local/include/ncbi-tools++/util/tables/tables_export.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libaccess.a
  /usr/local/lib/libalign_format.a
  /usr/local/lib/libbiblio.a
  /usr/local/lib/libbiotree.a
  /usr/local/lib/libblast.a
  /usr/local/lib/libblast_app_util.a
  /usr/local/lib/libblast_services.a
  /usr/local/lib/libblastdb.a
  /usr/local/lib/libblastdb_format.a
  /usr/local/lib/libblastinput.a
  /usr/local/lib/libblastxml.a
  /usr/local/lib/libblastxml2.a
  /usr/local/lib/libcdd.a
  /usr/local/lib/libcn3d.a
  /usr/local/lib/libcomposition_adjustment.a
  /usr/local/lib/libconnect.a
  /usr/local/lib/libconnssl.a
  /usr/local/lib/libcreaders.a
  /usr/local/lib/libdbapi.a
  /usr/local/lib/libdbapi_driver.a
  /usr/local/lib/libdocsum.a
  /usr/local/lib/libentrez2.a
  /usr/local/lib/libentrez2cli.a
  /usr/local/lib/libentrezgene.a
  /usr/local/lib/libfeatdef.a
  /usr/local/lib/libgbproj.a
  /usr/local/lib/libgbseq.a
  /usr/local/lib/libgencoll_client.a
  /usr/local/lib/libgene_info.a
  /usr/local/lib/libgeneral.a
  /usr/local/lib/libgenesbyloc.a
  /usr/local/lib/libgenome_collection.a
  /usr/local/lib/libhomologene.a
  /usr/local/lib/libid1.a
  /usr/local/lib/libid1cli.a
  /usr/local/lib/libid2.a
  /usr/local/lib/libid2_split.a
  /usr/local/lib/libid2cli.a
  /usr/local/lib/libigblast.a
  /usr/local/lib/libinsdseq.a
  /usr/local/lib/libmacro.a
  /usr/local/lib/libmedlars.a
  /usr/local/lib/libmedline.a
  /usr/local/lib/libmim.a
  /usr/local/lib/libmla.a
  /usr/local/lib/libmlacli.a
  /usr/local/lib/libmmdb.a
  /usr/local/lib/libncbi_xblobstorage_netcache.a
  /usr/local/lib/libncbi_xcache_dbapi.a
  /usr/local/lib/libncbi_xcache_netcache.a
  /usr/local/lib/libncbi_xloader_blastdb.a
  /usr/local/lib/libncbi_xloader_blastdb_rmt.a
  /usr/local/lib/libncbi_xloader_genbank.a
  /usr/local/lib/libncbi_xreader.a
  /usr/local/lib/libncbi_xreader_cache.a
  /usr/local/lib/libncbi_xreader_id1.a
  /usr/local/lib/libncbi_xreader_id2.a
  /usr/local/lib/libncbimime.a
  /usr/local/lib/libobjcoords.a
  /usr/local/lib/libobjprt.a
  /usr/local/lib/libomssa.a
  /usr/local/lib/libpcassay.a
  /usr/local/lib/libpcsubstance.a
  /usr/local/lib/libproj.a
  /usr/local/lib/libpub.a
  /usr/local/lib/libpubmed.a
  /usr/local/lib/libregexp.a
  /usr/local/lib/libremap.a
  /usr/local/lib/libremapcli.a
  /usr/local/lib/libscoremat.a
  /usr/local/lib/libseq.a
  /usr/local/lib/libseqcode.a
  /usr/local/lib/libseqdb.a
  /usr/local/lib/libseqedit.a
  /usr/local/lib/libseqmasks_io.a
  /usr/local/lib/libseqset.a
  /usr/local/lib/libseqsplit.a
  /usr/local/lib/libseqtest.a
  /usr/local/lib/libsequtil.a
  /usr/local/lib/libsubmit.a
  /usr/local/lib/libtables.a
  /usr/local/lib/libtaxon1.a
  /usr/local/lib/libtaxon3.a
  /usr/local/lib/libtest_mt.a
  /usr/local/lib/libtinyseq.a
  /usr/local/lib/libtrackmgr.a
  /usr/local/lib/libtrackmgrcli.a
  /usr/local/lib/libvalerr.a
  /usr/local/lib/libvalid.a
  /usr/local/lib/libvariation.a
  /usr/local/lib/libvarrep.a
  /usr/local/lib/libwritedb.a
  /usr/local/lib/libxalgoblastdbindex.a
  /usr/local/lib/libxalgodustmask.a
  /usr/local/lib/libxalgosegmask.a
  /usr/local/lib/libxalgowinmask.a
  /usr/local/lib/libxalnmgr.a
  /usr/local/lib/libxblast.a
  /usr/local/lib/libxblastformat.a
  /usr/local/lib/libxcgi.a
  /usr/local/lib/libxcleanup.a
  /usr/local/lib/libxcompress.a
  /usr/local/lib/libxconnect.a
  /usr/local/lib/libxconnserv.a
  /usr/local/lib/libxcser.a
  /usr/local/lib/libxfcgi.a
  /usr/local/lib/libxformat.a
  /usr/local/lib/libxhtml.a
  /usr/local/lib/libxncbi.a
  /usr/local/lib/libxnetblast.a
  /usr/local/lib/libxnetblastcli.a
  /usr/local/lib/libxobjedit.a
  /usr/local/lib/libxobjmgr.a
  /usr/local/lib/libxobjread.a
  /usr/local/lib/libxobjreadex.a
  /usr/local/lib/libxobjsimple.a
  /usr/local/lib/libxobjutil.a
  /usr/local/lib/libxregexp.a
  /usr/local/lib/libxregexp_template_tester.a
  /usr/local/lib/libxser.a
  /usr/local/lib/libxthrserv.a
  /usr/local/lib/libxutil.a
  /usr/local/lib/libxxconnect.a
#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 792bb6de6d6e131fb334887b8375943555a6ccb9
Core tap last commit: 29 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

If anyone could help me I would be very grateful.

**Comment by iMichka** [comment]
Hi. I do not know why you are talking about blast 2.6.0, we only deliver 2.5.0. And I think 2.6.0 is not out yet.

I think I had already had this error; which was fixed with that patch, after a discussion with the blast developers:
https://github.com/Homebrew/homebrew-science/blob/master/blast.rb#L36-L40

I am not sure why/where you are running "sudo make install"; this is not a command that is related to homebrew.

**Comment by storer1017** [comment]
@iMichka 2.6.0 says that it's out based on the RepeatMasker page. I used the patch, and I still got this error.

**Comment by iMichka** [comment]
I didn't see the version update. I ran the installation of 2.6.0 locally, and it fails (without the patch):

> ==> make install
if test -d /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then \
	    /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j install-gbench; \
	else \
	    /Applications/Xcode.app/Contents/Developer/usr/bin/make - --jobserver-fds=3,4 -j install-toolkit; \
	fi
/bin/rm -rf /usr/local/Cellar/blast/2.6.0/include/ncbi-tools++
/usr/bin/install -c -d /usr/local/Cellar/blast/2.6.0/bin /usr/local/Cellar/blast/2.6.0/libexec /usr/local/Cellar/blast/2.6.0/include/ncbi-tools++
/usr/bin/install -c /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/* /usr/local/Cellar/blast/2.6.0/bin
/usr/bin/install -c -m 644 /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/*.* /usr/local/Cellar/blast/2.6.0/libexec
if test -d /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi; then \
	    cp -pPR /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi /usr/local/Cellar/blast/2.6.0/libexec/; \
	fi
rm -f /usr/local/Cellar/blast/2.6.0/libexec/lib*-static.a
cd /usr/local/Cellar/blast/2.6.0/libexec  && \
	    for x in *.a; do \
	        /bin/ln -s "$x" "`/usr/bin/basename \"$x\" .a`-static.a"; \
	    done
cd /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/include && find * -name CVS -prune -o -print |\
            cpio -pd /usr/local/Cellar/blast/2.6.0/include/ncbi-tools++
51192 blocks
/usr/bin/install -c -m 644 /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/* /usr/local/Cellar/blast/2.6.0/include/ncbi-tools++
install: /private/tmp/blast-20170213-1212-9hor4b/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/common: Inappropriate file type or format
make[1]: *** [install-toolkit] Error 71
make: *** [install] Error 2

This is the same error we had when updating to 2.5.0, so they probably did not merge the patch to 2.6.0. I am rebuilding with the patch to see if there is a difference in the error message.

**Comment by iMichka** [comment]
Seems the patch is still needed. I opened a PR with the updated version: #5134

Once the bottles are built I'll merge it.

**Comment by iMichka** [comment]
Blast has been upgraded to 2.6.0. Closing this. Please open a new bug if you still encounter problems. Thanks.
