### ISSUE TITLE
Opencv3 contrib installation problem

### ISSUE THREAD

**Issue by lasuomela** [Homebrew/homebrew-science#5128]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
None
#### Brief summary of issue:
The installation of opencv3 with the contributed parts (--with-contrib) seems to get stuck in the "make" phase:

Lauri-MBP-2:~ Lauri$ brew install opencv3 --with-contrib
==> Installing opencv3 from homebrew/science
==> Downloading https://github.com/opencv/opencv/archive/3.2.0.tar.gz
Already downloaded: /Users/Lauri/Library/Caches/Homebrew/opencv3-3.2.0.tar.gz
==> Downloading https://github.com/opencv/opencv_contrib/archive/3.2.0.tar.gz
Already downloaded: /Users/Lauri/Library/Caches/Homebrew/opencv3--contrib-3.2.0.tar.gz
==> Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/81a6760
Already downloaded: /Users/Lauri/Library/Caches/Homebrew/opencv3--icv-macosx-20151201.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make

I've been letting the script run for an hour but according to gist log nothing seems to be happening (as it's not being altered anymore). Adding "--HEADS" doesn't seem to matter. The installation of opencv3 without the contributions seems to work fine. Any help would be appreciated!
#### The complete command that you issued:
brew install opencv3 --with-contrib
#### Gist with output of `brew doctor`:
arning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
#### Link output by `brew gist-logs <formula>`:

Section of the gist-log where install seems to freeze on:

clang++ called with: -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -mf16c -Wno-unused-function -Wno-overloaded-virtual -Wno-unused-private-field -DNDEBUG -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -bundle -Wl,-headerpad_max_install_names -undefined dynamic_lookup -o ../../lib/cv2.so CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o -Wl,-rpath,/tmp/opencv3-20170213-95692-1miyorn/opencv-3.2.0/macbuild/lib ../../lib/libopencv_reg.3.2.0.dylib ../../lib/libopencv_surface_matching.3.2.0.dylib ../../lib/libopencv_fuzzy.3.2.0.dylib ../../lib/libopencv_superres.3.2.0.dylib ../../lib/libopencv_xobjdetect.3.2.0.dylib ../../lib/libopencv_xphoto.3.2.0.dylib ../../lib/libopencv_bgsegm.3.2.0.dylib ../../lib/libopencv_bioinspired.3.2.0.dylib ../../lib/libopencv_dpm.3.2.0.dylib ../../lib/libopencv_line_descriptor.3.2.0.dylib ../../lib/libopencv_saliency.3.2.0.dylib ../../lib/libopencv_ccalib.3.2.0.dylib ../../lib/libopencv_tracking.3.2.0.dylib ../../lib/libopencv_videostab.3.2.0.dylib ../../lib/libopencv_aruco.3.2.0.dylib ../../lib/libopencv_optflow.3.2.0.dylib ../../lib/libopencv_stitching.3.2.0.dylib ../../lib/libopencv_structured_light.3.2.0.dylib ../../lib/libopencv_dnn.3.2.0.dylib ../../lib/libopencv_plot.3.2.0.dylib ../../lib/libopencv_datasets.3.2.0.dylib ../../lib/libopencv_face.3.2.0.dylib ../../lib/libopencv_text.3.2.0.dylib ../../lib/libopencv_photo.3.2.0.dylib ../../lib/libopencv_ximgproc.3.2.0.dylib ../../lib/libopencv_objdetect.3.2.0.dylib ../../lib/libopencv_xfeatures2d.3.2.0.dylib ../../lib/libopencv_shape.3.2.0.dylib ../../lib/libopencv_video.3.2.0.dylib ../../lib/libopencv_phase_unwrapping.3.2.0.dylib ../../lib/libopencv_rgbd.3.2.0.dylib ../../lib/libopencv_calib3d.3.2.0.dylib ../../lib/libopencv_features2d.3.2.0.dylib ../../lib/libopencv_flann.3.2.0.dylib ../../lib/libopencv_ml.3.2.0.dylib ../../lib/libopencv_highgui.3.2.0.dylib ../../lib/libopencv_videoio.3.2.0.dylib ../../lib/libopencv_imgcodecs.3.2.0.dylib ../../lib/libopencv_imgproc.3.2.0.dylib ../../lib/libopencv_core.3.2.0.dylib
superenv removed:  -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
superenv executed: clang++ -pipe -w -Os -march=native -fsigned-char -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -mf16c -Wno-unused-function -Wno-overloaded-virtual -Wno-unused-private-field -DNDEBUG -DNDEBUG -bundle -Wl,-headerpad_max_install_names -undefined dynamic_lookup -o ../../lib/cv2.so CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o -Wl,-rpath,/tmp/opencv3-20170213-95692-1miyorn/opencv-3.2.0/macbuild/lib ../../lib/libopencv_reg.3.2.0.dylib ../../lib/libopencv_surface_matching.3.2.0.dylib ../../lib/libopencv_fuzzy.3.2.0.dylib ../../lib/libopencv_superres.3.2.0.dylib ../../lib/libopencv_xobjdetect.3.2.0.dylib ../../lib/libopencv_xphoto.3.2.0.dylib ../../lib/libopencv_bgsegm.3.2.0.dylib ../../lib/libopencv_bioinspired.3.2.0.dylib ../../lib/libopencv_dpm.3.2.0.dylib ../../lib/libopencv_line_descriptor.3.2.0.dylib ../../lib/libopencv_saliency.3.2.0.dylib ../../lib/libopencv_ccalib.3.2.0.dylib ../../lib/libopencv_tracking.3.2.0.dylib ../../lib/libopencv_videostab.3.2.0.dylib ../../lib/libopencv_aruco.3.2.0.dylib ../../lib/libopencv_optflow.3.2.0.dylib ../../lib/libopencv_stitching.3.2.0.dylib ../../lib/libopencv_structured_light.3.2.0.dylib ../../lib/libopencv_dnn.3.2.0.dylib ../../lib/libopencv_plot.3.2.0.dylib ../../lib/libopencv_datasets.3.2.0.dylib ../../lib/libopencv_face.3.2.0.dylib ../../lib/libopencv_text.3.2.0.dylib ../../lib/libopencv_photo.3.2.0.dylib ../../lib/libopencv_ximgproc.3.2.0.dylib ../../lib/libopencv_objdetect.3.2.0.dylib ../../lib/libopencv_xfeatures2d.3.2.0.dylib ../../lib/libopencv_shape.3.2.0.dylib ../../lib/libopencv_video.3.2.0.dylib ../../lib/libopencv_phase_unwrapping.3.2.0.dylib ../../lib/libopencv_rgbd.3.2.0.dylib ../../lib/libopencv_calib3d.3.2.0.dylib ../../lib/libopencv_features2d.3.2.0.dylib ../../lib/libopencv_flann.3.2.0.dylib ../../lib/libopencv_ml.3.2.0.dylib ../../lib/libopencv_highgui.3.2.0.dylib ../../lib/libopencv_videoio.3.2.0.dylib ../../lib/libopencv_imgcodecs.3.2.0.dylib ../../lib/libopencv_imgproc.3.2.0.dylib ../../lib/libopencv_core.3.2.0.dylib -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 04588ec56e0e4cc8e438b1176bca6b28602b0c1e
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
Unfortunately I wasn't able to reproduce this issue locally. I don't really see anything that would suggest a systematic problem, it might just take a really long time to compile or was a transient, one-off error. Thanks for reporting the issue but without being able to reproduce this I'm not sure if there's anything we can do about it.
