### ISSUE TITLE
netcdf error

### ISSUE THREAD

**Issue by rojinsafavi** [Homebrew/homebrew-science#5139]
### Indicate troubleshooting steps taken

- [y ] Ran `brew update` and retried your prior step?
- [ y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [y ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
I'm having problem installing netcdf on our linux server

brew install netcdf

Last 15 lines from /soe/rojinsafavi/.cache/Homebrew/Logs/netcdf/12.make:

Making check in cxx
make[1]: Entering directory `/tmp/netcdf--cxx-compat-20170213-495-2342ru/netcdf-cxx-4.2/cxx'
make  nctst tst_failure 
make[2]: Entering directory `/tmp/netcdf--cxx-compat-20170213-495-2342ru/netcdf-cxx-4.2/cxx'
/soe/rojinsafavi/.linuxbrew/bin/g++-5 -DHAVE_CONFIG_H -I. -I..   -I/soe/rojinsafavi/.linuxbrew/Cellar/netcdf/4.4.1.1_3/include -isystem/soe/rojinsafavi/.linuxbrew/include  -Os -w -pipe -march=native -c -o nctst.o nctst.cpp
/bin/sh ../libtool --tag=CXX   --mode=link /soe/rojinsafavi/.linuxbrew/bin/g++-5  -Os -w -pipe -march=native -lnetcdf -L/soe/rojinsafavi/.linuxbrew/Cellar/netcdf/4.4.1.1_3/lib -L/soe/rojinsafavi/.linuxbrew/lib -Wl,--dynamic-linker=/soe/rojinsafavi/.linuxbrew/lib/ld.so -Wl,-rpath,/soe/rojinsafavi/.linuxbrew/lib -o nctst nctst.o ../cxx/libnetcdf_c++.la  -lnetcdf 
libtool: link: /soe/rojinsafavi/.linuxbrew/bin/g++-5 -Os -w -pipe -march=native -Wl,--dynamic-linker=/soe/rojinsafavi/.linuxbrew/lib/ld.so -Wl,-rpath -Wl,/soe/rojinsafavi/.linuxbrew/lib -o .libs/nctst nctst.o  -L/soe/rojinsafavi/.linuxbrew/Cellar/netcdf/4.4.1.1_3/lib -L/soe/rojinsafavi/.linuxbrew/lib ../cxx/.libs/libnetcdf_c++.so -lnetcdf -Wl,-rpath -Wl,/soe/rojinsafavi/.linuxbrew/Cellar/netcdf/4.4.1.1_3/lib
/soe/rojinsafavi/.linuxbrew/bin/ld: cannot find -lnetcdf
collect2: error: ld returned 1 exit status
make[2]: *** [nctst] Error 1
make[2]: Leaving directory `/tmp/netcdf--cxx-compat-20170213-495-2342ru/netcdf-cxx-4.2/cxx'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/netcdf--cxx-compat-20170213-495-2342ru/netcdf-cxx-4.2/cxx'
make: *** [check-recursive] Error 1

#### The complete command that you issued:

brew install netcdf

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
I could not reproduce this. Could you please provide:
`brew doctor`; `brew gist-logs netcdf`, `brew config`.
as asked by the issue template

**Comment by kaboroevich** [comment]
I'm having the same issue with the same error report. I made a workaround for my purposes (installing the R package [ncdf4](https://cran.r-project.org/web/packages/ncdf4/index.html)) by commenting out the `resource("cxx-compact").stage do` block in the bottle. The following is for when the error occurs.

**brew doctor**
Your system is ready to brew.

**brew gist-logs netcdf**
https://gist.github.com/10cfc120d7ef8ae6f11c4cea10847cf5

**brew config**
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 92bb61c506afd09388af2a391dd3f5998bdd4404
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 2fd7a2b0fdec4678adae3a10954121ea6b989133
Core tap last commit: 24 hours ago
HOMEBREW_PREFIX: /home/keith/.linuxbrew
HOMEBREW_REPOSITORY: /home/keith/.linuxbrew
HOMEBREW_CELLAR: /home/keith/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: single-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648 => /home/keith/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.12.0 => /home/keith/.linuxbrew/bin/git
Perl: /usr/bin/perl
Python: /home/keith/.linuxbrew/bin/python => /home/keith/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /home/keith/.linuxbrew/bin/ruby => /home/keith/.linuxbrew/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_112
Kernel: Linux 2.6.32-642.15.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.6 (Final)
Codename: Final
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: 20170115

**Comment by iMichka** [comment]
The netcdf formula was moved to homebrew-core. This is a Linux issue, and it is not clear to me what is going on. If you still encounter problems, please open an issue on linuxbrew-core, so that we can try to help you there. Thanks.
