### ISSUE TITLE
Lammps openmpi error

### ISSUE THREAD

**Issue by allanavila** [Homebrew/homebrew-science#5155]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
[Allans-MacBook-Pro.local:17265] [[377,0],0] ORTE_ERROR_LOG: Bad parameter in file orted/pmix/pmix_server.c at line 262
[Allans-MacBook-Pro.local:17265] [[377,0],0] ORTE_ERROR_LOG: Bad parameter in file ess_hnp_module.c at line 666
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  pmix server init failed
  --> Returned value Bad parameter (-5) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[Allans-MacBook-Pro.local:17264] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 575
[Allans-MacBook-Pro.local:17264] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 165
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[Allans-MacBook-Pro.local:17264] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

#### Output of `brew config`:HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: a74b7ade66e340c55b3bea7b6226fa68a311b4ce
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 409001022e0f10ac3400000a502a7bea0fbedfa8
Core tap last commit: 14 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
Please fill out the missing information (brew doctor, brew gist-logs, brew config). Thanks

**Comment by allanavila** [comment]
@iMichka thank you for helping me. I am new to all of this terminal language and hope I have filled in what is missing correctly for the (brew doctor, and brew config).

However I am unsure what to put for the brew gist logs

**Comment by johanzhuohan** [comment]
I have an exactly the same issue. brew test lammps -v runs completely well. but I cannot run executable "lammps".

**Comment by iMichka** [comment]
I am not a lammps specialist, so I have no clue what is going on.

Could you try: `brew install lammps -s`. It will recompile from source, linking against the latest libraries, so that we can exclude that is got broken due to some updated openmpi or whatever other dependency.

What is the `body.in` file? Could I get it so I can test this locally? Is it small enough to be added to the test?

**Comment by apetri** [comment]
It might be a problem with open MPI on MacOS Sierra: https://www.open-mpi.org/faq/?category=osx
The quick fix is shorten the name of the open MPI temp directory:

export TMPDIR=/tmp

**Comment by iMichka** [comment]
@allanavila Please test `brew install lammps -s`, and also the hint given by @apetri.

Someone could also maybe report this upstream (https://github.com/lammps/lammps) and try to get help there. We are only package managers, and for us the package builds and installs, and the tests runs. So someone will have to debug this, but we do rely on our users to give us a hand for those tricky corner cases.

**Comment by allanavila** [comment]
Hey everyone,
I apologize for the delay in my response, I have been ill.
Update: the problem is fixed I simply had Homebrew install open mpi again and there was no issue when using lammps.

However, I completely agree @apetri. It was an open mpi-mac os problem and if the homebrew reinstall had not worked I am confident your suggestion would have also fixed the problem.

@iMichka I apologize for posting this lammps issue here, I am new to github and the homebrew community. You have been very helpful, though.

Thanks Everyone
Allan

**Comment by iMichka** [comment]
No problem. When you said you re-installed `openmpi`, did you just `brew uninstall` and `brew install`, and used the bottles, or did you build openmpi from source (using the `-s` flag). Just to know the details if this was a one-off problem, or if we should rebuild openmpi on our side too.

**Comment by allanavila** [comment]
no uninstall, no -s, just did brew install openmpi.

**Comment by iMichka** [comment]
So, initial problem fixed by reinstalling openmpi. Not sure what the exact problem was. If somebody has the same problem we may need to invest more time to investigate this.

**Comment by aadrych** [comment]
I am having the same problem as this but even with uninstalling lammps and openmpi and reinstalling I get the same error. 
I also found that the option of building lammps with mpi support no longer exists. I get the error 
homebrew/science/lammps: this formula has no --with-mpi option so it will be ignored! which is not the same as the lammps download page. 
I can get it to work temporarily using the export TMPDIR=/tmp command but fails if I try to use again in another directory. 
Could anyone suggest a way for me to fix this please? 
I only have el-captain at the moment so I'm not sure if there has been a cross over between the os sierra lammps tap and the el captain and so it's now getting confused?
