### ISSUE TITLE
matplotlib: resource numpy unnecessary

### ISSUE THREAD

**Issue by kyungminlee** [Homebrew/homebrew-science#5160]
Resource numpy at in `matplotlib` formula unnecessary. ([matplotlib.rb#L105](https://github.com/Homebrew/homebrew-science/blame/master/matplotlib.rb#L105))
`depends_on "numpy"` at [matplotlib.rb#L68](https://github.com/Homebrew/homebrew-science/blame/master/matplotlib.rb#L68) should be sufficient.

**Comment by ilovezfs** [comment]
Sometimes resource blocks are used, and sometimes formula dependencies are used. Feel free to open pull request.
