### ISSUE TITLE
Matplotlib –with-python3 doesn’t compile (because of qhull)

### ISSUE THREAD

**Issue by metalbobinou** [Homebrew/homebrew-science#5175]
Hello,

I have an issue with matplotlib compiling with the option "--with-python3".
I opened a topic on brew.sh, but it seems more appropriate to post here 
(here is the original topic : [http://discourse.brew.sh/t/matplotlib-with-python3-doesnt-compile-because-of-qhull/638](url) )

So, I want to use matplotlib with python36.
When I type :

> brew install homebrew/science/matplotlib

The installation works well, but, matplot only works for python27 (obviously).

However, when I type :

> brew install homebrew/science/matplotlib --with-python3

Multiple packages are downloaded and compile, and one is in failure.
I keep having this error :

> src/qhull_wrap.c:10:10: fatal error: 'qhull/qhull_a.h' file not found
> #include "qhull/qhull_a.h"
>          ^
> 1 error generated.
> error: command 'clang' failed with exit status 1

I tried to install qhull, but nothing changed.
It seems matplotlib for python3 is having an issue with an include from its own qhull.
(to be exact, it appears during the build of delaunay curves "creating build/temp.macosx-10.12-intel-2.7/lib/matplotlib/delaunay" )

Am I doing something wrong ?

Thank you,

**Comment by iMichka** [comment]
Hi. Thanks for reporting. You should have filled out the issue template; because there is a lot of information missing.

Especially `brew gist-logs`; `brew-doctor` and `brew config` would help debug this.

**Comment by metalbobinou** [comment]
Ok
And to precise (before I take a "you didn't installed it in the right path !!1!"), I was able to recompile gcc (with gfortran) because of "numpy --with-python3" dependency (and also "scipy --with-python3" and "boost-python --with-python3") and make all of them work correctly.
And some previous files of matplotlib were also able to compile. So I don't think the path change is the real issue.
(I'm using a software that can't run without the python of brew... the software works correctly for now, except the final curves drawing that depend on matplotlib)

The gist-logs :
https://gist.github.com/18799a65afa73b5fbe1c6e9f8c69a335

Here is brew config :
> $ ./brew config
> HOMEBREW_VERSION: 1.1.10
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
> Last commit: 8 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 658f06c1ab01686889b277d5db5a99a5f93d0f93
> Core tap last commit: 72 minutes ago
> HOMEBREW_PREFIX: /Users/metalman/MyBrew/homebrew
> HOMEBREW_REPOSITORY: /Users/metalman/MyBrew/homebrew
> HOMEBREW_CELLAR: /Users/metalman/MyBrew/homebrew/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: quad-core 64-bit broadwell
> Homebrew Ruby: 2.0.0-p648
> Clang: 8.0 build 800
> Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Perl: /opt/local/bin/perl => /opt/local/bin/perl5.24
> Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
> Java: 1.8.0_112
> macOS: 10.12.3-x86_64
> Xcode: 8.2.1
> CLT: 8.2.0.0.1.1480973914
> X11: 2.7.11_rc2 => /opt/X11
> MacPorts/Fink: /opt/local/bin/port



./brew doctor :
> $ ./brew doctor
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
>
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
>
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
>  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
>  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
>  /opt/local/bin/cob-config
>  /opt/local/bin/curl-config
>  /opt/local/bin/freetype-config
>  /opt/local/bin/icu-config
>  /opt/local/bin/libpng-config
>  /opt/local/bin/libpng16-config
>  /opt/local/bin/Magick++-config
>  /opt/local/bin/Magick-config
>  /opt/local/bin/MagickCore-config
>  /opt/local/bin/MagickWand-config
>  /opt/local/bin/ncurses6-config
>  /opt/local/bin/ncursesw6-config
>  /opt/local/bin/pcre-config
>  /opt/local/bin/pkg-config
>  /opt/local/bin/python2-config
>  /opt/local/bin/python2.7-config
>  /opt/local/bin/python3-config
>  /opt/local/bin/python3.5-config
>  /opt/local/bin/python3.5m-config
>  /opt/local/bin/python3m-config
>  /opt/local/bin/regina-config
>  /opt/local/bin/sdl-config
>  /opt/local/bin/sdl2-config
>  /opt/local/bin/Wand-config
>  /opt/local/bin/xml2-config
>  /opt/local/bin/xslt-config
>  /usr/local/bin/python-config
>  /usr/local/bin/python2-config
>  /usr/local/bin/python2.7-config
>
> Warning: Python is installed at /Library/Frameworks/Python.framework
>
> Homebrew only supports building against the System-provided Python or a
> brewed Python. In particular, Pythons installed to /Library can interfere
> with other software installs.
>
> Warning: You have MacPorts or Fink installed:
>  /opt/local/bin/port
>
> This can cause trouble. You don't have to uninstall them, but you may want to
> temporarily move them out of the way, e.g.
>
>   sudo mv /opt/local ~/macports
>
> Warning: Your Homebrew's prefix is not /usr/local.
> You can install Homebrew anywhere you want but some bottles (binary packages)
> can only be used with a /usr/local prefix and some formulae (packages)
> may not build correctly with a non-/usr/local prefix.
>
> Warning: Homebrew's bin was not found in your PATH.
> Consider setting the PATH for example like so
>  echo 'export PATH="/Users/metalman/MyBrew/homebrew/bin:$PATH"' >> ~/.bash_profile
>
> Warning: You have a non-Homebrew 'pkg-config' in your PATH:
>  /opt/local/bin/pkg-config
>
> `./configure` may have problems finding brew-installed packages using
> this other pkg-config.

**Comment by tdsmith** [comment]
We should instruct matplotlib not to look for a system qhull.

**Comment by tdsmith** [comment]
One way to do this is `inreplace "setupext.py", "has_include_file(include_dirs, 'qhull_a.h')", "False"`

**Comment by metalbobinou** [comment]
Hi again,

Is there a manipulation I should do to make it compile anyway ?
I don't know where to do the `inreplace` to ignore the system qhull.
