### ISSUE TITLE
Blast failed to build when installing PROKKA/blast --without-check

### ISSUE THREAD

**Issue by mbprentice** [Homebrew/homebrew-science#5195]
### Indicate troubleshooting steps taken

- [y] Ran `brew update` and retried your prior step?
- [y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [y] Checked that a similar issue hasn't already been filed?
- [y] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
Last 15 lines from /home/mike/.cache/Homebrew/Logs/blast/01.configure:
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc-4.8 accepts -g... yes
checking for /usr/bin/gcc-4.8 option to accept ISO C89... none needed
checking how to run the C preprocessor... /usr/bin/gcc-4.8 -E
checking for gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking whether we are using the GNU C++ compiler... no
checking whether /usr/bin/g++-4.8 accepts -g... no
configure: error: Do not know how to parse GCC version number ./src/build-system/configure: line 7577: /usr/bin/g++-4.8: No such file or directory

In the config.log compiling also failed with Homebrew gcc 5.3.0 

#### The complete command that you issued:

brew install prokka --HEAD
 and
brew install homebrew/science/blast --without-check
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
It looks like `gcc-4.8` exists on your machine but not `g++-4.8`. Can you confirm this with `which`?

**Comment by mbprentice** [comment]
looks like I have g++-5 in ~/.linuxbrew/bin and /usr/bin but no g++-4.8 in either . Thanks for your help
On 1 Mar 2017, at 11:10, Jonathan Chang <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like gcc-4.8 exists on your machine but not g++-4.8. Can you confirm this with which?

**Comment by mbprentice** [comment]
Hi
It looks like #4335 is the same problem:  absence of g++-4.8 in usr/bin on Ubuntu 16.04 when the installation won't use g++-5. The solution may be very simple but as a novice I would be very grateful for some advice

**Comment by jonchang** [comment]
Can you please retry with superenv e.g. `brew install prokka --env=super`

**Comment by mbprentice** [comment]
Thanks Jon, travelling at present, my next opportunity to try this is at the weekend

**Comment by mbprentice** [comment]
`brew install prokka --env=super` fails the same way as `brew install prokka --HEAD`
and `brew install homebrew/science/blast --without-check`

configure: error: Do not know how to parse GCC version number ./src/build-system/configure: line 7577: /usr/bin/g++-4.8: No such file or directory

**Comment by mbprentice** [comment]
Hi Jon

I tried your suggestion from #4306 to set compiler to `gcc-5` like
  `brew install --verbose blast --cc=gcc-5 -cxx=g++-5`

and it worked - thanks

**Comment by tseemann** [comment]
It seems the `blast` formula no longer has  a `--without-check` option?

```
brew info blast
homebrew/science/blast: stable 2.6.0 (bottled)
Basic Local Alignment Search Tool
http://blast.ncbi.nlm.nih.gov/
/home/linuxbrew/.linuxbrew/Cellar/blast/2.6.0 (27 files, 643.8MB) *
  Built from source
From: https://github.com/Homebrew/homebrew-science/blob/master/blast.rb
==> Dependencies
Build: gpatch ✔
Recommended: jpeg ✔, libpng ✔, pcre ✔
Optional: freetype ✔, gnutls ✔, hdf5 ✔, lzo ✘
==> Requirements
Required: python ✔
Optional: mysql ✔
==> Options
--with-dll
        Build dynamic libraries
--with-freetype
        Build with freetype support
--with-gnutls
        Build with gnutls support
--with-hdf5
        Build with hdf5 support
--with-lzo
        Build with lzo support
--with-mysql
        Build with mysql support
--with-static
        Build without static libraries and binaries
--without-jpeg
        Build without jpeg support
--without-libpng
        Build without libpng support
--without-pcre
        Build without pcre support
```

**Comment by cmdcolin** [comment]
Is blast in general having problems on linuxbrew?

Sorry if this is not related to issue at hand but is the current blast formula currently not accepting gcc 5? I'm trying with linuxbrew with ubuntu 16.04 gcc 5.4 

```
 ~ brew install blast
==> Installing blast from homebrew/science
Error: homebrew/science/blast cannot be built with any available compilers.
Install Clang or brew install gcc
```
