### ISSUE TITLE
graph-tool won't build after upgrading to python 3.6

### ISSUE THREAD

**Issue by guglielmo** [Homebrew/homebrew-science#5198]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
checking for Python include path... -I/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/include/python3.6m
checking for Python library path... -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib -lpython3.6m
checking for Python site-packages path... /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
checking python extra libraries... -undefined dynamic_lookup
checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.6/Python
checking consistency of all components of python development environment... no
configure: error: in `/private/tmp/graph-tool-20170228-28689-1tdkxhw/graph-tool-2.21/build-python3-3.6':
configure: error:
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LIBS environment variable.
  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

```

#### Brief summary of issue:
After updating brew packages on february 25th, python3 was upgraded from 3.5 to 3.6.
Trying to recompile graph-tool for this version generated this error.

#### The complete command that you issued:

```
brew install --build-from-source --with-python3 --without-python graph-tool

```
#### Gist with output of `brew doctor`:

```
Your system is ready to brew.
```

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/32a3aec6a9f8ba50b5aa0ff360cc3666

#### Output of `brew config`:

```
 $ brew config
HOMEBREW_VERSION: 1.1.10-410-g84fbcdc91
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 84fbcdc9130e002a1afc2eeb119b7b8c46bf0a13
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f9555ae02d9a7c1773ddbac4411cf5a3dbea870
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/gu/.rbenv/shims/ruby => /Users/gu/.rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_60, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by gfairchild** [comment]
I actually experienced the exact same issue. I've been preoccupied with #5181 (dealing with OpenMP errors), but when I tried to build using `brew install --with-python3`, I got the same error referring to the non-standard path. I also have Python 3.6 installed.

**Comment by ilovezfs** [comment]
Yeah I'm tempted to declare 2.21 a dud and downgrade.

**Comment by guglielmo** [comment]
@ilovezfs how could I do that now? :-)

**Comment by guglielmo** [comment]
Could not compile with 3.6, even using previous commit referring to 2.20 release: f8dee4a25ec1b783f4261707ff25e3551.

The error was the same.

I'm reverting to use python 2.7 for this project.

Is python3 at all supported? It does not seem to be tested in the CI.

**Comment by ilovezfs** [comment]
ci never tests non-default options

**Comment by mrksbrndt** [comment]
Hello everyone,

I struggled with this myself. After my findings there are two reasons why it fails:
1. Homebrewed python 3 returns a wrong value for distutils.sysconfig.get_config_var('LINKFORSHARED')
2. Automake's ax_python_devel.m4 (which is used by graph-tool) uses this deprecated var instead of invoking python3-config

I think the formula tries to fix this by overwriting the values (https://github.com/Homebrew/homebrew-science/blob/master/graph-tool.rb#L100)

If I change PYTHON_EXTRA_LDFLAGS to PYTHON_EXTRA_LIBS in the formula it works again.

But instead of incorporating both versions in one formula I think it would be a better idea to make two formulas, one for python 2.x and one for python 3.x. I only need the python 3.x version and have to wait for the python 2.x version to compile even so I won't use it.

I'd be happy to get some feedback about this and also if the fix is working for others

**Comment by ilovezfs** [comment]
@mrksbrndt mind opening a PR with your fix? Two formulae is probably not in the cards for the time being.

**Comment by ilovezfs** [comment]
@tdsmith is this a python3 formula bug?

**Comment by mrksbrndt** [comment]
@ilovezfs I just created a pull request.

**Comment by guglielmo** [comment]
@mrksbrndt the way I do it is through the --without-python option, that should compile with no support for python 2.

So: 
`brew install -v --build-from-source --with-python3 --without-python graph-tool`

**Comment by guglielmo** [comment]
@mrksbrndt I launched the compilation, and it is now compiling. To see if it will also work I'll have to wait a little (~60min on my machine).

**Comment by iMichka** [comment]
If it does not build for python2 and python3 at the same time, it would be great if we could add this to the formula:
```
if build.with?("python3") && build.with?("python")
        odie "graph-tool: Does not support building both python 2 and 3 wrappers"
```

**Comment by gfairchild** [comment]
Looks like building without Python isn't enough for me:

```
> brew install graph-tool --with-python3 --without-python
==> Installing graph-tool from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://downloads.skewed.de/graph-tool/graph-tool-2.21.tar.bz2
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/graph-tool/2.21 PYTHON=python3 PYTHON_LDFLAGS=-undefined dynamic_lookup PYTHON_EXTRA_LDFLAGS=-undefined dynamic_lookup --with-python-module-path=/usr/local/Cellar/graph-tool/2.21/lib/python3.6/site-packages
Last 15 lines from /Users/gfairchild/Library/Logs/Homebrew/graph-tool/01.configure:
checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.6/Python
checking consistency of all components of python development environment... no
configure: error: in `/private/tmp/graph-tool-20170301-24443-1oavs2k/graph-tool-2.21/build-python3-3.6':
configure: error:
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LIBS environment variable.
  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

See `config.log' for more details

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
graph-tool --with-openmp --with-python3 fails referencing chrono namespace https://github.com/Homebrew/homebrew-science/issues/5181
graph-tool: symbol binding failed https://github.com/Homebrew/homebrew-science/issues/3259
graph-tool won't build after upgrading to python 3.6 https://github.com/Homebrew/homebrew-science/issues/5198
graph-tool --with-python3 --with-openmp ignores python3, then fails https://github.com/Homebrew/homebrew-science/issues/4553
```

**Comment by guglielmo** [comment]
@gfairchild actually it seems to be working, at least as far as the --without-python option is concerned.

The error makes me think that you did not apply the patch mrksbrndt mentioned in his comment.

I report it here for your convenience: _change PYTHON_EXTRA_LDFLAGS to PYTHON_EXTRA_LIBS in the formula_.

That is at line 100 of `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/graph-tool.rb`.

**Comment by gfairchild** [comment]
Ah, you're exactly right! It appears to be building now. Sorry about that.

**Comment by iMichka** [comment]
I just merged the proposed patch: #5208

@gfairchild Please `brew update` and try to reinstall `graph-tool`, the patch should fix it for you.

I still need your opinion. Should we add these lines:
```
if build.with?("python3") && build.with?("python")
        odie "graph-tool: Does not support building both python 2 and 3 wrappers"
```

This forces people to use the `--without-python` flag if they are trying to build `--with-python3`. Just a safeguard so that no new issues are opened if somebody stumbles over this.

**Comment by gfairchild** [comment]
Updated, and it looks like `brew install graph-tool --with-python3 --without-python` is proceeding properly.

Regarding the Python 2/3 issue, can we either:

1. Fix the formula so that it compiles for both 2 and 3 or
1. Implement @mrksbrndt's suggestion of splitting the formula into two: one for Python 2 and one for Python 3.

I'm more in favor or option 1 since that's kind of more standard with the `--with-python3` and `--without-python` flags. What exactly is preventing this option from working?

**Comment by iMichka** [comment]
Two separate formula is double the work to maintain, and not so standard in the homebrew world. Especially for python2/3. So solution 1 it will be.

If we are not able to get both running, then my proposal for the error message would be the final solution. Not ideal but brings the least surprises.

**Comment by gfairchild** [comment]
I agree.

**Comment by gfairchild** [comment]
I'm trying to build with `brew install graph-tool --with-python3`, and I'll report back the errors I get so that we can start debugging.

**Comment by gfairchild** [comment]
Actually, everything just built just fine!

```
> brew install graph-tool --with-python3
==> Installing graph-tool from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://downloads.skewed.de/graph-tool/graph-tool-2.21.tar.bz2
Already downloaded: /Users/gfairchild/Library/Caches/Homebrew/graph-tool-2.21.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/graph-tool/2.21 PYTHON=python PYTHON_LDFLAGS=-undefined dynamic_lookup PYTHON_EXTRA_LIBS=-undefined dynamic_lookup --with-python-module-path=/usr/local/Cellar/graph-tool/2.21/lib/python2.7/site-packages
==> make install
==> ../configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/graph-tool/2.21 PYTHON=python3 PYTHON_LDFLAGS=-undefined dynamic_lookup PYTHON_EXTRA_LIBS=-undefined dynamic_lookup --with-python-module-path=/usr/local/Cellar/graph-tool/2.21/lib/python3.6/site-packages
==> make install
Warning: homebrew/science/graph-tool dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/graph-tool/2.21: 572 files, 656.9M, built in 72 minutes 17 seconds
```

However, I got a segfault when trying to run in Python 2:

```
> python
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from graph_tool.all import *
Segmentation fault: 11
```

I'm rebuilding a few things just to make sure everything built properly.
```

**Comment by tdsmith** [comment]
I don't believe `LINKFORSHARED` is the right variable to use for flags for building a Python extension module, so, no, there is no bug in the python3 formula. It is a deficiency of the graph-tool build system that we need to pass any extra flags at all.

**Comment by mrksbrndt** [comment]
@tdsmith Correct, `LINKFORSHARED` should not be used but autoconf still uses it which itself is used by many others. Nevertheless, the output of the homebrewed python 3 is very different compared to other versions. Just as a comparison:

Apple Python 2 (2.7.10):
```
-u _PyMac_Error /System/Library/Frameworks/Python.framework/Versions/2.7/Python
```

Homebrewed Python 2 (2.7.13):
```
-u _PyMac_Error /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python
```

Homebrewed Python 3 (3.6.0):
```
-Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.6/Python
```

The absolute path is missing. This has already been a problem in the past (https://trac.macports.org/ticket/39223).

**Comment by gfairchild** [comment]
Are there any graph-tools devs that are following this thread? If not, perhaps we should rope them in.

**Comment by tdsmith** [comment]
The difference between the python2 and python3 LINKFORSHARED happened upstream: https://bugs.python.org/issue3588

Hm, I did try to fix it once anyway: https://github.com/Homebrew/legacy-homebrew/issues/37923 -- and that code's still in the formula; I guess we should make it work.

**Comment by count0** [comment]
Upstream here. AFAIK `python3-config` will use LINKFORSHARED internally. Can anyone verify if `python3-config --ldflags` returns the correct flags?

**Comment by count0** [comment]
What do you get for `distutils.sysconfig.get_config_var("LINKFORSHARED")`?

**Comment by gfairchild** [comment]
Python 2.7:

```
> python
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("LINKFORSHARED")
'-u _PyMac_Error Python.framework/Versions/2.7/Python'
```

Python 3.6:

```
> python3
Python 3.6.0 (default, Mar  6 2017, 11:41:46)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("LINKFORSHARED")
'-Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.6/Python'
```

**Comment by count0** [comment]
Ok, so it seems that `LINKFORSHARED` is indeed broken. Strictly speaking, this is a Python bug, but we can fix graph-tool to use `python-config` instead. Please open an issue upstream in the graph-tool website, and it will be dealt with.

**Comment by gfairchild** [comment]
I'll do that shortly.

**Comment by gfairchild** [comment]
Done: https://git.skewed.de/count0/graph-tool/issues/377
