### ISSUE TITLE
lammps: MPI4PY module install

### ISSUE THREAD

**Issue by aadrych** [Homebrew/homebrew-science#5205]
Hi, 

I've used homebrew to install lammps on to my mac laptop in the hopes of using the python interface with lammps more easily. 
I do however need to use the mpirun command in lammps which I can't do using homebrew because I have been unable to install the MPI4PY module. 
When using brew install MPI4PY I get the error
Error: No available formula with the name "mpi4py" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
Even with the most up to date brew install. 

Please could someone suggest how I can get mpi4py in to homebrew to use with lammps please?

Thanks in advance

**Comment by jonchang** [comment]
We would probably accept a pull request that would add this formula. Please consult the [Formula Cookbook](http://docs.brew.sh/Formula-Cookbook.html) and [contributing guidelines](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md). The formula for `pillow` is a good example of how to build a Python library for Homebrew. Feel free to ping a maintainer if you need help with this.

**Comment by aadrych** [comment]
Hi, how come you have closed this thread ?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by aadrych** [comment]
It's not just the lack of MPI4PY that I'm confused about. The lammps documentation recommends that the module be built into the Lammps directory so that it has access to the same mpi library?

**Comment by jonchang** [comment]
It looks like lammps and mpi4py are separate packages, so they would need to be built as separate formula. I closed the issue because although this is not something we're actively working on, we would nevertheless welcome a pull request for it, per my previous message.

**Comment by aadrych** [comment]
Okay. Do you know how I can keep doing my work on the brew installed lammps whilst modifying another lammps directory to try and include mpi4py?
