### ISSUE TITLE
clonalframeml moved to GitHub

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/homebrew-science#5213]
clonalframeml is hosted at GitHub now. (https://github.com/xavierdidelot/ClonalFrameML)
How I can update the formulae correctly?

1. Add `url`
2. Add `sha256` after running `brew fetch clonalframeml --build-from-source`
3. Update `def install`

What's next? If have.

**Comment by iMichka** [comment]
Hi. We have a extensive documentation here on how to open a pull request, and some general rules to follow when doing so:
http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

If you have any specific questions; just ask, we can guide you through this.

**Comment by miguelarauj1o** [comment]
@iMichka 

``` bash
brew bump-formula-pr --url=https://github.com/xavierdidelot/ClonalFrameML/archive/v1.0.tar.gz --audit --strict clonalframeml
```

returns:

``` bash
==> replace "https://github.com/xavierdidelot/ClonalFrameML/archive/v1.0.tar.gz" with "https://github.com/xavierdidelot/ClonalFrameML/archive/v1.0.tar.gz"
==> replace "7b1a2f30e6b9fa629ad24c933930336d75a69ba1df51860113608247211cf546" with "7b1a2f30e6b9fa629ad24c933930336d75a69ba1df51860113608247211cf546"
Error: You probably need to bump this formula manually since the new version
and old version are both 1.0.
```

I made the required replaces.

But, I don't know how to fix the error.

**Comment by iMichka** [comment]
`brew bump-formula-pr` should be used if you bump the version number (for example from 1.0 to 1.1). This is not the case here, so you can not use it. You will need to do this manually, see the relevant section in the doc (`Create your pull request from a new branch`).

One important thing is that the 1.0 tag should tag the exact same commit as before, for consistency. But I see the sha256 of the file is the same, so this seems to be OK.

**Comment by tseemann** [comment]
I've asked them to make a new release:
https://github.com/xavierdidelot/ClonalFrameML/issues/50
