### ISSUE TITLE
VTK relase debug request.

### ISSUE THREAD

**Issue by gmrandazzo** [Homebrew/homebrew-science#5215]
Dear all,

i have a problem regarding the vtk library and qt5.7.
If i compile my software in relase mode -DCMAKE_BUILD_TYPE=Release, my applications crash with this output:
"QWidget: Must construct a QApplication before a QWidget"

Instead if i compile in Debug mode the applications working well... So.. I guess that the vtk bottle/source is just compiled under Debug mode and not release mode. Can i ask to add the possibility to have both? Debug and relase mode?

Just add the parameter -DCMAKE_BUILD_TYPE=RelWithDebInfo to vtk.rb.

Best regards,
GMR

**Comment by jonchang** [comment]
It's unusual that builds in release mode crash. Do you have a test case that we can look at? Also, have you reported this to the vtk developers?

**Comment by iMichka** [comment]
From what I see, we build with `-DCMAKE_BUILD_TYPE=Release` by default (because of `std_cmake_args`). This means that the bottles have been build in release mode.

**Comment by iMichka** [comment]
Please report this upstream. We can reopen this bug if this is a homebrew-specific packaging problem.
