### ISSUE TITLE
Formula should have a desc

### ISSUE THREAD

**Issue by harshnarang8** [Homebrew/homebrew-science#5225]
While running brew audit --strict t-coffee, I came across the following message, "Formula should have a description". Is it okay to browse the t-coffee website and use their description in the formula, and create a PR?

**Comment by iMichka** [comment]
Hi. I think this is not a problem at all, this is what we are doing for other formulas too. Maybe you will have to find your own description, as the number of characters is limited. Feel free to open a pull request for that.
