### ISSUE TITLE
fully scope test system calls

### ISSUE THREAD

**Issue by harshnarang8** [Homebrew/homebrew-science#5231]
While trying to fix a few audits, I've come across the following problem:
`fully scope test system calls e.g. system "#{bin}/velvetg"`
Can someone help point the direction on how to fix such problems?

**Comment by iMichka** [comment]
For ref, happened in #5227
`fully scope test shell_output calls e.g. shell_output "#{bin}/seqlogo"`

I think you need to write it like this: `shell_output("#{bin}/seqlogo -h 2>&1", 255)`. Could you please try again?

Wording of the error is weird, I'll have a look if I can improve that.

**Comment by iMichka** [comment]
I hope my hint helped. Closing here as this is more a question than a real issue.
