### ISSUE TITLE
lammps: Error in download

### ISSUE THREAD

**Issue by oa0107** [Homebrew/homebrew-science#5241]
Hello,

I am trying to learn LAMMPS but looks like my first step is not going smooth. I am using MAC OS and when I follow the download steps, I checked my installation as per the manual and I got the following:

Last login: Tue Mar  7 13:47:45 on console
dynamic-10-125-214-57:~ Omar$ brew test lammps -v 
Testing homebrew/science/lammps
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170307-1382-zvndow.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/lammps.rb -v
==> /usr/local/Cellar/lammps/2016.11.17/bin/lammps -in /usr/local/share/lammps/bench/in.lj
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Error: homebrew/science/lammps: failed
Failed executing: /usr/local/Cellar/lammps/2016.11.17/bin/lammps -in /usr/local/share/lammps/bench/in.lj
/usr/local/Homebrew/Library/Homebrew/formula.rb:1836:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1774:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1774:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/lammps.rb:241:in `block in <class:Lammps>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1673:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:884:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1672:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1666:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
dynamic-10-125-214-57:~ Omar$ 

Why is that error? Could anyone help me please?

Thank you,

Omar

**Comment by iMichka** [comment]
Hi. Please always fill out the issue template.

This is maybe related to #5155, but I am not sure.

We are only package managers, if you think we wrongly packaged lammps, please try to find out. But I do think this should be reported upstream first.

**Comment by iMichka** [comment]
Please double check if #5155 helps. If not, please report upstream. They are the most likely to help you with this problem. If you really think this is a homebrew bug, please open a new issue.

**Comment by oa0107** [comment]
@iMichka I apologize for posting here but I am totally new to this. I figured out what was the problem. For MAC OS, homebrew/science/lammps is automatically not linked when you download lammps but I figured it out.

**Comment by iMichka** [comment]
@oa0107 Thanks. Would there be any commands that we would need to execute during installation to help other people encountering the same problem?

**Comment by oa0107** [comment]
I just had to type:
> link homebrew/science/lammps
I know it is very easy step to figure out but I have zero experience with downloading from a MAC OS terminal this so I was proud of myself at some point.
I made sure after that if the download would have any issue:
> brew test lammps -v
and everything seems to work fine
Thanks

**Comment by iMichka** [comment]
At least it works for you, but you are not expected to call `link homebrew/science/lammps`. Maybe something got broken and this fixed it.

Just out of interest, could you post here:
- Gist with output of `brew doctor`
- Link output by `brew gist-logs lammps`
- Output of `brew config`

Trying to do some post-mortem analysis of the bug. But we may just leave it as-is as a one-off error due to some setup combination on your machine.

**Comment by oa0107** [comment]
dynamic-10-125-176-35:~ Omar$ brew doctor
Your system is ready to brew.
dynamic-10-125-176-35:~ Omar$ brew gist-logs lammps
https://gist.github.com/771c991b1f3809be89bba02c0f32f814
dynamic-10-125-176-35:~ Omar$ brew config
HOMEBREW_VERSION: 1.1.11-23-gb38c52f
ORIGIN: https://github.com/Homebrew/brew
HEAD: b38c52f930ad5736518dff54f135674347a4a222
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5bac5c4670ef8d357b7413914fc59e1deeed639
Core tap last commit: 20 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
dynamic-10-125-176-35:~ Omar$

**Comment by oa0107** [comment]
Again, thank you for your concern.
