### ISSUE TITLE
pcl_viewer bin not found after brew install pcl

### ISSUE THREAD

**Issue by changkaizhao** [Homebrew/homebrew-science#5245]
I `brew` install pcl ,but I check the folder `/usr/local/Celler/pcl/1.8/bin` there is no bin `pal_viewer`. I use Mac!

**Comment by adamwtow** [comment]
This is a repeat of: https://github.com/Homebrew/homebrew-science/issues/4437

**Comment by changkaizhao** [comment]
I copy `pcl_viewer` bin from `pcl_viewer.app` to `/usr/local/bin`  , now it works!

**Comment by jonchang** [comment]
@changkaizhao @adamwtow thanks for figuring this out! If you could open a pull request for this formula that adds a symlink to the `bin` directory that would be fantastic. Feel free to ping me if you need help with this.
