### ISSUE TITLE
Installing VTK with Python 3 bindings fails. 

### ISSUE THREAD

**Issue by talonchandler** [Homebrew/homebrew-science#5247]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?

#### Summary:

Installing vtk with python 3 bindings fails. Installing vtk with python 2 binding works fine. I'm using brewed python3.

The first fatal error (line 1487 of 02.make in the gist) says that Python.h could not be found. I'm confused because the preceding clang++ call uses the option -I/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/include/python3.6m 
which is where Python.h lives. 

Thanks for your help!

#### The complete command that you issued:

`brew install vtk --with-python3 --without-python`

#### Gist with output of `brew doctor`:

Your system is ready to brew. 

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/talonchandler/e7e6f4ac60cd351c32d40605473b8d12

#### Output of `brew config`:

HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 57a65b15d2eca77c35e5a9f2866360332786e416
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

**Comment by iMichka** [comment]
Thanks for reporting this. I confirm from the log files that the error is:
> /tmp/vtk-20170309-53160-noi1kj/VTK-7.1.0/Utilities/Python/vtkPython.h:80:10: fatal error: 'Python.h' file not found
#include <Python.h>

I'll try to recompile locally first and let you know what I found out. It's maybe due to the patch that I added to VTK, or any other reasons, but I know their cmake setup a little bit so there is good hope that I can get that fixed.

**Comment by iMichka** [comment]
First investigations show that:
- I vaguely remember having built 7.1.0 with python3 at one point, between now and July 2016, and it worked.
- removing the patch does not help, so the patch does not seem to be the problem
- building head is also broken (no need for the patch there)
- copy-pasting the cmake flags we pass and building manually from a repository outside of homebrew works, so this seems to be a homebrew specific bug.
- checking out hombre 1.1.8 makes it compile.

I am currently bisecting to find out what broke this.

**Comment by iMichka** [comment]
@MikeMcQuaid seems that reverting this: https://github.com/Homebrew/brew/pull/2211
fixes the problem.

**Comment by iMichka** [comment]
The gist log shows:
> superenv removed:  -I/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/include/python3.6m

**Comment by ilovezfs** [comment]
I'm having trouble reproducing this issue.

**Comment by iMichka** [comment]
@talonchandler Please try `brew upgrade`. There is a new python3 bottle. In fact homebrew should have made the upgrade for you (and for me), but it didn't. With the latest packages everything should work fine. We are investigating the problem, but at least you should be able to build for now (after `brew upgrade`).

**Comment by talonchandler** [comment]
@iMichka Excellent. The VTK installation worked. Thanks for maintaining!

**Comment by bastula** [comment]
This doesn't work again with Python 3.6.2 built from homebrew. Works fine with Python 2.7.13 from homebrew.

My build log gist: https://gist.github.com/bastula/997fdf989850bd991a4a94e2e77db389

**Comment by iMichka** [comment]
Please open a new issue for this in https://github.com/Homebrew/homebrew-core, and fill out the full issue template. Thanks.
