### ISSUE TITLE
protobuf-cpp-3.1.0.tar.gz Couldn't connect to server

### ISSUE THREAD

**Issue by mathslimin** [Homebrew/homebrew-science#5300]
hi protobuf-cpp-3.1.0.tar.gz is not exists
but protobuf-cpp-3.2.0.tar.gz is ok

CMake Error at cmake/OpenCVUtils.cmake:1081 (message):
  Failed to download v3.1.0/protobuf-cpp-3.1.0.tar.gz.  Status=7;"Couldn't
  connect to server"
Call Stack (most recent call first):
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:23 (ocv_download)
  opencv_contrib/modules/dnn/cmake/download_protobuf.cmake:51 (ocv_protobuf_download)
  opencv_contrib/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:30 (include)
  opencv_contrib/modules/dnn/CMakeLists.txt:38 (include)

**Comment by jonchang** [comment]
Hi @mathslimin, could you please [fill out the issue template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md) when filing issues. It helps us maintainers diagnose your problem. Feel free to open a new issue with the template filled out.
