### ISSUE TITLE
Bowtie2 2.3.0 installation error

### ISSUE THREAD

**Issue by s18692001** [Homebrew/homebrew-science#5302]
Hi there,

I'm using brew to install MetaPhlAn2 [https://bitbucket.org/biobakery/biobakery/wiki/metaphlan2](url)
which contains steps of Bowtie2 2.3.0 installation. It shows errors as following:

make install prefix=/home/yangj/.linuxbrew/Cellar/bowtie2/2.3.0
Last 15 lines from /home/yangj/.cache/Homebrew/Logs/bowtie2/01.make:
                 from aligner_seed2.h:101,
                 from aligner_driver.h:78,
                 from aligner_driver.cpp:20:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
In file included from ds.h:30:0,
                 from bowtie_main.cpp:25:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
make: *** [bowtie2-align-l] Error 1
In file included from ds.h:30:0,
                 from bowtie_main.cpp:25:
threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
compilation terminated.
make: *** [bowtie2-align-s] Error 1

What should I do to deal with this problem?

Thanks!

**Comment by jonchang** [comment]
Hi @s18692001, thanks for reporting this issue. In the future please be sure [fill out the issue template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md) so the maintainers can diagnose problems faster.

This will be fixed once https://github.com/Homebrew/homebrew-science/pull/5303 is merged. You may also want to contact the author of metaphlan2 as it seems like using TBB with bowtie2 will be the default going forward, and they should ensure that their software is compatible with that assumption.

**Comment by snijesh** [comment]
​sudo apt-get install libtbb-dev
​make
​
