### ISSUE TITLE
Paraview 5.3.0 does not create symlink in Applications folder

### ISSUE THREAD

**Issue by deOliveira-R** [Homebrew/homebrew-science#5314]
Brew update run twice returning "Already up-to-date"
Brew doctor returns "Your system is ready to brew"

"brew link paraview" gives:

Warning: Already linked: /usr/local/Cellar/paraview/5.3.0
To relink: brew unlink paraview && brew link paraview

If I execute "brew unlink paraview && brew link paraview"

Unlinking /usr/local/Cellar/paraview/5.3.0... 0 symlinks removed
Linking /usr/local/Cellar/paraview/5.3.0... 0 symlinks created

I think the installation of ParaView was supposed to create a symlink inside the Applications folder, or am I wrong?

Also, I think it was supposed to be named "ParaView" which is how some programs expect ParaView to be called and fail to locate it with a different name.

Could someone clarify this issue?

Thanks

**Comment by jonchang** [comment]
`brew linkapps` will do you what you want, but note that this will no longer be supported in Homebrew very soon (see below). At that point we will probably have to either migrate `paraview` to Homebrew/cask or come up with another acceptable solution.

    Unfortunately brew linkapps cannot behave nicely with e.g. Spotlight using
    either aliases or symlinks and Homebrew formulae do not build "proper" .app
    bundles that can be relocated. Instead, please consider using brew cask and
    migrate formulae using .apps to casks.
