### ISSUE TITLE
OpenCV3 fails to install on macOS with --c++11

### ISSUE THREAD

**Issue by starcolon** [Homebrew/homebrew-science#5329]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

When installing OpenCV3 with `--c++11` and having the latest **XCode developer tools v8 (2343)** installed, 
the compilation of the package fails. I used to install it when I was running Xcode developer v7 last year with exactly the same brew command and it was successful. 

#### The complete command that you issued:

```
brew install opencv3 --with-ffmpeg --without-numpy --without-test --with-contrib --c++11
```
> Please note that, removal of `c++11` argument works fine. But I do need a C++11 version of the library so I can't omit it.

#### Error message gist
https://gist.github.com/starcolon/755e985dfb7be5dfbafecedff09fc4d8

**Comment by iMichka** [comment]
You didn't fill out the full issue template. Especially there is information missing like `brew doctor`, `brew gist-logs <formula>`, `brew config`, which would help debug this.

I tested this locally and it building with these build options worked for me. So there is something different on your machine. Which we can only debug with all the full information. Please open a new issue with the required information.
