### ISSUE TITLE
Error in brew test lammps -v

### ISSUE THREAD

**Issue by maryamalq** [Homebrew/homebrew-science#5332]
So I followed the instruction posted in: http://lammps.sandia.gov/download.html#homebrew
to install lammps in mac OSX using Homebrew but when I reach to ` brew test lammps -v`
command I get an error: `AttributeError: 'lammps' object has no attribute 'lmp'
Error: homebrew/science/lammps: failed
`

the whole code is shown below: `brew test lammps -v
Testing homebrew/science/lammps
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170326-13649-jon6cw.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/lammps.rb -v
==> /usr/local/Cellar/lammps/2016.11.17/bin/lammps -in /usr/local/share/lammps/bench/in.lj
LAMMPS (17 Nov 2016)
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (33.5919 33.5919 33.5919)
  1 by 1 by 1 MPI processor grid
Created 32000 atoms
Neighbor list info ...
  1 neighbor list requests
  update every 20 steps, delay 0 steps, check no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 2.8
  ghost atom cutoff = 2.8
  binsize = 1.4, bins = 24 24 24
Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
Memory usage per processor = 8.21387 Mbytes
Step Temp E_pair E_mol TotEng Press 
       0         1.44   -6.7733681            0   -4.6134356   -5.0197073 
     100    0.7574531   -5.7585055            0   -4.6223613   0.20726105 
Loop time of 2.10478 on 1 procs for 100 steps with 32000 atoms

Performance: 20524.690 tau/day, 47.511 timesteps/s
98.8% CPU use with 1 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 1.7883     | 1.7883     | 1.7883     |   0.0 | 84.97
Neigh   | 0.24147    | 0.24147    | 0.24147    |   0.0 | 11.47
Comm    | 0.026662   | 0.026662   | 0.026662   |   0.0 |  1.27
Output  | 0.00014997 | 0.00014997 | 0.00014997 |   0.0 |  0.01
Modify  | 0.041604   | 0.041604   | 0.041604   |   0.0 |  1.98
Other   |            | 0.006554   |            |       |  0.31

Nlocal:    32000 ave 32000 max 32000 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Nghost:    19657 ave 19657 max 19657 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Neighs:    1.20283e+06 ave 1.20283e+06 max 1.20283e+06 min
Histogram: 1 0 0 0 0 0 0 0 0 0

Total # of neighbors = 1202833
Ave neighs/atom = 37.5885
Neighbor list builds = 5
Dangerous builds not checked
Total wall time: 0:00:02
==> python -c from lammps import lammps ; lammps().file('/usr/local/share/lammps/bench/in.lj')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/lammps.py", line 85, in __init__
    if not name: self.lib = CDLL(join(modpath,"liblammps.so"),RTLD_GLOBAL)
  File "/Users/maryam/anaconda/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python2.7/site-packages/liblammps.so, 10): Symbol not found: _PyCObject_FromVoidPtr
  Referenced from: /usr/local/lib/python2.7/site-packages/liblammps.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/liblammps.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lammps.py", line 89, in __init__
    if not name: self.lib = CDLL("liblammps.so",RTLD_GLOBAL)
  File "/Users/maryam/anaconda/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(liblammps.so, 10): Symbol not found: _PyCObject_FromVoidPtr
  Referenced from: /usr/local/lib/liblammps.so
  Expected in: flat namespace
 in /usr/local/lib/liblammps.so
Exception ignored in: <bound method lammps.__del__ of <lammps.lammps object at 0x106defb00>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/lammps.py", line 159, in __del__
    if self.lmp and self.opened:
AttributeError: 'lammps' object has no attribute 'lmp'
Error: homebrew/science/lammps: failed
Failed executing: python -c from\ lammps\ import\ lammps\ ;\ lammps().file('/usr/local/share/lammps/bench/in.lj')
/usr/local/Homebrew/Library/Homebrew/formula.rb:1836:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1774:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1774:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/lammps.rb:242:in `block in <class:Lammps>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1673:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:884:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1672:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1666:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'`
please help I appreciate any answer you give.

**Comment by iMichka** [comment]
A new version was just merged. Please update and test again. Thanks.

**Comment by iMichka** [comment]
Closing. Please open a new issue if you still have trouble with this. Thanks.
