### ISSUE TITLE
Error: No such file or directory - python3-config

### ISSUE THREAD

**Issue by olalonde** [Homebrew/homebrew-science#5344]
### Indicate troubleshooting steps taken

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x ] Checked that a similar issue hasn't already been filed?
- [ x] Looked up the software bug tracker if reporting a build error?
- [x ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

`Error: No such file or directory - python3-config`

#### Brief summary of issue:

OpenCV3 installation exits with an error during installation:

```
==> Cloning https://github.com/opencv/opencv_contrib.git
Cloning into '/Users/olalonde/Library/Caches/Homebrew/opencv3--contrib--git'...
remote: Counting objects: 2039, done.
remote: Compressing objects: 100% (1706/1706), done.
remote: Total 2039 (delta 406), reused 1353 (delta 224), pack-reused 0
Receiving objects: 100% (2039/2039), 48.68 MiB | 365.00 KiB/s, done.
Resolving deltas: 100% (406/406), done.
==> Checking out branch master
Error: No such file or directory - python3-config
```

Full log here: 
https://gist.github.com/71c9e458aad28d1239f59b9ab9f3e07a

#### The complete command that you issued:

```
brew install opencv3 --with-contrib --with-python3 --HEAD
```

#### Gist with output of `brew doctor`:

https://gist.github.com/8b7a57b3f22e6039a07b377da8f3fe4a

#### Output of `brew config`:

```
$ brew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61f86788c2eb049acea418f238e53201fd61a8af
Core tap last commit: 84 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/olalonde/.rbenv/shims/ruby => /Users/olalonde/.rbenv/versions/2.2.2/bin/ruby
Java: 1.8.0_102
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by jonchang** [comment]
It looks like you're trying to build from a python virtualenv, which probably doesn't install all the support scripts, etc. that opencv3 needs to build. Try building it outside of a venv. Moreover we don't really support `HEAD` builds since they are entirely dependent on the upstream developers.
