### ISSUE TITLE
netcdf --with-fortran error

### ISSUE THREAD

**Issue by bhelenbr** [Homebrew/homebrew-science#5364]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

I am having linking errors when building netcdf --with-fortran.  This is leading up to the installation of petsc (which also fails for fortran related reasons even if I skip netcdf).  I've deleted the entire /usr/local directory and started from scratch but still get the same issue.  I think this is because of an upgrade to the command line tools which happened in the last few days.   I have XCode 8.3 (8E162) installed.  

#### Brief summary of issue:

Already downloaded: /Users/bhelenbr/Library/Caches/Homebrew/netcdf--fortran-4.4.4.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/netcdf/4.4.1.1_4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAS
==> make
Last 15 lines from /Users/bhelenbr/Library/Logs/Homebrew/netcdf/10.make:
      ___netcdf_nc_interfaces_MOD_addcnullchar in module_netcdf_nc_interfaces.f90.o
      _nf_inq_libvers_ in nf_misc.f90.o
      _nf_strerror_ in nf_misc.f90.o
      ___netcdf_MOD_nf90_put_var_any in netcdf4.f90.o
      ___netcdf_MOD_nf90_put_att_text in netcdf4.f90.o
  "__gfortran_string_scan", referenced from:
      ___netcdf_nc_interfaces_MOD_stripcnullchar in module_netcdf_nc_interfaces.f90.o
      ___netcdf_nc_interfaces_MOD_addcnullchar in module_netcdf_nc_interfaces.f90.o
      _nf_inq_libvers_ in nf_misc.f90.o
      _nf_strerror_ in nf_misc.f90.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [fortran/libnetcdff.6.1.1.dylib] Error 1
make[1]: *** [fortran/CMakeFiles/netcdff.dir/all] Error 2

#### The complete command that you issued:

brew install petsc

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/cfc8cc83ce358df0caf690c73a66a89b

#### Output of `brew config`:

brew config
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 89 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ceac963146444cab3398ba3dc45986acc67acbe
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
I remember having built it in january/february with the older Xcode and it worked. I can confirm that I have this error now with the new Xcode (the same as you have). Somebody (upstream) will need to find a fix for this.

**Comment by bhelenbr** [comment]
Ok.  Thanks for your help. 

There seem to be other problems with petsc related to gfortran.  I don’t really need the fortran interface so I may try to figure out how to make a petsc script that doesn’t require fortran.   

Brian



Brian Helenbrook
Paynter-Krigman Endowed Professor in Engineering Science Simulation
Mechanical and Aeronautical Engineering Department
357 CAMP
Clarkson University
Potsdam, NY 13699-5725

work: 315-268-2204
fax: 315-268-6695

**Comment by ilovezfs** [comment]
OK CMake has fixed this: https://gitlab.kitware.com/brad.king/cmake/commit/53f17333f830d4f314bbe10ba32889bbcfbc3c46

I will try to backport the fix to CMake 3.7.2

**Comment by bhelenbr** [comment]
Thank you

**Comment by ilovezfs** [comment]
@bhelenbr this should take care of it once it's merged https://github.com/Homebrew/homebrew-core/pull/12198.

**Comment by ilovezfs** [comment]
This is now fixed.
