### ISSUE TITLE
r-gui: Requires macOS

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-science#5380]
_From @yzhzu on April 4, 2017 2:40_

Installing r-gui from homebrew/science
```
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://cran.r-project.org/bin/macosx/Mac-GUI-1.68.tar.gz
######################################################################## 100.0%
==> xcodebuild -target R -configuration Release SYMROOT=build HEADER_SEARCH_PATH
Last 15 lines from /home/rcmm/.cache/Homebrew/Logs/r-gui/01.xcodebuild:
2017-04-04 10:36:11 +0800

xcodebuild
-target
R
-configuration
Release
SYMROOT=build
HEADER_SEARCH_PATHS=/home/rcmm/.linuxbrew/opt/r/R.framework/Headers
OTHER_LDFLAGS=-F/home/rcmm/.linuxbrew/opt/r


READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
```

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is a problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

### Propose a feature:

Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered. Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

_Copied from original issue: Linuxbrew/brew#325_

**Comment by rwhogg** [comment]
`r-gui` basically downloads R.app, which is inherently Mac-only. So I think the proper solution here is to mark `r-gui` as Mac-only (assuming Homebrew-science is okay with such a change).

However, I think we also need to fix the GUI that comes with the `r` formula. At least for me, it doesn't launch either the built-in X11 or Tk GUI's.

@sjackman and @yzhzu, does that sound reasonable to you?

(Note that the issues we're seeing on https://github.com/Linuxbrew/homebrew-dupes/pull/125 might come up here)

**Comment by rwhogg** [comment]
One other problem: installing Rcmdr fails for me with: `ERROR: dependency ‘tcltk2’ is not available for package ‘Rcmdr’`. That's also possibly related.

Might want to look into this too once the tap migration from homebrew-dupes is finished.

**Comment by sjackman** [comment]
@yzhzu To install R on Linuxbrew use `brew install r`
To install a GUI for R see RStudio https://www.rstudio.com

**Comment by sjackman** [comment]
> However, I think we also need to fix the GUI that comes with the r formula. At least for me, it doesn't launch either the built-in X11 or Tk GUI's.

I've never used the GUI that comes with R, but yeah, it'd be good if it worked. RStudio is :100:

**Comment by sjackman** [comment]
> r-gui basically builds R.app, which is inherently Mac-only. So I think the proper solution here is to mark r-gui as Mac-only (assuming Homebrew-science is okay with such a change).

I've opened PR #5381
