### ISSUE TITLE
cytoscape 3.5

### ISSUE THREAD

**Issue by deepstop** [Homebrew/homebrew-science#5385]
Hi,

cytoscape 3.5 is the current stable version, could you please do a version bump:

http://chianti.ucsd.edu/cytoscape-3.5.0/cytoscape-3.5.0.tar.gz

thanking you!

**Comment by jonchang** [comment]
Hi @deepstop, our documentation on [how to open a pull request for Homebrew](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should be able to guide you through this process. Feel free to ask any questions if you encounter difficulties.
