### ISSUE TITLE
openblas doesnt compile with macOS sierra (10.12)

### ISSUE THREAD

**Issue by silwalr** [Homebrew/homebrew-science#5396]
### Indicate troubleshooting steps taken

- [ yes] Ran `brew update` and retried your prior step?
- [ yes] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ yes] Checked that a similar issue hasn't already been filed?
- [ yes] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=_dtrmm_kernel_LN -DASMFNAME=_dtrmm_kernel_LN_ -DNAME=dtrmm_kernel_LN_ -DCNAME=dtrmm_kernel_LN -DCHAR_NAME=\"dtrmm_kernel_LN_\" -DCHAR_CNAME=\"dtrmm_kernel_LN\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_LN.o
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=_dtrmm_kernel_LT -DASMFNAME=_dtrmm_kernel_LT_ -DNAME=dtrmm_kernel_LT_ -DCNAME=dtrmm_kernel_LT -DCHAR_NAME=\"dtrmm_kernel_LT_\" -DCHAR_CNAME=\"dtrmm_kernel_LT\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -DTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_LT.o
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=_dtrmm_kernel_RN -DASMFNAME=_dtrmm_kernel_RN_ -DNAME=dtrmm_kernel_RN_ -DCNAME=dtrmm_kernel_RN -DCHAR_NAME=\"dtrmm_kernel_RN_\" -DCHAR_CNAME=\"dtrmm_kernel_RN\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_RN.o
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_LN.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_LT.o] Error 1
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_RN.o] Error 1
make: *** [libs] Error 1

#### Brief summary of issue:
error when trying to install openblas with-openmp. i tried this after successfully running 
brew reinstall gcc --without-multilib

#### The complete command that you issued:
brew install -sv openblas --with-openmp

#### Gist with output of `brew doctor`:
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/silwal/progs/anaconda/bin/curl-config
  /Users/silwal/progs/anaconda/bin/freetype-config
  /Users/silwal/progs/anaconda/bin/icu-config
  /Users/silwal/progs/anaconda/bin/libdynd-config
  /Users/silwal/progs/anaconda/bin/libpng-config
  /Users/silwal/progs/anaconda/bin/libpng16-config
  /Users/silwal/progs/anaconda/bin/python3-config
  /Users/silwal/progs/anaconda/bin/python3.5-config
  /Users/silwal/progs/anaconda/bin/python3.5m-config
  /Users/silwal/progs/anaconda/bin/xml2-config
  /Users/silwal/progs/anaconda/bin/xslt-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libgcc_s.1.dylib
  /usr/local/lib/libgcc_s.10.4.dylib
  /usr/local/lib/libgcc_s.10.5.dylib
  /usr/local/lib/libgfortran.2.0.0.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libgfortran.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libgfortran.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3fc8010f6f9f2ebdfee620b3854751224433ee9c
Core tap last commit: 62 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.9.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/silwal/progs/anaconda/bin/python => /Users/silwal/progs/anaconda/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.3-x86_64
Xcode: 8.3
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by wukedi0410** [comment]
I have also been failed to install openblas on the Mac Pro (workstation).
However, I am successful to install it on the macbook.
==> Installing openblas from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/xianyi/OpenBLAS/archive/v0.2.18.tar.gz
Already downloaded: /Users/kdwu/Library/Caches/Homebrew/openblas-0.2.18.tar.gz
==> make CC=clang FC=/usr/local/bin/gfortran libs netlib shared
Last 15 lines from /Users/kdwu/Library/Logs/Homebrew/openblas/01.make:
make[1]: *** [dtrmm_kernel_LN.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1849:1: error: unexpected token at start of statement
#### Writing Back ####
^
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1849:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_RN.o] Error 1
make[1]: *** [dtrmm_kernel_LT.o] Error 1
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1849:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_RT.o] Error 1
make: *** [libs] Error 1

**Comment by jenson-shi** [comment]
### I'm failed too. I have reinstalled gcc --without-multilib.

### Build errors:

 brew install openblas --with-openmp
==> Installing openblas from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/xianyi/OpenBLAS/archive/v0.2.18.tar.gz
Already downloaded: /Users/shixiongfei/Library/Caches/Homebrew/openblas-0.2.18.tar.gz
==> make CC=gcc-6 FC=/usr/local/bin/gfortran libs netlib shared
Last 15 lines from /Users/shixiongfei/Library/Logs/Homebrew/openblas/01.make:
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=_dtrmm_kernel_RN -DASMFNAME=_dtrmm_kernel_RN_ -DNAME=dtrmm_kernel_RN_ -DCNAME=dtrmm_kernel_RN -DCHAR_NAME=\"dtrmm_kernel_RN_\" -DCHAR_CNAME=\"dtrmm_kernel_RN\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_RN.o
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_LN.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_LT.o] Error 1
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_RN.o] Error 1
make: *** [libs] Error 1

### brew config

HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b6265e2eeca95bf0ba1d8a9a537eedcdc1907cb7
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /Users/shixiongfei/anaconda3/bin/python => /Users/shixiongfei/anaconda3/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11

**Comment by iMichka** [comment]
There is an openblas update. I opened a PR for that #5421.
Let's see if that helps

**Comment by iMichka** [comment]
I updated to 0.2.19 and added an upstream patch that fixes the compilation error.
This should fix this problem.
