### ISSUE TITLE
r-gui El capitan bottle compiled using Sierra sources

### ISSUE THREAD

**Issue by tobadia** [Homebrew/homebrew-science#5411]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
R-gui app is correctly installed using `brew install r-gui`. It downloads `https://homebrew.bintray.com/bottles-science/r-gui-1.68.el_capitan.bottle.tar.gz` and pours fine. However when starting the app I get prompted with an OSX error "This requires osx 10.12. You're running 10.11.6".
`shasum -a 256 /Users/tobadia/Library/Caches/Homebrew/r-gui-1.68.el_capitan.bottle.tar.gz` returns the expected sha checksum as can be seen in r-gui.rb (59d782583a0273c4009c29f9bd935eef5837a79c06875e2cd62a63f6a1d8f29a).

This leads me to believe the binary in the bottle has been improperly compiled using Sierra sources instead of El Capitan. Maybe just an mix-up between version sources (might be worth checking if the Sierra version isn't actually the El Capitan one, and the other way around).
#### Brief summary of issue:
The `r-gui-1.68.el_capitan.bottle.tar.gz` bottle seems to have been incorrectly compiled using SIerra sources instead of El Capitan.

#### The complete command that you issued:
brew install r-gui

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
Error: No logs.

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: afe9867b31dc82e4317e7b5e268dc509acde2dd7
Core tap last commit: 79 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11

### Formula Requests:
not relevant

**Comment by iMichka** [comment]
Hi.

Could you try: `brew uninstall r-gui && brew install r-gui --build-from-source` ?

Just to see if this is really a mixup or a problem in the build process?

**Comment by tobadia** [comment]
Hi,

Will try out tomorrow when I'm on that laptop again. I did try to uninstall
and reinstall but did not force from sources on purpose (I did rm the
downloaded file from Cellar though). More to follow when I'm back at work.

Thanks for investigating anyway.

**Comment by tobadia** [comment]
Checked today by building from source. Still the same error
`brew install r-gui --build-from-source
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 4 taps (caskroom/cask, caskroom/versions, homebrew/core, homebrew/science).
==> Updated Formulae
cmake ✔                        gjs                            gtksourceview3                 jenkins                        proftpd                        sourcekitten                   youtube-dl ✔
dhall-json                     gspell                         gxml                           nats-streaming-server          pygobject3                     thefuck ✔

==> Installing r-gui from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://cran.r-project.org/bin/macosx/Mac-GUI-1.68.tar.gz
######################################################################## 100,0%
==> xcodebuild -target R -configuration Release SYMROOT=build HEADER_SEARCH_PATHS=/usr/local/opt/r/R.framework/Headers OTHER_LDFLAGS=-F/usr/local/opt/r
🍺  /usr/local/Cellar/r-gui/1.68: 130 files, 3.9MB, built in 12 seconds`

And then the same error as before when trying to launch the GUI.

**Comment by iMichka** [comment]
The installation documentation says:

> Only Mac OS X 10.6 and higher are supported, and only 64-bit R. The
project is called "R.xcodeproj" and requires Xcode 3.2 or higher.
>
>The project can be built by selecting "R" target and "Build" inside
the XCode GUI.
>
>Supported configurations are:
  SnowLeopard64 (release, current OS X, default)
  Lion64 (release, OS X 10.7+, Xcode 4.5+)
  MLion64 (release, OS X 10.8+, Xcode 4.5+)
  Debug (with debugging output, current OS X)
>
>The configurations differ mainly in the SDK selected (recent versions
of Xcode only support the current and immediately previous SDKs, so
for example in Mar 2013 the default would build for 10.8, but
configuration Lion64 allows building for >= 10.7).
>
>To build the project from the command line in the Mac-GUI directory
use something like:
	xcodebuild -target R -configuration SnowLeopard64

We are passing: `"-configuration", "Release"`, which is undocumented. Not sure this is expected to work at all. Maybe you could report this problem to upstream and ask for advice.

**Comment by iMichka** [comment]
And as building from source is also broken, this shows that this is not a bottling problem.

**Comment by jonchang** [comment]
> We are passing: "-configuration", "Release", which is undocumented. Not sure this is expected to work at all. Maybe you could report this problem to upstream and ask for advice.

As far as I can tell, the documentation is updated as there is no `SnowLeopard64` build target. Unfortunately I don't have an older machine to try to reproduce this bug on.

**Comment by tobadia** [comment]
Indeed, the doc seems to be outdated (file created 2013-03-18 and indicated "last updated" 2013-03-08 within the file... Although i'm not sure about these exact dates it's way out of date anyway)

I thought it could just be a mix-up in build calls but this doesn't make sense. I'll try and see with the CRAN team (including a reference to the issue raised here if that can be of any help).

Thanks again for the thorough examination.

**Comment by tobadia** [comment]
Some updates regarding this issue. If I'm reading what the R-SIG-MAC mailing list says, it's still something fishy on Homebrew's side: https://stat.ethz.ch/pipermail/r-sig-mac/2017-April/012302.html

However this still does not explain why building from source would fail on my machine...

**Comment by tobadia** [comment]
Fix found and applied, as suggested on the R-SIG-Mac mailing list. By building from source myself (from the .tar.gz archive) I had to add `MACOSX_DEPLOYMENT_TARGET=10.11` to the xcodebuild call.

So depending on the SDK available o the machine builds are compiled on, these flags should be set. I have no clue where the bottled versions are generated and if there's a better way to suggest an edit of the pipeline that leads to building the binaries, but the xcodebuild call should include a `MACOSX_DEPLOYMENT_TARGET=$(version)` or something similar (not sure what homebrew has access to, might be extracted the same way the `macOS` info is returned by `brew config` ??)

**Comment by jonchang** [comment]
@tobadia thanks for looking into this! Would you mind opening a pull request for this change? Getting the current macOS version can be done with `MacOS.version.to_s`.

**Comment by tobadia** [comment]
Will do later today, in 2-3 h probably. I'll test on a Sierra machine if I can, as well, just to check if I'm not breaking anything.

**Comment by tobadia** [comment]
Done! The compiled binaries should still be modified (probably by adding the same flag for future builds) to prevent the same thing from occuring when `--build-from-source` is not requested. Not sure where this should be edited as I don't know where the bottling pipeline takes place, though.

**Comment by iMichka** [comment]
The bottles were rebuilt on our jenkins buildbot. 3 bottles got build with different platform targets, as MacOS.version was different each time. This should be good now, even for installations which are not compiled from source. Closing issue.
