### ISSUE TITLE
Error: undefined local variable or method `buildpath' for #<Class:0x007fe1ac83ed58>

### ISSUE THREAD

**Issue by jhuh3226** [Homebrew/homebrew-science#5419]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
Error: undefined local variable or method `buildpath' for #Class:0x007fd82601abe8
#### Brief summary of issue:
I'm having problem with Installing OpenCV 3 with Python 3 bindings via Homebrew
(referring link " http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/").
On commanding $ brew install opencv3 --with-contrib --with-python3 --HEAD,
there always occurs this issue of

Error: undefined local variable or method `buildpath' for #Class:0x007fd82601abe8
#### The complete command that you issued:
 brew install opencv3 --with-contrib --with-python3 --HEAD

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.12-3559-g5d74069b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5d74069b98a9a4a923c748e33b5f101a45ceac83
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a3802a60f14f54159107cc706f1f2492036b7e91
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: 8.3.0.0.1.1490382677
X11: N/A

### Formula Requests:
not relevant

**Comment by iMichka** [comment]
Hi. Thanks for reporting.

We do not really support `HEAD` builds. They are there to play around; but we are not actively fixing bugs as these are often moving targets. Please open a new issue if there is still a problem with the stable version.

**Comment by serser** [comment]
On High Sierra, `contrib` may not be supported, since:

    "Warning: opencv: this formula has no --with-contrib option"
