### ISSUE TITLE
opencv3: Python 2.7 & 3.6 bindings build successfully but not available in homebrew'd python

### ISSUE THREAD

**Issue by blebo** [Homebrew/homebrew-science#5430]
The following commands need to be executed after successful install of opencv3 with python 2.7/3.6 bindings, in order to access opencv3 from homebrew'd python.

Python 2:

    ln -s /usr/local/Cellar/opencv3/3.2.0/lib/python2.7/site-packages/cv2.so /usr/local/lib/python2.7/site-packages/cv2.so

Python 3:

    ln -s /usr/local/Cellar/opencv3/3.2.0/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so /usr/local/lib/python3.6/site-packages/cv2.so

Recommend that these steps be added as a post-install task in the formula (if the applicable .so file was built successfully).

**Comment by blebo** [comment]
Successful build gist if interested: https://gist.github.com/blebo/ed25bb7a0e97b32bd611bb8a697d7fa9

**Comment by tdsmith** [comment]
I think this is stated in the post-build caveats; let us know if that wasn't the case.

**Comment by blebo** [comment]
OK I missed that. It only shows the following for python2.7: 

    echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth

Its probably worth adding another line for python3.6:

    echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth

**Comment by tdsmith** [comment]
Hmm, yep! That was bug https://github.com/Homebrew/brew/issues/249; I'm finally working on a solution in https://github.com/Homebrew/brew/pull/2499.
