### ISSUE TITLE
opencv3 build error

### ISSUE THREAD

**Issue by jhuh3226** [Homebrew/homebrew-science#5433]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
Error: undefined local variable or method `buildpath' for #<Class:0x007fde1302bd88>
#### Brief summary of issue:
On installing OpenCV 3 on macOS with home-brew, there occurs problem of 
`Error: undefined local variable or method buildpath' for #<Class:0x007fde1302bd88>`

#### The complete command that you issued:
`brew info opencv3`

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs opencv`:
Error: undefined local variable or method `buildpath' for #<Class:0x007fc0be9f1150>
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv3.rb:248:in `<class:Opencv3>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv3.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:259:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:69:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:125:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'

#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.12-3565-g02f01893
ORIGIN: https://github.com/Homebrew/brew
HEAD: 02f0189335907805d422c817462674081f48ab60
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8352c507159584e82d28ac6623c339db246d3494
Core tap last commit: 44 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: 8.3.0.0.1.1490382677
X11: N/A

### Formula Requests:

**Comment by iMichka** [comment]
Follow up from #5419.

Does `brew gist-logs opencv3` really return `-bash: syntax error near unexpected token newline`?

And does this fail while building or when you call `brew info opencv3` like explained in your description?

**Comment by iMichka** [comment]
Related to https://github.com/Homebrew/brew/issues/2500

**Comment by jhuh3226** [comment]
@iMichka 
I just updated return for the` brew gist-logs opencv3`.
and yes it also fails when `brew info opencv3`was commended returning `Error: undefined local variable or method `buildpath' for #<Class:0x007fbd5a1008c8>`.

**Comment by iMichka** [comment]
opencv has been migrated to homebrew-core. Please test that version and report any issue back there. Thanks.
