### ISSUE TITLE
brew install netcdf wild

### ISSUE THREAD

**Issue by hsiaoyi0504** [Homebrew/homebrew-science#5434]
It is related to sneumann/mzR#85
libnetcdf.11.dylib can't be loaded. If I use `brew install netcdf` to install `netcdf`
`ls /usr/local/opt/netcdf/lib/` shows that there is libnetcdf.11.dylib.
However, it can't be loaded through  `@rpath/libnetcdf.11.dylib`

My `brew doctor` result:
```
brew doctor                                                                                                    
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /opt/ImageMagick/bin/Magick++-config
  /opt/ImageMagick/bin/Magick-config
  /opt/ImageMagick/bin/MagickCore-config
  /opt/ImageMagick/bin/MagickWand-config
  /opt/ImageMagick/bin/Wand-config
```

I had already ran `brew update` several times.

### Bug reports / build errors:
When I installed `mzR`
The installation already finished, but package can't be loaded and produce following errpr:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.3/site-library/mzR/libs/mzR.so':
  dlopen(/usr/local/lib/R/3.3/site-library/mzR/libs/mzR.so, 6): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /usr/local/lib/R/3.3/site-library/mzR/libs/mzR.so
  Reason: image not found
Error: loading failed
Execution halted
```

#### Brief summary of issue:
The setting or link of `libnetcdf.11.dylib` maybe is incorrect.

#### The complete command that you issued:
`brew install R`
`brew install netcdf`
In R, I use `source("https://bioconductor.org/biocLite.R")` and `biocLite("mzR")`

#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 27a6f377b2dfa714ecb61e0379e040036d6838b7
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: 8.3.0.0.1.1490382677
X11: N/A
```

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.
```

**Comment by woodruffw** [comment]
Building `netcdf` from source fixed the `LC_ID_DYLIB` for me, which suggests that this is a leftover regression from https://github.com/Homebrew/brew/pull/2036.

We'll fix it by rebuilding the bottles, but in the mean time you should be able to fix your problem locally by running:

```ruby
brew uninstall netcdf
brew install --build-from-source netcdf
```

Thanks for reporting this!

**Comment by woodruffw** [comment]
Actually, even that shouldn't be necessary. You should be able to just uninstall and reinstall from the bottle, since our relocation code will correctly replace `@rpath` with the prefix. The problem stems from `netcdf` just being installed after the aforementioned PR.

**Comment by hsiaoyi0504** [comment]
`brew reinstall netcdf` didn't work for me. I will try
```
brew uninstall netcdf
brew install --build-from-source netcdf
```

**Comment by hsiaoyi0504** [comment]
It still doesn't work.....

**Comment by ilovezfs** [comment]
It won't because you're on the stable tag not master. You'll need to wait for the next tag (my recommendation) or switch to master (not my recommendation).

**Comment by ilovezfs** [comment]
@hsiaoyi0504 OK 1.1.13 has been tagged. https://github.com/Homebrew/brew/releases/tag/1.1.13

If you `brew update` and try again, I think it will be fixed.

**Comment by hsiaoyi0504** [comment]
It works, really thanks a lot !!

**Comment by ilovezfs** [comment]
You're welcome!
