### ISSUE TITLE
libgif update broke vips bottles

### ISSUE THREAD

**Issue by iAdramelk** [Homebrew/homebrew-science#5438]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

`vips` stopped working after update. Then I try to start it, I now see following in the console:

```
❯ vips --version
dyld: Library not loaded: /usr/local/opt/giflib/lib/libgif.4.dylib
  Referenced from: /usr/local/bin/vips
  Reason: image not found
[1]    7070 abort      vips --version
```
Reason for that is that latest version of `libgif` didn't have file named `libgif.4.dylib` in it's folder anymore:

```
❯ brew list giflib
/usr/local/Cellar/giflib/5.1.4/bin/gif2rgb
/usr/local/Cellar/giflib/5.1.4/bin/gifbuild
/usr/local/Cellar/giflib/5.1.4/bin/gifclrmp
/usr/local/Cellar/giflib/5.1.4/bin/gifecho
/usr/local/Cellar/giflib/5.1.4/bin/giffix
/usr/local/Cellar/giflib/5.1.4/bin/gifinto
/usr/local/Cellar/giflib/5.1.4/bin/giftext
/usr/local/Cellar/giflib/5.1.4/bin/giftool
/usr/local/Cellar/giflib/5.1.4/include/gif_lib.h
/usr/local/Cellar/giflib/5.1.4/lib/libgif.7.dylib
/usr/local/Cellar/giflib/5.1.4/lib/ (2 other files)
```
Then I manually added symlink from `libgif.dylib` to `libgif.4.dylib` everything started working:

```
cd /usr/local/opt/giflib/lib/
ln -nsf  libgif.dylib libgif.4.dylib
```

#### Brief summary of issue:

`giflib` don't have file named `libgif.4.dylib` anymore, it breaks `vips` installation.

**Comment by jonchang** [comment]
Please run `brew update` and see if that fixes the issue. We just pushed a new version of `vips` which should have the proper links to `giflib`.

**Comment by iAdramelk** [comment]
Works good now, thanks!
