### ISSUE TITLE
Symbol not found while using Cufflinks

### ISSUE THREAD

**Issue by momo12321** [Homebrew/homebrew-science#5440]
I am trying to run cufflinks , all the other programs that requrie boost like Tophat and such are working perfectly. However whenever I execute Cufflinks, I get this error : 
dyld: Symbol not found: __ZN5boost11this_thread5hiden11sleep_untilERK8timespec
  Referenced from: /usr/local/bin/cufflinks
  Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
Trace/BPT trap: 5
I always end up with 4 files ( cufflinks should output 4 files ) , however they have zero bytes in them .

I tried these steps:
brew update
brew upgrade 
brew reinstall cufflinks

But nothing changed and the error remained still .

**Comment by jonchang** [comment]
Hi @momo12321, thanks for your report. Could you please fill out the [issue template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md)? In particular, knowing if you're installing from source or a bottle will be helpful to diagnose your issue. Feel free to reopen a new issue with the issue template filled out.
