### ISSUE TITLE
Openni2 not found with OPENNI2_INCLUDE

### ISSUE THREAD

**Issue by pammacdotnet** [Homebrew/homebrew-science#5441]
OpenNi2 is not found if ENV.append "OPENNI2_INCLUDE" is used. 

ENV.append "OPENNI2_INCLUDE_DIRS" seems to work ok.

**Comment by jonchang** [comment]
Hi @pammacdotnet, thanks for your report. Could you please fill out the [issue template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md)? I don't actually know what formula this is for as there are several it could apply to. Feel free to open a new issue with the template filled out.
