### ISSUE TITLE
biopieces won't install

### ISSUE THREAD

**Issue by alexstaj** [Homebrew/homebrew-science#5446]
little help please. 

tried to install biopieces but ruby needed a gem.  installed the gem using sudo (required to install it) but its not being detected (even after restarting).

mbp:~ Staj$ brew install biopieces
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).

==> Installing biopieces from homebrew/science
biopieces: Unsatisfied dependency: inline
Homebrew does not provide special Ruby dependencies; install with:
  `gem install inline`
Error: An unsatisfied requirement failed this build.
mbp:~ Staj$ sudo gem install inline
Successfully installed inline-0.1.0
Parsing documentation for inline-0.1.0
1 gem installed
mbp:~ Staj$ brew install biopieces
==> Installing biopieces from homebrew/science
biopieces: Unsatisfied dependency: inline
Homebrew does not provide special Ruby dependencies; install with:
  `gem install inline`
Error: An unsatisfied requirement failed this build.

**Comment by jonchang** [comment]
What does `ruby -e 'require "inline"'` say?

**Comment by alexstaj** [comment]
mbp:~ Staj$ ruby -e 'require "inline"'
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:96: warning: else without rescue is useless
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:108: warning: else without rescue is useless
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:93: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
			when nil: @position = length-1
			         ^
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:94: syntax error, unexpected keyword_when, expecting keyword_end
			when 0: @position = length-1 if @cycle
			    ^
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:105: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n'
			when nil: @position = length-1
			         ^
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:106: syntax error, unexpected keyword_when, expecting keyword_end
			when length-1: @position = 0 if @cycle
			    ^
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:106: syntax error, unexpected ':', expecting keyword_end
			when length-1: @position = 0 if @cycle
			              ^
/Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline/history_buffer.rb:128: syntax error, unexpected keyword_end, expecting end-of-input
	end
	   ^
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/inline-0.1.0/lib/inline.rb:22:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from -e:1:in `<main>'

**Comment by jonchang** [comment]
Seems like there's an issue with the `inline` gem, not sure if we're able to fix this as it looks like it hasn't been updated since 2008.

**Comment by alexstaj** [comment]
sudo gem install RubyInline worked to allow me to install it.  havent tried to use it yet though.
