### ISSUE TITLE
STACKS 1.46

### ISSUE THREAD

**Issue by ACharbonneau** [Homebrew/homebrew-science#5448]
I'm trying up update the formula for STACKS to the most current version, but I keep getting a `fatal error: 'tr1/functional' file not found`

It looks like this issue was address in the previous formula update https://github.com/Homebrew/homebrew-science/pull/2265 so I'm not sure why it's back or what to do now.

I have homebrew completely updated, including the gcc compiler, and am running OSX Sierra 10.12.4 

I get the same error when I try to install on a linux machine, so it doesn't seem to be just an OSX problem anymore. 

Any suggestions?

**Comment by jonchang** [comment]
It's probably easier to look at the code. Do you mind opening a pull request so we can see your changes and how our build machines handle it?

**Comment by ACharbonneau** [comment]
Of course! I just wasn't sure whether I was supposed to pull request obviously broken code. It's PR https://github.com/Homebrew/homebrew-science/pull/5450

**Comment by sjackman** [comment]
TravisCI
``
g++-5: error: ./htslib/libhts.a: No such file or directory
```
https://travis-ci.org/Homebrew/homebrew-science/builds/223748725#L1397

If it's a make parallelization issue, then either
```ruby
    system "make"
    ENV.deparallelize
    system "make", "install"
```
or
```ruby
    ENV.deparallelize
    system "make", "install"
```
may resolve it.

**Comment by sjackman** [comment]
CircleCI
```
checking for functional regular expressions... configure: error: Regular expressions are not functional, you need g++ 4.9.0 or greater.
```
Add…
```ruby
fails_with :gcc => "4.8"
```

**Comment by sjackman** [comment]
Superseded by #5450
