### ISSUE TITLE
CI on sierra failed because Xcode is outdated

### ISSUE THREAD

**Issue by tnayuki** [Homebrew/homebrew-science#5452]
My PR's CI failed because Xcode is outdated.

https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/7810/version=sierra/testReport/junit/brew-test-bot/sierra/doctor/

> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: Your Xcode (8.3.1) is outdated.
> Please update to Xcode 8.3.2 (or delete it).
> Xcode can be updated from the App Store.

**Comment by ilovezfs** [comment]
Thanks for the report. The CI nodes will be updated eventually.
