### ISSUE TITLE
opencv3: --with-python3 doesn't work

### ISSUE THREAD

**Issue by kkdd** [Homebrew/homebrew-science#5463]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

```brew install opencv3 --with-python3``` just doesn't seem to link a module for python3.

#### The complete command that you issued:

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1421
$ brew install python python3
$ python --version
Python 2.7.13
$ python3 --version
Python 3.6.1
$ brew tap homebrew/science
$ brew install opencv3 --with-python3
$ python -c "import cv2; print cv2.__version__"
3.2.0
$ python3 -c "import cv2; print(cv2.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
```

```
$ brew config
HOMEBREW_VERSION: 1.1.13-45-gcd110b4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cd110b467d76e0d93afc35785c769478b0ed6b32
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 62e443dba3e70ffaf8dd9ac5af6c5ad224cabdf8
Core tap last commit: 72 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by jonchang** [comment]
What does `brew install opencv3 --with-python3 --without-python` return?

**Comment by Neabfi** [comment]
I have the same problem it creates
```/usr/local/opt/opencv3/lib/python2.7/```` 
but not
 ``` /usr/local/opt/opencv3/lib/python3.5/ ```

**Comment by iskandarshabaev** [comment]
I have the same problem.
brew install opencv3 --with-python3 does not create /usr/local/opt/opencv3/lib/python3.5/
brew install opencv3 --with-python3 --without-python does not create /usr/local/opt/opencv3/lib/python2.7/

**Comment by iMichka** [comment]
What is sure is that you will not be able to have both python2 and python3 installations, because opencv3 does not support this from a single build.

**Comment by jonchang** [comment]
@iMichka does it make sense to make `--with-python` and `--with-python3` mutually exclusive and update the options documentation to reflect that?

**Comment by iMichka** [comment]
@jonchang I opened a PR for that, see #5488
Using the same strategy as for VTK.

So the only valid combinations will be:
> brew install opencv3 --without-python --with-python3 (install for Python 3)
> brew install opencv3 --with-python (installs for Python 2)

**Comment by iMichka** [comment]
And the initial problem reported here is different.
See that tutorial: http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/

> I have no idea why the Python 3 + OpenCV 3 bindings are not named cv2.so  as they should be, but the same is true across operating systems. You’ll see this same issue on macOS, Ubuntu, and Raspbian.
> Luckily, the fix is easy — all you need to do is rename cv2.cpython-35m-darwin.so  to cv2.so

This seem to be a common problem. Either this is on purpose and the opencv 3 documentation should tell this (and users needs to be aware of this); or we should rename the `.so` file.

**Comment by Neabfi** [comment]
So in the tutoriel it should be ```brew install opencv3 --without-python --with-contrib --with-python3 --HEAD``` instead of ```brew install opencv3 --with-contrib --with-python3 --HEAD```for python3 ?

**Comment by akirasosa** [comment]
I tried ```brew install opencv3 --without-python --with-python3```. It looks like same as ```brew install opencv3 --without-python```.

Nothing was created for python.
```
$ ls /usr/local/Cellar/opencv3/3.2.0/lib | grep python
# nothing.

$ python3
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
```
Here is my environment.
```
$ brew config
HOMEBREW_VERSION: 1.1.13-129-gc6c930174
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c6c930174eeff9d863d068acbe3ccaa8fe520bb6

$ brew list | grep python
python
python3

$ which python
/usr/local/bin/python

$ which python3
/usr/local/bin/python3
```

**Comment by iMichka** [comment]
What does this output?:
> ls /usr/local/Cellar/opencv3/3.2.0/lib/python3.6/site-packages/

If `cv2.cpython-36m-darwin.so` was built, it means it worked. Read my comment and the tutorial.

**Comment by akirasosa** [comment]
@iMichka 
Thanks! But I don't have a ```python3.6``` directory as written in my previous comment.
```
$ ls /usr/local/Cellar/opencv3/3.2.0/lib/python3.6/site-packages/
ls: /usr/local/Cellar/opencv3/3.2.0/lib/python3.6/site-packages/: No such file or directory
```

**Comment by adityapatadia** [comment]
This is the commit which is creating all the problems. https://github.com/Homebrew/homebrew-science/commit/435b6e5c471fd4061af376e88737b8895e7affa0

I removed those lines added in the commit and it's working perfectly fine.

**Comment by iMichka** [comment]
> This is the commit which is creating all the problems. 435b6e5

Note sure. What problems are we talking abou?. There seem to be quite a mixup of different problems in this issue. And my change was made 2 days after the initial report, so it is not responsible for the initial problem (which is that the .so file needs to be renamed as cv2.so). I am currently working on a patch for this.

@adityapatadia @akirasosa You seem to have a different problem, which is that the .so file does not get build at all. Please open a new bug for that.

**Comment by iMichka** [comment]
Two fixes will be needed to make this work:
Giving the cv2.so file the right name: #5503
Adding the missing caveats line: https://github.com/Homebrew/brew/pull/2499

**Comment by iMichka** [comment]
@kkdd Can you please test?

```
brew update
brew uninstall opencv3
brew pull https://github.com/Homebrew/homebrew-science/pull/5503
brew install opencv3 --without-python --with-python3
echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth
```

Once you are done you can use `brew update-reset` to reset homebrew to the "normal" state.

**Comment by iMichka** [comment]
In fact the .so file renaming is not needed.
All you can do is:

```
brew update
brew uninstall opencv3
brew install opencv3 --without-python --with-python3
echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth
```

**Comment by lelayf** [comment]
same issue for me, `brew install opencv3 --without-python --with-python3` does not create any python3.6 directory under /usr/local/opt/opencv3/lib

**Comment by GLBaird** [comment]
I have tried this recommended method:
```brew update
brew uninstall opencv3
brew install opencv3 --without-python --with-python3
echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth```
It did not work, and like others say, `/usr/local/opt/opencv3/lib/python3.6/site-packages` does not exists. There is no `python3.6` folder inside `/usr/local/opt/opencv3/lib`.
Have given up on this, as a waste of my time, and installing it manually.

**Comment by DLtech456** [comment]
I am experiencing the same issue, Python3.6 folder is not showing up inside opencv3. Could you please tell me how to install it manually?

**Comment by ManuelLevi** [comment]
Experiencing the same issue.

**Comment by toejough** [comment]
based on the discussion at https://github.com/Homebrew/homebrew-science/issues/3939 (which made me re-examine my python environment), and elsewhere where I found recommendations not to try to install support for both python2 and python3, I did the following, which worked for python3:

* `brew uninstall python` (personally, I didn't need this, and wasn't sure why it was there anyway)
* `brew uninstall opencv3` (didn't install correctly, so get rid of it for now)
* `brew uninstall numpy` (I think numpy installed against the wrong python environment the first time around)
* `pyenv global system` (I wasn't in a virtual-env, but I was using a pyenv-managed python in the environment I tried to do the installation)
* `brew install numpy --without-python --with-python3`
* `brew install opencv3 --without-python --with-python3 --with-contrib`

After that the expected python directory existed in `lib`.

**Comment by toejough** [comment]
I'm not sure if the `brew uninstall python` bit above is really necessary.  It shouldn't be.  It also seems odd to me that the active version of python would prevent correct installation. 

In my ideal world, both `numpy` and `opencv3` would consistently use the same python environment.  Any of:

* the non-virtual-env, non-pyenv, python installation/env
* the active virtual-env/pyenv
* the brew-installed python environment

I'm not sure what the details here are, or what level of cooperation is necessary between the numpy and opencv3 maintainers.

Is this something that could happen, or is there some technical/philosophical hurdle there?

**Comment by chocol4te** [comment]
Should brew automatically maintain its own virtualenv system for managing Python, across all formulae? That way formulae can do whatever they want to their own python installation and not have to worry about issues like this or version control, where updating Python breaks formulae installations. Each one can manage its own versions and choose to update or not.

**Comment by walchko** [comment]
ok, could you please remove:

``` bash
if build.with?("python3") && build.with?("python")
  # Opencv3 Does not support building both Python 2 and 3 versions
  odie "opencv3: Does not support building both Python 2 and 3 wrappers"
end
```

If I comment this out and install opencv3 for python2 and python3 with:

    brew install opencv3 --with-ffmpeg --without-numpy --with-nonfree --with-python3 --with-tbb --with-contrib

it works nicely:

```bash
kevin@Dalek ~ $ brew install opencv3 --with-ffmpeg --without-numpy --with-nonfree --with-python3 --with-tbb --with-contrib
==> Installing opencv3 from homebrew/science
==> Downloading https://github.com/opencv/opencv/archive/3.3.0.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/opencv3-3.3.0.tar.gz
==> Downloading https://github.com/opencv/opencv_contrib/archive/3.3.0.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/opencv3--contrib-3.3.0.tar.gz
==> Downloading https://github.com/opencv/opencv_contrib/archive/3.3.0.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/opencv3--contrib-3.3.0.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because opencv3 and opencv install many of the same files.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/opencv3/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/opencv3/lib
    CPPFLAGS: -I/usr/local/opt/opencv3/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/opencv3/lib/pkgconfig


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
==> Summary
🍺  /usr/local/Cellar/opencv3/3.3.0_1: 516 files, 122.3MB, built in 10 minutes 36 seconds
```

Note, I don't use `brew` for numpy, IMHO that is what `pip` is for ... it keeps things clean and simple. `brew` should never install a python library managed by `pip` ever.

I do wish you would automate the installation of opencv for python ... after all, I am installing it with python bindings, so why would I not want the python library installed too???

```bash
kevin@Dalek opencv3 $ echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
kevin@Dalek opencv3 $ echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth
```

I really don't understand what the problem is.

**Comment by iMichka** [comment]
> ok, could you please remove:

This broke some people's builds, that's why it has been added. And nobody came up with a better solution. But we will remove it as we are migrating the formula from science to core, giving this a second shot. If it breaks again people's build, then we will add it back.

This whole issue will be close soon and the discussion can be done with a fresh eye in homebrew-core.

**Comment by iMichka** [comment]
opencv has been migrated to homebrew-core. Please test that version and report any issue back there. Thanks.
