### ISSUE TITLE
Symbol not found while using Cufflinks

### ISSUE THREAD

**Issue by momo12321** [Homebrew/homebrew-science#5466]
### Indicate troubleshooting steps taken
- [ yes] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ yes] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
dyld: Symbol not found: __ZN5boost11this_thread5hiden11sleep_untilERK8timespec
Referenced from: /usr/local/bin/cufflinks
Expected in: /usr/local/opt/boost/lib/libboost_thread-mt.dylib
Trace/BPT trap: 5

#### Brief summary of issue:
I am trying to run cufflinks , all the other programs that requrie boost like Tophat and such are working perfectly. However whenever I execute Cufflinks, I get this error. The cufflinks files outputted are zero bytes of size. (empty)
 #### The complete command that you issued:
cufflinks accepted_hits.bam
#### Gist with output of `brew doctor`:
Your system is ready to brew
#### Link output by `brew gist-logs <formula>`:
Error: no logs
#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: daabacb96470a2abaa454f1d4a7e91afc7f37e63
Core tap last commit: 72 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.10.2-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
X11: N/A
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
```
readlink /usr/local/opt/boost
```

**Comment by ilovezfs** [comment]
what's the output?

**Comment by momo12321** [comment]
../Cellar/boost/1.63.0

**Comment by ilovezfs** [comment]
```
brew update
brew upgrade
brew reinstall cufflinks
```

**Comment by momo12321** [comment]
I tried this, nothing changed

**Comment by ilovezfs** [comment]
The current version of boost is 1.64.0 so that should not be 1.63.0 if you already ran brew update and brew upgrade.

**Comment by momo12321** [comment]
I just upgraded , still no difference

**Comment by ilovezfs** [comment]
OK, now try
```
brew reinstall -s cufflinks
```

**Comment by momo12321** [comment]
Error: Cannot install homebrew/science/samtools-0.1 because conflicting formulae are installed.

  samtools

Please `brew unlink samtools` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

**Comment by ilovezfs** [comment]
brew unlink samtools
brew reinstall -s cufflinks
brew unlink samtools-0.1
brew link samtools

**Comment by momo12321** [comment]
i got this error while trying to reinstall cufflinks:Last 15 lines from /Users/mohamad/Library/Logs/Homebrew/cufflinks/02.make:
            ar & serialization::make_array(data_, s);
                 ~~~~~~~~~~~~~~~^
In file included from clustering.cpp:10:
In file included from ./clustering.h:38:
In file included from ./abundances.h:18:
/usr/local/include/boost/numeric/ublas/matrix.hpp:5977:33: error: no member named 'make_array' in namespace 'boost::serialization'
            ar & serialization::make_array(data_, N);
                 ~~~~~~~~~~~~~~~^
3 errors generated.
make[2]: *** [clustering.o] Error 1
make[2]: *** Waiting for unfinished jobs....
3 errors generated.
make[2]: *** [differential.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by ilovezfs** [comment]
OK, that's this https://svn.boost.org/trac/boost/ticket/12978.

```
perl -p -i -e 's/#include <boost\/serialization\/array.hpp>/#include <boost\/serialization\/array_wrapper.hpp>/' /usr/local/Cellar/boost/1.64.0/include/boost/numeric/ublas/matrix.hpp
perl -p -i -e 's/#include <boost\/serialization\/array.hpp>/#include <boost\/serialization\/array_wrapper.hpp>/' /usr/local/Cellar/boost/1.64.0/include/boost/numeric/ublas/storage.hpp
brew reinstall -s cufflinks
```

**Comment by momo12321** [comment]
I did what you said exactly , unlink samtools-0.1 , linked smalls , updated brew , and tried cufflinks and IT WORKED
I can't thank you enough! You're amazing.

**Comment by ilovezfs** [comment]
You're welcome :)

**Comment by iMichka** [comment]
@ilovezfs should we make a patch out of this? Seems the boost problem is still open on their bugtracker. No clue when this will be fixed.

**Comment by ilovezfs** [comment]
@iMichka no we fixed this in https://github.com/Homebrew/homebrew-core/pull/12748

**Comment by iMichka** [comment]
Thanks 👍
