### ISSUE TITLE
upgrade request - rstudio-server.rb

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Homebrew/homebrew-science#5486]
I'm a user of the excellent formula for rstudio-server. 

Currently it installs rstudio-server 1.0.44

Rstudio-server current release is v1.0.143

It would be nice if it would be upgraded.  I tried to edit the formula myself but failed!

**Comment by randy3k** [comment]
I have created #5442  a few days ago targeting for rstudio-server v1.0.136. As v1.0.143 is just out, I will just update it to  v1.0.143

**Comment by randy3k** [comment]
I noted that R has updated to 3.4 and unfortunately rstudio-server v1.0.xxx doesn't build against R 3.4 since the R API has changed. We will need to upgrade it to the preview version v1.1.xxx.

**Comment by iMichka** [comment]
PR was merged, version 1.0.143 is available. Closing here.
