### ISSUE TITLE
DRAWEXE OCE linking issue

### ISSUE THREAD

**Issue by rajeeja** [Homebrew/homebrew-science#5493]
The following error shows up after launching DRAWEXE

==> DRAWEXE
can't read "::env(CASROOT)": no such variable
Draw[1]> Draw[2]> exit

Another library that I link with OCE gives the following error:

[ 84%] Linking CXX executable brick_facet
**ld: library not found for -lDRAWEXE**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/brick_facet] Error 1
make[1]: *** [test/CMakeFiles/brick_facet.dir/all] Error 2
make: *** [all] Error 2

I have CASROOT set and also DYLD_LIBRARY_PATH

**Comment by iMichka** [comment]
Please fill out the full issue template. I have even no clue about which formula we are talking about here.

**Comment by rajeeja** [comment]
Will do. THanks. It says on the title: OCE

**Comment by iMichka** [comment]
I was focused on DRAWEXE and missed the oce. We are getting a lot of issue reports for different packages, so filling out the issues clearly helps a lot.
