### ISSUE TITLE
how to try a lammps example in mac os x using homebrew in a single processor?

### ISSUE THREAD

**Issue by maryamalq** [Homebrew/homebrew-science#5496]
I installed lammps using homebrew just as the steps noted on the website. I reached the point where to test lammps by typing ( brew test lammps -v ) and it did work with no error. I want to try examples to understand the program better. My attempt to do so is the following:
I want to lammps/example directory through : `cd /usr/local/share/lammps/examples`
and then listed some examples: `ls`
I choose the ELASTIC example directory and choose the file in.elastic to run. through : `lammps -in in.elastic`  and this was the output: `PMIx has detected a temporary directory name that results
in a path that is too long for the Unix domain socket`

I tried running the example through (lmp_linux and mpi ) commands but it says that the command is not found.

please help I really don't know anything about the program..and I want to test an example in a single-processer before trying working on parallel
Any help is appreciated, Thanks !!

**Comment by iMichka** [comment]
Next time, please fill out the full issue template.

I think this is not related to homebrew. There is a FAQ entry in mpi for your error
https://www.open-mpi.org/faq/?category=osx#startup-errors-with-open-mpi-2.0.x

> The workaround for the Open MPI 2.0.x and v2.1.x release series is to set the TMPDIR environment variable to /tmp or other short directory name.
