### ISSUE TITLE
Error building opencv --with-java

### ISSUE THREAD

**Issue by mohammedsaleh21** [Homebrew/homebrew-science#5498]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
the error message i am getting is "No such file or directory - /private/tmp/opencv3-20170425-7114-k4n6pn/3rdparty/ippicv/downloader.cmake"
#### The complete command that you issued:
brew install opencv3 --HEAD --with-contrib --with-java
#### Gist with output of `brew doctor`:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
#### Output of `brew config`:
HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 56719a24e9d4f30ab0730047c6306eeb7df79515
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
Please fill out the FULL issue template. We won't be able to help you without this ...

**Comment by mohammedsaleh21** [comment]
I did

**Comment by iMichka** [comment]
Right, I wrote this and you were not done writing, sorry :)

We do not support `--HEAD` builds. These are reserved for people knowing what they are doing, but we can not help debug this directly. Could you try without `--HEAD`? And could you try with/without `contrib` and/or `java`, to see which one of the flags makes this fail?

**Comment by chuk966** [comment]
I had same trouble and removing --HEAD helps

**Comment by iMichka** [comment]
Thanks. Closing here. It may be good to report the issue upstream though, if we do not want to have this in the next release.

If there any new trouble installing opencv3, please open a new issue with a non head build. Thanks.
