### ISSUE TITLE
Unable to install brew install gcc --without-multilib

### ISSUE THREAD

**Issue by RachitKansal** [Homebrew/homebrew-science#5513]
ran brew gist-logs gcc, here:
https://gist.github.com/5781768991cc37fa6f1166b0ee7ead13
please help

**Comment by RachitKansal** [comment]
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [lto1] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

This is the error I get

**Comment by RachitKansal** [comment]
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [lto1] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

**Comment by iMichka** [comment]
Hi. Please always fill out the issue template.

This formula is in homebrew-core, please report that there. Thanks.
