### ISSUE TITLE
Brew edition of NetCDF 4.4.1.1 not working with OPeNDAP 

### ISSUE THREAD

**Issue by wjcapehart** [Homebrew/homebrew-science#5514]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

N/A

#### Brief summary of issue:

NetCDF 4.4.1.1 using MacOS 10.12.4 is not working with OPeNDAP.  

This seems to be an issue that is permeating through a number of builds that leverage netcdf such as the NCAR Command Language (NCL) distributions including the one on EarthSystemGrid that the brew cask for NCL uses. 

When using the science/netcdf build requests to the OPeNDAP files fails with a segmentation fault both with netcdf program _**ncdump**_ and with code that uses the brew's netcdf library.   

Example of both are below in the appropriate ticket section.  This is increasingly an issue since we in the community are using OPeNDAP more and more.

I was able to get the netcdf source code downloaded from UNIDATA to successfully process the OPeNDAP site housed data, but unfortunately I am new to git-hubbing and my git-Fu™ is weak and I am afraid of making a dogs breakfast of any existing builds that work.  

Is there someone with more skill than me who can better troubleshoot this?

Much Obliged,
Bill Capehart
SD School of Mines

#### The complete command that you issued:

**Output of Generic ncdump command to a generic OPeNDAP server file **

[wjc@mandrenke:/usr/local]% ncdump http://test.opendap.org/opendap/data/nc/3fnoc.nc
Segmentation fault: 11

**Output of Fortran Test File (link below) **

_Source Code._
https://github.com/wjcapehart/BWW_AWS_NCL/blob/master/opendap_read.f90

_Output:_
[wjc@mandrenke:~/GitHub/BWW_AWS_NCL]% ./opendap_read 
 testing file http://test.opendap.org/opendap/data/nc/3fnoc.nc

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x10e09c6a9
#1  0x10e09ba75
#2  0x7fffb4d8db39
#3  0x10e2db1d1
#4  0x10e2d1c14
#5  0x10e2d47e9
#6  0x10e2cc9ec
#7  0x10e2e3087
#8  0x10e291281
#9  0x10e290fec
#10  0x10e013e89
#11  0x10e066706
#12  0x10e00ab17
#13  0x10e00adb4
Segmentation fault: 11

#### Gist with output of `brew doctor`:

https://gist.github.com/wjcapehart/61928c5d3faec6a3ba5e8bdfaa72f2ff

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/wjcapehart/04b32eb8455b62e1b0938cf4f7d7987c

#### Output of `brew config`:

https://gist.github.com/wjcapehart/78acc490219b8b99e9705c79489e65dc

**Comment by iMichka** [comment]
Hi. Thanks for reporting this.

Looking at your logs, everything installed fine. The netcdf test suite was run and all the tests passed. So this error is not covered by their tests.

This may be difficult to debug from our side. The error could be that we passed some wrong compilers flags during the build, which can always happen. It would be great to compare our build with a manual build done "outside" of homebrew. You should probably report this error upstream, because for the moment I see nothing what may be wrong on our side.

**Comment by wjcapehart** [comment]
Thanks Michael.  I also saw that it cleared the dap tests in the log which is perplexing since it clearly doesn't on the programming tests.   I WAS able to get a local build to compile a version that was able to use OPeNDAP outside of homebrew and the ncdump query to worked for it, but I am not sure how to make it manifest in brew itself with hacking the netcdf.rb file and pointing to libraries and such.  Despite being the Linux "emergency sysadmin" in my org for now almost 10 years I am very much a n00b at Github and homebrew...

**Comment by iMichka** [comment]
I tried: `ncdump http://test.opendap.org/opendap/data/nc/3fnoc.nc` on my MacOS 10.12.4, and it seems to work for me (at least it has been outputting numbers since 5 minutes, so I guess it correctly works). I stopped it meanwhile (do I need to wait until the end to test it completely?

You may test: `brew uninstall netcdf && brew install netcdf -s', which will rebuild netcdf from source. Maybe there is some architecture/processor related problem here.

**Comment by wjcapehart** [comment]
Michka:  The data that is streaming is the metatdata and data from the `3fnoc.nc' converted from th binary netCDF format to human-readable ASCII.    If you get that stream with the command in question it means that you have been able to reach the OPeNDAP server and crack and read the remote file in question.  (A control-C is fine at that point to end the data running across your terminal).  I've tried the build-from-source option and it still reports the same Segmentation Faults.  

Unfortunately I am still getting segmentation faults even with the build-from-source mode on.

**Comment by iMichka** [comment]
I think your best bet is to ask the netcdf people if they could help you debug the segfault. You will probably need to use a debugger. Or maybe they will have an idea of what may not be working. I have no real experience in segfaults, but my intuition would be that there is a bug somewhere in netcdf. Especially if you rebuilt from source, so we can exclude some fancy architecture/processor problems.

You have also a bunch of warnings in your `brew doctor` output. Maybe you could review these carefully, these files may be messing up your setup.

For `curl`, you can `brew info curl` to see some information, and `brew cat curl` to see the formula.

**Comment by wjcapehart** [comment]
We've been working with this problem on the UNIDATA NetCDF mailing list. 

We believe we have a working resolution.  The problem is in the ~/.dodsrc file.  Removing references to certificates removed the problem.    

A previous issue was found here.

https://github.com/Homebrew/homebrew-science/pull/4847

**Comment by iMichka** [comment]
Did they say what we should be doing to make this work for you?

The patch proposed in #4847 would be to build curl with openssl, but that seems not to be the correct solution.

**Comment by iMichka** [comment]
Ok I saw the discussion here:
http://netcdf-group.1586084.n2.nabble.com/Using-NetCDF-with-OPeNDAP-on-MacOS-Sierra-homebrew-and-netCDF-dependant-software-td7576349i20.html

> It looks like this is an issue with the built-in Mac curl library dropping support for openSSL in favor of SecureTransport. SecureTransport will not read certificates, keys, etc. off of disk. If you have a .dodsrc file telling netCDF-C to use certs, keys, etc. from disk, it looks like you will trigger this issue. If you move .dodsrc, or comment the entries out, ncdump works

Seems it is fixed for you by removing the references to the certificates fixed it for you. Closing here.

**Comment by wjcapehart** [comment]
That is correct.   We have a working solution... Thanks, Michka

**Comment by iMichka** [comment]
Thanks. And sorry that we could not offer a different alternative, but we have limited ressources.
