### ISSUE TITLE
lammps: Install issues

### ISSUE THREAD

**Issue by wweiss10** [Homebrew/homebrew-science#5515]
### Indicate troubleshooting steps taken

- [ y] Ran `brew update` and retried your prior step?
- [ y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [n ] Checked that a similar issue hasn't already been filed?
- [n don't know how ] Looked up the software bug tracker if reporting a build error?
- [n ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
Error: homebrew/science/lammps: failed
Failed executing: /usr/local/Cellar/lammps/2016.11.17/bin/lammps -in /usr/local/share/lammps/bench/in.lj
/usr/local/Homebrew/Library/Homebrew/formula.rb:1840:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/lammps.rb:241:in `block in <class:Lammps>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1677:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:886:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1676:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1670:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'

#### Brief summary of issue:
I ran the code listed below and I ran into errors. This was the first command run after installation. 

#### The complete command that you issued:
 brew test lammps -v

#### Gist with output of `brew doctor`:
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.
I am very new to LAMMPS and scientific programs in general. Advice and resources would be much appreciated. Thanks.

**Comment by iMichka** [comment]
A new lammps version has just been merged. Please `brew update && brew upgrade`, and test. Thanks.

**Comment by iMichka** [comment]
Closing. Please open a new issue if you still have trouble installing this. Thanks.
