### ISSUE TITLE
hugo 0.20.6 - SHA256 mismatch

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#5520]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
brew install hugo
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://github.com/spf13/hugo/archive/v0.20.6.tar.gz
==> Downloading from https://codeload.github.com/spf13/hugo/tar.gz/v0.20.6
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 857655b69fb3e7f174011fd6774501194f1241bbb833256fd63b585b6d7a3cc0
Actual: 692e08b009430d27064821d498f1454152cbfd5f26d019c29002e6fbff8fc387
Archive: /home/linuxbrew/.cache/Homebrew/hugo-0.20.6.tar.gz
```

**Comment by jonchang** [comment]
See https://github.com/Homebrew/homebrew-core/pull/13186
