### ISSUE TITLE
snid: cannot download resource

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-science#5584]
```
==> Downloading http://hercules.berkeley.edu/database/BSNIPI/bsnip_v7_snid_templates.tar.gz
Error: Failed to download resource "snid--bsnip_templates"
```

Once this is fixed, the formula will need a revision bump due to GCC major version upgrade: https://github.com/Homebrew/homebrew-science/pull/5531

**Comment by iMichka** [comment]
I just sent an email to the maintainer, the link provided on the website is not working.

**Comment by iMichka** [comment]
Done with #5743
