### ISSUE TITLE
dyld: Library not loaded when run octave

### ISSUE THREAD

**Issue by tangyiwu** [Homebrew/homebrew-science#5585]
```
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/octave/4.2.1_1/libexec/octave/4.2.1/exec/x86_64-apple-darwin16.4.0/octave-gui
  Reason: image not found
octave exited with signal 6
```

**Comment by academikuser** [comment]
➜  elpa git:(develop) ✗ which R
/usr/local/bin/R
➜  elpa git:(develop) ✗ R -v
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/r/3.4.0/R.framework/Versions/3.4/Resources/lib/libR.dylib
  Reason: image not found
[1]    44989 abort      R -v
➜  elpa git:(develop) ✗ brew install R
Warning: homebrew/science/r-3.4.0 already installed

**Comment by academikuser** [comment]
brew reinstall r --build-from-source

or 

brew reinstall octave --build from-source    

you did an upgrade from gcc 6 to gcc 7 and then --purged the old gcc to save disk space, so you no longer have the library in the right place.

**Comment by jonchang** [comment]
I've just updated `octave`, please try `brew update && brew rm octave && brew install octave`.

**Comment by sunilshah** [comment]
brew update && brew rm octave && brew install octave  does not work.

**Comment by jonchang** [comment]
@sunilshah can you please clarify what you mean by "does not work"? Please open a new issue filling out the issue template.

**Comment by tangyiwu** [comment]
@academikuser it does work, thank you

**Comment by sunilshah** [comment]
Hi Jonchang,

The commands completed without errors but octave had the same run time error

dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/opt/qrupdate/lib/libqrupdate.1.dylib
  Reason: image not found
Abort trap: 6

What did work was symlink to gcc 6.3.0_1 library

**Comment by ilovezfs** [comment]
The qrupdate went in 4 hours ago: https://github.com/Homebrew/homebrew-science/pull/5540

So it should work now.
