### ISSUE TITLE
r has dependency on gcc@6, but only lists gcc (which has updated to 7)

### ISSUE THREAD

**Issue by hauntingEcho** [Homebrew/homebrew-science#5587]
### Indicate troubleshooting steps taken
`brew install gcc@6; ln -s /usr/local/opt/gcc@6/lib/gcc/6/ /usr/local/opt/gcc/lib/gcc/6` resolves the issue locally

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [N/A] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
running rscript after updating gives the following error:
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/r/3.4.0/R.framework/Versions/3.4/Resources/lib/libR.dylib
  Reason: image not found

#### The complete command that you issued:
r

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
(after running the steps to fix listed above)
https://gist.github.com/anonymous/6f6824c449949a36551ef8d266175c1c

#### Output of `brew config`:
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea00392776c02e7f5c13b61cd91503c794d44b71
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_77
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A

### Formula Requests:
change logic for "gcc" requirement to "gcc@6"

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ellisvalentiner** [comment]
@hauntingEcho try building R from source

```
brew uninstall R
brew install --build-from-source R
```

**Comment by jonchang** [comment]
Building R from source should not be necessary. We've updated to gcc 7.1 and are in the process of rebuilding bottles for affected formulae. Try `brew update && brew rm r && brew install r`

**Comment by tkosaka1976** [comment]
Recently, R 3.4.1_2 on sierra also show similar error.
When I installed "flowCore" of Bioconductor,
~~~
** R
** data
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
   共有ライブラリ '/usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so' を読み込めません:
  dlopen(/usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so
  Reason: image not found
ERROR: lazy loading failed for package ‘flowCore’
* removing ‘/usr/local/lib/R/3.4/site-library/flowCore’

The downloaded source packages are in
	‘/private/tmp/RtmptYkfXs/downloaded_packages’
 警告メッセージ:
 install.packages(pkgs = doing, lib = lib, ...) で:
  installation of package ‘flowCore’ had non-zero exit status
~~~

Probably, it is also problem in libgfortran.3.dylib.
Could you help me?

**Comment by hauntingEcho** [comment]
@tkosaka1976 did you try rebuilding as @ellisvalentiner mentions above?

**Comment by tkosaka1976** [comment]
Yes, I did. But always failed.

**Comment by piperod** [comment]
brew link --overwrite gcc worked for me.
