### ISSUE TITLE
Warning: Calling ENV.Og is deprecated when building the latest R.

### ISSUE THREAD

**Issue by whao** [Homebrew/homebrew-science#5597]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
<pre>
==> Upgrading homebrew/science/r --with-openblas --with-pango --with-valgrind --with-x11
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://cran.rstudio.com/src/base/R-3/R-3.4.0.tar.gz
Already downloaded: /Users/whao/Library/Caches/Homebrew/r-3.4.0.tar.gz
==> Patching
patching file src/modules/lapack/vecLibg95c.c
Hunk #1 succeeded at 2 with fuzz 2.
<b>Warning</b>: Calling ENV.Og is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/r.rb:96:in `install'
Please report this to the homebrew/science tap!
</pre>
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
Thanks for filing this issue @whao. Do you mind opening a pull request that changes this line to add `-g -O0` (or whatever optimization level you need for valgrind) to cflags? Feel free to ping me or any other maintainer for help.

**Comment by iMichka** [comment]
Pull request opened here: #5766

**Comment by iMichka** [comment]
#5766 is merged. Closing here.
