### ISSUE TITLE
curl: (22) The requested URL returned error: 503 Error: Failed to download resource "gnuplot"

### ISSUE THREAD

**Issue by jcminerlanl** [Homebrew/homebrew-science#5606]
FAILURE to replace gnuplot with a modification to include --with-aquaterm
`brew update`
`brew tap homebrew/science`
`brew install gnuplot --with-aquaterm --with-qt4 --with-test`

### Indicate troubleshooting steps taken
`brew doctor` (out of date Xcode)
`brew prune`
Remove 3 symbolic links and 10 directories.

### Bug reports / build errors:
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.6/gnuplot-5.0.6.tar.gz

curl: (22) The requested URL returned error: 503
Error: Failed to download resource "gnuplot"
Download failed: https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.6/gnuplot-5.0.6.tar.gz

#### Brief summary of issue:
The issue appears to be a failure to download from source forge.
gnuplot is located at https://sourceforge.net/projects/gnuplot/files/gnuplot/
This location is different than where homebrew attempts to download from

#### Link output by `brew gist-logs <formula>`:
`brew gist-logs gnuplot`
Error: No logs.

#### Output of `brew config`:
HOMEBREW_VERSION: 1.2.0-60-ge4ecf6d
ORIGIN: https://github.com/Homebrew/brew
HEAD: e4ecf6d6bc30914cc3bcb0a45ff2a573a920a844
Last commit: 35 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c4f788f512c3fdb9f83dace59b2194a778c13bd
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.10.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121, 1.8.0_112, 1.8.0_102
macOS: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
What does `brew fetch -s gnuplot` return?

**Comment by jcminerlanl** [comment]
https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.6/gnuplot-5.0.6.tar.gz

This fails just the same as `brew install gnuplot --with-aquaterm --with-qt@5.7`

curl: (22) The requested URL returned error: 503
Error: Failed to download resource "gnuplot"
Download failed: https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.6/gnuplot-5.0.6.tar.gz

**Comment by iMichka** [comment]
Does the manual download of this file works form your browser? I could install gnuplot from source without problem. Maybe sourceforge is blocked for you on your actual connection?

**Comment by iMichka** [comment]
Closing here due to inactivity. Please tell us if you still encounter problems, but I do believe this was either a transient connection problem or sourceforge being blocked on your network.
