### ISSUE TITLE
IGV sha256 mismatch

### ISSUE THREAD

**Issue by chrisgulvik** [Homebrew/homebrew-science#5622]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
`==> Upgrading homebrew/science/igv 
==> Downloading https://www.broadinstitute.org/igv/projects/downloads/IGV_2.3.92.zip
==> Downloading from http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.92.zip
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 4e499c706e81c0ef1b88652f3cfcc18e6af3f1e22b0aaef359cfa325a7c32d4b
Actual: 7850481aa7bc5dec8790b0b1d6d6c23c8ee22ed4df1ab1914e6fa3e4e5ee3eeb
Archive: $HOME/.cache/Homebrew/igv-2.3.92.zip
To retry an incomplete download, remove the file above.`

#### Brief summary of issue:
SHA256 changed for the same file. Looks like the beginning of a pattern based on issue #4378

#### The complete command that you issued:
`brew update && brew upgrade`

#### Output of `brew config`:
`HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 5f808f9919f1752cee09b520b08f6d6605f7b732`

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment]
Thanks for reporting this issue @chrisgulvik. I've updated the `igvtools` formula so please `brew update && brew reinstall igvtools`
