### ISSUE TITLE
R searches for libgfortran.3.dylib but gcc 7.1 has libgfortran.4.dylib 

### ISSUE THREAD

**Issue by pat-s** [Homebrew/homebrew-science#5623]
Reinstalled `r` bottle (3.4.0_1) and `gcc` (7.1) and facing the following error:

`Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.3.dylib`

whereas in `/usr/local/opt/gcc/lib/gcc/7/` only `libgfortran.4.dylib` exists. 

A priori I tried the workaround of #5587 (also building from source) which did not work for me. @jonchang did you already built the new R bottles?

**Comment by jonchang** [comment]
Hi @pat-s, I can't reproduce this error. `brew install r` followed by `brew linkage r` reports that R is linked against `/usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib`. What commands were you running, and could you fill out the full issue template next time? Thanks

**Comment by pat-s** [comment]
`brew linkage r` did the trick - wasn't aware of that command. Any idea what could have caused the wrong linking? 
I did not do any adjustments, `r` was just upgraded normally. It was running smooth for some days since the error only appears if a package needs `gcc` during installation.

Next time I use the template, sorry for that. Thanks for your help!
