### ISSUE TITLE
opencv3 build error

### ISSUE THREAD

**Issue by thinkpiece** [Homebrew/homebrew-science#5727]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../../../../3rdparty/lib/liblibprotobuf.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 13%] Built target libprotobuf
make: *** [all] Error 2

#### Brief summary of issue:

Hi, there. Recently I cleaned up my MacBook and tried to install opencv3 with python3 support. But I failed it and it seems that there is an error between Xcode and protobuf. Not sure.

#### The complete command that you issued:

`brew install opencv3 --with-contrib --with-cuda --without-python --with-python3 --with-tbb`
Also tried other cases such as --with-nonfree

#### Gist with output of `brew doctor`:

It says 'Your system is ready to brew.'

#### Link output by `brew gist-logs <formula>`:

Here's the result link of `brew gist-logs opencv3`
https://gist.github.com/thinkpiece/fb3374cf6d944f06f575058ce580cc97

#### Output of `brew config`:

HOMEBREW_VERSION: 1.2.1-9-gf0dc1d96c
ORIGIN: https://github.com/Homebrew/brew
HEAD: f0dc1d96c50551be69ea418148a9bc2d72cfaf16
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ee82bb8a9620878bf7ab1e2ecfc16e7145b24f07
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by thinkpiece** [comment]
found that it was nvcc error

**Comment by jclosure** [comment]
@thinkpiece I have the same issue.  What version of Xcode CLT works?
