### ISSUE TITLE
pyROOT with root6.08.06 with Python3.6.1 not available

### ISSUE THREAD

**Issue by HealthyPear** [Homebrew/homebrew-science#5737]
### Indicate troubleshooting steps taken

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] Checked that a similar issue hasn't already been filed?
- [ x] Looked up the software bug tracker if reporting a build error?
- [ x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

pyROOT6 with Python3 not available, "import ROOT" from python3 gives "no module named ROOT".

#### Brief summary of issue:

ROOT6.08.06 installed via brew with Python3 support did not build libPyROOT.so and ROOT.py which could not be found in the updated locate database where they should be, e.g. $ROOTSYS/lib.

#### The complete command that you issued:

brew install root6 --with-fftw --with-python3 --with-xrootd --without-python

#### Gist with output of `brew doctor`:

Warning: Setting DYLD_* vars can break dynamic linking.
Set variables:
  DYLD_LIBRARY_PATH: /Users/micheleperesano/Applications/ROOT/v5.34.36/lib:/Users/micheleperesano/Applications/MARS/v2.17.5:

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/micheleperesano/Applications/ROOT/v5.34.36/bin/root-config

Warning: Your XQuartz (2.7.8) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc

#### Link output by `brew gist-logs <formula>`:

Error: No logs.

#### Output of `brew config`:

HOMEBREW_VERSION: 1.2.1-42-g04420d0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 04420d07a4c127b9a85013f31619eed4b88ec94b
Last commit: 13 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea7fc337b0c3a082da4e7c77e39e574d4dc8a297
Core tap last commit: 35 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.8 => /opt/X11

**Comment by wickles** [comment]
> brew install root6 --with-fftw **--with-python3** --with-xrootd **--without-python**

Don't the two python arguments contradict one another? I imagine `--without-python` means without ANY python support, not just removing the python2 support if that's what you were going for. 

Also, since pyROOT gets compiled and linked with homebrew's python, you must run it with homebrew's python, i.e. `/usr/local/python(3)`. However this line 
```
Warning: Python is installed at /Library/Frameworks/Python.framework
```
indicates that you have a third party python installation with binaries probably linked in /usr/local/bin and overriding homebrew's python. If it's the official python distribution, you can safely delete it since there's no point installing it in addition to the system python and homebrew's python.

**Comment by joeycarter** [comment]
I'm also having trouble with this. When I run,

`brew install root6 --with-python3`

I get the error,

`Root6: Does not support building both python 2 and 3 wrappers`

Then when I try,

`brew install root6 --with-python3 --without-python`

it runs, but I looked at the flags that are passed to `cmake` and I see,

`-Dpython=OFF -Dpython3=ON`

The relevant python flags `PYTHON_EXECUTABLE`, `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` all point correctly to the respective python3 locations, so ostensibly it should work. However in the [ROOT build documentation](https://root.cern.ch/building-root), there is no option for `-Dpython3`, so all it sees is `-Dpython=OFF` and so the PyROOT libraries aren't built.

I haven't tried this but I'm wondering if `brew install root6 --with-python3 --without-python` would work if `-Dpython=ON` were passed to `cmake`. Or even nicer if `brew install root6 --with-python3` would do this automatically.

**Comment by wickles** [comment]
A `grep` or `ack` shows that the build configuration does use the `python3` flag so I think it's just missing from the documentation.

**Comment by iMichka** [comment]
root and root6 have been migrated to homebrew core (https://github.com/Homebrew/homebrew-core). Please update and test again with the current version; and report any issue there. Thanks.
