### ISSUE TITLE
Graph Tool doesn't work inside a virtualenv

### ISSUE THREAD

**Issue by zfrenchee** [Homebrew/homebrew-science#5741]
#### Brief summary of issue:

I've `brew install`ed graph-tool via `brew install graph-tool --with-python3` and although I can now import graph tool in both python2 and python3 *outside* a virtualenv, as soon as I step into a virtualenv, I can't access graph tool. Why is this? 

```
~/Documents/mmsb » python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graph_tool
>>>
------------------------------------------------------------
~/Documents/mmsb » source venv/bin/activate
------------------------------------------------------------
~/Documents/mmsb » python
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graph_tool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'graph_tool'
>>>
```

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/zfrenchee/5c88090fcaa555f9b1decab7af5e09cf

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 390578c329203c599a07d5cfdd7c0c453127dcff
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

**Comment by tdsmith** [comment]
By default, virtualenvs don't have access to packages installed elsewhere on the system. You can create your virtualenvs with [--system-site-packages](https://virtualenv.pypa.io/en/stable/userguide/#the-system-site-packages-option) to get around it.

Alternatively, you could write a .pth file containing `/usr/local/opt/graphtool/lib/pythonx.y/site-packages` to your virtualenv's site-packages folder to _only_ pull in graph-tool. .pth files are documented on the [site module doc page](https://docs.python.org/3/library/site.html).

I'll close this since this isn't a Homebrew issue; good luck!

**Comment by zfrenchee** [comment]
Thanks!

**Comment by zfrenchee** [comment]
@tdsmith is there a way to do this retroactively, e.g. add graph_tool to a venv that I built a long time ago?

**Comment by tdsmith** [comment]
Yes, the second mechanism with the pth file.
