### ISSUE TITLE
root6 failed to build on <10.12.4>

### ISSUE THREAD

**Issue by apuignav** [Homebrew/homebrew-science#5745]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
Cannot find them... Wondering if it's the warnings (suspicious warnings in stdlib).

#### Brief summary of issue:
Trying to install root6 with fftw support (so, no bottle) fails, although I don't see any errors...

#### Gist with output of `brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/persistent/cPersistence.h
  /usr/local/include/python2.7/persistent/ring.h
brew install ro
Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  dirmngr
  gpg-agent
```

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/anonymous/4fd082b8e8a27057db2a4d6a0f99615b

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2856b9e1e89fba013da875f7c7486379569fca46
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by iMichka** [comment]
Looking at the full log file:
https://gist.githubusercontent.com/anonymous/4fd082b8e8a27057db2a4d6a0f99615b/raw/a5f62d35fa00260d062e364840108f45b91f97f8/02.make

> [ 73%] Building CXX object graf2d/postscript/CMakeFiles/Postscript.dir/src/TPDF.cxx.o
cd /tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/graf2d/postscript && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/include/root -I/tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/include  -m64 -pipe -W -Wshadow -Wall -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -std=c++11 -DR__HAVE_CONFIG -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -o CMakeFiles/Postscript.dir/src/TPDF.cxx.o -c /tmp/root6-20170526-10084-3r5xn/root-6.08.06/graf2d/postscript/src/TPDF.cxx
/tmp/root6-20170526-10084-3r5xn/root-6.08.06/graf2d/gviz/src/TGraphEdge.cxx:18:10: fatal error: 'gvc.h' file not found
#include <gvc.h>
         ^
1 error generated.
make[2]: *** [graf2d/gviz/CMakeFiles/Gviz.dir/src/TGraphEdge.cxx.o] Error 1
make[1]: *** [graf2d/gviz/CMakeFiles/Gviz.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

The formula may need a depends_on => "graphviz"? Could you try this out?

**Comment by apuignav** [comment]
Oh, interesting! `graphviz` is installed, and the header file is there, but maybe it's not finding it because it's in the `graphviz` folder?

```
[7:02]~$ ls /usr/local/include/graphviz/
arith.h               geom.h                gvc.h                 gvconfig.h            gvplugin_loadimage.h  pack.h                types.h
cdt.h                 graphviz_version.h    gvcext.h              gvplugin.h            gvplugin_render.h     pathgeom.h            usershape.h
cgraph.h              gv.cpp                gvcjob.h              gvplugin_device.h     gvplugin_textlayout.h pathplan.h            xdot.h
color.h               gv.i                  gvcommon.h            gvplugin_layout.h     gvpr.h                textspan.h
[7:02]~$ brew upgrade graphviz
Error: graphviz 2.40.1 already installed
[7:03]~$ brew info graphviz
graphviz: stable 2.40.1 (bottled), HEAD
Graph visualization software from AT&T and Bell Labs
http://graphviz.org/
/usr/local/Cellar/graphviz/2.40.1 (536 files, 12.9MB) *
  Poured from bottle on 2017-03-18 at 20:31:55
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphviz.rb
==> Dependencies
Build: pkg-config ✔
Required: libtool ✔, gd ✔, libpng ✔
Optional: pango ✘, gts ✘, librsvg ✘, freetype ✔
==> Requirements
Optional: x11 ✔
==> Options
--with-app
	Build GraphViz.app (requires full XCode install)
--with-bindings
	Build Perl/Python/Ruby/etc. bindings
--with-freetype
	Build with freetype support
--with-gts
	Build with GNU GTS support (required by prism)
--with-librsvg
	Build with librsvg support
--with-pango
	Build with Pango/Cairo for alternate PDF output
--with-x11
	Build with x11 support
--HEAD
	Install HEAD version
```

**Comment by apuignav** [comment]
Investigating a bit the logfile, I see some objects that are built with `-I` to the correct folder ,eg,

```
[ 73%] Building CXX object graf2d/gviz/CMakeFiles/Gviz.dir/src/TGraphEdge.cxx.o
cd /tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/graf2d/gviz && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/include/root -I/usr/local/include/graphviz -I/tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/include  -m64 -pipe -W -Wshadow -Wall -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -std=c++11 -DR__HAVE_CONFIG -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -o CMakeFiles/Gviz.dir/src/TGraphEdge.cxx.o -c /tmp/root6-20170526-10084-3r5xn/root-6.08.06/graf2d/gviz/src/TGraphEdge.cxx
```

While the particular one that fails does not have that include:

```
[ 73%] Building CXX object graf2d/postscript/CMakeFiles/Postscript.dir/src/TPDF.cxx.o
cd /tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/graf2d/postscript && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -I/tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/include/root -I/tmp/root6-20170526-10084-3r5xn/root-6.08.06/build_dir/include  -m64 -pipe -W -Wshadow -Wall -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -std=c++11 -DR__HAVE_CONFIG -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -o CMakeFiles/Postscript.dir/src/TPDF.cxx.o -c /tmp/root6-20170526-10084-3r5xn/root-6.08.06/graf2d/postscript/src/TPDF.cxx
/tmp/root6-20170526-10084-3r5xn/root-6.08.06/graf2d/gviz/src/TGraphEdge.cxx:18:10: fatal error: 'gvc.h' file not found
```
I'm not sure if this is useful or not...

**Comment by iMichka** [comment]
Did you try to edit the formula and add the `depends_on => "graphviz"` line? Just to be sure.

**Comment by apuignav** [comment]
I added `depends_on "graphviz" => :optional` but the result is the same.

**Comment by iMichka** [comment]
@apuignav Could you try with the dev version? https://root.cern.ch/downloading-root
Just edit the formula, change the URL and the sha256.

**Comment by apuignav** [comment]
I tried:

```
  url "https://root.cern.ch/download/root_v6.09.02.source.tar.gz"
  sha256 "5348096084adea514297050884baa33f6cf6fd9e91e83e9967c6f07528588639"
```

Same result :-(

**Comment by iMichka** [comment]
Just to be sure, if you do: `brew install root6 -s`, it works? It just fails with the fftw option?
If that is the case we will need to dive into their build setup and look why the flags are not passed ...

**Comment by apuignav** [comment]
It doesn't work either! Logs are uploaded here: https://gist.github.com/e50c7eb89cc748b7d50a9c89d8a714b8

`brew doctor` looks ok:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/persistent/cPersistence.h
  /usr/local/include/python2.7/persistent/ring.h
```

**Comment by iMichka** [comment]
I ran a local build to see what happens.

If I uninstall `graphviz`, and build with `brew install root6 -svd`, I see:
-- Looking for Graphviz
-- Could NOT find GRAPHVIZ (missing:  GRAPHVIZ_INCLUDE_DIR GRAPHVIZ_cdt_LIBRARY GRAPHVIZ_gvc_LIBRARY GRAPHVIZ_graph_LIBRARY GRAPHVIZ_pathplan_LIBRARY) 
-- Graphviz not found. Switching off gviz option

This build goes to the end and correctly work. This means that if no graphviz is installed, everything is fine as that part of the build is disabled. This is how the bottles were built for root6, as there was no graphviz installed on the build bot (clean environment for the build).

Now, if you had graphviz installed, it will pick up graphviz and try to build that part of the code. You may have graphviz installed through a manual installation or as a dependency for another formula.

My theory is that this won't work because we filter out include flags, so if we do not have the graphviz dependency explicitly defined in the formula, the include paths may end up being removed.

It should have been `depends_on "graphviz"` instead of `depends_on "graphviz" => :optional`.
I will run multiple builds to test my theory, this may take a little bit of time.

**Comment by iMichka** [comment]
My theory seems to be correct. I opened a pull request.
You can test this with:
> brew pull https://github.com/Homebrew/homebrew-science/pull/5788
> brew install root6 -s

Once you are done you can do a `brew update-reset` to drop the temporary fix. Could you test this?

**Comment by apuignav** [comment]
Thanks, I can confirm it works!

Also `brew install root6 --with-fftw` is working 😄 

However, I see this warning:

```
Warning: homebrew/science/root6 dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

But I am pretty sure this has nothing to do with the fix...

**Comment by iMichka** [comment]
PR merged; closing here.

The warning is unrelated.
