### ISSUE TITLE
petsc bottle is ahead of openmpi version.

### ISSUE THREAD

**Issue by bhelenbr** [Homebrew/homebrew-science#5747]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
petsc has a test that often breaks when I install from a bottle:  

if (OMPI_MAJOR_VERSION != PETSC_HAVE_OMPI_MAJOR_VERSION) || (OMPI_MINOR_VERSION != PETSC_HAVE_OMPI_MINOR_VERSION) || (OMPI_RELEASE_VERSION != PETSC_HAVE_OMPI_RELEASE_VERSION)
#    error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"

#### Brief summary of issue:

Right now I have the most recent openmpi installed with the version:

#define OMPI_MAJOR_VERSION 2
#define OMPI_MINOR_VERSION 1
#define OMPI_RELEASE_VERSION 0

but the latest version of petsc (3.7.6_2) from bottle installs with 

#define PETSC_HAVE_OMPI_MINOR_VERSION 1
#define PETSC_HAVE_OMPI_MAJOR_VERSION 2
#define PETSC_HAVE_OMPI_RELEASE_VERSION 1

This causes petsc to throw errors when you try to use it.

#### The complete command that you issued:
compiling my own code with petscksp.h included.

#### Link output by `brew gist-logs <formula>`:

brew gist-logs petsc
https://gist.github.com/316e1d164ee1df43536066e37ff8175

#### Output of `brew config`:

brew config
HOMEBREW_VERSION: 1.2.1-96-gfb33acbb
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb33acbbe47162adf90e92cbb6b244f26a5a346e
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e2bf7ff3fccd4ebf7f0b3bb18d5b1577052982d7
Core tap last commit: 8 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by bhelenbr** [comment]
Actually, when I just found that when I browse the github repository openmpi is at version 2.1.1 not 2.1.0.  I can't figure out how to get my local version to update though.

**Comment by ilovezfs** [comment]
```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e2bf7ff3fccd4ebf7f0b3bb18d5b1577052982d7
Core tap last commit: 8 weeks ago
```
Are you on a branch maybe?

**Comment by bhelenbr** [comment]
That was it.  Thanks.
