### ISSUE TITLE
R: Missing libRlapack.dylib for v3.4

### ISSUE THREAD

**Issue by pat-s** [Homebrew/homebrew-science#5750]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
In dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/3.4/site-library/kernlab/libs/kernlab.so':
  dlopen(/usr/local/lib/R/3.4/site-library/kernlab/libs/kernlab.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/kernlab/libs/kernlab.so
  Reason: image not found
```

#### Brief summary of issue:

When trying to install package `kernlab` binary. Missing several .dylib files in R 3.4

```
ls /usr/local/Cellar/r/3.4.0_1/R.framework/Versions/3.4/Resources/lib
libR.dylib	libRmath.a	libRmath.dylib
```

```
ls /Library/Frameworks/R.framework/Versions/3.3/Resources/lib
libR.dylib		libRblas.0.dylib	libRblas.dylib.dSYM	libRlapack.dylib.dSYM	libgcc_s_x86_64.1.dylib	libquadmath.0.dylib	libreadline.dylib
libR.dylib.dSYM		libRblas.dylib		libRlapack.dylib	libgcc_s.1.dylib	libgfortran.3.dylib	libreadline.5.2.dylib
```

`/Library/Frameworks/R.framework/Versions/3.4/` does not even exist. 

I reinstalled R several times using the bottle and some options. Current build info:

```ruby
brew info R
homebrew/science/r: stable 3.4.0 (bottled), HEAD
Software environment for statistical computing
https://www.r-project.org/
/usr/local/Cellar/r/3.4.0_1 (2,247 files, 59.3MB) *
  Built from source on 2017-05-29 at 13:56:31 with: --without-accelerate --with-openblas --with-x11
```

#### Output of `brew config`:

**Comment by iMichka** [comment]
Hi. I do not know what is broken but I can confirm that the files are missing. Maybe we need to do something different in the build setup for this R version? Just to let you know that nobody is currently working on this.

**Comment by pat-s** [comment]
Thanks for your reply @iMichka. In the meantime I somehow managed to install `kernlab`. However, I do not really remember what I did in particular but it involved several new builds (and compiling attempts) of R and `kernlab` and at some time it worked. 

Seems to be a niche/local problem as nobody else reported it so far.

**Comment by iMichka** [comment]
Then I'll close this. If somebody really needs to fix this, he can do it. But we will not be able to provide much support for the moment. Pull requests are welcome. Thanks.
