### ISSUE TITLE
gubbins: influences on quast

### ISSUE THREAD

**Issue by tmozgach** [Homebrew/homebrew-science#5752]
Hello @ilovezfs ,

I run the following script: 
```
RUN brew install homebrew/science/matplotlib
RUN brew  tap homebrew/science
RUN brew install gubbins
RUN brew install quast
``` 

I got the following error:
```
Installing quast from homebrew/science
quast: Unsatisfied dependency: matplotlib
Homebrew does not provide special Python dependencies; install with:
  `pip install matplotlib`
Error: An unsatisfied requirement failed this build.
The command '/bin/sh -c brew install quast' returned a non-zero code: 1 
```

It seems that gubbins rewrites matplotlib. 

Please look at your  ( @ilovezfs  ) previous commit:
https://github.com/Homebrew/homebrew-science/commit/dc46cbca6fbf49651ec2861eb443d817a25cfc0a

Was It important reason to add a "without-python" option? Could you please tell me how to fix this problem in the best  way?

**Comment by tmozgach** [comment]
@ilovezfs could you please look at this problem?

**Comment by sjackman** [comment]
I believe this issue is resolved now. Can you please try it again?

**Comment by tmozgach** [comment]
@sjackman  I tried again the above commands, the same error.

**Comment by sjackman** [comment]
Open a PR against `quast` and change
```diff
-  if OS.mac? && MacOS.version <= :mountain_lion
+  if !OS.mac? || MacOS.version <= :mountain_lion
    depends_on "matplotlib"
  else
    # Mavericks and newer include matplotlib
    depends_on "matplotlib" => :python
  end
```

**Comment by sjackman** [comment]
Open a PR against `gubbins` and change…
```ruby
  depends_on "numpy" => ["with-python3", "without-python"]
  depends_on "pillow" => ["with-python3", "without-python"]
```
to
```ruby
  depends_on "numpy"
  depends_on "pillow"
```

**Comment by sjackman** [comment]
I believe this issue was fixed.
