### ISSUE TITLE
Missing dependency of werkzeug for Tensorflow

### ISSUE THREAD

**Issue by christopherowen** [Homebrew/homebrew-science#5777]
- Fresh brew installation
- Ran: brew install homebrew/science/tensorflow
- Install completes successfully
- Running tensorboard gives the following dependency error on werkzeug:
```
host:~ user$ tensorboard 
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/usr/local/lib/python2.7/site-packages/tensorflow/tensorboard/tensorboard.py", line 28, in <module>
    from werkzeug import serving
ImportError: No module named werkzeug
```

**Comment by christopherowen** [comment]
Maybe something like this could be added to the recipe?

https://github.com/ClusterHQ/homebrew-tap/blob/master/flocker-0.3.2.rb#L94-L97

**Comment by iMichka** [comment]
@christopherowen Would you like to try to open a pull request for this?
See the documentation: http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

**Comment by iMichka** [comment]
@ilovezfs I just realised that I made a small mistake: I added the `tensorflow` formula in April, after a pull request here. There is a `libtensorflow` in core since February.

The science version seems to install all the python stuff too, so I propose to copy the code from science to core, remove the `tensorflow` formula from science, and add a migration from science to core. Does that sound right?

**Comment by ilovezfs** [comment]
@iMichka I'd add an entry to tap_migrations in science, and an entry to formula_renames in core, as well as an alias in core. I probably wouldn't migrate any of the code from science over unless a user opens a PR in core proposing the changes for some reason.

**Comment by iMichka** [comment]
Ok. I'll do that.

**Comment by iMichka** [comment]
For all requests/questions/issues around tensorflow, those should be asked in homebrew-core. The formula is called `libtensorflow`. See #5837 for ref. Closing here.
