### ISSUE TITLE
tamarin-prover.rb: new bottles not in bintray

### ISSUE THREAD

**Issue by lordqwerty** [Homebrew/homebrew-science#5778]
Hi,

When running `brew install tamarin-prover`  a 401 error is encountered, therefore resulting in TAMARIN being built from source. Recently we submit a new version and it was accepted, however the bottles do not seem to exist in Bintray (https://homebrew.bintray.com/bottles-science/). Only the previous version 1.2.1 not the current recipe 1.2.2 shown in https://github.com/Homebrew/homebrew-science/blob/master/tamarin-prover.rb. 

Looking at the history I can see that BrewBot updated the bottles in https://github.com/Homebrew/homebrew-science/commit/e55dee5373ca64ffdcf1fec3d8b8f5659f1557ec#diff-d652f289929e32fb636f361ab79d76d5 but they are not on bintray. Any help?

**Comment by iMichka** [comment]
I made a PR, once the bottles are built I'll update them: #5779

**Comment by iMichka** [comment]
In fact this is not necessary; the bottles were not published, that's all. I did this manually on bintray. This should be OK now.
