### ISSUE TITLE
pymol

### ISSUE THREAD

**Issue by rbf22** [Homebrew/homebrew-science#5780]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

brew test pymol
Testing homebrew/science/pymol
==> Using the sandbox
==> /usr/local/Cellar/pymol/1.8.4.0/bin/pymol /usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/pymol_path/data/demo/pept.pdb
Last 15 lines from /Users/rfenwick/Library/Logs/Homebrew/pymol/test.01.pymol:

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

 Hit ESC anytime to toggle between text and graphics.

 Detected OpenGL version 2.0 or greater. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel HD Graphics 4000 OpenGL Engine
  GL_VERSION:  2.1 INTEL-10.25.13
/usr/local/Cellar/pymol/1.8.4.0/bin/pymol: line 4: 20076 Abort trap: 6           "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"
Error: homebrew/science/pymol: failed
Failed executing: /usr/local/Cellar/pymol/1.8.4.0/bin/pymol /usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/pymol_path/data/demo/pept.pdb
/usr/local/Homebrew/Library/Homebrew/formula.rb:1859:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1797:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1797:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/pymol.rb:41:in `block in <class:Pymol>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1694:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:887:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1693:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1687:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'

#### The complete command that you issued:
pymol

PyMOL(TM) Molecular Graphics System, Version 1.8.4.0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

 Hit ESC anytime to toggle between text and graphics.

 Detected OpenGL version 2.0 or greater. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel HD Graphics 4000 OpenGL Engine
  GL_VERSION:  2.1 INTEL-10.25.13
/usr/local/bin/pymol: line 4: 13592 Abort trap: 6           "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"

After which there is a bug report that is requested by apple.

#### Gist with output of `brew doctor`:
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/rfenwick/Codes/AMBER/amber16/bin/nc-config
  /Users/rfenwick/Codes/AMBER/amber16/bin/nf-config
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk

#### Output of `brew config`:
brew config
HOMEBREW_VERSION: 1.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 54e01d76db34a3a649c79b189873bfd0a52dbc9f
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 889f1d8cf2d2221c4a7d8c718952ad9bb9e6f6e0
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45, 1.6.0_65-b14-468
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
Hi. Pymol is broken, see for example: #5780
Not sure if your problem is the same. Seems you have trouble running the test, that is one thing; any problems at runtime?

And please fill out the while issue template if you want to get help.

**Comment by rbf22** [comment]
yes, it simply dies on execution.

**Comment by iMichka** [comment]
Err, I wanted to say: #5505

Closing as duplicate.
