### ISSUE TITLE
show aligns is missing from MUMer-3.23

### ISSUE THREAD

**Issue by hmontenegro** [Homebrew/homebrew-science#5781]
I see this:
```
  TOOLS = %w[
    combineMUMs delta-filter dnadiff exact-tandems mapview mgaps
    mummer mummerplot nucmer promer repeat-match
    run-mummer1 run-mummer3 show-coords show-diff show-snps show-tiling
  ].freeze
```
There are some tools missing in relation to a linux install: `annotate combineMUMs gaps nucmer2xfig show-aligns`

**Comment by iMichka** [comment]
@hmontenegro Would you like to try to open a pull request for this?
See the documentation: http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

**Comment by hmontenegro** [comment]
I could, but I don't use Homebrew so the patch would be untested. I discovered the issue due to [this](https://www.biostars.org/p/256511) question. I then looked at my locally installed MUMmer on linux and spotted the missing execs.

**Comment by iMichka** [comment]
I opened a PR with the changes here: #5782

**Comment by iMichka** [comment]
PR merged, the tools you had in your list should now also be delivered. Closing. Thanks.
