### ISSUE TITLE
iqtree: compile with clang

### ISSUE THREAD

**Issue by bqminh** [Homebrew/homebrew-science#5785]
Hi, is this possible to compile iqtree using clang (OpenMP version)?

Because I noticed better performance (5-10%) compared with binary compiled by GCC. Moreover, for unknown reason GCC-compiled iqtree does not scale well with increasing number of cores. This is not the case when compiled with Clang.

Thanks for your attention!
Minh (team leader of IQ-TREE software)

**Comment by iMichka** [comment]
Hi. I think that for the moment `needs :openmp` seems to set the compiler to gcc7 on mac. I do not know the details, but one would have to dive in the code to see why that is. Maybe explicitly depending on the newest llvm formula would help. Pull requests are welcome. Just to let you know that nobody is actively working on this so we will not be able to have a look at this. It is up to the community to provide improvements like this.
