### ISSUE TITLE
Error: wrong number of arguments (1 for 0) /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/pcl.rb

### ISSUE THREAD

**Issue by bin70** [Homebrew/homebrew-science#5798]
Hello! 
I want to install pal-1.7.2_1 due to my project needs.
When I use
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-science/af86b59999db7d6ccc0d5fd3612dc4f6c475e19d/pcl.rb`
then I get the error:
`Error: wrong number of arguments (1 for 0)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/pcl.rb:2:in `<class:CudaRequirement>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/pcl.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:274:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:447:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:47:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'`

I don't know how to fix this error, but I really need to install the old version pcl.
Any help would be appreciated!

**Comment by iMichka** [comment]
This is not something we are actively working on / actively supporting. You are left alone here to fix it, or find somebody in the community that can help you. Please understand that we are an understaffed open-source project, so we can not help you fix this edge case.

**Comment by bin70** [comment]
Thank you all the same for replying me out of your busy schedule :)


在 2017年7月1日，下午7:23，Michka Popoff <notifications@github.com> 写道：
