### ISSUE TITLE
gd and mummer both want to symlink  /usr/local/bin/annotate

### ISSUE THREAD

**Issue by alexstaj** [Homebrew/homebrew-science#5804]
mbp:~ Staj$ brew update
Already up-to-date.
mbp:~ Staj$ brew upgrade
==> Upgrading 1 outdated package, with result:
homebrew/science/mummer 3.23_1
==> Upgrading homebrew/science/mummer 
Error: Cannot install homebrew/science/mummer because conflicting formulae are installed.
  gd: because /usr/local/bin/annotate is a symlink belonging to gd

Please `brew unlink gd` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

Old version of mummer did not have this problem.

**Comment by iMichka** [comment]
@alexstaj We have a PR open for this. I hope we can push a fix rapidly. See #5795

If you don't need `gd`, you can temporally run `brew unlink gd`.
