### ISSUE TITLE
snoscan 0.9: new version 0.9.1 making URL invalid

### ISSUE THREAD

**Issue by gtamazian** [Homebrew/homebrew-science#5811]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried my prior step.
- [x] Ran `brew doctor`, fixed as many issues as possible and retried my prior step.
- [x] Checked that a similar issue hasn't already been filed.

### Bug reports / build errors:
```
Error: Failed to download resource "snoscan"
Download failed: http://lowelab.ucsc.edu/software/snoscan-0.9.tar.gz
```
#### Brief summary of issue:
The **snoscan** tool was updated from version 0.9 to version 0.9.1. The URL of the software archive has also changed to http://lowelab.ucsc.edu/software/snoscan-0.9.1.tar.gz, making the URL of the previous version invalid.

#### The complete command that was issued:
```
brew install snoscan
```

**Comment by iMichka** [comment]
@gtamazian Thanks for letting us know. It's a shame that they are removing older versions.

Would you like to try to open a pull request to make the change yourself? Here is the documentation that should help you to do it: http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

**Comment by iMichka** [comment]
I'm working on a pull request here: #5915

**Comment by iMichka** [comment]
Update done (#5915).
