### ISSUE TITLE
OpenCV3 Build Issue: liblibprotobuf.a has no symbols

### ISSUE THREAD

**Issue by jzhang046** [Homebrew/homebrew-science#5819]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../../../../3rdparty/lib/liblibprotobuf.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 13%] Built target libprotobuf
make: *** [all] Error 2
```

flag -DBUILD_LIBPROTOBUF_FROM_SOURCES=ON was set. 

#### Brief summary of issue:

> liblibprotobuf.a has no symbols. 

#### The complete command that you issued:

> brew install opencv3 --with-contrib --with-cuda --with-jpeg-turbo --with-quicktime --with-static --with-python3 

#### Gist with output of `brew doctor`:

> Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
[https://gist.github.com/c0c6ed6c7cd6e166b40fd7c6f5a40572](https://gist.github.com/c0c6ed6c7cd6e166b40fd7c6f5a40572)
#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.2.3-9-g3fe32053
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3fe32053a7f0d7f817a90e308ab0c62436a5c208
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4f5f667591ed133cbf48a972ed2912c507b4de1
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

**Comment by AlvarHHM** [comment]
I just run into the same error 

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../../../../3rdparty/lib/liblibprotobuf.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(atomicops_internals_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../3rdparty/lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[  8%] Built target libprotobuf
make: *** [all] Error 2

**Comment by jzhang046** [comment]
The reason was because nvcc does not support clang 8.1.0. 

I have not encountered with this problem anymore, but with an new problem that built opencv_cudafilters fails.

**Comment by iMichka** [comment]
So when `--with-cuda` is used, we should add a `fails_with :clang` in the formula, when clang is 8.1.0? What compiler is compatible is that case? A newer or older clang?

> but with an new problem that built opencv_cudafilters fails.

Please open a new issue for that.

**Comment by autosquid** [comment]
I met this problem even with ```brew install opencv --with-contrib --with-nonfree --without-python --with-python3 --without-test```

**Comment by iMichka** [comment]
opencv has been migrated to homebrew-core. Please that version and report any issue back there. Thanks.
