### ISSUE TITLE
configure failure on hdf5 

### ISSUE THREAD

**Issue by BarrySmith** [Homebrew/homebrew-science#5827]
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

hdf5 fails in configure claiming the cc (mpicc) compiler doesn't work. It does work for me on other codes.

#### The complete command that you issued:

brew upgrade hdf5

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/anonymous/fd397496b5d3a13c57bfb7bc8eb304d7

#### Output of `brew config`:

$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 89c229f2d23d6a8a80754f2ba11e474a4b73b1b0
Core tap last commit: 58 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.9 => /opt/X11

**Comment by iMichka** [comment]
Hi.

Brew doctor says:
> Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  open-mpi

Please do this. It should add mpi back. And then you can try to reinstall hdf5.

**Comment by BarrySmith** [comment]
Michka,

      This is a goofy feature of home-brew with respect to MPI and shouldn't be a problem. 

       The reason open-mpi is not linked is because I am using mpich and they both can't be linked at the same time. Brew has a working mpi MPICH linked and it works for other packages so I don't think this is why the hdf5 fails.

    Barry

**Comment by iMichka** [comment]
I extracted the build error from the log file:

```
configure:4503: /usr/local/bin/mpicc --version >&5
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:4514: $? = 0
configure:4503: /usr/local/bin/mpicc -v >&5
mpicc for MPICH version 3.2
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.12.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -o a.out -L/usr/local/lib -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -headerpad_max_install_names -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
... rest of stderr output deleted ...
configure:4514: $? = 1
configure:4503: /usr/local/bin/mpicc -V >&5
clang: error: unsupported option '-V -I/usr/local/Cellar/mpich/3.2_2/include'
configure:4514: $? = 1
configure:4503: /usr/local/bin/mpicc -qversion >&5
clang: error: unknown argument: '-qversion'
configure:4514: $? = 1
configure:4534: checking whether the C compiler works
configure:4556: /usr/local/bin/mpicc       conftest.c  >&5
ld: file not found: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4560: $? = 1
configure:4598: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "HDF5"
| #define PACKAGE_TARNAME "hdf5"
| #define PACKAGE_VERSION "1.10.1"
| #define PACKAGE_STRING "HDF5 1.10.1"
| #define PACKAGE_BUGREPORT "help@hdfgroup.org"
| #define PACKAGE_URL ""
| #define PACKAGE "hdf5"
| #define VERSION "1.10.1"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4603: error: in `/private/tmp/hdf5-20170615-37566-1yyg02g/hdf5-1.10.1':
configure:4605: error: C compiler cannot create executables
See `config.log' for more details
```

There are a bunch of errors in there. They may not all be relevant, it's just the config tool that checks different things; so errors are sometimes expected.

> clang: error: unsupported option '-V -I/usr/local/Cellar/mpich/3.2_2/include'

I just found a similar question here:
https://stackoverflow.com/questions/40100439/what-causes-clang-error-unsupported-option-v-isystem-usr-local-include-wit

> In fact, I don't know what's happened, But I know after I upgrade to Sierra, /Library/Developer/CommandLineTools/usr/bin/Clang's version is 8.0, but before I upgrade, xcode version is 8.0, but /Library/Developer/CommandLineTools/usr/bin/Clang's version is 7.0, that's the key

That's all I could find for the moment.

**Comment by iMichka** [comment]
@BarrySmith I will close this issue. We do not have the ressources to work on that edge case. Of course we would like to help but we are understaffed. You are left alone for questions regarding support for mpich. Of course if somebody from the community wants to pick this up, they are welcome. Pull requests are also welcome if somebody finds a solution for this. Thanks.
