### ISSUE TITLE
Homebrew/science/r installation fails

### ISSUE THREAD

**Issue by scarnecchia** [Homebrew/homebrew-science#5830]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

==> Finishing up
ln -s ../Cellar/r/3.4.0_1/bin/R R
ln -s ../Cellar/r/3.4.0_1/bin/Rscript Rscript
ln -s ../Cellar/r/3.4.0_1/include/R.h R.h
ln -s ../Cellar/r/3.4.0_1/include/R_ext R_ext
ln -s ../Cellar/r/3.4.0_1/include/Rconfig.h Rconfig.h
ln -s ../Cellar/r/3.4.0_1/include/Rdefines.h Rdefines.h
ln -s ../Cellar/r/3.4.0_1/include/Rembedded.h Rembedded.h
ln -s ../Cellar/r/3.4.0_1/include/Rinterface.h Rinterface.h
ln -s ../Cellar/r/3.4.0_1/include/Rinternals.h Rinternals.h
ln -s ../Cellar/r/3.4.0_1/include/Rmath.h Rmath.h
ln -s ../Cellar/r/3.4.0_1/include/Rversion.h Rversion.h
ln -s ../Cellar/r/3.4.0_1/include/S.h S.h
ln -s ../../../Cellar/r/3.4.0_1/share/man/man1/R.1 R.1
ln -s ../../../Cellar/r/3.4.0_1/share/man/man1/Rscript.1 Rscript.1
ln -s ../Cellar/r/3.4.0_1/lib/libR.dylib libR.dylib
ln -s ../Cellar/r/3.4.0_1/lib/libRmath.dylib libRmath.dylib
ln -s ../../Cellar/r/3.4.0_1/lib/pkgconfig/libR.pc libR.pc
ln -s ../Cellar/r/3.4.0_1/Frameworks/R.framework R.framework
Error: 11:6: unexpected symbol
11: help options
          ^
Execution halted
Error: 11:6: unexpected symbol
11: help options
          ^
Execution halted

#### Brief summary of issue: R installation fails at symlinking step. R itself will load, but attempts to run R CMD or install.packages will result in the same error:

"Error: 11:6: unexpected symbol
11: help options
          ^
Execution halted
Error: 11:6: unexpected symbol
11: help options
          ^
Execution halted"

#### Gist with output of `brew doctor`:

:~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

#### Output of `brew config`:

HOMEBREW_VERSION: 1.2.3-9-g3fe32053a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3fe32053a7f0d7f817a90e308ab0c62436a5c208
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6de4acf0d944534405bacd780a795ce91cf717d9
Core tap last commit: 20 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/scarndp/.rbenv/shims/ruby => /Users/scarndp/.rbenv/versions/2.3.1/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
> Gist with output of brew doctor:
> Output of brew config:

Please add this

**Comment by scarnecchia** [comment]
First post updated with requested information.

**Comment by iMichka** [comment]
I am not really sure what you are seeing here. The error is a runtime error from `r`.

Does your `r` installation really looks like this:
> ln -s ../../Cellar/r/3.4.0_1/lib/pkgconfig/libR.pc libR.pc
ln -s ../Cellar/r/3.4.0_1/Frameworks/R.framework R.framework
Error: 11:6: unexpected symbol
11: help options
^
Execution halted

For me it looks like this:
>ln -s ../../Cellar/r/3.4.0_1/lib/pkgconfig/libR.pc libR.pc
ln -s ../Cellar/r/3.4.0_1/Frameworks/R.framework R.framework
==> Caveats
To enable rJava support, run the following command:
  R CMD javareconf JAVA_CPPFLAGS=-I/System/Library/Frameworks/JavaVM.framework/Headers
If you've installed a version of Java other than the default, you might need to instead use:
  R CMD javareconf JAVA_CPPFLAGS="-I/System/Library/Frameworks/JavaVM.framework/Headers -I/Library/Java/JavaVirtualMachines/jdk<version>.jdk/"
(where <version> can be found by running `java -version`, `/usr/libexec/java_home`, or `locate jni.h`), or:
  R CMD javareconf JAVA_CPPFLAGS="-I/System/Library/Frameworks/JavaVM.framework/Headers -I$(/usr/libexec/java_home | grep -o '.*jdk')"
==> Summary
🍺  /usr/local/Cellar/r/3.4.0_1: 2,247 files, 59.3MB, built in 8 minutes 19 seconds

What I am trying to understand is if the exception is being thrown when `r` is built/linked by homebrew, or when you try to run it. If that is the case, what exact script/command are you running to get this error?

**Comment by scarnecchia** [comment]
Yup, it really looks like that. This is happening when i issue the command to brew install R. 

brew install -v homebrew/science/r --with-x11

If it's an error with R, it's bizarre that it would throw at this point.

**Comment by scarnecchia** [comment]
Still no idea why it came up during installation, but the error itself was caused by user error. Deleted an old .Renviron and .Rprofile file and all is right in the world.

**Comment by iMichka** [comment]
Nice you found out what was broken. We often do not touch user configuration files, and if the r migration process had a problem, it explains why it broken during the installation. Glad your problem is now solved.
