### ISSUE TITLE
Revisions for gsl needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#5841]
https://github.com/Homebrew/homebrew-core/pull/14727

- [x] abinit (#5682)
- [x] analysis
- [x] andi
- [x] anvio (#5856)
- [x] apophenia (#5871)
- [x] art
- [x] astrometry-net (#5873)
- [ ] atomic-pseudopotential-engine (#5874)
- [x] bayestraits (#5875)
- [x] clonehd
- [x] dynare (#5876)
- [x] ea-utils (#5877)
- [x] enblend-enfuse (#5870)
- [x] fgsl (#5878)
- [x] fwdpp (#5859)
- [x] getdp (#5879)
- [x] gnuastro (#5880)
- [x] gnudatalanguage (#5872)
- [x] gromacs (#5881)
- [x] hotspot (#5882)
- [x] libbi (#5883)
- [ ] libeemd (#5884)
- [x] libsequence (#5860)
- [ ] lobstr (#5861)
- [x] mash
- [x] mathgl (#5885)
- [ ] methpipe (#5886)
- [ ] moose (#5835)
- [x] nco (#5887)
- [ ] nest (#5888)
- [ ] nip2 (#5889)
- [x] pspp (#5890)
- [ ] quaff (#5863)
- [x] root (#5891)
- [x] root6 (#5892)
- [x] siril (#5869)
- [x] visp (#5893)
- [x] wiggletools
- [x] xmi-msim (#5868)

**Comment by sjackman** [comment]
@tomzgach Could you please increment the `revision` and submit a PR to rebuild the bottle for these formulae?

1. analysis
2. andi
3. anvio
4. art
5. clonehd
6. fwdpp
7. libsequence
8. lobstr
9. mash
10. quaff
11. wiggletools

**Comment by sjackman** [comment]
This list was created from `brew uses gsl` and then grepping those formulae for the comment `# tag "bioinformatics"`. Can you please also check if there's any of the formulae in the long list above that are in ORCA but missing the `# tag "bioinformatics"`? If you find any, also bump the revision for those formulae, and when you do, also add the comment `# tag "bioinformatics"`.
