### ISSUE TITLE
Blast failed to install for funannotate installation

### ISSUE THREAD

**Issue by kramergj** [Homebrew/homebrew-science#5905]
Hi there,
I am trying to install funannotate and am running into an issue getting blast to install.  

When I try....
$ brew install funannotate
==> Installing funannotate from nextgenusfs/tap
==> Installing dependencies for nextgenusfs/tap/funannotate: blast, rmblast, repeatmasker, repeatmodeler, proteinortho
==> Installing nextgenusfs/tap/funannotate dependency: blast
Error: homebrew/science/blast cannot be built with any available compilers.
Install Clang or brew install gcc

When I try to install blast alone...
==> Installing blast from homebrew/science
Error: homebrew/science/blast cannot be built with any available compilers.
Install Clang or brew install gcc

I've tried reinstalling gcc and installing clang, however neither has worked.  I do not seem to be having difficulty installing any other program (other than the ones dependent on blast)

For example, when I try to install gcc...
brew install gcc
Warning: gcc 5.3.0 is already installed

And I tried installing a different version of gcc based on a prior post (https://github.com/Homebrew/legacy-homebrew/issues/32266)
brew install homebrew/versions/gcc48
Warning: Use gcc@4.8 instead of deprecated homebrew/versions/gcc48
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.bz2
Already downloaded: /home/nodwell/.cache/Homebrew/gcc@4.8-4.8.5.tar.bz2
==> ../configure --build=x86_64-apple-darwin4.4.0-79-generic --prefix=/home/nodw
Last 15 lines from /home/nodwell/.cache/Homebrew/Logs/gcc@4.8/01.configure:
--with-system-zlib
--enable-libstdcxx-time=yes
--enable-stage1-checking
--enable-checking=release
--enable-lto
--enable-plugin
--disable-werror
--with-pkgversion=Homebrew GCC 4.8.5
--with-bugurl=https://github.com/Homebrew/homebrew-core/issues
MAKEINFO=missing
--disable-nls
--enable-multilib

checking build system type... Invalid configuration `x86_64-apple-darwin4.4.0-79-generic': machine `x86_64-apple-darwin4.4.0-79' not recognized
configure: error: /bin/bash ../config.sub x86_64-apple-darwin4.4.0-79-generic failed

Any insight will be greatly appreciated

### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by cmdcolin** [comment]
Do you happen to be using a HPC system? I remember having problems similar to this but can't precisely remember how to fix, I think it was just using a different system (logging into a "dev" system) within my HPC

**Comment by kramergj** [comment]
Hi there, thank you for the reply.  Well, I actually was trying to get the install to work on an Ubuntu system.  I still haven't figured out the issue with this, but got the funannotate install to work on a mac and so I suppose I've moved on.

**Comment by tseemann** [comment]
@kramergj do you have the linuxbrew `bin` folder in your PATH first?

**Comment by nextgenusfs** [comment]
I think this maybe same error as here https://github.com/Homebrew/homebrew-science/issues/5195, i.e. blast no longer has `--without-check` option.  I had that option hard coded in the formula if on linux.  So is blast+ now installing correctly on linuxbrew?
