### ISSUE TITLE
Raxml is compiling with incorrect instruction set

### ISSUE THREAD

**Issue by wheelern** [Homebrew/homebrew-science#5920]
My machine can't use AVX instructions, but brew is only compiling raxmlHPC-PTHREADS and raxmlHPC-PTHREADS-AVX (should include SSE3 instructions as well).

    [zamanian@brc6 ~]$ ls /home/linuxbrew/.linuxbrew/Cellar/raxml/8.2.10_1/bin
    raxmlHPC-PTHREADS  raxmlHPC-PTHREADS-AVX

    [zamanian@brc6 data]$ grep avx /proc/cpuinfo
    [zamanian@brc6 data]$

    [zamanian@brc6 data]$ grep sse3 /proc/cpuinfo
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush 
    acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl pni 
    pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm

Not sure what's up or if I'm doing something wrong. Thanks.

**Comment by jonchang** [comment]
Can you please fill out the issue template, including all the brew config and doctor info. Thanks

**Comment by jonchang** [comment]
Hah, actually sse3 instructions are confusingly called pni in `/proc/cpuinfo`. Please file an issue for this over at Linuxbrew. (If you'd like to take a shot at fixing this, the relevant code is in `Library/Homebrew/extend/os/linux/hardware/cpu.rb`)
