### ISSUE TITLE
rJava install fails: ld: library not found for -licuuc, a linker error

### ISSUE THREAD

**Issue by heoa** [Homebrew/homebrew-science#5968]
I have istalled Java with cask

```
brew cask list
java  
```
I want to install rJava on macOS 10.11.6. My current Java version is `Java version: 1.8.0_131`, according to `R CMD javareconf|grep version`. My R is 

```
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin11.4.2 (64-bit)
```

But I get the linker error in R with `install.packages("rJava")`

    ld: library not found for -licuuc
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [libjri.jnilib] Error 1
    make[1]: *** [src/JRI.jar] Error 2
    make: *** [jri] Error 2
    ERROR: compilation failed for package ‘rJava’

I found many years old thread [here](https://github.com/Homebrew/homebrew-science/issues/627) but related to other linker package so irrelevant. 

**How to get the rJava installed? What is causing the linker error licuuc?**

**Comment by jonchang** [comment]
It doesn't seem like you're using the latest version of R. Please `brew upgrade r` and try installing `rJava` again to see if the issue is fixed. If it isn't please file a new issue over at [homebrew/core](https://github.com/Homebrew/homebrew-core/issues) since that's where the R formula lives now.

**Comment by gmhhope** [comment]
Same issue. Could anybody help?
