### ISSUE TITLE
cd-hit 4.6.8 missing from Linuxbrew bintray

### ISSUE THREAD

**Issue by andrewyatz** [Homebrew/homebrew-science#6010]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```
==> Installing homebrew/science/cd-hit
==> Downloading https://linuxbrew.bintray.com/bottles-science/cd-hit-4.6.8.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "cd-hit"
Download failed: https://linuxbrew.bintray.com/bottles-science/cd-hit-4.6.8.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/weizhongli/cdhit/releases/download/V4.6.8/cd-hit-v4.6.8-2017-0621-source.tar.gz
==> make openmp=yes
==> make PREFIX=/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/cd-hit/4.6.8/bin install
�  /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/cd-hit/4.6.8: 41 files, 1017.3KB, built in 6 seconds
```

#### Brief summary of issue:

According to `cd-hit`'s history LinuxbewTestBot created a cask version of 4.6.8 and wrote a sha256 sum as seen in commit 842bf7f87575f5e979faa57fe3615a6354d9afdd. However when installing cd-hit this version is missing from https://linuxbrew.bintray.com/bottles-science/ (versions 4.6.4 and 4.6.6 are present at the time of writing).

#### The complete command that you issued:

```
brew install homebrew/science/cd-hit
```

**Comment by ilovezfs** [comment]
should be fixed now
