### ISSUE TITLE
octave: mkoctfile references old suite-sparse library

### ISSUE THREAD

**Issue by houtanb** [Homebrew/homebrew-science#6015]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
The Octave mkoctfile refernces old suite-sparse version
```
dyld: Library not loaded: /usr/local/opt/suite-sparse/lib/libsuitesparseconfig.4.5.4.dylib
  Referenced from: /usr/local/opt/octave/bin/mkoctfile
  Reason: image not found
```
```
• brew info suite-sparse
suite-sparse: stable 4.5.5 (bottled)
```

#### The complete command that you issued:
```
• /usr/local/Cellar/octave/4.2.1_3/bin/mkoctfile
dyld: Library not loaded: /usr/local/opt/suite-sparse/lib/libsuitesparseconfig.4.5.4.dylib
  Referenced from: /usr/local/Cellar/octave/4.2.1_3/bin/mkoctfile
  Reason: image not found
Abort trap: 6
```

#### Gist with output of `brew doctor`:
https://gist.github.com/houtanb/8caeaaab2ed89d336e6671729b2e7a5d

#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.2.5-14-g88b762f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88b762f78447842a6187e0fda49c9493f029cbef
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ffa5a7ff463451d77837a69c978da319c8a81766
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by jonchang** [comment]
`brew reinstall octave` should fix this. If you're still having problems please file an issue in [homebrew/core](https://github.com/Homebrew/homebrew-core/issues) since that's where the `octave` formula lives now.

**Comment by houtanb** [comment]
@jonchang thanks, that did it, though I had to recompile octave locally. I posted the issue because I thought you could simply update the bottles...

**Comment by ilovezfs** [comment]
I think what happened here is that the octave formula was a revision 3 in science, and then reset to revision 0 when it was imported into core. Bumping the revision from 0 to 4 should get everyone correctly transitioned.
