### ISSUE TITLE
igraph: Depends on openblas libxml2 for Linux

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-science#6025]
```
==> brew linkage --test igraph
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libgcc_s.so.1
  /lib/x86_64-linux-gnu/libm.so.6
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  /usr/lib/x86_64-linux-gnu/libxml2.so.2
Missing libraries:
  libblas.so.3
  liblapack.so.3
Unwanted system libraries:
  libxml2.so.2
==> FAILED
```
https://travis-ci.org/Linuxbrew/homebrew-core/builds/259027827#L1373-L1377

**Comment by sjackman** [comment]
@tmozgach Can you confirm that you see this error with `brew linkage igraph`?
If so, could you please submit a PR to add the dependencies `openblas` and `libxml2` `unless OS.mac?`
Thanks!

**Comment by tmozgach** [comment]
@sjackman Fixed: https://github.com/Homebrew/homebrew-science/pull/6038

**Comment by iMichka** [comment]
PR merged, closing here.

**Comment by sjackman** [comment]
Thanks, Tanya and Michka!
