### ISSUE TITLE
Formula with deprecated fails_with :llvm

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-science#6029]
- [x] maq (#6039)
- [x] megahit (#6045)
- [ ] mira (see #5522)
- [x] mrbayes
- [x] phlawd (https://github.com/Homebrew/homebrew-science/pull/6048)
- [x] ray
- [x] shrimp

The `fails_with :llvm` lines need to be removed and these formulae need to be cleaned up.

**Comment by iMichka** [comment]
#6030 removed what needed to be removed. I will go through the list and rebuild/audit everything to see what is going on with these formulae.

**Comment by harper357** [comment]
I am also getting this error with BLAST.

**Comment by iMichka** [comment]
Did you try to re-run `brew update` ? Please open a new issue and fill out the issue template so we can try to help you. Thanks.

**Comment by harper357** [comment]
My mistake, i guess i wasn't on right branch for this tap.

**Comment by iMichka** [comment]
`megahit` was updated 6 days ago and did build (#6045). One less to check. `maq` is fixed too and has been merged.

**Comment by iMichka** [comment]
For `mira`, this PR may be picked up: #5522

**Comment by iMichka** [comment]
`mrbayes` was fine; it had just:
```
fails_with :llvm do
build 2336
http://sourceforge.net/tracker/index.php?func=detail&aid=3426528&group_id=129302&atid=714418
```

These were some compilation problems from 2011. Since then, new versions have been published. So nothing to do for that formula.

**Comment by iMichka** [comment]
`ray` is also fine, it was also disabled for `build 2336`, which is super old. Bottles have been built lately so this is ok.

**Comment by iMichka** [comment]
`shrimp` is fine, as it uses openmp, it will use gcc 7, and that compiled fine on my mac. It may be a problem if openmp support is built with llvm one day, but we will have to look at it then.

**Comment by iMichka** [comment]
We have a PR open for `mira`, not sure when we will have a look at it. Closing here, all done.
