### ISSUE TITLE
pillow: Missing Linux bottle (4.2.1)

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-science#6080]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

`pillow` has a Linux bottle tag, and while version 4.2.1 exists on Bintray, apparently the bottle was not published.

**Comment by jonchang** [comment]
```
 $ brew fetch pillow
==> Fetching pillow from homebrew/science
==> Downloading https://linuxbrew.bintray.com/bottles-science/pillow-4.2.1.x86_6
######################################################################## 100.0%
Downloaded to: /home/jonchang/.cache/Homebrew/pillow-4.2.1.x86_64_linux.bottle.tar.gz
SHA256: fe85c015285f5b0e61bccf7d3a5ff71bf7896c1d3a433c8645f59d517d5f157c
```
