### ISSUE TITLE
armadillo 7.960.0 build failure (openblaso not found)

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#6081]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

`/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lopenblaso`

#### The complete command that you issued:

brew upgrade armadillo`

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/anonymous/d309708179ef3536671892140dc3cbb3

**Comment by iMichka** [comment]
@tseemann armadillo was migrated to core. Could you update and try again? Please open the issue here if it still does not work for you: https://github.com/Linuxbrew/homebrew-core

Thanks

**Comment by tseemann** [comment]
@iMichka it installs fine now, thanks!
