### ISSUE TITLE
root6 python linking is broken

### ISSUE THREAD

**Issue by kratsg** [Homebrew/homebrew-science#6108]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- ~[ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~

#### Brief summary of issue:

ROOT6 formula is not linking to python correctly.

```
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

#### The complete command that you issued:

`python -c "import ROOT"`

#### Gist with output of `brew doctor`:

`Your system is ready to brew`

#### Link output by `brew gist-logs <formula>`:

Not a build error.

#### Output of `brew config`:

https://gist.github.com/anonymous/a682a93d346cbb089b37025aeb190fd5

**Comment by iMichka** [comment]
root and root6 have been migrated to homebrew core (https://github.com/Homebrew/homebrew-core). Please update and test again with the current version; and report any issue there. Thanks.
