### ISSUE TITLE
Problem in Installation of DiscovarDenovo

### ISSUE THREAD

**Issue by beherasan** [Homebrew/homebrew-science#6147]
### Indicate troubleshooting steps taken

Here I am showing the error occur while installing Discovardenovo in my Fedora 23 OS.  I am also reporting the output of 'brew doctor' and 'brew config' command. 
**$ brew install homebrew/science/dicovardenovo**
....
....
==> make install
Last 15 lines from /home/santosh/.cache/Homebrew/Logs/discovardenovo/02.make:
libDiscovarDeNovo.a(GapToyCore.o): In function `GapToyCore(int, char**)':
/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src/paths/long/large/GapToyCore.cc:625: undefined reference to `digraphE<BaseVec>::O(int) const'
libDiscovarDeNovo.a(FinalFiles.o): In function `FinalFiles(HyperBasevector const&, vec<int, std::allocator<int> > const&, MasterVec<ReadPath> const&, vec<FeudalString<char, std::char_traits<char> >, std::allocator<FeudalString<char, std::char_traits<char> > > > const&, vec<long, std::allocator<long> > const&, FeudalString<char, std::char_traits<char> > const&, FeudalString<char, std::char_traits<char> > const&, int, int, unsigned char, FeudalString<char, std::char_traits<char> > const&, unsigned char const&, FeudalString<char, std::char_traits<char> > const&, std::map<FeudalString<char, std::char_traits<char> >, GapToyResults, std::less<FeudalString<char, std::char_traits<char> > >, std::allocator<std::pair<FeudalString<char, std::char_traits<char> > const, GapToyResults> > >&, FeudalString<char, std::char_traits<char> > const&, FeudalString<char, std::char_traits<char> > const&, vec<int, std::allocator<int> > const&, MasterVec<BaseVec> const&, unsigned char)':
/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src/paths/long/large/FinalFiles.cc:249: undefined reference to `digraphE<BaseVec>::O(int) const'
libDiscovarDeNovo.a(Improve60.o): In function `Improve60(HyperBasevector&, vec<int, std::allocator<int> >&, MasterVec<ReadPath>&, MasterVec<BaseVec> const&, MasterVec<PQVecA<MempoolAllocator<unsigned char> > > const&, unsigned char) [clone ._omp_fn.0]':
/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src/paths/long/large/Improve60.cc:92: undefined reference to `digraphE<BaseVec>::O(int) const'
/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src/paths/long/large/Improve60.cc:94: undefined reference to `digraphE<BaseVec>::O(int) const'
/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src/paths/long/large/Improve60.cc:68: undefined reference to `digraphE<BaseVec>::O(int) const'
libDiscovarDeNovo.a(Improve60.o):/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src/paths/long/large/Improve60.cc:68: more undefined references to `digraphE<BaseVec>::O(int) const' follow
collect2: error: ld returned 1 exit status
Makefile:871: recipe for target 'DiscovarDeNovo' failed
make[1]: *** [DiscovarDeNovo] Error 1
make[1]: Leaving directory '/tmp/discovardenovo-20170812-14067-17vlki8/discovardenovo-52488/src'
Makefile:288: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
These open issues may also help:
discovardenovo: /usr/bin/g++-4.8: No such file or directory on Ubuntu 16.04 https://github.com/Homebrew/homebrew-science/issues/4335

**$brew config**
HOMEBREW_VERSION: 1.2.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 20bcce2c176469cec271b46d523eef1510217436
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 56b2a8ff5fbad8bf2004d4194b76f03b75fe5210
Core tap last commit: 41 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit 0x64e
Homebrew Ruby: 2.4.1 => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.1_1/bin/ruby
Clang: N/A
Git: 2.5.5 => /bin/git
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.0/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.13_1/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.1_1/bin/ruby
Java: openjdk version "1.8.0_111"
Kernel: Linux 4.8.13-100.fc23.x86_64 x86_64 GNU/Linux
OS: Fedora release 23 (Twenty Three)
Host glibc: 2.22
/usr/bin/gcc: 5.3.1
glibc: N/A
gcc: 5.3.0
xorg: N/A
**$brew doctor**
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
/bin/freetype-config
/bin/brltty-config
/bin/pkg-config
/bin/icu-config
/bin/pcre-config
/bin/libpng-config
/bin/x86_64-redhat-linux-gnu-pkg-config
/bin/kde4-config
/bin/libpng16-config
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
Unexpected header files:
/usr/local/include/google/sparsehash/hashtable-common.h
/usr/local/include/google/sparsehash/libc_allocator_with_realloc.h
/usr/local/include/google/sparsehash/densehashtable.h
/usr/local/include/google/sparsehash/sparsehashtable.h
/usr/local/include/google/template_util.h
/usr/local/include/google/type_traits.h
/usr/local/include/sparsehash/internal/hashtable-common.h
/usr/local/include/sparsehash/internal/libc_allocator_with_realloc.h
/usr/local/include/sparsehash/internal/densehashtable.h
/usr/local/include/sparsehash/internal/sparsehashtable.h
/usr/local/include/sparsehash/internal/sparseconfig.h
/usr/local/include/sparsehash/template_util.h
/usr/local/include/sparsehash/type_traits.h
Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
Unexpected .pc files:
/usr/local/lib/pkgconfig/libsparsehash.pc
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /home/linuxbrew/.linuxbrew/sbin.
Consider setting the PATH for example like so
echo 'export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> ~/.bash_profile
Warning: Broken symlinks were found. Remove them with `brew prune`:
/home/linuxbrew/.linuxbrew/bin/g++-4.4
/home/linuxbrew/.linuxbrew/bin/gcc-4.4

please suggest me to solve the error, 

Thanks,
Santosh
- [Yes ] Ran `brew update` and retried your prior step?
- [ yes] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Please report `brew gist-logs discovardenovo`
