### ISSUE TITLE
brew install openbr requires opencv 2.4.5

### ISSUE THREAD

**Issue by bzarzuela** [Homebrew/homebrew-science#6185]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

CMake Error at CMakeLists.txt:88 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "2.4.5".

  The following configuration files were considered but not accepted:

    /usr/local/share/OpenCV/OpenCVConfig.cmake, version: 3.3.0
    /usr/local/opt/opencv/share/OpenCV/OpenCVConfig.cmake, version: 3.3.0

#### Brief summary of issue:

OpenCV was upgraded to version 3 but I can't find a way to force it to use opencv@2

#### The complete command that you issued:

brew install openbr

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/anonymous/e57ebd87f4dc1c63825772bc155e8aa3

**Comment by ilovezfs** [comment]
Thanks for reporting this. It will be resolved by https://github.com/Homebrew/homebrew-science/issues/6186.

**Comment by jonchang** [comment]
Fixed by https://github.com/Homebrew/homebrew-science/pull/6195
