### ISSUE TITLE
Formulae need to use opencv@2 not opencv

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#6186]
- [x] butterflow (#6193)
- [x] cvblob (#6194)
- [x] insighttoolkit (#6187)
- [x] openalpr (+ check if the jpeg dependency makes sense) (#6197)
- [x] openbr (#6195)
- [x] openimageio (#6196) actually https://github.com/Homebrew/homebrew-science/pull/6230
- [x] shogun (#5684)
- [x] siril (#6188)
- [x] visp (#6198)

CC @iMichka @jonchang @sjackman

**Comment by iMichka** [comment]
All done!
