### ISSUE TITLE
Revisions for boost 1.65.0 needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#6192]
## With linkage

- [x] alpscore https://github.com/Homebrew/homebrew-science/pull/6223
- [x] augustus
- [x] bless
- [x] ckon https://github.com/Homebrew/homebrew-science/pull/6224
- [x] cufflinks https://github.com/Homebrew/homebrew-science/pull/6204
- [ ] dealii
- [x] delly
- [ ] dssp https://github.com/Homebrew/homebrew-science/pull/6225
- [x] express
- [x] field3d https://github.com/Homebrew/homebrew-science/pull/6226
- [ ] graph-tool https://github.com/Homebrew/homebrew-science/pull/6228
- [x] lightstringgraph https://github.com/Homebrew/homebrew-science/pull/6227
- [ ] mlpack https://github.com/Homebrew/homebrew-science/pull/5660 ?
- [x] mothur
- [ ] nixio https://github.com/Homebrew/homebrew-science/pull/6232
- [ ] ome-common https://github.com/Homebrew/homebrew-science/pull/6258
- [ ] ome-files https://github.com/Homebrew/homebrew-science/pull/6254
- [ ] ome-xml https://github.com/Homebrew/homebrew-science/pull/6255
- [x] openimageio https://github.com/Homebrew/homebrew-science/pull/6230
- [ ] pulseview https://github.com/Homebrew/homebrew-science/pull/3827 ?
- [ ] pykep https://github.com/Homebrew/homebrew-science/pull/6256
- [ ] quaff
- [ ] rapsearch2 https://github.com/Homebrew/homebrew-science/pull/6201
- [ ] scram
- [x] shark https://github.com/Homebrew/homebrew-science/pull/6262
- [x] statismo ~https://github.com/Homebrew/homebrew-science/pull/5916~ https://github.com/Homebrew/homebrew-science/pull/6273
- [x] tophat

## Without linkage

- [ ] analysis
- [ ] bali-phy
- [ ] blaze-lib
- [x] boost-compute https://github.com/Homebrew/homebrew-science/pull/6239
- [ ] cmdstan
- [x] dgtal https://github.com/Homebrew/homebrew-science/pull/6260
- [ ] enblend-enfuse
- [ ] fwdpp
- [ ] kat
- [ ] libbi
- [ ] libsequence
- [ ] lobstr https://github.com/Homebrew/homebrew-science/pull/5861
- [ ] madlib
- [ ] mtl
- [ ] nxtrim
- [ ] paraview
- [ ] rstudio-server
- [ ] sailfish
- [ ] salmon
- [ ] trilinos
- [ ] vislcg3

## Didn't install (no bottles)

- [ ] amos
- [ ] galsim
- [ ] joinx
- [ ] meraculous
- [ ] mira
- [ ] quake

CC @iMichka @jonchang @sjackman

**Comment by sjackman** [comment]
29 of 54 currently have a Linux bottle.
```
alpscore	delly		libbi		nxtrim		sailfish
amos		dgtal		libsequence	ome-common	salmon
analysis	enblend-enfuse	lobstr		ome-files	shark
augustus	express		madlib		ome-xml		statismo
bless		fwdpp		mlpack		pykep		tophat
cufflinks	kat		nixio		rapsearch2
```

**Comment by iMichka** [comment]
We should start with these as soon as the boost linux bottle has been pushed.

**Comment by sjackman** [comment]
These were the only formula that gave a `brew linkage failure` on Linuxbrew.
```
alpscore
augustus
bless
ome-common
ome-files
ome-xml
rapsearch2
shark
```
It's possible that the others only use the `boost` header files, and don't need their bottles rebuilt.
In that case, the boost dependency should be `:build`, like for example `abyss`.

**Comment by sjackman** [comment]
The `boost` 1.65.0 bottle is merged for Linuxbrew.

**Comment by sjackman** [comment]
The first example I found…
```
==> brew linkage --test analysis
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
No broken dylib links
No unwanted system libraries
```
`analysis` has no run-time dependency on `boost`, so its bottle does not need to be rebuilt, and it should be
```
depends_on "boost" => :build
```

**Comment by sjackman** [comment]
The first example I found…
```
==> brew linkage --test analysis
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
No broken dylib links
No unwanted system libraries
```
`analysis` has no run-time dependency on `boost`, so its bottle does not need to be rebuilt, and it should be
```
depends_on "boost" => :build
```

**Comment by ilovezfs** [comment]
Any of the ones with macOS bottles should be rebuilt if they're linked to Boost since they won't actually generate linkage errors given that the boost libraries are unversioned on macOS.

**Comment by sjackman** [comment]
Unless they only use the `boost` headers and don't link against the `boost` libraries at all, like for example `analysis`.

**Comment by ilovezfs** [comment]
hence

>if they're linked

**Comment by sjackman** [comment]
Are you able to identify which of the 54 above have no linkage to `boost`?

**Comment by ilovezfs** [comment]
alpscore
augustus
bless
ckon
cufflinks
dealii
delly
dssp
express
field3d
graph-tool
lightstringgraph
mlpack
mothur
nixio
ome-common
ome-files
ome-xml
openimageio
pulseview
pykep
quaff
rapsearch2
scram
shark
statismo
tophat

**Comment by ilovezfs** [comment]
Those are those ones _with_ linkage.

**Comment by ilovezfs** [comment]
The ones without:

analysis
bali-phy
blaze-lib
boost-compute
cmdstan
dgtal
enblend-enfuse
fwdpp
kat
libbi
libsequence
lobstr
madlib
mtl
nxtrim
paraview
rstudio-server
sailfish
salmon
trilinos
vislcg3

**Comment by ilovezfs** [comment]
And the ones that wouldn't install:

amos
galsim
joinx
meraculous
mira
quake

**Comment by sjackman** [comment]
Awesome. Thanks!

**Comment by sjackman** [comment]
Should we create a `boost@1.64` formula for the above six formulae?

**Comment by ilovezfs** [comment]
No, those didn't install because they don't have bottles.

**Comment by ilovezfs** [comment]
`galsim` is linked to `libboost_python.dylib` once it's installed. So it should be revision bumped even if it has no bottle. It could have a bottle if the resources were vendored instead of
```
  depends_on "astropy" => :python
  depends_on "numpy" => :python
  depends_on "nose" => :python if build.with? "test"
```

**Comment by tmozgach** [comment]
I will bump revision for the following:
```
augustus
bless
cufflinks
delly
express
mothur
rapsearch2
tophat
```

**Comment by jonchang** [comment]
I've split the original list into the with/without linkage that @ilovezfs so kindly hunted down. I will start opening pull requests for the remainder with linkage.

**Comment by iMichka** [comment]
Superseded by #6296
