### ISSUE TITLE
Problem Executing LAMMPS after Homebrew Install

### ISSUE THREAD

**Issue by bcornick** [Homebrew/homebrew-science#6200]
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Brief summary of issue:

After installing the latest version of Homebrew and then using it to install LAMMPS, I could not get the executable to run. When I run `brew test lamps -v` output looks normal and it works, but when I try to run my own `lammps < file.in` I receive the following error message:

`"PMIx has detected a temporary directory name that results
in a path that is too long for the Unix domain socket:

    Temp dir: /var/folders/3m/0584lgjs6w5314972vhpbzdh0000gn/T/openmpi-sessions-501@Bretts-MacBook-Pro_0/48380

Try setting your TMPDIR environmental variable to point to
something shorter in length

It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)"`

Being a student that is relatively new to this and not so familiar with MPI, I have no idea how to solve this issue. Thanks.

**Comment by iMichka** [comment]
We had really similar problems reported before. I do not remember what was the exact solution, but here is some stuff to read: #5269, #5155
You can also look at the different closed issues for lammps, I may have missed one or two.
Hope that helps.

**Comment by iMichka** [comment]
Closing, as I think this is a user configuration problem. Feel free to comment on the issue though, but not sure we can help you here. Thanks.
