### ISSUE TITLE
System  will not update to  jpeg 9 

### ISSUE THREAD

**Issue by jimramberg** [Homebrew/homebrew-science#6212]
This is what I tried:

Jims-MBP:~ ramberg$ brew info jpeg
jpeg: stable 8d (bottled)
Image manipulation library
http://www.ijg.org
/usr/local/Cellar/jpeg/8d (20 files, 1.6MB) *
  Built from source on 2016-02-15 at 09:04:26 with: --universal
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jpeg.rb

Jims-MBP:~ ramberg$ brew update
Already up-to-date.

Jims-MBP:~ ramberg$ brew upgrade
Updating Homebrew...

Jims-MBP:~ ramberg$ brew upgrade jpeg
Updating Homebrew...
Error: jpeg 8d already installed
Jims-MBP:~ ramberg$ 

thanks for any and all help

**Comment by tseemann** [comment]
I just tried the same thing and it worked on my macOS.  I am on Sierra.
Can you report `brew config` and `brew doctor` ?

**Comment by jimramberg** [comment]
Jims-MBP:~ ramberg$ brew config
HOMEBREW_VERSION: 1.3.1-97-g6d393de
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6d393decfe8099cb049c0ee62c6dc5877e54c0d7
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d1f9504afa90fdd39a14c87b8648aa27b84ab66
Core tap last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_144, 1.7.0_60, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.112 => /opt/X11

=======================================================Jims-MBP:~ ramberg$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gegl
  scrollkeeper

**Comment by tseemann** [comment]
Here's mine for comparison:
```
HOMEBREW_VERSION: 1.3.1-97-g6d393de
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6d393decfe8099cb049c0ee62c6dc5877e54c0d7
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e23b9669f6cd34c3559a692c0e5e108b68807013
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_31, 1.7.0_25
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.9 => /opt/X11
```

Ma

**Comment by iMichka** [comment]
```
/usr/local/Cellar/jpeg/8d (20 files, 1.6MB) *
Built from source on 2016-02-15 at 09:04:26 with: --universal
```

I think that prevents the upgrade, but not sure.
Anyway, try:

`brew uninstall jpeg && brew install jpeg"

**Comment by iMichka** [comment]
BTW I think universal is deprecated, we do not support that option anymore.

**Comment by ilovezfs** [comment]
>I think that prevents the upgrade, but not sure.

Nope.
```
iMac-TMP:homebrew-core joe$ brew outdated
jpeg (8d) < 9b
iMac-TMP:homebrew-core joe$ cat /usr/local/Cellar/jpeg/8d/INSTALL_RECEIPT.json 
{"homebrew_version":"1.3.1-97-g6d393de","used_options":["--universal"],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1503740392,"source_modified_time":1326618372,"HEAD":"6d393decfe8099cb049c0ee62c6dc5877e54c0d7","stdlib":null,"compiler":"clang","aliases":["libjpeg","libjpg"],"runtime_dependencies":[],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"8d","devel":null,"head":null,"version_scheme":0}}}iMac-TMP:homebrew-core joe$ brew upgrade
==> Upgrading 1 outdated package, with result:
jpeg 9b
==> Upgrading jpeg 
==> Downloading https://homebrew.bintray.com/bottles/jpeg-9b.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/jpeg-9b.el_capitan.bottle.tar.gz
==> Pouring jpeg-9b.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/jpeg/9b: 20 files, 725.2KB
iMac-TMP:homebrew-core joe$
```

**Comment by ilovezfs** [comment]
```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6d1f9504afa90fdd39a14c87b8648aa27b84ab66
Core tap last commit: 4 months ago
```
@jimramberg you're probably not on master.

```
cd $(brew --repo homebrew/core)
git status
```

**Comment by jimramberg** [comment]
That was it guys: I was not on master.
Thanks for the help. Much appreciated
