### ISSUE TITLE
rmblast make[1]: *** [install-toolkit] Error 1 on RHEL 7.3

### ISSUE THREAD

**Issue by ponomarevsy** [Homebrew/homebrew-science#6235]
Hello! I am using RHEL 7.3 and the latest release of RMBlast, ncbi-blast-2.6.0+-src.tar.gz, with patch isb-2.6.0+-changes-vers2.patch.gz as described here:

http://www.repeatmasker.org/RMBlast.html and I am getting the following error when running "make install":

make[1]: *** [install-toolkit] Error 1

How can this be fixed? Thank you! More error-related information comes here:

» make install
if test -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/gbench; then
make install-gbench;
else
make install-toolkit;
fi
make[1]: Entering directory /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++' /bin/rm -rf /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ /bin/install -c -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/bin /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ /bin/install -c /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/bin/* /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/bin /bin/install -c -m 644 /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/. /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib if test -d /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi; then \ cp -pPR /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/lib/ncbi /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib/; \ fi rm -f /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib/lib*-static.a cd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/lib && \ for x in .a; do \ /bin/ln -s "$x" "/bin/basename "$x" .a-static.a"; \ done cd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/include && find * -name CVS -prune -o -print |\ cpio -pd /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ 51193 blocks /bin/install -c -m 644 /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/ /nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/build/include/ncbi-tools++ /bin/install: omitting directory ‘/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++/ReleaseMT/inc/common’
make[1]: *** [install-toolkit]
Error 1 make[1]: Leaving directory/nethome/appbuild/eb_files/rmblast/ncbi-blast-2.6.0+-src/c++'
make: *** [install] Error 2

**Comment by jonchang** [comment]
Hi @ponomarevsy, thanks for your report. Could you please file a new issue and fill out the [issue template](https://github.com/Homebrew/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md)? We especially need to know the exact Homebrew command you are running when getting this error as it currently doesn't seem like an issue with Homebrew.

**Comment by iMichka** [comment]
I think he is trying to build ncbi-blast-2.6.0 with the patch provided by upstream. Not sure we want to support that kind of setup. It seems to be an "official" release though.

**Comment by ponomarevsy** [comment]
I am not using Homebrew on Mac, I am using RHEL 7.3. Any help/reference to a solution would be greatly appreciated. Thanks.

**Comment by iMichka** [comment]
I opened a pull request #6257 to update blast with that patch. We can continue the discussion there.

Just to make things clear:
- You did not fill out the issue template, and the bug description here is quite weak
- I would have preferred a real new release from upstream, something like blast 2.6.1, instead of putting a patch on the website ... but so be it.

**Comment by iMichka** [comment]
I have no time at all to work on this. Upstream need to release a proper version or you can submit a pull request yourself with the patch.
