### ISSUE TITLE
Mumps with mpich

### ISSUE THREAD

**Issue by PierreMarchand20** [Homebrew/homebrew-science#6318]
I tried to install mumps with mpich but I got the following message:

==> Installing mumps from homebrew/science
==> Installing dependencies for homebrew/science/mumps: open-mpi
==> Installing homebrew/science/mumps dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.
  mpich: because both install mpi__ compiler wrappers

Please `brew unlink mpich` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

It supposed to work according to #771. Am I missing something ? I tried `brew install mpich` and `brew install -s mpich` and both gave me the same message.

**Comment by dpo** [comment]
Both `scalapack` and `parmetis` build against MPICH but for some reason, `mumps` doesn't want to. I'll look into it.

**Comment by PierreMarchand20** [comment]
Actually, scalapack  builds against MPICH if you build from source: 'brew install -s scalapack' otherwise I had the same kind of problem.

**Comment by dpo** [comment]
Yes, it's necessary to build from source if you change any default, including the default variant of MPI to build against. So you'll have to remove all formulae that were built against `open-mpi`, remove `open-mpi`, install `mpich` and build `scalapack` and `parmetis` from source.

**Comment by dpo** [comment]
@ilovezfs I can `brew install -s mumps` and build against `mpich` if I change
```ruby
depends_on :mpi => [:cc, :cxx, :f90, :recommended] 
```
to
```ruby
depends_on :mpi => [:cc, :cxx, :f90]
```
Any idea why `:recommended` would want to force `open-mpi` and refuse to recognize `mpich`?

**Comment by dpo** [comment]
Sorry, nevermind. The issues appears to be elsewhere.

**Comment by dpo** [comment]
@PierreMarchand20 Please see a solution here: https://github.com/Homebrew/brew/issues/3159

**Comment by PierreMarchand20** [comment]
Thank you, it seems to work. I guess you are discussing it in Homebrew/brew#3159  but it would be nice to have a cleaner way to do so, or at least a warning. But again, thank you 👍
