### ISSUE TITLE
Cannot install bedtools v2.26.0 on macOS 10.12.6

### ISSUE THREAD

**Issue by jhawkey** [Homebrew/homebrew-science#6334]
I'm having some issues attempting to install bedtools on my Mac. I've run brew update twice, and  resolved all warnings from brew doctor, which now returns `Your system is ready to brew.`

Here is the build error:
```jane@Serenity ~ $ brew install bedtools
==> Installing bedtools from homebrew/science
==> Downloading https://github.com/arq5x/bedtools2/archive/v2.26.0.tar.gz
Already downloaded: /Users/jane/Library/Caches/Homebrew/bedtools-2.26.0.tar.gz
==> make
Last 15 lines from /Users/jane/Library/Logs/Homebrew/bedtools/01.make:
                           ~~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [../../../../obj//StrandQueue.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  * compiling ContextSpacing.cpp
  * compiling ContextMerge.cpp
  * compiling ContextJaccard.cpp
  * compiling ContextClosest.cpp
  * compiling ContextSubtract.cpp
  * compiling ContextCoverage.cpp
  * compiling ContextComplement.cpp
  * compiling ContextGroupBy.cpp
make[1]: *** [Records] Error 2
make: *** [src/utils/FileRecordTools] Error 2
```

I also tried installing by downloading bedtools from the website and running make, but I believe I am getting similar issues:
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [../../../../obj//StrandQueue.o] Error 1
make[1]: *** [Records] Error 2
make: *** [src/utils/FileRecordTools] Error 2
```

[Here is a link to the gist-logs output](https://gist.github.com/jhawkey/81033a69242e634aa6baeb382161b2e9).

Thanks,
Jane

**Comment by Hydrochaeris** [comment]
I am also struggling with the exactly the same errors. I tried with different versions of the program and installed Xcode and whatnot to no avail. If anyone would know of a possible solution I would also greatly appreciate it.

**Comment by gaotc200** [comment]
I also have exactly the same problem.

**Comment by iMichka** [comment]
> I also tried installing by downloading bedtools from the website and running make, but I believe I am getting similar issues:

Then you should probably report the error upstream, to the `bedtools` developers. They may be able to help you.

**Comment by jonchang** [comment]
I encountered this problem while migrating bedtools to homebrew/core. I'm preparing a patch now that will fix this issue.

**Comment by benoitballester** [comment]
Exact same issue here - So what was the fix in the end ?

**Comment by hejing3283** [comment]
I am having the same problem.

**Comment by gaotc200** [comment]
@benoitballester @hejing3283 see my reference in arq5x/bedtools2 above and jonchang's fix

**Comment by ilovezfs** [comment]
`bedtools` is now available in homebrew/core
