### ISSUE TITLE
scotch build error on macOS 10.13

### ISSUE THREAD

**Issue by jtceleron** [Homebrew/homebrew-science#6386]
### Indicate troubleshooting steps taken

- [ Y ] Ran `brew update` and retried your prior step?
- [ Y ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ Y ] Checked that a similar issue hasn't already been filed?
 #4382 . But that one was on macOS 10.12.
- [ N ] Looked up the software bug tracker if reporting a build error?
- [ Tried ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

==> make scotch VERBOSE=ON CCS=clang CCP=/usr/local/bin/mpicc CCD=/usr/local/bin
Last 15 lines from /Users/yiyangzhang/Library/Logs/Homebrew/scotch/01.make:
clang -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ  -c wgraph_part_ml.c -o wgraph_part_ml.o
clang -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ  -c wgraph_part_rb.c -o wgraph_part_rb.o
clang -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ  -c wgraph_part_st.c -o wgraph_part_st.o
clang -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ  -c wgraph_part_zr.c -o wgraph_part_zr.o
clang -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ  -c wgraph_store.c -o wgraph_store.o
libtool -lm -lz -lpthread -lbz2 -dynamic -install_name /usr/local/Cellar/scotch/6.0.4_4/lib/libscotch.dylib -undefined dynamic_lookup -o libscotch.dylib arch.o arch_build.o arch_cmplt.o arch_cmpltw.o arch_deco.o arch_dist.o arch_hcub.o arch_mesh.o arch_tleaf.o arch_torus.o arch_vcmplt.o arch_vhcub.o bgraph.o bgraph_bipart_bd.o bgraph_bipart_df.o bgraph_bipart_ex.o bgraph_bipart_fm.o bgraph_bipart_gg.o bgraph_bipart_gp.o bgraph_bipart_ml.o bgraph_bipart_st.o bgraph_bipart_zr.o bgraph_check.o bgraph_store.o common.o common_file.o common_file_compress.o common_file_uncompress.o common_integer.o common_memory.o common_string.o common_stub.o common_thread.o fibo.o gain.o geom.o graph.o graph_base.o graph_band.o graph_check.o graph_coarsen.o graph_induce.o graph_io.o graph_io_chac.o graph_io_habo.o graph_io_mmkt.o graph_io_scot.o graph_list.o graph_match.o hall_order_hd.o hall_order_hf.o hall_order_hx.o hgraph.o hgraph_check.o hgraph_induce.o hgraph_order_bl.o hgraph_order_cp.o hgraph_order_gp.o hgraph_order_hd.o hgraph_order_hf.o hgraph_order_hx.o hgraph_order_kp.o hgraph_order_nd.o hgraph_order_si.o hgraph_order_st.o hmesh.o hmesh_check.o hmesh_hgraph.o hmesh_induce.o hmesh_mesh.o hmesh_order_bl.o hmesh_order_cp.o hmesh_order_gr.o hmesh_order_gp.o hmesh_order_hd.o hmesh_order_hf.o hmesh_order_hx.o hmesh_order_nd.o hmesh_order_si.o hmesh_order_st.o kgraph.o kgraph_band.o kgraph_check.o kgraph_map_bd.o kgraph_map_cp.o kgraph_map_df.o kgraph_map_ex.o kgraph_map_fm.o kgraph_map_ml.o kgraph_map_rb.o kgraph_map_rb_map.o kgraph_map_rb_part.o kgraph_map_st.o kgraph_store.o library_arch.o library_arch_f.o library_arch_build.o library_arch_build_f.o library_common_f.o library_geom.o library_geom_f.o library_graph.o library_graph_f.o library_graph_base.o library_graph_base_f.o library_graph_check.o library_graph_check_f.o library_graph_coarsen.o library_graph_coarsen_f.o library_graph_color.o library_graph_color_f.o library_graph_io_chac.o library_graph_io_chac_f.o library_graph_io_habo.o library_graph_io_habo_f.o library_graph_io_mmkt.o library_graph_io_mmkt_f.o library_graph_io_scot.o library_graph_io_scot_f.o library_graph_map.o library_graph_map_f.o library_graph_map_io.o library_graph_map_io_f.o library_graph_map_view.o library_graph_map_view_f.o library_graph_order.o library_graph_order_f.o library_graph_part_ovl.o library_graph_part_ovl_f.o library_mapping.o library_memory.o library_memory_f.o library_mesh.o library_mesh_f.o library_mesh_graph.o library_mesh_graph_f.o library_mesh_io_habo.o library_mesh_io_habo_f.o library_mesh_io_scot.o library_mesh_io_scot_f.o library_mesh_order.o library_mesh_order_f.o library_order.o library_parser.o library_parser_f.o library_random.o library_random_f.o library_strat.o library_version.o library_version_f.o mapping.o mapping_io.o mesh.o mesh_check.o mesh_coarsen.o mesh_graph.o mesh_induce_sepa.o mesh_io.o mesh_io_habo.o mesh_io_scot.o order.o order_check.o order_io.o parser.o parser_ll.o parser_yy.o vgraph.o vgraph_check.o vgraph_separate_bd.o vgraph_separate_df.o vgraph_separate_es.o vgraph_separate_fm.o vgraph_separate_gg.o vgraph_separate_gp.o vgraph_separate_ml.o vgraph_separate_st.o vgraph_separate_th.o vgraph_separate_vw.o vgraph_separate_zr.o vgraph_store.o vmesh.o vmesh_check.o vmesh_separate_fm.o vmesh_separate_gg.o vmesh_separate_gr.o vmesh_separate_ml.o vmesh_separate_zr.o vmesh_separate_st.o vmesh_store.o wgraph.o wgraph_check.o wgraph_part_fm.o wgraph_part_gg.o wgraph_part_gp.o wgraph_part_ml.o wgraph_part_rb.o wgraph_part_st.o wgraph_part_zr.o wgraph_store.o
echo libscotch.dylib
libscotch.dylib
clang -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ  -c library_error.c -o library_error.o
libtool -lm -lz -lpthread -lbz2 -dynamic -install_name /usr/local/Cellar/scotch/6.0.4_4/lib/libscotcherr.dylib -undefined dynamic_lookup -o libscotcherr.dylib library_error.o
ld: file not found: 
fatal error: /Library/Developer/CommandLineTools/usr/bin/libtool: internal link edit command failed
make[2]: *** [libscotcherr.dylib] Error 1
make[1]: *** [scotch] Error 2
make: *** [scotch] Error 2

#### The complete command that you issued:
brew install scotch

#### Gist with output of `brew doctor`:
Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/702542719aee59c0d825fa1d8cbfefd7

#### Output of `brew config`:
HOMEBREW_VERSION: 1.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91ab116ace7f4f97d3440190463c93be9ec6d675
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 74e296a95a0b3cdaf148d3258d1468a8724feab0
Core tap last commit: 32 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by cpraveen** [comment]
I am also facing this issue.

**Comment by mtmcgurn** [comment]
I have getting the same error.  Has anyone found a solution?

**Comment by cpraveen** [comment]
I could not solve it. Since I dont really need scotch and only need Trilinos, I tried to install Trilinos --without-scotch but that also failed.
