### ISSUE TITLE
Where is statismo.rb? It's listed on the Homebrew website under homebrew-science, but isn't available for installation

### ISSUE THREAD

**Issue by rohanvijayan** [Homebrew/homebrew-science#6390]
### Indicate troubleshooting steps taken

- [ X] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by iMichka** [comment]
Hi. Statismo has been removed, see https://github.com/Homebrew/homebrew-science/pull/6273

>This formula has been broken since some time,
as it fails to build with newest hdf5 and boost versions.
> Upstream has no time/interest to take care of this for the moment.

Of course you could volunteer to fix the build and see if upstream would accept some patches, and we would be willing to consider adding it back if needed.
