### ISSUE TITLE
LAMMPS test returns errors 

### ISSUE THREAD

**Issue by yosyp** [Homebrew/homebrew-science#6392]
#### Brief summary of issue:
Installing LAMMPS using [these steps](http://lammps.sandia.gov/download.html#homebrew) returns errors, namely (see gist link below for full output):
```
==> python -c from lammps import lammps ; lammps().file('/usr/local/share/lammps/bench/in.lj')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lammps
Error: homebrew/science/lammps: failed
Failed executing: python -c from\ lammps\ import\ lammps\ ;\ lammps().file('/usr/local/share/lammps/bench/in.lj')
```

#### The complete command that you issued:
1. `brew tap homebrew/science`
2. `brew install lammps`
3. `brew test lammps -v` gives [the following output](https://gist.github.com/yosyp/a5c5ac260e78e4512366c06f0307105b).

#### Link output by `brew gist-logs <formula>`:
[https://gist.github.com/anonymous/61eb14df52fc3c1685a375afee8532ee](https://gist.github.com/anonymous/61eb14df52fc3c1685a375afee8532ee)

**Comment by snoopdee** [comment]
I think the issue you note here is the same issue I mentioned elsewhere, but I'm not a regular here so I don't know how to commit the change.  Hopefully someone else can do it!

See comment here: https://github.com/Homebrew/homebrew-science/commit/d176b57c5ecdc03a21bafb18b47378bc93cc22d8

It seems there was an error in how to include user-contributed packages.  Changing line 196 in lammps.rb from

    system "make", "yes-" + pkg if build.include? "enable-" + pkg

to

    system "make", "yes-" + pkg if build.include? "with-" + pkg

seemed to do the trick.

**Comment by sjackman** [comment]
`lammps` is up for migration to Homebrew/core. Consider submitting this formula to https://github.com/Homebrew/homebrew-core. This repository Homebrew/science is being retired at the end of this year. See https://github.com/Homebrew/homebrew-science/issues/6331

**Comment by sjackman** [comment]
Contributing this formula to Homebrew/core would also build a binary bottle for it, which would likely resolve your issue.

Here's the top ten installation options:
```
 1 | homebrew/science/lammps                                   | 1,202 |  72.41%
 2 | homebrew/science/lammps --HEAD                            |   285 |  17.17%
 3 | homebrew/science/lammps --without-mpi                     |    31 |   1.87%
 4 | homebrew/science/lammps --with-user-reaxc                 |    26 |   1.57%
 5 | homebrew/science/lammps --with-user-misc                  |    25 |   1.51%
 6 | homebrew/science/lammps --with-user-colvars --with-user-r |    17 |   1.02%
 7 | homebrew/science/lammps --enable-user-reaxc --enable-user |    11 |   0.66%
 8 | homebrew/science/lammps --with-user-colvars --with-user-e |    11 |   0.66%
 9 | homebrew/science/lammps --HEAD --without-mpi              |    10 |   0.60%
10 | homebrew/science/lammps --with-user-colvars               |    10 |   0.60%
```
