### ISSUE TITLE
CalculiX 2.13 available

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew-science#6406]
Heads up that 2.13 was released recently.
I'm not on OSX but I volunteer for a project that uses CalculiX as a dependency.
CC @costerwi 

Edit: http://www.dhondt.de/ccx_2.13.src.tar.bz2

**Comment by costerwi** [comment]
Thanks! Just requested on #6417

**Comment by luzpaz** [comment]
Awesome! Thanks! Closing this ticket then :+1:
