### ISSUE TITLE
Revisions for Open MPI 3.0.0 needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-science#6425]
- [ ] abinit
- [ ] alpscore
- [ ] bless
- [x] ~~cerulean~~ does not depend on MPI. Its dependency abyss depends on MPI.
- [ ] cp2k
- [ ] dealii
- [ ] dida
- [ ] dl_poly_classic
- [ ] elemental
- [ ] exabayes
- [ ] garli
- [ ] getdp
- [ ] ipopt
- [x] ~~kollector~~ does not depend on MPI. Its dependency `abyss` depends on MPI.
- [ ] lammps
- [ ] lis
- [ ] meme
- [ ] mumps
- [ ] p4est
- [ ] parallel-netcdf
- [ ] parmetis
- [ ] pastix
- [ ] petsc
- [x] ~~rampart~~ does not depend on MPI. Its dependency `abyss` depends on MPI.
- [ ] ray
- [ ] scotch
- [ ] scotch5
- [ ] slepc
- [ ] superlu_dist
- [x] ~~trans-abyss~~ does not depend on MPI. Its dependency abyss depends on MPI.
- [ ] trilinos
- [ ] zoltan

CC @sjackman @iMichka @jonchang

**Comment by iMichka** [comment]
Building the linux bottle for openmpi right now: https://github.com/Linuxbrew/homebrew-core/pull/4832

**Comment by sjackman** [comment]
`cerulean`, `kollector`, and `trans-abyss` do not depend on MPI. Their dependency `abyss` depends on MPI.

**Comment by szhang0513** [comment]
which one I should reinstall？I dont quite understand what you mean, can you explain it more.

**Comment by sjackman** [comment]
```sh
brew reinstall -s lammps
```
