### ISSUE TITLE
make error: brew cdo from homebrew-science: error: cannot initialize return object of type 'int' with an rvalue of type 'void'

### ISSUE THREAD

**Issue by linyenheng** [Homebrew/homebrew-science#6427]
ran: brew install homebrew/science/cdo --with-grib2
had checked all of the troubleshooting
Could someone help this? Thank you so much

### Bug reports / build errors:
==> Installing cdo from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://code.mpimet.mpg.de/attachments/download/15187/cdo-1.9.0.tar.gz
Already downloaded: /Users/parichart/Library/Caches/Homebrew/cdo-1.9.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/cdo/1.9.0 LIBS=-lhdf5 --with-netcdf=/usr/local/opt/netcdf --with-hdf5=/usr/local/opt/hdf5 --with-szlib=/usr/local/opt/szip --with-grib_api=/usr/local/opt/grib-api --with-jasper=/usr/local/opt/jasper
==> make install
Last 15 lines from /Users/parichart/Library/Logs/Homebrew/cdo/02.make:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__mutex_base:17:
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:278:10: error: cannot initialize return object of type 'int' with an rvalue of type 'void'
 return pthread_cond_wait(__cv, __m);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./pthread_debug.h:29:40: note: expanded from macro 'pthread_cond_wait'
#define  pthread_cond_wait(a, b)       Pthread_cond_wait(__func__, a, b)
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/bin/sh ../libtool  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I.  -I../libcdi/src -I/usr/local/opt/grib-api/include -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include   -g -O2  -D_THREAD_SAFE -pthread -c -o libcdo_la-sellist.lo `test -f 'sellist.cc' || echo './'`sellist.cc
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/grib-api/include -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c sellist.cc  -fno-common -DPIC -o .libs/libcdo_la-sellist.o
6 errors generated.
make[1]: *** [libcdo_la-pipe.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/grib-api/include -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c sellist.cc -o libcdo_la-sellist.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/grib-api/include -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c modules.cc -o libcdo_la-modules.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html

**Comment by pgierz** [comment]
Has there been any progress with this? I am having the same problem...

If it helps, I am using:

```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables

pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 9.0.1.0.1.1506734476
volume: /
location: /
install-time: 1509568771
groups: com.apple.FindSystemFiles.pkg-group 
```

and

```
$ gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

since this looks like the origin of the problem is from XCode Command Line Tools, I suspect Apple changed something with the new version of the operating system. Just a guess though...

**Comment by rejonpardenilla** [comment]
I'm having the same problem.

I ran: `brew tap homebrew/science` and `brew install cdo`

and I get:

~~~
==> Installing cdo from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://code.mpimet.mpg.de/attachments/download/15187/cdo-1.9.0.tar.gz
Already downloaded: /Users/daniel/Library/Caches/Homebrew/cdo-1.9.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/cdo/1.9.0_1 LIBS=-lhdf5 --with-netcdf=/usr/local/opt/netcdf --with-hdf5=/usr/local/opt/hdf5 --with-szlib=/usr/local/opt/szip
==> make install
Last 15 lines from /Users/daniel/Library/Logs/Homebrew/cdo/02.make:
  return pthread_cond_wait(__cv, __m);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./pthread_debug.h:29:40: note: expanded from macro 'pthread_cond_wait'
#define  pthread_cond_wait(a, b)       Pthread_cond_wait(__func__, a, b)
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c sellist.cc  -fno-common -DPIC -o .libs/libcdo_la-sellist.o
/bin/sh ../libtool  --tag=CXX   --mode=compile clang++ -std=gnu++11 -DHAVE_CONFIG_H -I.  -I../libcdi/src -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include   -g -O2  -D_THREAD_SAFE -pthread -c -o libcdo_la-process.lo `test -f 'process.cc' || echo './'`process.cc
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c process.cc  -fno-common -DPIC -o .libs/libcdo_la-process.o
6 errors generated.
make[1]: *** [libcdo_la-pipe.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c sellist.cc -o libcdo_la-sellist.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c process.cc -o libcdo_la-process.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../libcdi/src -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/szip/include -g -O2 -D_THREAD_SAFE -pthread -c modules.cc -o libcdo_la-modules.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html
~~~

OS: High Sierra v10.13 (17A405)

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ilovezfs** [comment]
This should now be fixed if you `brew update` and `brew upgrade`
