### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib

### ISSUE THREAD

**Issue by jianqixi** [Homebrew/homebrew-science#6433]
Hi all, I tried to install lammps via home-brew. But I met one issue when running lammps.
It shows that:
dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib
  Referenced from: /usr/local/Cellar/lammps/2017.08.11/bin/lammps
  Reason: image not found

the brew gist-logs lammps returns:
https://gist.github.com/ad38ce94b0728efe1b1657ca93b78de4

Would you like to give me some suggestions. 

Thank you very much!

### Indicate troubleshooting steps taken

- [Y] Ran `brew update` and retried your prior step?
- [Y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [Y] Checked that a similar issue hasn't already been filed?
- [Y] Looked up the software bug tracker if reporting a build error?
- [Y] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

Hi, I have one issue on the mpi library. I tried to use the home-brew to install lammps. Everything seems ok. But when used "brew test lammps -v", it shows that "Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib   
Referenced from: /usr/local/Cellar/lammps/2017.08.11/bin/lammps
Reason: image not found"
I have checked online, it seems like to be the reason of different version of open-mpi. Does anybody meet the same problem before. Would you like to give me some suggestions. Thank you very much!

**Comment by McNoggins** [comment]
I'm getting a similar error using superlu.

> dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib
  Referenced from: /usr/local/opt/superlu_dist/lib/libsuperlu_dist.5.dylib
  Reason: image not found

**Comment by jianqixi** [comment]
I think it may be due to the compatibility for open-mpi in home-brew and the usage of openmpi of the software. I tried to install without using home-brew now.

**Comment by szhang0513** [comment]
I meet the same error，do you solve it？

**Comment by McNoggins** [comment]
I think the way to solve it is to rebuild from source: `brew reinstall --build-from-source <package>`

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-science/issues/6425.

**Comment by szhang0513** [comment]
how can I solve it by #6425, I cant understand, thx

**Comment by ilovezfs** [comment]
It is a known issue. This is a duplicate. Everything on the list in #6425 is broken and will remain broken until they're rebuilt. You can do so locally using brew reinstall as was mentioned above.

**Comment by szhang0513** [comment]
Ok ,I just add a ln -s /usr/local/opt/open-mpi/lib/libmpi.40.dylib /usr/local/opt/open-mpi/lib/libmpi.20.dylib
lammps can work! Its more convenient

**Comment by ilovezfs** [comment]
That is a bad idea and likely to break not only the software but also brew.
