### ISSUE TITLE
Error: inreplace failed while installing LAMMPS 

### ISSUE THREAD

**Issue by jacqueline-nguyen** [Homebrew/homebrew-science#6436]
**_I'm installing LAMMPS on Mac OS Sierra (10.12.6) but the error shows up:__**
==> Checking out branch master
Error: inreplace failed
Makefile.lammps.python2:
  expected replacement of "python_SYSLIB = $(shell which python2-config > /dev/null 2>&1 && python2-config --ldflags || (which python-config > /dev/null 2>&1 && python-config --ldflags || :))" with "python_SYSLIB = -ldl -framework CoreFoundation -undefined dynamic_lookup"

**_I've tried_ ** brew doctor
**_and fixed the problem below by_ ** brew prune

Unexpected header files:
  /usr/local/include/openbabel-2.0/openbabel/math/matrix3x3.h
  /usr/local/include/openbabel-2.0/openbabel/math/vector3.h

**_It however does't work_**
Please help me! 
Many thanks

**Comment by snoopdee** [comment]
I got something similar and fixed it by updating python: "brew upgrade python"
