### ISSUE TITLE
Issue installing GATK 

### ISSUE THREAD

**Issue by biomendi** [Homebrew/homebrew-science#6449]
### Indicate troubleshooting steps taken

- [ Yes ] Ran `brew update` and retried your prior step?
- [ Yes ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ No ] Checked that a similar issue hasn't already been filed?
- [ No ] Looked up the software bug tracker if reporting a build error?
- [ No ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

$ brew install gatk

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
bchunk                               faas-cli                             grafana                              itstool

==> Installing gatk from homebrew/science
==> Downloading https://github.com/broadgsa/gatk-protected/archive/3.6.tar.gz
Already downloaded: /Users/server_mac1/Library/Caches/Homebrew/gatk-3.6.tar.gz
==> mvn package -Dmaven.repo.local=${PWD}/repo
Last 15 lines from /Users/server_mac1/Library/Logs/Homebrew/gatk/01.mvn:
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

READ THIS: https://docs.brew.sh/Troubleshooting.html

#### The complete command that you issued: 

brew install gatk

#### Gist with output of `brew doctor`:

Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/68499adb844116ffcf7e0cfffde1a243

#### Output of `brew config`:

HOMEBREW_VERSION: 1.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d9b9d4f1cfbef8a7a271ceecddad2a52eea1a55
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: 24-core 64-bit arrandale
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 9.0.1, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: N/A

### Formula Requests: NO

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
>Java: 9.0.1, 1.6.0_65-b14-468

```
brew cask install java8
```
and then set `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`

**Comment by ilovezfs** [comment]
I see this doesn't have any bottles … that same change will have to be made in the formula unfortunately.

**Comment by biomendi** [comment]
Thanks for your answer. Could the formulae be modified?

I tried `brew cask install java8` and it says:

    Error: Cask 'java8' is unavailable: No Cask with this name exists. 

So I tried `export JAVA_HOME=$(/usr/libexec/java_home -v 9.0)` and it gives me another error:

brew install gatk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
No changes to formulae.

==> Installing gatk from homebrew/science
==> Downloading https://github.com/broadgsa/gatk-protected/archive/3.6.tar.gz
Already downloaded: /Users/server_mac1/Library/Caches/Homebrew/gatk-3.6.tar.gz
==> mvn package -Dmaven.repo.local=${PWD}/repo
Last 15 lines from /Users/server_mac1/Library/Logs/Homebrew/gatk/01.mvn:
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.667 s
[INFO] Finished at: 2017-11-13T14:51:21+01:00
[INFO] Final Memory: 18M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gatk-aggregator: Could not resolve dependencies for project org.broadinstitute.gatk:gatk-aggregator:pom:3.6: Could not find artifact com.sun:tools:jar:1.4.2 at specified path /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gatk-aggregator

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Issue installing GATK  https://github.com/Homebrew/homebrew-science/issues/6449

**Comment by ilovezfs** [comment]
as a workaround, once you install the java8 cask, until it's fixed you can
```
sudo mv /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk ~/
```
and then it should use java8.

**Comment by biomendi** [comment]
The building process works under java8, thank you!
