### ISSUE TITLE
Feature request: eccodes

### ISSUE THREAD

**Issue by raybellwaves** [Homebrew/homebrew-science#6450]
https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home

I can have a stab at this is nobody gets round to it.

**Comment by raybellwaves** [comment]
I'm having a first look at this as this will be my first PR.

If there any benefit to creating a bottle rather than creating from source?

The https://github.com/Homebrew/homebrew-science/blob/master/cdo.rb installation will probably be similar for eccodes so I can use that as a template. It seems this is installed from source with bottle currently disabled (perhaps it's best to download from source first then create a bottle)

**Comment by raybellwaves** [comment]
I hope you don't mind me leaving notes here as I'm learning how to contribute to homebrew and questions pop-up as well as documenting my experience. I can put them elsewhere if need be.

When doing `brew install --interactive eccodes` it unzips the tarball but doens't untar it.
https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-2.5.0-Source.tar.gz?api=v2 becomes eccodes-2.5.0-Source.tar. I don't suppose there is a way for brew install to untar as well as so it becomes eccodes-2.5.0-Source? (tar xvf)

**Comment by raybellwaves** [comment]
I tried to do `brew install --verbose --debug eccodes` in another terminal and it said 
`Error: Operation already in progress for eccodes.formula
Another active Homebrew process is already using eccodes.formula.
Please wait for it to finish or terminate it to continue`
Do I close out of that terminal to close the interactive session?

**Comment by raybellwaves** [comment]
I just noticed doing `brew create https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-2.5.0-Source.tar.gz?api=v2` put the formula in homebrew-core but I probably wanted it in homebrew-science

**Comment by iMichka** [comment]
Hi. Yes, homebrew-science will disappear soon (end of December). Your best bet would be to submit this to homebrew-core (of course the package needs to be notable enough), or host it in your own tap. I'll close this issue but feel free to comment on it if you have any question.
