### ISSUE TITLE
vigra build fails on high sierra

### ISSUE THREAD

**Issue by nextstopsun** [Homebrew/homebrew-science#6462]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
[ 46%] Built target vigranumpy_sampling
make[1]: *** [vigranumpy/src/core/CMakeFiles/vigranumpy_analysis.dir/all] Error 2
make: *** [all] Error 2
```
#### Brief summary of issue:
Build fails 

#### The complete command that you issued:
`brew install --with-openexr --with-python homebrew/science/vigra`
#### Gist with output of `brew doctor`:
```
brew doctor
Your system is ready to brew.
```
#### Link output by `brew gist-logs <formula>`:
[https://gist.github.com/17960ee84af0605c74852b2dad241a0b](https://gist.github.com/17960ee84af0605c74852b2dad241a0b)
#### Output of `brew config`:
```
brew config
HOMEBREW_VERSION: 1.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 236b0172306a6f4b233d374fcc20adce5c3e3261
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4ed830a5d86db63d67afa6cafbacce018268376e
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9.0.1
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.1.0.0.1.1508540944
X11: 2.7.11 => /opt/X11
```
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
`vigra` is up for migration to Homebrew/core. Consider submitting this formula to https://github.com/Homebrew/homebrew-core. This repository Homebrew/science is being retired at the end of this year. See https://github.com/Homebrew/homebrew-science/issues/6331

Contributing this formula to Homebrew/core would also build a binary bottle for it, which would likely resolve your issue.

Here's the top four installation options:
```
1 | homebrew/science/vigra                                       | 106 |  82.81%
2 | homebrew/science/vigra --with-python --with-openexr          |  12 |   9.38%
3 | homebrew/science/vigra --without-test                        |   5 |   3.91%
4 | homebrew/science/vigra --without-test --with-python          |   2 |   1.56%
```
