### ISSUE TITLE
petsc fails to configure on osx 10.13.2

### ISSUE THREAD

**Issue by Myromax** [Homebrew/homebrew-science#6492]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [NA] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-sundials-dir=/usr/local/opt/sundials did not work
*******************************************************************************
```

#### Brief summary of issue:
petsc fails to configure and blames sundials, which is installed in the above directory.

#### The complete command that you issued:
```
brew install petsc
```

#### Gist with output of `brew doctor`:
```
$ brew doctor
Your system is ready to brew.
```
#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/Myromax/00a1a7d5e2b5ded3bdf189827deb7505

#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: f42d8acde3907b90ea32cef01445744288984a4c
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3b3ea08da0cfb485264f116bd958ba6144898c4d
Core tap last commit: 23 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

**Comment by sjackman** [comment]
`petsc` is up for migration to Homebrew/core. Consider submitting this formula to https://github.com/Homebrew/homebrew-core. This repository Homebrew/science is being retired at the end of this year. See https://github.com/Homebrew/homebrew-science/issues/6331

Contributing this formula to Homebrew/core would also build a binary bottle for it, which would likely resolve your issue.

Here's the top five installation options:
```
 1 | homebrew/science/petsc                                      | 555 |  80.20%
 2 | homebrew/science/petsc --with-openblas                      |  23 |   3.32%
 3 | homebrew/science/petsc --without-sundials                   |  22 |   3.18%
 4 | homebrew/science/petsc --with-complex --with-debug --with-o |  18 |   2.60%
 5 | homebrew/science/petsc --with-complex                       |  10 |   1.45%
```
