### ISSUE TITLE
Paraview 5.3.0_3 failing to build on MacOS 10.13.2-x86_64

### ISSUE THREAD

**Issue by keevee09** [Homebrew/homebrew-science#6501]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
Paraview is failing to build on MacOS 10.13.2-x86_64 via homebrew.
#### The complete command that you issued:
brew update && brew upgrade
#### Gist with output of `brew doctor`:
https://gist.github.com/keevee09/8c6f403ddf529a1ad3c544c59f451d65
#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/keevee09/8d74cd2b576def3aafa537420ff99aad
#### Output of `brew config`:
HOMEBREW_VERSION: 1.4.1-3-g426c998
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 426c998ff513a182aced1a5a4c4b7ec6f9203288
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d8a64440c3944f1dfde4f1bb228d7218868c636f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /Users/tony/perl5/perlbrew/perls/perl-5.24.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/tony/.rbenv/shims/ruby => /Users/tony/.rbenv/versions/2.4.0/bin/ruby
Java: 9.0.1, 1.8.0_66, 1.8.0_45
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
`paraview` is up for migration to Homebrew/core. Consider submitting this formula to https://github.com/Homebrew/homebrew-core. This repository Homebrew/science is being retired at the end of this year. See https://github.com/Homebrew/homebrew-science/issues/6331

Submitting this formula to Homebrew/core would also build a bottle, and likely resolve your installation issue.

```
install events in the last 90 days for paraview
================================================================================
1 | homebrew/science/paraview                                    | 236 |  90.77%
2 | homebrew/science/paraview --with-mpi                         |  20 |   7.69%
3 | homebrew/science/paraview --HEAD --with-mpi                  |   2 |   0.77%
4 | homebrew/science/paraview --HEAD                             |   1 |   0.38%
5 | homebrew/science/paraview --without-qt                       |   1 |   0.38%
```
