### ISSUE TITLE
Problem with  homebrew/science/rstudio-server 1.1.383_1

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Homebrew/homebrew-science#6506]
@randy3k @ilovezfs   I get the following error.  Not sure what's wrong?

```
==> Upgrading 1 outdated package, with result:
homebrew/science/rstudio-server 1.1.383_1
==> Upgrading homebrew/science/rstudio-server 
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/rstudio/rstudio/archive/v1.1.383.tar.gz
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server-1.1.383.tar.gz
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/gin-1.5.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--gin-1.5.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/gwt-2.7.0.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--gwt-2.7.0.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/junit-4.9b3.jar
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--junit-4.9b3.jar
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/selenium-java-2.37.0.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--selenium-2.37.0.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/selenium-server-standalone-2.37.0.jar
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--selenium-server-2.37.0.jar
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/chromedriver-mac
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--chromedriver-mac-mac
==> Downloading https://s3.amazonaws.com/rstudio-dictionaries/core-dictionaries.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--dictionaries-dictionaries.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/mathjax-26.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--mathjax-26.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/pandoc/1.19.2.1/macos/pandoc-1.19.2.1.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--pandoc-1.19.2.1.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/pandoc/1.19.2.1/macos/pandoc-citeproc-0.10.4.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--pandoc-citeproc-0.10.4.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/libclang-3.5.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--libclang-3.5.zip
==> Downloading https://s3.amazonaws.com/rstudio-buildtools/libclang-builtin-headers.zip
Already downloaded: /Users/e/Library/Caches/Homebrew/rstudio-server--libclang-builtin-headers-builtin.zip
==> cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release -DRSTUDIO_USE_LIBCXX=Yes -DRSTUDIO_USE_SYSTEM_BOOST=Yes -DBOOST_ROOT=/usr/local/opt/boost -DBOOST_INCLUDEDIR=/usr/local/opt/
==> make install
Last 15 lines from /Users/e/Library/Logs/Homebrew/rstudio-server/02.make:
[  6%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/BoostErrors.cpp.o
[  6%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/BrowserUtils.cpp.o
/tmp/rstudio-server-20171221-31223-9lbch/rstudio-1.1.383/src/cpp/core/BoostErrors.cpp:151:47: error: use of undeclared identifier 'get_system_category'; did you mean 'system_category'?
      return error_code(e.get_native_error(), get_system_category()) ;
                                              ^~~~~~~~~~~~~~~~~~~
                                              system_category
/usr/local/include/boost/system/error_code.hpp:196:47: note: 'system_category' declared here
    BOOST_SYSTEM_DECL const error_category &  system_category() BOOST_SYSTEM_NOEXCEPT;
                                              ^
[  6%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/ConfigUtils.cpp.o
1 error generated.
make[2]: *** [src/cpp/core/CMakeFiles/rstudio-core.dir/BoostErrors.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/cpp/core/CMakeFiles/rstudio-core.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by randy3k** [comment]
It seems that rstudio does not like the new version of boost.

**Comment by randy3k** [comment]
Maybe related to this https://github.com/boostorg/system/commit/829a1320a7bef3ade74d6691fdcfe72e0b6917e9

**Comment by randy3k** [comment]
As homebrew-science is deprecating, I have moved the rstudio-server formula to https://github.com/randy3k/homebrew-rstudio-server
However, it doesn't provide bottles, which means users have to build rstudio-server from source.

@ilovezfs 
If I want to migrate the formula out of homebrew-science, do I just add my tap to [`tap_migrations.json`](https://github.com/Homebrew/homebrew-science/blob/master/tap_migrations.json) and remove `rstudio-server.rb`?

**Comment by ilovezfs** [comment]
We're not pointing tap migrations at third party taps but we can remove the formula in favor of your tap and let people find it.

**Comment by sjackman** [comment]
> However, it doesn't provide bottles, which means users have to build rstudio-server from source.

It is possible to build bottles in third party taps, though still a bit tricky. For an example, see…
https://github.com/Linuxbrew/homebrew-bio/blob/master/.circleci/config.yml

I can help answer questions if you're interested in building bottles.

**Comment by sjackman** [comment]
Migrated `rstudio-server` to https://github.com/randy3k/homebrew-rstudio-server/blob/master/rstudio-server.rb by @randy3k

**Comment by randy3k** [comment]
@sjackman 
Sadly, circle ci doesn't offer free service for macos. Is there any reference for travis? 

I cannot figure out how does this `test-bot` magic works? I made some local changes to the formula and commit. Then I run
```
> brew test-bot --skip-setup --tap=randy3k/rstudio-server -v
Homebrew/homebrew-test-bot a40c2ba (test-bot: fix remote GitHub username.)
ARGV: --skip-setup --tap=randy3k/rstudio-server -v
Homebrew/brew 1.4.1-9-gbd471d6b (Merge pull request #3589 from sjackman/shims-scm)
Homebrew/homebrew-core 837e6b2d4 (gcc@5: update 5.5.0 bottle.)
randy3k/rstudio-server origin/master 190fba3 (boost keg_only)
randy3k/rstudio-server HEAD 285dea3 (test)
==> brew readall --aliases randy3k/rstudio-server
```

The formula was not installed and no bottle was built.

**Comment by sjackman** [comment]
> Sadly, circle ci doesn't offer free service for macos. Is there any reference for travis?

I believe CircleCI offers macOS builds for free now: https://circleci.com/build-environments/xcode/

The last time I looked at doing building bottles with TravisCI, I determined that it was impossible to securely upload artifacts from fork pull requests without exposing the credentials. That may have changed now. CircleCI stores the artifacts on their AWS S3.

**Comment by sjackman** [comment]
`test-bot` reads a bunch of CI environment variables. If those variables are not set, it doesn't do much by default. Try though…

```sh
brew test-bot -v --skip-setup --tap=randy3k/rstudio-server rstudio-server
```

**Comment by sjackman** [comment]
I'd be really curious to hear if you can get it working on TravisCI though. Are you planning to build bottles for macOS, or Linux, or both?

**Comment by randy3k** [comment]
I don't think circie ci offers free macos service. Did homebrew-bio pay for the mac service?

<img width="1015" alt="screen shot 2017-12-21 at 2 30 17 pm" src="https://user-images.githubusercontent.com/1690993/34271709-81a5aa80-e65b-11e7-9b71-cc1d0833e5c1.png">

<img width="1098" alt="screen shot 2017-12-21 at 2 28 43 pm" src="https://user-images.githubusercontent.com/1690993/34271662-4832c09e-e65b-11e7-9ab2-62983437a882.png">

**Comment by sjackman** [comment]
Go to https://circleci.com/pricing/ and scroll down to `What if I am building open-source?`

> We offer a total of four free linux containers ($2400 annual value) for open-source projects. Simply keeping your project public will enable this for you!

> We also offer the Seed plan free for OS X open-source projects. Contact us at billing@circleci.com for access. If you are building a bigger open-source project and need more resources, let us know how we can help you!

**Comment by sjackman** [comment]
@randy3k I created the GitHub organization https://github.com/brewsci to house taps that have been migrated out of Homebrew/science. Would you be interested in moving your `rstudio-server` tap to Brewsci?

**Comment by randy3k** [comment]
As the new version of boost, `boost v1.66`, breaks `rstudio-server`, we will also need a versioned formula `boost@1.63`. I have been trying to submit PRs to homebrew core on versioned `boost` formula, but it seems that the core doesn't like to host versioned `boost` for just another formula.
Do you think we could/should ship a versioned boost formula at `brewsci`? (We could call it `boost@rstudio-server` if `boost@1.66` should be avoided.)

If we can resolve the issue of `boost`, I am happy to move it to `brewsci`.

**Comment by sjackman** [comment]
Does `rstudio-server` link against the boost libraries, or only use the header files? Many packages only use the header files. You can use `brew linkage rstudio-server` to determine whether the libraries are used. If it doesn't link against the libraries, it'd be pretty ease to use `boost` 1.63 as a resource inside the `rstudio-server` formula, rather than putting it in it's own formula.

**Comment by randy3k** [comment]
Unfortunately it doesn't work, rstudio-server requires [boost libraries](https://github.com/rstudio/rstudio/blob/c34c3b07423f5ba11b356826a70daa0f7d2c282f/src/cpp/core/CMakeLists.txt#L335-L339) to be linked statically at build time.

**Comment by randy3k** [comment]
I wonder how test-bot push the bottle commit https://github.com/Linuxbrew/homebrew-bio/commit/5c5a83904532dd50e73f6183e1254aa923274abd to github automatically. I understand that the commit was generated by `brew bottle --merge --write *.json` after collecting the artifacts, but I fail to see the mechanism to push the bottle commit to `master` branch automatically after a PR is merged. For instance, I cannot find any related jobs in https://circleci.com/gh/linuxbrew/homebrew-bio which is related to the commit.

**Comment by randy3k** [comment]
See if I understand the procedure correctly now:

When the PR was created, CircleCI runs `test-bot` and creates a  bottle commit and pushes that to LinuxbrewTestBot fork. Then, a maintainer will locally run `brew pull --bottle <PR URL>` to pull the PR and the bottle commit. Finally, the formula and bottle are updated by pushing the local commits to the formula repo.

**Comment by randy3k** [comment]
@sjackman do you anticipate for me to move the whole tap to Brewsci or to move the formulas to a repo, e.g `Brewsci/homebrew-science`?
