### ISSUE TITLE
Error when tapping: invalid syntax in tap

### ISSUE THREAD

**Issue by EricFromCanada** [Homebrew/homebrew-science#6513]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
Getting an error when tapping: "Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/Aliases/samtools@1.6"

Presumably this is because the above file points to `samtools.rb`, but only `samtools@0.1.rb` exists. (xref d0ef8b5)

#### The complete command that you issued:
```
==> Tapping homebrew/science
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 625, done.
remote: Compressing objects: 100% (620/620), done.
remote: Total 625 (delta 0), reused 28 (delta 0), pack-reused 0
Receiving objects: 100% (625/625), 536.45 KiB | 59.00 KiB/s, done.
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/Aliases/samtools@1.6
Error: Cannot tap homebrew/science: invalid syntax in tap!
```

**Comment by sjackman** [comment]
Thanks for the bug report, Eric.
Fixed by c36b2e103c23fd9898d7f55a7c3113a2ddb6fcc1. Thanks, @ilovezfs.
