### ISSUE TITLE
Warning: Dependency boost built with a different C++ standard

### ISSUE THREAD

**Issue by adamrork** [Homebrew/homebrew-science#6568]
This is my first time on GitHub, and I'm a bit new to Homebrew, so I preemptively apologize if I'm asking this in the wrong place or in an incorrect manner.

I just saw that Trinity was updated to 2.5.1, and when running `$ brew upgrade`, received the following warning related to dependency "boost".

`Warning: homebrew/science/trinity dependency boost was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.`

I tested Trinity via `$ ./runMe.sh`, and all seemed to work fine; there was no runtime error that Trinity detected, fatal or otherwise, anyway, and the files seemed to write properly. Is this a warning that can functionally be ignored, or could it cause serious, hidden calculation errors that would warrant me finding a fix for this? If the latter is the case, is there a best way to go about this?

I'd be happy to add any other necessary information.

**Comment by ilovezfs** [comment]
Homebrew's Boost is now built with C++11 and GCC (used here for OpenMP) still links libstdc++. Nothing to be concerned about.

**Comment by ilovezfs** [comment]
```
iMac-TMP:homebrew-science joe$ brew linkage trinity
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/lib/gcc/7/libgcc_s.1.dylib (gcc)
  /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib (gcc)
  /usr/local/opt/gcc/lib/gcc/7/libstdc++.6.dylib (gcc)
iMac-TMP:homebrew-science joe$ brew linkage express
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/boost/lib/libboost_atomic-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_chrono-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_date_time-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_program_options-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_system-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_thread-mt.dylib (boost)
  /usr/local/opt/protobuf/lib/libprotobuf.15.dylib (protobuf)
iMac-TMP:homebrew-science joe$ 
```
Note that trinity itself is not even linked to Boost and eXpress installs no libraries.

```
iMac-TMP:~ joe$ find $(brew --prefix express)/
/usr/local/opt/express/
/usr/local/opt/express//.brew
/usr/local/opt/express//.brew/express.rb
/usr/local/opt/express//INSTALL_RECEIPT.json
/usr/local/opt/express//LICENSE
/usr/local/opt/express//README
/usr/local/opt/express//bin
/usr/local/opt/express//bin/express
iMac-TMP:~ joe$
```
```

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ brew deps --tree trinity
homebrew/science/trinity
├── express
│   ├── bamtools
│   ├── boost
│   ├── protobuf
│   └── gperftools
├── bowtie2
│   └── tbb
├── jellyfish
├── trimmomatic
├── samtools
│   └── htslib
│       └── xz
├── htslib
│   └── xz
└── gcc
    ├── gmp
    ├── libmpc
    │   ├── gmp
    │   └── mpfr
    │       └── gmp
    ├── mpfr
    │   └── gmp
    └── isl
        └── gmp

iMac-TMP:~ joe$ 
```

**Comment by ilovezfs** [comment]
This will shut it up from now on: https://github.com/Homebrew/homebrew-science/commit/36be1b91208516b00cc2e3d704b2a87441cd31fc

**Comment by adamrork** [comment]
Thanks for the great information, @ilovezfs! I just reinstalled trinity-- that fixed the warning!

`My-MacBook-Pro:~ username$ brew reinstall trinity
==> Reinstalling homebrew/science/trinity 
==> Downloading https://homebrew.bintray.com/bottles-science/trinity-2.5.1.high_
Already downloaded: /Users/username/Library/Caches/Homebrew/trinity-2.5.1.high_sierra.bottle.tar.gz
==> Pouring trinity-2.5.1.high_sierra.bottle.tar.gz
==> Caveats
Trinity only officially supports Java 1.8. To skip this check pass the
option --bypass_java_version_check to Trinity. A specific Java version may
also be set via environment variable:
  JAVA_HOME=`/usr/libexec/java_home -v 1.8`
==> Summary
🍺  /usr/local/Cellar/trinity/2.5.1: 1,141 files, 68.2MB`
